### ISSUE TITLE
[M1A01] - Sobre os títulos.

### ISSUE THREAD

**Issue by Bilusca** [da2k/curso-reactjs-ninja#1]
@fdaciuk seria interessante, após o título de Modulo e EP. colocar o nome da aula. Algo como "M1#A01 - Ementa do Curso". 

Parabéns pelo conteúdo.

**Comment by fdaciuk** [comment]
Boa! Vou fazer isso @Bilusca! :D 
Valeu pela dica o/

**Comment by fdaciuk** [comment]
Feito @Bilusca! Obrigado mais uma vez pela sugestão :heart: :dancer: :sparkles:
