### ISSUE TITLE
Test componente com image

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#100]
Escreva aqui sua dúvida

@fdaciuk

Eu tenho um componente header que recebe um logo só que quando tento rodar o yarn test da erro de character

componente

```
'use strict'
import React from 'react'
import logo from './logo.jpg'

const Header = () => (
  <header>
    <div className='header__logo'>
      <img src={logo} />
    </div>
  </header>
)

export default Header
```

```
/Users/coisadedev/Documents/projetos/leroy-merlin/src/components/header/logo.jpg: Unexpected character '�' (1:0)
      > 1 | ����JFIF��C
          | ^
```

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Você só precisa dizer para o Jest como tratar imports que não sejam arquivos JS =)

Pra isso, você precisa fazer algumas configurações.

Adicione essas linhas no seu `package.json`:
https://github.com/fdaciuk/workflow-reactjs/blob/master/package.json#L16-L19

Só adicione a extensão das imagens que precisar, junto com o `.css` ali, separando as extensões por um pipe. Vai ficar assim:

```json
"^.+\\.(css|jpg)$": "<rootDir>/config/CSSStub.js"
```

Ae você adiciona esse arquivo no diretório `config/CSSStub.js`:

https://github.com/fdaciuk/workflow-reactjs/blob/master/config/CSSStub.js

Dessa forma, sempre que o Jest encontrar um import de CSS ou imagem, ele vai exportar somente um objeto vazio e não vai dar erro =)

**Comment by hjdesigner** [comment]
Funcionou, vlw novamente pela ajuda :)

**Comment by fdaciuk** [comment]
Show \o/
Qualquer coisa, só avisar =)
