### ISSUE TITLE
MRW#02 - Erro Comando Webpack

### ISSUE THREAD

**Issue by samuelbrehm** [da2k/curso-reactjs-ninja#103]
Continuo com problemas no Webpack. Instalei globalmente, tudo certo, mas na hora de usar o comando `webpack` o terminal apresenta uma lista de opções e não gera o bundle.

<img width="1638" alt="captura de tela 2018-03-24 as 10 55 16" src="https://user-images.githubusercontent.com/6319555/37865655-7a16fe8a-2f5e-11e8-9b3c-e1b7ab1e99a6.png">

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! Respondi na issue #97 =)
