### ISSUE TITLE
Dúvida em como inserir uma imagem no projeto

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#104]
Fernando caso eu queira inserir uma imagem em um componente (Por exemplo: a logo do reactflix onde esta escrito o nome do app), qual a maneira que vc recomenda ? importar a imagem diretamente no componente e referenciar na tag da imagem ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Você é quem decide =)
Tendo o loader do webpack corretamente configurado, ele vai se virar pra exportar a imagem da melhor forma possível =)

**Comment by fdaciuk** [comment]
Oi @willianrssi! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by willianrssi** [comment]
Obrigado @fdaciuk, estou importando a imagem no componente e referenciando na tag img.

```
import imageLogo from 'images/logo.png'
...
<img src={imageLogo} alt='Logo da aplicação' />
...
```

**Comment by fdaciuk** [comment]
Show! É uma forma :D
