### ISSUE TITLE
Como vc configurou o CSS no modulo 01?

### ISSUE THREAD

**Issue by samuelbrehm** [da2k/curso-reactjs-ninja#108]
Escreva aqui sua dúvida

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! No módulo 01 ele foi só adicionado manualmente na `index.html`, que serve o JS do React:
https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m01/github-app/index.html#L6

No módulo 2 você irá aprender outras formas de utilizar CSS em aplicações React =)

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! Ficou clara a resposta? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
