### ISSUE TITLE
Tamanho do build de produção com o módulo do firebase

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#109]
Boa noite Fernando, estava dando uma olhada em como ficou o tamanho do build de produção do reactflix, notei que o módulo firebase ocupa um tamanho considerável, tem alguma alternativa ou tática para otimizar isso? 

Desde já agradeço

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Ficou clara a resposta? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by willianrssi** [comment]
Obrigado pela resposta @fdaciuk ficou clara sua resposta.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, conte comigo =)
