### ISSUE TITLE
Dúvida sobre Curso de React

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#11]
Fala @fdaciuk, beleza? Estava pensando em comprar esse curso porém esta dando como ESGOTADO. Já era? Como funciona isso ? Valeu, abraço!

**Comment by fdaciuk** [comment]
Olá @gabrielferreiraa! =)
Desculpe, eu esqueci de atualizar a data. Agora está certo xD
Obrigado por reportar :dancer: :dancer: :sparkles:
