### ISSUE TITLE
Media queries com styled-components

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#110]
Olha eu aqui de novo Fernando =) rsrs

Então gostaria de saber de você alguma dica para usar as media queries no projeto que utiliza styled-components, ou se você conhece alguma outra alternativa melhor para isso.

o que eu vi pesquisando foi a utilização de um arquivo que exporta os tamanhos já definidos (tipo um arquivo 'device.js' no 'utils' com um objeto contendo os tamanhos) e no componente importa ele para escrever usando o styled normalmente , é isso mesmo? alguma dica?

obrigado mais uma vez por tirar minhas dúvidas

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Se você tiver os tamanhos das media queries que vai usar já definidos pode fazer dessa forma sim =)

**Comment by fdaciuk** [comment]
Oi @willianrssi! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by willianrssi** [comment]
Boa tarde @fdaciuk ,
Sem dúvidas professor, obrigado pela ajuda

**Comment by fdaciuk** [comment]
Show \o/
Qualquer coisa me avise :D
