### ISSUE TITLE
Recursividade de calda e performance no JS

### ISSUE THREAD

**Issue by 0v3lh4** [da2k/curso-reactjs-ninja#111]
Fernando,

Estou no modulo de testes com JEST e surgiu uma dúvida quanto a performance da implementação de map e filter recursivo. Por curiosidade, fiz testes com o map com recursividade e sem... e os resultados foram que ao trabalhar com muitas interações o map com recursividade é mais lento que o map sem recursividade, fora que o aumento de memória é visível nas interações acima de 5000 mil e que em mais de 8000 mil gera erro de "Maximum call stack size exceeded".

Pesquisando, encontrei que o javascript não suporta TCO (tail call optmization) e por este motivo a recursividade com muitas interações vai estourar ou ser mais lenta. Esse é o motivo? 
E em linguagens que são de fato funcionais, no mesmo cenário, a interação com recursividade seria mais lenta que em uma interação com for?

Exemplo dos timers:

    Chamadas:
    mapRecursive(Array.from(new Array(X)), (item, index) => ((index * 100) / 10));
    map(Array.from(new Array(X)), (item, index) => ((index * 100) / 10));

    Timer: map recursivo 100 interações: 0.001ms
    Timer: map sem recursividade 100 interações: 0ms

    Timer: map recursivo 1000 interações: 0.015ms
    Timer: map sem recursividade 1000 interações: 0ms

    Timer: map recursivo 5000 interações: 0.361ms
    Timer: map sem recursividade 5000 interações: 0.003ms

    Timer: map recursivo 8000 interações: 0.949ms
    Timer: map sem recursividade 8000 interações: 0.002ms

@fdaciuk

**Comment by fdaciuk** [comment]
Ainda não, mas vou deixar anotado aqui pra fazer um exemplo e mostrar como trabalhar com grandes cargas de dados em aplicações React :)

**Comment by fdaciuk** [comment]
Oi @0v3lh4! Ficou clara a resposta? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
