### ISSUE TITLE
PropTypes

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#114]
Recebi essa mensagem:
lowPriorityWarning.js:38 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

Isso ocorre porque constumo usar o import do PropTypes da seguinte forma:
import React, { PropTypes } from 'react'

e a documentação indicada na console fala para usarmos:
import PropTypes from 'prop-types'

Está correto a forma que estou importando?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Isso foi mudado à partir da versão 15.5 do React. No decorrer do curso, você vai ver essas atualizações, mas para acompanhar o curso corretamente, usando os mesmos códigos que eu usei sem problemas, por favor, siga as recomendações [desse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) =)

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Ficou clara a resposta? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by Alexandre1202** [comment]
Ficou claro sim.
Obrigado pela atenção

**Comment by fdaciuk** [comment]
Não por isso =)
Qualquer coisa, só avisar =)
