### ISSUE TITLE
Modulo 02/ Storybook

### ISSUE THREAD

**Issue by Srdeveloperpika** [da2k/curso-reactjs-ninja#115]
Olá, quando eu fui instalar o Storybook, instalei como na Aula 30 do Modulo2, ele deu erro ao dar o comando. Fui na documentação e lá eu constatei que o Getstorybook foi deprecado, e que agora tinha que ser instalado o "@storybook/cli", então instalei ele e seguiu tudo certinho, mas quando vou rodar o     
 "npm run storybook" aparece isso no terminal:
" > start-storybook -p 6006

info @storybook/react v3.4.1
info
info => Loading custom .babelrc
info => Loading custom webpack config (extending mode).
webpack built 0d6a8072896aa88614da in 8592ms
Hash: 0d6a8072896aa88614da
Version: webpack 3.11.0
Time: 8592ms
                       Asset     Size  Chunks                    Chunk Names
    static/manager.bundle.js  2.82 MB       0  [emitted]  [big]  manager
    static/preview.bundle.js  1.77 MB       1  [emitted]  [big]  preview
static/manager.bundle.js.map   3.5 MB       0  [emitted]         manager
static/preview.bundle.js.map  2.13 MB       1  [emitted]         preview
                  index.html  2.09 kB          [emitted]
                 iframe.html  2.09 kB          [emitted]
 [302] ./node_modules/@storybook/react/dist/server/config/polyfills.js 113 bytes {0} {1} [built]
 [697] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/addons.js ./node_modules/@storybook/core/dist/client/manager/index.js 52 bytes {0} [built]
 [698] ./node_modules/@storybook/react/dist/server/addons.js 105 bytes {0} [built]
 [699] ./node_modules/@storybook/addon-actions/register.js 38 bytes {0} [built]
 [723] ./node_modules/@storybook/addon-links/register.js 38 bytes {0} [built]
 [725] ./node_modules/@storybook/core/dist/client/manager/index.js 423 bytes {0} [built]
 [993] ./node_modules/@storybook/core/dist/client/manager/provider.js 3.35 kB {0} [built]
 [995] multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js 64 bytes {1} [built]
 [996] ./node_modules/@storybook/react/dist/server/config/globals.js 105 bytes {1} [built]
 [997] ./node_modules/webpack-hot-middleware/client.js?reload=true 7.35 kB {1} [built]
 [998] ./node_modules/querystring-es3/index.js 127 bytes {1} [built]
[1003] ./node_modules/webpack-hot-middleware/client-overlay.js 2.21 kB {1} [built]
[1008] ./node_modules/webpack-hot-middleware/process-update.js 4.33 kB {1} [built]
[1009] ./.storybook/config.js 640 bytes {1} [built]
[1084] ./stories .stories.js$ 183 bytes {1} [built]
    + 1078 hidden modules

ERROR in   TypeError: Cannot read property 'request' of undefined

  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:34

  - ExternalModuleFactoryPlugin.js:46 next
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8

  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7

  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5

  - NormalModuleFactory.js:236 applyPluginsAsyncWaterfall
    [workflow-reactjs]/[core]/[webpack]/lib/NormalModuleFactory.js:236:4

  - Tapable.js:260 NormalModuleFactory.applyPluginsAsyncWaterfall
    [workflow-reactjs]/[tapable]/lib/Tapable.js:260:70

  - NormalModuleFactory.js:220 NormalModuleFactory.create
    [workflow-reactjs]/[core]/[webpack]/lib/NormalModuleFactory.js:220:8

  - Compilation.js:401 semaphore.acquire
    [workflow-reactjs]/[core]/[webpack]/lib/Compilation.js:401:18

  - Semaphore.js:16 Semaphore.acquire
    [workflow-reactjs]/[core]/[webpack]/lib/util/Semaphore.js:16:4

  - Compilation.js:400 Compilation._addModuleChain
    [workflow-reactjs]/[core]/[webpack]/lib/Compilation.js:400:18

  - Compilation.js:488 Compilation.addEntry
    [workflow-reactjs]/[core]/[webpack]/lib/Compilation.js:488:8

  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [workflow-reactjs]/[webpack]/lib/SingleEntryPlugin.js:22:15

  - Tapable.js:293 Compiler.applyPluginsParallel
    [workflow-reactjs]/[tapable]/lib/Tapable.js:293:14

  - Compiler.js:499 applyPluginsAsync.err
    [workflow-reactjs]/[core]/[webpack]/lib/Compiler.js:499:9

  - Tapable.js:195 Compiler.applyPluginsAsyncSeries
    [workflow-reactjs]/[tapable]/lib/Tapable.js:195:46

  - Compiler.js:492 Compiler.compile
    [workflow-reactjs]/[core]/[webpack]/lib/Compiler.js:492:8

ERROR in   TypeError: Cannot read property 'request' of undefined

  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:34

  - ExternalModuleFactoryPlugin.js:46 next
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8

  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7

  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [workflow-reactjs]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5

  - NormalModuleFactory.js:236 applyPluginsAsyncWaterfall
    [workflow-reactjs]/[core]/[webpack]/lib/NormalModuleFactory.js:236:4

  - Tapable.js:260 NormalModuleFactory.applyPluginsAsyncWaterfall
    [workflow-reactjs]/[tapable]/lib/Tapable.js:260:70

  - NormalModuleFactory.js:220 NormalModuleFactory.create
    [workflow-reactjs]/[core]/[webpack]/lib/NormalModuleFactory.js:220:8

  - Compilation.js:401 semaphore.acquire
    [workflow-reactjs]/[core]/[webpack]/lib/Compilation.js:401:18

  - Semaphore.js:16 Semaphore.acquire
    [workflow-reactjs]/[core]/[webpack]/lib/util/Semaphore.js:16:4

  - Compilation.js:400 Compilation._addModuleChain
    [workflow-reactjs]/[core]/[webpack]/lib/Compilation.js:400:18

  - Compilation.js:488 Compilation.addEntry
    [workflow-reactjs]/[core]/[webpack]/lib/Compilation.js:488:8

  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [workflow-reactjs]/[webpack]/lib/SingleEntryPlugin.js:22:15

  - Tapable.js:293 Compiler.applyPluginsParallel
    [workflow-reactjs]/[tapable]/lib/Tapable.js:293:14

  - Compiler.js:499 applyPluginsAsync.err
    [workflow-reactjs]/[core]/[webpack]/lib/Compiler.js:499:9

  - Tapable.js:195 Compiler.applyPluginsAsyncSeries
    [workflow-reactjs]/[tapable]/lib/Tapable.js:195:46

  - Compiler.js:492 Compiler.compile
    [workflow-reactjs]/[core]/[webpack]/lib/Compiler.js:492:8 ".

@fdaciuk

**Comment by Srdeveloperpika** [comment]
Constatei que é pq o storybook está pegando o meu webpack.config e não usando o dele como no vídeo. Mas não sei como resolver!

**Comment by fdaciuk** [comment]
Oi @Srdeveloperpika! Esse é um problema com a diferença de versão do storybook atual com a versão usada no curso =)

Para usar a versão usada nas aulas, veja aqui:
https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#m2a43

Mais pra frente vamos fazer a atualização dessa dependência, fique tranquilo! Então pode usar essa versão mais antiga, apenas para conseguir acompanhar o curso. A forma de usar o storybook continua a mesma, foram poucas mudanças da versão antiga para a atual, e essas mudanças eu mostro em aulas futuras =)

**Comment by Srdeveloperpika** [comment]
A versão do storybook é essa no fim da página? Pois eu não cheguei na aula 43 ainda.

**Comment by Srdeveloperpika** [comment]
Aula 30, você apresenta o storybook, parei nessa.

**Comment by fdaciuk** [comment]
Boa @Srdeveloperpika! Atualizei o arquivo de dependências =)
Mas a instalação é a mesma :)

**Comment by Srdeveloperpika** [comment]
Grato, aí. Irei instalar e ver se resolve, posto aqui na issue o resultado.

**Comment by Srdeveloperpika** [comment]
Apareceu isso quando eu dei o getstorybook:   
 getstorybook - the simplest way to add a storybook to your project.

 • Detecting project type. ✓
 • Adding storybook support to your "React" app. ✓
 • Preparing to install dependencies. ✓


 • Installing dependencies. ✖

     An error occurred while installing dependencies.


   ╭─────────────────────────────────────────╮
   │                                         │
   │     Update available 1.6.1 → 1.7.0      │
   │   Run npm i -g getstorybook to update   │
   │                                         │
   ╰─────────────────────────────────────────╯

**Comment by Srdeveloperpika** [comment]
Grato demais Fernando, tudo deu certo. Só pra constar esse erro das dependências eu corrigi assim. fui na lib do Getstorybook e lá alterei uma linha que continha 'npm' e troquei pra npm.cmd. Se alguém apresentar o mesmo erro é isso.

**Comment by fdaciuk** [comment]
Legal @Srdeveloperpika! Que bom que deu tudo certo =)

Uma dica: não é legal modificar diretamente arquivos na `node_modules`, pois eles são gerados automaticamente, e você pode perder sua atualização sempre que precisar atualizar ou instalar outra dependência =)

Provavelmente o erro aconteceu por conta da versão do NPM que você tem instalada na sua máquina =)

Se quiser usar a mesma versão que foi usada no curso, só dar uma olhada [aqui](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/react-webpack/README.md#vers%C3%A3o-do-nodejs) =)

Qualquer dúvida, só avisar!
