### ISSUE TITLE
duvida sobre o constructor 

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#116]
fernando poderia me explicar melhor sobre o método **constructor**  não consegui compreender o porque do super ali
```
class App extends Component {
  constructor () {
    super()
    this.state = { }
  }
}
```

@fdaciuk

**Comment by Srdeveloperpika** [comment]
Quando a pessoa chama o super(), você está chamando o construtor padrão (sem os parâmetros) da superclasse, e o Construtor (Constructor) segundo a orientação de objetos é executado quando a pessoa instância uma classe. Desculpa me intrometer hehe

**Comment by fdaciuk** [comment]
Obrigado @Srdeveloperpika =)
@angelilton é como o @Srdeveloperpika comentou: o `super` representa a **superclasse**, que seria a classe da qual está se extendendo algumas funcionalidades (no caso, o `super` representa o `Component`).

E você só precisa executar o `super` para ter acesso ao `this` dentro do `constructor` da sua `class`. Ou seja: sempre que precisar do `this.props` ou `this.state` dentro do `constructor`, vc vai precisar chamar o `super` antes =)

**Comment by angelilton** [comment]
há sim agora entendi obg

**Comment by fdaciuk** [comment]
Legal! Qualquer dúvida, só avisar =)
