### ISSUE TITLE
M2#08 - jest na pratica - watch interativo

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#118]
Olá Fernando.

Tudo bom?

Estou reproduzindo os exemplos de testes do sum e div mas já conferi para fazer exatamente como você fez porém o report é diferente entre eles.

Veja:
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |       50 |      100 |                   |
 div.js   |        0 |        0 |        0 |        0 |                   |
 sum.js   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|

Veja que a div.js indica 0% para tudo e no seu exemplo consta 100% para quase tudo apenas com a implementação abaixo:

`'use strict'

export default () => {}

---x----x---x---

'use strict'

import { expect } from 'chai'
import div from './div'

it('div should should be a function', () => {
  expect(div).to.be.a('function')
})

`

Pensando em TDD onde devemos começar pelos testes e o fazer o desenvolvimento em seguida e de forma incremental eu vejo interessante que o reporte esteja 0% para todos os critérios de cobertura e o watch está mostrando justamente dessa forma, mas sabe me dizer porque no seu caso apresentou 100% para alguns indicadores do report mesmo com um código desse:
`export default () => {}`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! O Jest usa o Istanbul por baixo dos panos para fazer o _coverage_ do código.
Essa ideia de mostrar 0% ou 100% provavelmente foi alguma atualização na lib.

Como você deve estar usando uma versão mais recente do Jest, esse problema já está resolvido para o seu caso =)

**Comment by Alexandre1202** [comment]
Excelente! Obrigado.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
