### ISSUE TITLE
M1 Dados carregarem ao carregar a página

### ISSUE THREAD

**Issue by Lucas-Simbiose** [da2k/curso-reactjs-ninja#119]
Estou fazendo uma página utilizando a estrutura muito parecida ao app feito neste Módulo 1.
Eu tenho dois botões que são passadas as funções de clique de cima para baixo (Assim como você fez, a mesma função é usada para dois botões, onde eu passo o argumento assim como você faz com o 'type').
Eu gostaria que o primeiro botão fosse acionado ao carregar a página.
Fazendo uma analogia, onde você usa getRepos(type) eu utilizo getUserLeagues(league_type), onde você passa a função como prop no render com o getRepos e getStarred chamando a função com parâmetros diferentes eu também faço. Tentei chamar o método getUserLeagues('manager') utilizando o ComponentDidMount ou o ComponentWillMount mas não consegui fazer com que os dados fossem carregados como se eu tivesse clickado em um dos botões.
Utilizei alguns console.log para ver o fluxo, e pelo que vi, o log dentro da getUserLeagues antes do return(e) aparece, mas log dentro deste return não, como poderia resolver isso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Lucas-Simbiose! A ideia seria usar o `componentDidMount` mesmo! Preciso ver seu código para entender o que pode estar acontecendo de errado =)

Consegue compartilhar em um repositório aqui no GitHub?

**Comment by fdaciuk** [comment]
Oi @Lucas-Simbiose! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
