### ISSUE TITLE
Dúvidas Standard e Lints

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#12]
Boa tarde @fdaciuk , beleza? Uma dúvida bem rápida. O uso do _standard_ como _preLoader_, elimina a necessidade de usar ponto e virgula em toda minha aplicação? Pois estou com algumas mensagens de error de _semicolon_, creio que seja por conta do ponto e vírgula. Existe algum parâmetro para ele ignorar isso? Pois prefiro trabalhar com ponto e vírgula. Ou procuro outro lint? Valeu!
![image](https://cloud.githubusercontent.com/assets/17201177/21860320/4f1693f2-d817-11e6-90f7-6583d94c8777.png)

**Comment by gabrielferreiraa** [comment]
OBS: Acabei de ver aqui você falando do _semistandard_. Já adicionei o semi-standard ao `webpack.config`, tudo funcionando 10)%. Valeu e desculpe hehe

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa! Se você prefere usar `;`, mas quer continuar usando as outras opções do `standard`, você tem algumas alternativas:

1) Você pode usar o [`semi-standard`](https://github.com/Flet/semistandard')
2) Você pode pegar a [configuração padrão](https://github.com/feross/eslint-config-standard) do standard, e usar o [`eslint`](http://eslint.org/) mesmo para modificar o que quiser;
3) Fazer sua própria configuração usando o `eslint` ou usar qualquer outra configuração já existente =)

**Comment by fdaciuk** [comment]
> OBS: Acabei de ver aqui você falando do semistandard. Já adicionei o semistandard ao webpack.config, tudo funcionando 10)%. Valeu e desculpe hehe

Ah legal =)

Qualquer dúvida só avisar :D

**Comment by kaioduarte** [comment]
Deixa eu ressuscitar a issue rapidinho xD

@gabrielferreiraa O que você usou de loader pro `semistandard`? Só encontrei esse [módulo](https://github.com/wombleton/semistandard-loader) e não funcionou.

Valeu \o
