### ISSUE TITLE
Não renderiza o componente no servidor

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#120]
Escreva aqui sua dúvida

@fdaciuk

Olá!

To montando um projetinho para estudar que pesquisa videos no youtube.

Com o yarn start ou se eu rodo o python -m SimpleHTTPServer na pasta dist ele roda normalmente.

Mais quando subo os arquivos no github page ele não renderiza o componente e nem da erro rsrs.

https://henriquemelanda.com.br/view-youtube/
https://github.com/hjdesigner/teste-front-end

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Como você está colocando em um diretório, tem algumas configurações extras que você precisa fazer:

- No seu `webpack.config` de produção, você precisa adicionar, no `output`, o `publicPath` com o caminho que você vai usar no servidor (no caso `/view-youtube`). E para dev, pode deixar ele com `/`.

- Ainda no `webpack.config` de prod, mude o caminho do `dist`, adicionando `'view-youtube'` no final, logo após o `'dist'`. Assim ele vai gerar a versão de produção em `dist/view-youtube`. Ao fazer isso, você pode rodar o server python no diretório dist, e acessar no seu browser `localhost:9001/view-youtube`, assim como vai ficar no GitHub :)

- Lá na configuração do `Router`, você precisa passar uma prop `basename` para ele, também com a opção `/view-youtube` para prod, e `/` para dev. (pode testar usando a variável de ambiente `process.env.NODE_ENV`, que faz parte do Node.js, mas quando o webpack processar o arquivo, ele faz com que esse valor fique estático para ser usado no browser =)

- Uma outra dica é mover o `Router` para o `index.js`, pois ele funciona como o `Provider` do Redux, então faz mais sentido deixar ele no `index.js` ao invés de deixá-lo no `App.js` :)

Fazendo isso, tudo deve funcionar corretamente :)

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
