### ISSUE TITLE
M2#A75 Erro no storybook.

### ISSUE THREAD

**Issue by MarlonFlorencio** [da2k/curso-reactjs-ninja#121]
Olá @fdaciuk

Após refatorar o boilerplate para utilizar o Webpack 2, você faz um teste para verificar se o storybook está funcioando corretamente. No vídeo(minuto 3:40) está funcionando porém quando faço o teste com a minha versão, o storybook não funciona.

Fui no boilerplate e fiz checkout da sua [versão](https://github.com/fdaciuk/workflow-reactjs/tree/8628231887c0f84c5ccc9efe036fd25722fd6438) daquele dia, instalei as dependências e está apresentando o mesmo erro. 

No Firefox, o erro é "SyntaxError: import declarations may only appear at top level of a module" provavelmente no arquivo "storybook/config.js"

No Chrome, o erro é "Uncaught SyntaxError: Unexpected token {" no arquivo "storybook/config.js".

Espero ter passado as informações necessárias.

Abraço

**Comment by MarlonFlorencio** [comment]
boa tarde @fdaciuk 

No vídeo M2#A81, você explica como resolver esse problema. só que na aplicação do async/away apareceu um novo problema. **"Parsing error: Unexpected token componentDidMount  null"**

Se puder dar uma ajudar, eu agradeço.

Abraço

**Comment by fdaciuk** [comment]
Oi @MarlonFlorencio! Você tem o seu projeto rodando em algum lugar, onde está com esse erro? Um repo aqui no GitHub, talvez? Acho que é mais fácil pra tentar chegar em uma solução =)

**Comment by MarlonFlorencio** [comment]
@fdaciuk,

Boa noite professor, acabei passando mt desse ponto e vou fechar essas issue, qualquer coisa eu volto. 

Abraço

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer coisa, só avisar =)
