### ISSUE TITLE
M2#A110 - Dúvida this.timer e error

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#123]
Professor tenho uma dúvida, Nessa parte

```
componentDidUpdate () {
    clearInterval(this.timer)
    this.timer = setTimeout(this.handleSave, 1000)
  }

  componentWillUnmount() {
    clearInterval(this.timer)
  }
```
O senhor instanciou o `this.timer` e não precisou declarar ele para funcionar como se fosse uma variável padrão. 

Queria entender o por quê que funcionou dessa forma e eu entendo que se tivesse colocado dentro de uma função teria que executar `timer` sem precisar fazer ex:
```
  componentDidUpdate () {
    clearInterval(this.timer)
    this.timer = setTimeout(this.handleSave, 1000)
  }
```

E no meu código tá vindo dois erros professor
![image](https://user-images.githubusercontent.com/1054454/39519905-04489af2-4ddf-11e8-972a-36ef290dd21d.png)

O link para o repo: [link](https://github.com/lucianoMeusCursos/ReactNinjaExample/tree/master/my-examples/m02/applications/markdown-editor)

@fdaciuk

**Comment by lucianobarauna** [comment]
Sim eu dei uma olhada na propriedade depois com calma novamente rs.
E coloquei ela no onlClick assim `onlClick={() => foo}` e passou a funcionar de boa.

**Comment by fdaciuk** [comment]
haha! Legal =)
Qualquer dúvida avisa ae :)
