### ISSUE TITLE
M1#A14

### ISSUE THREAD

**Issue by rrgomide** [da2k/curso-reactjs-ninja#124]
Primeiramente, parabens pelo curso! Muito bem feito e explicado!

Minha dúvida é sobre as keys. Há alguma recomendação da equipe do React para o tipo de dados da key, ou seja, a performance do diff do VirtualDOM melhora se definirmos numbers (índice do array) ao invés de strings, por exemplo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rrgomide! Strings seriam sempre o melhor tipo de dados para esse caso, prefira sempre elas =)
Índices de arrays você só deve usar em casos onde o seu array não terá mudanças (elementos mudando de posição, ou novos sendo adicionados, ou ainda algum item sendo removido).

Para todos os outros casos, prefira sempre strings =)

**Comment by victorferreira** [comment]
@fdaciuk, e qual seria a alternativa quando temos um array de strings como do exemplo e o array é alterado? Existe alguma outra alternativa de key que não seja o array[index] nesse caso?

P.S.: [random id's](https://github.com/facebook/react/issues/1342#issuecomment-39230939) não parecem ser a solução também.

**Comment by fdaciuk** [comment]
Oi @victorferreira! Se o array contiver valores que poderão ser alterados no futuro (adicionar, remover, mudar posição), o ideal é sempre, antes de usar esse array no render, transformar cada elemento do array em um objeto com um ID próprio. ID's randômicos acabam sendo piores que usar o índice do array mesmo =)

**Comment by fdaciuk** [comment]
Oi @rrgomide e @victorferreira! Vou fechar a issue, mas se ainda ficou alguma dúvida, eu reabro, ok? =)
