### ISSUE TITLE
MRW#06 Não consigo fazer funcionar usando o import e export

### ISSUE THREAD

**Issue by Santiael** [da2k/curso-reactjs-ninja#125]
Ocorre o erro 'Uncaught SyntaxError: Unexpected identifier' no bundle.js
Segui passo-a-passo as instruções do vídeo,  e instalei as dependências segundo a aula do futuro.

![image](https://user-images.githubusercontent.com/31523464/40239570-c923595c-5a8c-11e8-9003-a32601888757.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Santiael! Consegue subir seu projeto aqui no GitHub pra eu dar uma olhada? =)

Se quiser também, pode dar uma olhada em como deveria estar o seu projeto dessa aula olhando o histórico aqui do repositório:

Diretório da aula `MRW#06`: https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-06

**Comment by Santiael** [comment]
Assim que chegar em casa upo no github... obrigado

**Comment by guilhermealbuquerquegit** [comment]
Como conseguiu resolver, estou enfrentando o mesmo problema.

**Comment by fdaciuk** [comment]
Oi @guilhermealbuquerquegit! Compare o seu projeto com o link que passei acima. Nesse link tem a estrutura de como deveria estar o seu projeto na aula 06 do módulo de React + webpack =)

**Comment by Santiael** [comment]
@guilhermealbuquerquegit , eu acredito que no meu caso eu instalei o babel, ou alguma outra dependência de forma errada... tudo que eu fiz foi refazer a instalação das dependências. Recomendo que dê uma olhada no seu package.json e veja se está tudo de acordo.

**Comment by Santiael** [comment]
@guilhermealbuquerquegit , no meu caso, acredito que instalei o babel, ou alguma outra dependência, de forma errada... tudo que eu fiz foi refazer a instalação das dependências. Recomendo que dê uma olhada no seu package.json e veja se está tudo de acordo.

**Comment by guilhermealbuquerquegit** [comment]
@Santiael vou fazer isso cara, vlw.

@fdaciuk eu comparei, não está totalmente idêntico ao seu, pois algumas coisas mudaram da época que as aulas foram gravadas pra atualmente. Mas ai segue o link do meu projeto https://github.com/guilhermealbuquerquegit/react-learn

**Comment by fdaciuk** [comment]
@guilhermealbuquerquegit ainda que algumas coisas mudaram, eu deixei as versões das dependências exatas para o momento em que as aulas tinham sido gravadas. Então pode deixar as configurações iguais as que eu mostrei que vai funcionar =)

Com o passar do curso, eu vou mostrando como fazer a atualização das dependências e do código das configurações, ok? =)

Para o seu caso, você pode até manter a última versão do React, ReactDOM e CreateReactClass se quiser, mas as dependências de desenvolvimento devem estar nas versões que foram apresentadas:
https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/react-webpack/mrw-06/package.json

Fazendo isso, seu código vai rodar sem problemas ;)

**Comment by fdaciuk** [comment]
Oi @Santiael! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
