### ISSUE TITLE
Modulo 04

### ISSUE THREAD

**Issue by Joaoh3326** [da2k/curso-reactjs-ninja#126]
Fala mestre, gostaria de saber se o modulo 4 vai demorar pra sair ? , se sim, vai demorar muito ?, porque se for demorar aproveito pra refazer o curso e treinar mais um pouco hehehehe.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Joaoh3326! Estou começando a gravar as aulas, até sexta-feira eu já libero as primeiras =)

**Comment by fdaciuk** [comment]
Show @Joaoh3326! Vá praticando bastante que vai ajudar :D
