### ISSUE TITLE
Erro react-hot-loader

### ISSUE THREAD

**Issue by leandrino** [da2k/curso-reactjs-ninja#127]
Estou com esse erro aqui no hot-loader:
```
Failed to compile.

multi react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./src/index
Module not found: Error: Can't resolve 'react-hot-loader/webpack' in '/usr/src/app'
```
as dependências são: 
```
  "devDependencies": {
    "autoprefixer": "^8.3.0",
    "babel-core": "^6.23.1",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^22.1.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.22.0",
    "chai": "^4.0.2",
    "clean-webpack-plugin": "^0.1.15",
    "cross-env": "^5.0.1",
    "css-hot-loader": "^1.3.5",
    "css-loader": "^0.28.4",
    "deep-freeze": "^0.0.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "extract-text-webpack-plugin": "^3.0.0-rc.2",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^22.1.1",
    "node-sass": "^4.7.2",
    "react-hot-loader": "next",
    "react-test-renderer": "^16.2.0",
    "standard": "^11.0.1",
    "standard-loader": "^6.0.1",
    "style-loader": "^0.21.0",
    "webpack": "^4.6.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-dashboard": "^1.1.1",
    "webpack-dev-server": "^3.1.3"
  },
  "dependencies": {
    "add": "^2.0.6",
    "babel-runtime": "^6.23.0",
    "fs": "^0.0.1-security",
    "popmotion": "^8.1.24",
    "preact": "^8.2.7",
    "preact-compat": "^3.17.0",
    "prop-types": "^15.6.0",
    "ramda": "^0.25.0",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-intl": "^2.4.0",
    "react-notification-system": "^0.2.17",
    "react-pose": "^1.6.4",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "redux": "^4.0.0",
    "redux-thunk": "^2.2.0",
    "styled-components": "^3.2.6",
    "uuid": "^3.2.1"
  },
```

alguém tem uma luz do que possa ser? já fiz alguns procedimentos que encontrei por ai e nada funcionou.

@fdaciuk

**Comment by manzolirch** [comment]
Opa @leandrino, vamos tentar resolver esse problema enquanto o prof não chega haha
Pelo que vi você instalou as dependências todas atualizadas, em vez de seguir o guia de versão de dependências (https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), não entendi porque no react-hot-loader, está "next" em vez da própria versão..

https://github.com/gaearon/react-hot-loader/issues/569
Achei essa Issue que fala desse problema do "next" algumas pessoas conseguiram resolver isso atualizando o react-hot-loader, da uma olhada :)

**Comment by leandrino** [comment]
opa @manzolirch, valeu, essa issue que vc linkou eu tinha tentado também..hehe

bom, resovi simplesmente adicionando as dependências no .babelrc e no loarder de js, funcionou blzinha.

sobre o webpack config eu estava com este : 
```
'use strict'

const webpack = require('webpack')
const common = require('./common')

const HtmlPlugin = require('html-webpack-plugin')
const DashboardPlugin = require('webpack-dashboard/plugin')

module.exports = {
  devtool: 'source-map',
  mode: 'development',

  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    common.entry.main
  ],

  output: Object.assign({}, common.output, {
    filename: ['name'].js,
    publicPath: '/'
  }),

  plugins: [
    new webpack.optimize.ModuleConcatenationPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new DashboardPlugin(),

    new HtmlPlugin(common.htmlPluginConfig)
  ],

  module: {
    rules: [
      common.standardPreLoader,
      common.jsLoader,
      common.cssLoader,
      common.fileLoader,
      common.urlLoader
    ]
  },

  resolve: common.resolve
}
```
Tentei também com essas dependências instaladas com o webpack config de dev do [repo do mestre](https://github.com/fdaciuk/workflow-reactjs/blob/master/webpack/dev.config.js) mas tbm deu erro.

Talvez tenha algumas tretas com as versões que estou usando x configuração.. vou começar uma nova configuração aqui e ver se da bom, qq coisa comento aqui novamente.

**Comment by fdaciuk** [comment]
Oi @leandrino! O seu problema provavelmente é por conta das versões do webpack e react-hot-loader (óbvio haha)!

Para tentar ajudar a resolver, seria interessante se você conseguisse compartilhar seu projeto, pra gente colocar pra rodar e ir testando.

O repo do boilerplate que estamos fazendo no curso ainda não está com o webpack 4. Pra ser sincero, nem cheguei a testar essa versão com o HMR ainda, então não vou saber te apontar qual o problema nesse momento =)

Pretendo fazer essa atualização em breve =)

Até lá, teve um carinha que mandou um PR com um update para o react-hot-loader v4, dá uma olhada pra ver se ele pode funcionar com a sua config atual + webpack 4:

https://github.com/fdaciuk/workflow-reactjs/pull/12/files

**Comment by leandrino** [comment]
Olha mestre(@fdaciuk ), só não testei ainda o runtime e nem o redux mas está ai, funcionou nesse configuração.

https://github.com/leandrino/workflow-react

**Comment by fdaciuk** [comment]
Legal! A configuração ficou bem mais simples mesmo =)

**Comment by mat55** [comment]
Boa tarde galera, professor @fdaciuk estou com um problema parecido. Quando eu configurei o webpack.config alterando o localhost, me retornou este erro aqui:
"ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in c:\Projetos\ReactAulas
 @ multi main".

Obs.: Meu hot-loader está na mesma versão que o você recomendou e o meu entry dentro do webpack.config na alteração do localhost é essa aqui: 
entry: [
		'react-hot-loader/patch',
	    'webpack-dev-server/client?http://localhost:3000',
	    'webpack/hot/only-dev-server',
		path.join(__dirname, 'src', 'index')
	],

**Comment by fdaciuk** [comment]
Oi @mat55! Sobe seu projeto aqui no GitHub e me passa o link pra eu dar uma olhada, por favor? =)
