### ISSUE TITLE
webpack@1 módulo loaders

### ISSUE THREAD

**Issue by devedupereira** [da2k/curso-reactjs-ninja#128]
Boa noite,
Comecei o curso e havia instalado as versões mais recentes dos módulos utilizados, até que fiz o downgrade para versão correta de cada um deles por não estar reconhecendo algumas coisas no webpack.config

Mesmo na versão correta do webpack (webpack-cli e webpack-dev-server) ao executar o npm start, não sobe a aplicação por causa do seguinte erro:
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
```

Encontrei outra issue aqui falando sobre a correção desse erro ser através de instalar a versão correta do webpack (que já foi feito) e mesmo assim continua não funcionando!

Segue meu webpack config inteiro:

```
'use strict';

const path = require('path');
const webpack = require('webpack');

module.exports = {
    devtool: 'source-map',
    mode: "development",
    entry: [
        'react-hot-loader/patch',
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        path.join(__dirname, 'src', 'index')
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/dist/'
    },
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel-loader'
        }]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
}
```

E, package.json:

```
{
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "react-hot-loader": "^3.0.0-beta.2",
    "standard": "^11.0.1",
    "standard-loader": "^6.0.1",
    "webpack": "^1.15.0",
    "webpack-cli": "^2.1.3",
    "webpack-dev-server": "^1.16.5"
  },
  "scripts": {
    "start": "node server.js",
    "dev": "webpack-dev-server"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
```
Existe algum erro? Ou alguma novidade sobre isso?

@fdaciuk

**Comment by manzolirch** [comment]
Uma duvida, você recomeçou o projeto ou apenas deu um downgrade na mão mesmo? haha esse     "webpack-cli": "^2.1.3", foi pedido no projeto? porque esse erro de Loaders é porque 'loaders' mudou para 'rules', recomendo que apague toda a ESTRUTURA do projeto e recomece, salve somente a pasta 'src'!

**Comment by devedupereira** [comment]
Fiz o downgrade na mão mesmo. Vou recriar o projeto do zero! Obrigado

**Comment by fdaciuk** [comment]
Valeu pela resposta @manzolirch! @devedupereira provavelmente o problema é o webpack-cli mesmo, pois ele pode estar sendo usado no lugar do webpack mesmo, exibindo esse erro =)

**Comment by devedupereira** [comment]
Resolvido! Obrigado pessoal...

**Comment by fdaciuk** [comment]
Legal @devedupereira! Qualquer coisa avisa ae =)
