### ISSUE TITLE
React + Webpack : 'Uncaught SyntaxError: Unexpected token import'

### ISSUE THREAD

**Issue by jacksondev** [da2k/curso-reactjs-ninja#129]
Não consigo executar ele sempre da esse erro: Uncaught SyntaxError: Unexpected token import.
alguém sabe resolver? 
OBS: Iniciante. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jacksondev! Esse erro depende de como você está fazendo ao configuração =)

Você está instalando as versões exatas usadas no curso? Lembre-se sempre que você deve seguir as versões que estão [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) para não ter erros, ok? =)

**Comment by jacksondev** [comment]
@fdaciuk 
Eu acho que esta tudo nas versões exatas, porem ainda esta com o mesmo erro.

{
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "standard": "^11.0.1",
    "standard-loader": "^4.0.0",
    "webpack": "^1.15.0",
    "webpack-cli": "^2.1.4",
    "webpack-dev-server": "^1.0.0"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}

**Comment by fdaciuk** [comment]
Dá uma olhada se o problema não é o webpack-cli. Remova elel do seu package.json, remova a node_modules, e execute `npm install` para instalar as dependências novamente =)

**Comment by jacksondev** [comment]
tbm ñ deu certo.

**Comment by fdaciuk** [comment]
Oi @jacksondev! Dá uma olhada no número da aula que você está fazendo, e compare o código do seu projeto com o [código que foi feito no momento da aula](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack).

Nesse link acima, cada diretório está com o conteúdo que foi feito em cada aula, com tudo rodando certinho.

Compare com o seu projeto para ver o que pode estar diferente, provavelmente faltou você fazer alguma configuração =)

**Comment by jacksondev** [comment]
Obrigado, o problema foi resolvido.

**Comment by fdaciuk** [comment]
Legal @jacksondev! Qualquer coisa só avisar =)

**Comment by JoaoVitorViana** [comment]
> Obrigado, o problema foi resolvido.

Qual foi a solução?
