### ISSUE TITLE
Dúvidas 

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#13]
Fala @fdaciuk, cá estou eu novamente. Algumas dúvidas rápidas creio eu, vou colocar em forma de lista.

1.  No `webpack.config` na parte de `output` em `PublicPath`, você fala sobre trabalhar com arquivos em memória, e seta um `/static/`. Mas não entendi muito bem esse esquema, vou realmente poder usar assim? Não vou chamar o `bundle.js` pela _url_ normal? Como funciona quando trabalho com 2 ambientes (dev/produção) ?

2.  Estou na aula 27 ainda. Mas algumas coisas me preocupam. Com essa estrutura do React, onClick (eventos) inline, e outras coisas a mais que vi até o momento (nada aprofundado). É realmente assim? Não consigo me imaginar estruturando uma aplicação toda dessa maneira, com eventos inline, html dentro de arquivos javascript. O React realmente trabalha dessa forma, ou até o momento você está fazendo assim apenas para motivos de aprendizado? 

Resumindo, não consigo pensar em uma aplicação estruturada em react, com essa estrutura apresentada até o momento.

**Comment by fdaciuk** [comment]
Opa @gabrielferreiraa =)

Vamos lá!

1) Essa configuração mostrada no módulo `#1` serve somente para o ambiente de desenvolvimento. Todo o módulo `#1` foi pensado apenas para mostrar como o React funciona, com o mínimo de configurações possível. Foi mostrado como usar com ES5, e fizemos uma configuração básica no webpack para podermos desenvolver de forma fácil nossos componentes utilizando ES6 e aproveitando a feature de _hot reload_ que o webpack fornece =)

No módulo `#2`, entramos mais a fundo na parte de configuração e focando mais em como seria o desenvolvimento de aplicações utilizando React, mostrando exemplos de uso do dia-a-dia que você terá ao desenvolver projetos com React =)

Então não se preocupe com configuração nessa etapa inicial. No módulo `#2` você verá a parte mais avançada de configuração do webpack, entendendo como tudo funciona, e podendo você mesmo configurar o que quiser, da forma que sua aplicação necessitar =)

2) Esses pontos que você listou, na verdade, são um pouco equivocados. O JSX é uma sintaxe _XML Like_, que aproxima ao máximo a forma como um componente deveria ser feito em HTML, do seu código JavaScript em si. Mas no final, tudo é somente JavaScript.

Ou seja: quando você escreve usando JSX, não é esse código que vai para produção. Antes disso, ele é compilado e transformado em simples funções. Como eu mostrei no início, quando começamos a ver sobre o JSX, ele transforma cada chamada de "tag" para a função `React.createElement`. Isso você poderia fazer manualmente, mas não ficar tão declarativo, de forma tão clara, pois o JSX tenta trazer o mais próximo possível como o seu componente ficará na view.

O que você precisa entender nesse caso, é que ele não vai assim para produção.

Sobre os eventos inline, eles também não são inline. A ideia é manter o que faz parte do seu componente o mais próximo possível dele, para facilitar o desenvolvimento. Ao compilar esse código, quando o React gera a view, ele gera o HTML normal, sem esses eventos inline, e apenas atrela os eventos usando `addEventListener`. A vantagem é que você não precisa ficar procurando onde está a função que faz referência a certo componente, como se fizesse com HTML e JS separados.

Quando finalizar o módulo `#2`, acredito que isso vai ficar bastante claro: como é mais fácil testar componentes, isolá-los para reaproveitar código e, ainda que sua aplicação fique grande, será muito fácil de dar manutenção, se a componentização for feita da forma correta.

À primeira vista, JSX parece "HTML no meio do JS" mesmo, mas não é. E não chega nem perto de ser =)

Conforme você for evoluindo no estudo do React, e criando algumas aplicações com ele, tudo isso vai ficar mais claro na sua mente. Vai por mim =)

Deu pra entender? Ficou alguma dúvida ainda sobre isso?

Se tiver qualquer dúvida, só avisar :D

**Comment by gabrielferreiraa** [comment]
Tudo esclarecido cara, valeu pela explicação. Qualquer pingo de dúvida não vou ter vergonha de perguntar pra você! hahah Abraço!

**Comment by fdaciuk** [comment]
Boa! Isso ae =)
