### ISSUE TITLE
[M3#A55] Erro de lint

### ISSUE THREAD

**Issue by MarlonFlorencio** [da2k/curso-reactjs-ninja#132]
@fdaciuk

Boa noite professor, uma dúvida simples. O lint está retornando esses erros para o componente [SearchCepContainer](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m03/samples/36-todo-list-get-cep/src/components/search-cep/index.js)
```
/todo-list/src/components/search-cep/index.js
   8:3  error  'state' is not defined         no-undef
  18:3  error  'handleSubmit' is not defined  no-undef
```
É normal? Como corrigir?

Abraço

**Comment by fdaciuk** [comment]
Oi @MarlonFlorencio! Tente atualizar o seu linter, provavelmente ele não está em na versão mais recente, que suportaria essa feature (que é recente) =)

**Comment by MarlonFlorencio** [comment]
Obrigado @fdaciuk,

Verifiquei q estou usando a versão 10.0.3 do standard e a versão mais atual é a 11.0.1. 
Vou testar ainda hoje.

Abraço

**Comment by fdaciuk** [comment]
Legal! Dá uma olhada se pode ser isso! Tenta também comparar sua versão com a versão que você linkou no primeiro comentário, porque lá nesse ponto do projeto ele não exibe esse _warning_, apesar de estar usando a `10.0.3` também =)

**Comment by fdaciuk** [comment]
Oi @MarlonFlorencio! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
