### ISSUE TITLE
M1#A14 - Dúvida sobre keys dos componentes

### ISSUE THREAD

**Issue by phillipnunes** [da2k/curso-reactjs-ninja#134]
Olá.

Ao colocar uma key nos elementos de meu componente usando o index não geraria um conflito com outros componentes (ou talves no mesmo componente) na tela que também usam a mesma estratégia? 

Por exemplo, caso eu tenho 3 divs com keys 1, 2 e 3, e mais embaixo, _no mesmo componente_, um select onde as keys também são os índices.

Se não existe esse conflito, como o React trata isso então?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @phillipnunes! O problema na verdade não é esse =)
Você pode ter vários `map` dentro do seu componente, e cada um deles poderia passar as mesmas `key` anteriores sem problema algum, pois cada array vai ser tratado de forma isolada.

A questão é que o React precisa da `key` apenas para saber o que foi alterado naquele array, para que ele não precise destruir o array e criar um novo sempre que o componente for re-renderizado, saca?

Se cada elemento do array tiver sua própria `key`, e ele mudar de posição, o React sabe como fazer isso com o mínimo de alterações possíveis =)

**Comment by phillipnunes** [comment]
Ah entendi!

Estava achando que poderia acontecer algum conflito no React, semelhante a quando temos mais de um id com o mesmo nome no html.

Obrigado @fdaciuk

**Comment by fdaciuk** [comment]
Fica tranquilo que não rola não xD
Qualquer dúvida, só avisar! o/
