### ISSUE TITLE
CreateStore M3#A11

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#137]
Ola Fernando

Eu já uso o Redux entendi que vc explica bem no detalhe o que o createStore faz e mesmo prestando muita atenção no seu exemplo eu tenho dúvidas 

Por favor 

Como pode essa função com nome de createStore retornar 3 valores?

E de onde vem o state e o Action que chega no reducer que vc criou?

@fdaciuk

**Comment by Alexandre1202** [comment]
Ola Fernando

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Você ainda tem a dúvida? É que você fechou a issue =)

Se tiver dúvida ainda, me avise que eu tento te explicar melhor, ok? =)

**Comment by Alexandre1202** [comment]
Oi Fernando. 

Cara... quando escrevi eu estava no metro e não sei se foi o sinal fraco ou eu digitando apenas com uma mão para ter fechado...

Por favor, me ajuda. 

Eu não entendi principalmente o que quer dizer aquela função que retorna mais de um valor pois como pode o método chamador receber mais de um retorno...

Não tenho muita experiência com JavaScript.

Minha experiência é com Java.

Agradeço se puder ajudar.

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Legal, vamos lá:
na verdade, o método não tem 3 retornos, e sim um único retorno que é um objeto.

E esse objeto que é retornado contém os 3 métodos que foram mostrados na aula =)

O state que o reducer recebe é sempre o redux que se vira para passar pra ele. Nesse caso, a variável `state` sempre vai ser o último estado que o redux recebeu =)

Já a action é recebida pelo reducer quando você usa o método `.dispatch`, passando aquele objeto com a propriedade `type`. Esse objeto é a `action` :)

Ficou claro?

**Comment by Alexandre1202** [comment]
sim.
Se é um único objeto com todos os atributos então ficou claro.
Obrigado

**Comment by fdaciuk** [comment]
Legal @Alexandre1202! Qualquer dúvida, só avisar =)
