### ISSUE TITLE
MRW#A03 - Usando o server do WebPack 

### ISSUE THREAD

**Issue by diegopgcabral** [da2k/curso-reactjs-ninja#138]
Segui todos os passos desse capitulo e no momento de executar o comando:

webpack-dev-server

Recebo o seguinte erro:

**C:\Users\diego.cabral\Desktop\Research\react-webpack>webpack-dev-server@1
'webpack-dev-server@1' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.**

Arquivo index.html

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<script src="/static/bundle.js"></script>
	</body>
</html>

arquivo package.json

> {
>   "devDependencies": {
>     "webpack": "^1.15.0",
>     "webpack-dev-server": "^1.16.5"
>   }
> }

Arquivo webpack.config.js

> 'use strict'
> 
> const path = require('path')
> 
> module.exports = {
> 	entry: path.join(__dirname,'src','index'),
> 	output: {
> 		path: path.join(__dirname,'dist'),
> 		filename: 'bundle.js',
> 		publicPath: '/static/'
> 	}
> }

fiz a instalação do webpack de desenvolvimento utilizando o comando abaixo:
**npm install --save-dev webpack-dev-server@1**

Poderia me ajudar?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @diegopgcabral! O comando você deve executar sem o `@1`. Essa parte é apenas para a instalação da dependência nessa versão específica.

É importante instalar a mesma dependência de forma global também, para ter o comando disponível no seu terminal =)

**Comment by diegopgcabral** [comment]
@fdaciuk executei o comando npm install --save-dev webpack-dev-server sem o @1..

C:\Users\diego.cabral\Desktop\Research\react-webpack>npm install --save-dev webpack-dev-server
npm WARN react-webpack No description
npm WARN react-webpack No repository field.
npm WARN react-webpack No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"ia32"})

+ webpack-dev-server@1.16.5
updated 1 package in 11.706s


mesmo assim quando digito o comando webpack-dev-server continuo recebendo o erro abaixo:

C:\Users\diego.cabral\Desktop\Research\react-webpack>webpack-dev-server
'webpack-dev-server' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

Estou meio perdido. Preciso fazer algo que eu não fiz?

**Comment by diegopgcabral** [comment]
Resolvido!!!!

**Comment by fdaciuk** [comment]
Oi @diegopgcabral! Resolveu? =)

Para instalar - usando o `npm i --save-dev` e/ou `npm i -g` - você **deve** usar o `@1`.

Agora, para **usar** o `webpack-dev-server`, aí sim você passa sem o `@1`, ok? =)
