### ISSUE TITLE
Dúvida sobre organização dos componentes

### ISSUE THREAD

**Issue by phillipnunes** [da2k/curso-reactjs-ninja#139]
Olá.

Eu costumo ir criando uma aplicação em paralelo aos cursos para ir fixando melhor os conhecimentos, estou fazendo o mesmo nesse caso, usando o create-react-app e os componentes do material ui para react.

Estou com dúvida sobre onde colocar as coisas. Eu criei um componente chamado Sidebar.js, adicionei tudo referente ao Drawer (que é o nome do sidemenu deles), importei o componente Sidebar.js dentro do App.js, e é dentro desse Sidebar.js, nessa área vermelha em destaque, que eu devo renderizar os componentes da aplicação:
![image](https://user-images.githubusercontent.com/4396768/41203991-3cea78ae-6cb5-11e8-9094-ac989c665b88.png)

Está tudo funcionando, mas estou achando a organização estranha. Do jeito que eu fiz, todas as mudanças e componente irão acontecer dentro do Sidebar.js em uma tag _main_ que existe nele (que corresponde ao espaço vermelho na imagem), mas tenho a impressão que deveria acontecer de outra forma e em outro lugar, talvez dentro do App.js, mas ainda não sei qual a melhor forma de organizar as coisas.

Poderia me dar alguma sugestão?
Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @phillipnunes! Consegue me mostrar o código, pra eu dar uma olhada?
Sobe o projeto aqui no GitHub =)

**Comment by fdaciuk** [comment]
Oi @phillipnunes! Legal =)

Bom, olhando aqui seu componente, o problema na verdade está apenas no nome que você deu para o seu componente.

Nesse `Sidebar.js` você tem 3 componentes principais: o `AppBar`, o `Drawer` e o `main`.

O que você poderia fazer, seria isolar esses 3, e chamá-los no `App.js`. Acredito que o `AppBar` é aquela barra do topo, azul, correto? Se for, pode chamar ela de `Header` ou algo assim.

O `Drawer` seria a `Sidebar`, e o `main` poderia ficar em um outro componente, que seria o `Content` ou algo assim.

Funciona pra você dessa forma? =)

**Comment by phillipnunes** [comment]
Parece melhor da forma como disse, @fdaciuk 

Vou alterar conforme suas sugestões. É bom que dou uma treinada a mais na criação e divisão de componentes.

Uma dúvida. Na hora de dividir, notei que cada componente vai ficar com suas props dentro dele, e que o trecho _const { classes, theme } = this.props;_ vai se repetir no render de alguns. Essa repetição de código chega a ser um problema, ou tem um pattern melhor, por exemplo deixando global em algum lugar?

[]'s

**Comment by fdaciuk** [comment]
Oi @phillipnunes! Não vejo problema, pois não é bem uma duplicação de código. Você pode separar os estilos específicos para cada componente, ao invés de usar um único objeto. Dessa forma, você facilita a reutilização de cada componente, já que eles serão puros, e os valores internos que cada componente precisa para renderizar corretamente estarão sendo passados via props =)

Se você perceber algum componente de fato sendo repetido, em um padrão específico, aí sim você consegue isolar isso e abstrair em um terceiro componente, por exemplo =)

Mas o caminho é esse! Praticar bastante! Primeiro para fazer a aplicação funcionar. Depois, para entender bem esses conceitos, e cada vez ir melhorando, ok? =)

**Comment by phillipnunes** [comment]
Ok, muito obrigado!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
