### ISSUE TITLE
Problema com API GH

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#14]
Fala @fdaciuk, beleza? Estou com um probleminha aqui, que não consigo resolver!

Estou na aula "M1#A43 - GitHub app - método para buscar repositórios e favoritos". Finalizando o request dos repositórios e colocando na tela.

O que está acontecendo é o seguinte: 
Quando vou dar um setState({  }) com o retorno da promise, ele não faz nada. Se dou `console.log(result)` todos os dados estão ali corretos. Não da erro no console nem no devtools do React. Vou deixar o link do meu app.js.

Fico no aguardo e enquanto isso vou tentando resolver, valeu!

https://github.com/gabrielferreiraa/bp_react/blob/master/github-app/src/app.js (line 45)

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa, tudo certo! =)

Vou baixar aqui e testar, e já vejo o que pode estar acontecendo =)

**Comment by fdaciuk** [comment]
Eae @gabrielferreiraa! Encontrei o problema =)

Na verdade, o setState está funcionando certinho.. o problema está [nessa linha](https://github.com/gabrielferreiraa/bp_react/blob/master/github-app/src/components/app-content.js#L22) e [nessa](https://github.com/gabrielferreiraa/bp_react/blob/master/github-app/src/components/app-content.js#L28).

`length` é `th`, não `ht` =)

E lembre-se de que, ao usar expressões de curto circuito, você precisa testar o valor já em booleano, pois, nesse caso em que length vai retornar um número, o React vai renderizar o `0` quando não houver itens, pois esse é o valor de `length` =)

Use `!!repos.length` ou `Boolean(repos.length)` =)

Qualquer dúvida, só avisar! :D
