### ISSUE TITLE
Sobre performance!

### ISSUE THREAD

**Issue by Joaoh3326** [da2k/curso-reactjs-ninja#140]
Professor, tipo eu vou dar uma palestra na faculdade sobre React, e tava vendo os pontos onde o React deveria ser escolhido ao invés de outro Framework ou lib(sei que o react é uma biblioteca), tem algum post que fale sobre performance dele sendo superior(sei que nem tudo se resume a performance) ? e tem como
se não for muito incomodo liberar algum desconto pro curso de react ninja ou do js ninja, pra fazer a divulgação do curso ? (fiz o de js ninja, e vou começar a fazer o de react novamente, e de longe foram os cursos que me deram a melhor base 🥇 )

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Joaoh3326! Que legal cara \o/

Bom, sobre performance, as libs e frameworks atuais são bem próximas, acho que não tem muito sentido em tentar comparar. Em vários casos, o React até perde nesse quesito, quando se trata de ações síncronas =)

O importante ao falar sobre performance é mostrar a importância da **performance percebida** pelo usuário ao usar / navegar na sua aplicação.

Pra esse caso, você pode dar uma pesquisada sobre o React Fiber, que foi a reescrita do algoritmo de renderização do React, e implantado na versão 16.

Uma talk que pode ajudar com esse conteúdo é a que o @raphamorim deu ano passado na React Conf: https://www.infoq.com/br/presentations/scratching-react-fiber

**Comment by Joaoh3326** [comment]
Vlw, pela dica vou ver sim a talk :D, e sobre o desconto rola ? vai ser esse sábado dia 16 :) , se não puder esta tudo bem, só isso que você me falou vai ser de grande ajuda.

**Comment by fdaciuk** [comment]
Ah, foi mal, esqueci de falar sobre os cupons: tá rolando uma promo que vai até final do mês, para todos os cursos, então pode usar esse mesmo cupom =)

Se quiser, pode só passar o link das promoções, em https://queroser.ninja/promocoes :D 

Fico muito feliz que está curtindo o conteúdo dos cursos, e agradeço imensamente por espalhar a palavra :heart:
