### ISSUE TITLE
[M1#A41] - Fluxo de execução

### ISSUE THREAD

**Issue by phillipnunes** [da2k/curso-reactjs-ninja#142]
Olá.

Nessa aula não entendi o fluxo das coisas acontecendo.

Quando eu pressiono ENTER, ele começa do app.js no _handleSearch={(e) => this.handleSearch(e)}_, e "desce" até o componente search, ou é o contrário, a aplicação começa do search.js e vai subindo até o app.js e achar a função de ajax?

Ah, e dei console.log naquele parâmetro _**e**_ do handleSearch no app, e ele retorna um proxy. Achei estranho porque achava que olhando dentro dele ao abrir teria o _target_ e depois o _value_, por causa do código _e.target.value_, mas não foi o caso.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @phillipnunes! Vamos lá:

O componente `Search` tem um evento `onKeyUp`. Esse evento é disparado sempre que uma tecla do teclado é pressionada e solta. Após soltar, o evento é disparado, e a função passada para o evento é executada.

Então tudo começa nesse componente. Mas de onde vem essa função? Para que o `Search` receba essa prop, o componente onde o `Search` foi usado precisa passar pra ele essa prop.

E o componente que contém o `Search` é o `AppContent`. Mas a função também não está no `AppContent`, está em um componente acima dele, que é o `App`.

Então a função principal está criada no `App`, pois é lá que a alteração de `state` vai ser feita para atualizar todos os componentes abaixo de `App`.

Como funções são do tipo _objeto_ em JavaScript, elas são passadas por referência. Sempre que passamos uma prop para um componente, é como se passássemos argumentos para uma função. Logo, essa função passada via prop de componente para componente, até chegar no `Search`, é a mesma referência que está lá no `App`.

Assim, quando qualquer tecla é pressionada e solta, o evento `onKeyUp` é disparado, executando a função que foi passada para ele. E como `handleSearch` é uma referência para a função que está lá no `App`, é essa função que vai ser executada quando o evento for disparado =)

Deu pra entender o fluxo? É exatamente o que aconteceria se usássemos JavaScript puro, sem o React :)

**Comment by fdaciuk** [comment]
Sobre dar um console.log no `e`: esse objeto de evento é criado pelo React. Ele é normalizado pelo React para funcionar exatamente igual em todos os browsers, por isso ele tem essa estrutura "estranha" quando você dá um `console.log` nele =)

Mas ele tem basicamente todas as propriedades que você precisaria de um evento comum, como se você estivesse usando JS puro.

O time do React chama de _Evento Sintético_, pois não é exatamente o mesmo objeto que o browser disponibiliza para um evento, mas um objeto normalizado para funcionar igual em todos os browsers =)

Ficou claro? =)

**Comment by phillipnunes** [comment]
_...É exatamente o que aconteceria se usássemos JavaScript puro, sem o React_ 
Ah, então entendi. Começa do componente mais interno e vai se propagando para cima. Tipo o Event Bubbling.

Estava achando que o React fazia alguma coisa diferente disso. Vou começar a me atentar mais a documentação.

Muito obrigado, você explicou tudo muito bem e deu pra entender facilmente.

:)

**Comment by fdaciuk** [comment]
É mais ou menos isso mesmo =)

Mas não é que propaga: a função está no componente `App`, mas é o evento do `Search` que dispara ela =)

E ela precisa ficar no `App`, pois é lá que fazemos a atulização do `state`. Com um novo `state`, aí sim o React começa a atualizar os componentes, à partir do componente que teve algum state ou props atualizado. Então o `render()` do `App` vai ser executado novamente, fazendo com que os componentes abaixo dele também sejam re-renderizados, desde que as props que eles recebem do state do `App` também tenham mudado =)

Mas é isso! Qualquer dúvida, só avisar =)
