### ISSUE TITLE
M2#A36 Testes

### ISSUE THREAD

**Issue by samuelbrehm** [da2k/curso-reactjs-ninja#143]
Olá Fernando!

Neste momento não tem a pasta testes. Por quê?
E já gostaria de perguntar se não seria bom ter uma pasta com o arquivo test.js dentro de cada pasta de componente, assim como você faz com o css? Não seria uma boa prática?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! Nessa parte do curso ainda estamos vendo sobre configurações do webpack =)
Mais pra frente ainda vamos falar um pouco mais sobre testes, e sobre esse ponto que você que você comentou, de ter os testes junto com o componente =)

Mas já adiantando: é sim uma boa prática, e facilita muito deixar tudo o que é referente ao componente o mais próximo possível dele =)

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! Deu certo? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
