### ISSUE TITLE
M2#A97 - Configurações no Boilerplate 

### ISSUE THREAD

**Issue by tgmarinho** [da2k/curso-reactjs-ninja#145]
Oi Fernando, blz? 

[M2#A97](https://www.udemy.com/curso-reactjs-ninja/learn/v4/t/lecture/7177306?start=0)

A configuração de inserir o normalize no common.js no markdown-editor precisa ser feita no boilerplate workflow-reactjs? https://github.com/fdaciuk/workflow-reactjs pq os excludes foram retirados mas o normalizeCss não foi inserido.

Bom se entendi bem era apenas para tirar o excludes né? O normalize coloca se precisar? Seria uma customização extra em um projeto que utiliza um css e o normalize.css

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tgmarinho! Eu não adicionei essa configuração no boilerplate porque é opcional. No caso, foi inserido apenas no projeto mesmo, pois seria necessário ali =)

E sobre os excludes é isso mesmo: dessa forma nós facilitamos para o webpack entender que nós queremos apenas aplicar os loaders no que estiver em `includes`, fazendo o build ser mais rápido por ele precisar apenas ler o que está em `includes`, sem se preocupar em ignorar o que está em `excludes`. Qualquer coisa que não estiver em `includes` vai ser ignorada =)
