### ISSUE TITLE
M1#A47 - Botão para limpar input

### ISSUE THREAD

**Issue by xbrunosousa** [da2k/curso-reactjs-ninja#146]
Fernando, boa noite! =)

Seguindo as aulas para criação do App do Github, fiz tudo certinho do incio ao fim. Está rodando perfeitamente. Porém, gostaria de criar um botão no input search para que, ao clicar, o conteúdo digitado seja apagado. Uma espécie de "X".

Qual o método correto para fazer isso?

Tentei criar uma function no onClick do button para zerar o valor do e.target.value, mas sem sucesso. 
Está correto?

Obrigado. =)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xbrunosousa! Consegue subir seu projeto no GitHub pra eu dar uma olhada como ficou? Fica mais fácil te apontar onde colocar as coisas =)

**Comment by xbrunosousa** [comment]
Segue link, @fdaciuk 
https://github.com/xbrunosousa/github-app-react.js/invitations

**Comment by fdaciuk** [comment]
Legal @xbrunosousa! =)

A sua ideia seria só limpar o input de search mesmo?

Se for, acho que a maneira mais simples seria colocar o `value` do input como controlado. Fazendo isso, o valor do input será manipulado pelo state do React, e assim você adicionar um `onClick` no seu button para limpar esse valor de forma simples =)

**Comment by xbrunosousa** [comment]
Isso, a ideia é fazer somente um button para limpar o value mesmo. Creio que igual no teu [exemplo](https://imgur.com/a/FXDFcMc) nas aulas! =)

No caso no onClick eu chamaria qual método?

Valeu!

**Comment by fdaciuk** [comment]
Então, esse "x" que aparece no exemplo que eu mostrei é o browser mesmo que coloca, por ser um input do tipo `search`. Mas como você está usando o `reactstrap`, provavelmente tem algum CSS sobrescrevendo esse comportamento do browser, e não deixando exibir o "x" =)

Para fazer com input controlado, você vai precisar adicionar `value` e `onChange` no campo de search, e criar um outro método que limpa o valor.

O valor pode ficar no componente pai, como `state`. Ae você passa via props esse valor, o método do `onChange` e o método que vai limpar esse `state`, saca?

**Comment by xbrunosousa** [comment]
Certinho, Fernando! Muito obrigado! =)
