### ISSUE TITLE
M2# jest

### ISSUE THREAD

**Issue by paulojosern** [da2k/curso-reactjs-ninja#148]
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  SyntaxError: Unexpected end of JSON input

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @paulojosern! Consegue subir seu projeto no GitHub pra eu dar uma olhada?

**Comment by paulojosern** [comment]
Oi sim sim ,

a mensagem aqui:
![image](https://user-images.githubusercontent.com/26974969/42055774-79bad9bc-7aee-11e8-9637-003135c2cca5.png)

https://github.com/paulojosern/jest-in-practice

**Comment by fdaciuk** [comment]
@paulojosern dei uma pesquisada sobre essa mensagem, e parece não ter relação com o Jest em si. Na verdade, você pode ignorar ela completamente xD

Algumas "soluções" que encontrei (não sei vai funcionar, teste uma a uma pra ver, por favor):

1. Se você tem o `git` instalado, pode remover esse arquivo '.watchmanconfig` da raiz da sua aplicação, e tente apenas iniciar um novo repo do `git`, rodando apenas `git init`. Após fazer isso, tente executar os testes novamente e veja se essa mensagem continua aparecendo;

2. Se continuar aparecendo, e se você tiver o `watchman` instalado, tente rodar o comando no terminal: `watchman shutdown-server`. Tente rodar novamente os testes, e veja se a mensagem continua aparecendo.

Essas foram as possíveis soluções que eu encontrei. De qualquer forma, se não funcionar, pode ignorar a mensagem, ela nem deveria estar aparecendo. Provavelmente não irá aparecer em versões futuras do Jest =)

**Comment by fdaciuk** [comment]
Oi @paulojosern! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
