### ISSUE TITLE
MD1# servidor mostrando estrutura de diretorios

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-reactjs-ninja#149]
Opa Fernando, tudo certinho?
então... depois que adicionei o gitignore no app do Github, quando subo o servidor esta me mostrando a estrutura de diretórios ao invés de subir a aplicação , ontem passei o dia tentando descobrir o que fiz de errado, ja desinstalei e instalei tudo novamente, troquei a porta e nada.

subi o app nesse repositorio 

[https://github.com/LucasCMota/GitHub-Search-React](url)

@fdaciuk

**Comment by LucasCMota** [comment]
\o/,  descobri o que fiz de errado, tinha apagado o index.html ehehe

**Comment by fdaciuk** [comment]
Opa! Legal que descobriu o/

Qualquer coisa, avisa ae :D
