### ISSUE TITLE
Dúvida em relação ao curso

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#15]
@fdaciuk, cá estou novamente. Não para dúvida, mas por curiosidade!

Estudando junto com você, e ao mesmo tempo buscando novos conteúdos na internet, posso ver a citação de várias tecnologias e pensamentos que acompanham o React e trabalham junto com ele, são eles os principais: Flux e Redux. Estou na aula M1#A50 até o momento isso não foi abordado. Alguma das aulas que estão no ar, explicam o que são esses conceitos/tecnologias? Pesquiso, pesquiso e pesquiso porém, não acho ninguém didático o suficiente para me explicar e me ajudar em relação a isso. Consegue me dar uma mão?

Desculpe a "abrissão" de issues, é que esse React tem mta coisa pra aprender hehehehe

Abraço!

**Comment by fdaciuk** [comment]
> Desculpe a "abrissão" de issues, é que esse React tem mta coisa pra aprender hehehehe

Não tem que se desculpar de nada meu caro, o curso é para que você aprenda mesmo! E só aprende se você não tiver dúvidas :D 

Vamos lá: Redux / Flux são arquiteturas para organização de estados dentro da aplicação. Vamos falar sobre isso no módulo `#03`.

Mas eles não são obrigatórios. Eles servem para resolver um problema específico, e você vai entender quando chegar lá, então fique tranquilo =)

No curso, nós iremos abordar tudo o que é mais importante no ecossistema do React, para que você possa criar uma aplicação completa, sem erros =)

O módulo `#01` e `#02` são para entender bem como o React funciona, quais são as formas de criar componentes, de forma que você possa reaproveitar ao máximo, e fazer da forma certa, com testes, e ainda aprendendo a gerar a versão de produção da sua aplicação. Só com React!

A partir do módulo `#03`, vamos começar a ver ferramentas que vão nos ajudar a trabalhar com aplicações maiores:

- Redux para tratamento de estados no módulo `#03`;
- Gerenciamento de rotas no módulo `#04`;
- E para fechar com chave de ouro, _Server Side Rendering (SSR)_, ou renderização do lado do servidor - também conhecido como **Aplicações Isomórficas**, no módulo `#05`.

Todos os módulos serão cobertos com muitos exemplos práticos, para cobrir o máximo possível de técnicas que você pode utilizar!

Bom, é isso =)

E continue assim: não se acanhe em perguntar! É assim que se aprende =)

Conte comigo sempre que precisar =)
