### ISSUE TITLE
MRW#03 - Usando o server do Webpack

### ISSUE THREAD

**Issue by apsantos-dev** [da2k/curso-reactjs-ninja#151]
Olá @fdaciuk, tudo bem?

Aos 06:20 você explica como instalar o webpack global, entretanto, ao executar o comando apresentou erro. Neste caso, instalei a webpack-cli:

$ sudo npm install -g webpack-cli
$ sudo npm cache clean --force

Tentei:

$ sudo npm install --save-dev webpack-cli

nada...

Erro:

react-ninja-webpack/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^
TypeError: validateSchema is not a function

node --version
v10.6.0

npm --version
6.1.0

> package.json
{
  "scripts": {
    "start": "webpack --config webpack.config.js"
  },
  "devDependencies": {
    "webpack": "^1.15.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^1.16.5"
  }
}

> webpack.config.js

'use strict'

const path = require('path')

module.exports = {
  entry: path.join(__dirname, 'src', 'index'),

  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  }
}

Os outros arquivos estão identicos.

Sinto muito por não conseguir resolver isso. Já pesquisei de tudo...
E desculpa se a forma que postei a dúvida está errado. Tentei deixar o mais objetivo possível.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @apsantos-dev! Sem problemas meu caro =)

Esse problema é por conta da versão do webpack =)

Eu deixei um vídeo no início desse módulo chamado "Aula do Futuro". Lá eu mostro esse arquivo aqui:
https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md

É esse arquivo que você deve seguir para instalar as dependências corretamente, para ficarem na mesma versão usada quando o curso foi gravado =)

Durante o desenrolar do curso, vamos atualizando essas dependências para as versões mais recentes, e entendendo esses problemas que podem acontecer de uma versão para outra, ok? =)

Qualquer dúvida, só avisar :D

**Comment by apsantos-dev** [comment]
Olá @fdaciuk, bom dia!

Meu amigo, não sei aonde estava errando. Eu até fiz as instalações seguindo o tutorial [Versions of dependencies](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md "Link que você menciona no curso!")

Então removi a node_modules, desinstalei tudo que era global e fiz passo a passo novamente. Funcionando perfeitamente agora! \o/

Só mais uma dúvida:

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

Achei esse link aqui (https://webpack.js.org/concepts/mode/) e depois vou dar uma olhadinha. 

Muito obrigado mais uma vez!

**Comment by fdaciuk** [comment]
Opa, legal que funcionou =)

Esse warning é da versão 4 do webpack. Pode ser que você ainda tenha o `webpack-cli` instalado. Se tiver, pode remover ele também =)
