### ISSUE TITLE
MRW#02 - Configuração básica do Webpack

### ISSUE THREAD

**Issue by rafaelToz1989** [da2k/curso-reactjs-ninja#152]
Olá Daciuk, boa noite, tudo bem?

A minha dúvida é em relação a execução do comando "webpack", para gerar o arquivo /dist/bundle.js, pois executei o comando conforme orientado: npm install --save-dev webpack@1, ao invés do comando de instalação global exemplificado no vídeo: npm i -g webpack (seria isso mesmo?), porém ao executar "webpack" seguindo a orientação, o meu console do windows exibe a seguinte mensagem:

"'webpack' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes."

package.json:

{
  "devDependencies": {
    "webpack": "^1.15.0",
    "webpack-cli": "^3.0.8"
  }
}

webpack.config.js:

'use strict'

const path = require('path')

module.exports = {
    entry: path.join(_dirname, 'src', 'index'),
    output: {
        path: path.join(_dirname, 'dist'),
        filename: 'bundle.js'
    }
}

Estou fazendo algo errado? será que esqueci de alguma parte da configuração?

Poderia me ajudar, por favor, com essa questão?

Desde já, te agradeço.

Abraços!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafaelToz1989! Vamos lá!

Primeiramente, pode remover o `webpack-cli`, pois ele faz parte da versão 4 do webpack, e vai dar problema com versões anteriores =)

Sobre a forma de instalação e como rodar o comando direto no terminal, é o seguinte:
Você precisa instalar duas vezes o webpack: com `--save-dev` para instalar local, e com `-g` para instalar também global!

A versão global é para que você consiga rodar o comando `webpack` à partir do seu terminal. E a versão local é a versão que vai ser usada no projeto =)

Para não precisar instalar a versão global (assim como eu fiz no vídeo), você precisa adicionar o diretório `node_modules/.bin` no `$PATH` do seu sistema.

Não sei como seria para adicionar no windows, mas no Linux seria somente você executar o comando abaixo no seu terminal:

```
export PATH="node_modules/.bin:$PATH"
```

Ou adicionar essa linha no arquivo de configuração do seu shell (`.bashrc`, `.zshrc`, etc).

Depois de reiniciar o terminal (fechar e abrir novamente), você já vai conseguir rodar qualquer ferramenta de CLI do Node.js à partir da raiz do projeto.

No caso do webpack, quando você instala ele com `--save-dev`, ele cria um arquivo executável à partir do comando `webpack` no seu diretório `node_modules/.bin`, por isso funciona sem precisar instalar de forma global =)

Ficou claro?

**Comment by rafaelToz1989** [comment]
Funcionou sim Fernando, muito obrigado! =)

Mas só uma dúvida em questão, aproveitando o assunto (não sei se deveria abrir uma nova Issue, por se tratar do vídeo seguinte).

Aconteceu que após realizar a instalação do webpack-dev-server (com o comando: npm install --save-dev webpack-dev-server@1 e  a instalação global com o comando: npm install -g webpack-dev-server@1), quando fui executar o comando "webpack-dev-server", o console exibiu o seguinte erro: 

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

package.json:
{
  "devDependencies": {
    "webpack": "^1.15.0",
    "webpack-dev-server": "^1.16.5"
  }
}

Sabe me dizer o que poderia ser? 

Muito obrigado pela ajuda até o momento e se for necessário, posso abrir uma nova.

**Comment by fdaciuk** [comment]
Oi @rafaelToz1989! Esse erro pode ter mais de um motivo. O mais provável é que você já estava rodando o `webpack-dev-server` em um terminal, e rodou o comando em outro. Como a mesma porta está sendo usada, ele daria um erro parecido com esse (em teoria ele deveria exibir um `EADDRINUSE`, não um `EACCES`, mas dá uma olhada se pode ser isso.

Outra possibilidade é sobre as permissões: se você instala as dependências globais com `sudo`, pode ser também por isso, e você pode precisar usar o `sudo` também para subir o `webpack-dev-server`. Se for o caso, recomendo que você desinstale o node que está instalado na sua máquina, e instale o NVM, que vai permitir o uso do Node.js de forma local, sem necessidade do `sudo`, inclusive para instalar dependências globais =)

**Comment by rafaelToz1989** [comment]
@fdaciuk 

 Boa noite @fdaciuk, tudo bem?

Após enviar a pergunta para você eu verifiquei aqui que o problema ocorrido era devido a porta 8080 estar sendo ocupada por outra aplicação. Notei que há duas formas de resolver, matando essa alocação ou executando o webback-dev-server em outra porta, solucionando o problema.

Agradeço muito seu suporte e ajuda, até logo e um grande abraço!

**Comment by fdaciuk** [comment]
Isso mesmo @rafaelToz1989! Legal que resolveu =)
Qualquer coisa só avisar :D
