### ISSUE TITLE
React.js Ninja: Módulo React + Webpack (finalizado)

### ISSUE THREAD

**Issue by apsantos-dev** [da2k/curso-reactjs-ninja#153]
Olá @fdaciuk!

FInalizei a primeira etapa \o/. Rodando uma beleza aqui. Só uma dúvida, não consigo gerar a pasta /dist

Subi os arquivos para um repositório temporário, assim você consegue avaliar melhor:

https://github.com/apsantos-dev/boilerplate-react-webpack

Veja o erro ao rodar o comando: webpack

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
   -> Options affecting the normal modules (`NormalModuleFactory`).

Ja revisei o código várias vezes e tentei achar nas issues criadas. Não consegui entender o motivo.

Muito obrigado e se puder dar uma dica ficarei muito grato!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @apsantos-dev! Dá uma olhada se você não tem instalado globalmente o `webpack-cli`. Se tiver, remova ele e instale só o `webpack@1` =)

Também cheque sua `node_modules` pra ver se não tem o `webpack-cli` ali.

Pra garantir, remova a `node_modules` e instale novamente as dependências (com `npm i`) =)

**Comment by apsantos-dev** [comment]
Olá @fdaciuk , olha eu novamente!

Fiz como sugeriu:

# desinstalei global
$ sudo npm uninstall -g webpack-cli

# Tentei gerar a pasta dist
$ webpack
$ bash: webpack-cli: command not found...

# removi o node_modules
$ sudo rm -rf node_modules

# reinstalei as dependencias
$ npm i

Apresenta o seguinte erro:

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
 - webpack-command (https://github.com/webpack-contrib/webpack-command)
   A lightweight, opinionated webpack CLI.
We will use "npm" to install the CLI via "npm install -D".
Which one do you like to install (webpack-cli/webpack-command):

# Tentei instalar como sugerido no erro
$ npm install -D

# Tentei instalar webpack-cli@1 e webpack-command
$ npm install --save-dev webpack-cli@1 webpack-command

Sem sucesso ainda.

O projeto roda lindamente. O servidor localhost:3000 funciona bem e atualizações automaticamente. Só não consigo mesmo é gerar o folder dist

**Comment by apsantos-dev** [comment]
Olá @fdaciuk, olha eu novamente!

Fiz como sugeriu:

# Desinstalei global
$ sudo npm uninstall -g webpack-cli

$ webpack-cli
$ bash: webpack-cli: command not found...

# removi o node_modules
$ sudo rm -rf node_modules

# reinstalei as dependencias
$ npm i

# Tentei gerar a pasta dist
$ webpack

Apresenta o seguinte erro:

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
 - webpack-command (https://github.com/webpack-contrib/webpack-command)
   A lightweight, opinionated webpack CLI.
We will use "npm" to install the CLI via "npm install -D".
Which one do you like to install (webpack-cli/webpack-command):

# Tentei instalar como sugerido no erro
$ npm install -D

# Tentei instalar webpack-cli@1 e webpack-command
$ npm install --save-dev webpack-cli@1 webpack-command

Sem sucesso ainda.

O projeto roda lindamente. O servidor localhost:3000 funciona bem e atualizações automaticamente. Só não consigo mesmo é gerar o folder dist

**Comment by apsantos-dev** [comment]
Olá @fdaciuk, olha eu novamente!

Fiz como sugeriu:

Desinstalei global
> $ sudo npm uninstall -g webpack-cli

> $ webpack-cli
> $ bash: webpack-cli: command not found...

removi o node_modules
> $ sudo rm -rf node_modules

reinstalei as dependencias
> $ npm i

Tentei gerar a pasta dist
> $ webpack

Apresenta o seguinte erro:

> One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
>  - webpack-cli (https://github.com/webpack/webpack-cli)
>    The original webpack full-featured CLI.
>  - webpack-command (https://github.com/webpack-contrib/webpack-command)
>    A lightweight, opinionated webpack CLI.
> We will use "npm" to install the CLI via "npm install -D".
> Which one do you like to install (webpack-cli/webpack-command):

Tentei instalar como sugerido no erro
> $ npm install -D

Tentei instalar webpack-cli@1 e webpack-command
> $ npm install --save-dev webpack-cli@1 webpack-command

Sem sucesso ainda.

O projeto roda lindamente. O servidor localhost:3000 funciona bem e atualizações automaticamente. Só não consigo mesmo é gerar o folder dist

**Comment by fdaciuk** [comment]
Oi @apsantos-dev! Não é pra instalar o `webpack-cli`, é pra remover ele! É pra instalar só o `webpack@1`, tanto local como global =)

Remova o `webpack-cli` e `webpack` local e global, e instale com `webpack@1` que vai funcionar =)

**Comment by fdaciuk** [comment]
Oi @apsantos-dev! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by Rhomennik** [comment]
Oi prof.. Estou com este problema no mesmo mudloulo
![image](https://user-images.githubusercontent.com/24496303/54869897-b1c15900-4d7d-11e9-9076-0a72e03d2911.png)

**Comment by fdaciuk** [comment]
Oi @Rhomennik! Pela mensagem de erro, o seu problema é o mesmo: versão do webpack! Instale a versão correta, como mostrei nas mensagens anteriores, que deve funcionar :)

**Comment by Rhomennik** [comment]
### Funcionou !!,

Era a versão do meu Webpack, Instalei a versao que voce estava usando.. Porem, meu Npm sempre me avisa que e nessesario fazer um 
`npm audit fix`

Isso e meio incomodo, tem como solucionar? O no caso tem que deixar a versão como do curso? ..

**Comment by fdaciuk** [comment]
@Rhomennik a versão usada no curso é apenas para que você consiga acompanhar o curso e aprender os conceitos como estão sendo mostrados.

Ao final do módulo 2, você vai ver tudo o que precisa sobre essa parte de configurações, e então poderá usar a versão mais recente, apenas corrigindo as atualizações que foram feitas na lib, já que nesse momento do curso você já saberá lidar melhor com a ferramenta :)

Ignore essa mensagem por enquanto, e foque nos conceitos aprendidos, ok? :)

Qualquer coisa, só avisar :)

**Comment by Rhomennik** [comment]
### Obrigado Professor
@fdaciuk  Pode deixar, Muito obrigado pelo suporte Professor!!, 
muito bom o curso!!!!

**Comment by fdaciuk** [comment]
Fico feliz que está curtindo! Qualquer coisa, só avisar :D
