### ISSUE TITLE
[M2#A51] Problemas de teste e lint

### ISSUE THREAD

**Issue by leandromds** [da2k/curso-reactjs-ninja#154]
Fala Daciuk, tudo bem contigo?

Segui todos os passos dessa aula e tanto o linter do standard e test do jest funcionaram bem, porem os watchs não estão funcionando como deveria.

O test:linter no primeiro ciclo funciona corretamente, porém ao detectar uma mudança ele faz o refresh e o coverage pega todos os arquivos do projeto ao invés de pegar apenas da pasta "utils" como na imagem abaixo:
![captura de tela 2018-07-07 as 10 37 09](https://user-images.githubusercontent.com/9199934/42411422-36444e44-81d2-11e8-932c-917cd971060d.png)

Já o lint:watch ele excuta traz o resultado mas não fica "assistindo" ele para a de rodar como na imagem abaixo:
![captura de tela 2018-07-07 as 10 42 52](https://user-images.githubusercontent.com/9199934/42411452-8bf02534-81d2-11e8-9c07-5d32bd27cb8c.png)

O projeto esta nesse link:
https://github.com/leandromds/github-app

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leandromds! 

Sobre o `test:watch`, não consegui reproduzir aqui. Tente deletar o diretório `coverage` (e não versionar ele, adicione ele no `.gitignore` da sua aplicação), e veja se o problema continua. Aqui eu criei um teste no arquivo `app/utils/pagination/pagination.test.js` e ele mostrou corretamente o teste =)

---

Sobre o linter, o problema é que você não está executando a função de callback que a task do gulp recebe. Seu código está assim:

```js
cdm.on('close', () => cb)
```

A função `cb` deve ser executada dentro da função passada para o evento `close`. O código deveria estar assim:

```js
cdm.on('close', () => cb())
```

=)

**Comment by 0v3lh4** [comment]
@leandromds Tive vários problemas com o jest-cli ^23 no windows. Fiz o downgrade para a versão 22.4.4 e resolveu.

Se quiser tentar...
yarn upgrade jest-cli@22.4.4 --dev

**Comment by fdaciuk** [comment]
Oi @leandromds! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)

**Comment by leandromds** [comment]
Fala @fdaciuk consegui resolver sim, ontem eu fiz as alterações e os ajuste que vc recomendou e deu tudo certo!  agradeço a sua ajuda e a ajuda do @0v3lh4! um abraço

**Comment by fdaciuk** [comment]
Show! Sem problemas @leandromds! Só fechei pra manter a organização mesmo =)
Qualquer coisa, só avisar :D
