### ISSUE TITLE
[M1#A36] Default propTypes

### ISSUE THREAD

**Issue by kaioduarte** [da2k/curso-reactjs-ninja#155]
Boa noite Fernando!

Antes de explicar a dúvida, estou utilizando todas as dependências mais recentes. Estou com um probleminha com a `defaultProp` do módulo `prop-types` do React. Fiz o seguinte (o restante do código está igual ao da aula):

```
const Repos = ({ className, title, repos }) => {
  return (
    <div className={className} >
      <h2>{title}</h2>
      <ul>
        {
          repos.map((repo, idx) => (
            <li key={idx}>
              <a href={repo.link}>{repo.name}</a>
            </li>
          ))
        }
      </ul>
    </div>
  )
}

Repos.defaultProp = {
  className: '',
  repos: []
}

Repos.propTypes = {
  className: PropTypes.string,
  title: PropTypes.string.isRequired,
  repos: PropTypes.array
}
```

Entretanto, se eu não passar a propriedade `repos` no uso do componente, estou obtendo o seguinte erro: `Uncaught TypeError: Cannot read property 'map' of undefined`. Há alguma coisa a se fazer?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kaioduarte! O problema está no nome da propriedade que você usou: você está usando `defaulProp`, o correto é `defaultProps` (com `s` no final) =)

**Comment by kaioduarte** [comment]
Mais uma vez caindo na trap do typo... :sweat:
Obrigado @fdaciuk!
