### ISSUE TITLE
M2#A114 duvidas nesse video

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#156]
fala daciuk,
cara fiquei com dúvidas em relação a esse cod que vc fez aqui
```
{isSaving !== null && (
    ...
 )}
```
não etendi o porque do  && 
e outra duvida é sobre o {children}  ele tem que ter esse nome? mas eu caso eu usa-se um span ele que seria renderizado? não entendi muito sobre isso

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! Essa expressão é chamada de _curto circuito_ (ou _short circuit_).

A regra é a seguinte:
- se o valor passado antes do `&&` for _truthy_ (convertido para booleano retornar `true'), então o valor após o `&&` será renderizado. No caso, se `isSaving !== null` retornar `true`, então o código que vem após o `&&` é renderizado.

- já se esse valor que vem antes do `&&` for _falsy_ (convertido para booleano retornar `false`), então esse valor será retornado.

JavaScript puro e simples =)

Sobre o `children`, essa é uma prop especial do React para renderizar componentes que são colocados "dentro de uma tag".

Volta um pouco lá no módulo `#1` que tem uma aula que eu explico sobre essa prop =)

**Comment by LucasCMota** [comment]
Se me permite acrescentar esse exemplo sobre o curto circuito
```
console.log( true  && false )// false
console.log( false && true  )// false => short circuit
console.log( false && false )// false => short circuit
console.log( true  && true  )// true
```
```
console.log( true  || false )// true => short circuit
console.log( false || true  )// true
console.log( true  || true  )// true => short circuit
console.log( false || false )// false
```
no caso do operador `&&`, como ele precisa que as duas sentenças sejam verdadeiras,  nos dois exemplos do meio quando o interpretador do javascript encontra um false ele não vai verificar nunca a segunda, porque não faria sentido ja que precisa que as duas sejam `true.`

com o operador `||` se a primeira senteça for `true` o interpretador nao vai verificar a segunda pois ele so precisa que uma seja `true`. Espero ter ajudado.

**Comment by fdaciuk** [comment]
Quase isso @LucasCMota! Só tem que levar em consideração que o curto circuito avalia apenas **a primeira** expressão, não as duas.

Usando o `&&`, se a primeira for _truthy_, ele retorna a segunda. Se a primeira for _falsy_, ele retorna essa primeira.

Já com o `||` acontece o contrário:
Se a primeira for `truthy`, ele retorna essa primeira. Já se a primeira for `falsy`, ele retorna a segunda =)

Pra facilitar:

```js
console.log(true && false) // false -> mas não retorna "false" pq as duas expressão juntas são false, e sim porque a primeira é truthy. 

Outro exemplo seria:
console.log(true && null) // null -> veja que o retorno não é "false" e sim "null", pois como a primeira expressão é "true", a segunda expressão é retornada =)
```

**Comment by angelilton** [comment]
ok compleendi até tinha entendido a logica mas como estava com isso na cabeça de que o && tem que ser os 2 verdadeiros achei entranho não tem outa comparação
