### ISSUE TITLE
[M2#A23] Bug na implementação do reduce

### ISSUE THREAD

**Issue by kaioduarte** [da2k/curso-reactjs-ninja#157]
Boa noite Fernando!

Na implementação do _reduce_ tem um _bug_, por não considerar o índice inicial como 1 quando não é passado o valor inicial.

![image](https://user-images.githubusercontent.com/11046907/42550122-1d9927f8-84a6-11e8-8599-88a847450aac.png)

Edit: Notei agora que na implementação do reduceRight do Node o índice inicial é 0 :confused: :skull: 

![image](https://user-images.githubusercontent.com/11046907/42551532-14bcf6a2-84ae-11e8-8989-42bafcf18c56.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @kaioduarte! Muito obrigado por reportar =)
Vou gravar uma aula do futuro voltando nesse ponto para adicionar mais um teste e corrigir isso =)

**Comment by fdaciuk** [comment]
Oi @kaioduarte! Só pra avisar que esse bug está anotado aqui! Ainda não gravei a aula, mas estou preparando atualizações para os módulos 1 e 2 do curso, e vou levar esse bug em consideração na hora de regravar, ok?

Por enquanto vou fechar a issue, mas se você tiver qualquer problema, só avisar :)
