### ISSUE TITLE
Desanimador, essa é a palavra chave

### ISSUE THREAD

**Issue by arivaldonsilva** [da2k/curso-reactjs-ninja#159]
Você inicia no curso gratuito e nem configuração de ambiente vc consegue fazer. Não é para mim este curso, acredito eu.

@fdaciuk

**Comment by LucasCMota** [comment]
Vi um video uma vez de um professor de filosofia que mudou meu modo de pensar em relação ao que você acaba de falar, o que ele fala se aplica a qualquer area de conhecimento. vou deixar o link espero que lhe ajude [https://www.youtube.com/watch?v=fDBGY4UiCwA](url)

Se outras pessoas conseguem você também consegue!

**Comment by fdaciuk** [comment]
Oi @arivaldonsilva! Me diga qual problema você está tendo que eu te ajudo a resolver =)
Assim como o vídeo que o @LucasCMota postou: na nossa área não há nada que seja impossível! Se você quiser, você aprende, e eu estou aqui pra te ajudar no que for preciso, ok? =)

**Comment by fdaciuk** [comment]
Oi @arivaldonsilva! Vou fechar a issue, mas conte comigo sempre que precisar, ok? =)
