### ISSUE TITLE
M2#A34 - Publicando em "Produção"

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#16]
Boa tarde @fdaciuk, beleza?

1 - Como uma forma de testar o bundle de produção que geramos gerado, criei um repositório separado para o github-app no meu GH e gerei uma GitHub Page. Porém, está dando 404. 

Será que pode ser algum problema no webpack? Ou é na Github Page mesmo? Não sei o que fiz de errado, porém também não sei se essa é uma forma boa e eficaz de realizar esse teste.

Repositório: https://github.com/gabrielferreiraa/github-app

2 - Colocando isso no webpack:
```
new htmlPlugin({
    title: 'GitHub App',
    template: path.join(__dirname, 'src', 'html', 'template.html')
})
```

Ao invés de buscar um `index.html` na raiz ele busca o que está em `src/html` ? Não compreendi mt bem essa parte.

3 - Uma outra dúvida que me surgiu após essa aula, com minificação (uglify), e geração de bundle, é como irei utilizar o pré processadores CSS por exemplo. Ou um autoprefixer no gulp, enfim. Uma coisa que faz parte do nosso dia dia, agora com apenas 1 arquivo css/js para toda a aplicação.

Abraço!

**Comment by gabrielferreiraa** [comment]
Para funcionar a GH Page, precisei dar um `/dist` na URL.
https://gabrielferreiraa.github.io/github-app/dist/

Está certo isso?

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa! Vamos lá ;)

1) O bundle de produção é gerado dentro do diretório `dist`. É esse diretório que você deve enviar para produção :)

Basicamente, a ideia é a seguinte: o diretório que você configura em `output.path` no `webpack.config.js` é o diretório usado para criar todos os assets (arquivos estáticos, finais, que não dependem de compilação, e podem ser acessados diretamente via browser).

2) Esse trecho de código é a configuração para gerar o HTML pelo webpack. Ele vai usar como template o html que você passou na propriedade `template`, e gerar o HTML no diretório que você configurar como `output.path` no `webpack.config.js`.

3) Nas aulas `#36` e `#37` eu mostro como usar outras opções para CSS. Mas, basicamente, você precisa simplesmente baixar o `loader` que você quer usar - `stylus-loader`, `sass-loader`, etc - e adicionar na entrada de loader de CSS:

```js
{
  test: /\.styl$/,
  include: path.join(__dirname, 'src'),
  loaders: ['style', 'css', 'stylus']
}
```

Isso vai fazer com que, ao encontrar um arquivo que termine com `.styl`, ele aplique os loaders na ordem (do último para o primeiro):
- stylus-loader - para transformar o stylus em CSS;
- css-loader - para resolver `url()` como se fosse um `require()` no JS;
- style-loader - para criar a tag `style` na aplicação.

A ideia é mais ou menos essa.

Nesse módulo, ainda vamos ver várias configurações de loaders, que vai deixar mais claro como trabalhar com essa parte usando  o webpack :)

Qualquer dúvida, só avisar!

**Comment by gabrielferreiraa** [comment]
Ficou claro sim, valeu pela resposta esclarecedora :D

**Comment by fdaciuk** [comment]
Qualquer coisa só avisar! :D
