### ISSUE TITLE
Dúvida sobre criação de component

### ISSUE THREAD

**Issue by lmarcosss** [da2k/curso-reactjs-ninja#160]
Estou com a seguinte dúvida, quero criar um component de botão por exemplo, no entanto, a minha intenção é criar um que será usado de várias maneiras, acredito que até seja esse o intuito de criar componentes... A minha ideia é fazer como se fosse um "bootstrap" personalizado, o que seria mais correto? eu criar um componente de botão e depois conforme houver necessidade ir criando outros botões que herdam de botão, ou criar apenas a classe botão e ir utilizando as classes direto no css do próprio componente botão e fazer o uso de flags por exemplo, antes de renderizar etc.........

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lmarcosss! Tem várias formas de fazer isso =)

A melhor forma de fazer vai depender de quão personalizados serão os seus botões.

Se as alterações que você for fazer nos botões for apenas de CSS, a solução mais simples seria criar um componente que pode receber uma prop `kind` por exemplo, onde você passa o "tipo" do botão ("primary", "secondary", etc).

Agora, se o conteúdo interno do botão pode mudar:
- pode ter só texto;
- pode ter ícone;
- pode ter outras tags;
- se tiver ícone, pode estar tanto na direita como na esquerda.

Se for esse o caso, onde você pode ter vários formatos, então o recomendado é fazer uso da prop `children`, pois assim você consegue criar um componente que seria a "casca" do botão, recebendo via  `children` todo o conteúdo interno.

Com essa "casca", que vai ser o componente mais "baixo nível" de botão, você consegue ir criando outros usando ele como base, e apenas passando o `children` conforme a sua necessidade: com ícone, com outras tags, etc.

Enfim: a ideia é tentar compor os componentes sempre no JS, e escrever o CSS uma só vez, ao invés de criar classes no CSS e ficar adicionando essa classe em todo botão na sua aplicação. Se essa classe precisar mudar, você vai ter um baita trabalho =)

Já compondo à partir do JS, você não vai ter essa duplicação, e vai conseguir reutilizar mais facilmente qualquer componente =)

O ponto principal é: depende de como são os componentes que você vai precisar criar =)
