### ISSUE TITLE
[M2#A33] extract-text-webpack-plugin

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-reactjs-ninja#161]
Opa Fernado, tudo certinho? estou com um pequeno problema que não consegui resolver, depois que instalei a dependencia `extract-text-webpack-plugin` esta me retornando o erro `	if(element.loader) return element.loader.split("!") TypeError: element.loader.split is not a function
`

minha configuração do webpack 
```
'use strict'

const path = require('path')
const webpack = require('webpack')
const validate = require('webpack-validator')

const HtmlPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = validate({

  devtool: 'source-map',

  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    path.join(__dirname, 'src', 'index')
  ],

  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name]-[hash].js',
    publicPath: ''
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new ExtractTextPlugin('[name]-[hash].css'),
    new HtmlPlugin({
      title: 'GitHub app',
      template: path.join(__dirname, 'src', 'html', 'template.html')
    })
  ],

  module: {
    preLoaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'standard'
    }],

    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'babel'
    }, {
      test: /\.css$/,
      exclude: /node_modules/,
      include: /src/,
      loader: ExtractTextPlugin.extract('style', 'css')
    }]
  }
})
```

@fdaciuk

**Comment by LucasCMota** [comment]
depois de assistir a aula até o fim e deixar a configuração igual a da aula surgiu um erro diferente` [1] "loader" must be a string`
vou deixar o link do  [repositorio](https://github.com/LucasCMota/GitHub-Search-React)

**Comment by fdaciuk** [comment]
Oi @LucasCMota! Vou rodar seu projeto aqui e já te dou um feedback do que pode ter acontecido =)

**Comment by LucasCMota** [comment]
uhuuu!!! agora foi, abrigada!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D

**Comment by LucasCMota** [comment]
Como você fez para identificar que era um erro de versão?

**Comment by fdaciuk** [comment]
@LucasCMota eu dei uma olhada novamente na aula =)

Ao finalizar a instalação, a versão da lib instalada é exibida no terminal! Depois foi só desinstalar a versão atual e tentar instalar a versão usada na aula =)

Basicamente tentativa e erro mesmo, mas a probabilidade de ser a versão era grande, já que o webpack mudou algumas coisas na v4 =)

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer coisa, só avisar =)
