### ISSUE TITLE
M3#A77 - Ajuda com o get no Firebase

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#162]
Não estou conseguindo pegar os dados que nem na aula. :(

O erro é: Error: permission_denied at /videos: Client doesn't have permission to access the desired data.

E também esta dando aviso no console do mode de usar o firebase:
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the CDN builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

Código: https://github.com/hjdesigner/redux/tree/master/49-reactflix/06

![captura de tela 11](https://user-images.githubusercontent.com/2280313/43096778-83396138-8e90-11e8-90fa-f7002a1906ff.png)

![captura de tela 12](https://user-images.githubusercontent.com/2280313/43096779-835946a6-8e90-11e8-96f0-e6ab5a6b079e.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Nas aulas nós usamos o "Realtime Database" (que você pode selecionar ali ao lado do título "Database")

Nesse caso, você está criando as entradas no "Cloud Firestore", que é um pouco diferente do que foi mostrado nas aulas =)

**Comment by hjdesigner** [comment]
Que burro que eu sou kkkk
Quando criei o database ele foi direto para o cloud, eu vi que estava diferente mais achei que era coisa do google.

Obrigado pela ajuda 8)

**Comment by fdaciuk** [comment]
Relaxa =)

Eles mudaram recentemente, esse Cloud é mais moderno :D 

Mas qualquer coisa, pode gritar aqui =)
