### ISSUE TITLE
M2#A34 erro de execução 

### ISSUE THREAD

**Issue by LucasCMota** [da2k/curso-reactjs-ninja#164]
Fernando estou com esses dois avisos console, é normal? 

Subindo com npm start
![captura de tela de 2018-07-25 01-36-06](https://user-images.githubusercontent.com/13294634/43179874-6c5d07fa-8fab-11e8-85a1-e6b30b22ed62.png)

Subindo na pasta dist com  python server
![captura de tela de 2018-07-25 01-36-11](https://user-images.githubusercontent.com/13294634/43179812-313b120c-8fab-11e8-8343-3b868fe9b1a0.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Na verdade pode ser um problema, se você precisar desse `bundle.js`, que está dizendo que não está sendo encontrado nesse caminho =)

O que você está tentando fazer? Rodar a versão de desenvolvimento, ou gerando a versão de produção e tentando rodar ela? 

Passa o link do seu projeto que eu dou uma olhada =)

**Comment by LucasCMota** [comment]
eu fiz as duas formas,então aprenseta erros diferentes [repositorio](https://github.com/LucasCMota/GitHub-Search-React)

**Comment by fdaciuk** [comment]
Beleza, já vi o problema =)

Na aula `M2#A32`, nós deixamos para que o webpack insira dinamicamente o script no nosso HTML, então é necessário remover aquela entrada `<script>` que tem no `index.html`, beleza? =)

Fazendo isso, o erro já vai sair =)

Agora, sobre a versão de produção, não é com o mesmo comando de desenvolvimento (`npm start`) que vamos subir a aplicação.

Veja que os arquivos de produção são gerados no diretório `dist`. Tudo o que tem nesse diretório pode ser servido de forma estática que já vai funcionar, sem webpack, sem nada =)

Pra isso, só é necessário um servidor que sirva esses arquivos de forma estática =)

Na aula, eu mostro como fazer isso usando o servidor estático do Python.

Mas se você não tiver ele instalado, e quiser uma forma mais fácil, você pode fazer via Node.js:

Apenas instale no seu projeto, como dependência de desenvolvimento, o http-server:

```
npm i --save-dev http-server
```

Então, crie uma entrada no `package.json` para usar o `http-server`. O que ele vai fazer é simplesmente servir o diretório configurado como se estivesse em um servidor mesmo, e você vai conseguir acessar no seu browser via `localhost:<ALGUMA_PORTA>`.

Para fazer isso, só adicione na entrada "scripts" do seu `package.json` uma entrada, por exemplo, `server`:

```
"scripts": {
  // aqui vai ter as outras entradas "start" e "build". Deixe como estão, e só adicione a entrada "server" abaixo
  "server": "http-server dist"
}
```

Então, ao executar o comando `npm run server`, todo o conteúdo de `dist` será servido, e sua aplicação estará funcionando como se estivesse em produção =)

**Comment by fdaciuk** [comment]
Dê uma olhada também no seu webpack.config de produção: o nome da variável de ambiente é `NODE_ENV` (com underline), não `NODE-ENV` (com traço) =)

**Comment by LucasCMota** [comment]
dentro da pasta dist, nao esta sendo gerado o bundle, esta gerando o index.html , hash.css e hash.js,

**Comment by LucasCMota** [comment]
@fdaciuk, desculpa pela demora a dar o retorno, estava dando uma revisava no que ja estudei, foi erro meu não ter atentado para o fato de não ter removido a entrada de script dentro do index.html, ja está funcionando tudo ok, Obrigada!

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer coisa só avisar =)
Só lembre de ajusar o `NODE_ENV` também, pois você poderá gerar um bundle muito grande, com código desnecessário, quando gerar a versão de produção =)

**Comment by LucasCMota** [comment]
sim, eu consertei esse erro também =)

**Comment by fdaciuk** [comment]
Show!
