### ISSUE TITLE
[M2#A08] - Windows - erro no watch do jest

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-reactjs-ninja#165]
Daciuk, quando rodo o watch do jest no windows, estou recebendo esse erro:

```
Failed to collect coverage from C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja
Da2k\Exercicios\m02\jest-in-practice\package.json
ERROR: Unexpected token, expected ; (2:11)
STACK: SyntaxError: Unexpected token, expected ; (2:11)
```

Com isso, ele gera a tabela de informações no terminal totalmente errada. O que pode ser?

Seria melhor remover o node_modules e instalar tudo copiando o package do seu repositório?

O meu package.json esta assim:

```
{
  "scripts": {
    "test": "jest --coverage",
    "test:watch": "npm test -- --watch"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-jest": "^23.4.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "chai": "^4.1.2",
    "jest-cli": "^23.4.1"
  }
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gustavom! Consegue subir seu projeto aqui no GitHub e passar o link? Parece ser um erro de sintaxe no seu package.json, mas olhando isso que você colocou, parece estar ok.

Preciso ver o projeto pra tentar simular o erro local =)

**Comment by fdaciuk** [comment]
Oi @gustavom! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
