### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#166]
Olá, professor! 

Sou aluno de todos os seus cursos.  Comprei o React Ninja 
esses dias e em breve começarei a assistir as aulas e estudar, 
a ementa está muito bacana! :smiley:

Você pode me dizer se haverá aulas sobre React Native? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Nesse curso não vai ter aulas sobre o React Native especificamente, mas todas as técnicas aprendidas no curso poderão ser aplicadas em aplicações usando o React Native =)

O que vai mudar é apenas o ambiente: você terá problemas no mobile diferentes dos que vai encontrar na web =)

**Comment by Roger-Melo** [comment]
Feshow, professor! 😎
