### ISSUE TITLE
Dúvida referent ao React Router no github page

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#168]
Olá!

Quando entro em uma pagina do site e dou reload na pagina ele da 404, local esta funcionando normal, tem mais algum macete para funcionar no servidor?

Site: https://henriquemelanda.com.br/
Github: https://github.com/hjdesigner/my-site-react

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! O GitHub pages foi pensado apenas para páginas estáticas, não para SPAs. Nesse caso, ao tentar fazer reload de rotas, como elas são gerenciadas apenas no frontend, e essa estrutura de diretórios não existe fisicamente no servidor, você vai receber um erro 404 mesmo (se quiser entender na prática esse problema, dá uma olhada nas primeiras aulas do módulo 4, onde eu falo sobre isso).

A solução para o seu caso seria usar algum servidor que esteja preparado para SPAs, como o [now](https://zeit.co/now), por exemplo =)

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
