### ISSUE TITLE
Animações com React

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#169]
Tudo bem @fdaciuk ?
Qual ferramenta, pacote, ..., que você conhece/recomenda utilizar para fazer animações junto com react ?  

@fdaciuk

**Comment by fdaciuk** [comment]
Opa! Na verdade, qualquer lib de animação vai funcionar bem =)
Especificamente para React, tem algumas que são bastantes conhecidas:
- [React Motion](https://github.com/chenglou/react-motion)
- [React Transition Group](https://reactcommunity.org/react-transition-group/)

Mas você pode usar GSAP tranquilamente, por exemplo =)

Alguns outros links que podem ajudar:
- https://reactjs.org/docs/animation.html
- https://react.rocks/tag/Animation
- https://github.com/FormidableLabs/react-animations
- https://medium.com/react-native-training/react-animations-in-depth-433e2b3f0e8e
- https://mdbootstrap.com/react/css/animations/

**Comment by willianrssi** [comment]
Valeu @fdaciuk, acho que vou aproveitar que o @willianjusten lançou um curso novo na udemy sobre o greensock, vai ser extremamente útil !!!

mais umas vez obrigado.

**Comment by fdaciuk** [comment]
Boa! Vai fundo que o curso parece ser ótimo mesmo =)
Qualquer coisa, só avisar :D
