### ISSUE TITLE
Conflito de versão no babel

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-reactjs-ninja#17]
Fala @fdaciuk blza? tive um imprevisto aqui estou no começo do curso e tinha importado a ultima versão do babel 6. alguma coisa e não estava indo por nada, resolvi colocar a 5. alguma coisa q no caso do vídeo era a que você usava, e funcionou. 
![babelerror](https://cloud.githubusercontent.com/assets/1440797/22408885/ee249e4a-e667-11e6-8a4f-bf712cd46608.png)

vou dar sequencia no curso, no caso pelo que entendi algo que era necessário foi removido do babel 5 pra 6, preciso me preocupar?

**Comment by fdaciuk** [comment]
Fala @brunotortelli! =)

Então, para rodar direto no browser, o melhor é pegar a versão que está na documentação do React. Essa vai funcionar certinho.

Mas isso você não vai usar em produção, é somente para tetes rápidos mesmo. Seguindo o curso eu vou mostrar como é o caminho correto que você deve seguir para usar para desenvolvimento e produção =)

Mas pra esse caso específico do babel pra usar no browser e compilar JSX _just in time_, precisa ser a versão 5 mesmo.

Deu pra entender?

**Comment by brunotortelli** [comment]
deu sim eu vi vc falando isso na parte 6 haha, eu to com uma ideia meio ousada que eu vou colocar num futuro ai se eu conseguir desenvolver em um site de paroquias, o caso e o seguinte o site da diocese centraliza as paroquias e muita gente ta querendo um tipo de calendario, ai eu pensei em criar uma aplicação por fora do WP que eu vou acoplar em uma pagina la, no caso seriam blocos com data hora paroquia referente e o evento, e isso teria alguns filtros, pelo que eu vi da pra usar o react pra isso e eu poderia abstrair alguns detalhes pra ele poder ser reutilizável, a minha duvida seria como eu conseguiria deixar fácil de ser alimentada essa aplicação e se possível que a interface pra alimentar pudesse ser acessada do WP mesmo, ou de fora, mas como não serei eu que alimentarei, que fosse algo que alguém que posta no WP conseguisse executar sem problemas, e depois caso tenha sucesso portar isso pra apps mobile.

**Comment by fdaciuk** [comment]
Legal @brunotortelli! Dá pra fazer isso sim =)
O [WP tem uma API Rest](http://v2.wp-api.org/) que você pode consumí-la com React no seu tema =)

**Comment by brunotortelli** [comment]
que massa, @fdaciuk cara to com uma duvida noob aqui, eu fui usar o examples, porem na ora de dar npm start não rola, ai isso me traz a outra duvida, por ex digamos que eu vou começar um app do 0 e tenho aquela estrutura básica nossa, como eu faço pra instalar as dependências definidas no json? e no caso do examples eu copiei as paginas pro meu pc, e to de dentro delas dando npm start, isso ta errado? eu vi a outra questão do amigo sobre material UI, que é o padrão atual do google, eu queria saber tbm se tem como eu criar componentes de styleguides, como se fossem temas pros meus apps. o curso ta muito foda, mal vejo a hora de por em pratica.

**Comment by fdaciuk** [comment]
Fala @brunotortelli =)
Então, para testar o que está em _examples_, é só entrar em algum diretório que tenha o `package.json`, e rodar dois comandos:
`npm install` e `npm start`

Ou, se for usar o Yarn: 
`yarn` e `yarn start`.

=)

Provavelmente deu algum erro porque você não instalou os pacotes antes (estou certo?) =)

Em breve nós vamos ver também sobre essas libs que tem estilos prontos (Material UI, Bootstrap, etc), e aprender a criar componentes reaproveitáveis de verdade, sem precisar ficar replicando marcação HTML :)

Que bom que tá curtindo o curso! Qualquer dúvida, só avisar :D
