### ISSUE TITLE
[M2]#A92 - Querendo mudar o setState pra setar linhas true ou false

### ISSUE THREAD

**Issue by michelribeiro** [da2k/curso-reactjs-ninja#170]
Tenho o seguinte cenário.

Abaixo eu passo para uma função o que recebo da api (data.LOSE_CD_STATUS_CODE) que vem 200, 404 ou 500:

`<td className={this.state.status ? 'error': 'normal'}>
{this.statusServidor(data.LOSE_CD_STATUS_CODE)}</td>`

Na função eu recebo esse valor e tenho que verificar qual número, se for 404 eu quero ativar a classe erro.
Ae, a função é essa abaixo:
`statusServidor(status) {
        if(status === '200') {
            this.setState({status: true})
        }
        return status
    }` 
Não funciona, dá erro falando que não posso mudar o setState dessa forma.
Como eu faria pra mudar o state de cada linha caso o retorno 404 ?
O erro!
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

@fdaciuk

**Comment by michelribeiro** [comment]
Entendi.
Porém, não estou sabendo executar o que quero no código.
Já vi que teria  que usar o filter, certo ?
Segue o código.

```
import data from "../db.json";
class Main extends Component {
    constructor() {
        super()
        this.state = {
            classStatus: ""
        }
    }

    filterInfoData(data) { //funcao pra passar para o map o conteudo
        // quero retornar o data para o map consumir e setar a classe com erro quando o LOSE_DS_URL     
       // for igual a 404
        return data.filter((i) => {
            return i.LOSE_DS_URL
        })
    }
    render() {
        return (
            <div>
                <Table striped bordered responsive hover>
                    <tbody>
                    {
                        this.filterInfoData(data).map((data, key) => {
                            return (
                                <tr key={key}>
                                    <td className={classStatus}>
                                        {data.LOSE_CD_STATUS_CODE}
                                    </td>
                                </tr>
                            ) 
                        }) 
                    }
                </tbody>
                </Table>
            </div>
 )}}
```

Gostaria de setar a classe como erro se o .LOSE_DS_URL fosse 404 e normal se fosse 200.
Abs

**Comment by fdaciuk** [comment]
Entendi seu problema. Mas o `data` vai vir de um JSON estático mesmo? Se sim, como os valores após o primeiro render não precisam ser modificados, não há necessidade de usar state.

Você pode só fazer essa verificação com um ternário ao passar a class para o seu elemento.

Ao invés de:

```jsx
<td className={classStatus}>
```

Seria só fazer:

```jsx
<td className={data.LOSE_DS_URL === 404 ? 'erro' : 'normal'}>
```

É isso que você queria fazer?

**Comment by michelribeiro** [comment]
Então, utilizei o JSON estático pra elucidar a pergunta, rs.
Já fiz dessa forma testando no próprio elemento se o retorno é um valor com o ternário. rs
Estou querendo entender mesmo como eu devolvo pra data os valores tratados da forma que eu quiser.

Tenho vários problemas pra resolver nesse sentido.

Exemplo 1:
Consumo a api da faculdade e trago as datas das provas que vem no formato timeStamp, tenho que converter em date, pegar a data de hoje e diminuir pela data que veio da prova e se for menor a prova já aconteceu!

Exemplo 2:
Quero no data.URL_QUE_VEIO fazer um replace. Vem assim http://wwww.site.com.br/api/resto_da_url_1
Quero apagar essa url grande e deixar somente depois da /api/ (resto_da_url_1), sei que tenho que usar regex pra isso, porém como eu vou servir o data com essa alteração que não estou sabendo ! 

Consegui me expressar ?

Sobre eu poder setar o novo state em um objeto eu já entendi. Eu tinha um data.map() e nesse looping estava chamando uma func pra alterar o estado de um elemento, já mudei meu pensamento. Estou chamando o map() assim this.funcao_pra_manipular_api(data).map().
O problema agora é o que relatei acima, como manipular modificando os dados como eu quero ?


@fdaciuk

**Comment by fdaciuk** [comment]
Certo! Vamos tentar resolver um problema por vez! O primeiro é o ponto do exemplo 1: você precisa pegar os dados que vêm do request, e normalizar eles para usar no render() da forma que você precisa.

Pergunta: como está a função que faz o request e recebe os dados?

**Comment by michelribeiro** [comment]
Eu irei utilizar o axios ou o próprio fetch para manipular o objeto, mas agora esta direto na chamada no topo do arquivo como vc viu
```
import data from '../db.json';
```
A manipulação anteriormente estava assim: 
```
data.map((data, key) => {
```
Agora esta assim (Como vc me falou eu não posso mudar o state de um objeto que esteja no render dessa forma):
```
this.filterInfoData(data).map((data, key) => {
```

A função this.filterInfoData(data) recebe data e quero entender como manipulo esse data pra popular corretamente dentro do render.
Ex:
```
{data.date}
{data.url_tratada_pelo_regex}
```
@fdaciuk

**Comment by michelribeiro** [comment]
Surgiu uma outra dúvida no que você disse acima, para eu utilizar o ternário.
```
<td className={data.LOSE_DS_URL === 404 ? 'erro' : 'normal'}>
```
Nesse caso, eu já  até tinha feito aqui dessa forma, porém eu queria entender como eu consigo  acumular uma quantidade para poder exibir como exemplo abaixo:

(12 Erros 404)   - (10 Erros - 500)

@fdaciuk

Obs: Desculpa ae a enxurrada de perguntas, mestre. Mas, estou em um ritmo brabo e só estou perturbando aqui pq esgotei no  google.

**Comment by fdaciuk** [comment]
@michelribeiro para responder a essas perguntas, eu preciso ver como está seu código, senão não tem como eu te apontar onde está o seu erro, saca? A resposta pra resolver é exatamente a que eu dei na primeira resposta da issue, mas para resolver o seu problema, preciso ver como está seu código, senão fica difícil entender o contexto =)

Vi que você compartilhou seu projeto, vou dar uma olhada nele e te respondo por lá, ok? =)

Vou fechar a issue aqui, mas se você achar necessário, podemos reabrir se ainda tiver alguma dúvida específica que precise ser tirada aqui =)
