### ISSUE TITLE
M2#A45

### ISSUE THREAD

**Issue by gregoryfm** [da2k/curso-reactjs-ninja#174]
Daciuk,

Existe alguma diferença de exportar o objeto ou a função?

Pelo que vi no video, continua tendo a duplicação de config, a diferença é que uma é passada via objeto e outra via função.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gregoryfm! Na verdade, usando a função, apesar de eu ter mostrado nessa aula a adição do preLoader de forma manual, você tem a opção de extender uma configuração sua e concatenar com a configuração atual do storybook.

Mais pra frente você vai ver que vamos separar o que é comum para todos os ambientes para facilitar o reuso =)

**Comment by fdaciuk** [comment]
O loader de JS você não pode sobrescrever, pq o storybook mesmo não vai deixar. O arquivo final de configuração é exportado internamente pelo storybook, então ainda que você tente sobrescrever a configuração do loader de JS, no final ele vai pegar essa sua configuração e sobrescrever o loader de JS pelo dele =)

A ideia principal de usar funções é apenas quando você quer adiciona algo em algum loader específico do storybook. No caso que eu mostrei, era pra adicionar algumas opções ao loader de CSS que ele já tem. 

Senão você pode só usar um objeto mesmo e boa =)

**Comment by gregoryfm** [comment]
Massa, novamente obrigado pelo esclarecimento.

**Comment by fdaciuk** [comment]
=)
Qualquer dúvida, só avisar!
