### ISSUE TITLE
Problemas com a versão do React usada no curso

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#175]
Isso aqui é uma dica pra quem também ta fazendo o curso agora. Não sei se estou postando isso no lugar certo, mas quando postar acredito que alguem vai me informar e tudo se resolve. A versão do React usada no curso é a 15.1.0, para quem ta fazendo o curso agora como eu, sugiro manter essa versão se não você verá erros no console como: "React.createClass is not a function"... e entre outros. Isso se deve ao fato do React nas versão mais recente ter removido algumas coisas da versão que esta sendo ensinada no curso. Caso queira usar a versão mais nova(16.4.2) sugiro pesquisar as funções novas que substituem as antigas. Quebrei a cabeça um monte porque eu escrevia EXATAMENTE o mesmo código que o professor porém dava erro no console, então fica ai a dica para quem ta começando também. Abraços e bons estudos

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! É isso mesmo =)
Logo no início do curso, eu coloquei algumas aulas com o nome de "Aula do Futuro", onde eu falo exatamente isso, e peço para seguir as versões exatas que estão nesse arquivo:

https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md

Tem também uma mensagem no README do repositório alertando para isso:
https://github.com/da2k/curso-reactjs-ninja#problema-com-as-vers%C3%B5es-das-depend%C3%AAncias

De qualquer forma, no decorrer do curso vamos fazendo algumas atualizações, e em breve teremos um módulo falando apenas sobre as novidades que estão surgindo React =)

Se tiver algum outro lugar que você acha que seria interessante deixar essa informação, onde facilite para que todos os alunos consigam saber disso, por favor, me deixe saber =)

**Comment by RodrigoWebDev** [comment]
É verdade... como eu consegui resolver o problema eu prossegui normalmente com o curso e vi essa "Aula do futuro". Acabei criando esse post desnecessariamente kkkk, peço perdao. E deixo também uma sugestao... Coloca um video no começo do modulo 1 explicando esse problema com as versões, tenho certeza que muita gente ja ficou ou pode ficar travado por esse problema. Eu por exemplo só peguei os links dos scripts la do CDN e nem me atentei para a versão que estava diferente, quebrei a cabeça por horas. Obrigado pela resposta e abraços

**Comment by fdaciuk** [comment]
Capaz, não precisa se desculpar =)
Sempre que tiver dúvidas / dicas / sugestões, pode postar aqui, sem problemas =)

No módulo 1 eu não adicionei nenhuma aula do futuro, pois lá eu falo a versão exata em que usamos o React à partir do CDN. Apenas no módulo de webpack é que instalamos sem se preocupar com a versão. Nesse caso, é necessário instalar a versão 15.4 pra seguir sem problemas =)

Mas agradeço demais a sugestão. Vou colocar uma aula do futuro logo no início do curso falando sobre isso, acho que vai ajudar mesmo os alunos a se atentarem para esses casos =)

Grande abraço, e conte comigo para o que precisar =)
