### ISSUE TITLE
[M2#A08] - Erro no watch do jest no Git Bash

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#176]
E aí, @fdaciuk, blz? O `watch` não roda pra mim, dá erro, funciona apenas o `watchAll`, estou usando o Git Bash como terminal e quando tento rodar o `npm run test:watch` aparece:

`--watch is not supported without git/hg, please use --watchAll`
`npm ERR! Test failed.  See above for more details.`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! @ test:watch: `npm test -- --watch`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the @ test:watch script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2018-08-22T18_09_23_216Z-debug.log`

Quando uso `watchAll` funciona, mas sem as opções q vc mostrou no video:

`Watch Usage
 > Press o to only run tests related to changed files.
 > Press p to filter by a filename regex pattern.
 > Press q to quit watch mode.
 > Press Enter to trigger a test run.`

Seria problema do Git Bash, ou da versão das dependências?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Consegue subir seu projeto aqui no GitHub pra eu dar uma olhada? Aí passa o link aqui que eu já te digo qual pode ser o problema =)

**Comment by 0v3lh4** [comment]
Já tive o mesmo problema...
O jest --watch precisa do git ou mercurial para funcionar.
Executa git init no diretório do seu projeto que a opção --watch deve funcionar.

https://github.com/facebook/jest/issues/5725

**Comment by fdaciuk** [comment]
Boa @0v3lh4! =)
@hiwoshu testa ae e diz pra gente se funciona assim =)

**Comment by hiwoshu** [comment]
Então, não funciona. Parece q tem q ser um repositório clonado, ou um _branch_, pra funcionar.

Tentei com o `git init`, e apareceu um monte de erro.

O q deu certo foi trocar o terminal, testei em outros terminais e deu tudo certo, mas com `watchAll`, e só no Git Bash q não aparecem as opções. Mas já estou usando outro terminal e agora tá tudo certo.

Obg.

**Comment by fdaciuk** [comment]
Perfeito @hiwoshu =)
