### ISSUE TITLE
[M3#A17] - Problemas com o Jest

### ISSUE THREAD

**Issue by mat55** [da2k/curso-reactjs-ninja#177]
Eae @fdaciuk, boa tarde. Estou tendo problemas com o Jest que está achando um erro muito estranho, sendo que eu mal comecei esta aula. O erro que está retornando, é de 'Unexpected token' para os imports que é necessário fazer, do arquivo que vai ser testado e do método 'expect' do chai. Segue o anexo para melhor entendimento:

![image](https://user-images.githubusercontent.com/39055336/44527007-069fd280-a6bc-11e8-8fed-2ec39d3323af.png)

Com problemas nestes dois imports normais. estou com dificuldades para avançar. 

Obs.: Para acompanhar o módulo de Redux, eu criei outro projeto com CRA e criei os jsFile normal.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mat55! Consegue subir seu projeto aqui no GitHub pra eu dar uma olhada? Assim eu consigo baixar aqui e ver o que pode estar faltando =)
Provavelmente é alguma dependência que faltou, ou a falta do arquivo `.babelrc` =)

**Comment by mat55** [comment]
Eae @fdaciuk, então depois que eu li essa issue aqui #72, eu decidi parar com o CRA e estudar no seu boilerplate, porque estava dando muito conflito e eu estava perdendo conteúdo. De qualquer forma, estou com um outro problema. Estou tentando rodar o código ```yarn update-packages```, mas ele retorna este erro: 
```
Error: spawn yarn ENOENT
```
Obs.: Eu acabei de entrar na aula [M3A24], e tive que instalar o yarn, pois o cmder não o estava encontrando.

**Comment by mat55** [comment]
E aproveitando a oportunidade, queria tirar umas dúvidas (achei melhor ser aqui do que criar uma issue, mas se for errado fazer isso, eu crio uma). 

1) Qual a relação entre as actions (no caso das suas aulas action-creators) e os reducers? 
Por que dentro dos **reducers**, eu pego o meu parâmetro _action_, e consigo tirar dele o _type_ e o _payload_ (mesmo sem os tests).

2) E de onde que eu tiro o _type_ e o _payload_ do action?

Agradeço a ajuda e os esclarecimentos. @fdaciuk

**Comment by fdaciuk** [comment]
Oi @mat55! Como é outro assunto, vou pedir pra você criar uma nova issue com a última dúvida, ok? =)

Sobre o problema no `update-packages`, o problema é por conta do windows. Deixei uma nota sobre isso aqui:

https://github.com/fdaciuk/workflow-reactjs#troubleshooting

Dá uma olhada no arquivo `gulpfile.js`, remova a linha `4` e descomente a linha `7`:
https://github.com/fdaciuk/workflow-reactjs/blob/master/gulpfile.js#L4-L7

**Comment by mat55** [comment]
Bom dia @fdaciuk, infelizmente o erro persiste mesmo depois da sua orientação (não mais no **lint,** mas continua para dar **yarn update-packages**). Eu instalei o cross-spawn global e local e depois removi a linha 4 e descomentei a linha 7.

Quanto a minha dúvida, desculpa o incomodo e eu vou abrir uma nova issue.

**Comment by mat55** [comment]
Bom dia professor @fdaciuk, então eu segui as suas orientações e instalei local o `cross-spawn` (usando mesmo o --save-dev), só que infelizmente só funcionou para o `lint`, e não para o `update-packages`, que é o que o comando que eu gostaria de usar.

**Comment by fdaciuk** [comment]
Perfeito! Qual erro é exibido ao tentar rodar os `update-packages`?

**Comment by mat55** [comment]
Perdão professor @fdaciuk pela demora, mas ele esta exibindo o mesmo erro de antes 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
```
A diferença, é que só esta exibindo este erro para o `update-packages`.

**Comment by fdaciuk** [comment]
Show! Consegue subir seu projeto aqui no GitHub pra eu dar uma olhada? Assim eu consigo testar e conferir se o problema é só no windows mesmo =)

**Comment by mat55** [comment]
Bom dia professor @fdaciuk, segue o projeto para você poder dar uma olhada.
https://github.com/mat55/Curso-React-Ninja

**Comment by fdaciuk** [comment]
Oi @mat55! De fato o comando dá alguns problemas (diferentes no linux, mas ainda assim é um problema), por conta da atualização atual das dependências.

Por enquanto, pode ignorar esse comando, ok? =)

Se você tiver qualquer problema com a versão das dependências que você estiver usando, me avise que a gente vai resolvendo caso a caso, ok? =)

**Comment by mat55** [comment]
Então deixa a issue aberta?

**Comment by fdaciuk** [comment]
Vou fechar, mas se você tiver qualquer problema relacionado, só avisar que a gente reabre e eu te ajudo :D
