### ISSUE TITLE
[M1#A11] - Shorthand notation como parâmetro de função 

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#178]
Olá, professor! 

Estou com algumas dúvidas (várias na verdade, vou tentar explicá-las aos poucos).

No código abaixo, o que está acontecendo por baixo dos panos no parâmetro da função  
é isso: `{name: name, lastName: lastName}`?

O objeto criado por parâmetro e o `Title.defaultProps` são o mesmo objeto?

```javascript
'use strict'

import React from 'react'

const Title = ({name, lastName}) => (
  <h1>Hello, {`${name} ${lastName}`}!</h1>
)

Title.defaultProps = {
  name: 'desconhecido',
  lastName: 'Desconhecido'
}

export default Title
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Na verdade, essa sintaxe funciona da seguinte forma:

Esse código abaixo:

```jsx
const Title = ({name, lastName}) => (
  <h1>Hello, {`${name} ${lastName}`}!</h1>
)
```

Se fossemos escrever com a sintaxe do ES5, ficaria assim:

```jsx
var Title = function (props) {
  var name = props.name
  var lastname = props.lastname
  return (
    <h1>Hello, {`${name} ${lastName}`}!</h1>
  )
}
```

Olhando para os dois códigos, veja que, dentro do objeto `props` existem duas propriedades: `name` e `lastname`, correto? 

Veja que no segundo exemplo, em ES5, para criar as variáveis `name` e `lastname` dentro da função, pegando elas do objeto `props`, temos que criar uma por vez.

A ideia da _shorthand notation_ é permitir que você consiga criar novas variáveis que tenham o mesmo nome da propriedade do objeto, "extraindo" os valores dessas propriedades diretamente do objeto, de uma vez só.

Ainda daria pra você fazer da seguinte forma:

```jsx
const Title = (props) => {
  const { name, lastName } = props
  return (
    <h1>Hello, {`${name} ${lastName}`}!</h1>
  )
}
```

Veja que o resultado é o mesmo: nós "extraímos" como novas variáveis as propriedades `name` e `lastname` do objeto `props` =)

No caso do primeiro exemplo, a única diferença é que fazemos isso diretamente nos argumentos da função. A função vai receber um objeto, então nós "abrimos" esse objeto e pegamos somente as propriedades desse objeto de forma nomeada, como se estivéssemos criando novas variáveis com o mesmo nome das propriedades do objeto passado =)

Ficou claro? =)

**Comment by Roger-Melo** [comment]
Começou a clarear, professor. 

Shorthand notation e destructuring são a mesma coisa? 

Acho que o que tem me confundido é que a função espera receber um objeto por parâmetro [1] mas ela não é invocada em momento algum no código. Então eu não vejo esse objeto ser passado como argumento no momento da invocação da função, não existe um `Title({name="Nome", lastName="Sobrenome"})`. Por isso eu havia perguntado se o parâmetro da função está representando o Title.defaultProps [2]

[1]

```javascript
const Title = ({name, lastName}) => ( 
  <h1>Hello, {`${name} ${lastName}`}!</h1>
)
```

[2]

```javascript
Title.defaultProps = {
  name: 'desconhecido',
  lastName: 'Desconhecido'
}
```

**Comment by Roger-Melo** [comment]
Ficou, professor. 

Obrigado pela paciência! Kkk

**Comment by fdaciuk** [comment]
Show de bola! Qualquer dúvida, só avisar :D
