### ISSUE TITLE
Porque usar um servidor local para Front end?

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#179]
Eu entendo que quando usamos linguagem server side (PHP por exemplo) nós temos que iniciar um servidor local, mas porque usar um servidor local para estudar uma framework front end?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! 

A ideia é ter um ambiente sempre o mais próximo possível do que teremos em produção. Você sempre vai precisar de um servidor para servir sua aplicação para o mundo, via protocolo HTTP, independente se essa aplicação tem backend ou não =)

No caso de aplicações como as que estamos aprendendo, normalmente um servidor estático resolve o problema - servidores estáticos apenas servem o diretório do seu projeto como ele é =)

No módulo 4 vamos ver mais a fundo sobre isso, pois vamos falar sobre roteamento de uma aplicação, então esse conhecimento será necessário =)

Mas se ainda ficou alguma dúvida com relação a isso, só avisar =)

**Comment by RodrigoWebDev** [comment]
Entendi! Faz sentido então trabalhar com servidor localmente ! Obrigado pela resposta

**Comment by fdaciuk** [comment]
Sim, faz todo o sentido =)
Qualquer coisa, só avisar =)
