### ISSUE TITLE
M2#A37 - Duvida

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#18]
Fala @fdaciuk, tudo certo? 

Configurei o CSS Modules aqui, seguindo a aula etc. Em ambiente de DEV, deu tudo certo! Porém ao gerar o bundle de produção, ele gera com as classes normais do CSS. Como eu faria para gerar o hashs nas classes em produção também? Ou isso não é uma boa prática?

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa! Provavelmente ao configurar o webpack de produção, ao usar o `css-loader`, deve ter faltado o parâmetro `?modules` =)
Vê ae se é isso :D

**Comment by gabrielferreiraa** [comment]
Boa! Deu certo :) Valeuu

**Comment by fdaciuk** [comment]
\o/
qualquer dúvida, só avisar =)
