### ISSUE TITLE
[MRW#05] - vulnerability found

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#181]
Professor, ao baixar as dependências react e react-dom, conforme o versions-of-dependencies.md, é exibida uma mensagem dizendo que foi encontrada uma vulnerabilidade grave. Você poderia me dizer o porque disso? Devo instalar a próxima versão do webpack-dev-server como mostrado abaixo, nas imagens abaixo? 

Comando executado: 
`npm install --save react@15.4 react-dom@15.4`

Mensagens exibidas: 

![image](https://user-images.githubusercontent.com/29297788/44558596-88731880-a71b-11e8-95e1-69b653604f46.png)
![image](https://user-images.githubusercontent.com/29297788/44558601-8dd06300-a71b-11e8-9512-d2b174112d74.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Não precisa se preocupar com isso no momento por dois motivos:
1) Essa dependência é usada só em ambiente de desenvolvimento, você não vai usar o `webpack-dev-server` em produção;
2) Mais pra frente nós iremos fazer a atualização do webpack e das dependências dele, então fique tranquilo que isso vai ser resolvido mais pra frente =)

Se atualizar agora, provavelmente vai quebrar a configuração atual, já que você deve estar no momento com o webpack 1 =)

**Comment by Roger-Melo** [comment]
Fechou, professor!

**Comment by thiagofrancisquete** [comment]
Boa noite, eu tive o mesmo erro, porém aparecem duas vulnerabilidades... prossigo mesmo assim?
![erro](https://user-images.githubusercontent.com/21160480/51080086-8e629980-16bc-11e9-9b23-c6dd53dea905.png)

**Comment by fdaciuk** [comment]
Oi @thiagofrancisquete! Pode seguir sem problemas, a questão é a mesma do @Roger-Melo =)
A dependência só vai ser usada em desenvolvimento, e mais pra frente nós vamos atualizar de qualquer forma, então pode ficar tranquilo =)
