### ISSUE TITLE
O que é o "Common JS" ?

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#183]
Ouvi voce dizer isso algumas vezes no curso e eu nao faço ideia do que é...

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Isso não é tão relevante nesse início do curso, vamos ver com um pouco mais  de detalhes sobre isso no módulo 5. Mas "Common JS" é o nome dado ao sistema de módulos utilizado pelo Node.js, onde ele usa `require` e `module.exports` para importar e exportar arquivos =)

Na linguagem JavaScript não tínhamos nenhum sistema de módulos ainda, até surgir o _ES Modules_ (usando `import` e `export`). Tudo era global.

Então, quando o Node.js surgiu, ele precisava de um sistema de módulos. Então foi criado o "Common JS" =)

Se quiser saber um pouco mais antes de chegar no módulo 5, posso recomendar alguns artigos que eu escrevi sobre o assunto:

https://blog.da2k.com.br/2015/01/03/como-criar-componentes-js-usando-modulos-amd-commonjs-e-umd-parte-1-3/

https://blog.da2k.com.br/2015/01/04/como-criar-componentes-js-usando-modulos-amd-commonjs-e-umd-parte-2-3/

https://blog.da2k.com.br/2015/01/05/como-criar-componentes-js-usando-modulos-amd-commonjs-e-umd-parte-3-3/

**Comment by fdaciuk** [comment]
Sem problemas @RodrigoWebDev! Fique à vontade para perguntar sempre que tiver dúvidas =)
O importante é conseguir seguir com o curso, e aprender de verdade :D
