### ISSUE TITLE
Source maps nao aparece no dev tools

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#184]
Nao consigo visualizar os arquivos source map no dev tool tanto do chrome quanto no firefox :/

@fdaciuk

**Comment by RodrigoWebDev** [comment]
Problema resolvido... Mas nao sei exatamente como, sei que segui normalmente na outra aula e deu tudo certo

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Que bom que resolveu =)
Provavelmente havia faltado alguma configuração =)

Qualquer dúvida, só avisar :D
