### ISSUE TITLE
Requests interdependentes.

### ISSUE THREAD

**Issue by phillipnunes** [da2k/curso-reactjs-ninja#185]
Olá.

Estou treinando um pouco, e nessa aplicação de teste fiquei com uma dúvida sobre a melhor forma de montar os requests. no final, acabei chamando uma requisição dentro de outra:

[Link para o código](https://github.com/phillipnunes/hacker-news/blob/master/src/App.js)

Dentro da função newsIdList eu chamo a newsItemDetails, pois a segunda depende do resultado da 1ª.

Tem alguma forma melhor de fazer?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @phillipnunes! Legal, essa é uma forma =)

Tem outras formas de resolver o mesmo problema sim, mas vai depender de como você vai querer o resultado =)

Da forma que você fez, ao receber a primeira resposta - que deve ser um array - você faz vários requests, e assim que cada um for terminando você já vai atualizando o estado.

Se você quiser, por exemplo, que o estado seja atualizado apenas ao final de todos os requests, ao invés de fazer um `forEach`, você pode fazer um `map` que irá retornar um array com todas as Promises onde será feito o novo request. 

Então pode usar `Promise.all` para garantir que, somente ao final do request de todos os itens, essa promise será resolvida =)

Enfim, tem várias maneiras de resolver o mesmo problema, tudo vai depender de como você quer que o resultado seja exibido =)

Particularmente acho que dessa forma que você fez funciona bem, já que não vai ser necessário esperar todos os requests antes de começar a exibir os dados na tela para o usuário =)

**Comment by phillipnunes** [comment]
Legal, achei que estava mal feito pois haviam me dito que estava errado. Que eu não deveria fazer AJAX dentro de um loop pois existem problemas como perder o controle do fluxo, no caso de acontecer algum erro em uma das requests eu não saberia onde foi....na verdade, não entendi direito o que ele quis dizer.

Aaaah..comecei aquele 100 dias de código, visando treinar o React e JS. Quando enrosco, uso seu curso como consulta  :)
Progresso até o momento: [Link](https://github.com/phillipnunes/100-days-of-code/blob/master/log.md)

Obrigado por esclarecer a dúvida, acho que vou deixar assim mesmo então.
Abraços.

**Comment by fdaciuk** [comment]
Então, há sim um problema em fazer requests dentro de um loop se de fato você precisa que TODAS as informações sejam exibidas na tela.

Agora pensa no seguinte: se o importante não é ter TODAS as informações na tela, mas sim TER informações na tela, e se alguma der erro, "paciência", não há problema em fazer requests dentro de um loop.

Obviamente alguma pode mesmo se perder - mais ou menos, pq ainda assim vc consegue tratar no catch e tentar fazer o request de novo, mas acho que você pegou o ponto.

No final, a resposta para a solução é sempre um grande "depende". =)

**Comment by phillipnunes** [comment]
Valeu!
