### ISSUE TITLE
Dúvidas sobre Redux

### ISSUE THREAD

**Issue by mat55** [da2k/curso-reactjs-ninja#186]
Bom dia @fdaciuk, estou com algumas dúvidas de como os elementos do Redux trabalham e aqui vão 2 perguntas:

1. Qual a relação entre as actions (no caso das suas aulas action-creators) e os reducers?

Por que dentro dos reducers, eu pego o meu parâmetro action, e consigo tirar dele o type e o payload (mesmo sem os tests).

2. E de onde que eu tiro o type e o payload do action?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mat55! Vamos lá: 

> Qual a relação entre as actions (no caso das suas aulas action-creators) e os reducers?

a ideia de usar o que chamamos de `action-creators` é apenas para abstrair o uso das actions mesmo. Ao invés de ficar sempre passando um objeto com `type` e `payload`, fica mais simples abstrair isso, criando uma função com um nome que diga o que a action vai fazer, e passar via argumento somente o valor realmente necessário para o payload da action =)

Eles não tem relação direta com os reducers =)

---

> Por que dentro dos reducers, eu pego o meu parâmetro action, e consigo tirar dele o type e o payload (mesmo sem os tests).

Quando você faz um `dispatch` de uma action, você passa para o método `dispatch` um `type` e um `payload`, correto? É daí que vem esse objeto `action` dentro do reducer =)
Lembra que eu mostrei o exemplo de como funciona o método `createStore`? Dá uma olhada nessa aula, pois lá eu mostro exatamente esse ponto, onde a action é passada pra frente ao executar o método `dispatch`, e esse método executa o reducer e passa o `state` atual e a action passada para o `dispatch` =)

---

> E de onde que eu tiro o type e o payload do action?

O `type` é padrão do Redux, e sempre obrigatório. O payload é apenas para manter a organização do código. Eu mostrei também que é possível qualquer valor nesse objeto `action`, quando você passa esse objeto para o `dispatch`. Então apenas por questões de organização, usamos sempre o `payload` junto com o `type` que já é obrigatório =)

---

Ficou claro?

**Comment by fdaciuk** [comment]
Oi @mat55! Sabe quando você usa o `dispatch`? É nesse momento você passa o `payload` e o `type`. O objeto passado para o `dispatch` é o que é representado pela variável `action` dentro do reducer:

```js
const action = {
  type: 'SOME_ACTION',
  payload: { id: 1, text: 'Some text' }
}

dispatch(action)
```

Sacou? =)

**Comment by mat55** [comment]
Então professor @fdaciuk, eu estou encerrando seu exemplo de TodoList e, neste exemplo, você cria `action-creators`. Dentro dessas `action-creators` é que nós criamos nosso método `addTodo` que cria um `type` e um `payload`. 
Então quando nós damos o `dispatch` do método `addTodo`, nós estamos passando o `type` e o `payload` para o `reducer`?

**Comment by fdaciuk** [comment]
Exatamente isso @mat55 =)
Porque o retorno do método `addTodo` é um objeto com uma propriedade `type` e uma `payload` =)
A ideia de criar action creators é apenas para abstrair as actions, e deixar mais simples de escrever ao dar o `dispatch` =)

**Comment by mat55** [comment]
Maravilha professor @fdaciuk!! Desculpa mesmo por ficar enchendo de perguntas essa issue e valeu mesmo pela compreensão.

**Comment by fdaciuk** [comment]
Relaxa @mat55! Você não deve ficar com dúvidas! Pode perguntar sempre que precisar =)
Vou fechar a issue, mas se puder ajudar em algo mais, só avisar :D
