### ISSUE TITLE
Dúvida em como usar SVG com React

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#187]
Boa tarde @fdaciuk, estou com uma dúvida na utilização de SVGs com React, como que você aconselha usar ?

@fdaciuk

**Comment by willianrssi** [comment]
Valeu @fdaciuk, na verdade minha dúvida inicial seria em como importar eles!

**Comment by fdaciuk** [comment]
Ah, saquei! Bom, você pode usar de duas formas:
- como componente React, ae você só coloca a tag dentro de um componente React e exporta / importa como qualquer componente;
- ou você usa como imagem mesmo, aí você pode usar como qualquer imagem no seu projeto: ou passando um caminho acessível pelo browser, como qualquer imagem, ou, se tiver o loader do webpack configurado, importar a imagem com `import` e passar a variável para o `src` da sua tag `img`  =)

**Comment by willianrssi** [comment]
Pois é, já usava dessa segunda maneira dentro da tag de `img`, só não sabia se era uma boa prática rsrsrs.

Hoje nessa busca de opções acabei achando um pacote para usar o svg inline: 

`react-inlinesvg`

https://github.com/gilbarbara/react-inlinesvg

valeu =)

**Comment by fdaciuk** [comment]
Boa! Parece uma boa solução =)

De qualquer forma, se eu puder ajudar em algo mais, só avisar :D
