### ISSUE TITLE
MRW09 - [WDS] Disconnected!

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#188]
Ola Professor! Estou recebendo um erro no console acredito ser do Hot Loader. Sabe me dizer o que tem de errado? Se precisar que eu suba os meus arquivos para voce checar é só avisar
![screenshot_12](https://user-images.githubusercontent.com/30677819/44935103-d56f7400-ad45-11e8-9ed1-2b86bd51a93b.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Esse erro normalmente é exibido quando a aplicação perde a conexão com o "webpack-dev-server" (por isso o WDS - Webpack Dev Server) =)

Dá uma olhada se você não derrubou o servidor e depois subiu de novo =)

Se não foi isso, pode sempre subir a sua aplicação aqui no GitHub e já colar o link que eu baixo pra testar, e vejo se pode estar faltando alguma configuração =)

**Comment by RafaelMouraFrontend** [comment]
Isso tb acabou de acontecer cmg, estou tentando debugar aqui

**Comment by RafaelMouraFrontend** [comment]
Acabei de resolver o meu aqui, não sei se foi isso e nem se é o seu caso, mas fica o feedback...
No arquivo webpack.config.js estava usando porta 3000 e no server.js estava usando porta 8000

**Comment by RodrigoWebDev** [comment]
@RafaelMouraFrontend infelizmente não era isso, os dois arquivos estao com a porta 3000, mas obrigado pela sua resposta. @fdaciuk aqui vai o link do rep -> https://github.com/RodrigoWebDev/reactjs-ninja

**Comment by fdaciuk** [comment]
Legal @RodrigoWebDev! Vou baixar o projeto aqui pra testar =)
Uma dica: remova a `node_modules` do seu versionamento. Não há necessidade de adicionar esse diretório =)

Para fazer isso:

1) remova o diretório `node_modules`, com `rm -rf node_modules`;
2) faça o `add` e `commit` com esse diretório deletado;
3) adicione no seu repositório um arquivo chamado `.gitignore` (com ponto na frente mesmo) e coloque nesse arquivo o seguinte conteúdo:

```
node_modules
```

Isso vai fazer com que o diretório `node_modules` seja ignorado no versionamento, na hora de fazer commits :D 

Agora pode comitar normalmente o arquivo `.gitignore` =)

Enfim, foi só uma dica. Vou olhar seu projeto e em breve volto aqui com a resposta =)

**Comment by fdaciuk** [comment]
@RodrigoWebDev baixei o projeto aqui e rodei, mas não deu esse erro que você mostrou.

Me diga quando é o momento exato em que você vê essa mensagem, passando aqui um passo a passo do que você faz desde iniciar a aplicação até ver o erro, pra eu tentar simular, ok? =)

**Comment by RodrigoWebDev** [comment]
@fdaciuk Obrigado pela dica! Acabei de aplicar ela. Então... eu basicamente dou npm start! É só isso que eu faço para rodar o projeto. Se quiser eu gravo minha tela e te mando

**Comment by fdaciuk** [comment]
Show @RodrigoWebDev, faz isso pra eu ver, por favor =)

**Comment by fdaciuk** [comment]
Qualquer coisa, tente fazer o seguinte: remova o diretório `node_modules` e rode `npm install` novamente para instalar as dependências, e depois tente dar o `npm start` e veja se o problema persiste =)

**Comment by RodrigoWebDev** [comment]
Eu ja tinha removido o Node Modules e dado npm start, perceb agorai que a mensagem de erro sumiu, não faço ideia do porque, porém a pagina ainda não atualiza quando eu salvo. O lado bom desse problema, é que ele não me impediu de continuar seguindo curso, apesar de ter ficado menos produtivo kkkk. Infelizmente não consegui colocar o video, aqui nao tem suporte pra isso

**Comment by fdaciuk** [comment]
@RodrigoWebDev, sobre a mensagem de erro, pode ser que o webpack-dev-server tenha se perdido na hora de instalar alguma dependência.. aí removendo a node_modules e instalando novamente ele se "ajusta" xD

Mas legal, que bom que deu certo! Qualquer coisa, só avisar :D
