### ISSUE TITLE
Dúvida/Curiosidade - Componentes React 

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#189]
Eu já escultei um galera falando em criar mini componentes em React para utilizar em sites que já existem.
Tipo uma vitrine feita, ou mudar só uma parte do projeto para react.....
Usando nosso workflow não é possivel, teria como dar um exemplo ou uma dica como procurar isso no google?
Deu para entender? rsrs

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Na verdade dá pra adaptar nosso workflow pra funcionar dessa forma =)
Eu criei algumas libs que faz isso que você precisa: cria o componente e exporta ele para ser usado de forma independente, dá uma olhada nas configurações desse projeto aqui:
https://github.com/fdaciuk/react-trianglify

**Comment by hjdesigner** [comment]
Massa, vou da uma olhada.
Obrigado!

**Comment by fdaciuk** [comment]
Se precisar de ajuda, só gritar =)
