### ISSUE TITLE
[OFF] Dúvida sobre Material Design

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#19]
@fdaciuk, só uma dúvida meio em OFF ao curso.

O intuito de estar fazendo este curso é que vou precisar desenvolver uma aplicação grande (Painel Administrativo) em breve. E decidi fazer em React !

Estava bem preocupado com a questão de layout, como estou usando JSX, vou me perder um pouco para usar folhas de estilo e tudo mais. Dei uma breve pesquisada e acabei caindo aqui: [Material UI](http://www.material-ui.com/#/). Essa seria uma boa alternativa para desenvolvimento? Pois eu vi que tem bastante coisa legal e "pronta". Gostaria que me falasse mais sobre esses Material Designs do React, o que você recomenda e tudo mais.

**Comment by fdaciuk** [comment]
Fala cara! Não é off não, tem tudo a ver =)

Mais pra frente eu vou acabar mostrando algumas soluções como o Material UI. Eu não cheguei a fazer nada muito grande com ele, mas o conceito é o mesmo para qualquer extensão / plugin / módulo externo: provavelmente vai chegar uma hora que você irá querer algo e irá travar no que ele te oferece.

Se no seu projeto não houver problemas quanto a isso, pode seguir tranquilo. Em todo o caso, é sempre interessante isolar tudo o que for externo (ou ao menos o que você percebe que pode ser um problema no futuro). Assim fica fácil de você substituir por outra solução, ou ainda extender as funcionalidades que esse módulo externo te oferece =)

Ficou claro?

**Comment by gabrielferreiraa** [comment]
Ficou claro sim :) Valeu ! 

Vou emendar uma outra dúvida aqui, pode ser? A uns dias atrás fiz umas perguntas em relação ao bundle de produção que geramos.

Não entendi exatamente como vou fazer quando der deploy para produção, pois os arquivos ficam dentro da `dist` (que eu escolhi), ai eu preciso acessar por exemplo: www.gabriel.com.br/dist para poder ter acesso a aplicação. O correto seria eu jogar esse bundle gerado na raiz do projeto? Ou tem algum esquema para colocar no Webpack que ele faz alguma mágica? hahaha 

Essa parte do bundle de produção etc ficou meio obscura pra mim ainda. 

A aplicação em produção depende só daquele `.js` gerado e mais nada?

**Comment by fdaciuk** [comment]
A ideia é essa mesma! O que vai para a produção é somente o diretório `dist`. Por que você mandaria seus arquivos fonte para o servidor de produção? Eles servem somente para você desenvolver, e gerar arquivos otimizados para o servidor de produção.

Da mesma forma que não faz sentido você programar em ES3/ES5, e já escrevendo código minificado, saca? =)

Arquivos fontes (`source` ou `src`) servem para você desenvolver da melhor forma possível. Ao gerar os arquivos que irão para produção, você faz as otimizações que o servidor precisa, e assim tem o melhor dos dois mundos =)

No caso do GitHub pages, você pode fazer de duas formas:

No GitHub, faz sentido você deixar seus arquivos fonte, pois é o lugar onde o código fica centralizado. Mas ele te dá a opção de usar o GitHub pages para jogar seus arquivos estáticos. 

Recentemente, eles atualizaram o GitHub pages para que você possa usar de algumas formas diferentes:
- Ou na branch `gh-pages`, como no início;
- Ou na branch master, se você tiver um `index.md` ou `index.html`, o GitHub usa como `index` da sua page;
- Ou ainda criando um diretório `docs` (normalmente para documentações de libs), e ali você joga todos os seus estáticos.

Nas configurações do seu repositório você encontra a opção para escolher o que se encaixa melhor pra você.

No caso dos projetos que estamos fazendo, você pode simplesmente mudar na configuração do `webpack` para ele gerar os arquivos no diretório `docs` ao invés de gerar no `dist`. Dessa forma, você comita esses arquivos, configura seu repositório para ler do diretório `docs` o GitHub pages e pronto! Já pode acessar sua aplicação de forma bem simples =)

Qualquer dúvida só avisar!

PS.: Vou fechar a issue, mas se tiver mais alguma dúvida relacionada, só comentar aqui que eu reabro, beleza? =)

**Comment by gabrielferreiraa** [comment]
Ok, então. Você disse "...O que vai para a produção é somente o diretório `dist`...". Eu mando para produção só o `index.html`, o `.css` e o `.js` ? 

O resto dos meus diretórios é apenas para desenvolvimento? E minhas imagens? E outros arquivos? Sei la! Isso não entra na minha cabeça porque é mágico demais kk

**Comment by fdaciuk** [comment]
> O resto dos meus diretórios é apenas para desenvolvimento?

Todos os diretórios que você tem arquivos JS serão concatenados em um único arquivo JS que ficará no diretório `dist`.

Os CSS também serão concatenados em um único arquivo CSS.

Sobre as imagens, você deixa elas no diretório `src`, mas vai usar um `loader` (no caso do webpack) para transferir as imagens também para a pasta `dist`, sacou? Mesma coisa para fontes, por exemplo =)

Nós ainda vamos falar mais sobre aplicações, como trabalhar com imageins, fontes, etc., mas foi bom você ter levantado essa dúvida, que outras pessoas também devem ter. Vou falar sobre isso também nos vídeos, pra tentar deixar essa parte mais clara.

A ideia é fechar o módulo 2 com isso bem claro na sua cabeça =)

**Comment by gabrielferreiraa** [comment]
Valeu pelos esclarecimentos @fdaciuk ! Qualquer coisa falo contigo

**Comment by fdaciuk** [comment]
Show! Pode falar mesmo, qualquer coisa que não tenha ficado claro, só avisar =)
