### ISSUE TITLE
M3#A56 erro de lint e falha no testes

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#190]
olá mestre cheguei aqui na aula M3#A56 e está me retornando esse erros no console não está inferindo em nada mais fiquei na duvido do porque

![erro de lint](https://user-images.githubusercontent.com/16200828/45073361-04bb1380-b0ad-11e8-89d0-f02a1db18b3b.png)

@fdaciuk

**Comment by angelilton** [comment]
bom dia mestre então os erro do teste eu consegui desbrir o que é eu tenho  alias para o reducers está assim:
```
    alias: {
      src: paths.src,
      components: join(paths.src, 'components'),
      utils: join(paths.src, 'utils'),
      reducers: join(paths.src, 'redux-flow', 'reducers')
    }
```
ai estava importanto com esse caminho:
`import createReducer from 'reducers/create-reducer'`
e não assim como você fez:
`import createReducer from '../create-reducer'`
se eu colocar os .. resolve mas ai não entedi o porque disso, até porque ele acusa nos index do todos e do visibility-filter mas quando rodo o app tudo funciona normal
e o erro dos lint não consegui esta dando nesse aqui:

**Comment by fdaciuk** [comment]
@angelilton sobe teu projeto aqui no GH e passa o link pra eu dar uma olhada? =)

**Comment by fdaciuk** [comment]
@angelilton conseguiu resolver? Vou fechar a issue, mas se você ainda estiver com esse problema, só avisar que eu te ajudo, ok? =)
