### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by edu290399** [da2k/curso-reactjs-ninja#191]
boa noite, estou tentando configurar o webpack pra atuar em conjunto com o react, mas quando chego no ponto de dar o comando np run dev no prompt, ele me retorna esse erro:

```
> webpack-dev-server --progress --colors --inline --hot

npm ERR! file C:\WINDOWS\system32\cmd.exe;
npm ERR! path C:\WINDOWS\system32\cmd.exe;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;
npm ERR! ExerciciosTreino@1.0.0 dev: `webpack-dev-server --progress --colors --inline --hot`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe; ENOENT
npm ERR!
npm ERR! Failed at the ExerciciosTreino@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\teste\AppData\Roaming\npm-cache\_logs\2018-09-06T01_43_16_049Z-debug.log
```

o que pode ser e como posso solucionar?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edu290399! Esse erro não diz muito sobre o problema, mas tente fazer o seguinte:
Ao invés de usar o `cmd` do windows, tente usar um outro terminal, como o [hyper](https://hyper.is/).

Se o problema continuar, me avise =)

**Comment by edu290399** [comment]
Muito obrigado, eu  tenntei fazer isso pelo cmder, porem o problema persistiu

**Comment by fdaciuk** [comment]
Legal @edu290399! Então o problema pode ser algo faltando no seu projeto =)
Consegue subir o código aqui no GitHub pra eu dar uma olhada?

**Comment by fdaciuk** [comment]
Oi @edu290399! Conseguiu resolver o problema? =)
Vou fechar a issue, mas se você ainda estiver com essa dificuldade, só avisar que eu te ajudo, ok? =)
