### ISSUE TITLE
MRW#02 - Configuração Básica do Webpack

### ISSUE THREAD

**Issue by Morette** [da2k/curso-reactjs-ninja#192]
Olá mestre.
Quando utilizo o comando no terminal <strong>@npm install --save-dev webpack</strong> eu instalo ele localmente, certo?
Porque então não consigo executar o webpack e preciso instalar globalmente?

Não entendi muito bem para que serve o bundle.js, dei uma pesquisada e mesmo assim não ficou claro. 😞

Aproveitando, caso eu tenha outra projeto e precise instalar o webpack globalmente, porém uma versão mais atualizada (hoje está na v4.18.0). Isso poderia dar conflito com versão do curso, certo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Morette! Vamos lá:

> Quando utilizo o comando no terminal @npm install --save-dev webpack eu instalo ele localmente, certo?
> Porque então não consigo executar o webpack e preciso instalar globalmente?

A instalação global é necessária apenas para que o seu sistema operacional entenda que o comando `webpack` pode ser executado em qualquer diretório.

Tem uma forma de resolver isso de forma local, sem precisar instalar globalmente:
- a primeira é criando um _NPM Script_. No seu `package.json`, você pode adicionar uma entrada `scripts`, dessa forma:

```json
{
  "scripts": {
    "webpack": "webpack"
  }
}
```

Ao fazer isso, você está criando um script chamado `webpack` que executa o comando de mesmo nome: `webpack`. Para executar esse _NPM Script_, você só precisa executar `npm run <NOME_DO_SCRIPT>`.

Nesse caso, seria:

```
npm run webpack
```

E isso vai executar o comando `webpack`. A diferença de executar através de um NPM Script, é que o NPM vai buscar essa ferramenta de linha de comando - no caso, o `webpack` - dentro do diretório local `node_modules`, antes de buscar no que chamamos de `$PATH` do seu sistema, que é onde ficam os comandos para os softwares executáveis através de linha de comando =)

---

> Não entendi muito bem para que serve o bundle.js, dei uma pesquisada e mesmo assim não ficou claro. 

A ideia de gerar um "arquivo empacotado" (_bundle_), seria basicamente a seguinte: você pode escrever HOJE códigos JavaScript que ainda não funcionam nos browsers (novas features, que estão sendo lançadas nas novas versões da linguagem), e com o `webpack` + `babel`, você consegue "transformar" essas novas features em features que o browser entende (códigos em ES5).

Por isso geramos um _bundle_: o webpack pega todas as dependências da sua aplicação, e "empacota" em um único arquivo que será servido para o navegador =)

Enquando o babel transforma as novas features que o browser não conhece, convertendo-as em features "mais antigas", ou códigos que o browser vai conseguir entender =)

---

> Aproveitando, caso eu tenha outra projeto e precise instalar o webpack globalmente, porém uma versão mais atualizada (hoje está na v4.18.0). Isso poderia dar conflito com versão do curso, certo?

Sim, se você instalar qualquer dependência de forma global, essa dependência será usada para TODOS os projetos instalados na sua máquina. Para que isso não aconteça, faça o que eu mostrei acima, usando um _NPM Script_ que assim você mantém as dependências de cada projeto de forma local =)

---

Ficou claro? =)

**Comment by Morette** [comment]
> a primeira é criando um NPM Script. No seu package.json, você pode adicionar uma entrada scripts, dessa forma:
`{
  "scripts": {
    "webpack": "webpack"
  }
}`
Ao fazer isso, você está criando um script chamado webpack que executa o comando de mesmo nome: webpack. Para executar esse NPM Script, você só precisa executar npm run <NOME_DO_SCRIPT>.

Bem legal, vou fazer isso então. 

> Por isso geramos um bundle: o webpack pega todas as dependências da sua aplicação, e "empacota" em um único arquivo que será servido para o navegador =)

Enquando o babel transforma as novas features que o browser não conhece, convertendo-as em features "mais antigas", ou códigos que o browser vai conseguir entender =)

Ahh, agora sim consegui entender!!

> Ficou claro? =)

Obrigado Mestre, excelente explicação, obrigado!
