### ISSUE TITLE
Seção 2 MRW#06 - Problema com Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Morette** [da2k/curso-reactjs-ninja#193]
Olá professor,
antes de alterar o padrão para o ES2015 estava rodando tudo OK, porém quando alterei para <i><b>import from</i></b> e <i><b>export default</b></i> começou a aparecer esse problema.

Vi que abriram a issue #125 , porém não encontrei a solução nela.

Comparei meu código com o seu e não encontrei divergência.
Segue meu [repositório](https://github.com/Morette/React/tree/master/React%20Ninja) e o da [aula](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-06).

@fdaciuk

**Comment by Morette** [comment]
Bom, ontem não pude trabalhar no código...
Fui fazer isso agora de manhã e não havia mais problema, tudo está rodando perfeito...

Vai entender
:sweat_smile:

**Comment by fdaciuk** [comment]
Oi @Morette! Pode ter sido alguma coisa faltando no seu código =)
Mas que bom que resolveu! Qualquer dúvida, só avisar :D
