### ISSUE TITLE
MRW#08 - erro no npm start

### ISSUE THREAD

**Issue by Morette** [da2k/curso-reactjs-ninja#195]
Olá professor,
no final da aula, quando fui rodar o 'npm start' aparece o seguinte erro:

```
node server.js

D:\Programming\Front\React\React Ninja\node_modules\webpack-dev-server\lib\Server.js:103
    const { compile, invalid, done } = compiler.hooks;
            ^

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (D:\Programming\Front\React\React Ninja\node_modules\webpack-dev-server\lib\Server.js:103:49)
    at new Server (D:\Programming\Front\React\React Ninja\node_modules\webpack-dev-server\lib\Server.js:116:5)
    at Object.<anonymous> (D:\Programming\Front\React\React Ninja\server.js:7:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-ninja@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-ninja@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thiag\AppData\Roaming\npm-cache\_logs\2018-09-16T11_56_33_348Z-debug.log
```

segue o link do [repositório](https://github.com/Morette/React/tree/master/React%20Ninja) 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Morette! O problema é a versão do `webpack-dev-server`. Você chegou a ver a aula do futuro, falando sobre as versões das dependências? =)

Lá eu indico para sempre ficar de olho [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), que estão as versões exatas das dependências que devem ser instaladas, ok? =)

**Comment by Morette** [comment]
Valeu mestre, isso resolveu.

>  Você chegou a ver a aula do futuro, falando sobre as versões das dependências? =)

Vi sim e tenho sempre visto a versão nesse arquivo para instalar.
Estou vendo todos os vídeos para conseguir acompanhar. Essa parte do setup inicial pra mim por enquanto está bem difícil de pegar.

Eu comparei o seu arquivo package.json com o meu para ver as versões e deixei essa passar...:sweat:
Preciso ter mais atenção

**Comment by fdaciuk** [comment]
Show de bola @Morette! Que bom que deu certo =)
Essa parte de configurações é chatinha mesmo, mas você só precisa fazer ela uma vez para as suas aplicações, e consegue reutilizar de forma bem fácil =)

Apesar de ter ferramentas que você pode usar pra não precisar ficar configurando na mão, é importante conhecer e entender como isso funciona, pois uma hora ou outra você pode precisar =)

De qualquer forma, se você quiser pular as aulas que falam de configuração pra ver depois, não há problemas! Pode usar o `create-react-app` pra acompanhar as aulas sem problema =)

Fica a seu critério :D 

E qualquer dúvida, conte comigo =)

**Comment by Morette** [comment]
> De qualquer forma, se você quiser pular as aulas que falam de configuração pra ver depois, não há problemas! Pode usar o create-react-app pra acompanhar as aulas sem problema =)

que nada, eu acho super importante essa parte do setup
eu fico bastante confuso de onde colocar as configurações, como por exemplo criar o arquivo server.js, mas eu imagino que isso deva estar explicado nas documentações do babel, webpack etc...

**Comment by fdaciuk** [comment]
Então, o local correto onde colocar essas configurações eu normalmente explico nas aulas. Mas se algo não ficar claro, só abrir issue aqui que eu vou te ajudando =)

**Comment by WRCrys** [comment]
Olá Fernando! Me ajuda, por favor, tive o mesmo problema do colega e que no caso instalando a versão correta funcionou, porém o build não aparece conforme na aula que tem o h1 Título e tudo mais.
No console só exibe aquela mensagem do bundle.js que o webpack está funcionando. Seria como se ele não enxergasse o resto.
