### ISSUE TITLE
Site inteiro em React

### ISSUE THREAD

**Issue by abanjos** [da2k/curso-reactjs-ninja#196]
Queria perguntar: é viável criar uma página inteira em react, do ponto de vista de SEO e qualidade da página. Digo desde o roteamento e estrutura principal da página até interações com usuário. Ou será que é melhor usar react somente para parte de interação e afins. To precisando criar uma page mas queria faze-la inteira em react.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @abanjos! É viável sim, mas tem algumas coisas que você precisa ter em mente:
- SPAs são "crawleáveis" pelo Google, mas você não consegue compartilhar conteúdo de uma página específica em redes sociais. Pois nesse caso, os crawlers de Facebook e Twitter - por exemplo - tentam obter os dados da página gerada de forma estática pelo seu servidor. Pra isso funcionar corretamente, você precisa fazer SSR (Server Side Rendering);
- se for manter a aplicação como SPA, é importante levar em consideração que, ao subir a sua aplicação para um servidor, esse servidor deve conseguir redirecionar qualquer request do tipo GET para a sua `index.html`, para que as rotas sejam gerenciadas pelo React Router.

Com isso em mente, você não terá muitos problemas em criar uma aplicação inteira com qualquer framework ou lib de frontend =)

**Comment by fdaciuk** [comment]
> o Google espera essa (ou essas) request pra fazer o crawling?
Sim! Mas como o conteúdo é gerado dinamicamente, pode ser que ele se perca em alguma coisa, pode acontecer de ele demorar um pouco mais pra ler, ou algumas vezes ler, outras não. Ósseos do ofício.

Mas no geral, ele consegue sim.

A alguns anos atrás, quando começaram a surgir as SPAs, para o Google tentar crawlear um site, eles tentaram "impor" um padrão usando o chamado [_escaped fragment_](https://developers.google.com/search/docs/ajax-crawling/docs/learn-more), mas acabou não vingando porque ele tentava fazer uma gambiarra com a hashbang (`#!`). Esse formato [foi deprecado em 2015](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html), pois uma API foi criada para o HTML5: a History API. 

Com essa nova API, o artigo onde dizia que o _escaped fragment_ havia sido deprecado foi atualizado, dizendo que o Google consegue sim crawlear sites com conteúdo gerado dinamicamente, desde que você não coloque seus assets (JS, CSS, etc) no arquivo `robots.txt` para serem ignorados:

>  In 2009, we made a proposal to make AJAX pages crawlable. Back then, our systems were not able to render and understand pages that use JavaScript to present content to users. Because "crawlers … [were] not able to see any content … created dynamically," we proposed a set of practices that webmasters can follow in order to ensure that their AJAX-based applications are indexed by search engines.

> Times have changed. Today, as long as you're not blocking Googlebot from crawling your JavaScript or CSS files, we are generally able to render and understand your web pages like modern browsers. To reflect this improvement, we recently updated our technical Webmaster Guidelines to recommend against disallowing Googlebot from crawling your site's CSS or JS files.

Acho que é isso! Dá uma lida nesses links que eu passei que acho que vai ficar mais claro =)

Mas, em resumo:

Sim, o Google indexa páginas criadas com conteúdo dinâmico e sem SSR; mas você não consegue compartilhar esse conteúdo dinâmico em redes sociais, pois os crawlers de Facebook e Twitter (pelo menos) não fazem essa renderização dinâmica. Nesse caso, a solução é fazer SSR.

**Comment by abanjos** [comment]
Perfeito, obrigado pela resposta.
Parece trabalhoso então seguir por esse caminho, talvez seja melhor manter a aplicação padrão e usar react em determinados momentos.

**Comment by fdaciuk** [comment]
Na verdade, depende muito do tipo de aplicação que você vai criar, e os seus objetivos com essa aplicação.
Particularmente, se for pra usar React, eu prefiro fazer a aplicação toda com ele, pois ele vai facilitar muitas coisas =)

Se você precisa de SSR, existem algumas ferramentas hoje que podem te ajudar, como o [next.js](https://github.com/zeit/next.js) e o [after.js](https://github.com/jaredpalmer/after.js) =)

Para sites estáticos, você pode usar o [Gatsby](https://www.gatsbyjs.org/).

E para SPAs, o que você já conhece de React + React Router =)

Enfim, tudo vai depender do conhecimento que você tem da ferramenta, e do seu objetivo com a aplicação =)

**Comment by abanjos** [comment]
Assim, se não quiser responder não precisa XD já ficou grande demais o issue.
O que seriam essas 'muitas coisas'? tem como aprofundar mais sobre? Tem como citar um exemplo de quando não usar o react por exemplo?

obs.: Tenho um e-commerce que queria refaze-lo em React, por isso as dúvidas.

**Comment by fdaciuk** [comment]
> Assim, se não quiser responder não precisa XD já ficou grande demais o issue.

Não é uma opção: enquanto houver dúvidas e eu puder ajudar, vou fazer isso. Não se preocupe com a quantidade de dúvidas, pergunte sempre que precisar =)

Bom, vamos lá: usar um framework / lib de frontend - não só o React - pode ajudar em coisas como:
- componentização: você escreve menos código, e reaproveita mais;
- performance: para o usuário ajuda bastante, pois a percepção dele é que as coisas acontecem muito mais rápido, visto que a maior parte das ações acontece no frontend, não necessitando recarregar a tela. E essa percepção de velocidade ajuda a manter o usuário no seu site/aplicação;
- se preocupar com o que realmente importa: no React, você não se preocupa em ficar manipulando DOM. Ele faz isso pra você. Você se preocupa apenas com a camada de dados, e como esses dados serão transformados para serem exibidos na tela. "Como" as coisas acontecem no DOM, é o React que se vira.

Enfim, esses são apenas alguns pontos que eu acho que fazem bastante diferença na hora de criar uma aplicação =)

Eu não diria que existe algum tipo específico de aplicação que você não deve usar React, mas recomendo que você estude bem como ele funciona, entenda bem como trabalhar com imutabilidade, e conheça bem JavaScript antes de pegar uma aplicação já funcional e tentar reescrever com React.

Esse conhecimento vai te ajudar a tomar as melhores decisões =)
