### ISSUE TITLE
Alterar State - M1A20

### ISSUE THREAD

**Issue by italo-lima** [da2k/curso-reactjs-ninja#197]
Pq não consigo alterar o estado do quadrado quando clico no botão?
Código:

```js
import Square from "./Square"
import Button from "./Button"

class App extends Component {
constructor() {
    super()
    this.state = {
      color: "red"
    }
  }

render() {
    return (
<div>
          <Square color={this.state.color} />

          {["red", "green", "blue"].map((color) => (
            <Button key={color} onClick={() => this.setState({ color })}>
              {color}
            </Button>
          ))}
        </div>
)}}
export default App
```

**Aki é o meu botão**:

```js
import React from "react"

const Button = ({children}) => {
    return (
    <button> {children} </button>
)
}

export default Button
```

**Aki é o meu quadrado:**

```js
import React from "react"

//Component Quadrado
const Square = ({ color }) => {
    console.log(color)
    return (
        <div style={{
            backgroundColor: color,
            height: "100px", width: "100px"
        }}>
        </div>
    )
}

export default Square
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @italo-lima! Vamos lá:

Perceba que você usou o componente que você criou (`Button`), passando pra ele duas props: `onClick` e `children` (podemos ignorar a `key` pq o React não passa essa prop para dentro do componente).

Mas olhando o seu componente `Button`, o elemento que vai renderizar o botão mesmo `<button>`, não está recebendo essa prop `onClick`, então ao clicar nesse botão, nada vai acontecer mesmo =)

Deu pra entender o problema? =)

**Comment by italo-lima** [comment]
pq eu preciso passar o onClick para o button?

Estava usando essa mesma ideia, para alterar o estado:
constructor() {
    super()
    this.state = {
      text: "Ítalo"
    }

<div onClick = {() => this.setState({
          text: "Ítalo Lima"
        })}>

Qual a diferença entre os 2 modos? (Anterior e esse q acabei de postar)

**Comment by fdaciuk** [comment]
Oi @italo-lima! Pense no componente que você cria como uma simples função. No caso, o `Button` é uma função criada por você. Já o componente `<button>` (com `b` minúsculo) é o componente que vai ser renderizado no DOM, representando a tag HTML `button`, certo?

No caso, pensando apenas em JavaScript, você escreveu uma função `Button`, que vai renderizar o botão de fato:

```
function Button ({ children }) {
  return <button>{children}</button>
}
```

Veja que o `button`, que é o elemento que vai ser renderizado, não tem o método `onClick`. Então, ao usar o `Button` (função que você criou), o único argumento utilizado é o `children`. Qualquer outro argumento passado será ignorado (os argumentos são as props):

Pensando no `Button` apenas como uma função, se você fosse executá-lo seria algo assim:

```js
Button({
  children: color,
  onClick: () => this.setState({ color })
})
```

Veja que um objeto é passado via argumento para a função `Button` - que é mais ou menos o que o React faz por baixo dos panos, quando você passa as props! Elas nada mais são do que propriedades de um objeto (props) passado como argumento para o componente:

```js
<Button onClick={() => this.setState({ color })}>{color}</Button>
```

Então essas props são passadas, mas não são utilizadas no componente que vai ser renderizado, sacou?

Para funcionar, você precisa pegar o `onClick` e passar para o `<button>`, que é o cara que vai receber o click de fato:

```js
function Button ({ children, onClick }) {
  return <button onClick={onClick}>{children}</button>
}
```

Deu pra entender a ideia? No segundo exemplo que você mostrou, funciona corretamente porque você está colocando o evento em uma `div`. Esse é o elemento que vai ser renderizado, por isso funciona.

Troque essa `div` por `button` e você verá que vai funcionar da mesma forma =)

O problema é você criar um componente seu - no caso, o `Button` - mas não repassar as props passadas para ele, para o componente que vai de fato ser renderizado =)

Ficou mais claro? =)

**Comment by italo-lima** [comment]
Agora entendi td, muito obrigado pelas dicas.

**Comment by fdaciuk** [comment]
Que bom que ficou claro @italo-lima =)
Qualquer dúvida, só avisar =)
