### ISSUE TITLE
M1#A14 Warning: React.createElement: type is invalid

### ISSUE THREAD

**Issue by Morette** [da2k/curso-reactjs-ninja#198]
Olá mestre,
quando eu coloco o key={ index } aparece o seguinte erro

![image](https://user-images.githubusercontent.com/20028647/45792317-a91f8700-bc63-11e8-9d91-ecb0243c0d9f.png)

Quando eu tiro a imagem funciona, porém aparece a msg de <i>unique key</i>

```js
class App extends Component {
   render () {
      return (
         <div className='container'>
               {['red', 'green', 'green'].map((square) => (
               <Square  color={ square } />
            ))}
         </div>
      )
   }
}
```

Segue link do meu [repositório](https://github.com/Morette/React/tree/master/React%20Ninja)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Morette! O seu problema é o seguinte: você está usando uma variável chamada `index`, mas ela não existe no escopo do seu código =)
Provavelmente você deveria estar usando o segundo argumento passado para a função do `map`, mas ele não está sendo passado, por isso o erro =)

**Comment by Morette** [comment]
Era isso mesmo...
Tenho que parar de estudar as 23h, depois disso o sono assume e fico dando esses moles por falta de atenção
😓

**Comment by fdaciuk** [comment]
Relaxa, acontece =)
Qualquer dúvida, só avisar :D
