### ISSUE TITLE
M2#A41 - cross-env

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-reactjs-ninja#199]
Ao rodar o `npm run build`, recebo o seguinte erro:

ERROR in ./src/components/app-content/index.js
Module not found: Error: Cannot resolve module 'components/search' in C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\src\components\app-content
 @ ./src/components/app-content/index.js 11:14-42

ERROR in ./src/components/app-content/index.js
Module not found: Error: Cannot resolve module 'components/user-info' in C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\src\components\app-content
 @ ./src/components/app-content/index.js 15:16-47

ERROR in ./src/components/app-content/index.js
Module not found: Error: Cannot resolve module 'components/actions' in C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\src\components\app-content
 @ ./src/components/app-content/index.js 19:15-44

ERROR in ./src/components/app-content/index.js
Module not found: Error: Cannot resolve module 'components/repos' in C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\src\components\app-content
 @ ./src/components/app-content/index.js 23:13-40

Mas o npm start não faz isso.

Meu projeto: https://github.com/gustavom/curso-react-ninja/tree/master/m02/working-with-assets/github-app

Olhando esse projeto, para as pastas base e para o package.json, acha que ele esta ok para usar de boilerplate para outros projetos ou preciso mexer nele

@fdaciuk

**Comment by gustavom** [comment]
Acho que me achei.

Na aula do alias no webpack, falou implementar o 'resolve' no arquivo config de produção.

Pelo menos não da mais o erro.

**Comment by fdaciuk** [comment]
Oi @gustavom! É isso mesmo =)
Na verdade, nessa aula a gente ainda não está usando o alias `components`, mas mais pra frente eu mostro uma abstração da configuração do webpack pra adicionar os alias tanto em produção como em desenvolvimento, sem precisar duplicar os webpack.config =)

**Comment by gustavom** [comment]
Sobre esse projeto que estamos fazendo o github app.

Seria possível, no momento que estou nessa aula, usar para fazer algum projeto, ou o meu projeto esta cru ou bagunçado para isso, como ainda não tenho o dominio, sinto que fiz uma zona kkkk. Mas ao mesmo tempo, usar o create-react-app me passa a sensação que não estou aprendendo nada.

**Comment by fdaciuk** [comment]
Não sei se entendi muito bem sua dúvida. Você quer saber se essa configuração do webpack que está sendo usada no projeto do GitHub App pode ser reaproveitada para usar em outros projetos, ao invés de usar o create-react-app?

Se for isso, claro, consegue sim! Nesse módulo 2 você vai ver ainda outras configurações importantes para adicionar no webpack.config. Inclusive, toda essa configuração mostrada nas aulas está sendo aplicada a um boilerplate que você pode usar pra começar qualquer projeto em React:
https://github.com/fdaciuk/workflow-reactjs

Nesse repositório já está com a versão mais recente do que foi mostrado em aula =)

Mas não há problema algum em você criar sua própria configuração e aplicar nos seus novos projetos =)

Inclusive, não há problema algum em usar o CRA também, muito pelo contrário: ele facilita bastante iniciar novos projetos! Depois, se você perceber que o CRA não supre o que você precisa, você consegue reaproveitar o diretório `src` dele, e criar sua própria configuração, mantendo os arquivos do seu projeto; ou ainda usar o [CRA Rewired](https://github.com/timarney/react-app-rewired), que vai te permitir continuar usando o CRA sem dar eject, e ainda assim extender algumas configurações dele =)
