### ISSUE TITLE
Limpar a área de User info enquanto faz o request

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#200]
Boa madrugada Professor! Como limpar a area do user info e deixar só o loader
sempre que eu fizer um request. Solução que tentei (porém sem sucesso):

{ !!userInfo && !!isFetching <UserInfo userInfo={userInfo} />

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Pra fazer isso, você pode setar o `userInfo` como `null` antes de iniciar o request.
E para validar se o `userInfo` é `null`, você pode **negar** o valor, não transformá-lo em booleano:

```
!userInfo && isFetching && <Loader />
```

Sacou? Ao negar o `userInfo`, esse valor é convertido para o seu equivalente booleano, e então invertido. Logo, se `userInfo` for `null`, o equivalente booleano de `null` é `false`. Ao inverter o valor, ele vai ser `true`. Então, se `userInfo` for `null` e `isFetching` também for `true`, o componente `<Loader />` será renderizado =)

Ficou claro?

**Comment by RodrigoWebDev** [comment]
Eu entendi a lógica, porém ao aplicar não teve o resultado esperado! O que eu queria era que toda a área do user info sumisse toda vez que eu fizesse um novo request, e aparecesse apenas o Loader, quando o request fosse finalizado apareceria as informações do usuario, e o loader desapareceria, mais ou menos isso...

**Comment by RodrigoWebDev** [comment]
Ah sim! Entendi, deu certo! Obrigado de novo =)

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D
