### ISSUE TITLE
Erro no console sempre que se faz uma busca

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#201]
Boa madrugada Professor! Ta aparecendo um erro no console pra mim sempre que faço uma busca! Não ta prejudicando a aplicação em nada ( eu acho kk ), ta tudo funcionando normal, mas gostaria de tentar entender o erro.  Vou anexar um print do erro. E aqui vai o link do repositorio : https://github.com/RodrigoWebDev/github-app
 
![question](https://user-images.githubusercontent.com/30677819/46127920-6b44d480-c208-11e8-8dbe-8c13b0805198.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! O problema é que você está passando um valor para `photo` em `propTypes`, que deveria estar em `defaultProps`:
https://github.com/RodrigoWebDev/github-app/blob/master/src/components/user-info.js#L28

**Comment by RodrigoWebDev** [comment]
AH é verdade kkk, nossa que mico! Obrigado Professor

**Comment by fdaciuk** [comment]
haha! Relaxa, acontece =)
Qualquer coisa, só avisar =)
