### ISSUE TITLE
[M1#A47] A onde exatamente eu passo as propTypes?

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#202]
Boa madrugada Professor! A onde exatamente eu passo as propTypes? Por exemplo, a prop "isDisabled" é usada no component "Search" e no component "app-content" que é o "pai" do search, no video voce passa a propType do "isDisabled" dentro do "Search". Eu sei que tenho que passar no pai por causa do fluxo de dados , mas ,   como saber a onde passar as propTypes de certas propriedas  que são passadas em outros componentes?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Na verdade, você pode passar as `propTypes` apenas no componente final, que vai usar a prop. Não precisa passar nos componentes "intermediários" =)

Essa validação de propTypes é apenas para garantir o tipo de dado que está sendo passado. Então não há problema em passar apenas no componente que usa essa prop.

Se quiser garantir que a prop esteja sendo passada corretamente desde o primeiro componente que recebe ela, então sim, você pode usar no primeiro e no último componente que recebe essa prop, mas não é obrigatório =)

**Comment by RodrigoWebDev** [comment]
Entendi! Obrigado pela resposta =)

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
