### ISSUE TITLE
Erro ao subir a aplicação para o servidor

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#203]
Boa madrugada professor! Como subir a aplicação(github app) que criamos no curso? Eu gosto de subir as aplicações
que eu desenvolvo para colocar no portfolio. Eu uso o github
pages. Porém ao subir a tela fica toda branca e da um
"Warning" no console. Voce pode checar isso no link do projeto
https://rodrigowebdev.github.io/github-app/. O código esta
aqui : https://github.com/RodrigoWebDev/github-app

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! No primeiro módulo do curso, o objetivo é apenas mostrar como o React funciona. No módulo 2, nós vamos voltar nessa aplicação, e fazer mais algumas configurações no webpack para servir essa aplicação em produção =)

**Comment by RodrigoWebDev** [comment]
Entendi Professor! Obrigado

**Comment by RodrigoWebDev** [comment]
Professor, eu nao encontrei a aula que ensina a servir o app em produção. Sei que estou pulando aula kkk, mas é só pra subir logo, depois eu volto e continuo o curso normalmente =)

**Comment by fdaciuk** [comment]
haha! Depois de terminar todo o módulo 1, nós continuamos com essa aplicação no módulo 2 à partir da aula 31 =)

**Comment by fdaciuk** [comment]
Sem problemas! Qualquer coisa, só avisar =)
