### ISSUE TITLE
[M2#A33] if(element.loader) return element.loader.split("!");

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#204]
Boa noite porfessor! Recebi esse erro no terminal ao dar npm start. Não tenho idéia do que é, sei que foi depois que instalei o extract-text-webpack-plugin e fiz a configuração no webpack. Segui os passos do video na configuração e mesmo assim deu erro. Sabe me dizer o que é? Repositório: https://github.com/RodrigoWebDev/github-app
![screenshot_3](https://user-images.githubusercontent.com/30677819/46176892-49d6fd80-c287-11e8-9f38-0aff4adab464.jpg)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Atualiza seu repositório pra eu baixar aqui e tentar simular o erro. Essa versão está rodando certinho aqui pra mim =)
