### ISSUE TITLE
[M1#A43] Objects are not valid as a React child

### ISSUE THREAD

**Issue by didiraja** [da2k/curso-reactjs-ninja#206]
Terminei a aula e não sei pq deu esse erro. Segue o print do erro e aqui meu [repositório com os arquivos da aula](https://github.com/didiraja/curso-react-ninja).

![image](https://user-images.githubusercontent.com/10463976/46813330-e4861080-cd4c-11e8-9125-20f2ec303266.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @didiraja! =)

Apesar da mesagem de erro estar visualmente apontando que o problema acontece no `this.setState`, na verdade ali é apenas o começo onde o problema começa a se desencadear =)

Tente olhar sempre no início da mensagem de erro, onde é exibido a árvore de componentes, e a linha onde o erro pode estar.

Se você olhar a mensagem de erro, ela diz:

```
Objects are not valid as a React child.
```

Ou seja: `Você não pode usar objetos como "children" de um elemento React`.

Interpretando essa mensagem, quer dizer que, em algum lugar do seu código, você usou um objeto como "children" de um elemento JSX. Basta agora descobrir onde esse objeto foi usado.

Seguindo na mensagem de erro, veja que ele mostra o primeiro componente da árvore onde pode conter o erro (normalmente o problema está nesse primeiro componente. Se não estiver, é só seguir a lista exibida):

```
in a (at Repos.js:15)
```

Veja que o React está dizendo que o erro está em um elemento do tipo "a" (um link `<a>`), no arquivo `Repos.js`, na linha 15.

Ao [abrir esse arquivo, na linha 15](https://github.com/didiraja/curso-react-ninja/blob/master/exercises/m01/src/components/Repos.js#L15) você tem o seguinte código:

```jsx
<li key={key}><a href={repo.link}>{repo}</a></li>
```

Veja que esse `repo`, que é "children" (filho) do elemento "a" - como mostra o erro - é um objeto. No `href` desse `<a>`, você usa `repo.link`. Isso significa que `repo` é um objeto, e contém propriedades.

É aí que está o problema! E como resolver? Provavelmente esse objeto tem uma propriedade `name`, que é o valor que deveria ter sido renderizado como filho desse `a` =)

Deu pra entender a ideia de como encontrar o problema, seguindo a mensagem de erro? =)

**Comment by didiraja** [comment]
@fdaciuk Eu tinha entendido a mensagem de erro, porém, quando chegava na linha não via problema nenhum mas agora acho que encontrei.

Valeu pela agilidade, o curso é ótimo

**Comment by fdaciuk** [comment]
Perfeito @didiraja! =)
Com o tempo nós vamos ficando familiarizados com os erros, e começa a ficar fácil encontrá-los =)

Qualquer dúvida, só avisar :D
