### ISSUE TITLE
[M2#A04]Problema com velocidade de excecução do Jest

### ISSUE THREAD

**Issue by RodrigoWebDev** [da2k/curso-reactjs-ninja#207]
Eai professor. Estou com um problema... quando eu executo um teste com o Jest, demora em torno de 5 segundos para executar, enquanto contigo demora 3milisegundos para executar. Por que? Desculpe se estou perguntando algo que vai ser explicado no futuro no curso. Se esse for o caso, pode desconsiderar a pergunta. Abraços

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RodrigoWebDev! Provavelmente é por conta do cache! O Jest faz cache quando você executa os mesmos testes, com o mesmo código. Então a primeira execução normalmente pode ser um pouco demorada, mas as próximas são bem rápidas =)

**Comment by RodrigoWebDev** [comment]
AH sim! Faz sentido! Obrigado pela resposta. Abraços =)

**Comment by fdaciuk** [comment]
Perfeito! Qualquer dúvida, só avisar =)
