### ISSUE TITLE
Dúvidas sobre o curso

### ISSUE THREAD

**Issue by vini23hot** [da2k/curso-reactjs-ninja#208]
Boa noite professor, gostaria muito de adquirir o curso React Ninja, principalmente agora depois dessa promoção que você disponibilizou no twitter, mas antes eu tenho umas dúvidas... caso você possa responder, eu agradeço!

- A versão do React (e das outras dependências) usada no curso desde o começo é muito diferente da atual? Tem muita coisa que vou ter que mudar quando for fazer uma aplicação com o que aprendi na aula usando a nova versão?
- Tem alguma previsão de quando irá terminar de disponibilizar todas as aulas do curso até o último módulo?
- No curso até o momento não tem nenhum projeto prático, mas depois de terminar todas as aulas, fica difícil de aplicar todo o conhecimento na prática pra fazer uma aplicação inteira em React?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @vini23hot! Vamos lá =)

> A versão do React (e das outras dependências) usada no curso desde o começo é muito diferente da atual? Tem muita coisa que vou ter que mudar quando for fazer uma aplicação com o que aprendi na aula usando a nova versão?

As bibliotecas sempre sofrem atualizações sim, mas, principalmente falando do React, os conceitos sempre se mantém. É isso que é o o foco mostrado no curso, além da ferramenta. Então todos os conceitos que você vai ver no curso (que começou na versão 15) são e serão válidos para todas as próximas versões do React. As versões mais novas contém mais atualizações que mudanças em si. E essas atualizações nós vamos ver em um módulo que eu vou disponibilizar em breve, então pode ficar tranquilo que tudo o que você aprender vai ser válido sim. Não vai ter nada a ser aprendido que será em vão =)

Outro ponto importante é que o React acaba "deprecando" algumas coisas. Boa parte dessas coisas eram meio óbvias que poderia acontecer, então o que é mostrado na hora de aplicar em aplicações de exemplo já é meio que pensando nisso =)

No decorrer do curso eu mostro algumas atualizações que vão surgindo, mas as novidades de todas as novas versões vão ficar para esse novo módulo que estou preparando =)

Mas nas aulas eu oriento como seguir com as versões usadas nas aulas, para que você consiga acompanhar e fazer os exemplos junto comigo, não se preocupe com isso também. E qualquer dúvida que você tiver, é só perguntar: fico à disposição para ajudar no que for necessário =)

> Tem alguma previsão de quando irá terminar de disponibilizar todas as aulas do curso até o último módulo?

Pretendo terminar todos os módulos até o final desse ano, mas não tem como garantir com certeza, pois muita coisa pode acontecer até lá. Por enquanto é a minha previsão. O foco das aulas é sempre na melhor qualidade possível, de forma que você aprenda de fato a usar a ferramenta, e se virar com ela. Sei que com o curso muito grande pode ficar complicado acompanhar tudo, por isso ele é separado em módulos. Dessa forma fica fácil você seguir uma linha de aprendizado, e pegar somente as partes que você precisa =)

> No curso até o momento não tem nenhum projeto prático, mas depois de terminar todas as aulas, fica difícil de aplicar todo o conhecimento na prática pra fazer uma aplicação inteira em React?

Durante o curso eu mostro diversos pequenos projetos práticos. Agora no módulo 4, onde falamos de SPA e Routing é onde nós vamos construir o maior projeto do curso: um sistema para pizzaria.

Em cada módulo é mostrado um projeto para que você consiga colocar em prática o que está aprendendo, pode ficar tranquilo com relação a isso também. O ponto chave é entender bem os conceitos passados e praticar. E tirar dúvidas, sempre que elas surgirem =)

---

Acho que é isso. Qualquer dúvida, fique à vontade para perguntar =)

**Comment by vini23hot** [comment]
Que resposta! Muito obrigado professor, sanou praticamente quase todas as minhas dúvidas. Realmente, já tinha percebido que esse curso é bem completo mesmo!

Você pode me dizer se na promoção de black friday, o curso com cupom vai estar mais barato que o desconto atual dessa semana? E vai até que dia esse desconto atual?
Como não está meio corrido as coisas aqui, não pretendo iniciar o curso agora, então se estiver mais barato na black friday fica melhor pra mim.

**Comment by fdaciuk** [comment]
Legal, que bom que ficou tudo claro =)

Essa promoção vai ficar válida mais essa semana. Sobre a black friday, ainda vou ver o valor que vai ficar, mas provavelmente vai se manter o mesmo, talvez um pouco mais em conta, mas isso só vou conseguir definir mais perto da data =)

De qualquer forma, se esperar para comprar na black friday, no máximo você vai comprar com valor igual a esse, talvez menor =)

**Comment by vini23hot** [comment]
Muito obrigado por tudo!
