### ISSUE TITLE
74. M2#A08

### ISSUE THREAD

**Issue by RafaelMouraFrontend** [da2k/curso-reactjs-ninja#209]
Nessa aula é recomendado que use esse script no package.json
"test:watch": "npm test -- --watch" 

Porem pra mim estava dando erro e falava no terminal pra usar: 
"test:watch": "npm test -- --watchAll"

Tem alguma diferença?!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RafaelMouraFrontend!

O `watch` só vai executar novamente os testes que você alterou. Usando o `watchAll`, todos os testes são executados novamente, ainda os que não estão sendo mexidos =)

**Comment by RafaelMouraFrontend** [comment]
O erro quando uso só o watch é esse:
--watch is not supported without git/hg, please use --watchAll

Andei dando uma pesquisada no erro, não sei se entendi errado mas esse erro vai acontecer toda vez que estiver no projeto sem git, seria isso?!

Segue um link sobre a treta...
https://github.com/facebook/jest/pull/4737

**Comment by fdaciuk** [comment]
Ah, entendi agora =)
Pois é.. o Jest usa o histórico do git pra saber quando um arquivo foi ou não alterado, provavelmente é esse o problema mesmo =)

Se você tiver o git instalado na sua máquina, seria só rodar um `git init` no diretório do seu projeto (ainda que você não vá usar o git), só pro Jest poder usar o comando `watch`.

De qualquer forma, o `watchAll` também vai funcionar para o seu caso, sem muita diferença (dependendo do tamanho do projeto) =)
