### ISSUE TITLE
Dúvidas sobre Webpack etc

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#21]
Fala @fdaciuk, tudo tranquilo? Estou aqui com a dúvida da semana, não te dou sossego ! hahaha

1. Estamos com aplicações pequenas até o momento e o `bundle` gerado já é de quase 3mb, e quando tivermos aplicações gigantes, iremos gerar o `bundle `e vai dar 20-30-40mb, como o _browser_ lida com isso? Não há queda na performance ? Ou algo do tipo, demora para renderizar algo para o usuário.

2. Como já falei pra você em issues e dúvidas passadas, estou fazendo esse curso para montar uma aplicação. Por isso as vezes faço perguntas pensando la na frente, ou perguntando coisas que "não está na hora de aprender" ainda, você deve me entender, estou correndo contra o tempo. Para começar a estruturar minha aplicação eu preciso de um norte em relação a Flux/Redux, pois quero utiliza-los. Não vou conseguir esperar as aulas do curso saírem (o que eu queria MUITO!) mas não vou conseguir, infelizmente. Tem algum lugar que você me indica ver/ler/estudar sobre esse assunto ? Todos vídeos/artigos que vejo, me perco mais ainda, eu realmente preciso de um norte em relação a esse assunto. Você consegue me ajudar? Mesmo "não estando na hora", digamos assim !? 

Valeu por toda atenção!

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa =)

Vamos lá ;)

### Sobre o tamanho do bundle

Para um único arquivo, 3mb com certeza é bastante grande. Você está gerando a versão para produção como mostrado em aula, ou ainda não chegou lá? Se não chegou, provavelmente o seu bundle pode ficar bem menor que isso para aplicações menores =)

Mas é natural que o bundle cresça conforme a aplicação também vai crescendo, até porque tudo está sendo feito direto no JS: HTML, CSS, e o próprio JS.

Com webpack nós conseguimos quebrar o arquivo final em vários arquivos menores. É um assunto um pouco complexo para mostrar em uma única resposta, mas você pode dar uma olhada na própria documentação do webpack, que lá mostra como fazer. [Aqui](https://webpack.github.io/docs/code-splitting.html) tem o link da v1 do webpack falando sobre _code splitting_.

Um outro ponto a se considerar é que a versão 2 do webpack foi lançada recentemente. A migração é bastante tranquila até, e trás muitos benefícios que nós iremos abordar em aula. Mas a documentação é o melhor caminho para entender como tudo funciona =)

2. Sobre Redux: o melhor lugar para se entender o Redux também é a [documentação](http://redux.js.org/). Lá você vai encontrar 30 vídeos do criador do Redux (Dan Abramov), explicando a ideia desde o começo.

Recomendo que você assista e entenda a ideia dele antes de utilizá-lo de fato. Pode ser que você nem precise utilizar =)

O importante é seguir a ideia que estamos passando no curso: sempre manter o estado da aplicação em um componente isolado, e usar todos os outros componentes como stateless.

Nem sempre você vai ter um único componente stateful, pode ser que você precise de mais de um, e isso é bastante comum. Mas usando o componente stateful para apenas manipular estado, e passar os dados para um componente filho, via props, que irá chamar todos os outros componentes abaixo deste, vai ficar bem mais fácil gerenciar a aplicação e, se for o caso, migrar para usar o Redux no futuro =)

Bom, espero que tenha ajudado. Qualquer dúvida, só avisar!
