### ISSUE TITLE
M1#A38

### ISSUE THREAD

**Issue by juniorb34** [da2k/curso-reactjs-ninja#210]
Estou recebendo a seguinte mensagem de erro nesta aula:

```
TypeError: Cannot read property 'map' of undefined
Repos
C:/Users/james/React/React-Ninja/github-app/src/components/repos.js:8
   5 | <div className={className}>
   6 |   <h2>{title}</h2>
   7 |   <ul>
>  8 |     {repos.map((repo, index) => (
   9 |       <li key={index}>
  10 |         <a href={repo.link}>{repo.name}</a>
  11 |       </li>
View compiled
▶ 22 stack frames were collapsed.
./src/index.js
C:/Users/james/React/React-Ninja/github-app/src/index.js:7
   4 | import App from './App';
   5 | import registerServiceWorker from './registerServiceWorker';
   6 | 
>  7 | ReactDOM.render(<App />, document.getElementById('root'));
   8 | registerServiceWorker();
   9 | 
  10 | 
View compiled
```

@fdaciuk

**Comment by juniorb34** [comment]
O problema aparece a partir do momento que eu defino em app.js os states userinfo, repos e starred. Enquanto eles estão vazios e Null consigo renderizar. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @juniorb34! Dá uma olhada em como você está iniciando essa variável `repos`. Ela deveria inicializar como um array vazio, pois só arrays têm esse método `map` =)

Se `repos` estiver inicializado corretamente, provavelmente você não está passando a prop em algum lugar, pois ela não deve estar chegando no componente `repos.js`; por isso diz que a prop está vindo como `undefined` =)

**Comment by juniorb34** [comment]
App.js

import React, { Component } from "react";
import "./App.css";

import AppContent from "./components/app-content";

class App extends Component {
  constructor() {
    super();
    this.state = {
      userinfo: {
        username: "Fernando Daciuk",
        photo: "https://avatars.githubusercontent.com/u/487669?v=3",
        repos: 12,
        followers: 11,
        following: 300
      },
      repos: [
        {
          name: "Repo",
          link: "#"
        }
      ],
      starred: [
        {
          name: "Repo",
          link: "#"
        }
      ]
    };
  }
  render() {
    return (
      <AppContent
        userinfo={this.state.userinfo}
        repos={this.state.repos}
        starred={this.state.starred}
      />
    );
  }
}

export default App;

**Comment by juniorb34** [comment]
repos.js

import React from "react";
import PropTypes from "prop-types";

const Repos = ({ className, title, repos }) => (
  <div className={className}>
    <h2>{title}</h2>
    <ul>
      {repos.map((repo, index) => (
        <li key={index}>
          <a href={repo.link}>{repo.name}</a>
        </li>
      ))}
    </ul>
  </div>
);

Repos.defaultProps = {
  className: " "
};

Repos.propTypes = {
  className: PropTypes.string,
  title: PropTypes.string.isRequired,
  repos: PropTypes.array
};
export default Repos;

**Comment by juniorb34** [comment]
app-content.js

import React from "react";
import Search from "./search";
import UserInfo from "./user-info";
import Actions from "./actions";
import Repos from "./repos";
import "../search.css";
import PropTypes from "prop-types";

const AppContent = ({ userinfo, repos, starred }) => (
  <div className="App">
    <Search className="search" />
    {!!userinfo && <UserInfo userinfo={userinfo} />}
    {!!userinfo && <Actions />}
    {!!repos.length && (
      <Repos className="repos" title="Respositórios: " repos={repos} />
    )}

    {!!starred.length && (
      <Repos className="starred" title="Favoritos: " starred={starred} />
    )}
  </div>
);

AppContent.propTypes = {
  userinfo: PropTypes.object.isRequired,
  repos: PropTypes.array.isRequired,
  starred: PropTypes.array.isRequired
};

export default AppContent;

**Comment by juniorb34** [comment]
Não consigo encontrar o erro, eis os arquivos envolvidos!

**Comment by fdaciuk** [comment]
Oi @juniorb34! Consegue subir seu projeto no GitHub? Pra encontrar esse problema fica mais fácil eu baixar aqui e colocar pra rodar, pra entender o que pode estar errado, ok? =)

**Comment by fdaciuk** [comment]
Ou melhor: já vi o problema =) 

Veja que ali no arquivo `app.js` no state do componente, a propriedade `repos` é um número. No curso eu mostrei que esse `repos` deve ser um array =)

Dá uma olhada novamente na aula pra entender essa parte, ok? =)

**Comment by fdaciuk** [comment]
Ah, já vi o problema! =)

Veja que, no arquivo `app-content.js`, você está passando para o componente `Repos` uma prop chamada `starred`, recebendo o valor de `starred`:

```jsx
<Repos className="starred" title="Favoritos: " starred={starred} />
```

O correto é passar o nome da prop como `repos` (assim com a chamada anterior a essa). Seu código deveria ser:

```jsx
<Repos className="starred" title="Favoritos: " starred={starred} />
```

Pois quando esse componente é chamado para exibir os favoritos, você não está passando uma prop chamada `repos`, mas dentro do componente você usa essa prop, saca? Por isso o erro que `repos` é `undefined` =)

**Comment by juniorb34** [comment]
Muito obrigado!!

@fdaciuk
