### ISSUE TITLE
[M1#A47] - GitHub App: Mudando o state ao clicar nos botões

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#212]
Olá, Professor! 

Finalizei a aplicação do GitHub do curso e gostaria de saber se uma implementação específica que fiz está de acordo com o mindset de desenvolvimento em React. 

Ao clicar em “ver favoritos”, o state “repos” recebe um array vazio. E vice-versa:

```javascript
  getRepos (type) {
    return e => {
      this.getGitHubUrlApi(this.state.userinfo.login, type)
        .then(repos =>
          this.setState({
            [type]: repos.map(repo => ({name: repo.name, link: repo.html_url}))
          }, () => type === 'starred' // IMPLEMENTAÇÃO DO TERNÁRIO <------------------------
            ? this.setState({repos: []})
            : this.setState({starred: []}))
        )
    }
  }
```

Caso seja necessário, o código completo está [neste repo](https://github.com/Roger-Melo/revisao-react-ninja-m01). Desde já, obrigado! =) 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Na verdade, tem uma forma melhor de fazer isso, pois o ternário é uma expressão, e sempre vai te retornar um valor. Da forma que você usou, seria melhor usar um `if`, já que você está apenas dando um `setState` dependendo do resultado do teste feito pelo ternário. E como `setState` não retorna valor, não faz sentido usar dessa forma.

Um forma melhor de fazer isso seria criar uma variável para saber qual lista deve ser limpa. Por exemplo:

```js
  getRepos (type) {
    return e => {
      const listThatShouldBeEmpty = type === 'starred' ? 'repos' : 'starred'

      this.getGitHubUrlApi(this.state.userinfo.login, type).then(repos => {
        this.setState({
          [type]: repos.map(repo => ({name: repo.name, link: repo.html_url})),
          [listThatShouldBeEmpty]: []
        })
      })
    }
  }
```

entendeu a ideia? =)

**Comment by Roger-Melo** [comment]
entendi sim, professor. Muito obrigado! =D
