### ISSUE TITLE
Aplicações multi-páginas com React

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#213]
Olá, professor! 

Fiz uma revisão do 1º módulo e estou em dúvida em como seria organizar uma aplicação com várias páginas em React.

Exemplificando, suponhamos que a aplicação do GitHub feita no curso fosse como a busca do Google. Uma página inicial apenas com o input e o logo e outra com os resultados:

![image](https://user-images.githubusercontent.com/29297788/47180082-073c9a00-d2f6-11e8-88b4-1ae41925cf5e.png)

![image](https://user-images.githubusercontent.com/29297788/47180231-71553f00-d2f6-11e8-963b-deda810dbdab.png)

Como isso seria organizado no fluxo do React? Desculpe se estou “passando o carro na frente dos bois”. Estou indo para o 2º módulo e ainda não sei se aplicações multi-páginas serão desenvolvidas no curso xD

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Isso está sendo visto no módulo 4 =)
As próximas aulas que eu estou preparando é de uma aplicação real completa, com rotas, autenticação, e um CRUD de dados (cadastro, leitura, edição e deleção) =)

**Comment by Roger-Melo** [comment]
Saqueeei. O curso está muito legal, professor. Parabéns! :smiley:

**Comment by fdaciuk** [comment]
Show! :D
