### ISSUE TITLE
[M2#A10] - deep.equal do chai

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#215]
Professor, gostaria de saber mais sobre o deep.equal. 

No código abaixo, o que está sendo testado é se o valor retornado na função `map` é um valor do tipo array com 2 valores do tipo number e se não são a mesma referência de array?

Porquê os dois valores do array são diferentes e o resultado do deep.equal ainda é `true`? 

```javascript
it('map([1, 2], (item) => item + 1) should return [2, 3]', () => {
  expect(map([1, 2], (item) => item + 1)).to.be.deep.equal([2, 3])
})
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! O `deep.equal` não testa a referência, mas testa os valores, de maneira "profunda" (deep) no objeto utilizado. No caso de arrays, ele vai testar se o valor e o índice do array correspondem. Para objetos, ele vai testar se as propriedades com o mesmo nome têm o mesmo valor. E se esse valor mais interno ainda for um objeto, ele continua iterando para não testar referências, apenas valores primitivos =)

**Comment by Roger-Melo** [comment]
então, no código acima, o `deep.equal` irá testar se a expressão `map([1, 2], (item) => item + 1)` corresponde a `[2, 3]`?

>No caso de arrays, ele vai testar se o valor e o índice do array correspondem.

Não entendi o que quis dizer =/

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! A ideia é a seguinte: o resultado da expressão `map([1, 2], (item) => item + 1)` deve ser um novo array `[2, 3]`, correto?

Nesse caso, como esse array vai ser uma referência diferente do array que a gente vai testar no `deep.equal`, nós temos que testar duas coisas:
- se os valores internos do array são os mesmos;
- se as posições dos valores estão no mesmo lugar (teste de índices).

É algo assim que o `deep.equal` vai fazer:

```js
const resultadoEsperado = [2, 3]
const valorRecebido = map([1, 2], (item) => item + 1)

return resultadoEsperado[0] === valorRecebido[0] && resultadoEsperado[1] === valorRecebido[1]
```

Sacou a ideia? Ele vai checar se o índice zero do `resultadoEsperado` é exatamente o mesmo valor do mesmo índice zero do `valorRecebido`. Depois, vai checar a mesma coisa, mas para o próximo índice, e assim por diante até que todos os valores no array sejam testados =)

Se algum desses valores ainda for um outro objeto ou array, ele itera de novo e testa novamente os valores desses outros objetos =)

Ficou mais claro? =)

**Comment by Roger-Melo** [comment]
saqueeeei. Agora sim ficou claro hahah. 

Valeu professor! @fdaciuk

**Comment by fdaciuk** [comment]
Show! Qualquer coisa só avisar =)
