### ISSUE TITLE
Use Strict

### ISSUE THREAD

**Issue by juniorb34** [da2k/curso-reactjs-ninja#216]
Professor, atualmente, ainda é necessário o uso do "Use Strict"? Por que?
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @juniorb34! Se estiver usando ES Modules, o código já é _strict_ por padrão, então não precisa. Mas enquanto utilizar ES5, onde não existe um sistema de módulos, aí é preciso usar sim =)

**Comment by fdaciuk** [comment]
Em alguns arquivos no início do curso eu usei mais por "costume" mesmo, mas sempre que usar ES Modules, não é necessário =)

**Comment by juniorb34** [comment]
Obrigado!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
