### ISSUE TITLE
[M2#A10] - typeof

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#217]
professor, vc usou o `typeof` para testar se um tipo é uma função. No JS Ninja, foi recomendado o uso dele para testar apenas tipos primitivos. 

```js
  if(typeof func !== 'function')
    throw new TypeError('func is not a function')
```

Dei uma olhada no MDN, e vi essa tabela: 

![mdn](https://user-images.githubusercontent.com/29297788/47454525-d05afe00-d7a5-11e8-8e0b-c743714c86df.png)

Vc recomenda então o uso do `typeof` para testar qualquer tipo de valor?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Então, o `typeof` é seguro para testar valores primitivos (menos o `null`) e funções =)
Veja que, para os outros tipos de valores, ele vai sempre retornar `object` =)

Para ter um resultado mais apurado, recomendo usar o método `toString` de `Object` (mostrado na aula 27 do curso de JS) =)

**Comment by Roger-Melo** [comment]
entendi, professor. Obrigado! =)
