### ISSUE TITLE
M1#A40 erro

### ISSUE THREAD

**Issue by juniorb34** [da2k/curso-reactjs-ninja#218]
Não consigo inicializar o projeto no servidor.
![image](https://user-images.githubusercontent.com/32278366/47506434-68a8bf80-d846-11e8-833d-63be9b4d094c.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @juniorb34! Pelo erro, a sua versão do node não é compatível com a versão da lib `@fdaciuk/ajax`. Nem sempre isso é um problema, na maior parte das vezes é falta de atualização na lib apenas (que é exatamente esse o caso), então você pode ignorar a entrada "engine" das dependências, usando o comando `yarn install --ignore-engines` para instalar as dependências =)

**Comment by juniorb34** [comment]
Deu certo, obrigado. Eu pergunto: esse conhecimento em tratamento de erros só vem mesmo com muita experiência (erro e acerto) ou existe um caminho especifico para tal? Eu admiro muto esse conhecimento! :)

**Comment by fdaciuk** [comment]
Oi @juniorb34! Isso vem com o tempo sim! O ponto importante para descobrir como resolver esses problemas é tentar entender o erro, e buscar a solução em algum lugar que tenha informações sobre a ferramenta em questão.

Você pode tentar pegar o erro e buscar ele no Google, ou então, como nesse caso o erro acontece ao executar um comando do `yarn`, buscar na documentação do Yarn sobre "engine", ou ainda no GitHub da ferramenta, se essa for open source =)

Fazendo isso, você começa a "acostumar" e entender melhor as mensagens de erro. Pode ser que nem sempre você encontre uma solução, mas com o tempo você via descobrindo novos caminhos ao menos para tentar chegar na solução do problema =)

**Comment by juniorb34** [comment]
Obrigado!
@fdaciuk

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar =)
