### ISSUE TITLE
Meu hotloader não funciona

### ISSUE THREAD

**Issue by darkwolf66** [da2k/curso-reactjs-ninja#219]
Estou com um probleminha no boilerplate, copiei ele e colei para uma pasta para começar o github app, primeiro deu problema que você já resolveu pra outro aluno das dependências, agora o hotloader não ta atualizando nada que alterno no App
![image](https://user-images.githubusercontent.com/2975858/47890819-64286c00-de2f-11e8-9192-f5e1bc3869c2.png)
![image](https://user-images.githubusercontent.com/2975858/47890830-70142e00-de2f-11e8-9ee0-c783c14b0202.png)

@fdaciuk

**Comment by darkwolf66** [comment]
Fiz o repo https://github.com/darkwolf66/Github-App
Valeu pela ajuda  😬

**Comment by fdaciuk** [comment]
@darkwolf66 eu baixei o projeto aqui e testei, e o hot loader funcionou certinho =)
Aparece algum erro pra você quando você tenta atualizar, ou só não atualiza quando você modifica o componente App?

**Comment by darkwolf66** [comment]
Só quando modifico componente App

**Comment by fdaciuk** [comment]
Qual sua versão do node.js e NPM? Só pra eu tentar rodar com as mesmas versões aqui pra ver se esse pode ser o problema =)

**Comment by darkwolf66** [comment]
Essas versões: 
![image](https://user-images.githubusercontent.com/2975858/47945668-4b2cc300-dee2-11e8-9de1-f1a9eaec546c.png)
😬

**Comment by fdaciuk** [comment]
Instalei e testei com essas mesmas exatas versões e está rodando fino :\
Pode ser algum problema específico do windows, aí eu não vou conseguir te ajudar, pois não consigo nem testar :\

Vamos tentar outra coisa: consegue gravar um vídeo da sua tela, com a tela dividida: o navegador de um lado, com o console aberto, e o seu editor de outro? E certifique-se de que esse projeto que você me passou é exatamente a versão que você está testando, ok? Pra não ter divergências =)

**Comment by darkwolf66** [comment]
Fiz um vide-o fazendo alguns testes:
https://www.youtube.com/watch?v=UyPnpN4XpLM

**Comment by fdaciuk** [comment]
Nesses primeiros testes que você está fazendo está aparecendo um warning, mas não dá pra ler no vídeo. Consegue gravar só um tela com esses passos que você fez no início, o console aberto, e aumentar um pouco o tamanho da fonte, só pra eu conseguir ler esse warning que está aparecendo?
