### ISSUE TITLE
Problema pra concatenar propriedades

### ISSUE THREAD

**Issue by brunotortelli** [da2k/curso-reactjs-ninja#22]

**Comment by brunotortelli** [comment]
@fdaciuk fiz a estrutura do desafio deixando as o espaço pras funções no app.js e o resto stateless, porem minha duvida é como pegar o link sendo que precisamos no caso do nome de usuario pra colocar antes do /repos, não consegui fazer essa interação/ concatenação, tem alguma dica? tentei subir os arquivos aqui mas nao deu certo ainda.

**Comment by fdaciuk** [comment]
Fala @brunotortelli! Consegue me mostrar o trecho de código do que você está tentando fazer?

**Comment by brunotortelli** [comment]
@fdaciuk agora vi aqui que tem como concatenar apos a variavel

`console.log(`https://api.github.com/users/${value}/repos`)`

agora minha duvida é, quem ta recebendo o valor do login eh o handleSearch, ele trata o userinfo e devolve o retorno com o userinfo alimentado, agora como eu posso ter acesso a esse valor do userinfo.login, de dentro da função de loadRepos e loadStarred pra poder usar ele nesse link ai de cima? 

`'use strict'

import React, { Component } from 'react'
import AppContent from './components/app-content'
import ajax from '@fdaciuk/ajax'
// import Title from './components/title'

import './css/style.css'

class App extends Component {
  constructor () {
    super()
    this.state = {
      userinfo: null,
      repos: [],
      starred: []
    }
  }

  handleSearch (e) {
    const value = e.target.value
    const keyCode = e.which || e.keyCode
    const ENTER = 13

    if (keyCode === ENTER) {
      ajax().get(`https://api.github.com/users/${value}`)
      .then((result) => {
        this.setState({
          userinfo: {
            username: result.name,
            photo: result.avatar_url,
            login: result.login,
            repos: result.public_repos,
            followers: result.followers,
            following: result.following
          }
        })
      })
    }
  }

  reposLoader (e) {
    const value = userinfo.login
    console.log(`https://api.github.com/users/${value}/repos`)
  }
  starredLoader (e) {
    console.log('Favoritos')
  }

  render () {
    return <AppContent
      userinfo={this.state.userinfo}
      repos={this.state.repos}
      starred={this.state.starred}
      handleSearch={(e) => this.handleSearch(e)}
      reposLoader={(e) => this.reposLoader(e)}
      starredLoader={(e) => this.starredLoader(e)}
      />
  }
}

export default App`

**Comment by fdaciuk** [comment]
Antes de responder: para colocar blocos de código, você pode usar 3 crases pra abrir o bloco, ae escreve o código, e depois fecha com mais 3 crases xD

---

Agora vamos lá! :D

Bom, o `handleSearch` não devolve valor, ele **seta um novo estado** para o seu componente após o request, certo? Esse novo estado contém as informações do usuário.

Sempre que você seta um novo estado, você consegue obter esse valor através do objeto `this.state`.

Nesse objeto você terá todas as informações que precisa =)

Ficou claro?

**Comment by brunotortelli** [comment]
Cara foi a tarde toda mas consegui fazer funcionar e assimilar a ideia, eu dei uma empacada no array, alias esse map o ideai e ir pro APP.JS provavelmente né, no caso ai to usando a mesma estrutura do repos pro starred, igual foi feito antes de ser dinâmico, agora sim ta ficando tudo mais claro, tenho que ver uma forma de quando der search ele não manter os repositórios do user anterior tbm. mas acho que ja da pra seguir com as aulas hehe

# **repos.JS**
```
'use strict'
import React, {PropTypes} from 'react'

const Repos = ({className, title, repos, reposLoader}) => (
  <div className={className}>
    <h2>{title}</h2>
    <ul>
      {repos.map((repo, index) => (
        <li key={index}>
          <a href={repo.html_url}>{repo.name}</a>
      </li>
    ))}
    </ul>
  </div>
)



Repos.defaultProps = {
  className: ''
}

Repos.PropTypes = {
  className: PropTypes.string,
  title: PropTypes.string.isRequired,
  repos: PropTypes.array
}

export default Repos

```

## **app.JS**

```
'use strict'

import React, { Component } from 'react'
import AppContent from './components/app-content'
import ajax from '@fdaciuk/ajax'
// import Title from './components/title'

import './css/style.css'

class App extends Component {
  constructor () {
    super()
    this.state = {
      userinfo: null,
      repos: [],
      starred: []
    }
  }

  handleSearch (e) {
    const value = e.target.value
    const keyCode = e.which || e.keyCode
    const ENTER = 13

    if (keyCode === ENTER) {
      ajax().get(`https://api.github.com/users/${value}`)
      .then((result) => {
        this.setState({
          userinfo: {
            username: result.name,
            photo: result.avatar_url,
            login: result.login,
            repos: result.public_repos,
            followers: result.followers,
            following: result.following
          }
        })
      })
    }
  }

  reposLoader (e) {
    const login = this.state.userinfo.login

    ajax().get(`https://api.github.com/users/${login}/repos`)
    .then((result) => {
      this.setState({
        repos: result
      })
    })
  }

  starredLoader (e) {
    const login = this.state.userinfo.login

    ajax().get(`https://api.github.com/users/${login}/starred`)
    .then((result) => {
      this.setState({
        repos: result
      })
    })
  }

  render () {
    return <AppContent
      userinfo={this.state.userinfo}
      repos={this.state.repos}
      starred={this.state.starred}
      handleSearch={(e) => this.handleSearch(e)}
      reposLoader={(e) => this.reposLoader(e)}
      starredLoader={(e) => this.starredLoader(e)}
      />
  }
}

export default App


```

app-content.JS

```
'use strict'
import React, {PropTypes} from 'react'
import Search from './search'
import UserInfo from './user-info'
import Actions from './actions'
import Repos from './repos'

const AppContent = ({userinfo, repos, starred, handleSearch, reposLoader, starredLoader}) => (
  <div className='app'>
    <Search handleSearch={handleSearch} />
    {!!userinfo && <UserInfo userinfo={userinfo} />}
    {!!userinfo && <Actions reposLoader={reposLoader} starredLoader={starredLoader} />}

    {!!repos.length &&
      <Repos className='repos'
        title='Repositórios'
        repos={repos} />}

    {!!starred.length &&
      <Repos className='starred'
        title='Favoritos'
        repos={starred} />}

  </div>
)

AppContent.propTypes = {
  userinfo: PropTypes.object,
  repos: PropTypes.array.isRequired,
  starred: PropTypes.array.isRequired
}

export default AppContent
```

**Comment by brunotortelli** [comment]
vc usa um plugin que serve pra identar codigo no vim? sera que tem pro atom?

**Comment by brunotortelli** [comment]
@fdaciuk

**Comment by fdaciuk** [comment]
Fala @brunotortelli! Desculpe a demora na resposta =)
Conseguiu entender e resolver?

> vc usa um plugin que serve pra identar codigo no vim? sera que tem pro atom?

Eu uso [essas configurações](https://github.com/da2k/curso-reactjs-ninja/blob/master/config/.vimrc) aqui para o Vim =)

Qualquer dúvida, só avisar xD

**Comment by brunotortelli** [comment]
@fdaciuk esqueci de dar feedback haha, fechei a issue porque me acertei aqui, a aula seguinte que você ensina a zerar os repositórios antes de mudar pra favoritos eu tinha feito corretamente, até aqui ta tranquilo, e o curso ta massa demais. entrei no slack la tbm.

**Comment by fdaciuk** [comment]
Show cara! :grimacing: 

Qualquer dúvida, só avisar!
