### ISSUE TITLE
Duvidas curso react 

### ISSUE THREAD

**Issue by wellingtongabriel** [da2k/curso-reactjs-ninja#220]
Escreva aqui sua dúvida

Olá estou fazendo o curso e tenho uma duvida tem como usar jquery no react ou não seria adequado ? e qual a melhor maneira de validar formulários com react ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @wellingtongabriel! Dificilmente você vai precisar usar jQuery com React.. o React supre tudo o que você faria usando jQuery, de forma muito mais performática e declarativa =)

Mas se ainda assim você precisar usar dá sim: no módulo 1 mesmo eu mostro um exemplo de como usar libs de terceiros junto com React, e nos módulos 1 e 2 tem alguns exemplos de aplicações usando algumas libs externas, para mostrar na prática como fazer :D 

Sobre validação de formulários, isso é e sempre vai ser um parto quando tentar validar com JavaScript: tem que fazer na mão mesmo! O React te ajuda com a ideia de formulários "controlados", onde os valores dos campos são adicionados diretamente no estado do componente, fazendo com que o formulário seja reativo, e no final você só vai precisar enviar os dados do state, tendo a certeza que aqueles são exatamente os valores que forem imputados nos campos.

Mas a parte de validação tem que fazer na mão mesmo =)

Tem uma lib bem legal que pode ajudar, se o seu formulário for muito grande, ou tiver muitas regras. Dá uma olhada no Formik: https://github.com/jaredpalmer/formik/

**Comment by wellingtongabriel** [comment]
ah entendi, vou dar uma olhada muito obrigado! estou indo para o modulo 2
do curso estou gostando muito parabéns!!

Em ter, 6 de nov de 2018 às 11:02, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Perfeito =)
Qualquer dúvida, só avisar :D
