### ISSUE TITLE
Favicon com webpack e react

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#221]
Bom dia @fdaciuk,
uma dúvida simples que eu tenho, qual maneira posso adicionar os favicons em um projeto react?
Porque como utilizamos o htmlPlugin não sei ao certo onde adicionar eles, diretamente no template.html? ou importando na aplicação?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Normalmente favicon não muda dentro da aplicação, então você pode adicionar direto no `template.html` mesmo, sem problemas =)

**Comment by willianrssi** [comment]
@fdaciuk com isso vem outra dúvida kkkkk,
quando eu faço o build ele não copia essas imagens para o diretório criado, tem como automatizar isso ?

**Comment by fdaciuk** [comment]
Justo haha! Na verdade, tem uma forma melhor: o html-webpack-plugin tem uma opção `favicon`, onde você pode passar um _path_ que ele vai adicionar o favicon automaticamente pra você. E quando você fizer o build, a imagem já vai para o lugar certo também =)

**Comment by willianrssi** [comment]
Valeu @fdaciuk,
vou dar uma olhada nessa opção.

**Comment by fdaciuk** [comment]
Show! Se não conseguir, só avisa que eu te ajudo =)
