### ISSUE TITLE
Dúvida no setState()

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#222]
Boa tarde @fdaciuk me pintou uma dúvida no uso do estado do componente.
digamos que eu tenha um componente com o seguinte estado:
```
this.state = {
  todoList: {
    day: '',
    items: []
  }
}
```
para setar um valor em ``` todoList.day ``` eu posso fazer: 

``` 
this.setState({
  todoList: {
    ...this.state.todoList,
    day: 'Monday'
  }
})
```
certo? ou deve ser evitado?
Ou nesse caso é melhor eu usar o `setState()` passando como parâmetro uma função ?
 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Pode fazer isso sim! Só tem que cuidar nos casos em que você precisa usar mais `setState`'s seguidos. Então a minha recomendação seria:

Sempre que você precisar reaproveitar algum valor do estado anterior para setar o novo - como no seu exemplo - use a função =)

**Comment by willianrssi** [comment]
Valeu @fdaciuk,
você recomenda isso por causa que o `setState()` é assíncrono certo?

**Comment by fdaciuk** [comment]
Também! Eu mostrei isso na aula, mas ao usar a função no setState, o React vai executar as funções em ordem, passando sempre para próxima o estado atualizado.

Se usar o `this.state`, você vai estar pegando o objeto que está na classe, logo ele nem sempre vai ser o valor atualizado após mais de duas chamadas seguidas do `this.setState` =)

**Comment by willianrssi** [comment]
Perfeito @fdaciuk irei rever as aulas que abordam o assunto, obrigado mais uma vez =)

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
