### ISSUE TITLE
M01-Aula47->  Problema para criar projeto 

### ISSUE THREAD

**Issue by rodolphonetto** [da2k/curso-reactjs-ninja#223]
Eu copiei os arquivos de dependencias dos exemplos anteriores, rodei o npm install e quando fui compilar o projeto com o npm start, ele me da esse erro da imagem, junto com ela também tem o arquivo package.json com as dependencias que foram instaladas.

https://i.imgur.com/6MPUtyF.png

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rodolphonetto! Dá uma olhada se você chegou a copiar também o arquivo `.babelrc`. Se você estiver usando Linux ou Mac, arquivos que começam com ponto são arquivos ocultos nesses sistemas, então provavelmente, se você copiou os arquivos um a um, deve ter faltado esse =)

**Comment by rodolphonetto** [comment]
Problema resolvido, eu tinha esquecido o .babelrc, ele tava oculto aqui no mac

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar =)
