### ISSUE TITLE
M01#A43

### ISSUE THREAD

**Issue by rodolphonetto** [da2k/curso-reactjs-ninja#224]
No metodo para fazer a requisição dos repositórios vc faz um return (e) com arrow function para "retornar a função" mas eu nao entendi a necessidade disso, no segundo exemplo está como eu fiz, e funciona corretamente tb.

```js
  getRepos (type) {
    return (e) => {
      const username = this.state.userinfo.login
      ajax().get(this.getGitHubApiUrl(username, type))
        .then((result) => {
          this.setState({
            [type]: result.map((repo) => ({
              name: repo.name,
              link: repo.html_url
            }))
          })
        })
    }
  }
```

```js
	getRepos(type) {
		const username = this.state.userinfo.login
		ajax().get(this.getGitHubApiUrl(username, type)).then((result) => {
			console.log(type)
			this.setState({
				[type]: result.map((repo)=> ({
					name:repo.name,
					link: repo.html_url
				}))
			})
		})
	}```


<!-- Não apague daqui pra baixo! -->
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rodolphonetto! Vou explicar =)

No exemplo que eu mostrei, o `getRepos` é usado como listener de evento de um botão. Um evento sempre espera que uma função seja passada, para que, quando o evento for disparado, a função é executada.

Mas veja que, como eu mostrei, nós passamos o `getRepos` para o evento de click **já executando a função**, para que possamos passar o `type`. Nesse caso, se a função não retornar nada, o que vai ser passado para o evento vai ser `undefined`, já que a função não retorna nada, e quando você clicar no botão, nada vai acontecer.

Por isso nós retornamos uma função: ao usar o `getRepos` assim (exemplo):

```js
<button onClick={this.getRepos('starred')}>Starred</button>
```

Nós estamos passando para o evento de click o **retorno** do método `this.getRepos('starred')`. Se ele não retornar nada, o clique não vai funcionar. Por isso retornamos uma função, passando o objeto de evento `e` (que é passado pelo evento de clique quando ele é disparado) =)

Se no seu código você usou o método `getRepos` exatamente como eu mostrei na aula, usando o seu código, o que vai acontecer é que esse método vai ser executado e o request será feito no momento do render do componente, mas ao clicar no botão, nada vai acontecer =)

Ficou claro? =)

**Comment by rodolphonetto** [comment]
Não ficou não :(

Eu usei dessa forma e esta tudo funcionando corretamente.

app-content.js > 	`{!!userinfo && <Actions getRepos={getRepos} getStarred={getStarred} />}`
actions.js > 		```
<button onClick={getRepos} >Ver Respoistórios </button>
		<button onClick={getStarred}>Ver Favoritos</button>
```

**Comment by fdaciuk** [comment]
@rodolphonetto, olha só:

Tá vendo essa arrow function que você está usando [aqui](https://github.com/rodolphonetto/github-app/blob/master/src/app.jsx#L65-L66)?

Essa arrow function tá fazendo o mesmo trabalho da que eu usei pra retornar do `getRepos` =)

Se você fizesse o `getRepos` retornando uma função, poderia usar esse código acima sem a arrow function :)

Deu pra entender a ideia? =)

**Comment by rodolphonetto** [comment]
Assisti de novo ao trecho da aula e após essa explicação agora tudo fez sentindo. Meus botões executam uma função passando um parametro e essa função retorna uma nova função em virtude do parametro passado e essa sim é a função que ˜interessa" para o botão. Obrigado

**Comment by fdaciuk** [comment]
Exatamente isso! =)

Bom, vou fechar a issue, mas qualquer dúvida, é só avisar :D
