### ISSUE TITLE
Fim do Modulo 01

### ISSUE THREAD

**Issue by rodolphonetto** [da2k/curso-reactjs-ninja#225]
Eu terminei o modulo 1 e antes de seguir pro modulo 2, tentei converter uma aplicação de estudos de javascript com ajax e manipulação de dom para o react mas não consegui... sei que não é duvida do curso mas consigo te mandar um e-mail com o github da aplicação e a explicação do problema? Queria ter certeza que entendi o modulo 01 antes de seguir em frente.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rodolphonetto! Sobe seu projeto no bitbucket (onde ele fica privado) e me passa o link via mensagem pela Udemy que eu dou uma olhada, pode ser? =)

**Comment by rodolphonetto** [comment]
Muito obrigado pela atenção, por enquanto eu consegui resolver o problema, pode fechar a issue caso eu não consiga terminar eu envio a mensagem lá :D

**Comment by fdaciuk** [comment]
Perfeito meu caro! Qualquer coisa, só avisar =)
