### ISSUE TITLE
[M2#A20] - loop for sem o 3º parâmetro

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#226]
Oi, professor!

Estou com dúvida em algo simples, mas que ainda não sei se consegui pegar. 

Dado o array `[1, 2, 3]`, ao fazer um loop for apenas com `(let i = arr.length; i--;)`,  
como o `i` está sendo pós decrementado, ele irá ter o valor `3` inicialmente e, na  
próxima vez que for invocado, terá o valor `2`? 

```javascript
  for (let i = arr.length; i--;) // aqui o valor de i é 3
    newArr.push(arr[i]) // aqui é 2
```

Pergunto porque antes do fim da iteração, não tem como ele valer `0` na linha  
`for (let i = arr.length; i--;)` e o `newArr.push(arr[i])` empurrar `0` para o `newArr`,  
porque o `0` é `falsy`.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Na verdade, o que acontece no funcionamento do `for` é o seguinte:

- o primeiro argumento é onde você pode usar para inicializar valores;
- o segundo argumento é a expressão que o `for` vai checar. Enquanto essa expressão retornar `true` (ou um valor `truthy`), o loop vai acontecer;
- o terceiro argumento é a expressão que irá ser executada se o equivalente booleano do segundo argumento retornar `true` =)

Sabendo disso, nós podemos simplificar o `for`, fazendo o seguinte:
- no primeiro argumento, nós iniciamos `i` com o valor do tamanho do array (`arr.length`);
- no segundo argumento nós pós-decrementamos o `i`, ou seja: o equivalente booleano de qualquer número é `true`, menos do zero, que é `false`. Então enquanto `i` não chegar a zero, o loop vai continuar. Com isso, não precisamos do terceiro argumento =)

Quando o loop começa, `i` vale 3, e é esse valor que é testado pelo `for`. Logo após isso, o valor de `i` é decrementado, e `i` passa a valor 2 quando entra no loop. Então Isso sempre vai funcionar, porque o último índice de um array é sempre o `array.length - 1`, saca? =)

Quando o `i` testado no `for` for igual a 1, ele vai entrar no loop valendo zero (pois será decrementado).

Quando ele chegar com o valor zero na próxima iteração, o loop não vai mais ser executado, pois o valor de `i` é zero, e convertendo esse valor em booleano, temos `false`.

O valor final de `i`, nesse caso, vai ser `-1`, pois a decrementação ainda vai acontecer, mas como não precisamos mais dessa variável, não faz diferença =)

Sacou a ideia? =)

**Comment by Roger-Melo** [comment]
Muito bem explicado, professor. Como sempre =) 

Entendi perfeitamente, obrigado @fdaciuk ! :smiley:
