### ISSUE TITLE
010 MRW03

### ISSUE THREAD

**Issue by EvanilsonSouza** [da2k/curso-reactjs-ninja#227]
O servidor webpack está rodando normalmente, porém não esta aparecendo no console a mensagem "webpack está funcionando ". 

Aqui está a configuração do meu Bundle:
'use strict'

const path = require('path')

module.exports = {
    entry: path.join(__dirname, 'src','index'),
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'  
    }
}

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @EvanilsonSouza! Sobe seu projeto aqui no GitHub por favor? E compartilha o link aqui pra eu ver o que pode estar faltando =)

**Comment by EvanilsonSouza** [comment]
claro, esta nessa url: https://github.com/EvanilsonSouza/react-webpack

**Comment by fdaciuk** [comment]
Legal, já vi o problema!
Na verdade não é um problema, é só como você está vendo as coisas =)

O seu index.html está apontando para o JS em `dist/bundle.js`. Ao usar o comando `webpack`, o webpack vai gerar esse arquivo. Então você pode abrir o arquivo `index.html` no seu navegador que você vai ver a mensagem no console.

Agora, se você estiver usando o `webpack-dev-server`, ele vai criar esse arquivo JS em memória, e o caminho dele vai ser `/static/bundle.js` (pois nós usamos lá no `publicPath` o caminho `/static/`, certo, lembra? ) =)

Então, para ver o conteúdo desse arquivo que está em memória, você tem que atualizar seu index.html para apontar para /static/bundle.js, como foi mostrado na aula =)

**Comment by EvanilsonSouza** [comment]
me desculpa esta te incomodando em pleno domingo mas ainda assim, mudado pra static não funcionou
