### ISSUE TITLE
Novas Features 

### ISSUE THREAD

**Issue by victorblevi** [da2k/curso-reactjs-ninja#228]
Escreva aqui sua dúvida
Professor, gostaria de saber se as novas features do react serão aprensentadas, como o react hooks 

@fdaciuk

**Comment by fdaciuk** [comment]
Com certeza! Teremos um módulo só para mostrar as novidades do React!

Assim que os hooks estiverem na versão estável do React, eles serão apresentados sim, assim como a feature completa do Suspense, e todas as novidades que forem surgindo :D
