### ISSUE TITLE
M2#A73 - "node scripts/update.js = Error: spawn yarn ENOENT"

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#229]
E aí @fdaciuk, blz?.

Então, tentei fazer o comando como vc fez no video mas ele aparece um erro aki:

````
node scripts/update.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
````

Pesquisei um pouco e tentei fazer o que disse o @willianrssi (**https://github.com/da2k/curso-reactjs-ninja/issues/84**) e tentei a sua solução tbm (**https://github.com/da2k/curso-reactjs-ninja/issues/32#issuecomment-294932181**), mas não deu certo, o erro persiste...

Não fiz alteração nenhuma, apenas clonei, rodei o `yarn`, pra  instalar as dependências e rodei o comando `node scripts/update.js`

A dúvida é se terei problemas nas próximas aulas por causa disso, ou se existe outra forma de atualizar...

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Ignora esse comando por enquanto.

Vou gravar uma aula do futuro falando para não usar ele, pois, por medidas de segurança, é importante fazer as atualizações de forma manual.

As libs mudam muito rápido, e se uma atualização grande acabar acontecendo, pode quebrar o projeto =)

Pode seguir só usando o boilerplate nas versões que estão nele, e só atualize alguma dependência se for realmente necessário, ok? =)

Se tiver qualquer problema, só me avisar :D

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :D

**Comment by hiwoshu** [comment]
Então aproveitando pra tirar a dúvida,
assim não preciso abrir uma issue no github,
sendo q não é assim tao importante:

não estou usando o webpack-dashboard por causa disso:

[cid:82a4cf13-587b-4855-8161-6f0e025dcccd]

isso acontece só no Hyper, mas em outros terminais ele tbm dá bug mas diferente,
pesquisei mas nao tem nada sobre isso,

tem gente q usa o webpack-dashboard com o Hyper e ele dá algum bug mas nao assim,
no windows, parece q ele so funciona bem mesmo no cmd, até no Windows Power Shell é + ou -.

Nas issues de suporte do webpack-dashboard e do Hyper no github nao tem muito sobre isso
enfim, nao que isso vá atrapalhar o estudo, é só remover webpack-dashboard --  do package.json

Mas so pra saber se vc tem alguma ideia de pq isso acontece.
________________________________
De: Fernando Daciuk <notifications@github.com>
Enviado: quinta-feira, 29 de novembro de 2018 10:36
Para: da2k/curso-reactjs-ninja
Cc: hiwoshu; Mention
Assunto: Re: [da2k/curso-reactjs-ninja] M2#A73 - "node scripts/update.js = Error: spawn yarn ENOENT" (#229)


Qualquer dúvida, só avisar :D

**Comment by fdaciuk** [comment]
Oi @hiwoshu! O webpack dashboard é realmente desnecessário. É só pra deixar a exibição "mais bonitinha", mas pode remover ele sem problemas =)

Não consegui ver a imagem com o problema, provavelmente pq vc deve ter anexado ela ao e-mail, e aqui no GitHub não aparece =)

Mas sem problemas, pode remover ele que não vai atrapalhar em nada os seus estudos =)
