### ISSUE TITLE
Seguir o curso sem o Hot Loader

### ISSUE THREAD

**Issue by MatheusFrez** [da2k/curso-reactjs-ninja#230]
Escreva aqui sua dúvida
Professor já tentei a configuração do Hot loader diversas vezes seguindo exatamente as versão indicadas e os passos a passo das video aulas mas n funciona, tem como eu seguir aprendendo no curso sem usar o Hot loader?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MatheusFrez! Claro, pode sim =)

A única diferença é que você vai precisar atualizar a página a cada alteração =)

Mas se você quiser olhar o que pode estar diferente no seu projeto, com base no que foi feito no curso, você pode acompanhar o código e as versões das dependências de cada aula à partir desse diretório:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

Ou se quiser subir como está seu projeto em um repositório aqui no GitHub, eu posso dar uma olhada para ver o que pode estar acontecendo de errado =)
