### ISSUE TITLE
Novas versões do WebPack, Babel etc

### ISSUE THREAD

**Issue by vitorregisrr** [da2k/curso-reactjs-ninja#231]
Olá Professor, primeiramente queria parabenizar pelo curso, a qualidade é muito boa!
Estou finalizando o módulo de webpack e percebi uma coisa: as versões do webpack, babel etc estão bastante ultrapassadas, a versão do webpack apresentada por exemplo foi a 1, e já estamos na 4.
Por acaso isso não vai prejudicar para projetos futuros? As versões mudam muita coisa, ou a base é a mesma? por que vi que só de baixar a versão errada vem uma tonelada de erros... E tem algum artigo ou vídeo que tu indica para quem quer complementar o curso com aulas mais atuais?
No de mais, a explicação do webpack está ótima, esclareci muitas dúvidas que em outros cursos não tinha entendido.
Um abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @vitorregisrr! Apesar da versão não ser a mais recente, os conceitos são mesmos usados em todas as versões, assim como o React =)

Obviamente a ferramenta evolui, e com isso algumas mudanças são necessárias. Mas no decorrer do curso eu apresento várias dessas mudanças, e em breve teremos um módulo para fazer apenas sobre essas atualizações do React e webpack =)

Então não se preocupe: pode seguir com as versões que eu mostrei no curso que, terminando o módulo 2, você já estará apto para atualizar se quiser! Ou ainda tem 2 outras opções:
- usar o create-react-app (apresentado no início do módulo 2);
- aguardar o módulo de atualizações, onde eu vou mostrar as diferenças de cada versão =)

Qualquer dúvida, só avisar! :D
