### ISSUE TITLE
Erro na configuração do eslint

### ISSUE THREAD

**Issue by justlikedev** [da2k/curso-reactjs-ninja#232]
Olá Daciuk,

Estou no módulo de configuração do boilerplate e após a configuração do eslint estou recebendo alguns warnings por conta do jsx.

![image](https://user-images.githubusercontent.com/33749117/49335175-b8aa3d00-f5cf-11e8-9e21-7af95283e888.png)

![image](https://user-images.githubusercontent.com/33749117/49335199-379f7580-f5d0-11e8-83f8-0f43da7fb746.png)

![image](https://user-images.githubusercontent.com/33749117/49335215-83eab580-f5d0-11e8-925e-6f94cee4d11d.png)

![image](https://user-images.githubusercontent.com/33749117/49335240-c9a77e00-f5d0-11e8-893d-adf7faef24c9.png)

Saberia me dizer se faltou adicionar alguma configuração?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @justlikedev! Se você já está usando JSX, então você precisa do `babel-preset-react` =)

Ele foi mostrado na aula 07 do módulo React + webpack =)

Aqui está o código dessa aula:
https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/react-webpack/mrw-07/.babelrc

**Comment by tarcisiopqdt** [comment]
> 
> 
> Oi @justlikedev! Se você já está usando JSX, então você precisa do `babel-preset-react` =)
> 
> Ele foi mostrado na aula 07 do módulo React + webpack =)
> 
> Aqui está o código dessa aula:
> https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/react-webpack/mrw-07/.babelrc

Estou com o mesmo problema e ja configurei o .babelrc conforme aula 07.
Não sei o que fazer :S

**Comment by rafaelnai** [comment]
> > Oi @justlikedev! Se você já está usando JSX, então você precisa do `babel-preset-react` =)
> > Ele foi mostrado na aula 07 do módulo React + webpack =)
> > Aqui está o código dessa aula:
> > https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/react-webpack/mrw-07/.babelrc
> 
> Estou com o mesmo problema e ja configurei o .babelrc conforme aula 07.
> Não sei o que fazer :S
> 
> meus arquivos...
> https://github.com/tarcisiopqdt/ReactNinja

Eu tive o mesmo problema, então instalei a versão 11 do standard e funcionou!
