### ISSUE TITLE
Lançando objetos de erro em programação funcional

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#233]
Olá, professor @fdaciuk!

Você poderia me ajudar com uma dúvida? Como seria o lançamento de erros  
em programação funcional? Há como evitar os `if`s abaixo?

```javascript
'use strict'

const isParameterAnArray = param => Array.isArray(param)
const isParameterAFunction = param => typeof param === 'function'

const map = (arr = [], func = item => item) => {
  if (!isParameterAnArray(arr))
    throw new TypeError('The first parameter must be an array')

  if (!isParameterAFunction(func))
    throw new TypeError('The second parameter must be a function')

  return (function mapInternal (arrInternal, counter) {
    const [head, ...tail] = arrInternal

    return arrInternal.length === 0
      ? []
      : [func(head, counter, arr), ...mapInternal(tail, counter + 1)]
  })(arr, 0)
}

export default map
```

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Nem sempre trabalhar de forma 100% funcional vai deixar seu código mais legível. E essa é a vantagem do JavaScript: como ele é multi paradigma, você consegue usar o melhor do funcional, estruturado, orientado a objetos, tudo junto =)

O que você teria que fazer para deixar esse código sem os `if`s, seria basicamente usar um ternário no lugar, já que ele retorna uma expressão.

E ao invés de disparar um erro usando `throw`, você poderia só retornar um objeto com o erro.

Mas essas outras formas de fazer vai depender muito de como você vai usar esse código.

Então use a forma que vai deixar o seu código o mais legível possível, e tente sempre aplicar boas práticas no seu código, se aproveitando do melhor que a linguagem te permite =)

Quando você começar a estudar uma linguagem puramente funcional, você vai perceber que a forma de resolver problemas é diferente, pois é como o paradigma te força a trabalhar =)

**Comment by Roger-Melo** [comment]
Entendi, professor. Acho que com o `if` ali fica mais legível, né?

> E ao invés de disparar um erro usando throw, você poderia só retornar um objeto com o erro.

Apenas por curiosidade, neste caso, o `TypeError` seria utilizado sem o `new`?

**Comment by fdaciuk** [comment]
> Entendi, professor. Me empolguei com o funcional hahah. Acho que com o if ali fica mais legível, né?

haha! Sim, eu pelo menos acho que fica melhor assim =)

> Apenas por curiosidade, neste caso, o TypeError seria utilizado sem o new, invocado como uma função, desta forma: TypeError('message')?

Não! Você pode construir normalmente um novo objeto de erro, só que, ao invés de usar o `throw`, pode usar o `return`, por exemplo =)

Ou ainda retornar um novo objeto, do tipo:

```js
return {
  error: true,
  message: 'Mensagem com o porquê do erro'
}
```

Enfim.. existem várias formas de se fazer, e a forma que você vai usar vai depender de como você vai tratar esse erro na sua aplicação. No geral, não é legal usar `throw`, a menos que você saiba muito bem o que está fazendo, pois o `throw` pode quebrar sua aplicação se a chamada da função não estiver dentro de um `try/catch`, por exemplo.

**Comment by Roger-Melo** [comment]
Ahhhh sim. Feshow, professor!

Como eu me sinto quando vc responde minhas issues (sou o caído no chão)

![daciuk](https://user-images.githubusercontent.com/29297788/49605944-1a282e00-f979-11e8-8fe3-d561bcfefcb3.gif)

**Comment by fdaciuk** [comment]
:joy: :joy: 

Sempre às ordens =)
