### ISSUE TITLE
[M2#A34] - Código gerado para produção não é minificado

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#234]
Olá, professor!  

Inseri o `webpack.optimize.UglifyJsPlugin` no `webpack.prod.config.js`, mas  
os arquivos em produção não estão sendo minificados. Você poderia dar um  
help? Se o código abaixo não for o suficiente, os arquivos estão  
[neste repo](https://github.com/Roger-Melo/estudos-curso-react-ninja/tree/master/examples/m02/working-with-assets/github-app).

```javascript
// webpack.prod.config.js
'use strict';

const path = require('path');
const webpack = require('webpack');
const validate = require('webpack-validator');

const HtmlPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const crp = new ExtractTextPlugin('crp.css')
const styles = new ExtractTextPlugin('[name]-[hash].css')

module.exports = validate({
  entry: path.join(__dirname, 'src', 'index'),

  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name]-[hash].js'
  },

  plugins: [
    crp,
    styles,

    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': '"production"'
      }
    }),

    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),

    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurrenceOrderPlugin(),

    new HtmlPlugin({
      title: 'GitHub App',
      inject: false,
      template: path.join(__dirname, 'src', 'html', 'template.html')
    })
  ],

  module: {
    preLoaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'standard'
    }],

    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'babel'
    }, {
      test: /\.css$/,
      exclude: /node_modules|(search|style)\.css/,
      include: /src/,
      loader: styles.extract('style', 'css')
    }, {
      test: /(search|style)\.css$/,
      exclude: /node_modules/,
      include: /src/,
      loader: crp.extract('style', 'css')
    }]
  }
});
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Você está falando dos arquivos JS ou CSS? Porque os JS estão minificados =)

**Comment by Roger-Melo** [comment]
Desculpe, professor. Não expliquei direito. Na verdade, o css não está minificado. @fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Sem problemas =)
A culpa é do `css-loader` xD
Teve uma atualização na lib com breaking change: a versão usada no curso é a `0.25`, e a que você tem é a `1.0`, onde a opção de minificar automaticamente foi removida :\

Para resolver, você pode só instalar a última release da versão `0`, assim:

```
npm install --save-dev css-loader@0
```

Fazendo isso ele já vai minificar certinho =)

Ou, se quiser manter essa versão, só dá uma olhada na documentação da release, pra ver o que precisa ser feito pra minificar: 
https://github.com/webpack-contrib/css-loader/releases

De qualquer forma, já adicionei no arquivo de ["atualizações de dependências"](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) essa versão! Obrigado por reportar =)

Qualquer dúvida, só avisar :D

**Comment by Roger-Melo** [comment]
feshow, professor!
