### ISSUE TITLE
[M2#A43] - npm run storybook retorna erro no console

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#235]
Olá, professor! 

Instalei o storybook com o `npm i -g getstorybook@1.6.1`, ao rodar o `getstorybook` é retornado o seguinte erro: 

![image](https://user-images.githubusercontent.com/29297788/49780269-f35d5500-fcf4-11e8-8bbb-5009a690ab89.png)

E quando executo o `npm run storybook`, mais erros são exibidos: 

![image](https://user-images.githubusercontent.com/29297788/49780288-0a9c4280-fcf5-11e8-87b1-12a653194c41.png)

Tentei encontrar a soluçãon as issues daqui e [nesta página](https://storybook.js.org/basics/guide-react/), mas o erro continua ocorrendo. Você pode me ajudar? 

Caso seja necessário, o repo com todos os arquivos é [este](https://github.com/Roger-Melo/estudos-curso-react-ninja/tree/master/examples/m02/working-with-assets/github-app).

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Provavelmente nesse projeto você já tinha instalado o `@kadira/storybook`, certo?
Como você usou o "-f", ele forçou a instalação da última versão, que tem algumas mudanças (eu mostro essas mudanças ao longo do módulo 2).

Então basicamente, o que você precisa fazer, é só remover o `@storybook/react`, que tudo deve funcionar corretamente =)

**Comment by fdaciuk** [comment]
Ah, pra remover é só usar `npm remove --save-dev @storybook/react` =)

**Comment by Roger-Melo** [comment]
funcionou. Obrigado, mestre @fdaciuk !
