### ISSUE TITLE
GitHub App - Duvida quanto a renderização da aplicação

### ISSUE THREAD

**Issue by gagres** [da2k/curso-reactjs-ninja#236]
Eu gostaría de saber se, ao criar um componente durante o projeto do GitHub App chamado AppContent, encapsulando todos os outros componentes da aplicação dentro dele, e colocando toda a manipulação de estado dentro do App apenas, isso não deixa mais lenta a renderização da aplicação?

Porque toda vez que qualquer propriedade for alterada, independente de qual foi ou para qual componente essa nova propriedade será utilizada, toda a aplicação terá de ser renderizada novamente, incluindo componentes que não possuem nada a ver com o estado que foi alterado. Isso não é um gasto de update do DOM desnecessário? Não existe uma forma melhor de faze-lo sem termos que alterar componentes que não tem nada a ver com o novo estado da aplicação?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gagres! Na verdade não =)
O React não faz atualizações diretamente no DOM. Lembra da aula que falamos sobre o "Virtual DOM"? O React tem uma cópia em memória da estrutura da nossa aplicação. Qualquer alteração de estado é feita primeiramente nessa árvore em memória.

E assim que o React já tem a nova árvore em memória atualizada, aí sim ele vai atualizar o DOM, fazendo somente os updates nos lugares necessários.

Se algum componente não for modificado por uma atualização de state, esse componente não será adicionado no DOM novamente, sem necessidade =)

Dificilmente você vai precisar se preocupar com updates de DOM se estiver escrevendo sua aplicação corretamente: usando imutabilidade, e mantendo os componentes puros.

Preocupe-se somente em manter os seus dados escritos de forma correta. O trabalho sujo de atualização do DOM com segurança e o máximo de performance possível você pode deixar com o React que ele se vira bem, e a lib está em constante atualização, para cada vez performar melhor =)

Claro que há casos e casos. No módulo 2 nós vamos falar um pouco mais sobre otimizações, e no módulo 4 você vai ver um exemplo de uma SPA completa, levando em consideração todos esses pontos para aplicações que precisam crescer, mantendo a performance =)

**Comment by gagres** [comment]
Beleza @fdaciuk , muito obrigado pela explicação, vamos continuar os estudos, hahahaha =]

**Comment by fdaciuk** [comment]
Segue em frente! Qualquer dúvida, só avisar =)
