### ISSUE TITLE
Jest testes

### ISSUE THREAD

**Issue by gagres** [da2k/curso-reactjs-ninja#237]
Escreva aqui sua dúvida

Professor, sobre a ferramenta Jest em sua versão atual **^23.6.0**, dentro da parte de testes o comando --watch só funciona se você estiver com um repositório inicializado no projeto. Descobri fazendo os testes aqui, caso não esteja ele da esse erro:

![screenshot from 2018-12-12 09-59-38](https://user-images.githubusercontent.com/10873171/49868463-ac568900-fdf4-11e8-8f3a-775f6937d2a3.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Legal @gagres! Obrigado por lembrar disso. Vou colocar uma nota no curso, que é possível usar o `--watchAll` se não quiser iniciar um repositório `git` =)
