### ISSUE TITLE
M1#A43 Dúvida

### ISSUE THREAD

**Issue by RafaelMouraFrontend** [da2k/curso-reactjs-ninja#239]
Escreva aqui sua dúvida
Na aula  M1#A43 tentei fazer com que  os repositórios fossem listados com a função, mas parece não funcionar de jeitno nenhum, fiquei hj o dia todo procurando o erro, nem aparecer no console aparece :(

Segui o link do repositório, se puder me dar um Help: https://github.com/RafaelMouraFrontend/github-app/ 

```
  getRepos (type) {
    return (e) => {
      ajax().get(`https://api.github.com/users/fdaciuk/${type}`)
        .then((result) => {
          this.setState({
            [type]: result.map((repo) => ({
              name: repo.name,
              link: repo.html_url
            }))
          })
        })
    }
  }
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RafaelMouraFrontend! 
Baixei o projeto aqui, e vi onde está o problema! Na verdade, esse é o problema que assola todo programador.

Os problemas estão [aqui](https://github.com/RafaelMouraFrontend/github-app/blob/master/src/components/app-content.js#L14) e [aqui](https://github.com/RafaelMouraFrontend/github-app/blob/master/src/components/app-content.js#L20).

Você escreveu `lenght`. O correto é `length` (TH no final) :D 

Mas fique tranquilo que isso acontece com TODO MUNDO =)
