### ISSUE TITLE
M1#A40 - Utilizando a Fetch API no React

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#240]
Ho ho ho! Feliz Natal, professor!

Para fazer request dos dados do user utilizando a Fetch API, é necessário importá-la primeiro? 

Fiz isso e deu certo:  

```javascript
import fetch from 'isomorphic-fetch'

// código omitido
        if (keyCode === enter) {
          fetch(`https://api.github.com/users/${value}`)
            .then(res => {
              if (res.ok) {
                return res.json()
              }
            })
            .then(res => console.log(res))
        }
// código omitido
```

![image](https://user-images.githubusercontent.com/29297788/50425350-70430f80-085b-11e9-8c20-383f0c4579b1.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! A Fetch API é uma feature que está implementada na própria engine que roda o JS, não sendo necessário importar nada, só usar!

Você só precisa importar se instalar alguma lib que simula o comportamento da fetch API, usando alguma outra técnica já disponível no ambiente em que você importa a lib: no caso do browser, ele vai usar o fetch se disponível e, se não, ele vai ser o XHR.

Já no node, ele pode usar o módulo `request` ou algum outro por baixo dos panos.

A ideia de usar uma lib é apenas abstrair o comportamento da fetch API para ambientes que ainda não têm essa feature implementada =)

**Comment by Roger-Melo** [comment]
Saquei, professor. Valeu!
