### ISSUE TITLE
M1#A18  - Dúvida

### ISSUE THREAD

**Issue by alexandrenilton** [da2k/curso-reactjs-ninja#241]
Olá Fernando.
Me surgiu uma dúvida na aula do titulo.
Quando uso o onClick no div, funciona perfeitamente.
Porém, quando adiciono o onClick no <LikeButton /> (Componente criado nos videos anteriores) não funciona, é normal esse comportamento, por se tratar de um componente? 
A página renderiza sem nenhum erro, porém quando clico em Curtir, o texto não é trocado.

```jsx
class App extends Component {

  constructor () {
    super()
    this.state = {
      text: 'Hello from ReactJS State'
    }
  }


  render () {
    return(
      <div className="container" >
        <LikeButton onClick={() => this.setState( {text: 'Alexandre'})} />
        <SearchButton />
        {this.state.text}
      </div>
    )
  }
}
```

Obrigado!
Estou adorando o curso, iniciei ontem cedo e já to frenético pra aprender mais.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @alexandrenilton! Que bom que está curtindo o curso :D 
Vamos lá:

Quando você usa `div` para criar um componente (ou qualquer nome referente à tags do HTML), esse elemento vai ser renderizado no DOM. O que significa que você consegue passar atribuitos e eventos para esse elemento, da mesma forma que você faria com JS puro, certo?

Mas quando você cria um componente, esse componente criado por você, em algum momento, vai retornar um elemento do DOM.

A diferença é que, quando você passa `onClick` para o componente que você criou, você está passando uma _prop_ para esse componente.

A pergunta que você deve fazer é: quem é que deve disparar o evento de click?

Imagine que o seu `LikeButton` tivesse essa estrutura:

```jsx
const LikeButton = () => (
  <div>
    <span>Like</span>
    <span>Outro texto</span>
  </div>
)
```

Veja que nesse componente `LikeButton`, eu tenho 3 elementos que serão renderizados no DOM: uma `div`, e 2 `span`, correto? Quem é que deve receber o evento de click?

Por isso, para componentes criados por você, você recebe via argumento na função (ou via props), as props passadas no componente acima.

Exemplo: você chamou seu componente `LikeButton` assim:

```jsx
<LikeButton onClick={() => this.setState( {text: 'Alexandre'})} />
```

Veja que você usou uma prop chamada `onClick`, e passou para essa prop uma função. 

Então você precisa, dentro do componente `LikeButton`, pegar essa prop e passar pra algum elemento que vai receber esse evento:

```jsx
const LikeButton = ({ onClick }) => (
  <div onClick={onClick}>
    <span>Like</span>
    <span>Outro texto</span>
  </div>
)
```

No exemplo acima, veja que o `onClick` - que é uma função - é passado dentro do objeto de props que o componente recebe. Eu simplesmente pego essa função, e passo ela pra quem eu quero que, ao ser clicado, execute essa função. No caso, eu passei para a `div`, mas poderia ter passado para qualquer `span` também =)

Ficou claro a ideia? Sempre que você cria um componente próprio, não é esse componente que vai ser renderizado no DOM, mas sim o que esse componente estiver retornando :)

**Comment by GugaDavi** [comment]
Opa Daciuk.

Excelente explicação. Entendi o funcionamento e que precisamos determinar quem receberá o evento, contudo fazendo aqui ainda não acontece nada.

```
'use strict';

import React from 'react';

const Button = ({ children, onclick }) => (
  <button onClick={onclick}>{children}</button>
)

export default Button;
--------
'use strict'

import React from 'react';
import Button from './button';

class App extends React.Component {
  constructor () {
    super()
    this.state = {
      name: 'Gustavo'
    }
  }
  render () {
    return (
      <div>
        <Button onClick={() => {this.setState({ name: 'Matheus' })}}>
          Mudar Nome
        </Button>
        <br/><br/>
        <Button>{this.state.name}</Button>
      </div>
    )
  }
}

export default App

```
Teria como ver o que estaria errado? Não apresenta nenhum erro na compilação.

**Comment by fdaciuk** [comment]
Oi @GugaDavi! O problema agora é apenas _typo_ (digitação):
Veja que o seu componente `Button` recebe uma prop `onclick` (tudo minúsculo), mas na hora de passar a prop pra ele, você passa `onClick` (com o `c` maiúsculo) =)
