### ISSUE TITLE
M2#A39

### ISSUE THREAD

**Issue by VagnerNico** [da2k/curso-reactjs-ninja#242]
Boa tarde Fernando:

Olha só gerei os arquivos no build conforme descrito em aula, mas quando rodo o server local com python simplesmente não carrega os estilos, eles estão ali no head e o arquivo referênciado no corpo do html; Porém, não aplica os estilos.

Suas aulas são excelentes, gostei muito da metodologia de explorar o desenvolvimento das funções para arrays!

Atenciosamente,

Vagner José Nicolodi

@fdaciuk

**Comment by VagnerNico** [comment]
Descobri o problema eu havia importado da seguinte forma:

`import style from './Search'

<div className={ style.search }`

Depois de remover a importação dessa forma e importar somente o css e nomear a class estaticamente o problema se resolveu!

**Comment by fdaciuk** [comment]
Oi @VagnerNico! Que bom que conseguiu resolver =)

Fico feliz em saber que está curtindo as aulas :D

Qualquer dúvida, só avisar =)
