### ISSUE TITLE
Redux or not Redux that is the question

### ISSUE THREAD

**Issue by VagnerNico** [da2k/curso-reactjs-ninja#244]
Bom dia @fdaciuk 
Novamente parabéns pelo curso, ele é fenomenal! Estou recomendando para todo mundo hehehehe!
Pois então minha dúvida é sobre quando devo optar por usar o Redux na minha aplicação ou não.
Pergunto porque eu tenho uma aplicação em Django com jQuery e estou estudando React justamente para migrar a aplicação, o Django vai ficar com minha API e vou fazer uma SPA em React.
Desde já agradeço a sua atenção!

Um grande abraço!

@fdaciuk

**Comment by VagnerNico** [comment]
Entendi, por exemplo o hash do JWT seria interessante passar com o Redux, que daí eu posso buscar ele em qualquer parte da minha aplicação para autenticar as solicitações para API.

**Comment by fdaciuk** [comment]
Sim, seria um caso =)
Mas se for pra usar só isso, e sua aplicação for só pra web, melhor persistir essa informação local mesmo, com IndexedDB, por exemplo =)
