### ISSUE TITLE
M2#A115 - Error: Can't resolve '@kadira/storybook'

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#245]
E aí @fdaciuk, blz?

Tá dando erro aqui no Storybook:

![captura de tela 8](https://user-images.githubusercontent.com/39469118/51047468-b44e4800-15af-11e9-88af-d9172aef5c61.png)

Sabe o porque disso?

Aguardo.
Obg

@fdaciuk

**Comment by hiwoshu** [comment]
@fdaciuk Esquece, já achei!

é so trocar `@kadira/storybook` pra `@storybook/react` q funciona

pode fechar ai, q tá funcionando

podia por uma nota lá no video, pq no template tá `@storybook/react`, mas no video vc fala pra por `@kadira/storybook` e aí não funciona.

vlw

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Na verdade, houve sim uma atualização no storybook (que você vai ver mais pra frente), e eu mostro essa atualização =)

Pra acompanhar com a versão que eu mostrei na aula, você pode seguir [esse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#m2a30-e-m3a43) :)

Mas que bom que deu certo! Qualquer problema avisa ae =)
