### ISSUE TITLE
M1#A03 - Qual arquivo importar?

### ISSUE THREAD

**Issue by rrmontuan** [da2k/curso-reactjs-ninja#247]
A versão mais recente do React é a 16.7.0. Por esse motivo os arquivos são diferentes daqueles apresentados no curso (Versão 15.1.0), quais deles deveriam ser importados e quais as diferenças? Os arquivos disponíveis na versão 16.7.0 são esses:

https://cdnjs.cloudflare.com/ajax/libs/react/16.7.0/cjs/react.development.js
https://cdnjs.cloudflare.com/ajax/libs/react/16.7.0/cjs/react.production.min.js
https://cdnjs.cloudflare.com/ajax/libs/react/16.7.0/umd/react.development.js
https://cdnjs.cloudflare.com/ajax/libs/react/16.7.0/umd/react.production.min.js
https://cdnjs.cloudflare.com/ajax/libs/react/16.7.0/umd/react.profiling.min.js

Percebi que quando uso os 2 primeiros a variável `React` não existe conforme mostrado aos 05:10 minutos da aula. Além disso não existe mais o `react-dom`.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rrmontuan! É importante usar as versões mostradas nas aulas, para conseguir acompanhar corretamente o curso. Com o passar das aulas, nós vamos atualizando, não se preocupe =)

Para importar do CDNJS, pode usar a versão `umd` =)
