### ISSUE TITLE
M2#A42

### ISSUE THREAD

**Issue by gagres** [da2k/curso-reactjs-ninja#248]
Boa noite professor! Eu queria saber o que acontece com nossos módulos ao realizar o build para produção da aplicação quando usamos os aliases do webpack? Funciona normalmente? O arquivo de bundle gerado virá com os paths de forma relativa ou absoluta?

O curso está sensacional, conteúdo muito massa e de qualidade!!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gagres! Aplicações frontend não entendem módulos, da forma que usamos.
Essa feature é do Node.js, usada no backend.

Quando criamos aplicações frontend usando módulos, precisamos de ferramentas para pegar o conteúdo desses módulos e "trazer" para dentro da nossa aplicação, de forma estática.

Então, quando geramos a versão de produção da nossa aplicação, o webpack vai pegar todas as dependências e colocar no bundle final, usando código que o browser consegue entender =)

Mesma ideia para os alias: por baixo dos panos, o webpack mapeia os caminhos e os módulos em objetos, e quando geramos a versão de produção, ele entrega tudo certinho para o browser saber o que fazer =)

**Comment by gagres** [comment]
Value pela explicação e resposta rápida professor.
Então em prod sem chances de dar problema utilizando o resolve do webpack né?

**Comment by fdaciuk** [comment]
Se não der problema enquanto você está desenvolvendo, dificilmente vc vai ter problemas em prod =)
