### ISSUE TITLE
Dúvida sobre a continuação do módulo 4

### ISSUE THREAD

**Issue by VagnerNico** [da2k/curso-reactjs-ninja#249]
Boa tarde professor:

Você têm uma ideia do release date das próximas aulas para completarmos a aplicação React-zzaria, pergunto por estar me programando para migrar uma aplicação em jQuery e gostaria de esperar esse desenvolvimento para me sentir mais a vontade com o Router.
Aproveitando ainda esse espaço, fiz o download de templates prontos em React e percebi que algumas pessoas usam e abusam de class components e outros utilizam mais function components, quais as implicações de usar mais um ou outro? altera algo no desempenho?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @VagnerNico! A ideia é tentar terminar o módulo 4 até metade de fevereiro, no máximo!

Sobre usar class ou funções, eu recomendo que você prefira escrever seus componentes como funções ao invés de class. Funções são mais simples, e minificam melhor, deixando o bundle final bem menor :)

Use class apenas quando precisar manipular estado, e mantenha o estado sempre isolado do restante da aplicação, como foi mostrado em todas as aplicações que fizemos durante o curso =)

No desenvolvimento da React-zzaria, nós vamos ver como usar esse conceito aplicado à SPAs =)

**Comment by VagnerNico** [comment]
Show de bola @fdaciuk obrigado pelo retorno!
Novamente parabéns por todo o trabalho, tua didática lembra muito uma professora que tive na faculdade que abordava a essência de elementos chaves que utilizaríamos posteriormente no curso.

**Comment by fdaciuk** [comment]
Legal @VagnerNico! Fico muito feliz em saber que está curtindo :D 
Vamos em frente! Qualquer coisa, avisa ae :D
