### ISSUE TITLE
React + Webpack #10

### ISSUE THREAD

**Issue by filipeltsilva** [da2k/curso-reactjs-ninja#25]
@fdaciuk, estou seguindo os vídeos e reproduzindo os exemplos da forma mais fiel possível. Entretanto, na aula 10 da configuração do Webpack, ao adicionar o standard no preLoader ocorre o erro conforme imagem abaixo. Parece ser algum erro no pacote do Webpack mesmo ou será que fiz algo errado?

O link para o código está [aqui](https://github.com/filipeltsilva/reactjs-labs/tree/master/curso-react-ninja/001-webpack/006-lint-tool).

![screen shot 2017-02-22 at 23 58 03](https://cloud.githubusercontent.com/assets/830213/23243206/2040598a-f95c-11e6-9cbd-989e9810234c.jpg)

P.S.: esse Webpack é chato, hein! 😝

**Comment by pauloregis** [comment]
Não sei se é isso, mas essa aula deve ter sido gravado na versão 1 do webpack e provavelmente vc deve ter baixado a v2.. acredito q se vc setar no package.json o webpack para versão utilizada na aula, q deve ter no repositório do curso, tudo deve rodar normalmente...

obs: se vc fizer isso nesse projeto, acredito q vai ter q remover, limpar o cache do npm e depois instalar na versão utilizada na aula

**Comment by fdaciuk** [comment]
Fala @filipeltsilva! É isso mesmo que o @pauloregis comentou: a versão que estamos usando nos vídeos do módulo `#01` são para o `webpack v1`. No módulo `#02`, nós começamos a migração para a `v2`.

Mas sim, isso vai causar confusão mesmo :|

Vou ver se consigo adicionar comentários nos vídeos mostrando que deve-se instalar a v1 para funcionar corretamente, senão eu gravo outros pra corrigir esses problemas =)

Mas basicamente seria, ao invés de rodar:

```
npm install --save-dev webpack
```

Execute:

```
npm install --save-dev webpack@1
```

Fazendo isso, ele vai instalar o último _release_ da v1 e tudo vai ficar certo =)

Me avisa se deu certo, por favor?

**Comment by filipeltsilva** [comment]
@fdaciuk e @pauloregis, de fato utilizei a versão 2, que na época dos vídeos ainda estava em beta, se não me engano. Vou fazer os testes com a v1 e dou um retorno. Grato pelo auxílio.

**Comment by fdaciuk** [comment]
Show! Eu adicionei algumas informações nos vídeos sobre isso, mas provavelmente vou ter que regravar alguns pra ficar mais clara essa transição =)

**Comment by filipeltsilva** [comment]
@fdaciuk e @pauloregis, para registro, fiz o downgrade dos pacotes webpack, webpack-dev-server e webpack-validator para a versão 1 e o código rodou sem erros. Obrigado pelos esclarecimentos.

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar =)
