### ISSUE TITLE
M2#A128 - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#250]
E aí @fdaciuk, blz?

Eu incomodando de novo...
Então, eu finalizei as aulas do markdown-editor, e deixei pra rodar o `yarn dev` no final, mas aí deu esse erro:

![captura de tela 9](https://user-images.githubusercontent.com/39469118/51281808-9d05c500-19ca-11e9-9239-b568e3175ae4.png)
`Uncaught TypeError: Cannot convert undefined or null to object` na linha 10 do `files.js` : 
```
>>>>{Object.keys(files).map((fileId) => (
        <li key={fileId}>
            <button onClick={handleOpenFile(fileId)}>{files[fileId].title}</button>
        </li>
    ))}
```
copiei o codigo do repositório do curso e testei e tbm aparece o mesmo erro
Todos os códigos dos arquivos estão iguais aos do repositório do curso, linha por linha

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Testei aqui e realmente tem um bug quando o localStorage começa zerado =)
Vou criar uma aula do futuro pra corrigir o problema, obrigado por reportar :D 

Pra resolver, é só modificar [essa linha](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m02/applications/markdown-editor/src/app.js#L99), no arquivo `src/app.js`, para usar o `files` apenas se ele existir. Senão, vamos usar um objeto vazio.

A linha deve ficar assim:

```js
this.setState({ files: files || {} })
``` 

Obrigado mais uma vez por reportar, e desculpe o vacilo =)

**Comment by hiwoshu** [comment]
Não, tranquilo! Eu achei que era erro meu.
Agora tá tudo funcionando certinho
Valeu! 👍

**Comment by fdaciuk** [comment]
Show! Vou gravar a aula do futuro e já subo lá =)
Obrigado mais uma vez, e qualquer dúvida, só avisar :D
