### ISSUE TITLE
Redux com API

### ISSUE THREAD

**Issue by VagnerNico** [da2k/curso-reactjs-ninja#251]
Grande professor,

Estou me aprofundando em redux aqui por ter gostado da ideia de deixar o estado para ser administrado pelo Redux e usar os componentes como views.
O meu reducer vai ter as ações de ADD_USER, UPDATE_USER e REMOVE_USER e vai se comunicar com uma API.
Eu estou criando o reducer usando TDD e cheguei na seguinte dúvida, a API gera o Id, last_login e date_joined pra mim, por um momento travei porque em todos os exemplos a gente lida com basicamente todos os campos que estarão no state. O que eu pensei em fazer no ActionsCreator seria o post pro servidor e logo após um fetch do usuário coletando as informações geradas pelo backend e então passaria para o dispatch para adicionar ao state do redux, seria esse o caminho certo, ou quando lidamos com API o reducer seria diferente?

Desculpa o texto gigante mas queria dar o contexto para a dúvida.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @VagnerNico! O Redux, da forma como ele foi criado, só funciona de forma síncrona.
Dá pra fazer ações assíncronas com Redux, mas aí só usando extensões.

No decorrer do módulo 3 eu mostro como fazer isso da forma correta. Recomendo você dar uma olhada nas aulas antes de começar a mexer, porque é preciso levar alguns pontos em consideração =)

**Comment by VagnerNico** [comment]
@fdaciuk lembrei, utilizando os middlewares, posso dar um fetch e aguardar o retorno da promise para de fato alterar o estado.
Mas na hora de realizar os testes, no caso do Id que será gerado pelo backend, eu posso testar com Id's arbitrários definidos por mim e quando colocar para rodar com a store utilizar um middleware para tornar o redux assíncrono e então aguardar o retorno do Id pelo servidor?

**Comment by VagnerNico** [comment]
@fdaciuk reassisti as aulas e brilhou aqui hehehehehe
Fiz da maneira que falei acima, criei meu Reducer com testes passando Id's arbitrários.
Posteriormente no ActionsCreator.js fiz uma função que faz o starterFetch que me retorna um array de objetos, depois faço o map dele utilizando a action ADD_USER e o state tem os dados, agora é só fazer com que a post request tenha uma response com o user criado (totalmente dependente do backend) e atualizar o state através da action padrão.
A felicidade e satisfação de entender o workflow do Redux é indescrítivel hehehehehe
Dalhe professor!!!!
