### ISSUE TITLE
Utilizando o SASS

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#252]
Oi professor! Eu gostaria de utilizar o SASS no GitHub App mas estou com alguns problemas, você pode me ajudar? 

Instalei o sass-loader e o node-sass como dev-dependencies do GitHub App, mudei a extensão dos arquivos dentro do diretório 'src' para `.scss` e incluí o 'sass-loader' no webpack.config.js e no webpack.prod.config.js. 

Ao executar o `npm start`, há uma msg no console dizendo que existem arquivos duplicados: 

![image](https://user-images.githubusercontent.com/29297788/51354643-60ee6500-1a9b-11e9-965f-6a1c931273b4.png)

Ao executar o `npm run build`, essa msg de erro é exibida: 

![image](https://user-images.githubusercontent.com/29297788/51355000-bf681300-1a9c-11e9-8dec-0810b0c7d879.png)

Como posso consertar isso? 

Vou deixar os códigos abaixo, mas caso seja necessário, os arquivos estão [neste repo](https://github.com/Roger-Melo/react-ninja-review/tree/master/examples/m02/github-app).

```javascript
// webpack.config.js

  module: {
    preLoaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'standard'
    }],

    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'babel'
    }, {
      test: /\.scss$/,
      exclude: /node_modules/,
      include: /src/,
      loaders: ['style', 'css?modules', 'sass-loader']
    }]
  },
```
```javascript
// webpack.prod.config.js

    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'babel'
    }, {
      test: /\.scss$/,
      exclude: /node_modules|(search|style)\.css/,
      include: /src/,
      loader: styles.extract('style', 'css', 'sass-loader')
    }, {
      test: /(search|style)\.css$/,
      exclude: /node_modules/,
      include: /src/,
      loader: criticalRenderingPath.extract('style', 'css', 'sass-loader')
    }]
```

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @Roger-Melo! Sobre os arquivos duplicados, como você está usando nesse projeto a v1 do webpack, ele tem um plugin que remove esses arquivos, deixando o bundle final mais limpo.

Mas recomendo que você atualize ao menos para a v2, que já usa esse plugin por padrão. Vai deixar seu projeto mais simples =)

Obs.: testei aqui com a v1 e o plugin `webpack.optimize.DedupePlugin()`, mas ainda assim o webpack dashboard fica dando o aviso de duplicado.. talvez seja um falso positivo do webpack dashboard (não sei dizer ao certo). Mas usando a v2 pra cima, vc não deve mais ter esse problema =)

---

Sobre a versão de build, faltou passar a extensão correta (scss) no `exclude` do _styles_ e no `test` do _critical rendering path_ =)

**Comment by Roger-Melo** [comment]
Oi, professor! Deu certo a versão de build =)

---

Atualizei o webpack para a versão `"webpack": "^2.2.1"`. Ao executar o `npm start`, não consigo visualizar o erro, porque a barra de rolagem da parte de 'log' do dashboard não funciona:

![image](https://user-images.githubusercontent.com/29297788/51423399-af3c5a80-1ba6-11e9-9e7f-306b32979ccf.png)

Então omiti o `webpack-dashboard -- ` do script `start`, no package.json e executei `npm start` novamente, pra ver se ficava mais fácil debugar e apareceu uma mensagem dizendo que eu devo incluir 
'-loader' nos nomes dos loaders. Só que essa mensagem continua sendo exibida mesmo após incluir os 
'-loader':

![image](https://user-images.githubusercontent.com/29297788/51423437-37226480-1ba7-11e9-9b99-0f73eef5062b.png)

Vou deixar os códigos abaixo, mas se for necessário, os arquivos estão [aqui](https://github.com/Roger-Melo/react-ninja-review/tree/master/examples/m02/github-app)

```javascript
// webpack.config

'use strict';

const { join } = require('path');
const webpack = require('webpack');
const htmlPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const DashboardPlugin = require('webpack-dashboard/plugin')

module.exports = {
  devtool: 'source-map',
  
  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    join(__dirname, 'src', 'index')
  ],
  
  output: {
    path: join(__dirname, 'dist'),
    filename: '[name]-[hash].js',
    publicPath: ''
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new DashboardPlugin(),
    new ExtractTextPlugin({
      filename: '[name]-[hash].css'
    }),

    new htmlPlugin({
      title: 'GitHub App',
      template: join(__dirname, 'src', 'html', 'template-dev.html')
    })
  ],
  
  module: {
    rules: [{
      test: /\.js$/,
      enforce: 'pre',
      exclude: /node_modules/,
      include: join(__dirname, 'src'),
      use: 'standard-loader'
    }, {
      test: /\.js$/,
      exclude: /node_modules/,
      include: join(__dirname, 'src'),
      use: 'babel-loader'
    }, {
      test: /\.scss$/,
      exclude: /node_modules/,
      include: join(__dirname, 'src'),
      use: ['style-loader', 'css?modules-loader', 'sass-loader']
    }]
  },

  resolve: {
    alias: {
      src: join(__dirname, 'src'),
      components: join(__dirname, 'src', 'components')
    }
  }
};
```

```javascript
// webpack.prod.config

'use strict';

const { join } = require('path');
const webpack = require('webpack');

const HtmlPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const criticalRenderingPath = new ExtractTextPlugin({filename: 'critical-rendering-path.css'})
const styles = new ExtractTextPlugin({filename: '[name]-[hash].css'})

module.exports = {
  entry: join(__dirname, 'src', 'index'),

  output: {
    path: join(__dirname, 'dist'),
    filename: '[name]-[hash].js'
  },

  plugins: [
    criticalRenderingPath,
    styles,

    new ExtractTextPlugin({
      filename: '[name]-[hash].css'
    }),

    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': '"production"'
      }
    }),

    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true
    }),

    new webpack.optimize.OccurrenceOrderPlugin(),

    new HtmlPlugin({
      title: 'GitHub App',
      inject: false,
      template: join(__dirname, 'src', 'html', 'template.html')
    })
  ],
  
  resolve: {
    alias: {
      src: join(__dirname, 'src'),
      components: join(__dirname, 'src', 'components')
    }
  },

  module: {
    rules: [{
      test: /\.js$/,
      enforce: 'pre',
      exclude: /node_modules/,
      include: join(__dirname, 'src'),
      use: 'standard-loader'
    }, {
      test: /\.js$/,
      exclude: /node_modules/,
      include: join(__dirname, 'src'),
      use: 'babel-loader'
    }, {
      test: /\.scss$/,
      exclude: /node_modules|(search|style)\.scss/,
      include: join(__dirname, 'src'),
      use: styles.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'sass-loader']
      })
    }, {
      test: /(search|style)\.scss$/,
      exclude: /node_modules/,
      include: join(__dirname, 'src'),
      use: criticalRenderingPath.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'sass-loader']
      })
    }]
  }
};
```

```javascript
// package.json

{
  "scripts": {
    "start": "node server.js",
    "build": "cross-env NODE_ENV=production webpack --progress --config webpack.prod.config -p",
    "storybook": "start-storybook -p 6006 -c storybook",
    "build-storybook": "build-storybook -c storybook"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "cross-env": "^5.2.0",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^2.1.2",
    "html-webpack-plugin": "^3.2.0",
    "node-sass": "^4.11.0",
    "react-hot-loader": "^3.0.0-beta.2",
    "sass-loader": "^7.1.0",
    "standard": "^11.0.1",
    "standard-loader": "^4.0.0",
    "style-loader": "^0.23.1",
    "webpack": "^2.2.1",
    "webpack-dashboard": "^2.0.0",
    "webpack-dev-server": "^1.16.5",
    "webpack-validator": "^3.0.1"
  },
  "dependencies": {
    "@fdaciuk/ajax": "^3.0.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "standard": {
    "globals": [
      "alert"
    ]
  }
}
```

@fdaciuk

**Comment by Roger-Melo** [comment]
Valeus, professor! =)

> No módulo 2 eu mostrei uma dependência para analisar os seus bundles: webpack-bundle-analizer
https://github.com/fdaciuk/workflow-reactjs/blob/master/webpack/prod.config.js#L9

Testei aqui e não achei nada duplicado. 

Testei também o [inspectpack](https://github.com/FormidableLabs/inspectpack), (engine que roda por baixo dos panos do webpack-dashboard). Novamente, sem arquivos duplicados.  

![image](https://user-images.githubusercontent.com/29297788/51447653-664fe780-1d07-11e9-83de-5c16af8824b0.png)

Loucura, né? 

@fdaciuk

**Comment by fdaciuk** [comment]
@Roger-Melo! Então, não vou dizer pra você não que não pode ser isso haha :D 
Mas se não tem, não tem xD
Depois só confere a versão de produção, se não está gerando códigos duplicados. Se não estiver, então tá tudo certo, é só um falso positivo =)

**Comment by Roger-Melo** [comment]
em breve saio dessa vida 

![linux](https://user-images.githubusercontent.com/29297788/51501063-922aa600-1db7-11e9-933c-d2b4e040f450.gif)

(eu do futuro usando linux)
@fdaciuk
