### ISSUE TITLE
M1#A49 Equivoco na explicação Rest parameters 

### ISSUE THREAD

**Issue by iagolaguna** [da2k/curso-reactjs-ninja#253]
Olá Fernando primeiramente eu queria te parabenizar por esse excelente curso e sua ótima didática, queria acrescentar também que nessa aula faltou um pequeno detalhe sobre o `rest paramaters`.

Essa função abaixo não funciona por que o `rest params` tem que ser o último argumento passado para a função
```
function(...params. callback) {
// code here
}
```
O correto seria :
```
function(callback, ...params) {
// code here
}
```
Abraços, ;)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @iagolaguna! Muito obrigado por reportar! Foi uma FALHA BIZARRA mesmo, desculpe!
Vou criar uma aula do futuro pra corrigir essa gafe =)

**Comment by fdaciuk** [comment]
Pronto! Removi a parte onde eu falava do rest params, pois mais pra frente eu vou mostrar isso de forma correta =)

Obrigado mais uma vez :D
