### ISSUE TITLE
Webpack gerando arquivos pesados no ambiente de desenvolvimento

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#254]
Professor, estou no M2#A47. No GitHub App, ao executar o `npm start`, é exibido no terminal que os arquivos `.js` estão com mais de 1mb. Achei estranho porque [não há tanto código js na aplicação](https://github.com/Roger-Melo/codepen/tree/master/06-github-app). Devo me preocupar? 

```
main-fdc167cf43f6fa1d09d5.js    1.34 MB       0  [emitted]  [big]  main
main-fdc167cf43f6fa1d09d5.js.map    1.62 MB       0  [emitted]    main
```

Em compensação, o arquivo JS gerado no build está com um tamanho bacana (153 kB).  

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Não precisa se preocupar não. Para dev, o webpack adiciona um monte de código pra funcionar o hot reload, entre outras coisas, que não fazem parte diretamente da aplicação.

Se preocupe apenas se em produção estiver com esse tamanho. Aí é hora de começar a pensar em carregar alguns módulos dinamicamente =)

**Comment by Roger-Melo** [comment]
feshow professor!
