### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by EduardoMOliveira** [da2k/curso-reactjs-ninja#255]
Boa noite estou seguindo o curso de React e ao configurar o Lint está apresentando esse erro, mesmo forçando outro tipo de erro ele para neste ponto e não estou encontrando o problema.

````
        WARNING in ./src/index.js
<text>:11:13: Parsing error: Unexpected token /

WARNING in ./src/app.js
<text>:8:24: Parsing error: Unexpected token /

````

Segue o meu código abaixo:

```
     const renderApp = (NextApp) => {
	render(
		<AppContainer>
			<NextApp />
		</AppContainer>,
		document.querySelector('[data-js="app"]')
	)
    }
```

``` 
    const App = React.createClass({
	
	render: function() {
		
		return <h1>Aplicação</h1>
	}
});

````

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @EduardoMOliveira! Suba seu projeto aqui no GitHub, por favor, e passe o link que eu dou uma olhada no que pode estar acontecendo, ok? =)
