### ISSUE TITLE
Operator Spread

### ISSUE THREAD

**Issue by renanlbl** [da2k/curso-reactjs-ninja#257]
Escreva aqui sua dúvida
No módulo 1, aula 50 você falou sobre spread, o conceito ficou claro, mas o exemplo eu não consegui entender..

No render, ao invés de utilizar os
```js
           userinfo={this.state.userinfo}
            repos={this.state.repos}
            starred={this.state.starred}
            isFetching={this.state.isFetching}
```
passamos a utilizar o `{...this.state}`

Mas nesse momento, no constructor o this.state está assim:
```js
 this.state = {
            userinfo:  null,
            repos: [],
            starred: [],
            isFetching: false
        }
```

Então por que quando utilizamos o operador spread o objeto não vai nessa forma que está no constructor? Digo, porque ele não vai passa o userinfo: null e sim userinfo: this.state.userinfo

Render atual:
```jsx
render() {
        return <AppContent 
            {...this.state}            
            handleSearch={ this.handleSearch }
            getRepos={this.getRepos('repos')}
            getStarred={this.getRepos('starred')}
            />
    }
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanlbl! =)

O objeto é passado assim como vc falou mesmo! Talvez você só tenha confundido o seguinte:
o que é passado como valor para a propriedade, é de fato o valor dela.

No caso, se `userinfo` tiver valor `null`, esse valor vai ser passado.

Mas o valor dessa propriedade está em `this.state.userinfo`, correto? Por isso eu mostrei dessa forma =)

Mas no final das contas, é exatamente o que você entendeu: o valor de `this.state.userinfo` é que vai ser passado para frente =)

**Comment by renanlbl** [comment]
@fdaciuk Showw! obrigadao

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :D
