### ISSUE TITLE
[MRW#10] - Testando o ESLint e obtendo mensagens de erros no npm

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#258]
Oi, professor! 

O StandardJS se tornou meu linter favorito, mas por [questões mercadológicas](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2018-results#js-linters), eu gostaria de testar o ESLint. Só que estou com problemas ao executá-lo em um projeto. 

Ao executar o npm script `"lint": "eslint src\\**.js --fix",` são exibidos os seguintes erros: 

![npm-error](https://user-images.githubusercontent.com/29297788/51776618-2d39bd80-20e1-11e9-86a1-021c9fc30cb9.jpg)

Você sabe como posso resolver essas mensagens do npm? Estou utilizando o ruimdows no momento. 

### Update:

O que tentei fazer: 

- executei `npm cache clean --force`
- deletei a node_modules
- reinstalei as dependências com o `npm install`
- instalei o python
- reinstalei o Node

e os erros do npm continuam aparecendo...

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Antes de falarmos sobre o problema, deixa só eu esclarecer algo: o _standardjs_é só um _set_ de configurações que usa o eslint por baixo dos panos =)

Sobre o seu erro, pode ter dois motivos: a contra-barra no _path_, e a falta de aspas duplas, por estar no windows.

Se for por causa da contra-barra, ainda que esteja usando windows, tente usar a barra no padrão Unix mesmo: `eslint --fix src/**`.

Senão, pode ser a falta de aspas duplas no _path_. Quando usado "glob pattern" + windows, é necessário usar aspas no _path_, (conforme documentação)[https://eslint.org/docs/user-guide/command-line-interface]. Então o comando final no seu `package.json` ficaria: 

```
"lint": "eslint --fix \"src/**\""
```

Acredito que seja isso =)

Me avise se deu certo ou não =)

**Comment by Roger-Melo** [comment]
> Oi @Roger-Melo! Antes de falarmos sobre o problema, deixa só eu esclarecer algo: o _standardjs_é só um set de configurações que usa o eslint por baixo dos panos =)

Agoora fez sentido hahah =)

>Se for por causa da contra-barra, ainda que esteja usando windows, tente usar a barra no padrão Unix mesmo: eslint --fix src/**.

Fiz a alteração da barra. Quando deixo alguns statements com semicolons e executo o `npm run lint`, os semicolons são inseridos e nenhum aviso ou erro é exibido no terminal.  

> "eslint --fix \"src/**\""

Com essa alteração também funcionou sem erros.  

Os erros do NPM agora só são exibidos no terminal se o parâmetro `--fix` for retirado, tanto com aspas no path quanto sem. Li que esse parâmetro não corrige tudo, mas melhor deixar do que ficar recebendo erros, né? 

Descobri que os mesmos erros do npm (no mesmo projeto) são exibidos ao executar o Jest :man_facepalming:

@fdaciuk

**Comment by fdaciuk** [comment]
Normalmente esse erro do NPM é genérico: quando algum comando executado via CLI do `npm` termina com erro, ele mostra esse monte de linhas com `npm ERR!`. 

Em praticamente 99% das vezes dá pra ignorar, e olhar mais acima, onde o verdadeiro erro aconteceu: nesse último exemplo seu, foi um teste que quebrou.

Sobre o linter, a ideia não é deixar o `--fix` fixo nesse comando. A ideia do `--fix` é que você consiga corrigir erros de _code styling_ automaticamente, normalmente quando você adiciona o linter em um projeto já existente, que ainda não tinha regras de lint a serem seguidas, ou quando você está trabalhando em algum projeto sem rodar o linter por um tempo, e quando vai rodar tem vários erros que precisam ser corrigidos.

A ideia é deixar o linter rodando enquanto você escreve código, para que ele te avise dos erros que vão surgindo, e assim você possa ir corrigindo. Se deixar o linter rodando com o `--fix` enquanto você coda, pode acontecer de corromper algum arquivo em algum momento, já que ele precisa escrever no arquivo ao mesmo tempo em que você está com o arquivo aberto, editando-o.

Não que vá acontecer, mas recomendo não usar dessa forma: deixe o `--fix` para esses momentos que comentei acima, e tudo deve funcionar sem problemas :)

**Comment by Roger-Melo** [comment]
então fechou, professor! Muito obrigado =)

P.s: uma pena o ESLint (padrão) ter mais mercado que o Standard. Não usar `;` é libertador :grinning:

@fdaciuk

**Comment by fdaciuk** [comment]
>  uma pena o ESLint (padrão) ter mais mercado que o Standard.
De onde você pegou essa informação? Lint normalmente é definido dentro de um time.

Se você trabalha sozinho, não faz diferença usar ou não `;`. Se o linter estiver bem configurado, um `--fix` resolve o problema =)

**Comment by Roger-Melo** [comment]
> De onde você pegou essa informação? Lint normalmente é definido dentro de um time.

Vi [nessa pesquisa](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2018-results#js-linters). 

> Se você trabalha sozinho, não faz diferença usar ou não ;. Se o linter estiver bem configurado, um --fix resolve o problema =)

É verdade. Em meus projetos pessoais não utilizo `;`. Mas, como sou aspirante à Front-end Developer Júnior, a adoção do ESLinter é uma (pequena) preocupação que tenho =)

**Comment by fdaciuk** [comment]
> Vi nessa pesquisa. O Standard está em penúltimo lugar.

Entendi, mas sinceramente, não vejo sentido: o Standard.js poderia ser comparado ao Prettier, por exemplo, mas não no meio de outras ferramentas de Lint, já que ele usa o Eslint por baixo dos panos =)

De qualquer forma, lint é questão de gosto. Tenha o seu bem configurado que tudo vai dar certo =)

Só pra explicar um pouco do motivo de eu ter escolhido o standard.js: ele já tem uma configuração pronta, então é basicamente instalar e usar. Quando você configura algum linter na mão, pode esquecer alguma regra, ou colocar regras que se podem conflitar no seu código, ou ainda usar uma regra achando que ela é válida, mas esquecer algum caso de uso que aquela regra não cabe. Aí você precisa ficar usando comentários no código pra ignorar, pois tem uma exceção à sua regra.

O Standard é muito bem formado e testado. Nunca precisei comentar linha por conta de alguma exceção, e ele sempre ajudou a pegar qualquer erro que eu pudesse ter no meu código, por isso eu gosto tanto de usar ele =)

**Comment by Roger-Melo** [comment]
Saquei. O fato de não ter que se preocupar com configurações é o grande diferencial dele para mim. 

> Entendi, mas sinceramente, não vejo sentido: o Standard.js poderia ser comparado ao Prettier, por exemplo, mas não no meio de outras ferramentas de Lint, já que ele usa o Eslint por baixo dos panos =)

Algumas pesquisas realmente não categorizam bem certas ferramentas =)

Obrigado, professor!

**Comment by fdaciuk** [comment]
> O fato de não ter que se preocupar com configurações é o grande diferencial dele para mim.
Exatamente!

=)
