### ISSUE TITLE
Duvidas sobre o componente Search, do GitHub App

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#259]
Olá, professor! 

Estou com problemas no componente `Search` do GitHub App. Incluí um botão ao lado do `input`:

![githubapp](https://user-images.githubusercontent.com/29297788/51795072-5fbce680-21c5-11e9-872b-c6cea4a3b58e.gif)

Atualmente, o único componente statefull da [aplicação](https://github.com/Roger-Melo/codepen/tree/master/06-github-app) é o `App`. Devido ao botão, tentei fazer o seguinte: 

- Envolvi o input e o botão em um `<form>`
- Converti o `Search` para class
- Removi o evento `onKeyUp` do input
- Adicionei o evento `onSubmit` no `<form>`

Só que se o método `onSubmit` modificaria o state `userinfo`, que está no `App` mas é utilizado em outros lugares da aplicação :dizzy_face: Vc pode me dar uma luz?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! É exatamente esse o motivo do `app.js` ser o único componente stateful da aplicação. O fluxo de dados no React é unidirecional: vem sempre de cima pra baixo. Quando você tem estado compartilhado, você deve então subir na árvore de componentes a manipulação desse estado, até que abaixo dele fiquem todos os componentes que vão apenas precisar usar esse state.

Se você fizer da forma que está pensando, primeiro que você começa a espalhar estado pela aplicação. Pense no caso de acontecer algum bug. Se você tiver vários componentes stateful, manipulando estados, vai ficar mais complicado você saber qual deles está causando o problema.

Segundo que, com o estado em nível mais "abaixo", não tem como você passar esse estado pra cima.

Agora, se você centralizar o estado, você sabe que, se acontecer algum bug, o problema vai estar onde o estado está sendo manipulado, já que todos os componentes abaixo são stateless: só recebem o estado e renderizam, mas não o manipulam =)

Sacou a ideia?

**Comment by Roger-Melo** [comment]
Entendi sim =) 

Na verdade o que tá pegando é essa [função](https://github.com/Roger-Melo/codepen/blob/master/06-github-app/src/app.js#L30). Eu gostaria de isolar a chamada ajax que está dentro dela em um método, para utilizá-la tanto ao pressionar `enter` no input quanto ao pressionar o botão. Só que não estou conseguindo pegar o value do input no método `handleSubmit` que criei (também no app.js)

@fdaciuk

**Comment by Roger-Melo** [comment]
Agoooora sim! :smiley:

> A única alteração que você vai ter que fazer é adicionar um id no campo do formulário, e pegar esse elemento dentro do método handleSearch com e.target.ID_DO_INPUT, já que e.target vai apontar para o form =)

Minha cabeça estava dando voltas tentando achar uma maneira de acessar o `value` do input, hahah. Esclarecido. Obrigado, professor! =)

**Comment by fdaciuk** [comment]
haha! Show! Às vezes a gente precisa "voltar" um pouco, e pensar mais simples =)
Qualquer coisa, avisa ae =)
