### ISSUE TITLE
Dúvidas gerais

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#26]
Fala @fdaciuk, beleza? Lá vai as perguntas rs

1 - Meu carma, autenticação. Não cheguei a colocar a mão na massa em relação a isso ainda, só pesquisei, acabei caindo [aqui](https://github.com/ReactTraining/react-router/tree/master/examples/auth-flow). É mais ou menos esse fluxo que preciso seguir (apenas de não estar tão claro pra mim esse auth-flow), tem algum lugar que posso me basear?

2 - Vamos pensar em um "editar usuário", que usa o mesmo arquivo de formulário "criar usuário" por exemplo, isso pode ser uma boa prática ou má prática? Ainda não consigo desenhar na minha cabeça o fluxo de CRUD em React editando/deletando. Pode me dar uns toques em relação a formulários nesse sentido? Trabalho com o `<form>` normal ? Pegando os dados com JS Puro para enviar pra API.

Valeu por toda força!

**Comment by gabrielferreiraa** [comment]
Aproveitando a issue aberta.

Fui consumir uma API aqui pela primeira vez com essa estrutura apresentada no curso e está caindo na exceção de Access-Control-Allow-Origin. 

Dei uma pesquisada, segundo o que eu li é alguma coisa que preciso colocar no Webpack? Sabe me dizer?

Valeu 🤗

**Comment by fdaciuk** [comment]
Muitas perguntas! haha! 

Vamos lá @gabrielferreiraa =)

Autenticação é um assunto bastante extenso, e tem várias formas de se fazer, mas nós vamos chegar lá no curso, fica traquilo =)

Sobre a parte de edição / novo usuário, sim, você pode usar o mesmo formulário. A única coisa que você precisa fazer é receber os dados nesse componente para preencher os campos. Se os campos estiverem em branco, então é um novo cadastro, senão é uma edição =)

Quem deve tratar se é um novo cadastro ou uma edição deveria ser o backend. Ao enviar as informações do usuário, no backend é verificado se o usuário já existe e só altera os dados dele, ou então cria um novo. Claro que no meio desse caminho tem várias validações que precisam ser feitas pra garantir que o cadastro / edição pode de fato ser feito, mas em resumo é isso.

Para cadastrar você pode usar formulário normalmente, como você faz com HTML puro. A ideia do React não é ser uma nova tecnologia, mas sim facilitar aqui que é mais complicado de se fazer: trabalhar com DOM.

Ao trabalhar com React, você deve imaginar como você faria se fosse com HTML e JS puros, saca? Mas deixando pro React o trabalho sujo de tratamento do DOM. Assim você se preocupa **só com os dados**. =)

Esse é o motivo do módulo `#02` ser tão extenso: a ideia é tratar de todos esses detalhes (ou o máximo deles possível) para que fique claro que trabalhar com React não é para ter um _react way_ de se fazer as coisas, mas sim usá-lo para melhorar o que já estávamos acostumados a fazer sem ele =)

A questão do _Access-Control-Allow-Origin_ é o que chamamos de **CORS**: _Cross Origin Resource Sharing_.

A ideia dele é restringir alguns recursos que podem ser compartilhados em páginas web. Normalmente o servidor que recebe requests HTTP tem isso configurado para impedir que qualquer site envie ou receba informações dele.

Para entender e resolver o problema, é preciso saber se o servidor que você está tentando consultar pede alguma configuração específica quanto a isso, ou se só falta mesmo liberar **no servidor** para que ele permita que você faça requests de uma origem diferente de onde ele está hospedado.

Isso acontece muito quando você tem a sua aplicação rodando em uma porta, e o servidor está em outra.

Acho que é isso. Ficou claro?

**Comment by gabrielferreiraa** [comment]
Você muito claro e didático como sempre, valeu! Abç

**Comment by fdaciuk** [comment]
Qualquer dúvida, grita ae =)
