### ISSUE TITLE
[M2#A06] - Por que utilizar o Chai

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#260]
Olá, professor! 

Estava aqui dando uma olhada na documentação do Jest, ela me parece bem completa. Daí me vieram as dúvidas: por que utilizar o chai? Sintaxe amigável / BDD interface? É possível escrever testes utilizando apenas os métodos de asserção do Jest?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Usar o Chai é só questão de gosto mesmo. Só com o Jest você faz tudo o que faria com o Chai, sem muitas dificuldades =)

Eu uso o Chai porque gosto da forma que ele funciona, só isso =)

**Comment by Roger-Melo** [comment]
Percebi que alguns métodos de asserção do Jest são mais verbosos.  

Para verificar se um item [não está incluso](https://jestjs.io/docs/en/expect#expectnotarraycontainingarray) em um array, é preciso escrever: 

```javascript
  it('[1, 2, 3] should not include item 4', function () {
    expect([1, 2, 3]).toEqual(
      expect.not.arrayContaining([4])
    )
  })
```

Vou utilizar o Chai sim kkk

@fdaciuk

**Comment by fdaciuk** [comment]
Pois é.. esse é um dos motivos de eu gostar do Chai haha :D 
Qualquer coisa, só avisar :D
