### ISSUE TITLE
Manipulando CSS através do estado da aplicação

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#262]
![stateclasses](https://user-images.githubusercontent.com/29297788/52017244-f0e5d300-24cd-11e9-8d14-5ae98af07673.gif)

Olá, professor!

No GitHub App, eu gostaria que quando as informações do usuário pesquisado aparecerem, os repos já fossem exibidos por default. Para representar isso visualmente, consegui fazer com que o botão 'public repos' já aparecesse 'selecionado' (como mostrado acima), mas queria saber se há uma maneira de melhorar o código.

Até coloquei o nome do commit como 'add buttons states with gambs' kkk. O repo está [aqui](https://github.com/Roger-Melo/codepen/tree/master/06-github-app/src), caso possa dar uma olhada.

Um breve resumo do que fiz: 

- Invoquei `this.getRepos('repos')()` na função de callback do `setState` do método `handleSubmit`
- Adicionei o state `buttonThatShoudBeTransparent`
- Adicionei a classe que deixa o botão transparente, caso `buttonThatShoudBeTransparent === 'nomeDoBotão'` seja `true`

@fdaciuk

**Comment by fdaciuk** [comment]
Legal @Roger-Melo! Acho que assim funciona, mas pode ficar mais semântico se você usar um nome que seja referente à informação de fato, ao invés de `buttonThatShouldBeTransparent`. 

Digo isso porque, imagine você precisando usar essa informação em outro lugar: você vai duplicar a informação no state por causa do nome dela? =)

Você poderia nomear a infomação como `emptyRepo`, `unloadedRepo`, ou algo do tipo.

Sacou mais ou menos a ideia?

**Comment by Roger-Melo** [comment]
Saquei d+. Obrigado mestre!
