### ISSUE TITLE
MRW#07 

### ISSUE THREAD

**Issue by walterjaworski** [da2k/curso-reactjs-ninja#263]
Fala carinha, beleza?
Seguinte, conforme o vídeo, aqui não deu muito certo a parte do source map, o que será que fiz de errado?

Estou anexando um print da tela.
![screen shot 2019-01-31 at 5 20 30 pm 2](https://user-images.githubusercontent.com/3688982/52079508-dc144880-257c-11e9-9a85-0b87aba1025f.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae cara! Compartilha comigo seu código em um repo aqui no GitHub, por favor? Assim eu consigo ver o que pode ter dado errado =)

Acredito que pode ser alguma diferença de versão de alguma dependência, mas é bom ver o código primeiro pra ter certeza :D

**Comment by walterjaworski** [comment]
Segue: https://github.com/walterjaworski/duvidas-react

**Comment by fdaciuk** [comment]
Oi @walterjaworski! Desculpe, olhei novamente os prints que você mandou, e entendi o problema =)
Esse arquivo que você está inspecionando é, de fato, o bundle gerado. Para ver o arquivo gerado pelo source maps, do jeito que você escreveu, ali nessa lista de arquivos mesmo deve ter uma entrada `webpack://`. Nessa entrada vai ter a estrutura que você está procurando =)

Eu cheguei a mostrar nessa aula, mas não sei se você chegou nesse ponto :D 

Dá uma olhada no print abaixo como deve aparecer pra você:

![screenshot from 2019-02-02 14-40-20](https://user-images.githubusercontent.com/487669/52166765-ad22e180-26f8-11e9-8f7c-70be83dd63b1.png)

**Comment by walterjaworski** [comment]
@fdaciuk  engraçado que não aparece a opção webpack ali na lista, mas vou retomar o curso e verificar novamente o que pode ter faltado.
Obrigado!

**Comment by fdaciuk** [comment]
Que estranho! Tenta fazer o seguinte: force um erro, que no console ele deve apontar para o caminho do arquivo gerado pelo source maps =)

**Comment by fdaciuk** [comment]
Show! Relaxa =)
Qualquer coisa, só avisar :D

**Comment by jghagemann** [comment]
Sei que não é bacana comentar em issues fechados, mas eu estava tendo o mesmo problema. Confiram o seguinte:
no arquivo index.html o src deve ser:

`<script src="./dist/bundle.js"></script>`

e não

`<script src="./static/bundle.js"></script>`


Tem uma hora que o Fernando troca do static pro dist, troquei isso e funcionou

**Comment by fdaciuk** [comment]
Oi @jghagemann! Sem crise! Se tiver a mesma dúvida, e não tiver conseguido resolver, pode comentar sim :)
