### ISSUE TITLE
M1#A43 - Dúvida

### ISSUE THREAD

**Issue by reglachek** [da2k/curso-reactjs-ninja#265]
Da forma como você retorna o resultado da API me parece que invés de retorna de fato um array você está na verdade evoluindo o estado da aplicação de um array para um objeto, pois devido eu ter feito o desafio proposto, de primeira, na minha cabeça fez mais sentido assim: 

```js
handleAction (type) {
    return () => {
      const username = this.state.userinfo.login
      ajax().get(this.getGitHubApiUrl(username, type))
      .then(result => result.map(repo => (
        this.setState({ repos: this.state.repos.push(repo) })
      )))
    }
  }
```
Porem fazendo dessa forma eu recebi esses dois erros(Se conseguir explicar o motivo desse erro ficarei grato):

```
Warning: Failed prop type: Invalid prop `repos` of type `number` supplied to `AppContent`, expected `array`.
    in AppContent (created by App)
    in App
    in AppContainer

Uncaught TypeError: _this3.state.repos.push is not a function
    at app.js:55
    at Array.map (<anonymous>)
    at Object.then (app.js:54)
    at XMLHttpRequest.n (ajax.min.js:9)
```

No caso desse ultimo erro a linha 54 é onde eu estou invocando o método push.
Então como fiquei na dúvida, consegui fazer de uma forma diferente, remapeando o array que é retornado pela API de forma a conter apenas os dados que nos interessavam, então ficou assim: 

```js
handleAction (type) {
    return () => {
      const username = this.state.userinfo.login
      
      ajax().get(this.getGitHubApiUrl(username, type))
      .then(result => {
        let newRepos = result.map(repo => ({
          name: repo.name,
          link: repo.svn_url
        }))

        this.setState({ [type]: newRepos })
      })
    }
  }
```
Então minha dúvida como aprendiz é a seguinte: A forma como eu consegui fazer está certa? A forma como você faz no vídeo realmente está evoluindo a aplicação de um array para um objeto, ou estou enganado ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @reglachek! Vamos lá:

É importante salientar que, sempre que você inicia uma variável no estado com um tipo de dado, essa variável precisa manter o mesmo tipo de dado SEMPRE! Então nós nunca iremos iniciar um variável como array, e depois mudar o tipo de dado para objeto por exemplo, ok?

E isso porque o nosso método `render` vai sempre estar preparado para o tipo de dado que nós usamos quando setamos o estado inicial.

No caso das variáveis `repos` e `starred`, você pode verificar que elas foram iniciadas como um array, dentro de `this.state` =)

Quando eu mostrei como atualizar o valor desses arrays, foi exatamente da forma que você que você fez no seu segundo exemplo, com a diferença que eu atribuí o resultado do método `map` direto para o valor em `[type]`, no objeto do estado =)

Não precisa criar uma variável antes, como você fez =)

Sobre o seu primeiro exemplo, onde é exibido o erro, o seu pensamento foi certo, mas a implementação errada.

Você nunca deve usar algum método que modifique uma variável de estado (que é o caso do méodo `push`). Sempre que precisar gerar um novo valor, é preciso **sempre** gerar um novo objeto.

O método `push` modifica um array, enquanto o método `map` **cria sempre um novo array**, com os valores passado no retorno do método.

Por isso usamos `map`, e não o `push`. Um outro problema de usar mutabilidade, como você fez com `push`, é que o método `push` não retorna o array novamente. Ele retorna o `length` do array. Por isso o erro exibido foi:

```
Warning: Failed prop type: Invalid prop `repos` of type `number` supplied to `AppContent`, expected `array`.
```

Veja que o erro diz que a propriedade `repos` é do tipo `number`, mas era esperado um `array`. _Por que ela é um `number`, se você iniciou ela como um array?_

Porque quando você usou o `push` pela primeira vez, passando o resultado do `push` para `repos`, o `push` passou o `length` do array, ao invés do próprio array, sacou?

E logo abaixo, você teve o próximo erro:

```
Uncaught TypeError: _this3.state.repos.push is not a function
```

Veja que o erro diz que o método `push` não existe em `this.state.repos`. Porque agora `repos` se transformou em um número, ele não é mais um array =)

Métodos que modificam arrays e objetos devem sempre ser evitados ao se trabalhar com React.

Você até pode usar, em casos específicos, mas recomendo evitá-los, e usar métodos similares, que sempre retornem novos objetos, para não ter esse tipo de problema que você teve, ok? =)

Se você ainda não entende o que é um objeto mutável, e como trabalhar com imutabilidade em JavaScript, vou deixar dois links pra você estudar sobre esses assuntos:

[Aqui](https://blog.da2k.com.br/2017/01/25/objetos-referencias-de-valores-em-javascript/) tem um post que escrevi sobre referências de objetos, e [aqui](https://www.youtube.com/watch?v=eKka6vj1uig) você pode ver uma palestra minha, onde eu falei sobre imutabilidade.

Recomendo também ver esses outros dois meetups que eu fiz recentemente (links [aqui](https://www.youtube.com/watch?v=GDZswgpSYQg) e [aqui](https://www.youtube.com/watch?v=Dy1VDtPxCp0)), falando sobre os métodos que iteram arrays, e explicando o uso correto de cada um deles, pois no primeiro exemplo você usou o `map` pra iterar um array, mas não retornou valor algum. Existem formas corretas de fazer isso, e esses dois vídeos vão te ajudar a entender cada uma delas =)

Imutabilidade, referências de objetos e métodos de array são assuntos muito importantes, que você obrigatoriamente precisa entender pra conseguir trabalhar com React sem muitos problemas, ok? =)

Espero que tenha ficado claro. Se algo não ficou, só avisar =)

**Comment by reglachek** [comment]
Excelente explicação @fdaciuk , obrigado pelas dicas sobre o métodos que modificam arrays e objetos, darei uma olhada nos links que me enviou e gostaria de aproveitar essa issue para elogiar o seu trabalho, pois ele tem uma grande admiração por mim. Continue assim <3

**Comment by fdaciuk** [comment]
Muito obrigado Matheus! Fico muito feliz em saber que o conteúdo tem te ajudado =)
Conte comigo para o que precisar :D
