### ISSUE TITLE
[MRW#01] - Dúvida acerca das configurações

### ISSUE THREAD

**Issue by bobecampos** [da2k/curso-reactjs-ninja#266]
Olá.

Primeiro, peço desculpas pelas perguntas que vou fazer aqui... eu sou bem leigo nessa área de Desenvolvimento. Tenho estudado bastante código, linguagens, mas quando chega nessa parte de instalação de ferramentas e plugins, meu cérebro frita, minha cabeça explode e eu acabo achando que eu sou o sujeito mais incompetente do mundo. Então acredito que minhas dúvidas possam ser bem amadoras.

Nessa aula, você falou de configurações do Vim... pelo que entendi, o Vim é um editor de textos. Eu uso o VS Code. Uma das minhas dúvidas é... para fazer este curso, eu preciso usar o Vim? Terei problemas se continuar usando o editor que eu já estou acostumado?

Travei por diversas vezes tentando seguir o passo a passo. Talvez, por falta de conhecimento em Git também. Não tenho conseguido seguir. 

Queria saber se existe a possibilidade de haver alguma "aula do futuro" mais voltada para isso, pra ajudar quem é mais leigo nessa etapa de instalação de ferramentas ou plugins. Porque eu tenho lidado bem com código, tenho conseguido assimilar bem a respeito, mas essas etapas de configurações quebram minhas pernas. Não sei se sou o único.

É isso, obrigado pelo seu tempo.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @bobecampos! Tudo bem? =)

Sobre o editor de textos, pode usar o que você se sentir mais confortável. No curso eu estarei usando o Vim, mas não vai fazer diferença o editor que você usar, ok? =)

Sobre a parte de instalação e configurações: consegue me dizer, especificamente, onde você travou? Assim eu consigo te ajudar da melhor forma =)

E não hesite em perguntar! Sempre que tiver dúvidas, ou não conseguir seguir com algo, saiba que estou aqui pra te ajudar, ok? =)

**Comment by bobecampos** [comment]
@fdaciuk 
Bom, primeiro, eu te agradeço por ser uma pessoa que dá suporte ativo pra quem usa seu curso. Isso é um diferencial enorme.

(também passei as últimas horas batendo cabeça, e acho que estou conseguindo entender algumas coisas)

Se o editor não fará diferença, eu preciso instalar o Vundle para instalação de plugins do Vim? Ou eu posso pular esta etapa?

Sobre o Terminal. Eu tenho usado o Cmder (inclusive, conheci com a sua indicação em uma das primeiras aulas), mas queria algo mais colorido pra facilitar minha vida. Então, não teria problema em abandonar e passar a usar o Terminator. Só que já comecei não conseguindo encontrar o download do Terminator para Windows. No https://gnometerminator.blogspot.com/p/introduction.html não consta uma versão para Windows. Ele é incompatível?

**Comment by fdaciuk** [comment]
Legal! :D 
O Vundle é para instalação de plugins específicos para o Vim, então pode ignorar =)

Para terminal, tem uma recomendação que acho que vai ser melhor que o Cmder, que é o [Hyper](https://hyper.is).

Ele deve funcionar corretamente em qualquer sistema operacional, inclusive no windows =)

**Comment by fdaciuk** [comment]
Da parte de software que você precisa instalar na sua máquina, o único realmente obrigatório é o Node.js e o NPM (ao instalar o Node.js, ele já vem com o NPM).

Editor de textos, terminal e navegador, você pode usar o que quiser :)

O Node.js é importante pois é à partir dele que vamos instalar as dependências via terminal que vamos precisamos usar durante o curso =)

**Comment by bobecampos** [comment]
Legal! Baixei e instalei o Hyper. Gostaria de saber por que você me indicou ele. 

Com o Hyper, eu preciso seguir as configurações de Terminal que estão no teu ReadMe, do config? Sobre Shell, ZSH, eu não faço idéia do que seja isso.

Por fim, sobre o Lint. O Lint é meio que um "padrão" de escrita? São normas? Ou é um arquivo instalável?

Peço desculpas novamente, porque sinto que minhas dúvidas são bem amadoras. E te agradeço mais uma vez pelo seu tempo e atenção.

**Comment by fdaciuk** [comment]
O Hyper normalmente funciona bem no Windows, já tive indicações de alunos, por isso te recomendei ele =)

Como ele foi lançado depois que eu já tinha começado o curso, ele acabou ficando fora das recomendações dos vídeos =)

Sobre o diretório `config` lá no repositório: eu só deixei essas configurações ali se por acaso algum aluno queira seguir mais ou  menos as configurações que eu estou usando, mas é completamente opcional, e apenas recomendado para aqueles que já se sentem um pouco mais confortáveis com essas ferramentas. Pode seguir com a sua configuração mínima (terminal Hyper, editor de textos, e o Node.js) que você vai conseguir acompanhar o curso sem problemas :)

Sobre o linter, é mais ou menos isso mesmo: como não existe um padrão de escrita em JavaScript, nós podemos escrever nosso código de várias formas diferentes. O linter serve para definir um padrão a ser usado no projeto, e evitar alguns erros comuns que são difíceis de enxergar quando estamos apenas escrevendo código JavaScript. Muitos desses erros só aparecem muito tarde, e acaba ficando difícil de debugar. O linter te ajuda com esses casos :)

E não precisa perdir desculpas não! A única coisa que eu espero do aluno que está fazendo esse curso é um bom conhecimento na linguagem JavaScript (ES5). Todas as novidades da linguagem (ES6 pra frente) que precisarmos utilizar eu vou mostrando durante o curso, não se preocupe com isso!

Se ficar qualquer dúvida com relação às configurações, instalação de dependências, etc., pode perguntar sem problemas! Vou tentar ir melhorando o curso, e deixando essas coisas o mais claro possível com o tempo, e com o feedback dos alunos :)

Fique à vontade para perguntar sempre que tiver dúvidas. Estou disponível para te ajudar a aprender React.js de verdade, e chegar no nível Ninja com essa ferramenta :D

**Comment by Roger-Melo** [comment]
> Bom, primeiro, eu te agradeço por ser uma pessoa que dá suporte ativo pra quem usa seu curso. Isso é um diferencial enorme. 

Verdade verdadeira, @fdaciuk é muito prestativo! =)

**Comment by Roger-Melo** [comment]
> Para terminal, tem uma recomendação que acho que vai ser melhor que o Cmder, que é o [Hyper](https://hyper.is).

oloko, testando já!

**Comment by fdaciuk** [comment]
haha! Legal galera. Precisando de algo, só avisar =)
