### ISSUE TITLE
NavLink não adiciona class active

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#268]
Por acaso alguém já teve problema no NavLink adicionar a class active somente quando carrega a pagina, se eu clico no menu ele carrega a pagina normalmente só que não adiciona a class active.

#Edit01
O erro esta ligado com o connect do Redux, eu retirei o connect do componente e ele funcionou normalmente.

#SOLUÇÃO
O que estava acontecendo era um bloqueio de atualização, pode se ler mais nesse artigo com a solução do próprio react-router.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Que bom que conseguiu resolver =)
Tem algumas tricks mesmo pra pra usar com redux, por conta do tipo de atualização xD

Qualquer coisa, avisa ae =)
