### ISSUE TITLE
[MRW#10] - app.js e index.js com Unexpected token /

### ISSUE THREAD

**Issue by walterjaworski** [da2k/curso-reactjs-ninja#269]
Fala carinha, tudo bom?
Antes de instalar o validator (e após também), reparei que após gerar o bundle.js, aparecem dois erros no terminal e no console do navegador:

> index.js <text>:11:16: Parsing error: Unexpected token /
app.js <text>:7:30: Parsing error: Unexpected token /

A princípio o código destes dois arquivos estão iguais aos da aula.

Aproveitando, após instalar o Validator e inserir no webpack.config.js, não retorna uma mensagem no terminal tamnbém.

Pode dar um help?

Segue repositório com os arquivos: https://github.com/walterjaworski/duvidas-react

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @walterjaworski! Tenta remover a sua `node_modules` e instalar novamente as dependências (com `npm install`) =)

Sobre o validator, qual mensagem você esperava que ele exibisse? Não entendi muito bem =)

**Comment by walterjaworski** [comment]
@fdaciuk depois de postar cheguei a consultar outros tópicos semelhantes e tentei isso de apagar a pasta `node_modules` mas não surgiu efeito nenhum.

Quanto a mensagem é a mesma que mostra no vídeo: [webpack-validator] Config is valid conforme print anexo: 
![screen shot 2019-02-07 at 1 44 52 pm](https://user-images.githubusercontent.com/3688982/52423123-9b698180-2ade-11e9-9a6e-5fa90e1034f5.png)

**Comment by walterjaworski** [comment]
[UPDATE] Adicionei uma linha em branco no final do app.js e do index.js e o erro sumiu. Mas a mensagem do validator, mesmo instalando e seguindo as orientações do vídeo, não aparece.

**Comment by fdaciuk** [comment]
Ah, saquei! Bom, eu rodei aqui o projeto, e realmente não está exibindo a mensagem. Não sei te dizer exatamente o porquê, mas a validação está rodando certinha, então pode ficar tranquilo =)

Sobre o erro de lint, deu certo agora então? Perfeito! Qualquer coisa então, só avisar =)
