### ISSUE TITLE
Manipulação do DOM apenas com JavaScript

### ISSUE THREAD

**Issue by renanlbl** [da2k/curso-reactjs-ninja#270]
Escreva aqui sua dúvida
Fala mestre! Ficou bem claro pra mim que o React trabalha com dados pra fazer a manipulação do DOM, mas eu estava fazendo um projeto e tive que voltar valor de um select para o placeholder toda vez que a pessoa clica no botão limpar, então usei Javascript puro pra fazer isso! Isso seria errado?
```

 handleClear = (e) => {
        const type = document.querySelector('[name=tipo]')
        const typeCompare = document.querySelector('[name=tipoCompare]')
        type.children.placeholder.selected = true
        typeCompare.children.placeholder.selected = true      
    }

```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanlbl! Você até consegue fazer isso manipulando DOM manualmente, mas como é possível fazer só usando React, é preferível sempre fazer dessa forma.

Você vai fazer manipulação de DOM em aplicações React apenas quando realmente não for possível fazer só com React.

Se você não conseguir fazer sozinho, e não puder compartilhar seu projeto todo, tente ao menos simular o comportamento do que você está fazendo em um pequeno projeto, que eu te ajudo a resolver isso, beleza? =)

**Comment by renanlbl** [comment]
@fdaciuk Ahh sim!! Valeuu da2k, vou tentar fazer mais um pouco sozinho, mas pode fechar, era só essa dúvida mesmo!! Obrigadão, vou dar continuidade ao curso pra ver se eu consigo fazer sozinho, só fiz até o modulo 1 - pt2.

**Comment by fdaciuk** [comment]
Show de bola! Qualquer dúvida, só avisar :D
