### ISSUE TITLE
M3#A14

### ISSUE THREAD

**Issue by juniorb34** [da2k/curso-reactjs-ninja#271]
professor, eu realmente não entendi essa aula. Já assisti algumas vezes, mas tá difícil. você pode me explicar melhor como funciona esse connect?
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @juniorb34! Claro =)
Vamos por partes, pra eu entender o que você conseguiu pegar, e o que não =)

Você entendeu que o connect, quando executado as duas funções que ele retorna, ele vai devolver um novo componente?

**Comment by juniorb34** [comment]
Não. :(

**Comment by fdaciuk** [comment]
Certo, vamos lá =)
Você chegou a ver as últimas aulas do módulo 2, onde eu falei sobre a Context API?

**Comment by juniorb34** [comment]
Sim. Eu entendo a função da Context API, que é passar o estado da aplicação direto para o componente desejado, sem precisar passar por "atravessadores", né isso?

**Comment by fdaciuk** [comment]
Isso ae! A função connect e o componente Provider basicamente abstraem essa funcionalidade da Context API: O Provider têm o contexto criado, e quando você usa o `connect`, que é a função que está conectada no contexto criado pelo Provider, você consegue repassar esse contexto pra frente.

Só que a abstração deixa as coisas mais simples: ao invés de passar via context, o `connect` pega a informação que você precisa (passado através da função `mapStateToProps`), e simplesmente traz essa informação do context, injetando no seu componente via props :)

**Comment by juniorb34** [comment]
Entendi. Mas ainda tô na dúvida na função mapStateToProps.
`const mapStateToProps = (state) => {
   return {
       counter: state
    }
}`

o "state" pode ser qualquer string que representa a store que foi passada pelo Provider, é isso? O valor state é então passado para a chave counter (no objeto que é retornado pela função), que é passado como uma prop para o component CounterContainer.

**Comment by fdaciuk** [comment]
É mais ou menos isso.

Só que o `state` recebido pela função `mapStateToProps` não é uma string qualquer, ele é o mesmo state que você tem na `store`.
Se você importar a `store` nesse arquivo, e usar `store.getState()`, você terá exatamente o mesmo resultado =)

A diferença é que, usando o `connect` com `mapStateToProps`, nós injetamos no componente via props as informações de estado que estão na nossa store.

Isso é uma vantagem pois o componente não fica dependente de código externo: tudo o que ele recebe, é sempre via props :)

Imagine a seguinte situação, pensando no caso de importar a `store` direto no componente:
se você tivesse que fazer um teste com esse componente, mas no seu teste você não tivesse acesso à `store`, como esse acesso vem "de fora" do componente que será testado, você precisaria, de alguma forma global, tentar "injetar" a store para que o componente tivesse acesso aos dados que estão ali.

Já passando via props, a informação já faz parte do escopo do componente. É como se fosse uma simples função, e as props fossem os parâmetros passados para a função: o que vem de fora é sempre injetado via parâmetro, nunca no escopo fora dessa função :)

Não sei se ficou muito claro. Se não ficou, vamos conversando que eu vou tentar ir clareando mais, ok? =)

**Comment by juniorb34** [comment]
Sim, está bem mais claro! :). Acho que não me expressei bem quando você me explica que "o `state` recebido pela função `mapStateToProps` não é uma string qualquer, ele é o mesmo state que você tem na `store`." Isso eu compreendi, professor.
Eu quis dizer que poderia dar qualquer nome ao state recebido. Por exemplo, ao invés de state eu escreveria "counter":
`const mapStateToProps = (counter) => { return { counter } }`

Está correto?

**Comment by fdaciuk** [comment]
> Acho que não me expressei bem quando você me explica que "o `state` recebido pela função `mapStateToProps` não é uma string qualquer, ele é o mesmo state que você tem na `store`." Isso eu compreendi, professor.

Perfeito =)

> Eu quis dizer que poderia dar qualquer nome ao state recebido. Por exemplo, ao invés de state eu escreveria "counter":

Ah sim, exatamente, pois é apenas o nome do argumento da função. Ele pode ser chamado de qualquer coisa, inclusive `counter`, como você fez, para reduzir a sintaxe =)

**Comment by juniorb34** [comment]
Obrigado!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
