### ISSUE TITLE
[MRW#03] Problemas com o terminal (comandos não funcionam)

### ISSUE THREAD

**Issue by bobecampos** [da2k/curso-reactjs-ninja#272]
Olá, Daciuk, boa noite.

Tenho executado passo a passo o que vejo nas suas aulas desse módulo, mas as coisas não estão funcionando, e eu não entendo o motivo. Já adianto que tenho utilizado as instruções do [versions-of-dependencies](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md).

Na aula 2, não consegui executar o comando `webpack` no meu terminal. Só consegui executar com uma dica que você deu em uma issue falando de alterar o package.json para depois poder usar o comando `npm run webpack`, e desse jeito deu certo.

No entanto, me deixa inquieto ter seguido tudo conforme a aula e não ter conseguido executar o `webpack`.

Agora, na aula 03, eu instalei o webpack-dev-server das duas formas propostas e, ao utilizar o comando `webpack-dev-server`, eu me deparei com o mesmo erro da aula 02.

'webpack-dev-server' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

A mesmíssima coisa acontece quando eu uso o comando `webpack`.

Eu sinceramente não sei o que pode estar acontecendo de errado, já que eu não entendo praticamente nada quando se trata de terminal, instalação, etc. Confesso que estou 100% perdido nessas aulas desse módulo, mas estou executando cada passo igualzinho às aulas e não tem dado certo.

Será que você consegue me dar uma luz?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @bobecampos!

Vamos lá =)

Para essas dependências que você precisa executar o comando diretamente do terminal, é preciso instalar elas também de forma global, além de instalar usando o `--save-dev` =)

Isso está no arquivo de dependências também, [olha só](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#v%C3%ADdeo-2) =)

Mas eu vou assistir novamente essas aulas pra ver se eu consigo melhorar essa forma de explicar, pois a intenção é tentar deixar tudo o mais claro possível =)

Obrigado por reportar sua dificuldade, e sempre que precisar de ajuda, pode sempre perguntar! Estou à disposição para ajudar =)

**Comment by bobecampos** [comment]
Então, como eu disse, eu fiz exatamente como nas aulas. E, em ambas as aulas, você faz a instalação usando o `--save-dev`... ou seja, eu fiz essas instalações também. Antes mesmo que a instalação global, até porque, em ambas as aulas, você instala primeiro usando o `--save-dev` e, depois, usando o `-g`. 

O ponto é que eu fiz as duas formas de instalações. Os meus arquivos estão iguais aos seus (com exceção do package.json, que precisei incluir a entrada

`"scripts": {
    "webpack": "webpack"
  }`

para poder usar o comando `npm run webpack`. No entanto, eu tive que fazer isso justamente porque o comando `webpack` não funcionou após eu fazer a instalação do webpack dos dois jeitos propostos na aula).

Eu não sei se os diretórios podem ter algo a ver com isso. O HD do meu computador é dividido, o C: é para sistema e o D: é para arquivos pessoais. O Node, por exemplo, está instalado no C:. Só que tudo que estou fazendo com relação a este curso de React está numa pasta no diretório D:. Não sei se isso pode estar atrapalhando... mas não imagino que seja isso, afinal, a instalação global não é justamente para permitir que meu terminal possa usar a ferramenta em qualquer diretório?

**Comment by fdaciuk** [comment]
Entendi! É exatamente essa a ideia de instalar de forma global: poder rodar os comandos de qualquer lugar! Mas o problema possivelmente é porque você está usando windows com algum terminal que não deve adicionar dependências do NPM no PATH do sistema, não permitindo assim a execução do programa de forma global.

Qual terminal você está usando? Vou recomendar pra você tentar o mesmo usando o [Hyper](https://hyper.is).

Teste com ele, por favor, e me diga se funcionou ou não, ok? =)

**Comment by bobecampos** [comment]
Então, eu estou usando o Hyper.

Foi inclusive você quem me recomendou, hahahaha.

Eu ainda não testei uma coisa: eu tenho o npm E o yarn instalados na minha máquina. Será que eles estariam dando conflito entre si?

E tem uma coisa que eu queria entender... tentando de outro modo fazer a instalação, eu usei o comando `npx create-react-app` e, aparentemente, ele baixou o meu React na pasta, tendo dentro da pasta node-modules uma pasta chamada webpack. 

O React instalou o webpack por si só pra mim? Consigo acompanhar o curso deste jeito?

**Comment by fdaciuk** [comment]
> Então, eu estou usando o Hyper.
> Foi inclusive você quem me recomendou, hahahaha.

Eita, verdade haha! Desculpe =)

> Eu ainda não testei uma coisa: eu tenho o npm E o yarn instalados na minha máquina. Será que eles estariam dando conflito entre si?

Cara, não acredito que seja esse o problema não. Mas não tenho como te dizer com certeza porque não tenho Windows pra testar isso :\
Vou ver se consigo subir uma máquina virtual pra tentar reproduzir o problema =)

> E tem uma coisa que eu queria entender... tentando de outro modo fazer a instalação, eu usei o comando `npx create-react-app` e, aparentemente, ele baixou o meu React na pasta, tendo dentro da pasta node-modules uma pasta chamada webpack.

Ah, essa seria uma forma que você poderia usar mesmo: como `npx`. Esse comando serve para não precisar instalar dependências de forma global. Tive alguns problemas em alguns casos, mas nada difícil de resolver :)

De qualquer forma, pra continuar acompanhando as aulas, você tem 3 opções:
- Você pode usar o `create-react-app`, que mantém todas as configurações por baixo dos panos, e pular as aulas e configuração (depois você pode voltar se quiser, pra aprender a fazer as configurações);
- A segunda opção seria usar o `npx` para rodar comandos direto na linha de comando. Ao invés de `webpack`, pode rodar direto o `npx webpack@1`. Mesma coisa para o `wepack-dev-server`: Use `npx webpack-dev-server@1`, e assim você deve conseguir acompanhar todas as aulas sem problemas;
- ou ainda criando os scripts no `package.json`, para rodar com `npm run NOME_DO_SCRIPT`, como você fez com o `webpack` :)

Enfim, fique à vontade para seguir da forma que achar mais simples (acho que adicionando o script, por mais verboso que seja, pode ser melhor nesse caso, por não precisar instalar as dependências de forma global) =)

> O React instalou o webpack por si só pra mim? Consigo acompanhar o curso deste jeito?

Esse webpack usado pelo create-react-app fica com as configurações "escondidas". Você consegue acompanhar as aulas, mas não vai conseguir usar as configurações da forma que eu for mostrando nas aulas, pois essa ferramenta serve exatamente pra você conseguir criar uma aplicação com React sem precisar configurar nada :D 

Mas assim: escolha o que for mais fácil pra você agora, e pergunte sempre que tiver dúvidas, que eu vou te ajudando, ok? =)

**Comment by bobecampos** [comment]
Tenho assistido às aulas normalmente. Apenas fazendo algumas poucas mudanças, tenho conseguido rodar os exemplos que você tem dado sem problemas.

> * Você pode usar o `create-react-app`, que mantém todas as configurações por baixo dos panos, e pular as aulas e configuração (depois você pode voltar se quiser, pra aprender a fazer as configurações);

Foi mais ou menos isso que eu fiz mesmo. Provavelmente, quando eu tiver mais noções, devo voltar nas aulas de Webpack. Mas realmente acredito ser muito inexperiente pra dar conta delas agora (como já falei outra vez, me viro melhor mexendo no código em si do que nessa parte de instalações, terminal, dependências, configurações, etc).

Atualmente, já estou na aula 13 do módulo 1... então até que está dando tudo certo (gosto de assistir às aulas com calma, anotando as coisas num caderno, mas tô dando uma corrida nesse caso e vendo a documentação junto porque preciso resolver um desafio em React até terça-feira pra disputar uma vaga de emprego, HAHAHA).

Daciuk, muito obrigado pela sua prestatividade de sempre. Gostaria que os outros instrutores da Udemy pelos quais já passei fossem mais como você.

Um abraço, e bom final de semana!

**Comment by fdaciuk** [comment]
Entendi! Legal cara, pode fazer dessa forma sem problemas =)

Fico muito feliz de ler feedbacks assim. Só mostra que o curso, no geral, está cumprindo com o objetivo, de realmente ajudar o aluno :D 

E conte comigo sempre que precisar! Estou à disposição para ajudar =)
