### ISSUE TITLE
Problema com o standard

### ISSUE THREAD

**Issue by jhonesgoncal** [da2k/curso-reactjs-ninja#273]
Problema com o standard, ele reclama de / 

repo
https://github.com/jhonesgoncal/curso-react-ninja

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonesgoncal! Eu testei aqui, mas funcionou corretamente, sem os warnings.

Você tinha comentado que apagou a node_modules e instalou de novo, correto? Tente apagar a node_modules e o package-config.json, e fazer a instalação novamente.

Alguns alunos que usam windows reportaram o mesmo problema, e isso resolveu.

Me deixe saber se isso funciona pra você :)

**Comment by fdaciuk** [comment]
Dá uma olhada também se você tem o plugin do `editorconfig` instalado no seu editor :)

**Comment by jhonesgoncal** [comment]
tem essa extensao pro vscode? estou usando mac

**Comment by fdaciuk** [comment]
Tem sim =)
Dá uma olhada aqui:
https://editorconfig.org/
