### ISSUE TITLE
Próximos modulos

### ISSUE THREAD

**Issue by cyberdanilo** [da2k/curso-reactjs-ninja#274]
Olá, tem alguma previsão para o lançamento do módulo de atualizações e o módulo 05, ou a ementa desses modulos ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @cyberdanilo! O módulo de atualizações eu vou lançar em breve. Estou terminando as aulas do módulo 4, e logo em seguida vou começar a fazer as aulas do módulo de atualizações =)

O módulo 5 vai demorar um pouquinho, pois pretendo fazer um curso de Node.js antes, para facilitar o entedimento desse módulo :)

Mas fique tranquilo que eu vou avisando das novidades pelas mensagens da Udemy :D

**Comment by danilosales** [comment]
Beleza, fico no aguardo!!!
