### ISSUE TITLE
M4-React-zzaria 

### ISSUE THREAD

**Issue by renatorvb** [da2k/curso-reactjs-ninja#275]
Olá professor, tudo bem? Sei que vai publicar em breve mais aulas do M4, mas vc tem uma previsão de datas das demais aulas do react-zzaria? 
Estou mto ansioso, pois estou me baseando em suas aulas para um projeto pessoal.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renatorvb! Até amanhã cedo já estarão disponíveis mais algumas aulas. A partir de agora, vou tentar aumentar a regularidade de disponibilização das aulas, pra fechar esse módulo o quanto antes, com o máximo de conteúdo relevante possível :D
