### ISSUE TITLE
M3#A19

### ISSUE THREAD

**Issue by pedromuraki** [da2k/curso-reactjs-ninja#276]
Fala Fernando, beleza?

Lá pelos 8 minutos de vídeo, vc substitui o paramêtro "counter" do filter, por um "_". Isso muda algo em relação a performance ou é apenas uma indicação visual dizendo que o parâmetro não vai ser usado no callback?

Abs!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pedromuraki! Não muda nada com relação à performance, é só pra não ficar uma variável nomeada sem uso mesmo. 

Mas essa forma de escrever é completamente opcional. Algumas pessoas podem gostar, outras não.

Use o que ficar melhor pra você entender, ok? =)

**Comment by pedromuraki** [comment]
Obrigado!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
