### ISSUE TITLE
Não estou conseguindo acessar os exercícios 

### ISSUE THREAD

**Issue by mathenrifs** [da2k/curso-reactjs-ninja#277]
Entro em challenge mas não encontro os exercícios pra treinar 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mathenrifs! Acabei não usando esse diretório para lançar desafios, mas os códigos feitos nas aulas estão no diretório [`examples`](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples), separado por módulo =)
