### ISSUE TITLE
M1#A12

### ISSUE THREAD

**Issue by filipeltsilva** [da2k/curso-reactjs-ninja#28]
@fdaciuk, duas questões sobre a short-hand notation:

1) Há algum ganho de performance na aplicação pelo fato de conseguirmos importar uma parte de um todo, como feito com _{ Component }_ na aula 12 do módulo 1?

2) O espaço após a abertura e antes do fechamento das chaves é obrigatório ou apenas uma convenção?

**Comment by fdaciuk** [comment]
Fala @filipeltsilva! Vamos lá!

Começando pela mais simples xD

O espaço é opcional, só _code styling_ mesmo =)

Nesse caso eu gosto de deixar um espaço antes e um depois para não ficar tudo colado =)

Sobre a primeira, a resposta é: depende.

Existe uma nova feature no `webpack 2` (que você vai ver no módulo 2), que se chama _tree shaking_. Ele faz exatamente isso que você comentou: se o código estiver usando ES6 Modules, ele consegue importar somente a parte necessária quando você usa a _shorthand notation_, ao invés da lib inteira. A não ser que o código esteja sendo exportado como propriedade do objeto principal. No caso do React, não faz diferença. É só pra não precisar usar `React.Component` mesmo.

Mas a ideia do _tree shaking_, que começou com o `rollup` - outro _module bundler_ que pode ser usado no lugar do _webpack_ - é pra ser usado quando ES Modules estiverem funcionando nos browsers e no Node.

Então sim: a ideia é que isso tenha melhoras na performance, mas no momento só vai ter se:
- o elemento importado não for propriedade do objeto principal;
- você estiver usando webpack 2 ou rollup.

Ficou claro? =)

**Comment by filipeltsilva** [comment]
@fdaciuk, ficou satisfatoriamente compreensível. Agora sou eu quem preciso continuar correndo atrás do conhecimento. Obrigado pelos esclarecimentos.

**Comment by fdaciuk** [comment]
Show! Mas fica tranquilo que vc ainda vai chegar na parte que eu explico isso no curso xD
