### ISSUE TITLE
O This no React.

### ISSUE THREAD

**Issue by renanlbl** [da2k/curso-reactjs-ninja#282]
Fala mestre, estava estudando sobre programação funcional, mas no final das contas eu entendi, mas deu um nó na minha cabeça kkkk...

Assim, pelo o que eu entendi no React só usamos programação funcional em Componentes stateless, nos componentes statefull é impossível usar programação funcional, certo?

E Outra coisa, quase sempre utilizamos arrow function... e nos componentes Statefull, quando usado arrow function, o this aponta para própria classe, certo? 

E tipo, fiz um teste no vscode do seguinte: 
`
const person = () => {
    console.log(this === global)
}
person() // output: false
`
Mas fazendo no console do navageador foi diferente o resultado.
`
const person = () => {
    console.log(this === window)
}
person() //output: true
`
Sei que é Javascript básico, mas isso me deu um nó na cabeça absurdo, não sei se é viável utilizar programação funcional no React ou não, porque em componentes Statefull me parece muito programação OO.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanlbl! JavaScript é uma liguagem multiparadigma, o que significa que você não vai conseguir usar ela sempre só de forma funcional. O React traz alguns conceitos de programação funcional, como imutabilidade e funções puras, e isso deve sempre ser respeitado quando falados de _state_ e _props_ (imutabilidade), e o retorno de um componente de função, assim como o método `render` de class, devem sempre ser puros.

Se você fizer isso, não vai ter problemas ao utilizar React :)

Arrow functions tem escopo léxico. Para entender como elas funcionam na sua totalidade, eu escrevi um artigo recentemente, que você pode ler [aqui](https://blog.da2k.com.br/2019/01/07/javascript-tudo-sobre-arrow-functions/). =)

Acho que já vai ajudar com essas dúvidas :)

Qualquer coisa, me avise!

**Comment by renanlbl** [comment]
Então, assim... funções puras são funções que não geram side effects e sempre vão retornar o mesmo output...

Mas quando por exemplo criamos um component de input Text com value sendo recebido por parâmentro...
```
const Search = ({ valueText }) => (
    <div className='search'>
        <input
          type='text'
          placeholder='Digite o nome do usuário no GitHub'
          value={valueText}
        />
    </div>
)
```
Isso estou criando uma função pura que sempre retornará esse input, certo? Mas o value passado por parâmetro {valueText} pode ser mudado dependo da situação e onde ele é chamado, correto? Então nesse caso ele acaba virando uma função inpura? Já que o output pode variar?

**Comment by fdaciuk** [comment]
Na verdade não, porque não é a função `inputText` que muda o valor de `valueText`. A função simplesmente recebe o `valueText` e renderiza, independente do que vier ali. Por isso ela é uma função pura: se você executar essa função, passando sempre o mesmo input, ela vai te devolver sempre o mesmo output.

E a função não faz nenhuma chamada externa, para modificar valores fora dela, logo ela não gera side effects, e continua sendo uma função pura.

Quem muda o `valueText` é quem chama essa função. E se o `valueText` mudar, uma nova chamada da função será feita, e um novo objeto será retornado.

Ficou claro? =)

**Comment by renanlbl** [comment]
@fdaciuk 
Valeuuu da2ka! Ficou claro agora!! vlww

**Comment by fdaciuk** [comment]
Perfeito @renanlbl! Qualquer dúvida, só avisar :D
