### ISSUE TITLE
MRW#08 Erros no console ao habilitar o hot module replacement

### ISSUE THREAD

**Issue by daniilomello** [da2k/curso-reactjs-ninja#283]
Hot loader não está funcionando, está aparecendo vários erros no console. 

![Imagem](https://i.imgur.com/eiHofbi.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @daniilomello! Compartilha comigo o repositório do seu projeto, por favor?

**Comment by daniilomello** [comment]
@fdaciuk 

https://github.com/daniilomello/react-ninja-project

**Comment by fdaciuk** [comment]
Oi @daniilomello! Faltou o `:` depois do `http`, na configuração do seu webpack:
https://github.com/daniilomello/react-ninja-project/blob/master/webpack.config.js#L11

=)

**Comment by daniilomello** [comment]
Nossa que vacilo, deu certo agora! Obrigado @fdaciuk

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
