### ISSUE TITLE
M3#A29 - Todo-list

### ISSUE THREAD

**Issue by gisesonia** [da2k/curso-reactjs-ninja#284]
No primeiro teste precisou criar um objeto e no segundo tem um initialState, mas no index.js não foi definido nada, no teste como ele entende que o before era o initialState ou não é assim?
Como ele sabe que já tem um objeto e está sendo adicionado outro?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gisesonia! Te respondi lá pela Udemy :)

**Comment by gisesonia** [comment]
Obrigada.
