### ISSUE TITLE
M3#A34 -App Todo List props

### ISSUE THREAD

**Issue by gisesonia** [da2k/curso-reactjs-ninja#285]
Escreva aqui sua dúvida

Oi, eu tenho muita dúvida na mudança de sintaxe de componente classe e stateless, no caso, eu estava seguindo o exemplo, mas estava usando componente classe e não sei como está sendo passado os parametros.
const App = ({ todos, handleAddTodo}), como fica?

class App extends React.Component {
  constructor(props) {
    super(props);
    console.log(props)
  }
faz destruturing, const {todos,handleAddTodo} = this.props?
Esqueci de perguntar,  eu não vi nada quando eu cliquei no botão, não adicionou nada.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gisesonia! Não sei se você chegou a assistir o módulo 1, mas lá eu explico certinho esses pontos mais básicos do React :)

Mas a troca de componente de `class` para componente de função é isso mesmo: na class, você tem acesso às props via `this.props` (fora do constructor. Dentro dele você pega no argumento que ele recebe, assim como no seu exemplo);

já para funções, você vai receber um objeto props via argumento na função.

Seria algo assim:

```js
class App extends React.Component {
  constructor (props) {
    // aqui você tem acesso as props via o argumento props
  }

  render () {
    // em todos os outros métodos da class, você consegue as props via this.props
    console.log(this.props)
  }
}
```

Já para funções, seria assim:

```js
const App = (props) => {
  console.log(props)
  return <h1>App</h1>
}
```

Se quiser pegar só os valores do objeto `props`, pode usar o _destructuring_:

```js
const App = ({ todos, handleAddTodo }) => {
  console.log(todos, handleAddTodo)
  return <h1>App</h1>
}
```

Para o caso de ser uma função, pode usar também a função padrão do JS, que vai funcionar da mesma forma:

```js
function App (props) {
  console.log(props)
  return <h1>App</h1>
}
```

E o destructuring, mesma coisa:

```js
function App ({ todos, handleAddTodo }) {
  console.log(todos, handleAddTodo)
  return <h1>App</h1>
}
```

**Comment by gisesonia** [comment]
Eu vou procurar as aulas, no meu exemplo, não apareceu o estado atualizado, eu criei no CodeSandbox porque não estou na minha máquina e estava querendo testar:

https://codesandbox.io/s/zl35rwpj5p

Porque não aparece o novo estado?

**Comment by fdaciuk** [comment]
Oi @gisesonia! =)
Você está tentando visualizar o novo estado no `constructor`? Se sim, provavelmente é por isso que você não está vendo o dado atualizado. O `constructor` é executado apenas uma vez, quando o componente é construído.

Coloque um console.log no `render`, antes do `return`, com os dados que você quer ver, pois esse método é sempre re-renderizado a cada vez que um valor de estado ou props mudam :)

**Comment by gisesonia** [comment]
```
 return (     
      <div>
        <form onSubmit={this.handleAddTodo}>
          <input type="text" name="todo" />
          <button type="submit">Adicionar</button>
        </form>
        {console.log(this.todos)}
        <ul>
```

**Comment by fdaciuk** [comment]
Pode ser aí, ou pode ser antes do `return` mesmo. Não esqueça que os `todos` vão estar em `this.props.todos` :)

**Comment by gisesonia** [comment]
Mas não apareceu, tá certo?
`class App extends React.Component {
  constructor(props) {
    super(props);
    const { todos, handleAddTodo } = this.props
    console.log(todos)
  }

  render() {
    
    return (     
      <div>
        <form onSubmit={this.handleAddTodo}>
          <input type="text" name="todo" />
          <button type="submit">Adicionar</button>
        </form>
        {console.log(this.todos)}
        <ul>
          <li style={{ textDecoration: "line-through" }}>Item 1</li>
          <li>Item 2</li>
          <li>Item 3</li>
          <li>Item 4</li>
          <li>Item 5</li>
        </ul>
        <div>
          <h3>Mostrar</h3>
          <span>Todos</span> | <a href="">Finalizados</a> |{" "}
          <a href="">A fazer</a>
        </div>
      </div>
    );
  }
}

const mapStateToProps = (state) => ({
  todos: state
})

const mapDispatchToProps = (dispatch) => ({
  handleAddTodo: (e) => {
    e.preventDefault();
    dispatch({
      type:'ADD_TODO',
       payload: { id:0, text: 'Hey'}
    })
  }
})

export default connect(mapStateToProps,mapDispatchToProps)(App);`

**Comment by gisesonia** [comment]
Arrumei `this.props.todos`

**Comment by fdaciuk** [comment]
O `handleAddTodo` você também passa via props, então tem que passar ele para o `onSubmit` do `form` com `this.props.handleAddTodo` :)

**Comment by gisesonia** [comment]
Agora sim, muito obrigada, gostei muito dos exemplos do seu curso, principalmente desse, porque dá para ver como as props são passadas, alguns exemplos são muito complexos e não dá para ver. Eu sempre acabo com esses erros bobos, mas que fazem toda a diferença.
Serviu para entender a diferença de classe e stateless.

**Comment by fdaciuk** [comment]
Perfeito @gisesonia! =)
Qualquer dúvida, só avisar :D
