### ISSUE TITLE
Axios e chamadas de API

### ISSUE THREAD

**Issue by gisesonia** [da2k/curso-reactjs-ninja#286]
Eu tenho várias dúvidas sobre utilizar request de API, estou tentando finalizar um projeto e não sei porque os dados não carregam, também porque eu não entendo muito de API, no curso tem algo sobre isso, sobre axios?
Como eu posso capturar esse tipo de erro, se os dados estão sendo passados para o react?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gisesonia! Tem sim =)
Assista os módulos 1 e 2 que tem bastante informação sobre isso :)
Pode pular as partes de configuração, e usar o create-react-app pra facilitar :)
Só fique atenta às versões do React, pra conseguir acompanhar exatamente o que eu estou mostrando!

Finalizando o módulo 2, você já pode utilizar as versões mais recentes do react e react-dom :)

**Comment by gisesonia** [comment]
Obrigada. vou olhar.

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
