### ISSUE TITLE
BuscarCep Form - presentation e container

### ISSUE THREAD

**Issue by rodrigoclp** [da2k/curso-reactjs-ninja#287]
Olá Fernando.
Para o buscar cep, você criou um container para o form/table. Considerando q esse form somente existirá ali e não será utilizado em outro local, seria necessário separar o presentation e o container, ou poderia ser tudo em um único componente (class e jsx)?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rodrigoclp! Se não precisar reutilizar, pode fazer tudo em um componente só, não é necessário separar :)

Eu separei por questão de gosto, e para não deixar um arquivo com muitas linhas de código, mas fique à vontade para fazer como achar melhor :)
