### ISSUE TITLE
Usar ou não usar o Redux

### ISSUE THREAD

**Issue by rodrigoclp** [da2k/curso-reactjs-ninja#288]
Estou confuso sobre o redux. Vejo sempre pessoas falando sobre redux, redux sagas, redux thunk etc. Porém, não consigo ver muita utilidade, a não ser para persistir informações globais, como dados de login por exemplo. 
Em alguns casos até prefiro fazer um novo request, ao invés de guardar no redux - parece q o componente fica mais simples e mais desacoplado.

Minhas dúvidas são: quando de fato usar o Redux? Quase não o utilizo, será q estou fazendo do jeito errado? Devo utilizar na maior parte dos componentes?

@fdaciuk

**Comment by nidelson** [comment]
@rodrigoclp também sempre tive essa dúvida: usar ou não... eis a questão! Mas veja bem:
Hoje uso e pra mim caiu como uma luva. É muito simples acoplar um novo `reducer` para ouvir certo tipo de action e dai as coisas começam ficar legais.
Por exemplo:
- Minha tela de login emite uma ACTION.AUTHENTICATION_LOADING
- O authenticationReducer ouve essa action, processa e emite um SIGNIN_SUCCESS ou SIGNIN_ERROR
- O navigationReducer ouve SIGNIN_SUCCESS e redireciona para Home.
- Um eventReducer poderia registrar uma timeline dessa `action` também, por exemplo.
Resumindo, cada mudança de um estado poderia envolver muitas outra ações e cada `reducer` pode ser encarregado de fazer seu papel em separado. Ainda mais quando sua aplicação estiver grande e que um evento dispara vários outros.

Eu não sei explicar como o mestre @fdaciuk, mas minha opinião é que o Redux é sim muito válido, ainda mais quando você sabe que a aplicação vai ficar gigante.

Se eu estiver redondamente enganado, me orientem, please!

[]s

**Comment by fdaciuk** [comment]
Oi @rodrigoclp!

Obrigado pela resposta @nidelson! :D 

Ao meu ver, não existe resposta pronta. Usar qualquer ferramenta depende de muitas coisas. Ao aprender Redux, você vai entender como ele funciona, e o quanto de verbosidade e boilerplate ele adiciona na sua aplicação.

Mas também vai saber que, com ele, você isola facilmente o estado e qualquer regra lógica da sua aplicação, se quiser.

A vantagem que ele traz com essa separação, é a de não precisar, necessariamente, usar uma única lib. Se futuramente você quiser usar as mesmas regras que estão no Redux em outra aplicação, com outra lib, você pode :)

Mas essa vantagem pode não ser verdade para a sua aplicação.

Por isso, antes de decidir por qualquer ferramenta, entenda como ela funciona, pois só assim, com base nesse conhecimento, e no que precisa ser feito na sua aplicação, você poderá decidir se faz uso dela ou não :)
