### ISSUE TITLE
M4#A59 - Uncaught Error: Network Error at eval (auth.esm.js:4943)

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#289]
E aí @fdaciuk, blz?

Deu esse erro aki quando faço o login, não funciona como no video:

![Captura de Tela (27)](https://user-images.githubusercontent.com/39469118/54302562-ea07b100-459f-11e9-82b2-69bea77fae3b.png)

segue o repo: [reactzzaria](https://github.com/hiwoshu/reactzzaria)

Já aproveitando pra tirar a dúvida: Como eu faria se quisesse criar um app com cadastro próprio de usuários, mas não sendo _email_ e _senha_, mas como um sistema corporativo, ou de gerenciamento em que o usuário acessa com _id_ e _senha_, e que tivesse diferentes níveis de permissão de acesso, tem essa opção no firebase? Ou seria uma má ideia usar o firebase para isso?

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Esse erro é no arquivo do firebase. 
Você está tentando fazer login no localhost? Chegou a ver se o seu localhost está liberado lá nas configurações de domínios autorizados do firebase (Authorized domains)?

---

Sobre a sua outra dúvida:

> Já aproveitando pra tirar a dúvida: Como eu faria se quisesse criar um app com cadastro próprio de usuários, mas não sendo email e senha, mas como um sistema corporativo, ou de gerenciamento em que o usuário acessa com id e senha, e que tivesse diferentes níveis de permissão de acesso, tem essa opção no firebase? Ou seria uma má ideia usar o firebase para isso?

O Firebase tem aqueles métodos específicos para autenticação. Se você quiser criar um diferente, teria que programar por conta :)

Sobre níveis de permissão, você pode setar na própria base do Firebase esses níveis, definindo as permissões à partir do ID do usuário que o Firebase te entrega no momento da autenticação ou criação do cadastro. Você pode setar todo novo usuário com nível mais baixo, e ter uma outra interface onde você, como administrador do sistema, consiga setar permissões diferentes para os usuários já cadastrados :)

**Comment by hiwoshu** [comment]
@fdaciuk 
Assim?:
![screenshot-console firebase google com-2019 03 13-19-27-34](https://user-images.githubusercontent.com/39469118/54318811-4382d680-45c6-11e9-8426-7c409d1643c2.png)


Sobre a outra dúvida, eu entendi, só pensei que tivesse uma opção automatizada como as outras.
Mas não tem problema, se precisar fazer eu faço, entendo um pouco de banco.

**Comment by fdaciuk** [comment]
Exato @hiwoshu! Você está testando local mesmo? Ou fez deploy em algum lugar?

**Comment by hiwoshu** [comment]
@fdaciuk
É tudo local mesmo, mas deu certo aki, acho q o problema é a minha internet mesmo, q é ruim.

![Captura de Tela (28)](https://user-images.githubusercontent.com/39469118/54432267-784a7700-4707-11e9-89a2-bc44c4ede326.png)

Valew!

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Que loucura! Eu dei uma pesquisada nas issues do Firebase, e encontrei uma de 2017 se não me engano, da galera falando sobre esse erro, que acontecia quando `navigator.onLine` estava setado para false. Isso poderia acontecer em conexões mais lentas mesmo, mas segundo o time do Firebase, já era pra estar resolvido :\ 

Mas que bom que deu certo :)
