### ISSUE TITLE
M2#A50 - Dúvida sobre yarn

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#29]
Fala @fdaciuk, beleza?

Só uma pequena dúvida de um cenário que eu passei aqui. 

Vi no vídeo, quando você instalou o as dependencias para test com o comando: `yarn add --dev jest-cli babel-jest chai` o yarn foi super eficaz e trabalhou em cima da instalação desses 3 pacotes !
Porém, no meu computador, ele demorou cerca de uns 5~10minutos, pois tive a impressão que ele passou atualizando todas dependências que tenho no package.json. Normal isso? Será que tem a ver com o Sistema Operacional ? Valeu

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa! =)

O Yarn faz um trabalho profundo de cacheamento de pacotes para ser o mais efetivo o possível. 

Pode ser que, no seu caso, como você estava instalando os pacotes pela primeira vez, ele teve que baixar tudo e organizar as referências. As próximas vezes que você precisar dos mesmos pacotes, com certeza o download será muito mais rápido =)

**Comment by fdaciuk** [comment]
Em alguns casos também, para que os vídeos sejam mais "direto ao ponto", eu faço um corte no momento da instalação. Essa também pode ter sido uma das razões da velocidade =)

**Comment by gabrielferreiraa** [comment]
Ta ok ! Valeu :D

**Comment by fdaciuk** [comment]
Qualquer dúvida grita ae =)
