### ISSUE TITLE
Entender o motivo do destructuring na função

### ISSUE THREAD

**Issue by renanlbl** [da2k/curso-reactjs-ninja#291]
Fala mestre, eu queria entender mais afundo o motivo de utilizar o destructuring nessa função...
` const pagination = ({ total = 1, activePage = 1} = {}) => {}`

Se apenas passase assim: `const pagination = ( total = 1, activePage = 1 )` **daria certo?** e na hora de chamar a função não teria como chamar assim: `pagination(total = 6, activePage = 2)` certo? Então a forma que eu acho que daria pra chamar essa função seria assim: `pagination(6, 2)` **(6 para total, e 2 para activePage)**

Então pelo o que eu entendi, o destructuring é pra ficar mais claro na hora de chamar a função, então podendo ser chamada assim: `pagination({ total: 6, activePage: 6 })`

Entao na hora de construir a função com o destructuring com objeto, ele já cria um objeto com 2 parâmetros, que podem já são transformados em variáveis??

Desculpa a leiguisse, mas queria entender tudinho kkk, valeu da2ka...,

**Aqui a função que estou me referindo abaixo:**
```
const pagination = ({ total = 1, activePage = 1} = {}) => {  

  if (typeof total !== 'number') {
    throw new TypeError('total should be a number')
  }

  if (typeof activePage !== 'number') {
    throw new TypeError('activePage should be a number')
  }

  if (total <= 5) {
    return Array.from({ length: total }, (_, i) => i + 1)
  }
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanlbl! Nessa parte onde tem o destructuring, duas coisas estão acontecendo:
1) o destructuring, de fato, criando as variáveis `total` e `activePage`, que são propriedades do objeto passado via parâmetro, e que serão usadas dentro da função;
2) E estamos também setando os valores padrão, se algum desses valores não forem passados. Essa feature se chamada _default parameters_.

No exemplo que você deu:

```js
const pagination = ( total = 1, activePage = 1 ) => {}
```

Se criássemos a função assim, teríamos que chamar só passando os números:

```js
pagination(6, 2)
```

Mas, se você olhar para a chamada dessa função, sem olhar a implementação, você saberia o que é o `6` e o que é o `2`? Não fica claro, concorda?

Por isso definimos que vamos passar um objeto, com duas chaves: `total` e `activePage`.

Se não usassemos nenhuma dessas features novas do ES6, somente usando ES5, a implementação ficaria assim:

```js
function pagination (args) {
  args = args || {}
  var total = args.total  || 1
  var activePage = args.activePage || 1
}
```

Veja que precisaríamos de 3 linhas a mais para fazer o que fizemos com _destructuring assignment_ + _default parameters_ :)

E estamos fazendo isso para garantir que, se a função for passada sem parâmetros, o valor recebido em `args` vai ser sempre um objeto.

Como `args` vai ser sempre um objeto, eu posso tentar pegar as propriedades `total` e `activePage` desse objeto, que ainda que essas propriedades não existam, eu não recebo um erro, e simplesmente atribuo um valor default de `1` para cada uma delas.

Agora, se `args` não for um objeto, e eu tentar usar `args.total`, por exemplo, vou receber um erro dizendo que `Cannot read property 'total' of undefined`, ou seja: não é possível ler a propriedade `total` de `undefined` (nesse caso, `args` seria `undefined` se nada fosse passado ao executar a função :)

Ficou claro? =)

**Comment by renanlbl** [comment]
Opa ficou claro, mas nessa função em ES5, a chamada da função seria assim?

`pagination({ args.total: 5, args.activePage: 2 })`
ou 
`pagination({ total: 5, activePage: 2 })`

**Comment by fdaciuk** [comment]
A chamada é sempre a mesma:

```js
pagination({ total: 5, activePage: 2 })
```

Sempre passando um objeto :)

**Comment by fdaciuk** [comment]
Essa primeira sintaxe que você colocou não existe :)

**Comment by renanlbl** [comment]
Valeu @fdaciuk!!! Fechouu, obrigado

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D
