### ISSUE TITLE
[M02#A52] - Erro Babel

### ISSUE THREAD

**Issue by raphaelanjos1** [da2k/curso-reactjs-ninja#292]
Fala mestre @fdaciuk, beleza? Estou tendo o seguinte erro quando rodo o yarn run test:watch e não consegui resolver sozinho:

![image](https://user-images.githubusercontent.com/26941113/54531529-471ab280-4964-11e9-809d-3f28972659e2.png)

Segue também a versão das dependências e o pagination.test.js

package.json:

![image](https://user-images.githubusercontent.com/26941113/54531610-76312400-4964-11e9-8e38-7744b69317e3.png)

pagination.test.js:

![image](https://user-images.githubusercontent.com/26941113/54531637-8812c700-4964-11e9-83d5-2df4bb8352ab.png)

Pode me ajudar? Caso necessário, posso subir um repositório. Desde já te agradeço (; .

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @raphaelanjos1! Pode sempre subir um repo pra eu testar, que já facilita :D 
Provavelmente é alguma versão de alguma dependência :)

Sobe o projeto que eu dou uma olhada pra você, ok? :D

**Comment by raphaelanjos1** [comment]
Fala @fdaciuk! Segue o link do repo: https://github.com/raphaelanjos1/react-pagination

**Comment by raphaelanjos1** [comment]
@fdaciuk resolvido mestre! Valeu pela força.

![image](https://user-images.githubusercontent.com/26941113/54615230-7b61a200-4a3c-11e9-93fd-6e117187b853.png)

**Comment by fdaciuk** [comment]
Perfeito @raphaelanjos1 \o/
Qualquer coisa, só avisar :D
