### ISSUE TITLE
Módulo React + webpack mrw#10

### ISSUE THREAD

**Issue by Bruno-hsc** [da2k/curso-reactjs-ninja#294]
meu codigo esta dando erro, não sei usar o git direito eu copio o codigo e coloco aqui?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Bruno-hsc! Eu te respondi lá pela Udemy, mas vou responder por aqui também :)

---

O Git é bem simples de usar, pode usar esse guia aqui que fica bem fácil :D

http://rogerdudler.github.io/git-guide/index.pt_BR.html

Depois me passe o link, porque pra eu conseguir te ajudar, eu preciso conseguir rodar seu projeto pra entender o que pode ser o erro, ok? :)

Qualquer dúvida no processo, me avise que eu te ajudo :D

**Comment by Bruno-hsc** [comment]
eu vi la, vou dar uma olhada.

**Comment by Bruno-hsc** [comment]
Oi professor, vou mandar o link, não sei se fiz direito :) confere ai:
https://github.com/Bruno-hsc/React-Ninja
OBS: tambem nao sei se é assim que manda o link

**Comment by fdaciuk** [comment]
Oi @Bruno-hsc! É isso aí mesmo :)

O seu erro é apenas _typo_ (erro de digitação) [nessa linha](https://github.com/Bruno-hsc/React-Ninja/blob/master/server.js#L10).

Você escreveu `puclicPath` ao invés de `publicPath` :)

**Comment by Bruno-hsc** [comment]
¬¬
Valeu, to aprendendo a mexer no git com o git ninja, muito bom!

**Comment by fdaciuk** [comment]
Perfeito @Bruno-hsc! Qualquer coisa, só avisar :D
