### ISSUE TITLE
Organização de componentes aninhados

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#295]
Oi Professor @fdaciuk ! 

Tô matando a saudade do GitHub App e bateu uma pequena dúvida.  

Dentro do componente `Repos`, possuo uma lista de 'tags' com  
algumas características do repositório; linguagem principal utilizada,  
qtd de forks, stars e a licença.  

![GitHub App](https://user-images.githubusercontent.com/29297788/54883919-9459c100-4e49-11e9-98fe-c630f4ac13a5.jpg)

Eu gostaria de criar um componente 'TagsList', que irá ser invocado  
dentro da declaração do componente `Repos`. A pretensão inicial  
é que essa lista seja utilizada apenas nessa parte da aplicação. Seria  
boa ideia criar a pasta deste componente dentro da pasta do  
componente Repos? 

P.s.: estou no módulo 2. Se mais à frente houverem aulas abordando  
o tema e vc puder me indicar onde está, já seria uma baita ajuda =)

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! O importante é sempre pensar no seguinte: não adicione mais complexidade do que você precisa. Se esse componente vai ser usado apenas em um lugar, deixe ele ali.

Se por acaso você perceber que vai ser necessário utilizá-lo em outro lugar, você isola a regra que se repete e reusa conforme a necessidade :)

Isso vale para a aplicação toda! No caso do GItHub App, eu só quebrei em mais componentes para mostrar como seria o processo, mas daria pra ter quebrado bem menos :)

**Comment by Roger-Melo** [comment]
Faz sentido, professor. Obrigado! =)
