### ISSUE TITLE
[MRW#06] Erro no import Title

### ISSUE THREAD

**Issue by iFabrycio** [da2k/curso-reactjs-ninja#296]
```
'use strict'

import Title from './App'
import React from 'react'
import { render } from 'react-dom'

render(
  React.createElement(Title),
  document.querySelector('[data-js="app"]')
)
```
Eu tenho um erro na linha 3

Linha:
`
import Title from './App'`
Erro:
`
Uncaught SyntaxError: Unexpected identifier in bundle.js:48`
App.js

```
'use strict'

import React from 'react'

var Title = React.createClass({
  render: function () {
    return React.createElement('h1', null, 'Título')
  }
})

export default Title
```
Brackets show this error:

```
Expected an identifier and instead saw 'import'.import Title from './App'
ESLint (1): ERROR: Parsing error: The keyword 'import' is reserved   
```    

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @iFabrycio! Provavelmente faltou adicionar a configuração do babel, para reconhecer códigos ES6+ :)
Aqui no repositório tem os códigos usados na aula. Compare para ver qual parte da configuração faltou:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

**Comment by fdaciuk** [comment]
Detalhe importante: veja a última linha que você mandou: a mensagem é referente ao ESLint, mas nesse momento, ainda não configuramos o linter na aplicação.

Dê uma olhada se o seu editor tem alguma configuração de lint, que pode estar exibindo essa mensagem :)

O ideal é que o linter seja configurado por projeto, não direto no seu editor, pois essas configurações podem variar de projeto para projeto :)
