### ISSUE TITLE
M1#A06

### ISSUE THREAD

**Issue by pissulin** [da2k/curso-reactjs-ninja#297]
Tentei instalar a versão correta do react do video , porem não tem mais suporte e estou com dificuldade para prosseguir com os exemplos.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pissulin! Não entendi muito bem sua dúvida. No site do [cdnjs](https://cdnjs.com/libraries/react) tem todas as versões do React disponíveis para uso :)

Consegue me mostrar o seu código pra eu ver como você está tentando fazer?
