### ISSUE TITLE
M2#A31: Versões raw e style loader

### ISSUE THREAD

**Issue by waldrey** [da2k/curso-reactjs-ninja#298]
Não sei se todos vão ter mesmo problema, mas quando instalei o **raw-loader** e **style-loader** sem informar a versão que foi utilizada não estava funcionando o CSS. Não sei se é necessário mas para evitar isso no futuro seria bom colocar no arquivo de versões de dependências.

**raw-loader**
```bash
npm install --save-dev raw-loader@0.5.1
````
**style-loader**
```bash
npm install --save-dev style-loader@0.13.1
````

Estava usando raw-loader@2.0.0 e style-loader@0.23.1

@fdaciuk

**Comment by waldrey** [comment]
Aproveitando issue criada, na aula **M2#A33** apresenta a mesmas falhas por causa das novas versões

**extract-text-webpack-plugin**
```bash
npm install --save-dev extract-text-webpack-plugin@1.0.1
```

**Comment by fdaciuk** [comment]
Perfeito @waldrey! Já está adicionado :)
Muito obrigado \o/

**Comment by TMiranda7** [comment]
Brooother , valeu mermo, desde ontem q to quebrando cabeça aqui ,

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Que bom que resolveu :)
A dica é ficar sempre de olho no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), pois lá tem as versões corretas que você consegue seguir sem problemas :)
