### ISSUE TITLE
Quais plugins você usa no Vim?

### ISSUE THREAD

**Issue by danvitoriano** [da2k/curso-reactjs-ninja#3]

**Comment by fdaciuk** [comment]
Fala @danvitoriano! =)
As minhas configurações eu passei no módulo onde falamos sobre React + Webpack, logo após a aula 6. Mas elas estão todas aqui nesse repositório. Você encontra nesse link: https://github.com/da2k/curso-reactjs-ninja/tree/master/config

Qualquer dúvida me avise =)

**Comment by danvitoriano** [comment]
Cool! Não tinha chegado nessa parte :) Tks!
