### ISSUE TITLE
M1#A06

### ISSUE THREAD

**Issue by edusites** [da2k/curso-reactjs-ninja#300]
Olá Daciuk,

Fui importar o React e React DOM dos links mais atualizado assim como manda a documentação no link: https://pt-br.reactjs.org/docs/cdn-links.html porém ao executar meu script ele dá a seguinte mensagem:

Inline Babel script:3 Uncaught TypeError: React.createClass is not a function

Pelo que entendi os scripts não estão reconhecendo a função createClass e fiz um teste com as bibliotecas demonstrada no curso e funciona normalmente, só estou abrindo essa issue devido agente sempre querer instalar modulos ou scripts atualizado.
 
```
<!DOCTYPE html>
<html>
<head>
<title>Criando meu 1 componente JSX</title>
</head>
<body>

<div id="app"></div>

<script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
<!--  Adicionando suporte ao JSX para criar elementos JS com sintaxe parecida com HTML -->
<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

<!--  Agora para criar elementos JSX criamos script JS do type babel -->
<script type="text/babel">
    
  const Title = React.createClass({
    render: function () {
      return (
        <h1>
          <span>Hello World Title</span>
        </h1>
      )
    }
  })

  ReactDOM.render(
      <Title />,
      document.getElementById('app')
    )

</script>
</body>
</html>

```
![Captura de Tela 2019-04-08 às 21 15 51](https://user-images.githubusercontent.com/32807316/55765022-31b91580-5a44-11e9-8e78-5c09b02570c5.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edusites! O createClass foi removido da lib principal, para ser adicionado a uma lib à parte.
Para seguir acompanhando com os exemplos que eu mostro nas aulas, pode usar as mesmas versões que eu estou usando, pois os conceitos que você irá aprender se aplicam inclusive às versões mais recentes :)

Algumas coisas apenas mudaram de lugar, como o createClass e o PropTypes, mas os conceitos são os mesmos! Então não se preocupe com versões no início. Após finalizar o módulo 2, você já terá um conhecimento suficiente de como o React funciona, e poderá usar as versões mais atuais sem problema algum :)

Se algo realmente mudar, fique tranquilo que eu vou mantendo o curso atualizado =)

E conte comigo para o que precisar :)

**Comment by edusites** [comment]
Obrigado @fdaciuk tenho mais uma dúvida, se eu não instalar o webpack de forma manual e partir com um create react app e seguir para a seção 3 em diante você acha que eu posso me atrapalhar adiante? ou com o create react consigo acompanhar as aulas?

**Comment by fdaciuk** [comment]
Oi @edusites! Pode usar o create-react-app, e pular as partes onde eu mostro as configurações sem problemas :)

Só fique atento às diferenças de versões das libs, que pode acontecer de ter alguma coisa ou outra diferente, mas você deve conseguir seguir sem problemas com o CRA sim :)
