### ISSUE TITLE
Novos Módulos

### ISSUE THREAD

**Issue by ederfleming** [da2k/curso-reactjs-ninja#304]
Bom dia Fernando!
Acabei de adquirir o curso de React enquanto finalizo o de Javascript.
Pelo que vi no README, ainda faltam 2 módulos do curso para serem lançados?

Se for isso, teremos acesso aí que você disponibilizar?
Teria previsão para o lançamento dos módulos 5 e 6?

Muito obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ederfleming! Os módulos do curso são independentes:
- Os módulos 1 e 2 são especificamente sobre o React, configurações, testes, criação de componentes e aplicações simples;
- O módulo 3 é sobre Redux;
- O módulo 4, que está sendo desenvolvido no momento, é sobre SPAs com React Router (aplicações mais complexas), onde estamos desenvolvendo uma aplicação de pizzaria :)

Assim que terminarmos o 4, vou começar a gravar o módulo de atualizações com o que tem de novidades até aqui no React (algumas coisas já estamos vendo no módulo 4, conforme vamos usando na aplicação de Pizzaria, mas veremos com mais detalhes no módulo de atualizações).

Depois disso, vou preparar um curso de Node, que vai dar uma base boa para iniciar o módulo 5, que será sobre SSR :)

Então a ideia é manter esse curso sempre vivo e atualizado. Por isso eu deixei separado em módulos: assim você pode estudar o que você precisa no momento, de forma independente, sem se preocupar em seguir uma ordem específica de estudos (apenas pegue um módulo e vá com ele até o fim), que você sempre vai estar por dentro das novidades que surgirem na lib :D

**Comment by alexandreolavio** [comment]
Olá Daciuk,
Terminei o módulo 4 com as pendências do projeto da pizzaria. Vc teria uma data para lançar o término do projeto?

**Comment by fdaciuk** [comment]
Oi @alexandreolavio! Essa semana já vou lançar mais aulas :D

**Comment by trooper26** [comment]
Boa noite, @fdaciuk. Aproveitando este tópico aberto, gostaria de perguntar se existe previsão para liberação da parte administrativa do projeto Reactzzaria (módulo 04) para cadastros internos utilizando API. Comprei o curso com um valor de investimento significativo, finalizei o curso até a aula 404 ("client-side") e percebo que há bastante tempo não existe nenhuma atualização de novas aulas. 
O curso está satisfatório, porém a falta dessas aulas estão me prejudicando. 
Aguardo feedback.

Obrigado.

**Comment by fdaciuk** [comment]
Oi @trooper26! Estou tentando liberar aulas semanalmente, mas nas últimas semanas fiquei impossibilitado de gravar, pois estava sem voz por conta de uma gripe :)
Mas essa semana já vou voltar a liberar as aulas semanalmente :)

Estamos quase finalizando a parte de Pedidos, e logo vamos entrar na parte de Cadastro!

Qualquer dúvida que você tenha, fique à vontade para perguntar, estou à disposição :)

**Comment by pedrokohler** [comment]
Boa noite, @fdaciuk tudo bem?

Já terminei tudo que está lá no curso até hoje.

Como ficamos sabemos quando você lançar novos módulos? No caso, sou aluno da Udemy. Acho que não recebo nenhum e-mail de vocês por lá.

Obrigado pela resposta!

**Comment by fdaciuk** [comment]
Oi @pedrokohler! Que legal que finalizou \o/ 

Eu envio as comunicações direto pela Udemy mesmo. Inclusive, na semana passada, eu mandei uma mensagem por lá, que deveria ter ido para o e-mail de todos os alunos, avisando que muito em breve eu devo subir as últimas aulas do módulo 4, que é o sistema de cadastro das pizzas. 

Se você não recebeu na sua caixa de entrada, dá uma olhada na sua caixa de spam, ou promoções, se você usa o Gmail, ou ainda lá na Udemy mesmo, que deve estar lá na área de notificações :)

Finalizando isso eu já vou começar a preparar o conteúdo para atualizar os primeiros módulos, pra mostrar tudo o que tem surgido de novo no React :D
