### ISSUE TITLE
M2#A58 - Sass + Storybook: Unexpected character '@'

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#305]
Oi professor.

Estou com problemas em fazer o `webpack.config.js` do storybook reconhecer os `.scss`.  

Tentei, de forma manual, fazer a implementação do loader:

```javascript
  newConfig.module.rules = (newConfig.module.rules || []).concat([{
    test: /\.scss$/,
    exclude: /node_modules/,
    include: path.join(__dirname, '..', 'src'),
    use: ['style-loader', 'css-loader?modules', 'sass-loader']
  }])
```

Só que os erros 'Unexpected character '@' (1:0)' e 'You may need an appropriate loader to handle this file type.' continuam sendo exibidos no terminal. Você poderia dizer onde estou errando? 

Case seja necessário, o repo da aplicação é [este](https://github.com/Roger-Melo/codepen/tree/master/06-github-app). Desde já, obrigado. 

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @Roger-Melo! Olhando seu projeto, você está usando uma versão do storybook que ainda usa a v1 do webpack. Essa versão não tem a entrada `rules`, e sim `loaders` :)

`rules` é à partir da v2 :)

**Comment by Roger-Melo** [comment]
Funcionou, professor!

Também acabei de resolver um outro percalço graças à um vídeo seu, Workflow CSS nos dias atuais. Obrigado! =)

@fdaciuk

**Comment by fdaciuk** [comment]
Show! Qqualquer coisa, só avisar :D
