### ISSUE TITLE
Dúvida sobre CRA e serviceWorker

### ISSUE THREAD

**Issue by VagnerNico** [da2k/curso-reactjs-ninja#306]
Bom dia @fdaciuk 
Talvez a pergunta fuja um pouco do escopo. Eu fiz um refactory de uma aplicação em Django + jQuery e utilizei um SW com o manifest para servir a aplicação como PWA. No refactory migrei para Django Rest + React utilizando o CRA, o CRA gera um SW que faz o cache da aplicação perfeitamente, maravilha até aqui. O problema surgiu quando tentei adicionar os event listeners para push, notificationclick, etc. Não consigo adicionar isso ao SW, existe alguma maneira de integrar o push notification ao SW gerado pelo CRA ou a melhor prática seria ejetar o CRA?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @VagnerNico! Não vou conseguir te responder com precisão pois ainda não fui a fundo nessa feature :)
Mas achei um artigo que talvez possa ajudar:
https://medium.com/founding-ithaka/implementing-push-notifications-with-create-react-app-bf35cd25d870

:)

**Comment by VagnerNico** [comment]
Show vou ver esse artigo, mas estou suando pra tentar resolver o problema hehehehehe
Não quero ejetar para não perder os benefícios do CRA.
Muito obrigado, e novamente queria dar os parabéns pelo melhor curso de React, recomendo pra todo mundo!

**Comment by fdaciuk** [comment]
Show @VagnerNico! Existem algumas ferramentas que te ajudam a mexer nas configs do CRA sem precisar ejetar, como o [rescripts](https://github.com/harrysolovay/rescripts), que eu mostrei no módulo 4.

Só não sei se ele tem alguma solução pra isso que você precisa, tem que dar uma olhada na documentação :)

Enfim, qualquer coisa que eu puder ajudar, só avisar :)

**Comment by VagnerNico** [comment]
Somente para compartilhar com o pessoal que enfrentar esse problema, consegui estender o service worker do CRA seguindo a ideia desse [link](https://karannagupta.com/using-custom-workbox-service-workers-with-create-react-app/).

**Comment by fdaciuk** [comment]
Perfeito @VagnerNico! Vou deixar a issue marcada como dica :D
Obrigado :)
