### ISSUE TITLE
Teste no arquivo action-creators.js

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#307]
É possível testar as funções que criamos no arquivos action-creators.js? 
Se sim teria um exemplo ou algum artigo que posso seguir, pq esta me incomodando rodar o teste de coverage e falar que esse arquivo não tem teste rsrs

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Sempre dá :)
Você pode escrever testes para as funções usadas nos action creators, já que eles simplesmente abstraem o objeto que passaríamos para o `dispatch` :)

Para action creators que não têm ações assíncronas, pode escrever _unit tests_ sem problemas.

Para os que são assíncronos, não precisa se preocupar em deixar 100% de cobertura de testes unitários, pois são outros tipos de testes que irão cobrir esse tipo de função, já que, para escrever testes unitários, você teria que mockar informações do redux (como o dispatch), por exemplo, e chamadas de API :)

Para esses casos, é melhor escrever testes de integração, ou ainda testes E2E, testando direto as ações na tela :)

**Comment by hjdesigner** [comment]
Desculpa te incomodar mais um pouco com isso mais estou a dias tentando fazer os testes no action-creatos mais sem sucesso.

Peguei alguns artigos na internet e até funcionou, só que quando tento aplicar no formato que é ensinado no curso não consigo fazer funcionar.

Teria como você criar um exemplo de como séria esses testes para que eu possa seguir?

**Comment by fdaciuk** [comment]
Me mostra o seu projeto, pra eu ver o que você está tentando testar. Assim fica mais fácil entender o problema :)

**Comment by fdaciuk** [comment]
E relaxa, não é incômodo nenhum: qualquer dúvida, pode perguntar à vontade :D

**Comment by hjdesigner** [comment]
Não consigo compartilhar o projeto porque é um projeto privado do serviço :(

Segue o arquivo action-creators.js

```
import instance from 'utils/request';
import config from 'utils/config';
import {
	GET_INFORMATION,
	LOADING_INFORMATION,
	ERROR_INFORMATION,
	FILTER_CANDIDATES,
} from './actions';


export const filterCandidates = values => (dispatch) => {
	dispatch({
		type: FILTER_CANDIDATES,
		payload: {
			filter: values,
		},
	});
};

export const getCandidate = id => (dispatch) => {
	instance.get(`/vagas/${id}/candidatos?per_page=10&page=1`, { baseURL: config.REACT_APP_BASE_URL })
		.then((response) => {
			dispatch({
				type: GET_INFORMATION,
				payload: {
					data: response.data.candidatos,
					total: response.headers['x-total'],
				},
			});
			dispatch({ type: LOADING_INFORMATION });
		}).catch(() => {
			dispatch({ type: ERROR_INFORMATION });
		});
};
```

Segue  index.js

```
import {
	GET_INFORMATION,
	LOADING_INFORMATION,
	ERROR_INFORMATION,
	FILTER_CANDIDATES,
} from './actions';
import createReducer from '../create-reducer';

const initialState = {
	loading: true,
	error: false,
	total: '',
	data: [],
	filterCandidates: '',
};

function toggleBool(state) {
	const newState = !state;
	return newState;
}

const candidateInformation = createReducer(initialState, {
        [FILTER_CANDIDATES]: (state, action) => ({
		...state,
		filterCandidates: action.payload.filter,
	}),
	[LOADING_INFORMATION]: state => ({
		...state,
		loading: toggleBool(state.loading),
	}),
        [ERROR_INFORMATION]: state => ({
		...state,
		loading: false,
		error: true,
		data: [],
	}),
        [GET_INFORMATION]: (state, action) => ({
		...state,
		error: false,
		data: action.payload.data,
		total: action.payload.total,
	}),
});

export default candidateInformation;
```

**Comment by fdaciuk** [comment]
Legal, deu pra entender melhor seu contexto :)
Bom, você não vai conseguir fazer testes unitários em alguns action creators por alguns motivos:
- testes unitários dependem que a função testada seja pura: receba uma entrada, processe e devolva uma saída, sem modificar ou usar informações / dados / libs externas;
- pra tentar chegar mais perto de testes unitários, você teria que mockar algumas funções (como o `dispatch`), o objeto de configuração que você está importando e a Promise `instance`.

Não recomendo usar mocks, pois, além de não ser um caminho ideal, pois você tem que escrever muito código apenas pra tentar simular uma funcionalidade de forma fake, esses testes ainda podem te dar falsos positivos: se algo for alterado na forma como a promise responde, por exemplo, mas não mudar nada no seu código, seu teste pode passar quando ele deveria quebrar.

Nesse caso, a melhor forma de fazer esse tipo de teste, seria o seguinte:

**Testes de integração:**

Você pode sempre injetar na função os dados de configuração e a promise `instance`. Dessa forma, você consegue injetar esses valores tanto no seu código, quanto no teste, garantindo assim o retorno correto.

**Testes E2E (End to End)**

São testes que testam o "final" da sua aplicação. Normalmente simulando a ação do usuário mesmo, que vai ter que passar por esse código dos action creators. Dessa forma, você consegue validar em tela se o resultado é realmente o esperado.

---

Tanto testes de integração como E2E são mais "custosos" para escrever, e não são 100% confiáveis, pois dependem principalmente de Network ou algum serviço externo, o que faz com que algumas vezes os testes passem, outras falhem, por conta exatamente dessas dependências externas.

Mas para os casos onde você precisa testar integrações assim, não tem muito o que fazer. 

Já os Testes Unitários são fáceis de escrever, e são totalmente confiáveis no ambiente que eles precisam testar, pois testam funções puras (apenas entrada e saída de dados síncronos). Mas eles não garantem que sua aplicação está corretamente integrada com outros serviços, ou conversando / respondendo corretamente a serviços externos.

Então é preciso balancear os testes: escreva testes unitários para funções puras, isolando o máximo que você conseguir, e fazendo o máximo de testes unitários que conseguir, já que eles rodam bem rápido, normalmente.

O que você não conseguir testar com Testes Unitários, aí você pode tentar escrever um teste de integração ou E2E, e assim você garante o máximo de cobertura de testes, para tentar garantir o máximo do funcionamento da sua aplicação :)
