### ISSUE TITLE
M2#A71 - Problemas para obter o header link

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#308]
Oi Professor! 

Você mostrou como obter os headers da resposta para a requisição que está sendo feita para a API do GitHub. Só que o header `link` não está vindo como resposta:

```
x-ratelimit-limit: 60
x-github-media-type: github.v3; format=json
x-ratelimit-remaining: 53
last-modified: Fri, 22 Mar 2019 18:33:15 GMT
etag: W/"e5684ef70df3a4d3a16b92c815666af2"
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
x-ratelimit-reset: 1555698133
```

Olhei na [doc da API](https://developer.github.com/v3/#link-header) e não encontrei um aviso dizendo que esse header foi removido da resposta. Preciso obtê-lo para conseguir gerar o número total de páginas do componente de paginação. Ou há outra forma? 

Se for necessário ver o código, o repo está [aqui](https://github.com/Roger-Melo/codepen/tree/master/06-github-app). Obrigado desde já. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! É isso mesmo. Quando tem só uma página, ele não envia o header Link :)

**Comment by Roger-Melo** [comment]
> Oi @Roger-Melo! É isso mesmo. Quando tem só uma página, ele não envia o header Link :)

Na verdade eu estava especificando a invocação do método de pegar os headers dentro da declaração de um método nada haver. My mistake, fessor. Valeu! 

@fdaciuk

**Comment by fdaciuk** [comment]
Saquei! Bom, qualquer coisa, só avisar :)
