### ISSUE TITLE
M1#A45

### ISSUE THREAD

**Issue by edusites** [da2k/curso-reactjs-ninja#309]
Olá Daciuk,

Estou com a seguinte dificuldade, iniciei uma propriedade chamada button para passar as propriedades do meu HTML de forma dinâmica conforme esse objeto. porém ao clickar no botão ver repositorios que dispara o método getRepos dá a seguinte mensagem ao tentar atualizar o state button:
TypeError: Cannot read property 'isDisabled' of undefined
Saberia informar onde estou errando?

```jsx
'use strict'

import React from 'react'
import AppContent from './m1_45/components/AppContent'
import axios from 'axios'

class App extends React.Component{

  constructor(){
    super()
    this.state = {
      userInfo : null,
      repos : [],
      starred : [],
      button : {
        repositorios : {
          isDisabled : false,
          text : 'Ver Repositórios'
        },
        favoritos : {
          isDisabled : false,
          text : 'Ver Favoritos'
        }
      }
    }
  }
  // Função que está sendo importada para Search.js
  handleSearch = (e) => {
    console.log('handleSearch',e.target.value)
    const keyCode = e.which || e.keyCode
    const ENTER = 13
    if(keyCode === ENTER){
      axios({
        method : 'get',
        url : `https://api.github.com/users/${e.target.value}`
        // data: {
        //   name: 'Carlos', // Parâmetro 1 enviado
        //   company: 'EspecializaTi' // Parâmetro 2 enviado
        // }
      }).then(result => {
        const usuario = result.data
        this.setState({
          userInfo : {
            name : usuario.name,
            image : usuario.avatar_url,
            login : usuario.login,
            repos : usuario.public_repos,
            followers : usuario.followers,
            following : usuario.following
          },
          repos : [],
          starred : [] 
        })
        console.log(usuario)
      }).catch(error => {
        throw `Erro na busca ${error}`
      })
    }
    //console.log('code', keyCode)
  }

  getRepos = (e) => {
    //console.log('getRepos',e)
    //const evento = e.target
    const user = this.state.userInfo.login || 'daciuk' 
    axios.get(`https://api.github.com/users/${user}/repos`)
    .then(result => {
      //console.log(result);
      this.setState({
        repos : result.data,
        button : {
          repositorios : {
            text : 'Seus Repositórios',
            isDisabled : true
          }
        }
      })
      ///console.log(evento.innerHTML)
    }).catch( error => {
      throw `Erro na busca dos Repositórios ${error}` 
    })
    

  }

  getStarret = () => {
    const user = this.state.userInfo.login || 'daciuk'
    axios.get(`https://api.github.com/users/${user}/starred`)
    .then(result => {
      //console.log(result)
      this.setState({
        starred : result.data,
        button : {
          favoritos : {
            text : 'Seus Favoritos',
            isDisabled : true
          }
        }
      })
    }).catch(error => {
      throw `Erro na busca dos Favoritos ${error}`
    })
    
  }

  render(){
    return(
      <AppContent 
        userInfo={this.state.userInfo}
        repos={this.state.repos}
        starred={this.state.starred}
        handleSearch={ (e) => this.handleSearch(e) }
        getRepos={(e) => this.getRepos(e)}
        getStarret={this.getStarret}
        propButtons={this.state.button}/>
    )
  }
}

export default App
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edusites! Provavelmente o seu problema é que, quando você vai atualizar os valores da propriedade `button` no estado, você cria um novo objeto, sobrescrevendo o anterior, sem manter todas as propriedades dele.

Ao usar o `setState`, você consegue atualizar um ou outro valor no state, desde que esse valor esteja no primeiro nível do objeto do estado.

Já o valor de `button` é um segundo nível de objeto, então você precisa, manualmente, copiar os valores anteriores desse objeto antes de atualizar o valor dele.

Para fazer isso da forma correta, eu mostrei na aula 92 do módulo 2. Dá uma olhada nessa aula que vai ficar fácil entender o que você precisa fazer para esse seu código funcionar como você espera :)

**Comment by edusites** [comment]
Olá @fdaciuk,

Obrigado pela prontidão, estou curtindo bastante seu curso e estou recomendando nos grupos de facebook sempre que há uma discussão sobre melhores cursos de react, mas vamos lá, se entendi quando você fala em "copiar os valores anteriores do objeto antes de atualizar" eu acesso os valores atuais do state dentro de setState e atribuo seus novos valores, fiz isso com base na aula que me indicou para assistir e funcionou 👍 , estou colando o código abaixo, seria isso mesmo? ou daria para melhorar?

`'use strict'

import React from 'react'
import AppContent from './m1_45/components/AppContent'
import axios from 'axios'
/**
 * Atualizando o state do componente getRepos 
 * passando uma função de callBack como primeiro parametro
 * ao setState((state) =>()) onde seu primeiro parametro representa
 * o state atual do componente, e a partir dele devemos pegar
 * os valores atualizado das propriedades mesmo estando circulando
 * e sendo atualizado por varios componentes diferentes.
 * Isso se faz necessário por setState ser uma função assincrona
 * e o sincronismo de seu retorno não deve seguir um fluxo linha apos linha
 * por isso a função de callBack. Outro ponto importante é que dentro dela
 * devemos pegar seus valores com state.prop e não this.state.prop por causa
 * que state.prop representa o retorno da propriedade no callBack já this.state.prop
 * representa o valor da propriedade no componente atual do objeto podendo conter um
 * valor desatualizado.
 */
class App extends React.Component{

  constructor(){
    super()
    this.state = {
      userInfo : null,
      repos : [],
      starred : [],
      button : {
        repositorios : {
          isDisabled : null,
          text : 'Ver Repositórios'
        },
        favoritos : {
          isDisabled : null,
          text : 'Ver Favoritos'
        }
      }
    }
  }
  // Função que está sendo importada para Search.js
  handleSearch = (e) => {
    console.log('handleSearch',e.target.value)
    const keyCode = e.which || e.keyCode
    const ENTER = 13
    if(keyCode === ENTER){
      axios({
        method : 'get',
        url : `https://api.github.com/users/${e.target.value}`
        // data: {
        //   name: 'Carlos', // Parâmetro 1 enviado
        //   company: 'EspecializaTi' // Parâmetro 2 enviado
        // }
      }).then(result => {
        const usuario = result.data
        this.setState({
          userInfo : {
            name : usuario.name,
            image : usuario.avatar_url,
            login : usuario.login,
            repos : usuario.public_repos,
            followers : usuario.followers,
            following : usuario.following
          },
          repos : [],
          starred : []
        })
        console.log(usuario)
      }).catch(error => {
        throw `Erro na busca ${error}`
      })
    }
    //console.log('code', keyCode)
  }

  getRepos = (e) => {
    //console.log('getRepos',e)
    //const evento = e.target
    const user = this.state.userInfo.login || 'daciuk' 
    axios.get(`https://api.github.com/users/${user}/repos`)
    .then(result => {
      //console.log(result);
      this.setState((state) => {
        state.button.repositorios.isDisabled = true
        state.button.repositorios.text = 'Seus repositórios'
        return {repos : result.data}
      })
      console.log(this.state.button.repositorios.isDisabled)
    }).catch( error => {
      throw `Erro na busca dos Repositórios ${error}` 
    })
  }

  getStarret = () => {
    const user = this.state.userInfo.login || 'daciuk'
    axios.get(`https://api.github.com/users/${user}/starred`)
    .then(result => {
      //console.log(result)
      this.setState( (state) => {
        state.button.favoritos.isDisabled = true
        state.button.favoritos.text = 'Seus favoritos'
        return {starred : result.data}
      })
    }).catch(error => {
      throw `Erro na busca dos Favoritos ${error}`
    })
    
  }

  render(){
    return(
      <AppContent 
        userInfo={this.state.userInfo}
        repos={this.state.repos}
        starred={this.state.starred}
        handleSearch={ (e) => this.handleSearch(e) }
        getRepos={(e) => this.getRepos(e)}
        getStarret={this.getStarret}
        propButtons={this.state.button}/>
    )
  }
}

export default App
`
![Captura de Tela 2019-04-21 às 20 12 17](https://user-images.githubusercontent.com/32807316/56476768-629d3f80-6473-11e9-80b2-7312d1e3107d.png)

**Comment by fdaciuk** [comment]
Legal @edusites! É mais ou menos isso.. você só não pode modificar manualmente o objeto de estado: sempre que precisar modificar algum objeto, faça um cópia do mesmo, criando uma nova referência, antes de modificar o que for necessário :)

Exemplo:

Ao invés de fazer:

```js
      this.setState((state) => {
        state.button.repositorios.isDisabled = true
        state.button.repositorios.text = 'Seus repositórios'
        return {repos : result.data}
      })
```

Crie sempre novos objetos, e então atualize o que for necessário:

```js
      this.setState((state) => {
        return {
          repos: result.data,
          // aqui criamos um novo objeto para passar para o state.button
          button: {
            // aqui nós copiamos tudo o que já tinha antes em state.button
            ...state.button,
            // e então modificamos os valores apenas dentro do novo objeto:
            repositorios: {
              // como aqui também temos um novo objeto, para garantir que, se ele tiver mais propriedades, essas vão se manter, e só isDisabled e text serão modificadas, copiamos o que está em state.button.repositorios aqui pra dentro:
              ...state.button.repositorios,
              isDisabled: true,
              text: 'Seus repositórios'
            }
          }
        }
      })
```

Sacou a ideia? :)

**Comment by edusites** [comment]
Sim, @fdaciuk entendi, muito obrigado!

**Comment by fdaciuk** [comment]
Perfeito! Fique tranquilo que, no decorrer do curso, nós vamos ver outros tipos de aplicações, e várias outras formas de lidar com estruturas de dados =)

Qualquer dúvida, só avisar =)
