### ISSUE TITLE
M1#A33 

### ISSUE THREAD

**Issue by romulotunala** [da2k/curso-reactjs-ninja#312]
# Resolvendo a questão do setState assíncrono.

Uma opção para esse segundo parametro, ou seja a função de callback, eu uso o parâmetro `prevState`. 
É uma opção boa ou não? Vc tem algo para apontar aqui? 
Não testei nesta situação específica, mas já usei so prevState e resolvi.

Queria sua opnião. Tenho sempre a preocupação de escolher a melhor opção.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @romulotunala! Sim, passando uma função para o setState é a melhor forma de modificar um estado baseado no seu valor anterior, ou ainda quando precisamos executar vários setState's seguidos :)

Mas vamos falar sobre isso ainda, no módulo 2 :)
