### ISSUE TITLE
M2#A85 - O método minChunks do CommonsChunkPlugin, no Windows

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#314]
Oi professor!

Gostaria apenas de fazer uma observação; para que esse método do CommonsChunkPlugin funcionasse foi necessário criar uma propriedade `react` no objeto o `paths` do common.js, pois 'node_modules/react' não funciona no windows, devido à barra. 

```js
// common.js
const paths = {
  // paths anteriores omitidos
  react: join(__dirname, '..', 'node_modules', 'react')
}
```

```js
// prod.config.js
    new webpack.optimize.CommonsChunkPlugin({
      name: 'react-build',
      minChunks: ({ resource }) => resource.includes(common.paths.react)
    }),
```

Preferi criar esse path no common ao invés de importar o `join` no `prod.config.js` ou utilizar `node_modules\\react`.  

Enfim, caso alguém passe pelo mesmo problema (no windows), é uma solução possível.  

@fdaciuk

**Comment by fdaciuk** [comment]
Perfeito @Roger-Melo! Obrigado pela dica! Já deixei a issue marcada :)
Vou pegar essas dicas daqui do repo e vou criar aulas do futuro, pra adicionar no curso. Acho que fica mais fácil pra quem estiver passando alguns problemas :D
