### ISSUE TITLE
Problema na Udemy: Erro no título de algumas aulas

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#315]
Oi professor. O título de algumas aulas está sendo exibido apenas tooltip do hover. Length do título, talvez?

![image](https://user-images.githubusercontent.com/29297788/56842880-a5468980-6870-11e9-8584-fede2ad24a61.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Eita! Vou reportar pra eles, obrigado :)
Se puder fazer também, quanto mais gente avisar do problema, mais eles agilizam pra arrumar :)

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Fiz alguns testes aqui modificando o tamanho da tela, e ele realmente mostra só os 3 pontinhos.. mas ao atualizar a tela, sem redimensionar, não dá esse problema. Confere pra mim, por favor, se isso acontece com você também?

Bom, de qualquer forma, vou fechar a issue porque é um problema específico da Udemy, vamos ver se eles resolvem :)

Obrigado por reportar :D

**Comment by Roger-Melo** [comment]
Oi professor. Verifiquei aqui e parece que o problema foi corrigido. As reticências estão inseridas apenas no fim dos títulos maiores, como o esperado =)

@fdaciuk

**Comment by fdaciuk** [comment]
Show! :D
