### ISSUE TITLE
M1#A46 - GitHub App: adicionando states de feedback

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#316]
Oi professor!

Estou aqui pensando com meus botões como adicionar mais states na GitHub App. Explico:  

Eu gostaria que, o componente abaixo do `Search` tivesse 3 states:  

![github app – Figma](https://user-images.githubusercontent.com/29297788/57196718-de988c80-6f35-11e9-8ab6-9b2ad2b842b9.jpg)

Atualmente, o código do `AppContent` está assim: 

```javascript
    {!!userinfo || <EmptyState />}
    {isFetchingData && <div>Loading</div>}
```

Estou pensando em renomear esse `<EmptyState />` (que é o state inicial, "welcome") e fazer com que ele lide com esses 3 states (que terão a mesma marcação e estilo, modificando apenas os ícones e textos).  

Esse mindset está de acordo com o fluxo unidirecional do React? E se sim, seguindo essa linha de pensamento, `userinfo` deveria ser um 4º state desse componente, mesmo que não tenha o markup e estilo dos outros 3 states?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Na verdade, o fluxo unidirecional é apenas para dizer que as informações vêm sempre de cima, de um componente pai, e vai passando para os filhos mais abaixo, nunca o contrário :)

Isso que você precisa fazer é apenas uma regra de componentização. Não vejo problemas em fazer dessa forma. O que eu te recomendaria é: faça como você está pensando, e dê uma olhada no código, e veja se ele está descritivo o suficiente.

Se faz sentido o que está acontecendo (talvez mostrar para outras pessoas opinarem depois de pronto pode te ajudar com isso) :)

Pode até criar uma issue aqui quando fizer isso, que eu te digo se poderia melhorar algo :)

Mas a forma de fazer isso fica totalmente a seu critério :)

**Comment by Roger-Melo** [comment]
Show, professor. 

Já comecei a esboçar no papel as possibilidades. Quando eu codar, abro a issue. Muito obrigado =D

@fdaciuk

**Comment by fdaciuk** [comment]
Perfeito :D
