### ISSUE TITLE
CRA Tree Shaking

### ISSUE THREAD

**Issue by dtodt** [da2k/curso-reactjs-ninja#317]
Fala professor, tudo certo?

Seguinte, é mais uma duvida mesmo, tenho visto nas aulas do modulo 4, que vc usa os `export default` normalmente.

Lembro de ter lido que pra funcionar o `tree shaking` e os lazy direito, tinha que utilizar export nomeado. Caiu essa definição já ?

Para que eu consiga utilizar o `React.lazy`, tenho feito assim:

##### /components/todo-item/todo-item.js
```javascript
import React from 'react'
import t from 'prop-types'

const TodoItem = ({ todo }) => {
  return <li>...</li>
}
TodoItem.propTypes = {
  todo: t.object.isRequired
}

export { TodoItem }
```

##### /components/todo-item/index.js
```javascript
export { TodoItem as default } from './todo-item'
```

Muda alguma coisa ou é só codigo a mais?

Valeu!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @dtodt! O _tree shaking_ acontece quando você tem mais de um export independente no mesmo arquivo. Exemplo:

**./numbers.js**

```js
export const one = () => 1
export const two = () => 2
```

E quando você importar só um deles:

```
import { one } from './numbers'
```

Só a função `one` vai ser adicionada no arquivo final, já que a `two` não foi utilizada.

Mas quando você tem apenas um único `export`, tanto faz se ele é nomeado ou _default_, não existe otimização a ser feita, já que, quando você importar, tudo o que está ali dentro vai ser usado :)

Ficou claro? :)

**Comment by dtodt** [comment]
Entendo, achei que era o export nomeado que fazia a delimitação entre os diversos chunks.

Então se eu tiver import lazy de arquivos separados por 'funcionalidade', o CRA vai criar um chunk por funcionalidade, independente de eu usar o export nomeado ou não.

**Comment by fdaciuk** [comment]
> Entendo, achei que era o export nomeado que fazia a delimitação entre os diversos chunks.

Na verdade, são dois conceitos / features / funcionalidades diferentes:
- os _chunks_ - que seriam pequenos pedaços de código em arquivos separados - são gerados quando usamos a função `import()`. Sempre que você importar algum módulo com a função `import`, esse módulo vai ser adicionado à um arquivo separado do bundle principal;

- já a ideia de _tree shaking_ só funciona com _exports_ nomeados mesmo: para fazer _tree shaking_, é necessário exportar funções independentes de forma nomeada. O conceito de _tree shaking_ é basicamente colocar no pacote final somente aquelas funções que foram importadas, se no mesmo arquivo de onde elas foram exportadas houverem outras funções; que se não forem importadas, não serão adicionadas ao pacote final :)

Não sei se eu consegui deixar claro a ideia dos dois conceitos, qualquer coisa só perguntar que eu tento explicar de outra forma :)

**Comment by fdaciuk** [comment]
> Então se eu tiver import lazy de arquivos separados por 'funcionalidade', o CRA vai criar um chunk por funcionalidade, independente de eu usar o export nomeado ou não.

Isso sim, já que, ao usar o `React.lazy`, ele espera que você importe o módulo com `import()` função. E o `import()` função faz com que o módulo seja adicionado à um arquivo separado.

E no caso do `React.lazy`, é obrigatório que o módulo seja exportado como `default` para funcionar corretamente, ao menos por agora :)

Mas qualquer módulo pode ser importado usando a função `import()`, inclusive trechos exportados de forma nomeada :)

**Comment by fdaciuk** [comment]
Só é importante frizar que o `import()` função não faz _tree shaking_, ele importa o conteúdo todo do arquivo, mas em um _chunk_, um arquivo separado.

O _tree shaking_ só acontece com o _import_ quando usado de forma estática :)

**Comment by dtodt** [comment]
Show, valeu ! :)

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :D
