### ISSUE TITLE
Renderizar duas vezes

### ISSUE THREAD

**Issue by andreclicksul** [da2k/curso-reactjs-ninja#318]
Olá Daciuk, blz

estou terminando o módulo 1 e já estou tb criando alguns app´s de teste, tenho algumas aplicações em jquery em que preciso renderizar informações em div´s diferentes. Gostaria de saber se tem como renderizar duas vezes. Na app de teste que estou trabalhando tenho um menu lateral esquerdo e tenho um menu de controle de usuários na parte superior direita do layout. Estes dois menus estão em div separadas, estou utilizando o react-router-dom para criar os links. Crio duas classes, tipo Menu1 e Menu2 e preciso renderizar os 2 componentes nas 2 div´s. Não sei se posso utilizar o ReactDOM.render duas vezes. Desde já agradeço pela ajuda.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @andreclicksul! Se a sua aplicação já está pronta, e funcionando com jQuery, e o que você quer fazer é migrar aos poucos para React, aí sim você pode usar dois ReactDOM.render para renderizar componentes específicos em partes específicas da sua aplicação.

Mas se o seu app está sendo pensado pra ser feito todo com React, o ideal é usar um só ReactDOM.render, e fazer toda a manipulação de como os componentes são exibidos, dentro do React ;)

No módulo 4 estou mostrando como usar o React Router. Se você já estiver conseguindo se virar bem com React, pode ver as aulas desse módulo para entender melhor como vai funcionar a ideia de trabalhar com "páginas" dentro de um app React :)
