### ISSUE TITLE
[M2#A08] - Erro ao executar comando

### ISSUE THREAD

**Issue by rafaelToz1989** [da2k/curso-reactjs-ninja#319]
Fala, Daciuk. Boa noite, tudo bem?

Instalando todas as dependências necessárias. ao tentar rodar o comando "npm test" ou mesmo o comando "npm run test:watch" ensinado nessa aula, é exibida a seguinte mensagem de erro, no console:

 FAIL  ./sum.test.js
  ● Test suite failed to run

    Plugin/Preset files are not allowed to export objects, only functions. In C:\Users\TOzi\Documents\udemy\reactNinja\m02\jest-in-practice\node_modules\babel-preset-es2015\lib\index.js

      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
          at Array.map (<anonymous>)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.825s
Ran all test suites related to changed files.

Já tentei rodar novamente o comando "npm install", mas sem sucesso. 
 
Você poderia me auxiliar com o problema em questão? Desde já agradeço e fico no aguardo da sua ajuda.

Grande abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafaelToz1989! Provavelmente o erro é por causa da sua versão do babel.
Instale a versão conforme mostrado [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que deve funcionar =)
Se continuar dando problemas, compartilhe comigo seu projeto, que eu coloco pra rodar aqui e te ajudo com isso, ok? :D

**Comment by rafaelToz1989** [comment]
> Oi @rafaelToz1989! Provavelmente o erro é por causa da sua versão do babel.
> Instale a versão conforme mostrado [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que deve funcionar =)
> Se continuar dando problemas, compartilhe comigo seu projeto, que eu coloco pra rodar aqui e te ajudo com isso, ok? :D

**Comment by fdaciuk** [comment]
Show de bola! Qualquer coisa, só avisar :)

**Comment by thallysbezerrarebel** [comment]
> Oi @rafaelToz1989! Provavelmente o erro é por causa da sua versão do babel.
> Instale a versão conforme mostrado [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que deve funcionar =)
> Se continuar dando problemas, compartilhe comigo seu projeto, que eu coloco pra rodar aqui e te ajudo com isso, ok? :D

Colocar as versões certas resolveu o meu problema :)
