### ISSUE TITLE
M2#A51 - Paginação - ambiente para testes - linter

### ISSUE THREAD

**Issue by hgtpcastro** [da2k/curso-reactjs-ninja#32]
Olá @fdaciuk, tudo bem?

Será que você consegue me ajudar? 

Obs.: Estou utilizando SO Windows 8 - 64 bits

Estou com problemas ao executar o Lint. Quando executo o comando: **yarn lint:watch**, o seguinte erro é exibido:

> yarn lint:watch v0.21.3
> $ gulp
> [08:06:43] Using gulpfile E:\react\cursos\da2k\curso-reactjs-ninja\examples\m02\applications\github-app\gulpfile.js
> [08:06:43] Starting 'lint'...
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn yarn ENOENT
>     at exports._errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> error Command failed with exit code 1.

**Comment by fdaciuk** [comment]
Fala @hgtpcastro! Consegue me dar mais detalhes do problema? O projeto que você está usando está no GitHub? Assim fica mais fácil ver se é algum problema de configuração, ou se é específico do windows =)

**Comment by hgtpcastro** [comment]
Então @fdaciuk, o projeto não esta no GitHub, porém o que eu fiz foi o seguinte: baixei os fontes diretamente do repositório para o meu pc e rodei o comando **yarn** no diretório do projeto para instalar as dependências, porém ao rodar o comando **yarn lint:watch**, da o erro.

Criar um fork do projeto do curso, seria a melhor forma de acompanhar? O que você me indica?

Desde já agradeço.

**Comment by fdaciuk** [comment]
@hgtpcastro a melhor forma de acompanhar seria ir acompanhando os códigos junto com as aulas, para ver a evolução. No caso do repositório, ele já está na versão mais recente, então tem coisas ali que você ainda não viu nas aulas =)

No teu caso, como está usando windows, pode ter alguns problemas diferentes, então é importante tentar instalar as coisas passo-a-passo para ver qual é o real problema. Mas pelo erro, parece que o `spawn` do node não conseguiu encontrar o comando `yarn`.

Qual terminal você está utilizando? Eu recomendo experimentar algum terminal que seja mais próximos do bash do unix.. o Console2 pode ser uma boa opção =)

**Comment by hgtpcastro** [comment]
Então @fdaciuk, a ferramenta que estou utilizando para acompanhar o curso é Visual Studio Code, e estou utilizando o próprio terminal do Visual Studio Code.

**Comment by fdaciuk** [comment]
Legal =)
Você tem o yarn instalado globalmente na sua máquina, certo? Você instalou ele via NPM ou com o instalador para windows?

Se foi pelo NPM, tente instalar pelo instalador pra ver se funciona: 
https://yarnpkg.com/en/docs/install#windows-tab

**Comment by fdaciuk** [comment]
@hgtpcastro conseguiu resolver?

**Comment by hgtpcastro** [comment]
Bom dia @fdaciuk 

Não te respondi antes pois tive que me ausentar... 

Então, instalei via npm.

Desinstalei o yarn via npm e fiz a instalação via pacote do windows (yarn-0.23.2.msi), mas infelizmente não obtive exito. O erro ainda persiste.

**Comment by hgtpcastro** [comment]
Boa tarde @fdaciuk

Consegui resolver o problema trocando o import do spawn no arquivo **gulpfile.js**: 

de

### **const { spawn } = require('child_process')**

por

### **const { spawn } = require('cross-spawn')**

Será que essa é a forma correta?

**Comment by fdaciuk** [comment]
Poxa, legal @hgtpcastro! O problema infelizmente é que no windows o `spawn` não funciona como deveria :|

Ainda bem que conseguiu achar uma boa solução :D 

Vou adicionar um comentário com essa dica no `gulpfile.js` para quem usa Windows \o/

**Comment by fdaciuk** [comment]
@hgtpcastro, bom, acho que o problema dessa issue foi resolvido né? =)
Vou fechar ela, mas se tiver qualquer dúvida, pode abrir outra, ok?

Se tiver relação com essa aqui, a gente abre ela novamente pra discutir e resolver :D

**Comment by hgtpcastro** [comment]
Valeu pela atenção @fdaciuk <https://github.com/fdaciuk>, muito obrigado.

A propósito, no curso iremos ver alguma coisa relacionado com
internacionalização de aplicações.

Você indicaria alguma biblioteca para internacionalização?

Valeu....

2017-04-18 15:51 GMT-03:00 Fernando Daciuk <notifications@github.com>:

**Comment by fdaciuk** [comment]
Talvez em algum projeto nós vamos falar sobre internacionalização, mas não é certo =)
A lib mais conhecido para isso é o [react-intl](https://github.com/yahoo/react-intl) =)
