### ISSUE TITLE
M1#A46 - GitHub App: implementando mais states

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#320]
Oi, professor! 

Fiz a adição dos estados na aplicação, como comentei [nessa issue](https://github.com/da2k/curso-reactjs-ninja/issues/316#issue-440461009). Você pode dar um feedback sobre o código? 

O [diff está aqui](https://github.com/Roger-Melo/codepen/commit/7dac2d725f889f485ba69587fa43046b1a140a60), acho que é mais fácil visualizar por ele =)  

Grande parte dele se deve ao fato de que movi alguns métodos para dentro do `constructor`. Depois irei mover o restante. 

@fdaciuk

**Comment by fdaciuk** [comment]
Show @Roger-Melo! Comentei lá no seu diff :)

**Comment by Roger-Melo** [comment]
Aaeeee, funcionou professor! Em breve subo no codepen e mostro como ficou. Muito obrigado! =)

Conforme fui codando surgiram outras dúvidas, você pode me dar um help? Vou postá-las  
separadas em issues. Se alguém buscar por tópicos parecidos, talvez a resposta seja apropriada =)

@fdaciuk

**Comment by fdaciuk** [comment]
Com certeza meu caro! Fique à vontade para perguntar :D 
Fico feliz em ajudar :)
