### ISSUE TITLE
M2#A45 - Erro ao carregar o CSS [Storybook]

### ISSUE THREAD

**Issue by rrmontuan** [da2k/curso-reactjs-ninja#322]
Tentei extender o webpack.config padrão porém quando rodo o comando `npm run storybook` o storybook acusa um erro na hora do build:

```
WARNING in ./~/@kadira/storybook/~/css-loader?importLoaders=1!./~/postcss-loader!./~/standard-loader!./src/components/actions/actions.css
<text>:1:1: Parsing error: Unexpected character '@'
```

Meu webpack.config extendido está dessa forma:

![storybook](https://user-images.githubusercontent.com/6073761/57695287-403ab400-7624-11e9-9ba8-cfbb4af1c82d.png)

Estou com o `getstorybook@1.6.1` instalado globalmente no Windows.

Só um detalhe: Quando eu executei o comando `getstorybook `ele falha para instalar as dependências (apesar dos outros checks estarem ok). Dai forcei pelo `npm install`.

![storybook2](https://user-images.githubusercontent.com/6073761/57695553-edadc780-7624-11e9-9d87-7d7900cbed6a.png)

Alguma dica do que poderia estar causando isso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rrmontuan! Consegue compartilhar comigo o repositório com esse código? Assim eu baixo aqui e vejo o que pode estar causando esse problema :)

**Comment by rrmontuan** [comment]
Boa tarde, Fernando!

o repositório é esse [aqui.](https://github.com/rrmontuan/github-app/tree/html-assets)

Muito obrigado pela ajuda!

**Comment by fdaciuk** [comment]
@rrmontuan esse repositório está sem o storybook, correto? Eu testei aqui instalando com o `getstorybook` e rodou normal.

Pode ser algum problema específico do windows, ou pode ser algum problema de permissão.

Consegue subir nesse repo a versão exata que você tem, que está dando erro?

**Comment by rrmontuan** [comment]
Então, Fernando esqueci de avisar para você usar o branch `html-assets`. Nele tem o storybook.

Testei há pouco no Linux (Ubuntu) e também não funcionou.

![Captura de tela de 2019-05-14 21-30-53](https://user-images.githubusercontent.com/6073761/57740816-0c957380-7690-11e9-8f60-67663745c88d.png)

Não sei se te ajuda em algo na análise, mas sem usar o webpack.config da pasta .storybook funciona, o problema acontece quando tento extender o webpack.config, conforme visto na aula.

**Comment by fdaciuk** [comment]
Entendi @rrmontuan! Rodei aqui nessa branch, e descobri o problema: foi só um erro de digitação [nessa linha](https://github.com/rrmontuan/github-app/blob/html-assets/.storybook/webpack.config.js#L9). Você digitou `teste` com `e` no final, aí o webpack estava tentando aplicar o standard-loader em todos os arquivos, inclusive no CSS :)

**Comment by rrmontuan** [comment]
@fdaciuk eu desinstalei e instalei as dependências diversas vezes mas nem me atentei a isso haha. Da próxima vez vou ficar mais esperto. Me desculpe pelo erro e muito obrigado pela ajuda!

Um abraço!

**Comment by fdaciuk** [comment]
Sem problemas meu caro =)
Para facilitar, tente sempre ler e entender a mensagem de erro.. hoje em dia, os devs de libs estão tentando deixar as mensagens bastante explícitas, pra ajudar devs a encontrar problemas mais facilmente :) 

O que eu fiz foi basicamente ver o erro, onde dizia que faltava um loader de CSS (mas esse não é, de fato, um problema, já que o storybook já tem um loader de CSS).

Então eu comentei a parte do preLoader que você tinha adicionado, e tudo rodou perfeitamente.

Obviamente o erro então estaria ali. Ao descomentar, eu fui relendo a configuração e percebi o problema :)

Mas problemas de digitação são bastante comuns, não é a primeira vez que acontece, e nem vai ser a última. Mas cada vez ficamos mais espertos :)
