### ISSUE TITLE
M4#A92 - Dúvida <Paper />

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#323]
E aí @fdaciuk, blz?

Só uma dúvida, porque vc não utilizou o componente [`<Card />`](https://material-ui.com/demos/cards/) do Material UI ao invés de praticamente recriá-lo com o `<Paper />`?

Não seria muito didático, não seria o momento agora e vc usará ele mais pra frente, ou não teria muito a ver com a aplicação, algum motivo específico?

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Sim, nós vamos chegar lá logo, logo haha! :D

**Comment by hiwoshu** [comment]
OK 👍
