### ISSUE TITLE
[M1#A07] Erro no "this.props"

### ISSUE THREAD

**Issue by GugaDavi** [da2k/curso-reactjs-ninja#324]
Opa Daciuk,

Suave?

Vê só, não não estou conseguindo reproduzir o exemplo da aula com o `this.props`. Ele dá varios erros e não renderiza no browser. 

Observei que colocando a prop `name` através do app.js no: <Title name="Gustavo Davi"/>, quando renderiza(Sem ser com o this) não aparece a propriedade `name` na tag no HTML. Contudo coloquei um `data-js="top"` na <div> que chamamos o elemento, para teste, e ela renderiza normalmente.

Conferi direitinho se foi algum erro de digitação, aparentemente não. Coloquei com aspas simples e duplas e o erro continua.

@fdaciuk

**Comment by GugaDavi** [comment]
Consegui resolver.

O problema é que estava utilizando arrow function, quando tentei com a notação do ES5 funfou. Sabe dizer porque?

`const Title = React.createClass({
  getDefaultProps: function () {
    return {
      name: 'Fulano'
    }
  },
  render: function () {
    return (
      <h1>Olá {this.props.name}!</h1>
    )
  }
})`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @GugaDavi! Ao usar o `createClass`, você passa um objeto com os métodos necessários para renderizar o componente.

Para ter acesso ao `this` de um objeto, os métodos precisam ser escritos com `function () {}`, pois essa função mantém o escopo do `this`.

Arrow functions têm escopo léxico, o que faz com que, o `this` usado dentro de uma arrow function, é o mesmo `this` do escopo onde essa arrow function foi criada :) 

Mais pra frente você verá o funcionamento da arrow function, acredito que vai ficar mais claro :)

**Comment by fdaciuk** [comment]
Se você quiser "adiantar" um pouco sobre o assunto de arrow functions, eu escrevi esse artigo que pode ajudar:
https://blog.da2k.com.br/2019/01/07/javascript-tudo-sobre-arrow-functions/
