### ISSUE TITLE
GitHub App - Views contendo estruturas condicionais para renderizar componentes

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#325]
Professor, em uma das aulas do módulo 02 você falou sobre views e que o idel seria não inserir estruturas condicionais nelas.  

No código abaixo, o ideal seria mover as condições que utilizam `!!userinfo`, por exemplo, para o arquivo de declaração de cada componente? 

```javascript
// app-content/index.js
const AppContent = ({  userinfo, repos, starred, getRepos, getStarred, handleSubmit, emptyRepos, handlePagination, feedbackState, feedbackMessage }) => (
  <div className={style.app}>
    <header>
      <Search
        handleSubmit={handleSubmit}
        isDisabled={feedbackState.isFetchingUser}
      />
    </header>
    
    <main>
      {!!userinfo || <FeedbackState
        feedbackState={feedbackState}
        feedbackMessage={feedbackMessage}
      />}

      {!!userinfo && <UserInfo userinfo={userinfo} />}
      {!!userinfo && <Actions
        getRepos={getRepos}
        getStarred={getStarred}
        emptyRepos={emptyRepos}
      />}

      {!!repos.repos.length && <Repos
        repos={repos}
        handlePagination={clickedPage => (
          handlePagination('repos', clickedPage)
        )}
      />}

      {!!starred.repos.length && <Repos
        repos={starred}
        handlePagination={clickedPage => (
          handlePagination('starred', clickedPage)
        )}
      />}
    </main>
  </div>
)
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Você lembra em qual aula foi isso? Só pra eu confirmar, pois talvez eu não tenha me expressado bem.. mas pode usar essa estrutura sim, sem problemas :)

O único problema que eu vejo seria nesse caso:

```jsx
{!!userinfo || <FeedbackState
        feedbackState={feedbackState}
        feedbackMessage={feedbackMessage}
      />}
```

Eu usaria `!userinfo && <FeedbackState`, pois deixa mais explícita a intenção :)

**Comment by Roger-Melo** [comment]
> Eu usaria !userinfo && <FeedbackState, pois deixa mais explícita a intenção :)

Faz sentido =)

Na [aula 116 do módulo 02](https://www.udemy.com/curso-reactjs-ninja/learn/lecture/7177410#overview) , à partir dos 10 minutos, foi dito que componentes de apresentação, que irão apenas exibir componentes, preferencialmente, não devem conter **lógica** (confundi o termo) =)

@fdaciuk

**Comment by fdaciuk** [comment]
> Na aula 116 do módulo 02 , à partir dos 10 minutos, foi mencionado que componentes de apresentação, que irão apenas exibir componentes, preferencialmente, não devem conter lógica (confundi o termo) =)

Ah, ok.. bom, revendo a aula aqui, foi isso mesmo: a ideia seria tentar melhorar a legibilidade do componente como um todo, já que nós só usamos a prop `isSaving` no componente `SaveMessage`.

Mas assim: não é uma regra, é apenas como EU gosto de fazer dessa forma, porque eu acho que melhora a legibilidade de componentes que só "chamam" outros componentes. Use o que você achar que fica mais fácil de entender :)

**Comment by Roger-Melo** [comment]
pra mim faz mais sentido também.

Vou tentar fazer assim =)

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
