### ISSUE TITLE
M2#A121 - Dúvida da necessidade de utilizar o reduce()

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#326]
Oi professor!

Nessa aula, à partir dos 05:50, foi utilizado um reduce para fazer o state `files` receber as mesmas keys e valores do `localStorage`:  

![reduce](https://user-images.githubusercontent.com/29297788/57931419-cce8aa80-788e-11e9-8b16-d5727d677318.jpg)

Minha dúvida é: por que o `reduce` foi utilizado ao invés de um destructuring no `localStorage`?  

```javascript
  componentDidMount () {
    this.setState({
      files: {...localStorage}
    })
  }
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Usei o `reduce` porque eu não pensei nessa solução MUITO MAIS SIMPLES na hora :joy: :joy: 

Pode usar ela que é sucesso :D

**Comment by Roger-Melo** [comment]
show! Vi essa parte da aula 15x pra conferir se eu não estava ficando louco hahah

**Comment by fdaciuk** [comment]
De qualquer forma, nas aulas mais à frente nós vamos refatorar esse código, mas isso que você fez é válido sim :)
