### ISSUE TITLE
M2#A126 - Erro ao tentar acessar o title, no state

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#327]
Oi professor, socorro!

Nessa aula, você ensina a fazer um componente para título do arquivo, no editor de MD. Ao tentar acessar uma propriedade de um objeto no state, o react exibe no browser o erro com a 'red box': `TypeError: Cannot read property 'title' of undefined`.

Ou seja, no código `title={this.state.files[this.state.id].title}`, ele não está conseguindo acessar a propriedade `.id`, eu acho. Caso possa olhar, o código está [aqui](https://github.com/Roger-Melo/estudos-curso-react-ninja/blob/master/examples/m02/applications/markdown-editor/src/app.js#L129). Quem está tentando receber o valor da prop `title` é um [input no header.js](https://github.com/Roger-Melo/estudos-curso-react-ninja/blob/10a377033c5ac596bf402c2c9e9860f73fa2101c/examples/m02/applications/markdown-editor/src/views/markdown-editor/header.js#L14).

P.s: se apenas um placeholder for passado: `title={'my title'}`, o input recebe esse valor normalmente... :confused:

@fdaciuk

**Comment by Roger-Melo** [comment]
Esquece, professor. Vc corrigiu o erro no vídeo seguinte. :joy:  
#ansiedadesMil

**Comment by fdaciuk** [comment]
haha! Boa =)
Qualquer coisa, pergunte à vontade :)
