### ISSUE TITLE
[M2#A10] Testando o map

### ISSUE THREAD

**Issue by edusites** [da2k/curso-reactjs-ninja#328]
Bom dia @fdaciuk !

Estou tentando importar e testar o modulo criado da seguinte maneira
`'use strict'

import map from './map'

let arr = [1,2,3]
const result = map(arr,(item) => item+1)
console.log(result)`

Mas estou recebendo um erro que não reconhece o import, porém nos testes estão com import e funcionando normalmente, o que há de errado? este projeto não tem suporte ao ECMA5?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edusites! O Jest já tem uma configuração interna que suporta o uso de ES6+, então para usar esse mesmo código em outro lugar, é preciso que sua aplicação também esteja configurada para suportar as novas features da linguagem, usando babel + webpack, por exemplo, ou alguma outra ferramenta que permita o uso dessas features :)

**Comment by fdaciuk** [comment]
Exato! O node ainda não tem suporte à ES Modules, então pra rodar esse código é preciso de uma ferramenta que entenda esse código :) 

Você pode usar o [esm](https://www.npmjs.com/package/esm), que tem uma configuração bem simples pra funcionar ES Modules no Node :)
