### ISSUE TITLE
M2#A108 - Quando não utilizar a localStorage

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#329]
Oi professor.  

Nessa aula, a `localStorage` é utilizada para persistir os dados da aplicação de Markdown.  
Você poderia dizer quando **não** é recomendado utilizá-la?  

Incrementando a pergunta: quando é melhor optar por persistir dados no back-end ou em um banco de dados e consumir esses dados através de uma API, ao invés de utilizar a Web Storage API?

@fdaciuk

**Comment by Roger-Melo** [comment]
Incrementando a pergunta: quando é melhor persistir dados no back-end ou em um banco de dados e  consumir esses dados através de uma API?

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Sempre que você tem uma aplicação web, é importante sempre pensar em persistir dados do lado do servidor, principalmente se esses dados precisam ser acessados de qualquer lugar que a pessoa estiver, e de qualquer dispositivo.

Fazendo persistência usando localStorage, por exemplo, os dados ficarão salvos apenas no navegador que a pessoa usou naquele momento.

Se você usou o seu PC, e depois quiser acessar o mesmo app no celular, não vai ter os mesmos dados, já que eles ficaram salvos no seu PC.

Esse é um caso onde os dados devem ficar em um server :)

Esse exemplo do editor de Markdown salvar no localStorage foi apenas para exemplo mesmo. O que você pode fazer de útil com o localStorage, por exemplo, é utilizá-lo para "cachear" dados vindos de um servidor.

Se os dados não mudam com muita frequência, ou o usuário tem o controle de quando os dados são atualizados, você pode fazer o primeiro request no server, e então salvar e consumir os dados do localStorage.

Assim que o usuário "pedir" para atualizar esses dados, vc faz um novo request. Dessa forma você evita requests e uso de banda do usuário desnecessários =)

**Comment by fdaciuk** [comment]
Detalhe que, para armazenar dados no browser, não existe apenas localStorage: você pode usar o IDB também (**I**ndexed **D**ata**B**ase), que é muito melhor, pois ele é async (localStorage é sync) =)

Se eu não conseguir encaixar algo falando sobre o IDB no curso, eu gravo um vídeo no YouTube falando sobre ele :)

**Comment by Roger-Melo** [comment]
Saquei. Muito obrigado pelo esclarecimento, professor =)

Vi que o Firebase é utilizado em um dos projetos do curso. Ele seria uma opção válida  
como banco de dados para um ERP online, por exemplo?

@fdaciuk

**Comment by fdaciuk** [comment]
Com certeza! Firebase é uma ótima ferramenta, e os recursos que ele oferece sem custos dá pra trabalhar tranquilamente em apps de pequeno e médio porte =)

**Comment by Roger-Melo** [comment]
Massa. Valeu, professor! =)

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
