### ISSUE TITLE
webpack.config.js usando ES6

### ISSUE THREAD

**Issue by baltazarparra** [da2k/curso-reactjs-ninja#33]
Como fazer pra poder escrever o arquivo webpack.config.js usando ES6. Pra poder usar import ao invés de require.

O correto seria usar tudo import, que é o padrão ES6, certo?

**Comment by fdaciuk** [comment]
Fala @baltazarparra =)

Não que seja padrão, pois o `webpack.config.js` roda em cima do Node, então você pode usar tanto o formato CJS do Node, com `require`, ou com ES6, usando `import`.

Para usar ES6 é bem simples: você só precisa instalar o `babel-register` como dependência de desenvolvimento, e renomear o seu arquivo `webpack.config.js` para `webpack.config.babel.js`.

Tem uma pequena desvantagem nisso, que é a velocidade de execução do script, pois o Babel vai ter que fazer a leitura do arquivo antes, converter o código para o padrão do Node antes de ele ser de fato executado. 

Mas é uma opção para facilitar a configuração no `webpack.config` =)

**Comment by baltazarparra** [comment]
Valeu mano =D

**Comment by fdaciuk** [comment]
Qualquer coisa só gritar =)
