### ISSUE TITLE
M4#A81 - Exemplo com classe

### ISSUE THREAD

**Issue by amauryeuzebio** [da2k/curso-reactjs-ninja#330]
Boa noite.

Gostaria de saber como ficaria a logica dos Redirects em um componente de classes?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @amauryeuzebio! Não mudaria muita coisa: basicamente [dessa linha](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m04/04-reactzzaria/33/sistema-pedidos/src/app.js#L30) pra baixo, todo o código ficaria dentro do método `render`.

[Essa informação](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m04/04-reactzzaria/33/sistema-pedidos/src/app.js#L13) nós adicionaríamos no `this.state`, e [essa parte](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m04/04-reactzzaria/33/sistema-pedidos/src/app.js#L12), usando a Context API, nós colocaríamos também no `render`, usando o `AuthContext.Consumer`, envolvendo todo o conteúdo do `render`, para pegar e repassar as informações do `userInfo`.

O [código do useEffect](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m04/04-reactzzaria/33/sistema-pedidos/src/app.js#L17-L28) ficaria no `componentDidMount` :) 

Teríamos apenas que fazer com que as funções `setUserInfo` e `logout` sejam passadas para a classe, usando propriedades da class, para que elas possam ser acessadas em todo o escopo da class (nesse caso, no método `componentDidMount`).

O arquivo `app.js` ficaria assim:

```jsx
import React, { lazy, Suspense } from 'react'
import t from 'prop-types'
import { Redirect, Route, Switch } from 'react-router-dom'
import { LinearProgress } from '@material-ui/core'
import firebase from 'services/firebase'
import { AuthContext } from 'contexts/auth'

const MainPage = lazy(() => import('pages/main'))
const Login = lazy(() => import('pages/login'))

class App extends React.PureComponent {
  state = {
    didCheckUserIn: false
  }

  setDidCheckUserIn (value) {
    this.setState({
      didCheckUserIn: value
    })
  }

  componentDidMount () {
    firebase.auth().onAuthStateChanged((user) => {
      console.log('dados do usuário:', user)
      this.setUserInfo({
        isUserLoggedIn: !!user,
        user
      })
      this.setDidCheckUserIn(true)
    })

    window.logout = this.logout
  }

  render () {
    const { location } = this.props
    const { didCheckUserIn } = this.state

    return (
      <AuthContext.Consumer>
        {({ userInfo, setUserInfo, logout }) => {
          this.setUserInfo = setUserInfo
          this.logout = logout
          const { isUserLoggedIn } = userInfo

          if (!didCheckUserIn) {
            return <LinearProgress />
          }

          if (isUserLoggedIn && location.pathname === '/login') {
            return <Redirect to='/' />
          }

          if (!isUserLoggedIn && location.pathname !== '/login') {
            return <Redirect to='/login' />
          }

          return (
            <Suspense fallback={<LinearProgress />}>
              <Switch>
                <Route path='/login' component={Login} />
                <Route component={MainPage} />
              </Switch>
            </Suspense>
          )
        }}
      </AuthContext.Consumer>
    )
  }
}

App.propTypes = {
  location: t.object.isRequired
}

export default App
```

**Comment by amauryeuzebio** [comment]
@fdaciuk Valeu ai pela explicação! Consegui adaptar aqui para o que eu queria com uso do redux.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
