### ISSUE TITLE
MRW#03 Não consigo executar o JS

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-reactjs-ninja#331]
Caro Daciuk,

Como pode perceber, já estou no segundo curso seu. Estou com um problema e já refiz umas 20 vezes paço a paço, inclusive utilizando o versions-of-dependencies.md, mas ainda assim não consigo executar o index.js no webpack. Vou te encaminhar a imagem com os arquivos e terminal abertos e coloquei o endereço como comentário no topo dos arquivos. Inclusive ele recompila quando altero o index.js, mas não aparece o log no terminal de jeito nenhum, nem aparece o arquivo no _sources_.

http://escoladeservidor.com/wp-content/uploads/2019/05/configuracao-webpack.jpeg

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! Legal, vamos resolver isso então :grin: 
Olhando a imagem parece estar tudo certo, então vamos fazer melhor: consegue subir seu projeto aqui no GitHub e passar o link?

Assim eu baixo aqui e testo, e vejo se pode estar faltando algo :)

**Comment by xneuber** [comment]
Nossa @fdaciuk , que vergonha. kkkkk. Era isso mesmo, resolveu aqui. Mas teve bom que refiz isso inúmeras vezes e acabou fixando muito mais. Estava reaproveitando o html, não imaginei que poderia ser ele. Rss. Muito obrigado!

**Comment by fdaciuk** [comment]
haha! Super normal cara, relaxa :)
É bom acontecer a primeira vez, que dificilmente acontece de novo :D 

Qualquer coisa, avisar ae :D

**Comment by rafa-so** [comment]
Fala aí Fernando, tudo tranquilo?

Então resolvi finalmente correr com o seu curso aqui (que por sinal é muito bom) e me deparei com um problema que não estou conseguindo resolver. Já  reescrevi várias vezes eu não saio do lugar. 

É o seguinte. Criei os seguintes arquivos:

- webpack.config.js
- src/index.js 
- index.html (script src=bundle || script src=static)

Na aula anterior o  script src (index.html) estava olhando para o bundle.js "físico". nesta aula, você mostrou o webpack-dev-server e colocou no arquivo de configuração o publicPath: '/static/'.

Meu problema, com este publicPath aí, o console não loga de maneira nenhuma. Segue o link do meu repo se você quiser dar uma olhada: https://github.com/rafa-so/react-webpack

Antes de colocar o publicPath, logava tranquilo. Colocando o publicPath, não  loga mais. Já refiz as aulas algumas vezes, e realmente não consigo ver onde está o meu erro rs

Abraços e muito obrigado por este curso :)

**Comment by fdaciuk** [comment]
Oi @rafa-so! Você tentou derrubar o `webpack-dev-server` e subir novamente? Aqui seu repositório está funcionando certinho :)

**Comment by rafa-so** [comment]
pow, é o que eu mais fiz kkkkk, mas beleza, vou tentar novamente e confirmo aqui, valeu :D

**Comment by fdaciuk** [comment]
Qualquer coisa tenta deletar seu diretório node_modules e os arquivos `package-lock.json` (**não o package.json, esse tem que ficar) e o `yarn.lock`, se tiver; e rodar de novo! 

Porque no projeto está tudo certo :)

**Comment by rafa-so** [comment]
Beleza, hoje a noite vou fazer todas essas verificações :) Grato

**Comment by rafa-so** [comment]
Bom, só para dar o feedback que era  exatamente isso. Não me  liguei que tinha que derrubar o webpack-dev-server. Só derrubei e foi deboas :D

Valeu aí para paciência rs

**Comment by fdaciuk** [comment]
Sem problemas @rafa-so! Qualquer coisa, só avisar :)
