### ISSUE TITLE
MRW#9 

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-reactjs-ninja#332]
no momento de acessar o serviço criado , apresenta essa mensagem no console

Uncaught Error: [HMR] Hot Module Replacement is disabled.
    at Object.<anonymous> (only-dev-server.js:76)
    at __webpack_require__ (bootstrap cf55845238d3a98e09d2:19)
    at Object.<anonymous> (bootstrap cf55845238d3a98e09d2:39)
    at __webpack_require__ (bootstrap cf55845238d3a98e09d2:19)
    at bootstrap cf55845238d3a98e09d2:39
    at bootstrap cf55845238d3a98e09d2:39

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Compare seu código atual com esse aqui:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-09

Se estiver exatamente igual, inclusive as versões das dependências, deve funcionar certinho :)
Se algo não funcionar, me avise :D

**Comment by TMiranda7** [comment]
consegui ver o erro! se tratava de um parametro errado do package.json.

**Comment by fdaciuk** [comment]
Show! Legal que resolveu :D 
Qualquer coisa, só avisar :)
