### ISSUE TITLE
 M4#A89 - Mudar cor do texto do AppBar

### ISSUE THREAD

**Issue by samyrabdo** [da2k/curso-reactjs-ninja#333]
Olá @fdaciuk , como faço p mudar a cor do texto e a cor de fundo da AppBar usando o theme? 
Eu gostaria de deixar a appbar com fundo transparente e com o texto cinza como nesse template: https://demos.creative-tim.com/material-dashboard/examples/dashboard.html?_ga=2.160358141.1994508337.1559226761-1562065546.1556894930

Obrigado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samyrabdo! Nós vamos chegar nessa parte de personalização ainda, mas pra fazer isso, você pode usar o `overrides`, na configuração do tema:
https://material-ui.com/customization/globals/
