### ISSUE TITLE
Criando um componente para conter a largura do conteúdo da aplicação

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#334]
Oi professor! 

Estou codando um projeto com o Gatsby gostaria de uma sugestão, se possível.  

Eu gostaria de implementar uma `<div>` com a largura que apenas o conteúdo da aplicação deve ter.  

Uma possibilidade seria criar um componente `Container`, que possui o estilo já com `width` e `margin` centralizada, e renderiza a prop `children`. Daí ele seria invocado dentro de outros componentes, para que esses componentes tenham, por exemplo, uma cor de fundo que ocupe toda a largura da tela e o conteúdo deles tenha a largura que foi determinada no estilo do `Container`.  

Há uma maneira melhor de fazer isto, sem repetir as invocações deste componente várias vezes?

A estrutura dos arquivos do projeto é diferente da forma mostrada aqui no curso. Não há um componente que guarda o estado. Como é o meu primeiro contato com o Gatsby, ainda não sei se estou fazendo uma besteira gigante com a organização.  

@fdaciuk

**Comment by fdaciuk** [comment]
Fala meu querido @Roger-Melo! :D 

Olha, no caso do Gatsby, eu ainda estou em processo de aprendizagem =)

Mas até onde eu vi, normalmente você cria um componente de Layout mesmo, e vai usando onde precisar, já que você pode ter vários templates para tipos de conteúdos diferentes (categorias, tags, post "single", lista de posts, páginas, etc).

O que eu tenho feito até então é isso: criar um componente Layout com a base que vai ser usada em todos os templates, e cada template criado, eu envolvo com esse componente Layout :)

Uma outra vantagem dessa abordagem, é que você pode ter um layout específico pra algum tipo de conteúdo. Dessa forma, seria só criar um outro tipo de Layout, e usar esse outro componente :)

**Comment by fdaciuk** [comment]
Sobre o estado: você pode trabalhar com o conceito de que cada "página" seria um Container, e esse container pode conter os estados referentes aos componentes abaixo dele, já que esse componente vai ser o primeiro a ser carregado, quando uma página for carregada :)

Deu pra pegar a ideia?

**Comment by Roger-Melo** [comment]
Saquei!

Que ferramenta, né? Tô gostando bastante dele. Parece ter pouco conteúdo em PT-BR, quem sabe rola um vídeo no queroser.ninja:tm:

Obrigado, professor =)

**Comment by fdaciuk** [comment]
Sim, Gatsby é sensacional! Vou preparar uns conteúdos em breve sim :D
