### ISSUE TITLE
 M4#A77 Como passar parametros do formulário para o auth.js

### ISSUE THREAD

**Issue by samyrabdo** [da2k/curso-reactjs-ninja#335]
Olá @fdaciuk, eu estou implementando o sistema com o login sendo feito ao digitar usuário e senha no formulário de login.
Minha pergunta é, como eu passo os dados de usuario e senha de login.js para auth.js?

O meu código está levemente diferente do seu.
Login.js

```
function Login() {

  const { login } = useContext(AuthContext)

  const [userInfo, setUserInfo] = useState({
    isUserLoggedIn: false,
    token: null
  })

  const { isUserLoggedIn, token } = userInfo

  useEffect(() => {
    setUserInfo({
      isUserLoggedIn: !!token,
      token
    })
  }, [])

  return (
    <Container>
      <Grid container justify='center' spacing={4}>
        <Grid item xs={12} container justify='center'>
        </Grid>
        <Grid item xs={12} container justify='center'>
          <form>
            <TextField
              label='Usuário'
              name='username'
              inputRef={usernameInput => (username = usernameInput)}
              margin="normal"
            />
            <TextField
              label='Senha'
              name='password'
              type="password"
              inputRef={passwordInput => (password = passwordInput)}
              margin="normal"
            />
            <Button
              variant="outlined"
              size="small"
              color="primary"
              onClick={login}>
              Entrar
              </Button>
          </form>
        </Grid>
      </Grid>
    </Container>
  )
  }
```

Esse a minha função Auth onde pego os dados de user e senha e faço a chamada na api para fazer o login. Portanto, meu Auth.js deveria receber o usuario e senha vindos do formulário em login.js

```

const userKey = '_auth_user'

const INITIAL_STATE = {
    user: JSON.parse(localStorage.getItem(userKey)),
    validToken: false
}

function Auth({ children }) {

    const login = useCallback((event, state = INITIAL_STATE) => {        
        event.preventDefault();
        fetch('http://localhost:4000/login', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                username: this.username.value,
                password: this.password.value,
            })
        })
            .then(response => {
                if (response.ok) {
                    return response.text()
                } else {
                    console.log('erro')
                    throw new Error('Usuário ou Senha incorreto')
                }
            })
            .then(token => {
                localStorage.setItem(userKey, JSON.stringify(token))
                return { ...state, user: token, validToken: true }
            })
            .catch(error => {
                localStorage.removeItem(userKey)
                return { ...state, user: null, validToken: false }
            })
    }, [])

    return (
        <AuthContext.Provider value={{login}}>
            {children}
        </AuthContext.Provider>
    )
}
```
```
<!-- Não apague daqui pra baixo! -->
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samyrabdo!

Nós vamos ver mais pra frente como fazer a implementação de usuário e senha usando o Firebase, mas pra te ajudar com a sua implementação, vou te dar algumas dicas :)

Tem alguns problemas aí que precisam ser resolvidos, vamos lá:

O primeiro detalhe que precisa ser ajustado é no seu formulário de login: todo formulário deve sempre seguir a definição padrão que você usaria com HTML puro, independente da biblioteca que você está usando. E não é diferente com React: se você vai submeter o formulário, ele precisa ter um atributo `method` e uma `action`, que vai dizer para onde ele vai ser submetido.

Ainda que você vá fazer o submit do formulário com JS, é importante ter essas informações para que tudo funcione como esperado, ainda que o usuário que usar sua aplicação não tenha JS habilitado por qualquer motivo :)

Ao fazer isso, para fazer o submit via JS, ao invés de usar o `onClick` do botão, use o evento `onSubmit` do `form`, que seria o mais semanticamente correto.

Com isso, você tem algumas vantagens:
- Não precisa usar `ref` nos inputs: se você não precisa validar a entrada dos campos dígito a dígito, você não precisa de input do tipo "controlado" (com as props `value` e `onChange`);
- e não precisa do `ref`, porque você consegue pegar as informações dos inputs à partir do objeto do evento, passado para o método que será listener do evento onSubmit do formulário, usando `e.target.elements.NOME_DO_CAMPO`.

No caso, o `NOME_DO_CAMPO`, você vai substituir pelo valor da prop `name` do campo:
Para o campo de senha, `e.target.elements.password`, e para o usuário, `e.target.elements.username` =)

Outro ponto importante: a função que é listener do evento recebe apenas um único argumento: o objeto de evento. Então nesse seu componente `Auth`, onde você cria o `login`, e passa o objeto de evento e um state, isso não existe! Essa função só vai receber o objeto de evento.

O que você poderia fazer para ficar melhor, é fazer a função `login` receber apenas um objeto, com `username` e `password`, e lá no formulário, você cria uma outra função que vai ser listener do evento, e essa função chama o `login`, passando um objeto com `username` e `password`.

Outro problema ali é você usar `this` dentro de um componente função. Isso não vai funcionar nunca, já que a função não vai ter `this` disponível, e não existe um `this.username`, nem um `this.password` nesse escopo para você tentar usar dessa forma. Pegue essas informações como falei acima: recebendo um objeto da função `login`.

E o retorno que você está fazendo dentro da Promise também não tem  muito sentido, já que eles não vão para "lugar nenhum": você não atribui esses valores à uma variável, não passa pra uma função, então eles não estão fazendo nada ali.

Para atualizar as informações do usuário, teria que usar a mesma ideia que eu mostrei no curso, atualizando o state do componente `Auth`, e passando esse valor para o Provider, para que ele possa ser acessado em qualquer lugar da aplicação onde você usar o `useContext` :)

Espero que tenha ficado claro! Em breve nós vamos chegar nessa parte de fazer login com usuário e senha usando Firebase, e a ideia de implementação vai ser parecida com essa que você está fazendo com servidor próprio :)

**Comment by samyrabdo** [comment]
Olá @fdaciuk , muito obrigado pelas resposta completa e pela agilidade.
Como eu tinha componentes de classes e estava passando para componente de função, acabei deixando passar algumas coisas (this...) no momento que te fiz a pergunta.
Tentei fazer as alterações conforme sua sugestão, mas ainda assim não estou conseguindo pegar os dados vindos do form.
Deixei o form conforme vc disse em login.js

 ```
 <Container>
      <Grid container justify='center' spacing={4}>
        <Grid item xs={12} container justify='center'>
        </Grid>
        <Grid item xs={12} container justify='center'>
          <form method='post' onSubmit={login} >
            <TextField
              label='Usuário'
              name='username'              
              margin="normal"
            />
            <TextField
              label='Senha'
              name='password'
              type="password"
              margin="normal"
            />
            <Button
              variant="outlined"
              size="small"
              color="primary"
              type="submit"           
              >
              Entrar
              </Button>
          </form>
```
E em auth.js, tentei pegar os elementos do form dessa maneira:



    const login = useCallback(e => {
        e.preventDefault();
        console.log(e.target) //nada é exibido no console

        fetch('http://localhost:4000/login', {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                username: e.target.elements.password,
                password: e.target.elements.password,
            })
        })
            .then( ...código não importante para a questao....)
    }
     , [])
O e.target.elements.username e e.target.elements.password vem nulos.

Tentei ser conciso p não tomar mto seu tempo. Caso tenha ficado algum trecho de código importante, eu envio. 

Obrigado

**Comment by fdaciuk** [comment]
Consegue subir esse projeto aqui no GitHub e compartilhar comigo o repositório? Se não puder deixar público, pode deixar o repo privado, e me adicione lá =)
Assim fica mais fácil eu baixar aqui e testar pra entender onde pode estar o problema.. só olhando trechos de código, alguma coisa vai sempre passar batida :)

**Comment by samyrabdo** [comment]
@fdaciuk eu acabei de editar meu comentário atualizando o resultado do `console.log`. Seria possível dar uma olhada nessa edição q fiz? Caso ainda assim vc não consiga me ajudar, darei um jeito de subir o codigo.
Obg

**Comment by samyrabdo** [comment]
Acabei de conseguir. 
Peguei os valores da seguinte forma: 
e.target.elements.username.value
e.target.elements.password.value

Mto Obrigado

**Comment by fdaciuk** [comment]
Boa! É exatamente isso: no `e.target.elements.NOME_DO_CAMPO` vai vir o objeto referente ao nó do DOM.. aí você pega o valor com `.value`, e qualquer outra propriedade que quiser desse objeto - `.checked`, por exemplo, para o casos dos _checkbox_ :)
