### ISSUE TITLE
M4#A100 Estratégia de componentes/rotas

### ISSUE THREAD

**Issue by samyrabdo** [da2k/curso-reactjs-ninja#336]
Olá @fdaciuk.
Acabei de assistir a última aula disponibilizada até agora e, mesmo q vc ainda aborde isso mais p frente, eu gostaria de tirar um dúvida conceitual.

Vi que no app react-zzaria a estratégia será mudar o componente e mudar a url da página, no caso do react-zzaria está ficando assim:
 

- rota: '`/`'   -> componente:` choose-pizza-size`
-  rota: `sabores-da-pizza` -> componente `choose-pizza-flavours`

Já vi outras estratégias que seria manter a mesma url e por meio de condicionais exibir um componente ou outro, no caso, a aplicação continuaria na mesma url '`/`', mas os componentes mudariam de `choose-pizza-size` para `choose-pizza-flavours`.

Quais as vantagens e desvantagens de usar uma estratégia ou outra?

Espero ter sido claro.

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samyrabdo! A vantagem de usar rotas ao invés de só condicionar a renderização ao estado, é que o usuário que estará fazendo o pedido da pizza terá a possibilidade de navegação entre as opções (tamanho da pizza, sabor e quantidade), sem que haja a necessidade de nós, manualmente, armazenarmos esse estado de navegação, já que tudo vai ficar no histórico do navegador do usuário.

Na verdade, isso que estamos fazendo pode ser feito de várias formas. Eu preferi fazer dessa forma nesse momento, mas com o app em produção, você pode analisar o comportamento do usuário, e à partir disso, definir uma forma melhor, seja com renderização condicional, seja com query string na URL, ou alguma outra solução :)

Sempre teremos vários opções para resolver o mesmo problema de formas diferentes. "Qual" solução usar vai muito além de uma escolha do dev :)
