### ISSUE TITLE
[M1#A15]

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-reactjs-ninja#338]
Daciuk,

Meu webpack está há algumas aulas com uma mensagem de  `Compiled with warnings.`
mas quando vou verificar ele está sempre reclamando de algum símbolo especial `/ = {`
mas ao ver o arquivo, todos eles fazem parte da linha, daí não estou entendendo o que é, está funcionando normal, mas acaba ficando incômodo. Vou encaminhar os arquivos:

Warnings do webpack:
```
WARNING in ./src/index.js
<text>:10:22: Parsing error: Unexpected token /

WARNING in ./src/app.js
<text>:10:23: Parsing error: Unexpected token =

WARNING in ./src/title.js
<text>:7:12: Parsing error: Unexpected token {

WARNING in ./src/square.js
<text>:6:15: Parsing error: Unexpected token =
webpack: Compiled with warnings.
```

Na linha 10 do index.js é:
`<NextApp />`

Na linha 10 do app.js é:
`<div className='container' onClick={function(e) {`

Na linha 7 do title.js é:
`<h1>Oi { `${name} ${lastname}` }</h1>`

Na linha 6 do square.js é:
`<div style={{`

Só reafirmando, está tundo funcionando perfeitamente, mas os _warnings_ persistem 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! Provavelmente é algum conflito entre dependências de dependências.
Tente remover o diretório node_modules, e o arquivo `package-lock.json` do seu projeto, e instalar as dependências novamente, com `npm install` que deve resolver :)
