### ISSUE TITLE
[MRW#01.0.1] Duvida versão antigas.

### ISSUE THREAD

**Issue by didamendes** [da2k/curso-reactjs-ninja#339]
Boa tarde, Mestre.
Instalando versão antigas não vai fazer o aluno só ficar preso naquela versão ?
Não deveria fazer um vídeo onde o Aluno aprende a sair de um pepino ? 
Att, Diogo.

**Comment by fdaciuk** [comment]
Oi @didamendes! Desculpe, como você removeu a marcação do meu user da issue, não recebi a notificação da sua dúvida :)

Vamos lá:
As libs nas versões mostradas no curso, ainda que não estejam nas versões mais recentes nos primeiros módulos, elas seguem sempre um "padrão" para sua utilização, que é usado nas versões mais recentes.

Algumas libs tiveram alterações, como o webpack por exemplo, que eu mostro no módulo 2. Mas da versão 2 em diante não tiveram mudanças significativas, apenas atualizações com melhorias e novas features.

O React é basicamente o mesmo: aprendendo os conceitos mostrados no curso, você usa ele em qualquer versão, porque as coisas não mudam simplesmente de uma versão para outra :)

Mas eu sei da importância de manter tudo atualizado, por isso, assim que finalizar o módulo 4, onde eu já estou mostrando várias das novas features do React, vou começar a atualizar os dois primeiros módulos, para refletirem a versão atual da lib, então pode ficar tranquilo quanto a isso :)

No mais, o que foi mostrado no curso continua funcionando normalmente nas novas versões :)

Se algo não funcionar, e você tiver qualquer dúvida, fique à vontade para perguntar :)

Estou à disposição para ajudar ;)
