### ISSUE TITLE
[reinstalação] Dúvidas sobre reinstalação das dependências ao formatar PC

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-reactjs-ninja#340]
Fernando,

Estou com uma dúvida sobre a reinstalação das dependências. Se caso eu precise formatar meu pc (preciso muito), vou inclusive voltar pro linux. Daí vou precisar instalar o node e refazer as linhas de comando de instalação de acordo com aquele arquivo pra resolver problemas de dependências até a aula que fui né? Posso reaproveitar todos os arquivos de configuração, não preciso de configurar tudo de novo não né?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! Não precisa configurar tudo do zero não :)

Basicamente é instalar o Node.js (e o NPM, que já vem com o Node) na sua máquina, e manter no seu projeto o arquivo `package.json`.

Com isso, ao executar `npm install` no diretório do projeto, o NPM vai olhar no arquivo `package.json` todas as dependências que você precisa, e vai instalar as versões corretas, criando o diretório node_modules com as dependências do seu projeto :)
