### ISSUE TITLE
 M4#A27 - Estratégia de navegação

### ISSUE THREAD

**Issue by samyrabdo** [da2k/curso-reactjs-ninja#341]
Olá @fdaciuk, acabei de ver as aulas sobre os componentes de navegação e estou com algumas dúvidas sobre qual a melhor estratégia a ser usada na minha aplicação. Acredito q vc ainda irá tratar disso nas próximas aulas, mas como preciso avançar no meu projeto, vai aqui a pergunta.

Meu projeto está baseado no do reactzzaria.
Tenho o `app.js` com a seguinte estratégia de navegação:

```
   <Switch>
        <Route path='/' exact component={MainPage} />        
        <Route path='/login' component={Login} />
        <Route component={Error404} />
      </Switch>
```
O componenente `MainPage` se refere ao meu componente "pai" `main.js`, onde controlo todos os estados da aplicação e é onde monto o layout da seguinte forma:

`main.js`
```
render () {
    return (
      <Fragment>
        <Sidebar />
        <Header headerTitle={this.state.headerTitle} />
        <Spacer />
        <Content
          CPF={this.state.CPF}
          searchCPF={this.searchCPF}
          CPFHandler={this.CPFHandler}     
          dataTableObject={this.state.dataTable}     
          searchDetailResult={this.searchDetailResult}
          showSearchDetailResult={this.state.showSearchDetailResult}
          ...
        />
      </Fragment>
    )
  }
```

A sidebar e o header são fixos, eu vario apenas o conteudo. Para tanto, eu passo os estados para o componente `Content`.
No componente`Content` eu controlo se vou exibir o componente q contem o resultado da busca por CPF (`SearchResult`) ou se exibo o componente que detalha ainda mais o resultado da busca (`SearchDetailResult`)

`content.js`
```
const Content = props => {

const renderSearchResult = (props.dataTableObject.length > 0 && !props.showSearchDetailResult) &&
    <SearchResult
      list={props.dataTableObject}
      searchDetailResult={props.searchDetailResult} />

  const renderSearchDetailResult = props.showSearchDetailResult &&
    <SearchDetailResult
      list={props.dataTableObject.list}
      CPF={props.CPF} />

  return (
    <Container>
      {renderSearchResult}
      {renderSearchDetailResult}
    </Container>
  )
}
```
Perceba que hoje eu exibo o componente `SearchResult` ou o componente `SearchDetailResult` basicamente verificando se `props.showSearchDetailResult` é verdadeiro ou falso, sem alterar a URL.
Eu seto `props.showSearchDetailResult` ao clicar no link "Detalhar" do componente `SearchResult`:

`searchResult.js`

```
const SearchResult = props => {
  const classes = useStyles()
  ...
  return (
     body.map(result => (
    <TableRow key={id_transacao}>
      <TableCell >{appName}</TableCell>
      <TableCell>{verified}</TableCell>
      <TableCell>
        <Link to={'/'}>
          <span onClick={e => props.searchDetailResult(e, id_transacao)}>Detalhar</span>
        </Link>
      </TableCell>
    </TableRow>
  ))

```

Ao clicar em "Detalhar" eu chamo a função `searchDetailResult` em `main.js`

```
searchDetailResult (event, id) {
    this.searchDetailResultHandler(true) 
    this.headerTitleHandler('Detalhamento - Coleta dos Dados biométricos')
    this.setState({
      ....
    })
  }

  searchDetailResultHandler (status) {
    this.setState({ showSearchDetailResult: status })
  }

```

Qual a melhor forma para ao clicar em "Detalhar" uma nova URL seja chamada (ex.: localhost:3000/detalhe) renderizando o componente `SearchDetailResult` passando como parametro o id_transacao, sem precisar fazer o controle lógico que faço atualmente por meio do estado do `showSearchDetailResult`

Espero ter conseguido ser claro, infelizmente não posso disponibilizar todo o código.
Obg

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samyrabdo! Acho que consegui entender seu problema :)
Vamos lá:

Bom, você não vai conseguir carregar nenhuma rota específica dentro de `MainPage`, pois a regra que você usou para carregar esse componente é que a rota deve estar em `'/'`, e somente nessa rota (por causa do `exact`), então ali dentro você não conseguiria carregar rotas à partir da raiz, como fizemos na Reactzzaria.

Outro ponto importante: no `searchResult.js` você não precisa do componente `Link`, pois você não vai navegar para uma rota diferente da que já está. Pode usar um `<button>` mesmo, pois você não precisa de `href` ali, só do evento `onClick`.

Bom, tem algumas formas de resolver seu problema:
Primeiro você teria que remover o `exact` da `MainPage` e tratar como fizemos na Reactzzaria. Dessa forma, você trata a página 404 dentro da `MainPage`, e também lá dentro você vai conseguir criar outras rotas para navegações internas;

Ao fazer isso, você tem algumas opções: 

- pode passar via query string o `id_transacao`, e à partir dessa query fazer a busca das informações que precisa;
- pode passar na rota mesmo o `id_transacao`, como um parâmetro da rota `/detalhe`. Ficaria algo assim:

Para navegar: `/detalhe/1` (onde `1` é o `id_transacao`);
Para criar a rota, passe o `path` como: `/detalhe/:id_transacao`.

Assim, quando você estiver no componente carregado para a rota `/detalhe`, você consegue pegar ali dentro esse parâmetro à partir da prop `match.params`, como vimos lá na aula 6 :)

Essas seriam algumas soluções que você pode utilizar :)

**Comment by samyrabdo** [comment]
Olá @fdaciuk .
Entendi as suas colocações e obrigado pela resposta completa. Mas isso acabou me gerando outra dúvida. 

É o seguinte, no meu componente `Main` que é o componente "pai" onde controlo todos os estados da aplicação e onde monto o layout, eu armazeno o resultado de um `fetch` que faço qdo o usuário pesquisa por um CPF, suponhamos q esse resultado fica armazenado no state `list`. Esse resultado é um array de objetos dessa forma:
```
0: {id_transacao: 25, verificado: true, data_verificacao: "2019-04-06T00:05:16.508Z", dados_detalhados: {…}}
1: {id_transacao: 26, verificado: true, data_verificacao: "2019-04-06T00:07:19.409Z", dados_detalhados: {…}}
2: {id_transacao: 72, verificado: true, data_verificacao: "2019-04-09T02:06:50.776Z", dados_detalhados: {…}}
3: {id_transacao: 1076, verificado: true, data_verificacao: "2019-04-13T19:16:23.019Z", dados_detalhados: {…}}

```
Eu exibo esses dados em uma tabela, ficando dessa forma (componente `SearchResult`):
```
ID        Verificado           Data                 Ação
25           sim              06/04/2019           Detalhar
26           sim              06/04/2019           Detalhar
72           sim              09/04/2019           Detalhar
1076         sim              13/04/2019           Detalhar
```

Ao clicar em "Detalhar" eu não gostaria de fazer outra requisição, mas apenas pegar o id da transação e no meu componente `searchDetailResult` exibir o objeto `dados_detalhados` que já me foi retornado no `fetch` feito anteriormente e que já está armazenado no state `list`.

Da forma que eu fiz, ao clicar no link Detalhar, q possui o seguinte código:
```
<Link to={'/'}>
          <span onClick={e => props.searchDetailResult(e, id_transacao)}>Detalhar</span>
</Link>
```
eu passava o `id_transacao` para `searchDetailResult` (ver codigo abaixo) e apenas atualizava o estado de `list` para q ele contenha os dados do objeto `dados_detalhados`

```
searchDetailResult (event, id) {
          this.setState({
             list: this.state.list.filter(function (l) {
               return l.id_transacao === id
            })
}
```
Dessa forma, ao renderizar o componente `SearchDetailResult`, ele já vinha com os dados de list filtrados conforme o id da transação clicado pelo usuário.

Porém, caso eu não tenha entendido errado, se eu fizer da forma q vc disse:

- Para navegar: /detalhe/1 (onde 1 é o id_transacao);
- Para criar a rota, passe o path como: /detalhe/:id_transacao.

eu teria que receber esse id no componente `SearchDetailResult` e nele eu teria que fazer um `fetch` novamente p pegar o id da transação e exibir o resultado. Seria isso mesmo?

A minha questão é, como eu faria p ter uma rota especifica (`/detalhe/1`) e recuperar os dados da state `list` que já está no componente main?

Caso eu não tenha conseguido ser claro, não se preocupe e podemos dar por encerrado essa issue, vc já me ajudou bastante e não precisa perder mais tempo tentando entender algo complexo até de explicar. Estou insistindo no assunto pq, apesar da aplicação estar funcionando, eu gostaria de aprender a fazer da melhor forma possível.

Obrigado

**Comment by fdaciuk** [comment]
Fala @samyrabdo! Nunca é perda de tempo meu caro, fico feliz em poder ajudar :)
Vamos lá:
É importante lembrar que, quando uma rota é carregada, essa informação é feita via JS, ou seja: a tela não recarrega, e as informações que você já tem não se perdem.

Logo, quando você carrega um componente à partir de uma rota, você simplesmente está fazendo uma renderização condicional, como se fizesse algo como:

```jsx
<>
  {window.location.pathname === '/' && <Home />}
  {window.location.pathname === '/login' && <Login />}
</>
```

Saca? É exatamente isso que o React Router DOM faz, por baixo dos panos, quando você usa o componente Route:

```jsx
<>
  <Route path='/' component={Home} />
  <Route path='/login' component={Login} />
</>
```

A implementação do Route, só a título de exemplo, para mostrar como seria abstrair o código acima, seria assim:

```jsx
const Route = (props) => (
  return window.location.pathname === props.path && <props.component />
)
```

Sacou a ideia? Não é nada demais o que fazemos ao usar o Route :)

Pensando dessa forma, você não precisa fazer mais um `fetch`. Se o seu `fetch` é feito no componente principal, que vai sempre carregar antes de qualquer rota, então você pode ter acesso ao resultado desse `fetch` em qualquer componente abaixo dele.

O que você precisa fazer é, unicamente, passar essa informação pra baixo, seja via props, ou usando a Context API, como mostrado no curso :)

Se usar a Context API, por exemplo, no resultado do fetch você salva os dados na Context, e quando você acessar `/detalhe/1`, você consulta no objeto que está na Context API por esse ID 1, e renderiza a a informação dele.

Como o resultado do fetch é um array, pra você buscar o item com ID 1, seria só usar o método `find`:

```js
list.find(item => item.id_transacao === id)
```

O código acima vai te retornar o objeto que contém o `id_transacao` igual a 1, que está no array `list` =)

Ficou clara a ideia? :)

**Comment by samyrabdo** [comment]
@fdaciuk a ideia ficou clara sim.
Mas para o que estava precisando a aula 101, recém lançada, foi perfeita, consegui simplificar a aplicação absurdamente.

Mto obrigado!

**Comment by fdaciuk** [comment]
Perfeito @samyrabdo! Qualquer coisa, só avisar :)
