### ISSUE TITLE
M1#A17

### ISSUE THREAD

**Issue by Suele** [da2k/curso-reactjs-ninja#342]
Olá Fernando,
Estou reproduzindo a aula, mas para mim no consolo mostra os seguintes erros.

![image](https://user-images.githubusercontent.com/11871880/59368076-d3463700-8d13-11e9-9296-1ac042412836.png)

meu github é: https://github.com/Suele/react-ninja-udemy
e a branch em que está o código é: (modulo#01-parte3-lifecycle-e-stateful-vs-stateless)

@fdaciuk

**Comment by Suele** [comment]
Oi Fernando,
Consegui resolver o problema faltava colocar `props.handleClick` um pequeno descuido.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Suele! Que bom que conseguiu resolver :D 
Qualquer dúvida, só avisar :)
