### ISSUE TITLE
[M2#10] - (Contribuição) Esclarecimento para o erro ao testar retorno de throw no ChaiJs

### ISSUE THREAD

**Issue by ozeas** [da2k/curso-reactjs-ninja#343]
Fala Fernando, tudo bom? Passando pra deixar uma contribuição. 

Vi que no M2#10 ~17:00 min, teve problema para adicionar o teste de lançamento de exceção no ChaiJs.

Isso se deu porque o call da função map() deve ser feita pelo próprio assertion do ChaiJs.

Lançamento com parâmetros:
`expect(function () { fn(42); }).to.throw();`

`expect(() => fn(42)).to.throw();  // Function expression`

Lançamento sem parâmetros:
`expect(fn).to.throw();     // Good! Tests `fn` as desired`

No exemplo, deveria ter sido assim:

`
it('map([1, 2]) should throw a error with message "func is not a function"', () => {
  expect(() => map([1, 2])).to.throw('func is not a function');
});
`

No mais, material de excelente qualidade!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ozeas! Perfeito, muito obrigado pela contribuição =)
Revendo a aula, ficou meio "massivo" de assistir por causa dessas tentativas até chegar em uma solução "viável" =)

Vou editar e dar os créditos, muito obrigado :D

**Comment by ozeas** [comment]
Valeu cara, estou aproveitando cada minuto do curso. Excelente material.

Fico feliz em poder contribuir!!

Att.

**Comment by fdaciuk** [comment]
Show de bola! Fico feliz que está curtindo :D 
Qualquer coisa, só avisar :)
