### ISSUE TITLE
Problemas com função fetch

### ISSUE THREAD

**Issue by ThiagoLanza** [da2k/curso-reactjs-ninja#344]
Escreva aqui sua dúvida

@fdaciuk

Oi professores,

A minha função fetch do searchCep não está sendo chamada. Está tendo um problema no import do ajax, está dando a seguinte mensagem:

Could not find a declaration file for module '@fdaciuk/ajax'. 'c:/TesteReact/react_ninja_modulo_redux/node_modules/@fdaciuk/ajax/dist/ajax.min.js' implicitly has an 'any' type.
  Try `npm install @types/fdaciuk__ajax` if it exists or add a new declaration (.d.ts) file containing `declare module '@fdaciuk/ajax';`ts

Gostaria de saber se vcs poderiam me ajudar com isso.

Atenciosamente,

Thiago Lanza

**Comment by fdaciuk** [comment]
Oi @ThiagoLanza! Parece que você está usando TypeScript no seu projeto, correto? :)
O erro é relacionado a ele, não à lib :)

Não uso TS, mas pela mensagem de erro, parece que você precisa criar o que ele chama de "Declaration File" (provavelmente um arquivo que contém a extensão `.d.ts`), e no conteúdo dele, declarar esse módulo como mostrado na mensagem :)

Se não conseguir resolver, recomendo buscar ajuda em algum grupo específico de TS. Tem esse aqui no Telegram:
https://t.me/typescriptbr

=)
