### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by xneuber** [da2k/curso-reactjs-ninja#345]
Daciuk,

Estou aqui para dar um feedback sobre o curso no Udemy e:

> Para quem é este curso:
> Desenvolvedores com conhecimento básico / intermediário em JavaScript que queiram entender sobre como o ReactJS funciona, e todo o seu ecossistema.

Fiz o curso de JS Ninja oferecido por você que só tenho elogios, comecei-o acelerando, pois já tinha uma boa base de programação de linguagens muito clássicas e antigas: visual basic, pascal, delphi, c, c++. Com foco em redes e servidores linux também estudei bastante shell scrip, ou seja, ou com paradigmas procedural ou orientados a objetos, nunca tinha tido contato, ou até mesmo, conhecimento de programação funcional. E aos poucos fui me nivelando as aulas, até chegar a um ponto que eventualmente tinha que voltar algumas pra lembras de sintaxes ou conceitos, mas principalmente o que mais gostei foi da didática dos "desafios", pois nos exigia aplicar os conhecimentos apreendidos e, por consequência, fixá-los.
Acabava também criando a demanda de criar "colas" durante as aulas dos comandos e conhecimentos ensinados, pois era uma maneira "mais fácil" de replicá-las posteriormente e, também, consequentemente fixando mais ainda.
Quando investi nos dois cursos, foi devido a uma possibilidade de emprego em uma multinacional, com a oportunidade de me desgarrar de Goiás (estado extremamente conservador, com pouco foco na produção tecnológica em contraparte à facilidade da aquisição oferecida por outros estados) para me mudar para o Rio.
Daí, quando vim pro React, tudo totalmente diferente, muito, mas muito conceito seguido sem aplicações práticas, sem fixações, sem "desafios", chegou num ponto que estou sendo papagaio de pirata pra ficar replicando os comandos que você faz nas aulas pra ver os resultados se repetirem no meu browser ou console.
Sempre, mas sempre mesmo fui apaixonado por programação, mas as dificuldades da vida me difundiram de trabalhar no que conseguisse manter minhas necessidades básicas, e por isso, sempre tratei as oportunidades que me foram dispensadas, mesmo que discrepantes do meu sonho, com muita seriedade, exatamente pelo fato delas pagarem minhas necessidades.
O curso é ou era, não sei mais, a chance de isso tudo mudar e eu fazer o que mais gosto.
Não estou falando isso te imputando nenhuma responsabilidade sobre minhas frustrações não tá?! É só no sentido de dizer que: poxa, se você puder, me ajuda. Me indica alguma coisa mais prática, no sentido de praticar mesmo, pra eu absorver mais o conteúdo aqui aplicado. Ou então, mesmo que o curso seja oferecido com o público alvo mais experiente, entre alguns conteúdos e outros, coloca uns exercíciozinhos pra quem é iniciante nessa confusão que é js e programação funcional. Se puder me indicar alguma coisa, me retorne no e-mail por favor: xneuber@gmail.com Muito obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @xneuber! Entendo muito seu ponto, e sei o quanto é frustrante estudar alguma coisa e não conseguir fixar o conhecimento daquilo.

O curso de React foi pensado para ser fácil para inciantes mesmo, que acabaram de sair do JS - já tendo, ao menos, um certo conhecimento na linguagem.

Claro que, como uma biblioteca, o React tem seus "jeitos" de fazer as coisas funcionarem, e isso eu tento passar de maneira mais clara possível nas aulas.

Mas entendo claramente que muita coisa pode passar batido, e esse tipo de feedback só me ajuda a tentar melhorar ainda mais na hora de criar um conteúdo, e tentar deixá-lo o mais acessível possível, independente do nível da pessoa que está estudando :)

Eu lancei alguns desafios durante o curso de React, mas nada como no curso de JS, que era um desafio por aula mesmo.

O curso de React precisa ser um pouco mais dinâmico, por estarmos lidando com uma biblioteca.

Mas nada impede de eu te ajudar com isso, e até atualizar o curso futuramente - que é o que vai acontecer em breve - adicionando desafios, com base nesses feedbacks que tenho recebido :)

Bom, sem mais delongas, vamos ao que interessa:
Só com a prática é que vamos conseguir fixar, de fato, o aprendizado.

Conheço alguns repositórios que contém desafios de empresas, e esses podem te ajudar a praticar usando React, para ver até onde você vai. Os links são esses:

- https://github.com/wbraganca/desafios-de-ti
- https://github.com/alinebastos/dev-practice
- https://github.com/felipefialho/frontend-challenges

Escolha algum (ou alguns) desafios, e tente fazê-los com o conhecimento que você tem hoje.

Qualquer dúvida, fique à vontade para perguntar, como sempre, estou à disposição para ajudar no que for necessário para que você alcance, de fato, o nível Ninja!

Só preciso de uma coisa de você: não tenha vergonha de perguntar sempre que tiver dificuldade com algo. Não espero que a pessoa que esteja fazendo meus cursos saiba tudo, e só assista as aulas, e já aprenda tudo.

Se você está fazendo um curso, você QUER APRENDER. E as dúvidas são normais! Por isso me coloco à disposição pra te ajudar no que você precisar!

Independente da dúvida, pode perguntar à vontade, ok? :)

Abraços e bons estudos! :D
