### ISSUE TITLE
[Dúvida] react-router-dom

### ISSUE THREAD

**Issue by kaioduarte** [da2k/curso-reactjs-ninja#346]
Fala Daciuk, tudo certo?

Estou migrando um site em html para React e as páginas seguem o mesmo estilo:
- navbar
- conteúdo
  + barra de navegação interna
  + conteúdo de acordo com a barra lateral
- footer

Queria deixar o carregamento das páginas e subpáginas dinâmico, pra isso criei um arquivo de rota na pasta do layout e as vou criando recursivamente, entretanto só a primeira rota da barra de navegação interna dá match.

Montei o caso no CodeSandbox, se puder dar uma olhada eu fico agradecido =)

https://codesandbox.io/s/problema-com-react-router-dom-yzgs3

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @kaioduarte! Tudo ótimo :D
Vamos lá =)

Bom, pra começar, só uma dica: não sei se você está usando exatamente essa estrutura no seu app, mas você está carregando o `Root` à partir do index.js, e o App à partir do `Root`, os dois usando o `Route`. Não tem necessidade de fazer isso se você não vai precisar das props passadas pelo react-router, saca? 

No exemplo da React-zzaria, nós carregamos o `App` com o `Route`, pois lá no `App` nós usamos o `location` :)

Se isso tinha ficado claro pra você, ignore =)
Só comentei porque não tinha certeza se você estava usando exatamente essa estrutura ou não :)

---

Sobre a sua dúvida: a princípio parece estar tudo certo. Vou precisar baixar o projeto, para analisar com calma, debugando.
Assim que tiver uma resposta eu volto a comentar aqui :)

**Comment by kaioduarte** [comment]
Tem mais coisas, só deixei o menor código possível pra reproduzir o cenário.


`root.js`

```js
import React from 'react'
import { hot } from 'react-hot-loader'
import { BrowserRouter, Route } from 'react-router-dom'

import CssBaseline from '@material-ui/core/CssBaseline'
import MuiThemeProvider from '@material-ui/core/styles/MuiThemeProvider'

import App from './app'
import AuthProvider from 'contexts/auth'
import SnackbarProvider from 'contexts/snackbar'

import theme from 'theme'

const Root = () => (
  <SnackbarProvider>
    <AuthProvider>
      <CssBaseline />
      <MuiThemeProvider theme={theme}>
        <BrowserRouter>
          <Route component={App} />
        </BrowserRouter>
      </MuiThemeProvider>
    </AuthProvider>
  </SnackbarProvider>
)

export default hot(module)(Root)
```
`app.js`
```js
import React, { lazy, Suspense, useContext } from 'react'
import t from 'prop-types'
import { Redirect, Route, Switch } from 'react-router-dom'
import LinearProgress from '@material-ui/core/LinearProgress'

import { AuthContext } from 'contexts/auth'
import { SnackbarContext } from 'contexts/snackbar'

import PrivateRoute from 'components/private-route'

const Dashboard = lazy(() => import('layouts/dashboard'))
const Main = lazy(() => import('layouts/main'))

const LoginPage = lazy(() => import('pages/login'))
const NotFoundPage = lazy(() => import('pages/page-not-found'))
const RecoverPage = lazy(() => import('pages/recover-password'))

function App ({ location }) {
  const { userInfo } = useContext(AuthContext)
  const { notification } = useContext(SnackbarContext)

  if (userInfo.isAuthenticated && location.pathname === '/login') {
    return <Redirect to='/dashboard' />
  }

  return (
    <Suspense fallback={<LinearProgress />} >
      <Switch>
        <Route path='/login' component={LoginPage} />
        <Route path='/recover-password' component={RecoverPage} />
        <Route path='/page-not-found' component={NotFoundPage} />
        <PrivateRoute path='/dashboard' component={Dashboard} />
        <Route component={Main} />
      </Switch>
      {notification}
    </Suspense>
  )
}

App.propTypes = {
  location: t.object.isRequired
}

export default App
```

Fico no aguardo :grin:

**Comment by fdaciuk** [comment]
Fala @kaioduarte! Caramba, demorei pra debugar e entender tudo o que estava acontecendo haha :D 

Bom, vamos lá!

O problema é o `Switch` dentro da função `renderNestedRoutes`. Removendo ele, funciona como deveria :)

**Comment by kaioduarte** [comment]
Hahaha, valeu demais @fdaciuk!
