### ISSUE TITLE
[Dúvida] Multiplo Context API

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#347]
Estou curioso para saber como vai ficar o reactzzaria com mais informações no context já que o context/auth.js vai ser somente para o login.

Sei que uma pergunta difícil, mais tem previsão de quando vai lançar essa aula?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Essa semana, mais tardar na próxima, já vamos precisar fazer isso :)
Mas basicamente é criar um novo componente para a Context, usando o Provider, e envolver toda a aplicação com esse componente:

```
<AuthProvider>
  <OtherProvider>
    <AnotherProvider>
      ...
    <AnotherProvider>
   </OtherProvider>
</AuthProvider>
```

Basicamente dessa forma :)

**Comment by hjdesigner** [comment]
Que massa achei que era bem mais complicado 8)

**Comment by hjdesigner** [comment]
Outra dúvida, se eu quiser eu posso colocar o <OtherProvider> dentro de outro componente em vez ser tudo dentro do root.js?

**Comment by fdaciuk** [comment]
Claro, pode sim! Desde que o Provider envolva, ainda que de forma indireta, os componentes que vão consumir os dados desse Provider :)

**Comment by fdaciuk** [comment]
Eu prefiro deixar no componente principal apenas por questão de organização, mas nada impede de você usar um Provider mais "internamente" na aplicação, desde que nenhum componente acima dele precise dos dados desse Context :)
