### ISSUE TITLE
M3#A22 TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by CristianaYasuda** [da2k/curso-reactjs-ninja#349]
Escreva aqui sua dúvida
Bom dia,
Não sei porque está dando este erro. :(

×
←→1 of 2 errors on the page
TypeError: Cannot read property 'map' of undefined
Counters
C:/Users/cristiana.yasuda/Documents/create-react-redux-app/src/components/counters/index.js:8
   5 | 
   6 | const Counters = ({ counters, addCounter }) => (
   7 |   <div>
>  8 |     <div>
   9 |       {counters.map((counter, index) => (
  10 |         <Counter key={index} counter={counter} />
  11 |       ))}
View compiled

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CristianaYasuda! O seu erro é o seguinte:

```
TypeError: Cannot read property 'map' of undefined
```

Esse erro diz que não é possível ler a propriedade `map` de `undefined`. 

A variável `counters`, passada para esse componente `Counters`, deveria ser um array, pois só arrays têm esse método `map`. Mas ele está vindo como `undefined`. Esse é o problema :)

Agora, para resolver, é preciso analisar quem está passando essa prop `counters` para o componente, e tentar chegar no local onde esse array é inicializado.

Se você subir seu projeto aqui no GitHub, eu posso baixar ele, rodar na minha máquina, e te ajudar a descobrir onde está a origem do problema, se você não conseguir resolver :)

**Comment by CristianaYasuda** [comment]
Olá, Felipe já achei este erro e desculpe pelo incomodo :)
Estava no reducers, não tinha atribuído um array para o state.

**Comment by fdaciuk** [comment]
Sem problemas @CristianaYasuda! Fique à vontade para perguntar sempre que tiver dúvidas :)
Fico à disposição para ajudar :)
