### ISSUE TITLE
create-app

### ISSUE THREAD

**Issue by baltazarparra** [da2k/curso-reactjs-ninja#35]
Comecei o curso recentemente e tive alguns problemas relacionado a versões, tanto do próprio React quanto das ferramentas.

Vou começar a app do primeiro módulo, posso usar o create-app do react, ao invés do boilerplate que fizemos no começo do curso?

**Comment by fdaciuk** [comment]
Opa @baltazarparra! Foi mal, só vi sua mensagem agora :|
Se quiser me marcar quando tiver dúvida, assim não tem perigo de eu não ver a mensagem =)

Mas pode sim! A ideia de criar o boilerplate é pra entender como funcionam as configurações, mas fique à vontade para usar qual você achar melhor =)

**Comment by baltazarparra** [comment]
Foi mal, esqueci de marca, kkk. Valeu cara!

**Comment by fdaciuk** [comment]
ahah! De boa =)
Precisar de algo, só avisar :D
