### ISSUE TITLE
M3#A47 TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by CristianaYasuda** [da2k/curso-reactjs-ninja#350]
Escreva aqui sua dúvida
Boa noite Fernando,
De novo o mesmo erro, mas agora está na ul:
  4 | import * as filterActions from '../../redux-flow/reducers/visibility-filter/actions';
   5 | 
   6 | const TodoList = ({ todos, activeFilter, handleToggleTodo }) => (
>  7 |     <ul>
   8 |       {getVisibleTodos(todos, activeFilter).map((todo) => ( 
   9 |         <li 
  10 |         key={todo.id} 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CristianaYasuda! O problema é o mesmo: o retorno de `getVisibleTodos` não está sendo um array :)
Dá uma olhada nessa função, e se não conseguir resolver, sobe seu projeto aqui no GitHub e passa o link que eu dou uma olhada, ok? :)

**Comment by CristianaYasuda** [comment]
Fernando, mais uma vez obrigada. ;)

**Comment by fdaciuk** [comment]
Conte comigo sempre que precisar :)
