### ISSUE TITLE
[M4#A99] - Erro ao rodar "yarn dev" após atualizações

### ISSUE THREAD

**Issue by hiwoshu** [da2k/curso-reactjs-ninja#351]
E aí @fdaciuk, blz?

Eu instalei as atualizações como na aula, mas quando fui executar o projeto deu esse erro aki:

![ErroWebpackVersion](https://user-images.githubusercontent.com/39469118/60356744-240e8e80-99a8-11e9-8153-a6148979335e.png)

(caso não consiga ver) [ErroWebpackVersion.png](https://github.com/hiwoshu/reactzzaria/blob/master/ErroWebpackVersion.png)

Eu fiz o que a mensagem diz pra não fazer e atualizei manualmente o webpack pra versão que pede ali, e depois deu o mesmo erro com o `webpack-dev-server`, repeti o processo, só pra executar o projeto mesmo.

Queria saber qual a forma correta de corrigir isso sem afetar outros projetos na minha máquina

**Comment by fdaciuk** [comment]
Oi @hiwoshu! Você seguiu todos os passos da mensagem? Seguindo todos os passos corretamente não é pra ter erros :)

**Comment by hiwoshu** [comment]
Eu segui, até coloquei `SKIP_PREFLIGHT_CHECK=true` no arquivo .env, mas não deu certo. Então desinstalei o webpack global e instalei manualmente a versão que pedia ali na mensagem, fiz o mesmo com webpack-dev-server. Aí funcionou, mas agora dá o mesmo erro em outros projetos.

**Comment by fdaciuk** [comment]
Opa! Então, a ideia seria **não instalar** nem o webpack, nem o webpack-dev-server local.. provavalmente esse é o problema :)

Se não conseguir resolver, sobe o projeto aqui no GitHub que eu dou uma olhada :)

**Comment by hiwoshu** [comment]
Fiz o q vc disse mas não deu certo, então tentei de novo colocar SKIP_PREFLIGHT_CHECK=true no arquivo .env, e deu certo, ele executa, mas no terminal aparece essa mensagem:
```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
```
mas executa sem erro!

Segue o link: [reactzzaria](https://github.com/hiwoshu/reactzzaria)

**Comment by fdaciuk** [comment]
Perfeito, é isso mesmo então! Essa mensagem pode ignorar, isso precisa ser atualizado dentro do CRA, então é só aguardar a atualização deles :)

**Comment by hiwoshu** [comment]
ok, valew!

**Comment by fdaciuk** [comment]
Baixei aqui agora, e testei sem o `SKIP_PREFLIGHT_CHECK=true` no `.env` e rodou sem problemas :)
Se quiser tentar aí :)

Qualquer coisa, se der erro novamente, removendo a node_modules e o yarn.lock e instalando tudo do zero deve rodar certinho, como rodou aqui :)

**Comment by hiwoshu** [comment]
blz, vou testar e qqr coisa eu posto aki de novo
