### ISSUE TITLE
M3#A31 - Estou adicionando uma complexidade desnecessária ao refatorar?

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#352]
Oi professor!

Eu gostaria de uma opinião, se possível. Acabei de assistir a aula em que o reducer `todos` foi finalizado e está pronto para ser inserido na aplicação. O código final da aula ficou assim:  

```javascript
'use strict'

import { ADD_TODO, TOGGLE_TODO } from './actions'

export const initialState = []

const todos = (state = initialState, action) => {
  switch (action.type) {
    case ADD_TODO:
      return state.concat({
        id: action.payload.id,
        text: action.payload.text,
        completed: false
      })

    case TOGGLE_TODO:
      return state.map((todo) => {
        if (todo.id !== action.payload.id) {
          return todo
        }

        return {
          ...todo,
          completed: !todo.completed
        }
      })
  }

  return state
}

export default todos
```

Antes de iniciar a adição dele na aplicação, fiz um refactory. O código ficou um maior, mas a intensão foi quebrá-lo em funções menores. A dúvida é: estou adicionando uma complexidade desnecessária à aplicação? Essa pressa em refatorar pode ser prejudicial?

```javascript
'use strict'

import { ADD_TODO, TOGGLE_TODO } from "./actions";

const isIdSameAsPayloadId = (todo, { payload }) => todo.id === payload.id
const getToggledTodoItem = (todo) => ({ ...todo, completed: !todo.completed })

const toggleTodo = (state, action) => (
  state.map((todo) => isIdSameAsPayloadId(todo, action)
    ? getToggledTodoItem(todo)
    : todo
  )
)

const addTodo = (state, { payload }) => ([
  ...state,
  { id: payload.id, text: payload.text, completed: false }
])

export const initialState = []

const todos = (state = initialState, action) => {
  const { type } = action

  return type === ADD_TODO
    ? addTodo(state, action)
    : type === TOGGLE_TODO
      ? toggleTodo(state, action)
      : state
}

export default todos
```

Um abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! O Redux ele funciona bem baixo nível mesmo, como você deve ter percebido, então abstrações sempre serão necessárias, para tentar reduzir complexidade e duplicação de código desnecessárias :)

Quando se está aprendendo, quanto mais testes de coisas diferentes você fizer, melhor! Refatoração é uma delas! Esse é momento em que você refatora, volta como estava, e compara, para ver o que fica melhor :)

Mais pra frente eu vou mostrar uma forma melhor para criar os reducers, que poderá te dar alguns outros insights na hora de refatorar :)

O que eu te recomendaria é o seguinte: cuide apenas ao fazer isso em produção. Nem sempre uma refatoração é necessária, pois pode acabar deixando o código mais complexo.

Mas falando de estudos, faça quantas refatorações você conseguir! Teste, mude, apague, escreva novamente!

Isso vai te dar bons insights para quando você estiver fazendo aplicações reais, já ir pelo melhor caminho, pois você já vai ter passado por alguns durante seu aprendizado :)

**Comment by Roger-Melo** [comment]
Show. Muito obrigado, professor.

Falando em estados, será que há alguma chance da talk no Frontend SP  
ser subida pro YouTube?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa! Não sei dizer se foi gravada, mas se não foi, eu posso "refazer" ela no canal do YouTube em breve :)

**Comment by Roger-Melo** [comment]
Atualmente, o [canal deles](https://www.youtube.com/channel/UCbF7lt8Jwi0G8zq23rVoePg/featured) tem 1 vídeo e 1 inscrito (eu).  

A ideia de reproduzir a talk no formato de vídeo no queroser.ninja é excelente =)

![image](https://user-images.githubusercontent.com/29297788/61308643-0e320380-a7c7-11e9-9f82-2799f91cac0e.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Massa @Roger-Melo! Vamos tirar a dúvida xD

@eshinkawa sabe dizer se as talks do Frontend SP Meetup foram gravadas, e vão para o YouTube? :D

**Comment by eshinkawa** [comment]
@fdaciuk nao foram gravadas pessoal. vamos começar uns pilotos em breve.

**Comment by fdaciuk** [comment]
Perfeito, valeu @eshinkawa =)
@Roger-Melo em breve eu gravo então, e disponibilizo no canal [@queroserninja](https://youtube.com/queroserninja) no YouTube :)

**Comment by Roger-Melo** [comment]
Show, professor @fdaciuk , grava mesmo! =D

@eshinkawa , o Daciuk "kill the snake and show the stick", hahah. Obrigado =)
