### ISSUE TITLE
[MRW#06]Erro ao compilar ES2015

### ISSUE THREAD

**Issue by JuulioCampos** [da2k/curso-reactjs-ninja#353]
Cheguei na parte onde usaremos o ES2015, porém quando importo o Title no video MRW#06 no index.js fica com erro Uncaught SyntaxError: Unexpected identifier
print index.js http://prntscr.com/oe6ett
print app.js  http://prntscr.com/oe6f5s
print config http://prntscr.com/oe6fe0
print erro http://prntscr.com/oe6fmq
print do  console http://prntscr.com/oe6g7z

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JuulioCampos! Dá uma conferida você criou o arquivo `.babelrc` na raiz da sua aplicação, e se as versões das dependências estão corretas.

Você pode comparar com esse código aqui, que foi exatamente o que foi usado na aula:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-06

Qualquer coisa, só avisar :)
