### ISSUE TITLE
Dúvida/orientação projeto (backoffice)

### ISSUE THREAD

**Issue by trooper26** [da2k/curso-reactjs-ninja#354]
Boa noite, @fdaciuk.

Conforme postei em outra issue, estou aguardando os novos módulos referentes ao sistema interno da Reactzzaria. O curso está excelente!
Porém, como eles ainda não estão no ar e acredito que eles solucionariam meu problema, gostaria que você me tirasse uma dúvida e desse algum tipo de orientação para desenvolver um sistema backoffice (dashboard administrativo).

Trata-se de um projeto particular onde tenho uma API exposta e tenho que consumir os dados dela no React. Basicamente consiste em criar um CRUD e desenvolver as telas utilizando Material UI. São diferentes endpoints (referentes à diferentes "entidades") e tenho todos os métodos/verbos para integrar, por exemplo: Get by ID e Get all (Listagens), Post (Inserir novo), Put (Edição), Delete, etc.

Minha pergunta é: devo construir este projeto utilizando os conceitos mais atuais do React, como Hooks, Context API ou devo gerenciar os estados utilizando Redux?
Dependendo da resposta, você teria algum exemplo ou algum "norte" para me passar sobre como devo proceder e, principalmente, como estruturar este projeto, criando pastas separadas, chamando quais serviços, etc?

Sou muito novo no React, mas graças ao seu curso estou conseguindo progredir muito bem. Agradeço desde já qualquer ajuda e/ou orientação.

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @trooper26! Legal, fico feliz em saber que está curtindo :grin: 

Essa ideia de projeto que você pretende fazer é basicamente o que estamos fazendo na Reactzzaria mesmo :)

O que eu diria é pra você não se preocupar tanto com separação de coisas de início. Como eu mostrei na Reactzzaria, separe inicialmente em páginas. Depois, conforme a necessidade, você vai removendo duplicações, isolando componentes e regras lógicas, você pode ir criando diretórios separados.

Mas a estrutura de diretórios que temos na Reactzzaria hoje é praticamente a estrutura final. No máximo vamos adicionar mais um diretório, de widgets, para componentes compartilhados, mas que podem ter lógica embutida. Então esse projeto, da forma que está, pode te dar uma boa base :)

Não sei em que ponto do curso você está, mas se já entendeu como o React funciona, e como funcionam os hooks, pode seguir por esse caminho (com Hooks) sem problemas! Sua aplicação vai ficar mais simples, e você pode criar seus próprios hooks, quando necessário, para isolar certas regras de negócio da sua aplicação :)

Sobre usar Redux, o que eu faria hoje: se você precisa que o estado que vai ser compartilhado fique completamente isolado da aplicação, e você vai ter mais de um ambiente com a mesma aplicação (web, mobile, desktop, etc), e todos esses ambientes precisam compartilhar o mesmo "shape" do estado global, e as mesmas ações para modificar os valores no estado, aí vale a pena usar Redux.

Fora isso, o estado global pode ficar acoplado na aplicação, com o uso só da Context API e Hooks mesmo :)

Acho que é isso! Qualquer coisa, só avisar :)

**Comment by fdaciuk** [comment]
Oi @trooper26! Vou fechar a issue, mas se ainda tiver problemas, só avisar que eu te ajudo, beleza? :)
