### ISSUE TITLE
Dúvida sobre estrutura M3#A12

### ISSUE THREAD

**Issue by oliveirawesley** [da2k/curso-reactjs-ninja#355]
Falaaa Daciuk,

Qual a diferença de usar a estrutura como exibida no vídeo e esta estrutura (Que eu geralmente uso quando preciso trabalhar com statefull component)

```
import React, { Component } from 'react';
 
export default class  extends Component {
 
 state = {
    initial = 0
 }
  render() {
    return <div />;
  }
}
```

Muito Obrigado desde já!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @oliveirawesley! Essa sintaxe que você está usando ainda não entrou na específicação da linguagem, mas deve entrar em breve. Mais pra frente, nesse mesmo curso, eu mostro essa sintaxe mais nova, e que, apesar de ainda não estar na spec final da linguagem, você já pode utilizá-la com segurança usando babel, pois ela já está quase para entrar :)

**Comment by fdaciuk** [comment]
Oi @oliveirawesley! Conseguiu entender essa parte? Vou fechar a issue, mas se ainda tiver problemas, só avisar que a gente reabre e eu te ajudo, beleza? :)
