### ISSUE TITLE
Erro com o spacing 

### ISSUE THREAD

**Issue by zorasantos** [da2k/curso-reactjs-ninja#356]
Ola Professor!
Estou recebendo esse erro quando utilizo o spacing={40}
`
const Login = () => (
  <Fragment>
    <Grid container direction='column' alignItems='center' spacing={40}>
      <Grid item >
        <Logo />
      </Grid>
`
Erro:
index.js:1375 Warning: Failed prop type: Invalid prop `spacing` of value `40` supplied to `ForwardRef(Grid)`, expected one of [0,1,2,3,4,5,6,7,8,9,10].
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at login.js:7)
    in Login (created by Context.Consumer)
    in Route (at app.js:13)
    in Switch (at app.js:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at app.js:11)
    in App (at src/index.js:11)
    in ErrorBoundary (at src/index.js:9)

Não estou conseguindo resolver.
 
@fdaciuk

**Comment by zorasantos** [comment]
Desculpe-me professor, acho que pulei sem querer a parte do vídeo que soluciona esse problema.
Ja resolvi, obrigado! 
 @fdaciuk

**Comment by fdaciuk** [comment]
Opa, legal! Que bom que resolveu :) 
Qualquer coisa, só avisar :D
