### ISSUE TITLE
[M2#A43] - Não consigo instalar o storybook

### ISSUE THREAD

**Issue by JessPergentino** [da2k/curso-reactjs-ninja#357]
Boa noite professor,

Estou tentando usar o storybook no projeto do gitApp, porém não consegui. Olhei nas outras issues, tentei seguir o mesmo procedimento e não consegui resolver. Já tentei segui o quick Start que está no site do storybook e tbm não consegui rodar.

Esse é erro q aparece ao tentar pelo comando visto na aula:

![img01](https://user-images.githubusercontent.com/30954713/61673683-d8a98080-acc6-11e9-802d-cb4bb73964bc.PNG)

Esse é o erro q aparece ao tentar pelo quick start do storybook:

![img02](https://user-images.githubusercontent.com/30954713/61674216-51a9d780-acc9-11e9-8e8a-f475c419276b.PNG)

![img05](https://user-images.githubusercontent.com/30954713/61674219-566e8b80-acc9-11e9-806b-183eddd49b16.PNG)

[Link Repositório](https://github.com/JessPergentino/curso-reactjs-ninja-udemy.git)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JessPergentino! Você chegou a instalar o `getstorybook` na versão apresentada [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#m2a30-e-m3a43)?

Baixei o seu projeto e instalei com essa versão, e correu tudo bem :)

Me deixe saber se você já fez isso, pra gente ver se o problema pode ser outro, ok? :)

Vou te acompanhar até isso funcionar! :D

**Comment by JessPergentino** [comment]
Sim, fiz uma nova tentativa com está versão e subi para o projeto no repositorio para q o senhor possa dar uma olhada. Não consegui rodar da mesma formar, pareceu os mesmo erros de antes ao tentar rodar o comando getstorybook, e ao tentar rodar o comando npm run storybook ele diz q start-storybook não é reconhecido como um comando interno.

**Comment by fdaciuk** [comment]
Beleza, vamos tentar outra coisa então :)
Olhando no repositório, as dependências já estão no projeto.
Então tente fazer o seguinte: remova o diretório `node_modules` e o arquivo `package-lock.json`, e execute novamente `npm install`, para instalar todas as dependências juntas.

Me diga se isso funciona pra você :)

**Comment by JessPergentino** [comment]
Funcionou sim, muito obrigada professor. Agora é dar continuidade as aulas. Valeu :)

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :D
