### ISSUE TITLE
Problema para logar e redirecionar

### ISSUE THREAD

**Issue by tmx01** [da2k/curso-reactjs-ninja#358]
Olá Fernando Estou tentando utilizar o conhecimento do curso para criar um app para treinar enquanto você vai postando as aulas, eu tenho um api de autenticação que quando loga ele traz o nome, cpf e token, problema que não estou conseguindo redirecionar para main?

//auth.js

const logar = useCallback((e) => {
        e.preventDefault();
        let usuario = signIn(e.target.usuario.value, e.target.senha.value)
        setUsuarioInfo({
            isusuarioLoggedIn: true,
            usuario
        })
    }, []);

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tmx01! Consegue compartilhar seu código todo, pra eu entender onde você está tentando fazer o redirecionamento?

**Comment by tmx01** [comment]
`import React, { createContext, useCallback, useState } from 'react';
import t from 'prop-types';

export const AuthContext = createContext();

function Auth({ children }) {
    const [usuarioInfo, setUsuarioInfo] = useState({
        usuarioLogado: false,
        dadosUsuario: null
    });

    const logar = async (usuario, senha) => {
        let dadosUsuario = await signIn(usuario, senha);
        setUsuarioInfo({
            usuarioLogado: true,
            dadosUsuario
        });
    };

    const logout = useCallback(() => {
        setUsuarioInfo({
            usuarioLogado: false,
            dadosUsuario: null
        });
    }, []);

    return (
        <AuthContext.Provider value={{
            logar,
            logout,
            usuarioInfo,
            setUsuarioInfo
        }}>
            {children}
        </AuthContext.Provider>
    )
}

const signIn = async (usuario, senha) => {
    const data = { usuario, senha };
    const requestInfo = {
        method: "POST",
        body: JSON.stringify(data),
        headers: new Headers({
            "Content-Type": "application/json"
        })
    };
    fetch("http://localhost:3005/usuario/login", requestInfo)
        .then(response => {
            if (response.ok) return response.json();
        })
        .catch(error => (
            console.log(error)
        ))
};

Auth.prototypes = {
    children: t.node.isRequired
}

export default Auth;`

**Comment by fdaciuk** [comment]
Oi @tmx01! Você fechou a issue porque conseguiu resolver, ou foi sem querer? :)

**Comment by tmx01** [comment]
foi sem querer aidna não consegui resolver ;)

**Comment by fdaciuk** [comment]
@tmx01 só olhando seu código parece estar correto. Você consegue subir ele em um repositório do GitHub, onde eu consiga baixar o código e colocar pra rodar na minha máquina pra testar, e entender onde pode estar o problema?

**Comment by tmx01** [comment]
@fdaciuk  estava tentando com o fetch, instalei o axios e deu certo, obrigado.

**Comment by fdaciuk** [comment]
Ah, saquei! Olhando novamente seu código aqui, vi que faltou retornar a resposta do `fetch` na função `signIn`. Provavelmente funcionaria com o `fetch` também, apenas usando `return fetch(...)` nessa função :)

**Comment by fdaciuk** [comment]
Mas legal, que bom que deu certo! Qualquer coisa, só avisar :)
