### ISSUE TITLE
Não está gerando o arquivo style.css no final da index M2#A39

### ISSUE THREAD

**Issue by RafaelMouraFrontend** [da2k/curso-reactjs-ninja#359]
Quando dou: npm run build, não consigo fazer com que ele gere o style na pagina dist e dentro do index.html

Se puder me ajudar, ja perdi algumas horas e nada estou travado aqui...

Segue o link do repo que subi oq estou fazendo:
https://github.com/RafaelMouraFrontend/NinjaReact/tree/master/githubapp_with_assets

@fdaciuk

**Comment by RafaelMouraFrontend** [comment]
Já resolvi professor tá safe

**Comment by fdaciuk** [comment]
Oi @RafaelMouraFrontend! Legal, que bom que resolveu :)
Qualquer coisa, só avisar :D
