### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by baltazarparra** [da2k/curso-reactjs-ninja#36]
Ex.

``` js
{!!actorsObj && <Actors actorsObj={actorsObj}/>}
```

Desta forma, eu consigo fazer que, o componente só seja renderizado quando eu preencher este objeto, mas...
E se eu quiser que ele seja renderizado, apenas se **todos** valores dentro deste objeto estejam preenchidos, como faço?

@fdaciuk

**Comment by fdaciuk** [comment]
Falae @baltazarparra =)
Nesse caso, você precisa criar testar as propriedades uma a uma pra garantir os valores corretos. Uma coisa que você pode fazer é criar uma função para validar esses valores, e usar algo do tipo:

```jsx
{isValid(actorsObj) && <Actors actorsObj={actorsObj}/>}
```

E a função isValid seria algo como:

```js
const isValid = (obj) => {
  return obj.name !== undefined &&
    obj.status === 'active'
}
```

Só exemplo dos valores, mas ae você testa como precisar.

Outra coisa que você pode fazer é normalizar o objeto. Usar uma função que receba esse objeto e, se alguma propriedade não foi preenchida, essa função passa um valor "default" pra essa propriedade.

Uma terceira opção ainda seria usar o `defaultProps` dentro do componente, passar cada propriedade desse objeto como `prop` no componente e setar valores default dentro do próprio componente =)

Tem várias formas de fazer, ae só escolher a que se encaixa melhor no seu projeto =)

**Comment by baltazarparra** [comment]
Valeu mano @fdaciuk !!!

**Comment by fdaciuk** [comment]
Qualquer dúvida só avisar :D
