### ISSUE TITLE
M2#A43 Problema storybook 

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-reactjs-ninja#360]
ao instalar as dependencias , apresenta o erro :
 • Installing dependencies. ✖

apos executar o storybook apresenta 👍 
PS C:\Users\Thiag\Documents\Ninja\atividades\curso-reactjs-ninja\rascunho> npm run  getstorybook
npm ERR! missing script: getstorybook
npm ERR!
PS C:\Users\Thiag\Documents\Ninja\atividades\curso-reactjs-ninja\rascunho> npm run  getstorybook
npm ERR! missing script: getstorybook
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     storybook
npm ERR!     build-storybook

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thiag\AppData\Roaming\npm-cache\_logs\2019-07-29T16_44_43_179Z-debug.log
PS C:\Users\Thiag\Documents\Ninja\atividades\curso-reactjs-ninja\rascunho>

OBS: com as dependencias no package, deletei a pasta node_modules e o arquivo package-look.json e executei o npm i.
tbm execultei o comando storybook -f e deletei o o  @storybook/react
nada funcionou 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @TMiranda7! Suas dependências estão alinhadas com o [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md)?

Se sim, compartilha comigo seu projeto, que eu baixo aqui e dou uma olhada no que pode estar acontecendo :)

**Comment by fdaciuk** [comment]
Ah, olhando a mensagem de erro, pode ser ainda que você está só digitando errado o nome do script. Você está tentando rodar `npm run getstorybook`, mas o comando, conforme mostrado na aula, é `npm run storybook` (sem o `get`) :)

Dá uma olhada também se pode ser isso :)

**Comment by TMiranda7** [comment]
cara , era só isso mermo , foi desatenção , vlw , tava quebrando a cabeça aqui

**Comment by fdaciuk** [comment]
Show! Que bom que resolveu :D 
Qualquer coisa, só avisar :)
