### ISSUE TITLE
M3A90 TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by zorasantos** [da2k/curso-reactjs-ninja#361]
Ola Professor!
Estou fazendo o reactflix. Apareceu esse erro depois que fiz isso na aula M3A90
`const VideosList = ({ videos }) => (
    <Container>
        {Object.keys(videos).map((id) => (
            <Video key={id}>
                <VideoThumb>
                    <PlayStyled />
                </VideoThumb>
                <VideoTitle>{videos[id].title}</VideoTitle>
            </Video>
        ))}
    </Container>
)`

![Capturar](https://user-images.githubusercontent.com/36997341/62266927-adc6d700-b400-11e9-8f1c-f5dfc5f8e858.PNG)
![Capturar](https://user-images.githubusercontent.com/36997341/62266975-dcdd4880-b400-11e9-9163-3da198394723.PNG)

Gostaria que o professor me explicasse um pouco sobre esse erro. Obrigado! 
Link do meu repositorio: https://github.com/zorasantos/desafio-100-Days-Of-Code/tree/master/Fifteenth%20Day/reactflix

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @zorasantos! O problema é que você está usando a entrada `videos` do state do redux [com o `v` minúsculo](https://github.com/zorasantos/desafio-100-Days-Of-Code/blob/master/Fifteenth%20Day/reactflix/src/components/videos-List/index.js#L57), mas na hora de definir o valor do state à partir do reducer principal, [você usou `V` maiúsculo](https://github.com/zorasantos/desafio-100-Days-Of-Code/blob/master/Fifteenth%20Day/reactflix/src/redux-flow/reducers/index.js#L6) :)

Padronize isso que vai funcionar certinho :)

Minha dica é manter tudo minúsculo: nomes de variáveis, diretórios, arquivos, etc. Assim você evita problemas desse tipo :)

**Comment by zorasantos** [comment]
Muito obrigado professor! Me desculpe por ter cometido um erro bobo desses kkk
Vou seguir sua dica.

**Comment by fdaciuk** [comment]
Sem problemas meu caro :)
Qualquer dúvida, fique à vontade para perguntar :)
