### ISSUE TITLE
thumnail video-list Reactflix

### ISSUE THREAD

**Issue by zorasantos** [da2k/curso-reactjs-ninja#362]
Ola Professor! Gostaria de uma dica sua de como eu posso fazer para aparecer o thumbnail nos videos do video-list da aplicação reactflix.

Muito obrigado! 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @zorasantos! O YouTube serve as thumbs à partir dessa URL:

```
http://i3.ytimg.com/vi/ID_DO_VIDEO/maxresdefault.jpg
```

Se você substituir o `ID_DO_VIDEO` pelo ID que você já tem cadastrado, você consegue pegar a thumb :)

Aí pode usar ela como background do componente `VideoThumb`, por exemplo :)

Pra fazer isso é bem simples:
- Passe uma prop `id` para o `VideoThumb`, com o ID do video;
- No styled do VideoThumb, adicione o CSS assim:

```
background: url('http://i3.ytimg.com/vi/${(props) => props.id}/maxresdefault.jpg') 50% 50% no-repeat;
background-size: cover;
```

Veja que ali no meio tem uma função. Essa função pode ser usada em qualquer lugar dentro da string do styled component, e ela recebe as props que o componente recebe. No caso, só precisamos retornar a prop ID no local correto para renderizar o background :)

**Comment by zorasantos** [comment]
Muito obrigado professor! Deu certo.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
