### ISSUE TITLE
M1#A28 - Introdução à formulários no React - Vídeo não abre

### ISSUE THREAD

**Issue by amcravila** [da2k/curso-reactjs-ninja#363]
Escreva aqui sua dúvida

O vídeo da aula 40. M1#A28 - Introdução à formulários no
React, não está abrindo. Ocorre erro:

_"Erro no Vídeo
Tentamos reproduzir seu vídeo diversas vezes, mas ocorreu um problema inesperado. Nossos engenheiros foram notificados.

Acesse https://helpx.adobe.com/flash-player.html para verificar se o Flash está habilitado no seu navegador.

Com o Flash habilitado, tente novamente em alguns minutos ou entre em contato com o suporte."_

O Flash está instalado e habilitado, visto que os demais vídeos abrem normalmente.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @amcravila! :)
A Udemy parece estar corrompendo alguns vídeos :\
Vou refazer o upload desse vídeo. Tente acessar novamente dentro de uns 10 minutos que já deve funcionar novamente :)

**Comment by amcravila** [comment]
Vídeo OK, Problema resolvido! Muito Obrigada!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :D
