### ISSUE TITLE
M2#A139

### ISSUE THREAD

**Issue by rafaelsevla** [da2k/curso-reactjs-ninja#365]
Quando eu rodo o comando  de teste acontece esse erro:

Mesmo tendo corrigido isso na aula anterior criando aquele "alias" pro jest interpretar o .css de outra forma

``` FAIL  src/components/button/button.test.js
  ● Test suite failed to run

    /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/src/components/button/button.css: Unexpected token (1:0)
      > 1 | .button {
          | ^
        2 |   border: 0;
        3 |   color: #fff;
        4 |   font-weight: 700;

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.147s
Ran all test suites.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|

Watch Usage: Press w to show more.
```

link do repo: https://github.com/rafaelsevla/markdown-editor

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @rafaelsevla! Cara, por algum motivo, seu arquivo `config/CSSStub.js` foi criado com um espaço no final!

Renomeie o arquivo, e salve novamente sem adicionar um espaço no final que vai funcionar :)

Você deve estar se perguntando como eu descobri isso, certo? Vou mostrar algumas evidências:
- se você acessar o arquivo pela [interface do GitHub](https://github.com/rafaelsevla/markdown-editor/blob/master/config/CSSStub.js%20), vai ver que, ainda que o arquivo tenha a extensão `.js`, o code highlight do GitHub não funcionou;
- outra coisa: dê uma olhada nessa URL acima: veja que tem um `%20` no final do nome do arquivo. Esse é o código para "espaço em branco", ao decodificar URLs :)
- Se estiver em um ambiente unix (Linux, Mac, ou com o Ubuntu no Windows), tente usar algum comando que autocomplete o nome do arquivo. Por exemplo: 
```
cat config/CS<PRESSIONE_O_TAB>
```

Ao executar o comando acima, e pressionar o TAB após o CS, se o seu terminal estiver configurado pra isso, ele deve autocompletar o nome do arquivo. Você vai ver que ele vai ficar assim:

```
at config/CSSStub.js\ 
```

Com uma contra-barra, e um espaço no final =)

Enfim, só pra você saber como eu descobri o problema. Renomeie o arquivo que vai funcionar :)

**Comment by rafaelsevla** [comment]
caraca era isso mesmo auhsaushauhsauhsua o pior é q eu ainda recriei esse arquivo varias vezes pelo vscode

talvez tenha sido o editor q colocou esse espaço

valeu @fdaciuk!!

**Comment by fdaciuk** [comment]
haha! Pode ser :)
Qualquer coisa, avisa ae :)
