### ISSUE TITLE
Como trabalhar com grandes cargas de dados em aplicações React

### ISSUE THREAD

**Issue by Roger-Melo** [da2k/curso-reactjs-ninja#366]
Oi, professor!

O que vc disse no comentário da issue referenciada abaixo é muito interessante =)

Pretende inserir esse conteúdo nesse último módulo do curso?

> No andamento do curso tem um exemplo de implementação do map recursivo usando setTimeout ?

> Ainda não, mas vou deixar anotado aqui pra fazer um exemplo e mostrar como trabalhar com grandes cargas de dados em aplicações React :)

_Originally posted by @fdaciuk in https://github.com/da2k/curso-reactjs-ninja/issues/111#issuecomment-380466291_

**Comment by fdaciuk** [comment]
Oi @Roger-Melo! Eu acabei não mostrando isso, mas como os primeiros módulos serão atualizados em breve, já adicionei no meu roteiro para tratar desse assunto :D

**Comment by Roger-Melo** [comment]
Excelente, professor. Muito obrigado! =)
