### ISSUE TITLE
[M1#A3] - http-server

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#369]
Olá Fernando.

Estou refazendo o curso e logo de cara estou precisando de ajuda para instalar o http-server.

Uso o HighSierra 10.13.6 com Node.js v10.16.3 npm v6.9.0 e quando faço:
npm i http-server
![image](https://user-images.githubusercontent.com/8005205/63476522-93a87380-c457-11e9-95ff-b32da07330ba.png)
e ele indica que instalou o + http-server@0.11.1

Mas quando chamo http-server
![image](https://user-images.githubusercontent.com/8005205/63476567-c5213f00-c457-11e9-8c2d-f1e5fb42eea6.png)
ele não encontra a instalação.

Não vejo a instalação dele quando listo os pacotes com o npm
![image](https://user-images.githubusercontent.com/8005205/63476635-32cd6b00-c458-11e9-8176-27d33369ac40.png)

Agradeço por ajuda.

@fdaciuk

**Comment by Alexandre1202** [comment]
Ja vi que ja vamos usar o webpack Dev server e dispensa o http-server.

Valeu @fdaciuk

**Comment by fdaciuk** [comment]
Isso mesmo @Alexandre1202! O http-server não será necessário nesse momento inicial do curso :)
