### ISSUE TITLE
M2#A51 - Dúvida Gulp

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#37]
Boa tarde mestre @fdaciuk,

Voltei nessa aula, e acabei tendo uma dúvida.

Qual o principal motivo de criar aquele watch de lint no gulp, sendo que ja temos o watch lint que é mostrado no dashboard ?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa =)

Então, a ideia do lint direto no gulp é pra usar junto com o Jest. Já que o Jest tem uma interface específica de watch para os testes, não rola rodar o lint junto, então temos que rodá-lo em uma task separada.

Só por isso =)

**Comment by gabrielferreiraa** [comment]
Entendi ! Valeuuu

**Comment by fdaciuk** [comment]
Qualquer dúvida só gritar =)
