### ISSUE TITLE
MRW02 - instalação webpack

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#371]
Oi Fernando. Tudo bem?

Faz tempo que instalei o webpack e estou voltando a fazer o curso agora. Vi todos os posts sobre esse módulo e nenhum deles é específico para esse erro:
![image](https://user-images.githubusercontent.com/8005205/63818121-d1087780-c915-11e9-95e7-d4276babffd4.png)

Quando chamo o webpack ele dá erro. Sei que ele precisa estar estalado globalmente mas não está funcionando então pelo que entendi é problema na instalação dele global. Mas está dando erro da instalação. 
Primeiro eu tomei o erro, depois fiz : npm uninstall webpack depois eu fiz npm install -g webpack@1 e tomo esse erro da imagem. 

Por favor alguma dica? 

@fdaciuk

**Comment by Alexandre1202** [comment]
oi @fdaciuk 

Segui esse roteiro para desinstalar o node e npm
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

E depois instalei o node a partir do nvm como você sugeriu. Depois voltei na aula que começa a falar sobre o webpack para seguir os passos.... que já decorei...rs.... mas ainda não está funcionando muito bem.

**Comment by Alexandre1202** [comment]
oi @fdaciuk 

Segui esse roteiro para desinstalar o node e npm
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by Alexandre1202** [comment]
Em seguida instalei o webpack em modo de desenvolvimento

![image](https://user-images.githubusercontent.com/8005205/64078430-f815cf00-ccb0-11e9-9c6c-d9be220070fd.png)

**Comment by Alexandre1202** [comment]
Instalei o eslint e o webpack em modo global 
![image](https://user-images.githubusercontent.com/8005205/64078444-1f6c9c00-ccb1-11e9-8db7-e7b5dccbef77.png)

**Comment by Alexandre1202** [comment]
Tudo parecia ir bem até quando chamei o webpack

![image](https://user-images.githubusercontent.com/8005205/64078451-4a56f000-ccb1-11e9-9178-d7386e45691b.png)

**Comment by Alexandre1202** [comment]
Tentei seguir a orientação do próprio npm e fiz o audit
![image](https://user-images.githubusercontent.com/8005205/64078542-5ee7b800-ccb2-11e9-88da-9109c020fe9b.png)

**Comment by Alexandre1202** [comment]
Mas o problema persiste
![image](https://user-images.githubusercontent.com/8005205/64078548-79219600-ccb2-11e9-927e-4656016a1efd.png)

**Comment by Alexandre1202** [comment]
@fdaciuk 

Vou continuar vendo stackoverflow e orientações da comunidade para ver se resolvo o problema mas agradeço se tiver mais alguma sugestão.

**Comment by Alexandre1202** [comment]
@fdaciuk 

RESOLVIDO

O próprio repositório do nvm tinha a solução. Bastava instalar o webpack-cli globalmente.

![image](https://user-images.githubusercontent.com/8005205/64078604-18df2400-ccb3-11e9-93ee-250776fb627b.png)

**Comment by Alexandre1202** [comment]
@fdaciuk aceito sugestão para corrigir o problema que ele alertou em amarelo na imagem acima.

**Comment by Alexandre1202** [comment]
Também consegui instalar o webpack-dev-server e executar-lo mas nessa versão ele não está obedecendo o publicPath do webpack-config.js

![image](https://user-images.githubusercontent.com/8005205/64079056-ff40db00-ccb8-11e9-87df-e21cda04b640.png)

**Comment by Alexandre1202** [comment]
Esse é o meu webpack-config.js

```
'use strict'

const path = require('path')

module.exports = {
  entry: path.join(__dirname, 'src', 'index'),
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  }
}
```

**Comment by Alexandre1202** [comment]
Também notei que ele não obedeceu o filename do webpack-config.js pois ele identificou exatamente o que já está na aplicação, ou seja, o index.js.

Tudo funcionou depois que ajustei no index.html fazendo simplesmente assim:

```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h1>React Ninja - Home page</h1>
</head>

<body>
   <script src='/index.js'></script> 
</body>
</html>
```

**Comment by Alexandre1202** [comment]
![image](https://user-images.githubusercontent.com/8005205/64079126-18965700-ccba-11e9-90b4-004818de8b12.png)

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! A instalação do node e npm funcionaram certinho, pelo jeito :)
Agora é só instalar o webpack na versão mostrada no [arquivo de versões de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que tudo vai funcionar como mostrado nas aulas :)

**Comment by Alexandre1202** [comment]
Obrigado

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
