### ISSUE TITLE
 Problema durante a execução do Webpack

### ISSUE THREAD

**Issue by nexusnx** [da2k/curso-reactjs-ninja#373]
Boa tarde Daciuk.  Eu estou com um erro estranho, verifiquei os códigos e todos parecem ok. Não sei se é um erro por conta das versões do webpack ou do babel.    Os códigos estão no GitHub: https://github.com/nexusnx/MRW-9.

 Uncaught Error: Cannot find module "sourcemapped-stacktrace"
 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @nexusnx! Com esse código do seu repositório, o erro que apareceu aqui é o:

```
ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token (9:4)
```

Confere pra mim se ele está atualizado, por favor? :)

**Comment by fdaciuk** [comment]
Se for esse mesmo o erro, só faltou adicionar no seu projeto o arquivo [`.babelrc`](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/react-webpack/mrw-09/.babelrc) =)

**Comment by nexusnx** [comment]
Acabei de upar o .babelrc.

O erro que aparece ainda é o  `Uncaught Error: Cannot find module "sourcemapped-stacktrace"`

**Comment by fdaciuk** [comment]
OI @nexusnx! Tente remover o diretório node_modules e o arquivo package-lock.json, e fazer a instalação novamente, com `npm install`. Isso deveria resolver :)

Me diz se deu certo :)

**Comment by brunaoflofl** [comment]
para mim aparece esse erro depois de fazer a instalação da aula 7, modulo 2 (npm install --save-dev babel-core@6 babel-jest@15)

erro:   Couldn't find preset "es2015" relative to directory "/home/bruna/reactNinja/modulo2/jest-in-practice"

**Comment by fdaciuk** [comment]
Oi @brunaoflofl! Você chegou a instalar esse preset no seu projeto? :)

**Comment by brunaoflofl** [comment]
oi, estou seguindo os links de instalação com as versões indicadas.. esse link das versões foi diferente do link que vc usou no video..

**Comment by brunaoflofl** [comment]
Deu certo! obrigada!

**Comment by fdaciuk** [comment]
Oi @brunaoflofl! Sobre esse comentário aqui:

> oi, estou seguindo os links de instalação com as versões indicadas.. esse link das versões foi diferente do link que vc usou no video..

Consegue me dizer em qual vídeo, e qual dependência está errada pra eu corrigir? :)
