### ISSUE TITLE
Acessar a aplicação externamente

### ISSUE THREAD

**Issue by kallylacerda** [da2k/curso-reactjs-ninja#374]
Como faço para permitir o acesso externo da aplicação? (usando CRA)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kallylacerda! Não sei se entendi muito bem sua dúvida, mas vamos lá:
assim que você termina de escrever sua aplicação, usando o CRA, você pode executar o comando `npm run build` (ou `yarn build`, se estiver usando `yarn`).

Isso vai gerar um diretório `dist` na raiz da sua aplicação, com todos os arquivos estáticos necessários para subir para algum servidor.

Basicamente, nesse diretório vai conter os HTML, CSS e JS, já transpilados, e prontos para serem acessados no navegador sem a necessidade de qualquer ferramenta especial, como o webpack, por exemplo.

É só pegar o conteúdo desse diretório e fazer deploy no seu servidor que ele já vai ficar acessível para qualquer pessoa com acesso à internet :)

Estamos quase finalizando o projeto Reactzzaria, no módulo 4, e eu vou mostrar como fazer isso de forma detalhada, pode ficar tranquilo :)
