### ISSUE TITLE
Exercicios

### ISSUE THREAD

**Issue by colzerah** [da2k/curso-reactjs-ninja#376]
Olá, duvida se o curso tem exercícios assim como o JS Ninja

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @colzerah! Esse curso não usa o mesmo formato de desafios do JS Ninja. A ideia é mostrar o uso do React dentro de pequenas aplicações que vamos construindo no decorrer do curso, e com isso você consegue ver na prática como o React funciona, e aprender novos conceitos de programação, como Programação Funcional, e estruturas de dados, por exemplo :)

Durante o desenvolvimento dessas aplicações, eu vou lançando alguns desafios referentes às próximas aulas, para que você consiga testar se realmente entendeu o que está sendo passado nas aulas =)

**Comment by colzerah** [comment]
opa Obrigado!
