### ISSUE TITLE
Component de confirm global

### ISSUE THREAD

**Issue by john182** [da2k/curso-reactjs-ninja#377]
Bom tarde tudo bem ??? seria possível incluir um component de confirm na aplicação da pizzaria, tentei criar e não conseguir controla o estado do component. Ex

Teria um componet no App onde ele poderia ser chamado em qualquer lugar da aplicação que apos confirmar eu iria executar alguma função no comp que fez a sua chamada

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @john182! Consegue sim :)
Como você quer um componente que compartilhe o estado de forma global com qualquer outro, você pode usar a Context API para compartilhar essa informação com outros componentes (chamar o `confirm`, passar as ações que ele vai executar, etc) :)

**Comment by john182** [comment]
Então mesmo se baseando no que foi usado no curso não conseguir realizar o procedimento.

**Comment by fdaciuk** [comment]
Então, é que existem várias formas de se fazer. Você pode usar a Context API que foi mostrada no curso, mas para esse caso, não exatamente como foi mostrado.

Mas com conhecimentos de componentização no React você consegue se virar! Vou te mostrar uma das formas que isso pode ser feito:
https://codesandbox.io/s/awesome-bohr-goh6o?fontsize=14&module=%2Fsrc%2Fapp.js

Tudo o que está nesse código já foi visto no curso. Dá uma olhada lá, e se tiver alguma dúvida, me avisa que eu vou explicando :)

**Comment by john182** [comment]
Opa @fdaciuk pela atenção realmente eu vi que foi demonstrado o uso de callBack hooks e tal, o conceito eu entendir, porem estou com dificuldade em aplicar. Alem do mais todos os projeto que terei que fazer será com TS, pois mesmo tanto replicar o seu código pra testa em TS estou com dificuldade. está dando uns erros aqui.

**Comment by john182** [comment]
@fdaciuk conseguir colocar pra roda aqui usando TS, mais to achando muito complexo o código pra entendimento, isso usando como referência o Angular já que a proposta do React e como ele é vendido é pra ser algo mais pratico. Não sei se estou fazendo as coisas da forma correta.

**Comment by fdaciuk** [comment]
Oi @john182! Não vou conseguir te ajudar com a parte de TS, porque não tenho trabalhado com essa ferramenta.

Mas o que você acha que está complexo de entender? É basicamente a chamada de uma função que vai carregar um componente, nada mais :)

**Comment by john182** [comment]
Então o que achei complicado foi a forma que foi pensando usando um promisse  e como foi chamado openConfirm dentro do dialog, Já que no Angular eu apenas usaria um service um observable. Mais sei que ali no  nada mais do que JS e tem plenitude que tenho que dominar o JS, como o Angular ajuda muito nessas coisas fico viajando pela falta de conhecimento. Emfim o que to tentando simular agora no reactzzeria é a pagina não encontrada <Route path="*" component={NotFound} /> mais no ta caindo nessa rota rsss. OBS joguei dentro do Main e do APP

**Comment by fdaciuk** [comment]
Entendi! Bom, a ideia de usar Promise, foi apenas para o caso de você ter uma ação assíncrona acontecendo ao clicar no botão de ação do `Confirm`. Se não usasse Promises, antes da ação finalizar, o `Confirm` já fecharia.

Com o uso da Promise, você consegue mostrar um loading, ou algo do tipo, para que o usuário saiba que algo está acontecendo :)

No caso do Angular, ele tem a forma dele de fazer as coisas. Ao trabalhar com React, por ele ser apenas uma biblioteca, é muito importante o conhecimento de JavaScript puro.

A vantagem de se estudar a linguagem é que você não fica preso a uma biblioteca ou framework. Se amanhã ou depois você precisar usar outra ferramenta, conhecendo JavaScript você consegue migrar sem muitas dificuldades :)

Sobre a página 404 na Reactzzaria: o componente deve ficar no `Main` mesmo :)

**Comment by john182** [comment]
@fdaciuk entendo mesmo é o caso do uso do ORM como o entity ou Hibernate  você não tem muita ideia das querys que são geradas já com o Daper o cara tem que ter uma noção de SQL.

Creio que com os estudo com React o conhecimento de JS iria rola.

Com relação ao 404 tente fazer ele nunca cair no 404

**Comment by fdaciuk** [comment]
Para a página 404, você só precisa adicionar um Route sem path no final da lista de Route, dentro do Main :)

Qualquer rota que não esteja configurada para carregar algum componente, vai carregar esse :)

Ainda vamos ver isso no curso, fique tranquilo :)

**Comment by john182** [comment]
@fdaciuk ha blza vou aguarda eu tinha colocado no Path="*"
