### ISSUE TITLE
Linter do Standard Issue

### ISSUE THREAD

**Issue by mafideju** [da2k/curso-reactjs-ninja#378]
E aí @fdaciuk, tudo bem? 

No seguinte código:
```
  state = { isFetching: false }

  handleSearchCep = async (e) => {
    e.preventDefault()
    this.setState({ isFetching: true })
    const response = await Axios
      .get(`http://apps.widenet.com.br/busca-cep/api/cep.json?code=${e.target.cep.value}`)
    this.props.updateAddress(response.data)
    this.setState({ isFetching: false })
  }
```

Tem com um _warning_ que me incomoda:
```
(Emitted value instead of an instance of Error) 

   8:3  error  'state' is not defined            no-undef
  10:3  error  'handleSearchCep' is not defined  no-undef
```
Parece que o linter não reconhece ES6, pois usando _contructor_ e  _class methods(function declaration)_ os erros somem. Adicionei dois novos plugins, o _package.json_ e o _.babelrc_ ficaram assim:
```
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",

{
  "presets": [
    "env",
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties",
    [
      "transform-runtime",
      {
        "helpers": false,
        "polyfill": false,
        "regenerator": true
      }
    ]
  ]
}
 ```
Como a configuração do _lint_ está vindo do _standard_ e não tenho acesso ao _.eslintrc_ dele, não estou conseguindo pegar esses caras. 

Na página do _standard_ ha muito pouca informação... Tem uma pista?

**Comment by fdaciuk** [comment]
Oi @mafideju! Esse código está dentro de uma class? 
Consegue me mostrar o seu código completo? De preferência, suba o projeto em um repositório aqui no GitHub, que eu consigo baixar e ver onde exatamente ele está acusando os problemas :)

**Comment by mafideju** [comment]
Ah claro, @fdaciuk, segue abaixo o link do repo, é basicamente a aplicação da aula em cima do boiler do curso, com um pequeno ajuste na estrutura de folders. 

https://github.com/mafideju/ReduxToDo

**Comment by fdaciuk** [comment]
Oi @mafideju! A v11 do standard já está com essa atualização =)
Se quiser, pode instalar as versões mais recentes do standard e standard-loader, que esses warnings não irão mais aparecer :)

Você provavelmente terá outros warnings relacionados à v16 do React, mas esse da `class` vai sumir :)

**Comment by mafideju** [comment]
Ok @fdaciuk, resolvido. 

Os outros _warnings_ que surgiram são autoexplicativos e assim fica mais fácil de resolver *=)*

Agora achei os docs do _Standard.js_ e entendi do que se trata,é uma outra configuração de linter, mais simples de usar pois já vem configurado. Já tinha visto _Airbnb_ e era naquela base que estava mais acostumado.

Obrigado!!!

**Comment by fdaciuk** [comment]
Legal @mafideju! Sim, o standard já vem com uma configuração base por padrão :)
Eu prefiro ele ao invés do AirBnB, porque ele não te restringe em muita coisa, só cobra para que você padronize seu código. As regras do standard são bem enxutas :)

Mas é isso! Que bom que deu certo!
Qualquer coisa, só avisar :)
