### ISSUE TITLE
Dúvidas CSS Modules

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#38]
Bom dia meu querido @fdaciuk, tudo certo ?

Aqui estou eu praticando meu lindo React. Até o momento estou usando a estrutura inicial sua, passada em aula, de CSS Modules, com CSS puro, importando ele dentro do JS e colocando no `className`. Porém, agora vi a necessidade de ter uma estrutura parecida com um ambiente de pré processadores.

Preciso ter um arquivo de CSS centralizado, com as cores padrão do meu site por exemplo, as fontes padrão, usar uma classe de forma global, importando um `mixin` por exemplo. Como o CSS Modules de comporta diante disso ? Eu vi que ele tem um tal de `composes`, mas não achei tão interessante rs, acho que não usei ele pra valer mesmo. Você acha necessário usar SASS juntamente com o CSS Modules, ou você acha desnecessário ? 

Consegue me dar uma mão / ajuda em relação a isso? Qual seria o ambiente adequado para trabalhar com CSS dentro da estrutura do React com Webpack ?

Grande abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Fala meu garoto =)

Você pode usar pré-processadores com CSS Modules sem problemas =)

Se quiser usar sass ou stylus por exemplo, só buscar por `sass-loader` e/ou `stylus-loader`, adicionar na entrada de loaders do webpack e boa =)

Como o `css-loader` já resolve `@imports` no código, você pode utilizar um diretório padrão para esses CSS que serão "globais", e criar um alias pra eles. Pra importar no CSS, você só precisa adicionar o `~` na frente, se for um alias ou se for uma dependência da node_modules =)

Exemplo: vc quer importar o `colors.styl` que está no diretório `./src/css`. Se tiver um alias `css` apontando pra esse diretório, dentro de qualquer arquivo do stylus você pode importá-lo assim:

```styl
@import '~css/colors.styl'

// use as cores do arquivo `colors.styl` aqui dentro =)
```

Ficou claro? =)

**Comment by gabrielferreiraa** [comment]
Entendi, mas por exemplo, eu tenho um arquivo, `default.scss`, e um `menu.scss`, sei la, só exemplo.

`default.scss:`
```
$colorDefault: #666;
```

e no `menu.scss` eu tenho:
```
/* a pasta css teria o alias que criei no webpack */
@import '~/css/default.scss';'

.menuColor {
   color: $colorDefault;
}
```

Após isso, quando eu for usar esse arquivo dentro do JS, eu vou chamar o SCSS ou o CSS ? O fluxo é SCSS > CSS > JS ? O Css vai ser executado antes do `import` do JS ?

Essa parte de estruturação de CSS com o webpack e ES6 ficou meio nebulosa pra mim hahaha

Valeu pela força !

**Comment by fdaciuk** [comment]
Pra importar você importa sempre o arquivo que você tem, no caso o `.scss`. No webpack, com o loader ele vai analisar o SCSS, converter pra CSS com o `css-loader`, e então vai usar ou o `style-loader` pra colocar na tag style esse CSS final, ou o `ExtractTextPlugin` pra gerar um arquivo externo =)

**Comment by fdaciuk** [comment]
Sábado passado eu fiz uma live falando exatamente sobre isso, talvez pode ajudar, dá uma olhada:
https://www.youtube.com/watch?v=5Z_RUWMtVTo

**Comment by gabrielferreiraa** [comment]
Vou assistir a live, se eu tiver alguma dúvida volto a encher seu saco aqui na issue! hahaha valeuuu

**Comment by fdaciuk** [comment]
Show! Vou fechar a issue, mas se tiver dúvida a gente reabre e continua :D
