### ISSUE TITLE
96. M2#A30 - Conhecendo o Storybook

### ISSUE THREAD

**Issue by bqdesigner** [da2k/curso-reactjs-ninja#380]
Opa, Fernando!
Na aula 96. M2#A30, estou tendo problemas para instalar o storybook. Ao executar getstorybook, 

```
• Detecting project type. ✓
• Adding storybook support to your "Webpack React" app. ✓
 • Preparing to install dependencies. ✓


• Installing dependencies. ✖

An error occurred while installing dependencies.

```
ele aparece o erro acima. Para realizar essa aula, clonei o diretório **mrw-10 de react-webpack**.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @bqdesigner! Consegue ver qual versão do `getstorybook` você instalou?

**Comment by bqdesigner** [comment]
Sim, eu estou utilizando a versão que foi listada por ti em ``` versions-of-dependencies ```. A versão é ``` getstorybook@1.6.1 ```

Após instalar, o ``` package.json ``` fica assim:
``` json

{
  "scripts": {
    "start": "node server.js",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "react-hot-loader": "^3.0.0-beta.2",
    "standard": "^11.0.1",
    "standard-loader": "^4.0.0",
    "webpack": "^1.15.0",
    "webpack-dev-server": "^1.16.5",
    "webpack-validator": "^3.0.0",
    "@kadira/storybook": "^2.21.0"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}

```

**Comment by fdaciuk** [comment]
Show! Deixa eu colocar pra roda aqui, e já te digo o que está acontecendo :)

**Comment by fdaciuk** [comment]
@bqdesigner você está usando `npm` ou `yarn`? Tente instalar manualmente as dependências, pode ser algum problema de permissão no seu diretório.

Apague o diretório `node_modules`, o arquivo `yarn.lock` e o arquivo `package-lock.json` (se algum desses existir), e então execute novamente a instalação das dependências, com `npm install`, se estiver usando NPM, ou `yarn`, se estiver usando Yarn :)

**Comment by fdaciuk** [comment]
Oi @bqdesigner! Não acredito que seja por conta do boilerplate, porque eu testei o mesmo aqui e funcionou certinho. Você está usando windows? Consegue subir seu projeto em um repositório aqui no GitHub pra eu ver se pode ser alguma específica desse projeto?

**Comment by bqdesigner** [comment]
[Aqui](https://github.com/bqdesigner/react-storybook), @fdaciuk.

**Comment by fdaciuk** [comment]
Oi @bqdesigner! Baixei, e instalei as dependências aqui.. ele dá alguns warnings, mas finaliza com sucesso.

No seu caso, dá algum erro mesmo? Ou você consegue rodar `npm run storybook` sem problemas?

**Comment by bqdesigner** [comment]
Oi, @fdaciuk, continua dando o mesmo erro =/
Confesso que não sei o que mais fazer kkkk.

**Comment by fdaciuk** [comment]
Mas o erro é que não consegue instalar as dependências, isso?
Manda um print pra eu ver :)

**Comment by bqdesigner** [comment]
Olá, @fdaciuk, segue a imagem. Tentei novamente instalar o storybook de maneira globa, ``` npm i -g getstorybook ``` e depois dei o comando ```getstorybook```. 

![image](https://user-images.githubusercontent.com/42852056/66587379-ab9b9a00-eb60-11e9-84cc-aa2da5dbe450.png)

**Comment by fdaciuk** [comment]
Mas após esse erro, você tentou rodar só `npm install`? Tente isso :)

**Comment by bqdesigner** [comment]
@fdaciuk, funcionou! Cara, tu é um Deus. Obrigado :) :) :)

**Comment by fdaciuk** [comment]
haha! Bem menos :joy: :joy: 

Que bom que deu certo :)
Qualquer coisa, só avisar :D

**Comment by nogueirajsx** [comment]
yarn add global getstorybook@1.7.0
yarn run storybook
