### ISSUE TITLE
Erro ao subir o servidor

### ISSUE THREAD

**Issue by FelipeSdS** [da2k/curso-reactjs-ninja#381]
Boa Noite !!!!
Estou no segundo modulo, na aula MRW#05, e me deparei com um erro que não estou conseguindo resolver, fiz as instalações de acordo com o "version of dependencies" e não encontrei nada diferente no código, e nada foi alterado no bundle.js .... por isso estou apelando para o HELP !!!! D: kkkk

Segue imagem do Erro : https://uploaddeimagens.com.br/imagens/erroreact-png

Repository Git : https://github.com/FelipeSdS/React-Ninja-Acomp 

Obs .. Pasta "Modulo 2  - React + webpack"
Obs 2 .. Estou usando VSCode para fazer as aulas.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @FelipeSdS! Veja que a mensagem de erro diz:

![ErroReact](https://user-images.githubusercontent.com/487669/66997813-8d2a2700-f0a9-11e9-9b73-d81ae98f36d1.png)

Isso significa que o elemento "alvo" que foi passado para o método `ReactDOM.render()` não é um nó HTML válido.

No seu caso, isso aconteceu porque você usou o [`querySelectorAll`](https://github.com/FelipeSdS/React-Ninja-Acomp/blob/master/Modulo%202%20-%20%20React%20%2B%20Webpack/src/index.js#L9) ao invés do `querySelector`. O `querySelectorAll` retorna uma `NodeList` (lista de nós do DOM), e não um elemento só, como o `querySelector`.

Fazendo essa alteração, tudo deve funcionar corretamente :)

---

Dica: mantenha o arquivo `package.json` no seu projeto, para que você consiga, facilmente, acompanhar as versões que instalou, e consiga reinstalar mais facilmente, quando necessário. E quando subir um repositório no GitHub, crie um arquivo `.gitignore` na raiz do seu projeto, e adicione nesse arquivo `node_modules`. Dessa forma esse diretório sempre será ignorado quando você fizer `push` :)

**Comment by FelipeSdS** [comment]
Funcionou certinho, muito obrigado professor :D

Obrigado pela dica vou seguir sim :D
@fdaciuk

**Comment by fdaciuk** [comment]
Perfeito meu caro! Qualquer dúvida, só avisar :)
