### ISSUE TITLE
Centralizar estados no React Hooks

### ISSUE THREAD

**Issue by LuanDc** [da2k/curso-reactjs-ninja#383]
Estou no modulo 2 do curso, mas estava pesquisando sobre React Hooks pra poder refatorar minha aplicação que uso como "cobaia" dos meus estudos. Queria saber se ainda com o uso do React Hooks, devemos centralizar todo o estado da aplicação em um único componente. Não entendi como nesse caso faria sentido, já que todo componente no React Hooks é um stateless. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @LuanDc! No módulo 4 você vai ver com mais detalhes sobre os Hooks no React.
Mas, à partir do momento em que você usa Hooks em um componente, ele deixa de ser stateless, e se torna stateful, pois ele passa a ter estado internamente.

Então, se você estiver escrevendo uma aplicação, usando o padrão "Container / Presentational", você pode seguir o mesmo padrão, só que sem usar classes: o componente stateful é a função que manipula os hooks, e os stateless são os componentes abaixo desse, que não manipulam estado :)

**Comment by LuanDc** [comment]
Show, então se eu quisesse refatorar minha aplicação pra usar Hooks eu só mudaria o componente stateful? os outros continuariam da mesma forma, correto?

**Comment by fdaciuk** [comment]
Sim, essa é uma forma de fazer :)
