### ISSUE TITLE
MRW#06 Usando o sistema de modulos do ES6/2015

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#384]
Olá @fdaciuk 

Estou revendo o curso e com dificuldades para executar o webpack-dev-server. O erro que eu tenho é esse:

```
✖ ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
```

Conforme a imagem abaixo:
![image](https://user-images.githubusercontent.com/8005205/68555085-a1dcaf00-040a-11ea-936a-a76e90ecdfc3.png)

O meu .babelrc que está na raiz do projeto é:

```
{
    "presets": ["es2015", "stage-0"]
}
```

O webpack.config.js é:

```
'use stritc'

const path = require('path')

module.exports = {
    entry: path.join(__dirname, 'src', 'index'), 
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'main.js',
        publicPath: '/static/'
    },
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel'
        }]
    }
}

```

E o package.json é:

```
{
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.9.0"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}
```

Troquei o loaders por rules com base em algumas referências mas ele continua não achando o babel e o babel-loader, pois apresenta o erro a seguir:
![image](https://user-images.githubusercontent.com/8005205/68555300-c71ded00-040b-11ea-896f-8343d20848fe.png)

Ajustei o loader: 'babel' para loader: 'babel-loader'  e mesmo assim ele reclama do babel:
![image](https://user-images.githubusercontent.com/8005205/68555353-224fdf80-040c-11ea-9e41-8e91fe39ab74.png)

Por favor pode me ajudar a solucionar o problema?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Ajustando a sua versão do webpack, tudo deve funcionar como esperado :)
Siga as versões usadas no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que vai funcionar conforme esperado :)

**Comment by mafideju** [comment]
Que legal!! conheci o curso do @fdaciuk através de indicação do @Alexandre1202 em um processo seletivo na Optum!!! BTW, se estiver precisando me liga que estou procurando ;)

Pelo que tenho visto, o Webpack 4 e o Babel 6 não 'falam' com o React 15 muito bem. Estas versões precisam ter alguma relação temporânea, ou seja, precisam ter sido lançadas em datas equivalentes para garantir sua compatibilidade. A implementação atual do React (16.11) provavelmente apresentará problemas quando usadas com Webpack 1, por exemplo. Caso queira usar a versão mais recente, atualize apenas o React, porém as explicações dadas no módulo 2 não serão as soluções para os problemas que estas versões mais novas apresentam, mas com certeza há muitas soluções e helpers de migração...
