### ISSUE TITLE
M01#A37 Erro após passar o conteúdo do App.js para AppContent

### ISSUE THREAD

**Issue by jghagemann** [da2k/curso-reactjs-ninja#385]
Fala Daciuk! Tudo tava mil maravilhas até que eu efetuei a passagem do conteúdo do App.js para AppContent.js conforme o vídeo e nada mais renderizou na tela.
A mensagem que tenho no console é: 
Uncaught TypeError: Cannot read property 'string' of undefined Repos.js:23

Essa linha aponta para o seguinte conteúdo:
```
Repos.propTypes = {
  className: React.propTypes.string, //linha 23 aqui
  title: React.propTypes.string.isRequired,
  repos: React.propTypes.array
}
```
Até realizar a troca pro componente AppContent.js os props e todo resto funcionava certinho, tô procurando o que possa ser mas não dou jeito de corrigir

@fdaciuk

**Comment by jghagemann** [comment]
Achei o Erro!
pra passar os propTypes dentro de Repos.propTypes o React.PropTypes tem que ter o "P" maiúsculo. Agora lembrei que tinhas falado isso em um vídeo passado!

**Comment by fdaciuk** [comment]
Opa! Isso mesmo :)
Qualquer coisa, só avisar :)
