### ISSUE TITLE
Plugin & TypeScript

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#386]
Oi Fernando

Estou no video 62. M1#A50 que você explica sobre trabalhar com Plugins & Manipular o DOM.

Tenho curiosidade de saber se por acaso é com Plugin que se usa TypeScript no React e mesmo se não for, por favor, quando você recomendaria a utilização de TypeScript.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Na verdade não :)

Esses plugins que eu mostro na aula, são plugins que serão utilizados em runtime (quando a aplicação estiver rodando).

No caso do TypeScript, você só vai usá-lo em ambiente de desenvolvimento, para conseguir usar tipos estáticos no seu código. Mais ou menos o que você consegue fazer com o `PropTypes` :)

Então você pode usar TypeScript se quiser, mas recomendo aprender a usá-lo primeiro, fora do React, para depois tentar usar com React.

Assim as coisas devem ficar mais claras :)

**Comment by Alexandre1202** [comment]
Muito obrigado.

**Comment by fdaciuk** [comment]
Qualquer coisa só avisar :)
