### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by jeanbarcellos** [da2k/curso-reactjs-ninja#388]
Olá, professor!

Sou seu aluno e estou iniciando o modulo 4! :D

Vi em uma outra issue (#166), um aluno perguntando se iria ter React Native neste curso e tu respondeste que não. 
Você poderia indicar algum(ns) Curso de Reative Native Online, para eu dar prosseguimento logo após eu concluir este de React.js Ninja???

Desde já, grato!

Abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jeanbarcellos! Não tenho nenhum curso em específico pra te recomendar, mas com o seu conhecimento de React afiado, a documentação do [React Native](https://facebook.github.io/react-native/) já vai te ajudar a iniciar sem muitas dificuldades :)

Existem alguns grupos também no Telegram, por exemplo, onde você poderá tirar dúvidas com as pessoas que estão usando RN:

Grupo de React no Telegram: https://t.me/reactjs_br
Grupo de React Native no Telegram: https://t.me/reactnativedrops

=)
