### ISSUE TITLE
dúvida na aula M4#A80

### ISSUE THREAD

**Issue by JSaints-Dev** [da2k/curso-reactjs-ninja#389]
Professor, tem alguma configuração que está corrigindo meu código, vou citar um exemplo...
...estou na aula M4#A80 e na função que checa se o usuário está logado ou não do arqui App, o segundo parametro da função...segue o ex abaixo...
digito assim como na aula...

```
// check if user is logged in
  useEffect(() => {
    firebase.auth().onAuthStateChanged((user) => {
      console.log('dados do usuário: ', user)
      setUserInfo({
        isUserLoggedIn: !!user,
        user
      })
    })
    window.logout = logout
  }, [ ])
```

mas ao salvar ele altera para a seguinte forma...

```
// check if user is logged in
  useEffect(() => {
    firebase.auth().onAuthStateChanged((user) => {
      console.log('dados do usuário: ', user)
      setUserInfo({
        isUserLoggedIn: !!user,
        user
      })
    })
    window.logout = logout
  }, [logout, setUserInfo])
```
...ou seja, ele está setando com as func que estão vindo AuthContext, isso pode me gerar problema?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JSaints-Dev! Não há probelma não :)
Provavelmente você deve ter algum plugin no seu editor com integração com o React que já faz esse tipo de correção. Mais pra frente eu ainda vou mostrar isso, mas pode ficar traquilo que está corretíssimo fazer dessa forma :)

**Comment by JSaints-Dev** [comment]
Thanks Professor
@fdaciuk

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
