### ISSUE TITLE
[Dúvida] createClass

### ISSUE THREAD

**Issue by juliocarneiro** [da2k/curso-reactjs-ninja#39]
Boa noite meu querido!
Estou com uma duvida a umas 3 lições já, no meu console está aparecendo um warning de createClass deprecated, segue:

Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

Fui dar uma olhada mas não estou entendendo muito bem, sou bem leigo em React o que sei estou aprendendo no curso!

Grande abraço

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, fala @juliocarneiro, tudo certo? =)

Esse warning foi um erro do time do React.. aconteceu pois até a versão 15.4 estava tudo ok. Como na versão 16 eles vão remover o `createClass` e o `PropTypes` da lib principal - eles colocaram em libs separadas - na versão 15.5 eles deixaram esse warning, que é bem chatinho, mas é só um aviso mesmo, não precisa se preocupar nesse momento =)

Seguindo com o curso, você vai ver que vamos atualizar todas as ferramentas que estamos usando =)

Se não quiser mais ver esse warning, é só instalar a versão específica do react. Vou ver onde eu falo sobre a instalação do React e deixar uma dica sobre essa instalação lá, mas é basicamente instalar o React assim:

```
npm install --save react@15.4 react-dom@15.4
```

Isso já deve resolver os warnings por enquanto =)

Qualquer dúvida, só avisar =)

**Comment by juliocarneiro** [comment]
Muito obrigado cara!
Abraço

**Comment by fdaciuk** [comment]
Qualquer coisa grita ae!
