### ISSUE TITLE
M1#A27 - propTypes - Aula do futuro

### ISSUE THREAD

**Issue by leovictor** [da2k/curso-reactjs-ninja#390]
Na aula M1#A27 fala para verificar as propTypes utilizando React.PropTypes, entretanto foi movido para a bibliotec prop-types, certo?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leovictor! Isso mesmo :)
No curso eu peço para usar as versões exatas para que você consiga seguir com o aprendizado sem problemas. Mas mais pra frente eu vou mostrando o que será modificado nas versões mais recentes do React. Então se você usar as versões conforme o arquivo de dependências, você vai conseguir seguir com o curso sem problemas. Se for usar as versões mais recentes logo no início do curso, pode ter algumas diferenças mesmo, ok? :)
