### ISSUE TITLE
Aula16. MRW#08 - Configurando nossa aplicação para usar o React hot loader

### ISSUE THREAD

**Issue by santosdvlpr** [da2k/curso-reactjs-ninja#391]
Olá Prof Fernamdo!!! Deu tudo certo até o video 7. Mas no video 8 ( aula16. MRW#08 - Configurando nossa aplicação para usar o React hot loader) não fui bem sucedido.
Ao executar o comando "npm start" no terminal tenho "webpack:Compiled successfully " e o servidor levanta escutando na porta 3000 mas quando chamo no browser a pagina esperada não aparece em vez disso aparece uma pagina de erro com a mensagem "Cannot GET /".
O meu projeto pode ser visto em https://github.com/santosdvlpr/react-webpack.
Humbeto S Pinto.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @santosdvlpr! Nesse seu projeto não tem a index.html, criada na aula 2 desse módulo :)
Se você quiser comparar seu código atual com o código das aulas, [aqui nesse diretório](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack) tem a listagem exata de tudo o que foi usado, inclusive as versões exatas das dependências usadas =)

**Comment by santosdvlpr** [comment]
Sim. Verdade estavam faltando alguns arquivos. Completei com o "index.html" e o "app.js" e mais "index.js, bundle.js e bundle.js.map". 
OBS: O GitHub me mandou esta mensagem "We found potential security vulnerabilities in your dependencies."  me alertando acerca da versão de alguns pacotes. Segui as instruções do curso para fazer as instalações. Vou repetir todos os passos em um novo projeto. mas se vc puder me dar mais algumas dicas sobre este problema, desde já agradeço.

**Comment by fdaciuk** [comment]
Essa mensagem do GitHub é porque realmente algumas versões de bibliotecas podem ter problemas de segurança, que foram resolvidos em versões mais recentes. Mas essas versões mais recentes podem não ser compatíveis com o que você estará vendo nesse momento no curso, então pode ignorar sem problemas essa mensagem, pois essas dependências nunca são usadas em produção (onde seria de fato o problema), mas apenas para desenvolvimento, ok? :)

**Comment by paula8oliveira** [comment]
Oi Fernando! Sobre essa mesma aula, quando executo o comando "npm start" retorna um erro no meu terminal, já pesquiser sobre mas não consigo achar uma solução, você pode me ajudar?

Segue o erro:

Paulas-MacBook-Pro:react-webpack oliveirapaulaa$ npm start

> @ start /Users/oliveirapaulaa/Desktop/react-course/react-webpack
> node server.js

**/Users/oliveirapaulaa/Desktop/react-course/react-webpack/server.js:7
new WebpackDevServer(webpack(config), {
^^^**

SyntaxError: Unexpected token new
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oliveirapaulaa/.npm/_logs/2019-12-04T17_20_53_134Z-debug.log

**Comment by fdaciuk** [comment]
Oi @paula8oliveira! Provavelmente tem algo a ver com o código que está na linha antes dessa onde ele exibiu o erro. Consegue subir seu projeto aqui no GitHub e compartilhar aqui pra eu dar uma olhada?

**Comment by paula8oliveira** [comment]
Tá aqui: https://github.com/paula8oliveira/react-webpack

Obrigada! :)

**Comment by fdaciuk** [comment]
Oi @paula8oliveira! Rodei aqui seu projeto, mas deram outros erros. Antes de tentar resolver esses erros, remova o diretório `node_modules` e o arquivo `package-lock.json` do seu projeto, e então instale novamente as dependências com `npm start` :)

Com isso, os erros que irão disparar serão:

Erro de sintaxe [nessa linha](https://github.com/paula8oliveira/react-webpack/blob/master/server.js#L12). Tem um parênteses sobrando. Ao invés de `(err)) => `, deveria ser `(err) =>`.

O outro erro é também um erro de sintaxe. Faltou uma vírgula ao final [dessa linha](https://github.com/paula8oliveira/react-webpack/blob/master/webpack.config.js#L14).

E por fim, um erro de referência, pois você usou uma função chamada `required` (com um `d` no final) [nessa linha](https://github.com/paula8oliveira/react-webpack/blob/master/webpack.config.js#L4). O correto é `require` :)

Seguindo esses passos, a aplicação deve subir sem problemas :)

**Comment by paula8oliveira** [comment]
Super obrigada, Fernando! Vou corrigí-los e te deixo saber se deu tudo certo. :)

**Comment by fdaciuk** [comment]
Perfeito! Qualquer dúvida, só avisar :)

**Comment by paula8oliveira** [comment]
Tudo funcionando perfeitamente! Obrigada, Fernando!

**Comment by fdaciuk** [comment]
Show de bola @paula8oliveira! Qualquer coisa, só avisar :)
