### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by vgsilva** [da2k/curso-reactjs-ninja#393]
Estou no video 14, estamos fazendo as alterações pra short hand notation, e após utilizar o export default Title, e import Title from './app', o seguinte erro é exibido no console: **Cannot use import statement outside a module**

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @vgsilva! Consegue subir seu código em um repositório aqui no GitHub pra eu dar uma olhada em como você está fazendo? :)

**Comment by fdaciuk** [comment]
Oi @vgsilva! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver dúvidas com relação a esse problema, só comentar aqui que eu te ajudo a resolver, ok? :)
