### ISSUE TITLE
M1#A09 - get Default props

### ISSUE THREAD

**Issue by paula8oliveira** [da2k/curso-reactjs-ninja#394]
Oi Fernando! Tudo bem?
Estou com um probleminha que aconteceu logo no início dessa aula. Alterei o códio do arquivo app.js, usando o getDefaultProps, no terminal deu tudo certo, mas no console me retornou esses 2 warnings:

1. Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

2. React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.

 o código tá atualizado aqui: https://github.com/paula8oliveira/react-webpack

Obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @paula8oliveira! Pode ignorar esses warnings por enquanto :)
O primeiro vai ser coberto em algumas aulas, em breve, pois ele é referente à versão v15.5 do React.

O segundo é por causa da versão do `react-hot-loader` que você instalou: usando a versão mostrada no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), você não verá mais esse warning :)

Tem algumas outras dependências ali que também podem dar problema. Seguindo as versões do arquivo de dependências, você consegue seguir sem dificuldades :)

Se quiser comparar o seu código com os arquivos de cada aula, pode acompnhar por aqui:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

Cada diretório é de uma aula :)

---

**Detalhe importante:** não é necessário versionar o diretório `node_modules`. Ele só vai deixar seu projeto maior na hora de fazer `push` para o GitHub :)

Para remover esse diretório do seu git é bem simples:
- Remova o diretório;
- Faça um commit, para adicionar a remoção ao histórico do git;
- Crie um arquivo `.gitignore` que tenha somente `node_modules` como conteúdo;
- Adicione e faça um commit desse arquivo;
- Rode novamente `npm install` para gerar a `node_modules`, dessa vez fora da sua árvore do git :)

**Comment by paula8oliveira** [comment]
Entendido, Fernando, mas ainda assim no browser não vejo a atualização, deveria aparecer "Olá, desconhecido". Mas vou comparar os códigos e te aviso qualquer coisa.

**Comment by fdaciuk** [comment]
Esses warnings não deveriam afetar a funcionalidade da aplicação. Vou baixar seu projeto aqui também, e te aviso quando eu encontrar o problema :)

**Comment by fdaciuk** [comment]
Oi @paula8oliveira! Faltou só você passar a _prop_ `name` nessa linha:
https://github.com/paula8oliveira/react-webpack/blob/master/src/app.js#L16

Você chamou o componente `Title`, mas não passou a prop que ele estava esperando :)
