### ISSUE TITLE
M02#A35 "loader must be a string"

### ISSUE THREAD

**Issue by jghagemann** [da2k/curso-reactjs-ninja#396]
Após instalar e configurar o webpack-dashboard conforme a aula, aparece a mensagem "loader must be a string" em vermelho logo após executar o comando npm start.

Antes de instalar o dashboard funcionava normalmente

@fdaciuk

**Comment by jghagemann** [comment]
Achei o problema:

nos loaders de css estava como loader ao invés de loaders antes do array. Corrigi e funcionou :)

**Comment by fdaciuk** [comment]
Opa, legal que achou o problema @jghagemann! Qualquer coisa, só avisar :)
