### ISSUE TITLE
M02#A39   TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by jghagemann** [da2k/curso-reactjs-ninja#397]
Após aplicar o ejs
```
<%= compilation.assets['crp.css'].source() %>
```
no style do template dá esse erro, está inclusive em vermelho no arquivo template do github, copiei direto de lá também pois poderia ter escrito algo errado, mas dá erro também.
O VSCode ainda flagra em vermelho todas as < quando uso esse código pois aparentemente não reconhece, não tô conseguindo avançar nas aulas assim.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jghagemann! Chegou a ver se as versões das bibliotecas que você está usando bate com as versões usadas na aula? Dá uma olhada [nesse arquivo aqui](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md).

Se estiver tudo certo, compartilha comigo seu projeto aqui no GitHub que eu dou uma olhada e te ajudo com isso, mas a probabilidade do problema ser a versão de uma dependência é bem grande :D

**Comment by fdaciuk** [comment]
Sobre o VSCode deixar em vermelho, provavelmente é só alguma configuração do editor. Você precisa instalar um plugin pra ele "entender" EJS :)

**Comment by jghagemann** [comment]
Tem algumas que estão com versões um pouco diferentes, mas eu segui todos os installs do guia de dependências e algumas das que são instaladas nas aulas não tem lá

**Comment by jghagemann** [comment]
Fernando! Seguinte, resolvi seguir a diante e logo na aula seguinte você incia dizendo que nosso ambiente dev estaria quebrado. Continuei seguindo os passos da aula M02#40 e depois de remover os itens mencionados na aula e renomear o template, tudo seguiu normalmente.

Então esse comportamento de quebrar era esperado? Fiquei umas horas tentando resolver isso até decidir seguir adiante

**Comment by fdaciuk** [comment]
Oi @jghagemann! Na verdade, não deveria. O que deve ter acontecido é que eu acabei vendo que quebrou quando finalizei a gravação dessa aula :)
Vou colocar um aviso no final dessa aula avisando que vai quebrar, e na próxima será feita a correção, ok? :)

Obrigado por avisar! :D
