### ISSUE TITLE
M02#A52 gulp: primordials is not defined

### ISSUE THREAD

**Issue by jghagemann** [da2k/curso-reactjs-ninja#398]
Fala mestre! ao executar o lint:watch recebo a mensagem do título do issue.
Pelo que achei no [StackOverflow](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node) a versão 3 do gulp não é compatível com as versões atuais do Node, Vou tentar usar uma versão atual do Gulp e aviso aqui se conseguir prosseguir nas aulas sem problemas :D

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jghagemann! Legal! De qualquer forma, se quiser usar o CRA pra seguir com as aulas, fique à vontade :)

**Comment by jghagemann** [comment]
Aprender a configurar isso na mão é importante! :)
Vou ter que dar uma lida nas docs por que aparentemente mudaram algumas coisas na versão 4 do gulp, sigo sem ele por enquanto já que não afeta muito, sendo só lint

**Comment by fdaciuk** [comment]
Legal, se você está nesse momento, faz todo o sentido mesmo :)
Qualquer versão do Node.js você está usando?

**Comment by jghagemann** [comment]
12.13 (Acabei de ver que tem um update da LTS no site pra 12.14)

**Comment by fdaciuk** [comment]
Entendi.. se não me engano, a v4 do Gulp teve algumas alterações na interface, então o resultado final pode ficar diferente.

De qualquer forma, se você quiser, pode instalar o NVM, e usar a v10 do Node apenas para conseguir seguir com esse projeto. Em breve vou fazer algumas atualizações nas aulas pra cobrir esses casos :)

**Comment by guilhermeci** [comment]
@fdaciuk , prof. sou seu aluno na Udemy do curso, porém estou com dificuldades para configurar o ambiente para seguir as aulas(estou a uma semana tentando resolver). Estou na metade do curso e precisei formatar a minha máquina e perdi as configurações que já possuia, agora toda vez que tento executar um comando do yarn ou npm recebo todo tipo de erro, o mais recorrente é node-gyp, muitos foruns dizem que é algo relacionado a versão, então o motivo do meu contato é para saber quais as configurações necessárias para executar os códigos de forma satisfatória.:
Eu uso o windows 10 pro(x64), visual studio code, nodejs 13.6.0, npm 6.13.6, yarn 1.21.1.  Agradeço de antemão pela atenção.

**Comment by fdaciuk** [comment]
Oi @guilhermeci! Normalmente as versões mais recentes do Node.js, NPM e Yarn deveriam ser suficientes.

A versão recomendada de uso do Node.js é sempre a versão LTS, que é a versão estável, e com tempo e suporte aumentado (atualmente, a v10).

Tente instalar a v10 do Node, com a versão do NPM que vier com ele, ou se estiver usando Yarn, pode instalar a versão mais recente, e tente novamente instalar as dependências do projeto.

Se tiver qualquer erro, poste aqui um print do erro, e um do seu package.json, para eu ver como estão suas dependências, ok? :)

**Comment by guilhermeci** [comment]
Olá @fdaciuk , com o node v10 consegui um ambiente estável. Mas tive se realizar alguns acertos:
Meu ambiente : Windows 10 Pro / Node 10.18.1
executar npm install
alterar o arquivo gulpfile.js 
```
const gulp = require('gulp')
// const { spawn } = require('child_process')

// on windows, install and use `cross-spawn`:
const { spawn } = require('cross-spawn')
```

```
npm i -D handlebars@4.5.0
```
para desativar as mensagens de erro ao executar yarn test:watch

Prof. Caso eu tenha mais alguma dificuldade e/ou encontre algum outro erro eu posto aqui. Muito obrigado pelo suporte e parabéns pelas aulas.

Abraço

**Comment by fdaciuk** [comment]
Perfeito @guilhermeci! Qualquer dúvida, fique à vontade para postar aqui! :D
