### ISSUE TITLE
53. M1#A41 - GitHub app - Refatorando a aplicação e populando os dados do usuário

### ISSUE THREAD

**Issue by santosdvlpr** [da2k/curso-reactjs-ninja#399]
Olá F. Daciuk !!!
Tudo certo até a aula anterior. O problema é que meu código não está renderizando 
as informações do componente UserInfo. Consegui passar os estados até fazer as requisições
e atualizar os states no App.js. Mas o App não renderiza os dados de UserInfo. Help-me!!!
https://github.com/santosdvlpr/react-webpack/tree/master/src

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @santosdvlpr! Conseguiu resolver? :)
