### ISSUE TITLE
Arrow function vs bind

### ISSUE THREAD

**Issue by victormiguez** [da2k/curso-reactjs-ninja#4]
Fala @fdaciuk, tudo certo?
Primeiramente gostaria de te parabenizar pelo conteúdo do curso, ficou muito bom, curti demais! :D

Fiquei com uma dúvida na hora de resolver o exercício.
Criei a seguinte função:
```
handlePublicReposSearch () {
  const login = this.state.userInfo.login
}
```
De início tentei chamá-la com:
```
handlePublicReposSearch={this.handlePublicReposSearch()}
```
Mas não funcionou, pois assim eu "perco" o `this` do componente.
Então cheguei em duas saídas:
```
handlePublicReposSearch={() => this.handlePublicReposSearch()}
```
Ou
```
handlePublicReposSearch={this.handlePublicReposSearch.bind(this)}
```

Por enquanto estou preferindo utilizar arrow function. Você tem alguma recomendação sobre isso? Qual seria a melhor prática?
Valeu! :)

**Comment by fdaciuk** [comment]
Opa! Massa @victormiguez :D 
Por enquanto, acho o método com arrow functions mais apropriado xD
Em breve vamos ver algumas outras soluções, mas eu prefiro usar arrow functions =)
