### ISSUE TITLE
[Dúvida] Erro preLoader

### ISSUE THREAD

**Issue by juliocarneiro** [da2k/curso-reactjs-ninja#40]
Boa noite de novo cara, estou na parte de instalar o standard como lint do meu boilerplate, mas esta dando um erro parece que com o preLoader, segue:

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
  configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }

Fiz tudo direitinho como foi passado no vídeo, porem não roda o bundle de jeito algum, meu código está em:

https://github.com/juliocarneiro/react-front-boilerplate

@fdaciuk

**Comment by fdaciuk** [comment]
É a versão do webpack =)

Instale o webpack com `npm install --save-dev webpack@1` =)

No decorrer do curso, vamos atualizar isso, então pode usar a versão 1 de boa =)

**Comment by juliocarneiro** [comment]
Valeu outra vez! Abraço

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)

**Comment by juliocarneiro** [comment]
poxa ainda nao rolou ;(
