### ISSUE TITLE
M1-A#41 Error no licence field no packge.json 

### ISSUE THREAD

**Issue by ThalesAlonso** [da2k/curso-reactjs-ninja#400]
Boa tarde Professor, estou com o seguinte erro ao tentar executar o projeto com node sever.js, ou npm start ou yarn start 

![image](https://user-images.githubusercontent.com/21249630/71525289-c5bb5d80-28af-11ea-98aa-06fa0de421e7.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ThalesAlonso! Você chegou a instalar o loader para JSX?

**Comment by ThalesAlonso** [comment]
Não cheguei, deve ser isso então né.

**Comment by fdaciuk** [comment]
Se você chegou nessa aula, provavelmente já deveria estar com o `babel-preset-react` instalado :)
Dá uma olhada se você pulou alguma aula, pois essa instalação nós fizemos no módulo "React + Webpack" :)

**Comment by ThalesAlonso** [comment]
Blz, devo ter pulado alguma aula então, ou ter esquecido de instalar essa depêndencia.

**Comment by fdaciuk** [comment]
Legal! Isso eu mostrei na aula 7 do módulo de React + webpack :)
Se quiser acompanhar as dependências usadas em cada aula desse módulo, eu deixei tudo aqui, separado por diretórios:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

Se ainda assim não funcionar, compartilha seu código comigo que eu te ajudo :)

**Comment by ThalesAlonso** [comment]
Professor pode fechar esse issue, era isso mesmo. Instalei a dependência que estava faltando e funcionou. Com a ressalva que tive vários warnings quando executei a aplicação no terminal. Mas funcionou perfeitamente. 
Muito obrigado professor.

**Comment by fdaciuk** [comment]
Legal @ThalesAlonso! Esses warnings provavelmente são por causa do linter. É importante resolvê-los. Se não conseguir, posta um print aqui que eu te ajudo com as mensagens :)

**Comment by ThalesAlonso** [comment]
Professor, estou com os seguintes warnings que não estou conseguindo resolver.
Porém aplicação está funcionando corretamente. 

![image](https://user-images.githubusercontent.com/21249630/71530368-3c645500-28c8-11ea-95b2-f1534ae2079e.png)

**Comment by fdaciuk** [comment]
Legal @ThalesAlonso! Isso aí é bem simples de resolver: o linter espera sempre uma nova linha ao final de cada arquivo. Para fazer isso, eu mostrei no curso o plugin **Editor Config**, que você instala no editor que você está usando, e cria um arquivo `.editorconfig` na raiz do projeto, com as configurações padrão que serão aplicadas sempre que algum arquivo nesse projeto for aberto no seu editor :)

Então os passos para resolver são: 
1) você precisa instalar o **Editor Config** para o seu editor: https://editorconfig.org/
2) Crie o arquivo `.editorconfig` na raiz da sua aplicação, com o [esse conteúdo](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m01/3rd-party-with-react/.editorconfig).

Após essa configuração, apenas abra cada um desses arquivos no seu editor, e então coloque a aplicação para rodar novamente. 

Fazendo isso, os warnings devem ter sumido.

Me deixe saber se isso resolve o seu problema :)

**Comment by ThalesAlonso** [comment]
Boa Tarde Professor, consegui resolver os problemas com o linter revendo a aula de linter. 
Agora só uma coisa está me incomodando, quando executo um yarn start, aparece um **warning no package.json**,  com o erro abaixo, você sabe o motivo disso  ? 

![image](https://user-images.githubusercontent.com/21249630/71744299-8956a700-2e45-11ea-8194-69ea9e376a12.png)

**Comment by fdaciuk** [comment]
Oi @ThalesAlonso! É só uma dica dizendo que seu projeto deveria ter uma entrada "license", mas isso não afeta projetos privados. Uma licença deve ser adicionada apenas se o seu projeto for público (se você estiver criando uma biblioteca, por exemplo) :)

Se você tem "TOC" por causa de warnings, pode resolver isso apenas adicionando no seu package.json uma entrada "license": "ALGUM_TIPO_DE_LICENÇA". Exemplo:

```
{
  "license": "MIT",
 // restante do conteúdo do seu package.json
}
```

**Comment by ThalesAlonso** [comment]
Show de bola, muito obrigado professor.

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
