### ISSUE TITLE
MRW#06 - Erro ao usar o import es6

### ISSUE THREAD

**Issue by nppneto** [da2k/curso-reactjs-ninja#401]
Bom dia, Prof!

Estou com um problema ao usar o import do es6.

Após o export default no src/app.js, ao importar o módulo no src/index.js, recebo a seguinte mensagem de erro no browser:

bundle.js:49 Uncaught SyntaxError: Cannot use import statement outside a module.

Segue index.js:

```
'use strict'

import Title from './app';

var React = require('react');
var ReactDOM = require('react-dom');

ReactDOM.render(
    React.createElement(Title),
    document.querySelector('[data-js="app"]')
);
```

Segue app.js:

```
'use strict'

var React = require('react');

var Title = React.createClass({
    render: function () {
        return React.createElement('h1', null, 'Título');
    }
});

export default Title;
```

Segue .babelrc:

```
{
    "presets": ["es2015", "stage-0"]
}
```

Segue webpack.config.js:

```
'use strict'

const path = require('path');

module.exports = {
    entry: path.join(__dirname, 'src', 'index'),
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/',
    },
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel',
        }]
    }
}
```

Att,

Nelson Neto.

@fdaciuk

**Comment by nppneto** [comment]
Bom dia, prof!

Desconsidere. Para quem cair nesse erro, reinicie o server do webpack.

Feliz ano novo a todos!

**Comment by fdaciuk** [comment]
haha! Legal, que bom que resolveu :)

**Comment by MarceloMileo** [comment]
@fdaciuk, estou como mesmo problema do Nelson, porem mesmo reiniciando o webpack-dev-server não resolveu.

**Comment by fdaciuk** [comment]
Oi @MarceloMileo! Tenta comparar seu código atual com o código da aula. Provavelmente faltou alguma coisa :)

Aqui tem os códigos e dependências exatas usadas em cada aula, separados por diretórios:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

**Comment by MarceloMileo** [comment]
@fdaciuk , ultima forma combatente, o esperto aqui passou o exclude e include do babel loader como string e não como RegEx...Não ia funcionar nunca...
Abraços.

**Comment by fdaciuk** [comment]
haha! Acontece meu caro :)
Que bom que conseguiu resolver :)
