### ISSUE TITLE
Conteudo Abordado.

### ISSUE THREAD

**Issue by marcelodosreis** [da2k/curso-reactjs-ninja#402]
Oi Fernando tudo jóia?
Eu tenho uma duvida sobre o curso e o conteúdo abordado, eu atualmente já trabalho com React, porem queria aperfeiçoar meus conhecimentos, em assuntos como Pattern, Arquitetura, Flux, E Redux-Saga. 
Eu achei seu curso porem não sei se ele atende minhas expectativas :/

Os conteúdos como Redux-Saga, Pattern em React e etc... sao abordados?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marcelodosreis! Tudo certo, e contigo? :)

Vamos lá:

Alguns patterns são abordados no curso, como `Container / Presentational Components` e `Render Props`.

Sobre arquitetura, durante o decorrer do curso eu apresento pequenos apps, até chegar no módulo 4, onde criamos um app maior, com uma estrutura que pode suprir boa parte dos projetos hoje. 

Como o React é apenas uma lib, a forma que você organiza seu código pode variar de projeto para projeto, mas durante o curso eu vou mostrando algumas possíveis formas de fazer isso :)

Sobre Redux, não abordo sagas. Para side effects, falamos apenas do redux-thunk :)
