### ISSUE TITLE
M1#A29 - Validação no radio button

### ISSUE THREAD

**Issue by LuizHAP** [da2k/curso-reactjs-ninja#405]
Estou tentando criar uma validação no onChange de cada Radio Button.

A ideia é simular um questionário, que após a selecionar a resposta correta os 3 group de Radio Buttons, habilite um botão.

```
constructor(){
        super();
        this.state = { 
            open: false,
            isLocked: true,
            questao1: '',
            questao2: '',
            questao3: '',
        };

        this.handleChange = this.handleChange.bind(this);

        this.openModal = this.openModal.bind(this);
        this.closeModal = this.closeModal.bind(this);
    }

    openModal() {
        this.setState({ open: true });
    }

    closeModal() {
        this.setState({ open: false });
    }

    handleChange(event) {
        let question = event.target.name
        let val = event.target.value
        this.setState({[question]: val})
    }
```

Porém não sei como eu posso fazer no onChange, alterar o ```this.state.isLocked = true```, já que o this.state é assincrono. Tentei por callback no ```handleChange```, porém não consigo tratar os dados do this.state.questao1, questao2 e questao3.

Poderiam me ajudar? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @LuizHAP! Você pode pensar na atualização desses estados de forma separada: deixe o seu código como está, e no `componentDidUpdate`, verifique se as 3 questões foram respondidas. Se sim, atualize o estado `isLocked` :)

Lembre-se também de verificar se o valor do `isLocked` é true, antes de fazer a alteração, pois, como você vai disparar um novo `setState`, um novo fluxo de atualização do componente será disparado, e esse método (`componentDidUpdate`) também vai ser. 

Então, ao verificar se as 3 questões estão corretas, e o `isLocked` é false, significa que o `isLocked` já foi alterado, e nada precisa ser feito. Caso contrário, só setar o `isLocked` para `true`. 

Deu pra entender a ideia? :)

**Comment by fdaciuk** [comment]
Oi @LuizHAP! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
