### ISSUE TITLE
M02A#115 Erro ao iniciar o storybook do botão

### ISSUE THREAD

**Issue by jghagemann** [da2k/curso-reactjs-ninja#407]
Fala mestre! Estou tentando iniciar o storybook logo após configurar o primeiro story do botão e dá o seguinte erro:  throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'preLoaders'.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jghagemann! Esse erro normalmente acontece quando você está usando uma configuração para uma versão do webpack, mas está usando outra versão do webpack. 

Confere como estão as versões das suas dependências, e veja se estão com as mesmas versões usadas na aula. Nesse link você consegue ver o projeto completo pra comparar com o seu:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/m02/applications/markdown-editor

Se ainda estiver com problemas, suba seu projeto aqui no GitHub e passe o link do repositório que eu dou uma olhada, ok? :)

**Comment by jghagemann** [comment]
Resolvido!
Por alguma razão tinha o storybook/react ao invés do kadira
O webpack tava na versão 3.6.0 ao invés da 2.2.1 mostrada, funcionou. Valeu!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
