### ISSUE TITLE
[M2#A32] Problemas com o template no htmlplugin

### ISSUE THREAD

**Issue by Tgnicius** [da2k/curso-reactjs-ninja#408]
Professor, boa tarde,

quando eu usei o template no webpack.config.js e redirecionei para o template.html. O html em questão foi aberto, porém o título não foi atualizado usando 
``` <title><%= htmlWebpackPlugin.options.title %></title> ```

e também, o principal problema, foi que o ``` <div data-js="app"></div> ``` não estava mais abrindo os componentes reacts, se tornando em um div vazio.

Código do htmlplugin:
```const HtmlPlugin = require('html-webpack-plugin') ```
...

```     
    plugins: [
        new webpack.HotModuleReplacementPlugin(), 
        new HtmlPlugin({ 
            title: 'GitHub App',
            template: path.join(__dirname, 'src', 'html', 'template.html')
        })
    ],
```

Como está aberto no navegador ('Não original' era eu tentando refazer os passos, para demonstrar que esse era o html que está dentro da pasta src e que ele estava reproduzindo alguma coisa):
![image](https://user-images.githubusercontent.com/58370059/73595803-62f35c80-4514-11ea-914d-cbe4bd9b6c32.png)

Quando vi que o template.html estava reproduzindo essa frase, tentei voltar atrás até o ponto em que reproduzia a div, mas não consegui.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Tgnicius! Consegue subir seu projeto em um repo aqui no GitHub pra eu dar uma olhada? Fica mais fácil pra descobrir o problema :)

**Comment by Tgnicius** [comment]
@fdaciuk https://github.com/Tgnicius/htmlPluginProblem

Não uso muito o github, mas creio ter criado o repositório

**Comment by fdaciuk** [comment]
Oi @Tgnicius! Legal, era isso mesmo. Faltou só o arquivo `.babelrc`, mas consegui ver onde está o problema: por algum motivo, você instalou a versão 1 do html-webpack-plugin (provavelmente você instalou ele com o `@1` no final, certo?)

Se foi isso mesmo, você só precisa reinstalar essa biblioteca, sem passar a versão. A versão mais recente deve funcionar como esperado. Para isso, só rodar o comando no diretório principal do seu app:

```
npm i --save-dev html-webpack-plugin
```

Me deixe saber se isso resolve o seu problema, ok? :)

**Comment by Tgnicius** [comment]
Deu certo! Desinstalei a versão que tinha (que eu tinha confundido com a versão da próxima aula, então realmente baixei a errada) e baixei a nova versão.

Código da desinstalação (no caso de alguém no futuro tbm ter o mesmo problema): 
```
npm uninstall --save-dev html-webpack-plugin@versãoinstalada
```
Obrigado pela ajuda :)

**Comment by fdaciuk** [comment]
Só uma dica: quando você precisa instalar a versão mais recente de uma lib já instalada, não precisa remover ela, só rodar o comando de instalação que a versão antiga será substituída :)

Mas legal que conseguiu resolver @Tgnicius! :)

Qualquer dúvida, só avisar :)
