### ISSUE TITLE
M03#A16 Uncaught TypeError createContext is not a function

### ISSUE THREAD

**Issue by jghagemann** [da2k/curso-reactjs-ninja#409]
Mestre! Acredito que desde que comecei a usar a context desde o sample 6 ou 7, toda a vez que tento usar o yarn dev pra verificar o contador dá um erro no console como escrito no título. 

Estou usando as dependências do react, react-dom, react-redux e redux com as versões iguais as do package.json.
Já tentei também clonando o workflow-reactjs e adicionando as pastas e arquivos copiando do repositório no github mas o erro continua.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jghagemann! Consegue compartihar seu projeto comigo? Sobe ele aqui no GitHub e passa o link que eu dou uma olhada :)

**Comment by jghagemann** [comment]
Feito:

https://github.com/jghagemann/reactninja-m03a16

**Comment by fdaciuk** [comment]
@jghagemann baixei seu projeto aqui, mas não está dando esse erro que você comentou. Consegue conferir se está tudo atualizado com a versão que você está vendo o erro?

**Comment by jghagemann** [comment]
Eu lembro de ter tentado rodar com o yarn que usava até agora, versão 1.21, de repente começou a dar erro quando tentava executar usando essa versão.
Fazendo uma pesquisa no site deles vi que tinham atualizado pro yarn 2 que era compatível com as versões do node 10 e 12 (estou usando a LTS mais recente). 

Pesquisei um tempão e mesmo mudando as versões das dependências não achei o erro, mas tá tudo igual o package.json e  não sei mais onde procurar

**Comment by jghagemann** [comment]
![Error](https://user-images.githubusercontent.com/42047435/73788314-879d3d80-477b-11ea-94a3-f2b0fcabb5a4.PNG)

**Comment by fdaciuk** [comment]
A v2 do Yarn mudou algumas coisas, e ainda estão decidindo alguns pontos. Recomendo manter a versão 1, ao menos por enquanto.

Tente baixar esse projeto que você passou o link, e fazer uma instalação do zero (deletando a `node_modules`, e o arquivo `yarn.lock` e rodando `yarn` para instalar as dependências).

Dessa forma, você deve ver exatamente o que eu vi: tem alguns erros na aplicação, mas não exibe  esse erro :)

**Comment by jghagemann** [comment]
Quando eu tento instalar com Yarn ele dá "Unexpected end of JSON input" nessa versão

**Comment by fdaciuk** [comment]
Você está usando a versão mais recente (1.21.1) ?

**Comment by jghagemann** [comment]
Sim, desinstalei o yarn2 reinstalei a 1.21.1 e rodei  ```yarn``` na aplicação como instruiu.
Chega uma hora que ele dá esse erro. Usando NPM ele instala tudo, porém quando uso o ```npm run dev``` o dashboard não carrega nada e a tela de cmd só pisca com o node e fecha, no ```localhost:3000``` so aparece uma tela em branco e o erro que tem na foto acima

**Comment by fdaciuk** [comment]
Certo, vamos tentar de outra forma: crie uma nova aplicação usando o Create React App, e mova seus arquivos pra lá, instalando as dependências necessárias do Redux (redux e react-redux).

Me deixe saber se isso funciona :)

Se não funcionar, vou pedir pra você subir aqui no GitHub o projeto com o CRA pra eu dar uma olhada, ok?

**Comment by jghagemann** [comment]
![Error CRA](https://user-images.githubusercontent.com/42047435/73851367-1bb6e580-480c-11ea-9864-12c4bfd85994.png)

Depois de ajustar alguns paths agora deu esses erros.
Subi o projeto aqui: https://github.com/jghagemann/reactninja-cra

Steps:
Instalar o CRA com yarn
Copiei os arquivos da sample M11
````yarn add redux@5.0.6```
````yarn add react-redux@3.7.2```
Conforme o package.json

**Comment by fdaciuk** [comment]
Legal @jghagemann! O `src/html` não é mais necessário nesse caso, pois o CRA tem o seu html próprio, que está em `public/index.html`. O primeiro erro que aparece é porque a `div` onde vai ser renderizado o app React não está com `data-js="app"`, e sim com `id="root"`.

Então faça a modificação no seu `src/index.js`, para ficar assim:

```
document.querySelector('#root')
```
Ou então edite o `public/index.html`, trocando o `id="root"` por `data-js="app"`. Qualquer uma das duas formas vai funcionar corretamente :)

**Comment by jghagemann** [comment]
Funcionou aqui! Vou seguir as aulas usando este CRA então e retorno pro template do workflow no módulo 4

**Comment by fdaciuk** [comment]
Perfeito, que bom que deu certo :)
O CRA já está bem estável, recomendo usar ele sempre :)
Inclusive, no módulo 4, estamos usando ele :D
