### ISSUE TITLE
#08 - Webpack - Config Webpack Dev Server

### ISSUE THREAD

**Issue by williamcosta** [da2k/curso-reactjs-ninja#41]
Fiz as configs iguais a da aula, porém retorna um erro quando tento rodar o script.

`TypeError: webpack.HotModuleReplacementPLugin is not a constructor`

Deixei todas as versões de dependências iguais a da aula em questão mesmo assim não resolveu o problema.

Link para o repositório com o código: https://github.com/williamcosta/curso-react

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @williamcosta, tudo certo? =)
Tem um `L` maíusculo na palavra `PLugin` =)

**Comment by williamcosta** [comment]
Opa @fdaciuk tudo certo!

Verdade era isso mesmo. Que mancada minha.

Obrigado!

**Comment by fdaciuk** [comment]
Sem problemas, acontece =)

Qualquer dúvida, só avisar! :D
