### ISSUE TITLE
M2#A51 - Conflito entre gulp e snazzy

### ISSUE THREAD

**Issue by Tgnicius** [da2k/curso-reactjs-ninja#410]
Olá de novo, professor!

Por algum motivo, quando eu instalo o gulp e faço o gulpfile.js e tento rodar o yarn lint:watch me aparece esse erro:
```
yarn run v1.21.1
warning package.json: No license field
$ gulp
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/itstar/react-webpack/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/itstar/react-webpack/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/itstar/react-webpack/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

E, além disso, quando fui testar o yarn lint novamente me deu outro erro:
```
yarn run v1.21.1
warning package.json: No license field
$ standard --verbose | snazzy
/bin/sh: snazzy: command not found
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

O erro parece citar que a dependência snazzy não foi achada, porém antes de instalar o gulp estava funcionando normalmente.

Refiz os passos da aula, funcionou o snazzy a princípio, mas quando faço a parte do gulp, aconteceram os mesmos problemas novamente.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Tgnicius! Sempre que der algum erro, pode subir seu projeto aqui no GitHub e compartilhar o link, ok?

Assim eu consigo ver onde pode estar o problema de forma mais eficiente :)

**Comment by Tgnicius** [comment]
Ok @fdaciuk , vou fazer logo isso nas próximas vezes.
Aqui está o link do repositório (o nome ainda está htmlPluginProblem, pois só atualizei os arquivos).
https://github.com/Tgnicius/htmlPluginProblem

**Comment by fdaciuk** [comment]
Oi @Tgnicius! No seu projeto está tudo ok. Parece que existe um bug do `gulp` v3 com a versão mais recente do Node.js. Então tem duas soluções:

- Você pode rodar o linter sempre com o comando `npm run lint`;
- Ou, se estiver usando o `nvm`, para gerenciar versões do Node.js, pode instalar a versão `10` do Node que deve funcionar.

A primeira opção é mais simples :)

**Comment by Tgnicius** [comment]
Ok, vou usar o yarn lint manualmente então. Obrigado!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
