### ISSUE TITLE
M1 - Stateful vs. Stateless

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#411]
Supondo o arquivo app.js, lá no finzinho temos:

```
  render () {
    return <AppContent
      {...this.state}
      handleSearch={this.handleSearch}
      getRepos={this.getRepos('repos')}
      getStarred={this.getRepos('starred')}
    />
  }
```

Dúvida: mesmo passando os states para AppContent, esse component continua sendo stateless? Ele está apenas acessando os states no parent?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Isso mesmo: a ideia de de **stateful** é o componente que **manipula** estados. Esse componente `AppContent` está recebendo os estados via props. Ele não manipula estados, apenas recebe e renderiza as informações que foram passadas :)

Se o `AppContent` tivesse um estado próprio para ser manipulado, aí sim ele seria considerado stateful :)
