### ISSUE TITLE
Erro com Webpack

### ISSUE THREAD

**Issue by Escanor2** [da2k/curso-reactjs-ninja#412]
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
o código que estou usando, o projeto em si eu vi rodando na video aula

**Comment by fdaciuk** [comment]
Oi @Escanor2! Esse erro provavelmente é porque você deve ter instalado uma versão diferente do webpack daquela mostrada na aula. Você está acompanhando as versões pelo [arquivo de depenências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md)?

**Comment by Campigoto** [comment]
Também estou com o mesmo problema. Executei exatamente como está descrito no arquivo de dependências. Preciso de ajuda, por favor.

**Comment by fdaciuk** [comment]
@Campigoto compartilha comigo o repositório com seu código pra eu dar uma olhada?

**Comment by fdaciuk** [comment]
Oi @Escanor2 e @Campigoto! Vou fechar a issue, mas se vocês ainda estiverem com dúvidas, só avisar que eu vou ajudando, ok? :)
