### ISSUE TITLE
 M1#A36 - render de tela não está funcionando

### ISSUE THREAD

**Issue by JulioBFG** [da2k/curso-reactjs-ninja#413]
no inicio da criação da github pages, foi solicitado para realizar a limpeza do projeto ou criação de um novo, e após eu realizar o mesmo, e criar a tela, app.js, e inserir o código, o index.js não realiza o render dela, somente me deixando com uma tela em branco, fui atrás de ver o que pode se tratar este problema, mas não consegui uma solução, pode me ajudar ?.
segue link do projeto no meu github : https://github.com/JulioBFG/ninja-react

Agradeço desde já!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JulioBFG! O problema no seu projeto é que faltou retornar o conteúdo do componente `App` :)
Dá uma olhada no erro do console que vai ficar mais claro :)

Você usou as chaves na arrow function do componente `App`, para criar o corpo da função. Ao usar as chaves, é obrigatório o uso do `return`.

Se você quiser usar o `return` implícito, pode só tirar as chaves, ou substituí-las por parênteses, para deixar o código mais organizado :)

**Comment by fdaciuk** [comment]
Oi @JulioBFG! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
