### ISSUE TITLE
M2#A12 - Recursive Map

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#414]
Saudações, mestre.

Só queria compartilhar contigo a solução que eu havia encontrado para esse challenge 'Recursive Map' do módulo 2.

Em particular, não achei ruim a solução encontrada para 'monitorar' o index, pelo length do array dinâmico sendo populado/mappeado, batizado de 'mapped'. Outra parte bem problemática foi como conseguir fazer o map(element, index, array) => array. Movi o tal 'mapped' para que fosse um 4º parâmetro (meio que virtual, pois utilizado apenas internamente na function) para acomodar o array original na 3ª posição default (respeitando o padrão esperado de um map normal).

Não deve estar muito legível sem essa explicação. rsrs Mas fiquei com vontade de te mostrar e ver se você vê algum problema.
:)

```
const map = (arr = [], func = (item) => item, originalArr = [], mapped = []) => {
  if (arr.length === 0)
    return mapped

  if (originalArr.length === 0)
    originalArr = arr

  const [head, ...tail] = arr

  mapped.push(func(head, mapped.length, originalArr, arr ))
  return map(tail, func, originalArr, mapped)
}
```

Bora fazer o Recursive Filter agora! Abs!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Legal a ideia, mas tem alguns pequenos problemas, vamos lá :)

Veja que você modifica a assinatura da função original `map`. Por mais que os seus testes não utilizem os dois parâmetros a mais (`originalArr` e `mapped`), eles estão ali, disponíveis para serem utilizados.

O que aconteceria se algum desses valores fosse passado para o `map`? Será que tudo continuaria funcionando como deveria? :)

A ideia de criar uma função interna, dentro do `map` para servir como nossa função recursiva, é exatamente esse: nós não precisamos expor detalhes de implementação que só precisam ser conhecidos dentro da função. A função `map` continua igual, com a mesma assinatura, aceitando os mesmos argumentos, e dentro dela nós implementamos da forma que acharmos melhor :)

Deu pra entender a ideia? :)

**Comment by pamplonapaulo** [comment]
Humm... Então, pelo que entendi, modifiquei a "assinatura" da função original ´´map´´quando inventei o 4º parâmetro. E ao fazer isso eu crio uma vulnerabilidade, tornando minha função "exposta" desnecessariamente.

**Comment by fdaciuk** [comment]
Isso mesmo! O terceiro e quarto parâmetros :)
E como não tem testes contra esses parâmetros, você não vai conseguir garantir que sua função funciona como esperado :)

De qualquer forma, não faz sentido adicionar "parâmetros virtuais" na função que será publicamente exposta. Agora, se você criar uma função interna, aí você pode passar o que quiser, visto que essa função interna não será acessível ao executar o `map` :)

**Comment by pamplonapaulo** [comment]
Valeu mestre!! Muito grato pela força!! Caminhando a passos de tartaruga, mas mastigando bem os conceitos pra ver se entra! rsrs Abs!

**Comment by fdaciuk** [comment]
Perfeito meu caro, é assim que se estuda :)
Segue firme aí, e conte comigo para o que precisar :D
