### ISSUE TITLE
M2#A21 - reverse recursivo

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#415]
Saudações mestre!

Vim aqui dessa vez só pra mostrar a minha solução do challenge, pois de repente você pode ter alguma observação/alerta para me fazer:

```
const reverse = (arr = []) => {
  return (function reverseInternal(arrayInternal, revArr = []) {

    return arrayInternal.length !== 0
      ? (revArr.push(arrayInternal.pop()), reverseInternal(arrayInternal, revArr))
      : revArr

  })(arr)
}
```

Estou quebrando bastante a cabeça para assimilar melhor estes usos de ternário, que nas suas aulas estão me parecendo muito avançados (ou eu muito atrasado). Daí vi que é possível passar multiple statements nos ternários, e isso me ajudaria na forma como eu estava raciocinando essa function.

Agora, após ver a tua solução, o sentimento é de que eu preciso estudar bastante o 'destructuring', ainda um tanto enigmático pra mim rsrsrsr

Valeu! :)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Legal, desse jeito funciona :)

Mas no caso dos exemplos mostrados, quando nós fazemos a implementação da função usando recursão, a ideia é tentar usar o máximo possível do paradigma funcional. E nesse paradigma, um dos pontos chave é evitar _side effects_.

Nesse seu código, o que fica fora do paradigma funcional é só o array `revArr`, que está sendo modificado pelo uso do método `push`.

O uso do ternário também é mais por questões de tentar manter esse paradigma, já que o ternário sempre retorna um valor, diferente do `if`, que só cria um bloco de código e o executa :)

Então sim: o uso talvez não seja o melhor para o dia a dia, pois o ideal é sempre tentar manter o seu código mais legível possível. A ideia desse tipo de implementação é pra que você treine exatamente o que vamos precisar usar muito no React: funções puras, imutabilidade, Higher Order Functions, etc :)

E só tome cuidado ao usar múltiplos _statements_, pois é sempre o último valor que será retornado. Muitas vezes, dependendo do código, pode não ficar muito claro que, na mesma linha, existem duas expressões diferentes sendo avaliadas :)

Acho que é isso! Estou gostando de ver, você testando formas diferentes de resolver o mesmo problema. Independente se é a melhor forma ou não, isso vai te dar muitos insights no futuro, quando você pegar problemas parecidos para resolver :)

Tá mandando muito bem, parabéns! :clap: :clap:
