### ISSUE TITLE
[MRW#02] Erro na configuração do webpack

### ISSUE THREAD

**Issue by moisesmedeiros7** [da2k/curso-reactjs-ninja#416]
Vou executar o webpack e aparece o seguinte:

**root@medeiros:/home/moises/Dropbox/Desenvolvimento/React/react-webpack#** webpack
webpack 1.15.0
Usage: https://webpack.github.io/docs/cli.html

Options:
  --help, -h, -?                                                                                  
  --config                                                                                        
  --context                                                                                       
  --entry                                                                                         
  --module-bind                                                                                   
  --module-bind-post                                                                              
  --module-bind-pre                                                                               
  --output-path                                                                                   
  --output-file                                                                                   
  --output-chunk-file                                                                             
  --output-named-chunk-file                                                                       
  --output-source-map-file                                                                        
  --output-public-path                                                                            
  --output-jsonp-function                                                                         
  --output-pathinfo                                                                               
  --output-library                                                                                
  --output-library-target                                                                         
  --records-input-path                                                                            
  --records-output-path                                                                           
  --records-path                                                                                  
  --define                                                                                        
  --target                                                                                        
  --cache                                                                                           [default: true]
  --watch, -w                                                                                     
  --watch which closes when stdin ends                                                            
  --watch-aggregate-timeout                                                                       
  --watch-poll                                                                                    
  --hot                                                                                           
  --debug                                                                                         
  --devtool                                                                                       
  --progress                                                                                      
  --resolve-alias                                                                                 
  --resolve-loader-alias                                                                          
  --optimize-max-chunks                                                                           
  --optimize-min-chunk-size                                                                       
  --optimize-minimize                                                                             
  --optimize-occurence-order                                                                      
  --optimize-dedupe                                                                               
  --prefetch                                                                                      
  --provide                                                                                       
  --labeled-modules                                                                               
  --plugin                                                                                        
  --bail                                                                                          
  --profile                                                                                       
  -d                                    shortcut for --debug --devtool sourcemap --output-pathinfo
  -p                                    shortcut for --optimize-minimize                          
  --json, -j                                                                                      
  --colors, -c                                                                                    
  --sort-modules-by                                                                               
  --sort-chunks-by                                                                                
  --sort-assets-by                                                                                
  --hide-modules                                                                                  
  --display-exclude                                                                               
  --display-modules                                                                               
  --display-chunks                                                                                
  --display-error-details                                                                         
  --display-origins                                                                               
  --display-cached                                                                                
  --display-cached-assets                                                                         
  --display-reasons, --verbose, -v                                                                

Output filename not configured.
root@medeiros:/home/moises/Dropbox/Desenvolvimento/React/react-webpack# webpack
/home/moises/Dropbox/Desenvolvimento/React/react-webpack/webpack.config.js:7
	output:{
	^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
root@medeiros:/home/moises/Dropbox/Desenvolvimento/React/react-webpack# webpack
/home/moises/Dropbox/Desenvolvimento/React/react-webpack/webpack.config.js:7
	entry: path.join(_dirname, 'src', 'index'),
	                 ^

ReferenceError: _dirname is not defined
    at Object.<anonymous> (/home/moises/Dropbox/Desenvolvimento/React/react-webpack/webpack.config.js:7:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:39:40)
root@medeiros:/home/moises/Dropbox/Desenvolvimento/React/react-webpack# webpack /home/moises/Dropbox/Desenvolvimento/React/react-webpack/webpack.config.js:4
	entry: path.join(_dirname, 'src', 'index'),
	                 ^

ReferenceError: _dirname is not defined
    at Object.<anonymous> (/home/moises/Dropbox/Desenvolvimento/React/react-webpack/webpack.config.js:4:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:39:40)
root@medeiros:/home/moises/Dropbox/Desenvolvimento/React/react-webpack# 

Poderia me ajudar com esse problema @fdaciuk ?

**Comment by moisesmedeiros7** [comment]
consertei a variável __dirname, mas segue:

entry: path(__dirname, 'src', 'index'),
	       ^

TypeError: path is not a function

**Comment by fdaciuk** [comment]
Oi @moisesmedeiros7! Conseguiu resolver?
