### ISSUE TITLE
M2#A07 - Nova dependência para rodar

### ISSUE THREAD

**Issue by jordaofabio** [da2k/curso-reactjs-ninja#417]
Para conseguir rodar o código dessa aula precisei adicionar a dependência @babel/preset-env, além das que já estavam atualizadas aqui no Github.

Também alterei o .babelrc que ficou assim:

```
{
  "presets": ["@babel/preset-env"]
}
```

**Comment by fdaciuk** [comment]
Oi @jordaofabio! Essa dependência só é necessária se você estiver usando uma versão do babel diferente da mostrada na aula :)

**Comment by jordaofabio** [comment]
Hummm então nem me liguei isso! Obrigado!

**Comment by fdaciuk** [comment]
Sem problemas :)
Qualquer coisa, só avisar :)
