### ISSUE TITLE
M1#A39 - Github app

### ISSUE THREAD

**Issue by MarceloMileo** [da2k/curso-reactjs-ninja#418]
Opa, tudo tranquilo mestre?
Segue uma duvida simples, mais conceitual.
Eu estou usando desestruturação na passagem das props, isso pode ser anti-pattern?
Ex:
```
const UserInfo = ({ username, repos, followers, following }) => ()
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MarceloMileo! Não é antipattern não, pode usar sem problemas :)

**Comment by MarceloMileo** [comment]
@fdaciuk, obrigado pelo retorno, vou encerrar essa issue

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
