### ISSUE TITLE
github-app utilizando hooks

### ISSUE THREAD

**Issue by JSaints-Dev** [da2k/curso-reactjs-ninja#419]
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JSaints-Dev! Não vai dar diferença visível, fique tranquilo :)
A diferença é que, no exemplo B, você escreve menos código. Nada mais :)

**Comment by JSaints-Dev** [comment]
ah blz...obrigado professor!!!

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
