### ISSUE TITLE
M1#011 - Dúvida import React.

### ISSUE THREAD

**Issue by williamcosta** [da2k/curso-reactjs-ninja#42]
Você mostrou nessa aula como criar o component Title com função pura.

E ai por curiosidade como aquele módulo era só ES6 ao meu ver poderia remover o import do React, porém quando remove ele fala que `React is not defined`.

Porque ele dá o erro sendo que não estamos usando nenhuma feature do React dentro do component?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @williamcosta! Você já chegou na parte que falamos sobre JSX? Naquela aula eu mostrei que o React é necessário, pois o babel transforma o JSX no método `React.createElement`, por isso o React é necessário no contexto de cada componente =)

**Comment by williamcosta** [comment]
Opa @fdaciuk acho que não cheguei nesse aula sobre JSX. Mas agora entendi a dependência do React. Isso que eu falei iria funcionar caso eu jogasse até as tags HTML para dentro da `Template String`.

**Comment by fdaciuk** [comment]
> Isso que eu falei iria funcionar caso eu jogasse até as tags HTML para dentro da `Template String`.

Não entendi essa parte =)
