### ISSUE TITLE
retornando  a fazer o curso 

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#420]
fala Daciuk eu tive que parar com o curso por um bom tempo agora voltei e vi que tem muitas coisas que já mudou sobre as config do react e versões do webpack também, eu parei no projeto do editor de markdown você recomendaria avancar para uma parte especifica do curso? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! As mudanças que ocorreram no React foram apenas algumas features movidas da lib principal. Nada mudou, de fato, na interface (forma de usar).

Então pode seguir o curso sem problemas de onde parou :)

O webpack automatizou algumas coisas sim, mas a base dele ainda continua sendo muita coisa da v2, só que agora com bastante coisa já automática, sem necessitar de configurações manuais.

Então pode seguir também com as configs se quiser, que você não vai precisar "desaprender" nada no futuro :)

Se quiser facilitar o processo, pode usar o Create React App, para não precisar lidar com configurações manualmente. 

A única mudança visível é sobre o prop-types que foi colocado em uma lib à parte, então seria a única coisa que você precisaria se preocupar, se estiver usando a versão mais recente da lib :)

Em breve eu vou disponibilizar atualizações para esses primeiros módulos, apenas para facilitar o uso da versão mais recente, e para mostrar as novidades da lib. O que já vimos, com certeza será  mantido nessas atualizações :)

Acho que é isso. Qualquer coisa, só avisar :)

**Comment by angelilton** [comment]
ok thank you
