### ISSUE TITLE
[M4A55 e 56] - Como fazer autenticação via API

### ISSUE THREAD

**Issue by JessPergentino** [da2k/curso-reactjs-ninja#421]
Boa tarde professor,

Na aula de autenticação vi que vc usou a autenticação via firebase, mas eu estou fazendo uma aplicação que será consumida por uma api, nessa api eu já implementei a autenticação, como que eu faço para utilizar a autenticação da api na spa? Teria algum material para indicar ou dica?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JessPergentino! Nesse caso, vai depender de como você criou a autenticação, pois quando você cria um sistema assim, você já cria pensando em como espera que ela seja consumida :)

Mas a ideia base é a mesma: você vai usar o `useEffect` pra fazer o request para a sua API, e pode salvar os dados do resultado da autenticação na Context API, para compartilhar com a aplicação toda :)

Se você precisar de alguma ajuda específica com a sua autenticação, me manda uma DM pela Udemy, que assim você consegue compartilhar seu código comigo sem deixar público, que eu vou te ajudando com isso, ok? :)

**Comment by JessPergentino** [comment]
Ok, valeu professor, qualquer coisa mando uma mensagem por lá. Obrigada!

**Comment by JessPergentino** [comment]
Boa tarde professor,  segui exatamente como o senhor sugeriu, porém não estou conseguindo salvar os resultados da autenticação no context API. Mandei uma DM la na udemy com mais detalhes e o repositório da aplicação.

**Comment by fdaciuk** [comment]
Oi @JessPergentino! Podemos continuar a conversa por lá então. Já te respondi :)
