### ISSUE TITLE
Projetos em React-Redux com TDD

### ISSUE THREAD

**Issue by jonyreis** [da2k/curso-reactjs-ninja#422]
Olá professor,

Atualmente estou na aula M2#A12 e estou gostando muito do conteúdo.
TDD com Jest está sendo umas das melhores experiências que tive com programação até agora.
Tenho um desafio para fazer utilizando Redux com TDD e gostaria de saber se no curso há algum projeto utilizando essas tecnologias.

Vlw, obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jonyreis! Que massa que está curtindo :D 
Sim, no módulo 3 eu mostro exatamente isso: como usar o Redux, e como escrever testes para os reducers, usando TDD, aproveitando o conhecimento sobre testes passado nesse módulo 2 :)

**Comment by jonyreis** [comment]
.
