### ISSUE TITLE
M2#A28 - find recursive

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#424]
Salve queridão!

Antes de solucionar o find recursive challenge, pensei: se não vou retornar um array, não preciso de um array internal. Does that make sense?

Então eu fiz assim:
```
const find = (arr, func) => {
  return (function findInternal(counter){
    return arr.length === counter
      ? undefined
      : func(arr[counter], counter, arr)
        ? arr[counter]
        : findInternal(counter + 1)
  })(0)
}
```
Está ligeiramente mais enxuto que a sua solução apresentada na aula. Algum side effect presente nessa forma? O que acha?

Gratidão!

Grande abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Ótima solução! Faz todo o sentido sim, parabéns :clap: :clap: 

É outra forma de resolver o mesmo problema, e ainda economiza memória, pois não usa um array auxiliar. Muito bom! :D
