### ISSUE TITLE
M2#A37

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#425]
Mestre, a respeito de 'css?modules', como poderíamos ajustar o código abaixo?
```
import React, { PropTypes } from 'react'
import style from './repos.css'

const Repos = ({ className, title, repos }) => (
  <div className={style.className}>
    <h2>{title}</h2>
    <ul>
      {repos.map((repo, index) => (
        <li key={index}>
          <a href={repo.link}>{repo.name}</a>
        </li>
      ))}
    </ul>
  </div>
)
```
A linha da div tag originalmente estava:
```
  <div className={className}>
```
Mas na aula você focou no componente search.js, que é levemente mais simples. Eu testei adicionando o style mas, obviamente, nesse caso não funciona. Devo concatenar 'style.' com o className? Ou será que nesse caso o css?module não funciona?

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Boa dúvida, vamos lá:
Quando estamos usando CSS Modules, o import que você faz vai te retornar um objeto com todas as classes que você definiu no arquivo CSS.

Se o seu CSS estiver assim:

```css
.container {}
.link {}
.label {}
```

Quando importar o CSS como você fez, você terá essas classes disponíveis como propriedades do objeto `style`. Para usá-las, é só usar a sintaxe de objeto.

Para aplicar a classe `.container` na `div`, por exemplo, você só precisa fazer:

```jsx
<div className={style.container}>...</div>
```

Se o nome da classe for dinâmica, ou não tiver caracteres permitidos para ser usada com a sintaxe de ponto, podemos usar a sintaxe de colchetes (JS padrão):

```jsx
const myClass = 'container'
...
<div className={style[myClass]}>...</div>
```

Exemplo de classe que não poderia ser usada com a sintaxe de ponto:

```css
.link-active {}
```

Aí você pode usar assim:

```jsx
<div className={style['link-active']}>...</div>
```

Deu pra entender a ideia? :)

**Comment by pamplonapaulo** [comment]
Sim, mestre! Deu pra entender direitinho. E agora me lembro que é na verdade já é a segunda vez em que me esqueço de como passar uma variável como propriedade de um objeto, sem utilizar a sintaxe de ponto. Sempre esqueço dos colchetes! rsrs

**Comment by fdaciuk** [comment]
haha! Sem crise =)
Quanto mais você usa, mais você fica familiarizado com a sintaxe :)

**Comment by pamplonapaulo** [comment]
Na verdade eu queria muito te pedir uma ajuda. Eu havia feito um teste isolado e parecia que seria simples, seguindo a sintaxe dos colchetes. Rodou ok.

Em seguida eu fui então fazer o css?module pra todos os componentes, porque pensei "ah, ok, se é possível eu quero então que meu código fique todo dessa forma, vou arrumar!".

E então, pra minha infelicidade, agora justamente aquela parte que eu trouxe nessa issue acima - e que foi aquela que eu primeiro havia testado após a sua resposta, com sucesso - agora não está mais funcionando.

Vou deixar um print, pra ver se ajuda você a entender. E vou atualizar meu github pra de repente você olhar o conjunto todo, se achar necessário.

Nesse print, meu browser tá com o app aberto na versão que havia funcionado. Note que modulei apenas o css do componente 'repos' - as demais classes acima no inspector estão sem a hash.

Porém no meu VS Code ao lado está o código do repo/index.js, salgo engano, exatamente da mesma forma que havia funcionado antes. E agora apenas essa parte é que não funciona.

A diferença é que a div que faz o wrapp agora não está recebendo classe alguma (isso está fora do print, mas estou lhe dizendo). Noto que o CSS está carregando a classe com uma hash, mas ela não está entrando no DOM do HTML por alguma razão que desconheço.

![Screen Shot 2020-03-08 at 6 55 08 PM (2)](https://user-images.githubusercontent.com/25485709/76171938-690dd600-616f-11ea-9ee8-099de2086471.png)

To obcecado pra ver isso rodando direitinho e não consigo ir adiante nas aulas! kkkkk Me ajuda! rsrsrs

**Comment by pamplonapaulo** [comment]
<img width="682" alt="Screen Shot 2020-03-08 at 9 49 59 PM" src="https://user-images.githubusercontent.com/25485709/76174576-e42eb680-6186-11ea-9c6f-9eb48fb99d83.png">

To achando que há um conflito das classes 'repos' do componente repos com estas classes 'repos' no app-content. Quando eu descomento estas linhas, aqui no app-content, o estilo do componente repos para de funcionar.

To debugando meio que em baby steps. rs Chego lá!

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Vamos lá:

No arquivo `app-content.js`, você está tentando repassar uma class `.repos` para o componente `Repos` (usando `style.repos`), mas essa classe não existe no seu CSS no arquivo `app.css`, que é de onde você está importado o estilo no `app-content.js`.

Essa classe `.repos` está dentro do arquivo `repos.css`, que foi importado no arquivo `repos.js`.
Então, pra repassar só a string `repos` e `starred`, o seu segundo exemplo está correto.

Aí, lá dentro do componente `Repos`, vc pode usar `style[className]`, que vai funcionar corretamente, já que `className` vai vir preenchida como `repos` ou `starred`, e essas duas classes existem no seu CSS `repos.css`.

---

É importante lembrar que, no momento em que você usa `style.repos`, o valor retornado disso não é a string `.repos`, e sim a hash criada pelo CSS Modules. Então, ainda que existisse uma classe `.repos` no seu arquivo `app.css`, e você tentasse repassar essa classe como no seu exemplo:

```
<Repos className={style.repos} />
```

O componente `Repos` não iria receber essa string da classe como `repos`, e sim com uma hash. Logo, lá dentro do `Repos` você não conseguiria usar `style[className]`, já que `className` não seria preenchido com `repos`, e sim com uma hash. Algo como `_4Dj-ZCDkkwX7iHNGJWUSP`.

Por isso seu código não estava funcionando :)

Deu pra entender a ideia? Talvez pareça um pouco complicado no início, pq o webpack está transformando seu código no momento da execução dele, enquanto você está desenvolvendo. Como no caso da classe: ao usar `style.repos`, ao invés de colocar a classe `repos` no elemento, uma hash é que será adicionada como nome da classe. Essa transformação acontece em _runtime_, ou seja, no momento em que seu código está rodando.

Me deixe saber se ficou claro, qualquer coisa eu tento explicar de outro jeito, ok? :D
