### ISSUE TITLE
[M1#A30] - Como controlar o select com multiple?

### ISSUE THREAD

**Issue by pedrokohler** [da2k/curso-reactjs-ninja#426]
```
import React from "react";

class Select extends React.Component {
    constructor() {
        super();
        this.state = {
            value: [1, 2]
        };
    }

    render() {
        return (
            <select
                multiple
                name="select"
                id="select"
                value={this.state.value}
                onChange={e => {
                    console.log(e.target.value);
                    this.setState({
                        value: e.target.value
                    });
                }}
            >
                <option value="1">opção 1</option>
                <option value="2">opção 2</option>
                <option value="3">opção 3</option>
                <option value="4">opção 4</option>
            </select>
        );
    }
}

export default Select;
```

No código acima o React permite apenas uma seleção por vez. Ele vem selecionado com as duas normalmente, porém não funciona quando tento selecionar. O motivo é que o valor de e.target.value vem como apenas um dos value, e não o array escolhido.

Como fazer para atualizar para o array desejado?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pedrokohler! Sobre o select multiple, eu não cheguei a entrar muito a fundo nele, mas basicamente é o seguinte:

O evento vai te retornar a coleção dos "options" selecionados em `selectedOptions`. O que você precisa fazer é simplesmente transformar essa _HTML Collection_ em array, para poder iterar por ela e pegar somente o `value` de cada um dos options selecionados, para adicionar no state.

O código seria mais ou menos assim:

```jsx
<select multiple value={this.state.value} onChange={(e) => {
  this.setState({
    value: [...e.target.selectedOptions].map((option) => option.value)
  })
}}>
```

A parte `[...e.target.selectedOptions]`  cria um novo array para podermos usar o método `map`.

Poderíamos também usar `Array.from(e.target.selectedOptions)` . O resultado é o mesmo =)

Então simplesmente iteramos pelo array, usando o `map`, que retorna um novo array. Esse novo array vai ter, no lugar dos `options`, apenas o valor deles (`option.value`).

Fazendo isso, o `this.state.value` vai ser um array só com os valores selecionados, e tudo vai funcionar como esperado =)

**Comment by pedrokohler** [comment]
Muito obrigado! @fdaciuk

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
