### ISSUE TITLE
M2#A45: Storybook - extendendo o webpack.config padrão

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#428]
Saudações, mestre.

Como você sabe, estou tentando manter o app com o css?modules. Bem provável que eu me depare com alguns issues extras por conta disso, mas ok.

Então a respeito do Storybook e das extensões do webpack.config.js, estou perdendo os estilos quando utilizo o código da aula (M2#A45).

Não os perco se eu mantiver o storybook/webpack.config.js sem extensões, isto é:
```
module.exports = {
  module: {
    preLoaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'standard'
    }],

    loaders: [{
        test: /\.css$/,
        exclude: /node_modules/,
        include: /src/,
        loaders: ['style', 'css?modules']
    }]
  }
}
```
Mas perco os estilos caso tente substituir o bloco acima pelo seguinte código:
```
const webpackConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js')

module.exports = function (config, env) {
  const newConfig = webpackConfig(config, env)

  newConfig.module.preLoaders = [{
    test: /\.js$/,
    exclude: /node_modules/,
    include: /src/,
    loader: 'standard'
  }]

  return newConfig
}
```
Não quero me apegar muito a isso. Vou seguir adiante. Mas quis vir aqui para te consultar e, talvez, confirmar de que, neste caso, então talvez eu devesse abrir mão do css?modules.

Ou será que haveria uma forma de contornar isso e conseguir manter o css?modules e utilizar a extensão do webpack.config.js?

Gratidão! Grande abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Consegue compartilhar o link do repo do seu projeto aqui pra eu dar uma olhada? Mais fácil colocar aqui pra rodar, pra entender o que pode estar acontecendo :)

**Comment by pamplonapaulo** [comment]
Claro!

Aqui ta o link direto pro meu storybook/webpack.config.js

A parte comentada é o código que não renderiza o CSS quando subo o http://localhost:6006/

https://github.com/pamplonapaulo/cursoReactjsNinjaBackup/blob/master/m2/working-with-assets/github-app/storybook/webpack.config.js

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Entendi o problema :) 
O storybook já tem uma configuração de loaders para CSS, então você precisa sobrescrever só essa configuração. Pra fazer isso, é bem simples: basicamente você precisa iterar o `newConfig.module.loaders`, e utilizar o método `.test` de regex, pra ver se a regex casa com o final de um arquivo `.css`. O código final ficaria assim:

```js
'use strict'

const webpackConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js')

module.exports = function (config, env) {
  const newConfig = webpackConfig(config, env)

  newConfig.module.preLoaders = (newConfig.module.preLoaders || []).concat({
    test: /\.js$/,
    exclude: /node_modules/,
    include: /src/,
    loader: 'standard'
  })

  // até aqui é o código que vc já tinha. Abaixo segue o novo código:
  // a primeira coisa é iterar o `newCofig.module.loaders`, usando o `map`, pois nós queremos um array exatamente do mesmo tamanho do anterior, mas com algumas propriedades alteradas. Fazemos a reatribuição porque o `map` retorna um novo array, e não modifica o original.
  newConfig.module.loaders = newConfig.module.loaders.map(loader => {
  // aqui nós verificamos se o que está na propriedade "test" do loader casa com um arquivo CSS, que é o que nós queremos. Se você abrir o arquivo padrão da configuração do storybook, você vai ver que tem vários loaders para JSON, imagens, etc., e junto deles, está o loader para CSS (no caso, o valor que procuramos é o "test" que tenha a regex `/\.css$/`). Para verificar, usamos o método `.test` de regex.
  // Nesse if, eu inverti: verifiquei se a regex NÃO CASA, pois, se não casar, ele vai retornar o mesmo loader, sem modificações. Fazendo o teste "invertido", podemos deixar nosso lógica fora do "if", com um nível de indentação a menos ;)
  if (!loader.test.test('test.css')) {
      return loader
    }

  // se chegar aqui, significa que temos o loader de CSS. Então nós "copiamos" todas as propriedades do objeto `loader` atual, usando o "spread operator", e então modificamos só a propriedade "loaders", com os valores que precisamos:
    return {
      ...loader,
      loaders: ['style', 'css?modules']
    }
  })

  return newConfig
}
```

Pronto! Ao fazer isso, tudo vai funcionar como esperado :)

Deixei comentado pra facilitar o entendimento. Me deixe saber se ficou claro, ou se ainda tem alguma dúvida :)

**Comment by pamplonapaulo** [comment]
Mestre, ficou bem claro. Muito bem explicado! Gratidão! Vou ajustar agora meu código com base nisso tudo! Abração e muito grato!

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :)
