### ISSUE TITLE
M1#A32 - html plugin

### ISSUE THREAD

**Issue by MarceloMileo** [da2k/curso-reactjs-ninja#429]
Boa tarde Felipe, tudo tranquilo?
Seguinte, meu html plugin não esta criando o index.html na raiz, eu ja removi o arquivo que já estava no projeto, removi e instalei novamente as dependencias, inclusive o package-lock.json e nada.
No terminal aparece que esta tudo funcionando.
![m1a32](https://user-images.githubusercontent.com/10727171/76647942-83173200-653c-11ea-9941-ea5b5fb688ea.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MarceloMileo! O `html-webpack-plugin` não cria o arquivo `index.html`, ele só edita o arquivo já criado, adicionando os scripts e CSS necessários. Você tem que deixar o arquivo criado :)

**Comment by MarceloMileo** [comment]
Hummmm......Entendi.

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
