### ISSUE TITLE
M2#A52 - Problema no `yarn test:watch`

### ISSUE THREAD

**Issue by gabrielferreiraa** [da2k/curso-reactjs-ninja#43]
Boa tarde cara, beleza ? Faz um tempo que não apareço por aqui rs

Então, estava configurando o ambiente de testes e linter. Funcionou tudo perfeitamente, porém, não sei por qual motivo o `yarn test:watch` não funciona, o `yarn test` sem watch funciona normalmente !!
Da uma olhada no `package.json`, não achei nada de errado :/

https://github.com/gabrielferreiraa/starterKitReact/blob/master/package.json

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @gabrielferreiraa! Qual problema deu aí pra você? Testei aqui e está funcionando certinho =)

A única coisa que pode acontecer é ele não rodar os testes de primeira, quando você roda o `yarn test:watch`, ae você só pressiona o `a` que ele vai rodar todos os testes novamente =)

Veja se é isso. Se não for, volta aqui que vamos debugando =)

**Comment by fdaciuk** [comment]
@gabrielferreiraa resolveu? =)

**Comment by gabrielferreiraa** [comment]
@fdaciuk, não consegui responder a issue ontem porque isso só esta dando no meu computador do trabalho. Cheguei agora e rodei pra tirar print do erro pra te mandar e rodou normalmente '-' 
Não sei se isso é bom ou ruim. hahah

De qualquer forma, desculpe. Pode fechar a issue.

Valeu pela atenção, abraço!

**Comment by fdaciuk** [comment]
haha! Tranquilo cara =)
Se continuar dando problema, nós abrimos a issue novamente e vamos debugando =)
