### ISSUE TITLE
M1#A27 - Erro React.PropTypes.func

### ISSUE THREAD

**Issue by klauswolfgram** [da2k/curso-reactjs-ninja#431]
Olá, quando tento adicionar no componente botao o trecho de codigo referente à propTypes, indicando que o handleClick recebera React.PropTypes.func, ao tentar carregar a pagina, a seguinte mensagem é exibida: TypeError: Cannot read property 'func' of undefined

```
import React from 'react';
import './style.css';

const Botao = ({children,handleClick}) => (
    <button onClick={handleClick} style={{
        backgroundColor: children
        }}>
        {children}
    </button>
)

Botao.propTypes = {
    handleClick: React.PropTypes.func
}

export default Botao
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @klauswolfgram! Dá uma olhada na versão do React que você tem instalada.. à partir da v15.5, o prop-types passou para uma lib separada do core do React (eu abordo isso no módulo 2) :)
Se você usar exatamente a versão exibida na aula, você vai conseguir seguir o cuso conforme mostrado :)

**Comment by klauswolfgram** [comment]
Ok, obrigado pelo retorno. Eu fiz o import da biblioteca prop-types.

**Comment by fdaciuk** [comment]
Legal! Qualquer coisa, só avisar :)
