### ISSUE TITLE
erro ao instalar react

### ISSUE THREAD

**Issue by mjuliano21** [da2k/curso-reactjs-ninja#432]
Olá não estou conseguindo instalar o react, apenas o react-dom. tentei utilizar a versão atual bem como a versão orientada na documentação

![image](https://user-images.githubusercontent.com/8331048/77550050-64476280-6e8f-11ea-8420-7898b253cf94.png)

**Comment by fdaciuk** [comment]
Oi @mjuliano21! O problema é que o nome do diretório do seu projeto é `react`. Nesse caso, o NPM se perde ao tentar instalar um pacote, pois ele pensa que está instalando o pacote em si mesmo, saca? haha!

Só renomeie seu diretório `D:\Cursos\React` para qualquer outra coisa (`D:\Cursos\ReactNinja`, por exemplo), que vai funcionar :)

---

OBS.: Não remova a marcação do meu usuário da issue (aquele `@fdaciuk` que aparece ao criar a issue), senão eu não recebo notificação da sua dúvida, ok? :)

**Comment by mjuliano21** [comment]
kkkkk ta brincando rsrs, valeu pela ajuda.

**Comment by fdaciuk** [comment]
Já passei por isso, normal haha! Qualquer coisa, só avisar :)
