### ISSUE TITLE
handleChangeCheckbox

### ISSUE THREAD

**Issue by abrandemburg** [da2k/curso-reactjs-ninja#434]
```
if (
      checkboxesChecked(checkboxes).length === flavours &&
      e.target.checked === true
    ) {
      return
    }
```

Não entendi a lógica desse código, pelo que entendi a condição é:
Se o checkbox já estiver no limite de sabores E o target que estou selecionando é true, então ignoramos.

Mas se o nosso target do handleClick está True não quer dizer que eu clicando nele o trocaria pra false? pra liberar o array de uma nova escolha? 

Se eu tenho 2 escolhas, e tenho 2 sabores como true, pra liberar espaço eu teria que selecionar novamente um TRUE para troca-lo para FALSE. Caso a minha escolha não seja um target TRUE então eu teria que ignorar porque estaria no limite de escolhas.

Me enrolei todo nesse código rsrs

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @abrandemburg! O valor que vem em `e.target.checked` ainda não é o valor real setado no checkbox, já que nosso checkbox tem seu estado controlado pelo React.

Então o `e.target.checked` é apenas a **intenção** de modificar para `true`. Ele só será alterado de fato quando executarmos a função que altera esse estado.

Isso significa que, se ele vier como `true`, quer dizer que ele **não estava** selecionado, e o usuário estava tentando selecionar. Por isso ignoramos :)

Ficou claro? :)

**Comment by abrandemburg** [comment]
Perfeito! Suspeitava que fosse algo assim, valeuu

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
