### ISSUE TITLE
Link direcionando para HOME sem 'to='

### ISSUE THREAD

**Issue by abrandemburg** [da2k/curso-reactjs-ninja#435]
```
<MainContent>
          <Input value={quantity} onChange={handleChange} autoFocus />
          <Button variant='contained' color='secondary' component={Link} onClick={addPizzas}>
            Adicionar e montar outra pizza
          </Button>
        </MainContent>
```

Como rola esse direcionamento pra HOME depois de adicionar a order ao context? O Link não precisa de um 'to={HOME}' pra direcionar? Ali só foi passado o Link

@fdaciuk

**Comment by abrandemburg** [comment]
Resolvido no vídeo seguinte

**Comment by fdaciuk** [comment]
Oi @abrandemburg! Que bom que resolveu :)
Qualquer coisa, só avisar :)
