### ISSUE TITLE
Pedido duplicado

### ISSUE THREAD

**Issue by abrandemburg** [da2k/curso-reactjs-ninja#436]
Eu não achei muito legal a resolução do problema de pedido duplicado. Quer dizer, passar pro usuário a responsabilidade de remover um 'problema' que não deveria ter. 

O modelo da aplicação que não ajuda em resolver?
A complexibilidade de lidar com problema deriva de passar os states pela rota e depois joga-las no context?

Se puder me dar uma direção pra eu tentar resolver esse 'bug' pq se não vai ficar difícil dormir rsrsrs. Se não for pertubar muito agradeço!

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae @abrandemburg! Existem várias maneiras de resolver o mesmo problema :)
Uma solução diferente da que foi mostrada na aula seria usar somente a Context para salvar as informações. A diferença dessa abordagem é que, ao usar os botões de navegação do browser, você não vai ter o estado da página anterior.

Mas isso seria facilmente resolvido se você colocasse todas as opções de escolha da pizza na mesma página :)

Enfim, existem várias de resolver, várias formas de apresentar esse conteúdo. Eu mostrei apenas uma delas. Fique à vontade para usar a imaginação e mudar como você achar que fica melhor :D

**Comment by abrandemburg** [comment]
Nice. 
Foi mal se pareceu que questionei sua solução, foi mais uma escolha pessoal em relação a como tratar. Mas agora ficou bastante claro, é melhor deletar o item que perder o estados.

Valeu!

**Comment by fdaciuk** [comment]
Nada cara! Esses questionamentos são super importantes! Eu sempre mostro uma solução para o problema (às vezes duas ou mais, dependendo do caso), mas nem sempre a solução que eu apresentar é a melhor forma de fazer.

Muitas vezes você vai analisar meu código, e vai encontrar melhores formas de resolver o mesmo problema, e isso **é ótimo!**

Continue questionando mesmo, pois é assim que evoluímos!

E conte comigo sempre que precisar :D
