### ISSUE TITLE
Módulo de Atualizações

### ISSUE THREAD

**Issue by lucas-brilhante** [da2k/curso-reactjs-ninja#437]
Olá, Fernando. Gostaria de saber se tem alguma previsão do lançamento do módulo de atualizações.
Estou bastante ansioso por ele.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucas-brilhante! Eu tô correndo pra finalizar a última parte da React-zzaria.. provavelmente até início da próxima semana já devo ter as últimas aulas gravadas :)

À partir daí, já vou começar a regravar os primeiros módulos, atualizando para a versão mais recente do React :D

**Comment by Yago-M-A** [comment]
Sei que aqui não é o local mais adequado, mas gostaria de tirar um dúvida, assistindo todas as aulas do curso já existentes, consigo iniciar uma carreira no mercado com o React?

OBS: Só tenho conhecimento de Javascript, básico de CSS e HTML, meu conhecimento de Javascript foi adquirido com o seu curso Ninja, :)

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Com certeza! Tenho vários alunos que conseguiram seu primeiro emprego só com o cursod e JS :)

Pegando bem o React, você tem ainda mais chances :)

**Comment by Yago-M-A** [comment]
Obrigado pela resposta.
