### ISSUE TITLE
M2#A07

### ISSUE THREAD

**Issue by gilnei** [da2k/curso-reactjs-ninja#438]
E ae @fdaciuk , blz? Estou tentando rodar o jest, mas empaquei na aula m2#a08 --> o problema é que ao rodar o jest, ele sempre diz que espera só função. Você tem idéia do que poderia ser? 

Esse é o erro quando rodo o 
npm test "--no-cache"

ou ate mesmo com o watch
```
 


 FAIL  src/sum.test.js
  ● Test suite failed to run

    Plugin/Preset files are not allowed to export objects, only functions. In _[meu diretorio]_ /jest/node_modules/babel-preset-es2015/lib/index.js

      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
          at Array.map (<anonymous>)

```

o git que tem esses arquivos é o https://github.com/gilnei/udemy-reactninja-lessons
Obrigado! 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gilnei! Isso é problema com versão de alguma das dependências :)
Se você seguir as versões [mostadas aqui](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), tudo vai funcionar como esperado :)

**Comment by rodrigosilvario** [comment]
@fdaciuk  Não está dando para seguir, mesmo com as dependências está dando este erro. Faltou então as versões. 

Só o Jest-cli puro já não funciona mais, só funcionou com a versão atual.

**Comment by fdaciuk** [comment]
@rodrigosilvario esse erro é especificamente do babel. Dependendo da versão do jest que você instalou, ele pode usar uma versão do babel diferente da que está no seu projeto. Então, na hora de ler o seu arquivo de configurações do webpack, ao encontrar as configurações para uma versão mais antiga do babel, ele vai dar esse erro, pois em uma versão ele esperava um objeto, onde em outra ele espera uma função.

Se você criar um projeto com Create React App, por exemplo, que já usa a versão mais recente do webpack e babel, vai conseguir usar a versão mais recente do Jest também, sem maiores problemas (até porque o Jest já vem instalado no Create React App) :)

**Comment by kadoshmt** [comment]
@gilnei @rodrigosilvario 
Aqui também não funcionou com o código do curso. Parece não funcionar bem com o Babel 6. Então fiz as seguintes configurações e consegui avançar no curso:

**package.json**
`{
  "scripts": {
    "test": "jest --coverage",
    "test:watch": "npm test -- --watchAll"
  },
  "devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/preset-env": "^7.6.0",
    "babel-jest": "^25.4.0",
    "chai": "^4.2.0",
    "jest-cli": "^25.4.0"
  }
}`

**.babelrc**

`{
  "presets": ["@babel/preset-env"], // converte o codigo para navegadores
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}`

**Comment by kadoshmt** [comment]
{
  "scripts": {
    "test": "jest --coverage",
    "test:watch": "npm test -- --watchAll"
  },
  "devDependencies": {
    "@babel/cli": "^7.6.0",
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/preset-env": "^7.6.0",
    "babel-jest": "^25.4.0",
    "chai": "^4.2.0",
    "jest-cli": "^25.4.0"
  }
}


{
  "presets": ["@babel/preset-env"], // converte o codigo para navegadores
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}

**Comment by fdaciuk** [comment]
@kadoshmt com a versão mais recente do Jest, vai precisar da versão mais recente do babel também. No curso estamos usando babel 6 e o Jest 15. Os dois funcionam corretamente juntos :)

**Comment by kadoshmt** [comment]
@fdaciuk Por algum motivo não funciona. Fiz exatamente seguindo [este guia](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) e dava esse mesmo erro. Instalando a versão 15 do Jest e a versão 6 do Babel dava esse erro de plugin. Pesquisei no stackoverflow e achei esta solução usando o Babel 7. Só consegui prosseguir mudando a versão do Babel (dai usei a versão mais atual do Jest ). Então, para quem não estiver conseguindo progredir, pode tentar esta solução. Pelo menso aqui funcionou.

**Comment by fdaciuk** [comment]
@kadoshmt entendi. Vou fazer alguns testes novamente com as versões do arquivo de dependências, só pra garantir que continua tudo certo =)

**Comment by fdaciuk** [comment]
Oi @gilnei, @rodrigosilvario e @kadoshmt! Eu fiz os testes aqui com as versões mostradas no 
[arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), instalando tudo do zero, e funcionou perfeitamente :)

Por favor, dêem uma olhada se você instalaram as dependências exatamente como [pede aqui nessa linha](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#m2a07).

Esse erro normalmente vai acontecer se você instalar a versão mais recente do `babel-core` e `babel-jest`. Usando as versões do link acima, vai funcionar exatamente como mostrado na aula :)
