### ISSUE TITLE
Dúvida M1#A43

### ISSUE THREAD

**Issue by Yago-M-A** [da2k/curso-reactjs-ninja#439]
E aí, fdaciuk, tudo beleza?
Fiz seu curso do Javascript Ninja e tinha até entendido o ```this```, mas nessa aula acabei ficando confuso, o ```this``` que está dentro do ```getRepos={this.getRepos('repos')}``` ele aponta para o App?
Eu pensei que ali dentro do ```return```  do ```render```, para apontar para o App, só usando Arrow Function, pois na minha cabeça, dentro do ```render e o return``` ali é uma closure e justamente por ser uma closure, devemos utilizar a Arrow Function que é léxica para apontar para o App, será que deu para entender minha dúvida?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Entendi sua dúvida sim :)

Vamos lá: o método `render` é um método da `class App` (que por baixo dos panos, é uma função construtora, como você viu no curso JS Ninja). Logo, o `this` ali dentro vai sempre apontar para o objeto criado à partir dessa classe.

O `this` só vai mudar quando ele for executado em um escopo diferente: por exemplo, dentro de uma função que for definida como _listener_ de algum evento. Nesse caso, usando a API DOM "pura", o `this` vai apontar para o objeto que está recebendo o evento.

No React, nesse caso, o `this` é setado para `null` :)

Então a ideia de usar uma arrow function é apenas para momentos onde o método vai ser definido como listener de algum evento, que seria exatamente o momento em que o `this` seria redefinido.

Como _arrow function_ tem escopo léxico, o `this` dentro da _arrow function_ vai apontar para o objeto do momento em que a função foi criada :)

Ficou mais claro? :)

**Comment by Yago-M-A** [comment]
Entendi, obrigado pela resposta.

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
