### ISSUE TITLE
M2#A13 - Map recursivo

### ISSUE THREAD

**Issue by willianribeiro** [da2k/curso-reactjs-ninja#44]
Faaaala Daciuk, tudo certin?!

Em um ponto da aula 13 temos este código [1]. Neste momento você comenta que para termos uma programação 100% funcional precisamos remover o if. Então chegamos a este outro código [2].

A minha pergunta é: por que em programação funcional não poderiamos ter o if? O ternário faz quase a mesma coisa (ao meu ver), mas ele é permitido e o if não, por quê isso ? .-.

Me ajuda a esclarecer? Abraço!

[1]
```
'use strict'

const map = (arr = [], func = (item) => item) => {
    const counter = 0;

    return (function mapInternal (arrInternal, counter) {
        if (arrInternal.length === 0)
            return [];

        const [head, ...tail] = arrInternal;
        return [
            func(head, counter, arr), 
            ...mapInternal(tail, counter + 1)
        ];
    })(arr, counter);
}

export default map;
```

[2]
```
'use strict'

const map = (arr = [], func = (item) => item) => {
    const counter = 0;

    return (function mapInternal (arrInternal, counter) {
        const [head, ...tail] = arrInternal;
        
        return arrInternal.length === 0 ? [] : [
            func(head, counter, arr), 
            ...mapInternal(tail, counter + 1)
        ];
    })(arr, counter);
}

export default map;
```

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @willianribeiro, tudo certo, e contigo? =)
Então, o que acontece é que, em programação funcional, você não tem blocos de código, tudo é uma expressão, ou seja, tudo retorna algum valor. O `if`, por si só, só gera um bloco de código, ele não retorna valor algum. Já o ternário sempre retorna um valor.

Pra tentar deixar mais claro. Você não consegue fazer isso:

```js
const value = if (1 < 2) {
  1
} else {
 2 
}
```

Porque o `if` serve somente como um bloco de código. Para atribuir o valor `1` ou `2` para value, você teria que fazer uma mutação na variável:

```js
let value
if (1 < 2) {
  value = 1
} else {
  value = 2 
}
```

Veja que temos que modificar o valor inicial de `value`, e em programação funcional (ou linguagens puramente funcionais), você deve trabalhar com **imutabilidade**.

Sacou? O `if` gera um bloco de código, e dentro dele você consegue colocar expressões, mas o bloco serve somente para "centralizar" operações.

Já o ternário retorna um valor, então você consegue atribuir o resultado dele a uma variável:

```js
const value = 1 < 2 ? 1 : 2
```

Ficou claro? =)

**Comment by willianribeiro** [comment]
Hmmm entendi!
Quando puder vou estudar sobre programação funcional, pra mim hoje é algo nebuloso hahaha
Obrigado por esclarecer! Abraço!

**Comment by fdaciuk** [comment]
Legal @willianribeiro :D 
Recomendo começar com Haskell, que é uma linguagem puramente funcional, e tem uma sintaxe linda <3
Qualquer dúvida, só avisar =)
