### ISSUE TITLE
M1#A54 

### ISSUE THREAD

**Issue by Yago-M-A** [da2k/curso-reactjs-ninja#440]
Finalizei o módulo 1 e estou com uma dúvida, pois no projeto do GitHub app, pelo o que entendi, foi utilizado mais circuit braker e manipulação dos dados, a minha dúvida é sobre quando usar o componentDidMount, etc. Acabei ficando meio confuso sobre isso.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! O `componentDidMount` é usado quando você precisa executar algum código logo que o componente monta, sem a necessidade de intervenção do usuário.

Assim que o componente monta, e o elemento é adicionado ao DOM, você pode usar o `componentDidMount` para fazer as manipulações necessárias nesse componente, ou fazer algum request para trazer dados que serão adicionados ao estado do seu componente, e serão renderizados nesse componente que acabou de montar.

Ficou mais claro? :)

**Comment by Yago-M-A** [comment]
Minha dúvida não é só sobre o ```componentDidMount```, é sobre ```component``` em geral, qual momento devo usar esses métodos de ciclo de vida, mas acho que fica meio difícil explicar por aqui, acho que vou seguir assistindo o módulo 2, pelo o que me parece, no módulo 2 você vai acabar usando eles, aí eu acabo tendo mais uma noção de como usar.

**Comment by fdaciuk** [comment]
Acho que consegui compreender melhor sua dúvida :)
Mas não existe uma resposta exata: você deve usá-los quando sentir necessidade na sua aplicação. Por isso é importante entender em que momento esses métodos são chamados. 

Mas o que vai trazer mais clareza para o uso de cada um desses métodos, é a prática do dia a dia. Tente criar outros pequenos projetos, que com a mão na massa, tudo começa a ficar mais claro :)

E conte comigo sempre que tiver dúvidas :)

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
