### ISSUE TITLE
M4#A34 Arquivo package.json faltando as tags de escript

### ISSUE THREAD

**Issue by rafael-marques** [da2k/curso-reactjs-ninja#441]
Fiz a instalação usando o `create-react-app nome-do-projeto` porém ao finalizar, ele não adiciona os scripts. Houve alguma atualização?

➜ create-react-app -V
3.2.0

➜ node -v
v12.16.1

➜ yarn -v
1.13.0

➜ npm -v
6.13.4

![image](https://user-images.githubusercontent.com/8671936/78372795-183ba280-75a0-11ea-857d-ea5bf4ebf727.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafael-marques! Deve ter dado algum erro na hora da sua instalação. Tente remove o `create-react-app` global, e instale via `npx` ou `yarn create`. Os comandos são:

```
npx create-react-app nome-do-projeto
```

Ou, com yarn:

```
yarn create react-app nome-do-projeto
```

Esses comandos vão fazer utilização da versão mais recente do CRA :)

Me deixe saber se deu tudo certo, ou se teve algum problema durante a instalação :)

Obs.: Lembrando que é importante o diretório `nome-do-projeto` **NÃO EXISTIR** antes de rodar algum dos comandos acima, ok? :)

**Comment by rafael-marques** [comment]
@fdaciuk funcionou apenas com o 
`yarn create react-app nome-do-projeto`

O npx não funcionou (v. 6.13.4).

Outra coisa, eu rodei
` npm uninstall -g create-react-app`
e não removeu a versão global. O que poderá ser?

**Comment by fdaciuk** [comment]
Você instalou o `create-react-app` global com o NPM ou com o Yarn? Se foi com o Yarn, o comando para remover é:

```
yarn global remove create-react-app
```

Dá uma olhada se não foi isso :)

**Comment by rafael-marques** [comment]
Cara, tentei remover com os dois mas não rolou. Mas de boa, vou rodar direto sem ser global mesmo :) Obrigado

**Comment by fdaciuk** [comment]
Tranquilo :)
Uma dica: se estiver usando Linux, você consegue ver onde o executável do CRA está instalado usando o comando:

```
which create-react-app
```

Se não for Linux, aí não sei te dizer :)
De qualquer forma, usando `npx` ou `yarn create`, ele já deve ignorar a versão instalado globalmente :)

Qualquer coisa, avisa aí :)

**Comment by rafael-marques** [comment]
Apenas para informação. o comando `which` funcionou sim e me mostrou onde estava no Mac ;) Valeu

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)

**Comment by angelilton** [comment]
fala @rafael-marques você teve algum problema futuro com o curso? 
pergunto porque tentei usar a versão 2.1.1 do create-react-app e tive o mesmo erro ai no erro do console ja falou da versão
