### ISSUE TITLE
M3#A47 

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#442]
fala daciuk tudo bem? 
vc poderia me explicar de outro modo esse trecho que code que vc fez para substituir o switch
não entendi como ele seria mais performático e como a logica em si terminar pq ele ainda entra em um filtro e depois um map certo!?
```
const showTodos = (todo, activeFilter) => {
  const filterItems = {
    [SHOW_ALL]: todo,
    [SHOW_DONE]: todo.filter((item) => item.completed),
    [SHOW_DOING]: todo.filter((item) => !item.completed)
  }
  return filterItems[activeFilter]
}
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! O `filter` e `map` já seriam feitos de qualquer forma, então isso não vai afetar em nada. A grande diferença é na leitura do código: é muito mais claro você ler um objeto de/para, do que fazer uma leitura de mais linhas de um switch/case, onde é preciso um `return` ou `break` para garantir que ele vai parar de executar, não acha? :)

**Comment by angelilton** [comment]
sim valeu
