### ISSUE TITLE
Problema com testes - M2#A04

### ISSUE THREAD

**Issue by ricardocaiuba** [da2k/curso-reactjs-ninja#443]
Fala Fernando, tudo bem?
Estou tendo um contratempo na aula M2#A04.
Em um arquivo de nome <strong>sum.test.js</strong> Escrevi o seguinte código conforme seu exemplo:
```
"use strict";

it("Um é igual a um", () => {
  console.assert(1 === 2, "1 não é igual a dois");
});
```
quando eu rodo o test, ele não me mostra a tag "FAIL". Ele fica dessa maneira:

```
 PASS  ./sum.test.js
  √ Um é igual a um (11ms)

  console.assert sum.test.js:4
    AssertionError [ERR_ASSERTION]: 1 não é igual a dois
```

Deixei o código em https://github.com/ricardocaiuba/jest-in-practice

Desde já, muito obrigado.

@fdaciuk

**Comment by rodrigosilvario** [comment]
Eu estou tendo  um problema parecido, no meu caso o sistema nem reconhece os testes. Ele dá match mas não executa.

**Comment by fdaciuk** [comment]
Oi @ricardocaiuba! Houveram algumas alterações no comportamento do `console.assert` em versões mais recentes do Node.js (você pode ver uma discussão sobre isso [aqui](https://github.com/facebook/jest/issues/5634)). Da versão 10 pra frente, o `console.assert` não gera mais um erro.. ele simplesmente exibe no console uma mensagem dizendo que o teste não passou, por isso o Jest não exibe o "Fail".

Para continuar tendo o comportamento anterior, foi criada uma biblioteca chamada `assert`, que dispara um erro. Essa biblioteca serve especificamente para quem vai manter o uso do `console.assert` nos seus códigos. A implementação, no seu caso, seria algo bem simples.Só fazer a instalação do `assert`:

```
npm i --save-dev assert
```

E depois reatribuir a função do `console.assert`, passando essa função.

Usando o sistema de módulos padrão do Node (CommonJS):

```js
'use strict'

console.assert = require('assert')
```

Ou, se sua aplicação já estiver configurada para usar ES Modules:

```js
import assert from 'assert'
console.assert = assert
```

Com isso, esse exemplo vai funcionar como esperado. Mas eu recomendaria você não se preocupar com isso no momento, que nas próximas auas eu vou mostrar com usar a ferramenta de asserção do próprio Jest. O `console.assert` foi só um exemplo inicial :)

**Comment by ricardocaiuba** [comment]
Maravilha man.
Muito obrigado.
@fdaciuk
