### ISSUE TITLE
Erro webpack + hotreload: Cannot read property 'entryOption' of undefined

### ISSUE THREAD

**Issue by psybox** [da2k/curso-reactjs-ninja#444]
Erro ao tentar usar hotreload no módulo 10:

Cannot read property 'entryOption' of undefined

@fdaciuk

**Comment by psybox** [comment]
consegui resolver alterando a versão do webpack-dev-server para "webpack-dev-server": "^1.16.5"
estava versão 3 (mesmo eu não tendo colocado manualmente essa versão)

**Comment by psybox** [comment]
nesses casos, qual a recomendação? Reinstalar o módulo com o comando que tem a versão aqui ou mudar na mão no packages.json?

**Comment by fdaciuk** [comment]
Oi @psybox! Para seguir o curso da forma como eu mostrei, o ideal é sempre seguir as versões mostradas no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md).

Dessa forma, tudo o que estiver mostrando em aula, você vai conseguir seguir exatamente igual :)

**Comment by psybox** [comment]
oi @fdaciuk como comentei acima eu segui, igualzinho, porém pelo que li o npm pode atualizar outros pacotes ao instalar um novo.

**Comment by psybox** [comment]
obrigado pelo retorno de qualquer forma.

**Comment by fdaciuk** [comment]
@psybox ali no arquivo está a v1 do webpack-dev-server mesmo, então seguindo com essa versão deve funcionar sem problemas :)
Mas assim: se ainda seguindo as recomendações do arquivo de dependências você tiver qualquer problema, só avisar aqui, e postar seu repo pra eu testar local, que vou te ajudando a resolver, ok? :)

**Comment by fdaciuk** [comment]
Só um ponto importante: sobre a versão do webpack-dev-server estar na v3, mesmo você não tendo instalado essa versão: normalmente isso não acontece, pois o `npm` só atualiza versões `patch` e `minor`, quando a dependência começa com `^` (`patch` é o terceiro número, e `minor`, o segundo). A `major` (primeiro número da versão) nunca deveria subir automaticamente.

Mas pra entender porque isso aconteceu, teria que analisar mais a fundo. Sinceramente, nunca vi isso acontecer. Se de fato foi o que rolou, pode ter algum bug no NPM.. então é bom sempre ficar de olho, e se for o caso, abrir uma issue no repo do NPM avisando do problema :)

**Comment by psybox** [comment]
Provável que tenha sido um erro meu. Vou ficar de olho, obrigado.
