### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by Yago-M-A** [da2k/curso-reactjs-ninja#446]
Boa noite, Daciuk, ainda estou indo para o módulo 3, mas estou empolgado com o curso e gostaria de saber se tem alguma previsão para novas aulas?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Que bom que está empolgado \o/ 
Na próxima semana eu já devo liberar as últimas aulas do módulo 4, depois vou atualizar os primeiros módulos, pra refletirem a versão mais recente do React :D

**Comment by Yago-M-A** [comment]
Vi em alguma issue do ano passo no mês de abril, você falando que vai lançar um módulo sobre Node, depois SSR, etc.
Como estão os planos, depois de tanto tempo dessa issue?

**Comment by fdaciuk** [comment]
A Udemy tem uma limitação na quantidade de aulas.. o curso hoje já está com mais de 80h, então ainda vou fazer isso, mas vai ser em um curso separado :)

**Comment by Yago-M-A** [comment]
@fdaciuk 
Pelo pouco que vi você tirando as dúvidas do pessoal, no módulo 4 é um projeto no estilo real, como se fosse no mercado de trabalho, nesse projeto você fez os testes unitários?

O Node e o SSR vão ser separado desse curso aqui?

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Nesse projeto não tem muito o que testar unitariamente. O que não foi feito, mas poderia, nesse caso, seria fazer testes de integração e E2E (end to end, ou testes de ponta-a-ponta), com [Cypress](https://cypress.io) ou o [Pupeteer](https://pptr.dev/).

Sobre o de Node, eu pretendo fazer vários cursos sobre, pois tem muito conteúdo para abordar. Então a parte de SSR vai ser em um curso separado sim :)

**Comment by Yago-M-A** [comment]
Oi @fdaciuk, nesse curso vai ter algo dessa tipo, E2E ou teste de integração?

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Nesse curso infelizmente não vai caber mais conteúdo. Eu falei bastante sobre testes unitários, mas integração e E2E vai ter que ficar para um próximo :)

**Comment by fdaciuk** [comment]
Oi @Yago-M-A! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
