### ISSUE TITLE
import de imagens

### ISSUE THREAD

**Issue by JSaints-Dev** [da2k/curso-reactjs-ninja#447]
Professor, o import de imagens no react, pelo que sei tem as opções:
```
const Img from './caminhoDaImagem'
```
```
const Img = require('./caminhoDaImagem')
```
```
import { ReactComponent as Img } from './caminhoDaImagem'
```
sendo esse último se não me engano só para o formato ```.svg```.

Agora minha questão é que estou querendo fazer um caousel de imagens que será gerenciado por um painel administrativo, e a url das imagens virão do banco em formato ```JSON```, ai é só eu colocar essa resposta no ```src={}``` da tag ```<img />``` que irá renderizar a imagem ok?

Agora tem como fazer isso já no desenvolvimento, sem ter a url?

@fdaciuk

**Comment by JSaints-Dev** [comment]
Porquê até agora para eu deixar o componente dinamico eu tive que fazer o import em um component fake, dei um ```console.log()``` para saber o caminho e ai fiz um array com a resposta de cada import e passei pra frente para o component receber... vou postar o trecho do code aqui para tentar ser mais claro

**Comment by JSaints-Dev** [comment]
Component ```fake-data.js```
```
import one from 'images/banner1.svg'
import two from 'images/banner2.svg'
import three from 'images/banner3.svg'

export default [
  {
    id: 0,
    url: one
  },
  {
    id: 1,
    url: two
  },
  {
    id: 2,
    url: three
  }
]
```

**Comment by JSaints-Dev** [comment]
component ```banner.js```

```
import React from 'react'

import styled from 'styled-components'

import Slider from 'react-animated-slider'
import 'react-animated-slider/build/horizontal.css'
import imgs from 'fake-data/banner-data'

const Banner = () => {
  return (
    <BannerContainer>
      <Slider autoplay={2000}>
        {imgs.map((item, i) => {
          return (
            <img key={i} src={item.url} alt='imageOne' />
          )
        })}
      </Slider>
    </BannerContainer>
  )
}
```

**Comment by JSaints-Dev** [comment]
nesse arquivo ```banner-data.js``` tentei sem o import e no valor da url coloquei o valor que está no import, estava assim...
``` 
export default [
  {
    id: 0,
    url: 'images/banner1.svg'
  },
  {
    id: 1,
    url: 'images/banner2.svg'
  },
  {
    id: 2,
    url: 'images/banner3.svg'
  }
]
```

...mas não deu msg de erro no console referente ao import

**Comment by fdaciuk** [comment]
Oi @JSaints-Dev! Para importação estática (quando você tem exatamente o caminho da imagem no momento da importação), é usando um deses 3 caminhos mesmo (o `require` é só para os casos onde não estiver usando ES Modules).

Agora, para importação dinâmica, como você precisa, tem algumas soluções: a mais simples seria já fazer o upload da mesma via backend em algum caminho que essa imagem fique pública (possa ser acessada via request GET sem restrições). Assim, após o request para pegar as imagens que precisam ser renderizadas, você já teria o caminho completo delas.

Existe também uma segunda opção que é: se você quiser deixar as imagens dentro do seu app frontend, e chamar essas imagens no seu código só pelo nome delas, você vai precisar deixar elas dentro do diretório `public` no seu app (levando em consideração que você está utilizando o Create React App), pois o diretório `public` serve tudo o que está ali de forma estática. 

Ou seja: adicionando um diretório `images` dentro de `public`, vc pode acessar qualquer imagem ali dentro assim:

```
<img src='/images/nome-da-imagem.jpg' />
```

Pois o conteúdo do diretório `public` é servido à partir da raiz do seu domínio.

Particularmente eu iria da primeira forma. Com ela, você pode usar algum serviço como o S3 da AWS por exemplo, pra salvar essas imagens e já entregar o caminho completo que o app frontend vai precisar pra renderizá-las :)

**Comment by fdaciuk** [comment]
Oi @JSaints-Dev! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
