### ISSUE TITLE
M2#A07

### ISSUE THREAD

**Issue by AndreLucasrs** [da2k/curso-reactjs-ninja#448]
Eae daciuk, blz ?
Estou tendo problema com a parte de teste e não estou encontrando o problema,
quando rodo o npm test,
no testRegex ate encontra, mas sempre da a mensagem,
No tests found

```
No tests found
  7 files checked.
  testPathDirs: C:\Users\andre\Documents\Udemy\reactjs ninja\m02\jest-in-practice - 0 matches
  testRegex: (/__tests__/.*|\.(test|spec))\.js$ - 1 match
  testPathIgnorePatterns: \\node_modules\\ - 7 matches

```
O git que está com os arquivos 
https://github.com/AndreLucasrs/reactjs-ninja/tree/master/m02/jest-in-practice

@fdaciuk

**Comment by AndreLucasrs** [comment]
@fdaciuk,
descobre o que era mas não entendi o pq acontece mas era por causa do caminho, a pasta em que estava salvando os arquivos do curso esta com espaço
\reactjs ninja
alterei algora para \reactjs_ninja e funcionou

**Comment by fdaciuk** [comment]
Oi @AndreLucasrs! O que acontece é que, qualquer comando que você roda no terminal funciona de forma parecida com funções no JavaScript: o comando do terminal seria a função, e você pode separar por espaço os argumentos passados para essa função.

Quando você tem um diretório com espaço, o que acontece é que parece que a parte após o espaço é um argumento passado para a parte antes do espaço. O comando funcionaria se você envolvesse o caminho todo entre aspas, mas em vários momentos - como nesse caso - você não teria controle sobre o caminho completo para adicoinar as aspas.

Então o ideal é nunca usar espaços para nomes de arquivos e diretórios. Isso é algo pra se levar pra vida toda, em qualquer projeto de programação: todo arquivo e diretório não deveria conter espaços em branco no seu nome, e se precisar separar, use o traço, pra ficar no padrão _kebab-case_ :)

**Comment by AndreLucasrs** [comment]
@fdaciuk, obrigado pela informação, irei seguir esse padrão :call_me_hand:
