### ISSUE TITLE
M1#A13 - Babel React Preset

### ISSUE THREAD

**Issue by camilaibs** [da2k/curso-reactjs-ninja#45]
Oi pessoal, quando instalei o `babel-react-preset` e adicionei `react` no array de presets do **.babelrc**, meu projeto passou a dar esse erro de compilação:
```
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src/index
Module not found: Error: Can't resolve 'babel' in '/Users/camilaibs/Desktop/curso-react-ninja'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index
```
Dai troquei o loader de `babel` para `babel-loader` no **webpack.config.js** e voltou a funcionar, aconteceu isso com vocês, entendi certo o que era para fazer na mensagem de erro?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @camilaibs! Para essa primeira parte do curso, estamos usando webpack na versão 1 (depois atualizamos, com o andamento do curso), então pra acompanhar certinho, instale o webpack e webpack-dev-server na versão 1:

```console
npm i --save-dev webpack@1 webpack-dev-server@1
```

Isso deve resolver até chegar na parte de atualização =)

Vou preparar alguns vídeos específicos sobre versões pra tentar amenizar esses problemas :) 

Mas qualquer dúvida, pode perguntar :D

**Comment by fdaciuk** [comment]
Oi @camilaibs! Isso resolveu o seu problema? =)

**Comment by fdaciuk** [comment]
Oi @camilaibs =)
Vou fechar a issue, mas se você ainda tiver algum problema relacionado a isso, só avisar que a gente reabre, ok? :D
