### ISSUE TITLE
Duvida sobre workflow-react

### ISSUE THREAD

**Issue by mauriciogirardi** [da2k/curso-reactjs-ninja#450]
@fdaciuk gostaria de saber sobre o workflow-react ele serve para desenvolver qualquer projeto ou apenas  se for um projeto robusto notei q ele é bem pesado  ou é impressão minha

**Comment by fdaciuk** [comment]
Oi @mauriciogirardi! A ideia de criar esse workflow era para ter uma base sólida para criar apps React. Mas hoje em dia eu recomendo você criar seus projetos com o Create React App, que já está bem sólido e sempre atualizado. Quando começamos o workflow-react, ainda não tínhamos o CRA, ou ele estava muito no início, mas hoje é melhor usar ele :)

**Comment by fdaciuk** [comment]
Oi @mauriciogirardi! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
