### ISSUE TITLE
M3#A52 busca do cep

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#451]
fala daciuk todo bem?
estou na aula M3#A52 e quando vou tentar fazer o request do CEP estou recebendo esse erro no console.
```
Access to XMLHttpRequest at 'http://apps.widenet.com.br/busca-cep/api/cep.json?code=78048148' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
VM197:1 GET http://apps.widenet.com.br/busca-cep/api/cep.json?code=78048148 net::ERR_FAILED

```
achei uma issue que você fala para fazer isso:
```
const response = await ajax({
  headers: { 'content-type': null }
}).get('http://apps.widenet....')
```
tentei mas ai já recebo esse outro erro aqui
```
VM81:1 GET https://apps.widenet.com.br/busca-cep/api/cep.json?code=78048148 500
```
poderia me ajudar porque achei outra API de cep porem não consigo fazer a mesma coisa que você fez nas aulas seguintes porque a responta é diferente, valeu

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! Essa API teve algumas pequenas alterações. Esse erro possivelmente é porque agora a API roda sobre HTTPS, e não aceita mais requests HTTP :)

A resposta no final também teve algumas alterações, mas foi apenas no nome das propriedades retornadas. Só dar um console.log na resposta que você vai ver :)

**Comment by angelilton** [comment]
valeu, eu usei o postman e o link com http funciona 😅😅

**Comment by fdaciuk** [comment]
Deve ser a regra de CORS da API, aí só afeta requests feitos via browser :)
