### ISSUE TITLE
M1#A28 Dúvida - Stateless e Statefull

### ISSUE THREAD

**Issue by deadlock** [da2k/curso-reactjs-ninja#452]
Bom dia!

Fiquei um pouco na dúvida sobre o final do vídeo, principalmente o último minuto onde são mencionados componentes stateless e statefull.

Algumas informações que são dadas no vídeo:

- Veremos porque devemos usar mais componentes stateless do que statefull

- Fica muito mais fácil pro react gerenciar quando um componente é statefull

- Fica muito mais fácil pro react fazer a diferenciação do dom virtual com componentes stateless do que em componentes statefull

No fim não consegui entender bem ao certo qual e quando devemos usar um ou outro, ou seja, os tradeoffs de cada um e se de fato o que foi dito é o real ou foi apenas uma troca de um termo por outro.

Obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @deadlock! Revendo aqui o vídeo, percebi que vou precisar dar uma pincelada melhor nessa parte de formulários, pra tentar deixar mais claro quando usar controlled e quando usar uncontrolled components. 

Mas só pra tentar responder sua pergunta: quando você cria um componente uncontrolled (onde o estado desse componente não é controlado pelo React), você vai precisar fazer validações, máscaras, etc., de forma manual: atrelando um evento ao elemento e manipulando DOM manualmente, pois o estado desse campo não está sendo controlado pelo React, e sim pelo browser.

Quando você cria um **controlled component**, o estado desse campo de formulário passa a ser controlado pelo React, e você não vai precisar se preocupar em manipular o campo de formulário em si, só precisa manipular o estado que controla aquele campo, que esse valor será refletido automaticamente no campo.

Bom, essa foi só a primeira aula falando sobre formulários. Vamos ver bastante sobre eles mais pra frente, e em breve eu devo adicionar mais algumas aulas falando mais a fundo sobre formulários também :)

De qualquer forma, sempre que tiver dúvidas, pode perguntar por aqui. Fico à disposição para ajudar no que for necessário :)

**Comment by fdaciuk** [comment]
> No fim não consegui entender bem ao certo qual e quando devemos usar um ou outro, ou seja, os tradeoffs de cada um e se de fato o que foi dito é o real ou foi apenas uma troca de um termo por outro.

Ah, e na segunda afirmação foi uma troca de termos mesmo. Vou corrigir :)
Obrigado por avisar!

**Comment by deadlock** [comment]
Perfeito, deu pra entender o conceito inicial e vou aguardar as próximas aulas pra pegar mais a fundo os casos de uso pra cada um.
Obrigado!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar :)
