### ISSUE TITLE
06  - Usando o sistema de módulos do ES62015

### ISSUE THREAD

**Issue by iamdiegoinacio** [da2k/curso-reactjs-ninja#454]
package.json
```
{
  "devDependencies": {
    "@babel/preset-react": "^7.9.4",
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    "create-react-class": "^15.6.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}
```

index.js
```
'use strict'

var React = require('react')
var ReactDOM = require('react-dom')


var Title = require('./app')

ReactDOM.render(
    React.createElement(Title),
    document.querySelector('[data-js="app"]')
)
```
app.js
```
'use strict'

var React = require('react')
var createReactClass = require('create-react-class');

var Title = createReactClass({
    render: function() {
        return React.createElement('h1', null, 'Título')
    }
})

module.exports = Title
```

.babelrc
```
{
    "presets": ["es2015", "stage-0"]
}
```

webpack.config.js
```
'use strict'

const path = require('path')

module.exports={
    entry: path.join(__dirname, 'src', 'index'),
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel-loader'
        }]
    }
 }
```

**Após eu ter instalado o babel, criado o ,babelrc e configurado o webpack.config.js o erro a baixo é mostrado, porém quando eu tiro o trecho de configuração do babel do webpack.config.js o erro some o bundle é gerado normalmente:**

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (C:\Users\MAQ06\Documents\projeto\react-webpack\node_modules\babel-loader\lib\index.js:103:36)

**ao retirar o trecho:**
```
module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel-loader'
        }]
    }
```
**O erro some, e o bundle é gerado normalmente.** 

Versões:
**webpack  v4.43.0**
**webpack-cli 3.3.11**
**node v 12.16.2**

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @iamdiegoinacio! Para conseguir acompanhar o curso sem erros, é preciso seguir as versões das dependências citadas
[nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md).

Seguindo esses passos, tudo vai funcionar conforme esperado :)

**Comment by iamdiegoinacio** [comment]
Apaguei tudo e instalei tudo novamente, mas o erro começa na instalação do babel 

in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (C:\Users\MAQ06\Documents\projeto\react-webpack\node_modules\babel-loader\lib\index.js:103:36)

webpack.config.js
```
'use strict'

const path = require('path')

module.exports = {
    entry: path.join(__dirname, 'src', 'index'),
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    module:{
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel-loader'
        }]
    }
}
```

**Comment by iamdiegoinacio** [comment]
Teve um relato desse mesmo problema nesse link :
https://github.com/babel/babel-loader/issues/666

Vou tentar atualizar o babel core e ver se resolve.

**Comment by iamdiegoinacio** [comment]
Atualizei o babel core executando npm install --save-dev babel-core, e continua a mesma coisa @fdaciuk

**Comment by fdaciuk** [comment]
@iamdiegoinacio essas não são as versões do 
[arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md).. lá estamos usando o webpack@1, e o babel@6.. instalando as versões exatamente como está nesse arquivo, você não vai ter esses erros :)

**Comment by iamdiegoinacio** [comment]
**Erro exibidos ao executar o comando npm install --save-deev webpack@1**

C:\Users\MAQ06\Documents\projeto\react-webpack>npm install --save-dev webpack@1
npm ERR! Unexpected end of JSON input while parsing near '...HnQQNtzejlAo/FJxZez\n'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MAQ06\AppData\Roaming\npm-cache\_logs\2020-04-25T17_15_52_560Z-debug.log

**Erro exibido ao executar o comando npm install -g webpack@1**

C:\Users\MAQ06\Documents\projeto\react-webpack>npm install -g webpack@1
npm ERR! Unexpected end of JSON input while parsing near '...HnQQNtzejlAo/FJxZez\n'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MAQ06\AppData\Roaming\npm-cache\_logs\2020-04-25T17_16_45_374Z-debug.log

**Comment by iamdiegoinacio** [comment]
+ babel-core@6.26.3
+ babel-preset-es2015@6.24.1
+ babel-preset-stage-0@6.24.1
+webpack 4.43.0

**Comment by fdaciuk** [comment]
Oi @iamdiegoinacio! Consegue instalar a versão 10 do Node.js e tentar novamente?

**Comment by iamdiegoinacio** [comment]
Minha versão do node atual é a v12.16.2, no caso eu iria desinstalar essa e instalar novamente a versão 10 correto?

**Comment by fdaciuk** [comment]
Pra ficar mais fácil, recomendo que você desinstale a versão atual, e instale o [NVM](https://github.com/nvm-sh/nvm). Com ele, você consegue manter várias versões diferentes do Node.js instaladas :)

**Comment by iamdiegoinacio** [comment]
Instalei o node 10, desinstalei tudo, instalei tudo novamente, mas:
1- webpack não aceita ser instalado com npm install --save-dev webpack@1, somente sem o @1

2- Mostra o mesmo erro ao gerar o bundle após instalar o babel:
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined

3- Caso eu tire o trecho a baixo:
```
module:{
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel-loader'
        }]
    }
```
O bundle é gerado normalmente.

**Comment by iamdiegoinacio** [comment]
Posso fazer o curso sem instalar o Babel? Estou desde ontem tentando instalar ele, mas não consigo.

**Comment by iamdiegoinacio** [comment]
Procurando eu acho que achei uma solução, o que você @fdaciuk  me diz da solução: **Create React App**
link: https://pt-br.reactjs.org/docs/create-a-new-react-app.html

**Comment by fdaciuk** [comment]
Com certeza! Só pular as partes de configuração que você consegue seguir tranquilamente com o CRA :)

Se estiver com dificuldades por conta da diferença de implementação de algumas coisas mostradas nos primeiros módulos do curso, só usar a versão do React usada no curso junto com o CRA que você não vai ter problemas :)

**Comment by fdaciuk** [comment]
Oi @iamdiegoinacio! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
