### ISSUE TITLE
M2#A02 - Conhecendo o create-react-app

### ISSUE THREAD

**Issue by jefferson-cruz** [da2k/curso-reactjs-ninja#455]
Instalei o create-react-app, porém ao executar o npm start é lançado um erro informando que a versão que eu tenho do webpack é antiga e que está sendo pedido a versão mais nova 4.42.0.
Estou tentando atualizar a versão do webpack com o comando npm i -g webpack@4.42.0, mas não atualiza.

Como atualizar esse pacote?

Se eu atualizar pode atrapalhar as próximas aulas?

`There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.42.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  C:\Users\jefferson.cruz\node_modules\webpack (version: 1.15.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.        
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.       

  6. Check if C:\Users\jefferson.cruz\node_modules\webpack is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls webpack in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed webpack.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cra@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cra@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jefferson-cruz! Para usar o Create React App, pode desinstalar o webpack global. Também não vai precisar do CRA instalado globalmente, pode usar o `npx` pra fazer a criação do novo projeto, dessa forma:

```
npx create-react-app seu-projeto
```

Nesse módulo eu vou mostrar bastantes coisas de configuração. Se você quiser seguir com o CRA, só pular essas aulas e tudo certo, ok? :)

:)

**Comment by fdaciuk** [comment]
Oi @jefferson-cruz! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
