### ISSUE TITLE
M1#A44 - Requisições com bloqueio de CORS

### ISSUE THREAD

**Issue by rafael-marques** [da2k/curso-reactjs-ninja#456]
Tentei fazer via fetch pegando dados de uma API que construi para teste e ambas estão em localhost mas em portas diferentes. 

Está retornando erro de CORS blocked. Como posso resolver isso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafael-marques! Portas diferentes são origens diferentes, então você vai precisar configurar os headers de CORS na sua API, dizendo quais domínios estão permitidos fazer requests nela :)

[Nesse link](https://enable-cors.org/server.html) você consegue ver como fazer a implementação, dependendo da linguagem que você está usando no backend :)

**Comment by rafael-marques** [comment]
Na mosca @fdaciuk resolvido. Obrigado.

Eu estou usando Lumen do Laravel e foi necess'ario apenas adicionar um middleware pra liberar o acesso. Não sei se essa issue ficará disponível para outros alunos mas caso fique,  segue o workaround 

[Aqui](https://www.codementor.io/@chiemelachinedum/steps-to-enable-cors-on-a-lumen-api-backend-e5a0s1ecx)

**Comment by fdaciuk** [comment]
Legal, que bom que deu certo :)
A issue fica fechada, mas disponível a quem quiser acessar :)
