### ISSUE TITLE
M2#A30

### ISSUE THREAD

**Issue by jefferson-cruz** [da2k/curso-reactjs-ninja#457]
Eu criei uma nova aplicação com o create-react-app e instalei o storybook. Mas está dando esse erro:

Installing dependencies. ✖

     An error occurred while installing dependencies.

Segue meu package.json
`{
  "name": "workflow-reactjs",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@storybook/cli": "^5.3.18",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0"
  }
}
`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jefferson-cruz! Para usar o storybook com o CRA, é importante seguir esse tutorial aqui, direto da documentação:
https://storybook.js.org/docs/guides/guide-react/

Se você já fez isso, então só faltou instalar as dependências. Nesse caso, você só precisar rodar `npm install` (ou `yarn`, se estiver usando Yarn), no diretório do seu projeto para que as dependências sejam corretamente instaladas :)

**Comment by fdaciuk** [comment]
Oi @jefferson-cruz! Vou fechar a issue, mas se você ainda tiver dúvidas, só avisar que eu vou te ajudando, ok? :)
