### ISSUE TITLE
M2#A29 - Lançamento de exceções

### ISSUE THREAD

**Issue by willianribeiro** [da2k/curso-reactjs-ninja#46]
Fala, @fdaciuk ! Eu aqui de novo :smile: 

Nesta aula você mostra como tratar exceções caso o usuário passe parâmetros diferente do esperado (na implementação imperativa).

Eu adicionei o tratamento na implementação recursiva, porém não consegui substituir os if's por ternário de modo que o código continuasse legível haha.

Qual seria a solução mais elegante pra esse caso?

```
'use strict'

const map = (arr = [], func = (item) => item) => {
    /* --- Aqui --- */
    if (!Array.isArray(arr))
        throw new TypeError('First parameter must be an array');

    /* --- E aqui --- */
    if (typeof func !== 'function')
        throw new TypeError('Second parameter must be a function');

    const counter = 0;

    return (function mapInternal (arrInternal, counter) {
        const [head, ...tail] = arrInternal;

        return arrInternal.length === 0 ? [] : [
            func(head, counter, arr),
            ...mapInternal(tail, counter + 1)
        ];
    })(arr, counter);
}

export default map;

```

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @willianribeiro! Então, o `throw` vai disparar um erro sempre que usado. Ele não retorna valor, então você não consegue usar ele com um ternário. Nesse caso é necessário o `if`.

Para tentar remover blocos de código, e deixar ele mais _funcional_, o que você poderia fazer é não disparar um erro (que só pode ser capturado com `try/catch`), mas sim retornar um `Error` ou `TypeError`, ou ainda retornar um array vazio, como o método `map` do objeto Array faz =)

**Comment by willianribeiro** [comment]
Eita, li e reli, mas não sei se entendi haha

Primeira coisa que fiquei confuso foi em relação ao retorno do Array.prototype.map. Pelo teste que fiz aqui ele retorna um erro se eu não passo a função [1] ou se eu passo outra coisa que não seja uma função [2] e não um array vazio .-.

Seguindo sua sugestão quem retornaria este erro seria o próprio map? E o que retornaria o `areAllArgumentsOk` para o map, um booleano ?



[1]
![image](https://user-images.githubusercontent.com/3102551/29799413-d0e5e582-8c39-11e7-869a-d21011d04b2f.png)

[2]
![image](https://user-images.githubusercontent.com/3102551/29799424-e722f0f6-8c39-11e7-886e-98eb607d5682.png)

**Comment by fdaciuk** [comment]
haha! Beleza, vou tentar explicar melhor =)

Como você está fazendo sua própria implementação do `map`, você é quem decide o que vai retornar :)

Mas como você está tentando manter o mesmo padrão do `map` de array, então tem que ter em mente algumas coisas:

- O `map` só existe para objetos do tipo `Array`, por isso ele só valida a função, se ela não for passada;
- Ele dispara um TypeError se uma função não for passada. Se você quiser fazer isso na sua implementação, você vai precisar de um `if` de qualquer forma, e precisa remover também a função que passamos como `default parameter`;
- Se quiser tentar manter algo 100% funcional, e não usar o `if`, não vai rolar dar `throw` para disparar um erro. Nesse caso, você pode definir outro tipo de retorno: 
  - ou um objeto de erro - usando `new TypeError`, mas retornando esse objeto, sem dar `throw`
  - ou assumir que o primeiro parâmetro vai sempre ser um array vazio se outra coisa for passada e a função, independente do que for passado, vai assumir que é uma função que só retorna o array.

Essas definições de como a função vai funcionar é você quem decide, entendeu? =)

Mas, se quiser manter o mesmo padrão do `map`, disparando um erro, vai ter que usar o `if` mesmo pra checar o tipo do valor passado =)

**Comment by willianribeiro** [comment]
Putz véi, entendi tudo agora, valeu demais!! <3

**Comment by fdaciuk** [comment]
Show \o/
Qualquer coisa grita ae :D
