### ISSUE TITLE
Uso do forceUptate e de PureComponent

### ISSUE THREAD

**Issue by mjfneto** [da2k/curso-reactjs-ninja#462]
Eu não conhecia o método `forceUpdate()`. Li um pouco sobre ele na documentação do React, e parece que ele deveria ser [evitado](https://reactjs.org/docs/react-component.html#forceupdate):

> Normally you should try to avoid all uses of forceUpdate() and only read from this.props and this.state in render().

Por que você o usa na aula `m03/samples/06-react-counter`? Ele tem alguma ligação com o fato de estar num [`PureComponent`](https://reactjs.org/docs/react-api.html#reactpurecomponent), já que ambos "saltam" o método `shouldComponentUpdate`? Acho que minha dúvida é: por que usar o `forceUpdate` se um `PureComponent`, por si mesmo, não implementa `shouldComponentUpdate`?

Imagino que seja porque estamos usando Redux para gerenciar o estado da aplicação, o que é um caso de dados vindos da ferramenta (uma fonte externa ao React, talvez). Pois a [documentação](https://reactjs.org/docs/react-api.html#reactpurecomponent) diz:

> Only extend PureComponent when you expect to have simple props and state, or use forceUpdate() when you know **deep data structures** [Redux?] have changed.

E

> If your render() method depends on **some other data** [Redux?], you can tell React that the component needs re-rendering by calling forceUpdate().

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mjfneto! Você mesmo já respondeu a sua dúvida :)
Mas vamos lá, vou detalhar alguns pontos importantes:

**Usar ou não o `forceUpdate`?**

Sim, esse método deve ser evitado sempre que possível. O React já possui uma forma própria de lidar com estados, então o ideal é sempre usar esse formato para lidar com dados.

Mas o React é apenas uma biblioteca, e não vai cobrir 100% dos casos para a criação de qualquer projeto. Muitas vezes precisaremos usar bibliotecas externas, que manipulam dados de forma diferente da que o React faz.

E o React se adapta muito bem a isso, nos oferecendo os métodos de lifecycle dos componentes e o método `forceUpdate`, para que possamos lidar com essas bibliotecas externas. 

Então a recomendação é: não seu o `forceUpdate`, a menos que você esteja usando qualquer lib externa que tenha uma manipulação própria de dados, onde você precise renderizar esses dados, e não consiga atualizar um componente com o `setState` padrão do React :)

**Sobre o PureComponent**

Nós usamos esse componente para extender os nossos próprios, pois ele já tem uma implementação própria do `shouldComponentUpdate`, diferente do `Component` padrão do React, que, sempre que você disparar um `setState`, independente se algum valor do estado mudou ou não, ele vai disparar novamente o método `render`.

---

E ainda tem mais um ponto importante: no caso do Redux, nós não precisamos usar manualmente o `forceUpdate`, pois já existe uma outra biblioteca que integra o redux com o React. Provavelmente você ainda não chegou nessa aula.

Mas o meu objetivo com essa aula, mostrando o `forceUpdate`, foi realmente mostrar que o React trabalha tranquilamente com qualquer tipo de biblioteca externa, e você pode usar isso sempre que for necessário :)

Ficou claro? :)

**Comment by mjfneto** [comment]
Claro! Obrigado. E eu assisti o módulo seguinte (07), onde você diz que o método `connect` permite essa integração sem o `forceUpdate`. Realmente, ficou mais fácil de compreender.

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, fique à vontade para perguntar :)
