### ISSUE TITLE
Modulo 2 - markdown editor - gerar build

### ISSUE THREAD

**Issue by RuiRocha1991** [da2k/curso-reactjs-ninja#465]
Boa tarde,
Estou a seguir as aulas do modulo 2 e já acabei. mas agora no fim ao gerar a build esta a dar alguns erros, ja estive a pesquisar e nao consigo encontrar uma soluçao.
Será que me pode ajudar?

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/29250466/81613810-fde2b900-93d6-11ea-9506-eef67f2c518b.png">

Estou a ter os seguintes erros, mas ja tinha conseguido gerar build sem dar os erros.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @RuiRocha1991! Consegue subir seu código em um repositório aqui no GitHub?
Compartilha aqui comigo o seu repo que eu dou uma olhada no que pode estar acontecendo, ok? :)

**Comment by RuiRocha1991** [comment]
Boas, @fdaciuk. 
Sim claro que partilho todo o codigo.
[https://github.com/RuiRocha1991/markdown-editor](markdown-editor)

Obrigado

**Comment by fdaciuk** [comment]
Oi @RuiRocha1991! Eu baixei o projeto aqui e teste, realmente ele dá esses erros. Ainda não descobri de fato o que acontece, preciso investigar mais, mas o build é gerado corretamente. Se você olhar no diretório `dist`, os arquivos estarão lá :)

O problema só acontece ao tentar minificar, mas não vai afetar sua aplicação :)

**Comment by RuiRocha1991** [comment]
Boas, @fdaciuk.
Estive a testar e nao estava a encontrar erros que pode-se dificultar a utilizaçao da App. contudo se der para nao ter os erros presentes era melhor.

Muito obrigado, o curso está-me ajudar bastante 😄

**Comment by fdaciuk** [comment]
Em breve eu devo fazer a atualização dos primeiros módulos do curso, onde vamos começar já com o Create React App. Aí vai ficar mais simples de usar, já que ele já vem preparado para gerar a versão de produção :)

Mas qualquer dúvida que tiver, fique à vontade para perguntar :)
