### ISSUE TITLE
[Dúvida] React Redux

### ISSUE THREAD

**Issue by ebraimcarvalho** [da2k/curso-reactjs-ninja#466]
Fala Daciuk, beleza? A princípio entendi a teoria do Redux, mas na prática eu fiquei travado ainda, pesquisei outras fontes e outras formas de explicação pra alinhar com o que vi no curso e quero tirar umas dúvidas contigo se é isso mesmo que eu entendi, pode ser?

A princípio o Redux precisa de dois carinhas principais: O Actions.js e o Reducer.js, mas é bom usar um terceiro actionTypes.js pra centralizar os nomes das variáveis em um arquivo só e pra evitar erros com string e se precisar adicionar ou remover algo, tá tudo concentrado num arquivo só.

No arquivo actionTypes.js basicamente exportamos os nomes de todas as constantes que usaremos para disparar uma ação, tipo:
ex:
```
export const ADD_TODO = 'todos:ADD_TODO'
export const TOGGLE_TODO = 'todos:TOGGLE_TODO'
```

O segundo arquivo seria o actions.js (ou action-creators.js, como no exemplo do Todo list) em si, onde estariam as pure functions que usariamos para disparar as ações na aplicação
ex:
```
export const addTodo = (text) => ({
  type: ADD_TODO,
  payload: {
    id: v4() // cria um id único usando uma lib de terceiro,
    text
  }
})
```

O terceiro arquivo é o Reducer em si, onde estaria a manipulação da ação passada pelo dispatch e retorna o estado atualizado de acordo com a ação passada
ex:
```
const todos = (state = initialState, action) => {
  switch (action.type) {
    case ADD_TODO:
      return state.concat({
        id: action.payload.id,
        text: action.payload.text,
        completed: false
      })
}
```
Pronto, essa parte eu acho que entendi bem, o negócio pegou pra mim pra entender como conecta o store na aplicação e como passa as ações pro reducer trabalhar. O que entendi foi assim:

1. Na porta de entrada da aplicação, na index.js, importamos o createStore e o Provider do redux e do react-redux, e importamos nosso reducer;

2. Definimos nosso store como constante e passamos nosso reducer como parametro do createStore: ```const store = createStore(reducer);```

3. Envolvemos nossa aplicação com o Provider passando nosso store criado acima como propriedade store: ```<Provider store={store}>...aplicação</Provider>```

4. Nosso trabalho na index ta finalizado, partimos para o App.js e importamos o connect do react-redux e nossas actions;

5. Bom, aqui começa a parte onde to precisando entender mais... Definimos a função mapStateToProps, para ter acesso ao state chamando-o nas props do nosso app.js
**Minha dúvida nesse ponto: o parametro state dessa função vem do provider?**

```
const mapStateToProps = (state) => ({
  todos: state
})
```

6. Definimos a função mapDispatchToProps para ter acesso às actions nas props do elemento app.js.
**Outra vez, o dispatch passado no parametro da função vem do provider store={store} também?**

```
const mapDispatchToProps = (dispatch) => ({
  handleAddTodo: (e) => {
    e.preventDefault()
    dispatch(addTodo(e.target.todo.value))
    e.target.todo.value = ''
  }
})
```

7. Conectamos essa parada toda ao App, usando o:
```export default connect(mapStateToProps, mapDispatchToProps)(App)```

8. Passamos essas propriedades para nosso elemento App.js:
```const App = ({ todos, handleAddTodo, handleToggleTodo }) => (...```

9. Podemos agora gerenciar o estado disparando ações nos elementos do nosso elemento, usando simplesmente assim:
```
<form onSubmit={handleAddTodo}>
// or
onClick={handleToggleTodo(todo.id)...
```

Pronto, é nessa linha mesmo que estou pensando? Escrever isso tudo de forma estruturada foi bom pra mim também para fixar ainda mais esses conceitos.
Forte abraço!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @ebraimcarvalho! Perfeito meu caro, entendi onde está a sua dúvida. Vamos lá :)

Só antes de responder a sua dúvida, vou comentar alguns pontos importantes sobre o que você colocou:

Para o uso do redux (puro, sem React ou qualquer outro framework), você só precisa de duas coisas: a store (criada com o createStore) e o reducer. Os arquivos `actionTypes.js` e `actions.js` são completamente opcionais, e servem especificamente como abstração. Só com a store e, no mínimo, um reducer, você já coloca o redux pra funcionar :)

Pelo que entendi, a sua dúvida é em como o Redux se conecta ao React, certo? De onde vem as informações, como é que o react-redux funciona, e como eles se conversam, não é isso? :)

Bom, lembra que, no final do módulo 2, eu falei sobre a Context API? Que com ela nós conseguimos passar informações de estado para nossos componentes em qualquer parte da árvore de componentes, sem precisar ficar passando via props? É exatamente assim que o react-redux faz para conectar o Redux ao React!

Quando você envolve toda a sua aplicação usando o `Provider` do react-redux, ali está toda a configuração de estado que vai ser repassada para os componentes que usarem a função `connect`.

Basicamente, o componente `Provider` recebe uma prop `store`, que é a `store` do redux. Nesse objeto, nós temos acesso aos 3 métodos necessários para lidar com os dados vindos do Redux: `getState`, `dispatch` e `subscribe`, certo?

Então o `Provider` simplesmente "mapeia" esse objeto da store para ser repassado via Context API para a função `connect`, também do react-redux.

A função `connect` funciona da seguinte maneira: Ela é uma função que pode ser usada sem passar nenhum argumento, e então ela vai retornar uma segunda função, esperando que um componente seja passado pra ela.

Essa segunda função do `connect` retorna ao final, um novo componente. Esse novo componente vai ser uma extensão do seu componente, que você passou para a função connect, só que com as props do Redux injetadas.

Mais ou menos algo assim:
https://github.com/fdaciuk/talks/blob/master/2017/meetup-react-sp/context-api/context-api/src/context10/connect.js

Esse link acima é de um arquivo de uma palestra onde eu falei sobre a Context API, basicamente reescrevendo o react-redux na mão, pra mostrar como ele funciona na prática :)

Se você olhar esse código já deve sacar como a função `connect` funciona :)

Então, respondendo à sua pergunta:

> Minha dúvida nesse ponto: o parametro state dessa função vem do provider?

Sim, o `state` vem do Provider, que recebeu via props a store do Redux, e repassou via Context API. Na função `connect`, via Context API nós temos acesso à store, e lá podemos pegar o state para ser repassado para a função `mapStateToProps` :)

> Outra vez, o dispatch passado no parametro da função vem do provider store={store} também?

Mesma ideia para o `dispatch` :)

No final das contas, você já tinha entendido! Só quis mostrar com um pouco mais de código como as coisas podem funcionar por baixo dos panos :)

Qualquer dúvida, fique à vontade para perguntar :)

**Comment by ebraimcarvalho** [comment]
Tranquilo @fdaciuk . Grato pela atenção e disposição em esclarecer! Valeu mesmo!
Forte abraço!
