### ISSUE TITLE
duvida de começar um projeto do zero

### ISSUE THREAD

**Issue by mauriciogirardi** [da2k/curso-reactjs-ninja#467]
Tenho uma duvida mais como dev não sobre seu curso como você escolhe as tecnologia para começar um projeto  tive quero fazer um  sistema delivery  web   integrado com mobile , blz  quero implementar oq estou aprendendo no curso  quero  fazer  o front-end  com react js  Mobile react native e back-end node js  essa é a base q quero mais  ai vem a duvida qual bando de dado usar   o front uso gatsby next ou react só  
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mauriciogirardi! Legal que você já tem uma stack base, isso facilita bastante as coisas :)

Banco de dados vai depender de como você vai usar os seus dados: se precisar de relacionamentos, vai precisar de um banco SQL, aí eu recomendaria o Postgres ou o MariaDB. 

Se precisar de um banco não relacional, aí tem várias opções: Mongo para lidar com documentos, Redis para lidar com chave / valor, etc. Vale a pena gastar um tempo pesquisando sobre alguns bancos, com base na sua necessidade, para ver o que melhor se encaixa pra você :)

Sobre usar no frontend, eu costumo seguir o seguinte:
- Preciso de SEO e meu app vai ter rotas? Gatsby
- Posso usar só uma página para SEO, ou não preciso de SEO? Create React App.

Basicamente isso :)

Espero ter dado uma luz :)

**Comment by fdaciuk** [comment]
Oi @mauriciogirardi! Vou fechar a issue, mas se você tiver qualquer problema, só avisar, ok? :)
