### ISSUE TITLE
Configuração do Ambiente

### ISSUE THREAD

**Issue by ADILSON-SEABRA** [da2k/curso-reactjs-ninja#468]
Boa tarde !
Sou desenvolvedor, com Base Windows, não conheço nada Linux, preciso de ajuda, pois não tenho ideia de como configurar o abiente para o curso, no Windows 10 - 64bits

@fdaciuk

**Comment by fdaciuk** [comment]
Oi Adilson, tudo bem? :)

No windows, recomendo você usar o WSL, que é um subsistema Linux dentro do windows. Instalando o WSL, você consegue executar os comandos exatamente da forma que eu faço no curso :)

Se não souber como instalar o WSL, esse curso aqui vai te ajudar:
https://www.youtube.com/watch?v=YcR8pKvjx44&list=PLlAbYrWSYTiOpefWtd6uvwgKT1R-94Zfd

**Comment by fdaciuk** [comment]
Oi @ADILSON-SEABRA! Vou fechar a issue, mas se você tiver qualquer problema, só avisar, ok? :)
