### ISSUE TITLE
Vídeo do Futuro sobre mudanças de versões do React

### ISSUE THREAD

**Issue by Riverfount** [da2k/curso-reactjs-ninja#469]
Estou acompanhando o curso e gostando bastante. Sou desenvolvedor Python e estou aprendendo React para ter um pouco de noção do que acontece no Front das aplicações.

Mas, encontrei algumas dificuldades que foram difíceis de sanar e na verdade tudo se resumia na versão do React usado pelo CDN. Nas aulas vc usa a versão 15.1.0, mas salienta de usarmos a versão mais recente. A versão mais recente nas CDN's é a 16.13.1 e confesso que foi difícil fazer rodar o código dos primeiros vídeos nessa versão. Difícil não, foi impossível. Eu tive que usar as versões que vc usa nos vídeois e aí sim tudo rodou de boa.

Na sequência, ao entrar no módulo de React + WebPack me deparo com um conceito de metodologia de aula interessante: as aulas do futuro! Assim, minha pergunta é: Por que não utilizar esse conceito de Aula do Futuro para apresentar, rapidamente, as mudanças que estão ocorrenco na mudança de versões do próprio React e não só das dependências. Digo isso por que, se entendi bem, no React 16.13.1 a funçaõ `React.createClass` está depreciada e em seu lugar deve-se utilizar o `createReactClass`, assim pq não fazer um vídeo falando disso. O que pouparia bastante tempo nosso, pois fiquei investigando o porquê de estar tomando o erro `React.createClass is not a function`. Enfim, fica aqui a sugestão!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Riverfount! Realmente faltou orientação nessas primeiras aulas, vou adicionar isso com certeza, muito obrigado por avisar :)

E em breve eu devo atualizar esse módulo de forma total, para contemplar a versão mais recente do React, que veio com algumas features bem interessantes :)

Por hora, vou adicionar a aula do futuro falando sobre a versão usada no CDN, ma sempre que tiver dificuldade com algo, fique à vontade para perguntar. Estou à disposição para ajudar :)
