### ISSUE TITLE
MRW#05 - React.createClass is deprecated

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#47]
Professor ao fazer essa aula eu me deparo com um warning dizendo que createClass do React, vai ser decrepitado a partir da versão 16, posso continuar o curso normalmente ? nas próximas aulas vai ser atualizado essa questão ou não devo me preocupar com isso ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi João! Não precisa se preocupar não, pode seguir =)
Quando essas aulas foram gravadas, o React estava na versão `15.4` e não dava esse _warning_.

Então se quiser instalar ele, só rodar:

```console
npm install --save react@15.4
```

Dessa forma você instala a versão específica que estamos usando :D 

Mas pode ficar tranquilo que, durante o curso, nós vamos atualizando as versões de libs e das ferramentas que estamos utilizando :D 

Provavelmente você pode ter problemas com outras dependências durante as próximas aulas. Se isso acontecer, pode abrir issue que eu vou te ajudando a resolver, vai ser só essas questões de versão =)

Vou preparar um vídeo no início de cada aula onde tem instalação de pacotes mostrando as versões específicas que estamos usando, assim vai ficar mais fácil se achar :D 

Mas qualquer dúvida que você tenha, ou qualquer problema que der em qualquer momento da aula, pode reportar aqui que eu vou te ajudando, ok? :D

**Comment by CheeseFlan** [comment]
Vlw professor :D

**Comment by fdaciuk** [comment]
\o/

Qualquer coisa só avisar =)
