### ISSUE TITLE
continuidade do curso

### ISSUE THREAD

**Issue by guilhermeci** [da2k/curso-reactjs-ninja#471]
Opa, tudo bem @fdaciuk ?

prof. conclui o curso no Udemy(finalmente!!!)... mas me deu a impressão que o curso tá em continuidade... fiquei na dúvida se finalizou na aula 474, se existe outro curso de complemento, se em outra plataforma, vai ser atualizado? a periodicidade e tal.

Mais uma vez parabéns pelo trabalho e vamos... agora pro javascript ninja!!

Abraço

**Comment by fdaciuk** [comment]
Oi @guilhermeci! Parabéns por chegar até aqui \o/

O curso está em andamento sim :)

Estou liberando algumas aulas por semana, para finalizarmos a aplicação de cadastro de pizzas! Quando chegar na última aula, eu vou fazer um encerramento do módulo em vídeo, pode ficar tranquilo :)

Bons estudos, e conte comigo para o que precisar! :D
