### ISSUE TITLE
MRW#08

### ISSUE THREAD

**Issue by marcosnovaesq** [da2k/curso-reactjs-ninja#472]
boa noite @fdaciuk , ao fazer todas as configuraçoes necessarias para usar o hot loader, e dar o comando npm start, ele faz tudo certinho, printa no terminal o 'Listening on http://localhost:3000', porem no navegador, ao acessar esse endereço localhost:3000 ele aparece apenas a mensagem "Cannot GET /"
nao funciona tambem se for http://localhost:3000/src
procurei na internet mas nao achei soluçao
no console do navegador aparece Failed to load resource: the server responded with a status of 404 (Not Found)
porem, se eu no terminal iniciar o servidor apenas com webpack-dev-server diretamente sem usar as configuraçoes do server.js, ele funciona certinho. Não consigo entender muito bem por que esta acontecendo isso

**Comment by fdaciuk** [comment]
Oi @marcosnovaesq! O `src` não é acessível publicamente. Dá uma olhada se você colocou o arquivo index.html na raiz do seu projeto (no mesmo lugar onde você roda o comando para subir o servidor). Normalmente é esse o problema :)

**Comment by marcosnovaesq** [comment]
@fdaciuk  o arquivo index.html tem que estar na raiz que voce diz a pasta src? ou um antes dessa pasta onde tao os arquivos de configuraçao? Ou roda o comando dentro da pasta src?

**Comment by marcosnovaesq** [comment]
@fdaciuk consegui, tive que tirar o index.html da pasta src, achei q era pra estar la,

**Comment by fdaciuk** [comment]
Isso mesmo @marcosnovaesq: a index.html precisa estar antes da `src` :)
Qualquer dúvida em relação à estrutura de arquivos, você pode dar uma olhada aqui no repositório mesmo: no diretório [`examples`](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples) tem os diretórios de cada módulo.

Para esse módulo de React + webpack, tem um diretório [`react-webpack`](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack), com os códigos usados em cada aula separados por diretórios, para você consultar a ordem dos arquivos e as versões das dependências que foram usadas em cada aula, e comparar com o seu código, pra ver se o seu está certo :)
