### ISSUE TITLE
M4#A38 ErrorBoundary

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#473]
fala daciuk tenho uma duvida sobre essa aula na versão mais nova do creact-react-app ele já vem envolvido em um compoment no caso eu teria que colocar o ErrorBoundary junto ou talvez esse novo componente ja faça isso? 
```
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! Pode colocar abaixo do `React.StrictMode` :)
