### ISSUE TITLE
M2 #86 Dynamic Import

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#474]
Olá, mestre @fdaciuk 

Sobre "dynamic import", assisti diversas vezes a aula tentando identificar por que fala-se que o valor é carregado dinamicamente. Achei a aula toda muito interessante, a forma diferente de se carregar o componente importado. Mas, na prática, não vi nenhuma vantagem em relação a um valor passado via props, em um componente importado de forma estática. O import estático também carregaria a informação passada via props, aparentemente sem nenhuma desvantagem.

Mas sei que devo estar enganado, então queria te pedir essa luz para enxergar algum caso onde os diferenciais estejam mais evidentes.

Grande abraço e obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae @pamplonapaulo! Ótima questão, vamos lá:

eu vejo pelo menos dois pontos positivos no uso do import dinâmico:
1. A dependência só é "baixada" quando solicitada;
2. Para dependências muito grandes, sua aplicação não fica travada até que a dependência fique disponível.

O ponto 1 eu mostrei nessa aula: ao usar o import dinâmico junto com o webpack, esse arquivo que foi importado com o `import()` vai ser separado do bundle final.

Dessa forma, se no primeiro carregamento da nossa aplicação esse arquivo não for chamado, ele também não vai ser baixado pelo usuário, ou seja: menos bytes pra baixar, menos banda da internet do usuário vai ser gasta (pense em um acesso via 3g, por exemplo), e também a aplicação vai carregar mais rápido, pois tem menos dependências pra carregar.

Já o ponto 2 eu vou mostrar mais pra frente. Você vai ver no curso como criar um editor de markdown, e lá vamos usar uma lib bem grande que faz a transformação do markdown para HTML, para ser renderizado em tela.

Nesse caso, se importarmos a lib estaticamente (com o `import` padrão), essa lib vai fazer parte do bundle final, e será carregada junto com todo o resto da aplicação. Como a lib é bem grande, vai demorar alguns segundos para que as informações apareçam na tela.

Importando essa lib dinamicamente, nós podemos carregar a aplicação primeiro, e essa lib vai sendo baixada em segundo plano, não afetando o carregamento padrão da aplicação :)

Acredito que vai ficar mais claro quando chegar nessa aplicação, mas se ainda tiver dúvidas, só dizer que eu tento explicar melhor :)

**Comment by pamplonapaulo** [comment]
Maravilha, mestre @fdaciuk ! Claro como água mineral! rs

Na carona desse assunto, surgem duas perguntas:

1) Um app via CRA também respeita esses mesmos critérios, isto é, o import dinâmico também ficará separado do bundle final?

2) Fiquei na dúvida se chamar de bundle ou de chunk. Cada chunk é um bundle separado, né? O CRA faz tudo isso sozinho por padrão sem precisarmos configurar o webpack?

Muito grato!

**Comment by fdaciuk** [comment]
Opa! Sim, o CRA também funciona da mesma forma, pois por baixo dos panos, é o webpack que cuida de tudo. Então pode usar import dinâmico também no CRA sem problemas :)

Chunk, na tradução literal, seria "pedaço". Então o chunk basicamente é um "pedaço" separado do bundle (pacote) final :)

E sim: o CRA já está configurado pra funcionar dessa forma: só usar o `import()` função que o arquivo vai ser separado do bundle final :)
