### ISSUE TITLE
M1#A17

### ISSUE THREAD

**Issue by jrosetim** [da2k/curso-reactjs-ninja#475]
<!--
DICA: Se você precisar adicionar trechos de código, coloque-os entre 3 crases,
assim:

```
function blabla () {
}


Colocando 3 crases antes, 3 crases depois, o código aparecerá corretamente
formatado.

Lembre-se também de, antes de publicar a Issue, clicar na aba "Preview", para
visualizar se a formatação está correta :)
-->

<!-- Escreva aqui sua dúvida após essa linha -->


<!-- Não apague daqui pra baixo! -->
Boa tarde @fdaciuk, blz?

Nessa video aula M1#A17 você utiliza o children da seguinte forma 
```
import React from 'react'

const Button = ({children}) => (
    <button> {children} </button> 
)

export default Button
```

Mas eu só estou conseguindo utilizar assim,
é alguma atualização do React por acaso?

```
import React from 'react'

const Button = ({children}) => (
    <button> {`${children}`} </button> 
)

export default Button
```

essa é o outro componente, onde uso o Button como pai

```
import React from 'react'
import Button from './button'

const ButtonLike = () => (
    <Button> Like </Button>
)

export default ButtonLike
```

**Comment by fdaciuk** [comment]
Oi @jrosetim! Usar somente as chaves dentro do JSX é para fazer a interpolação para JS. Então qualquer código JS será válido ali dentro. Da forma que você fez, você simplesmente parseou o `children` para string antes de renderizar. Se o seu `children` for sempre uma string, você não terá problemas.

Agora, se o seu `children` for uma outra tag JSX, você vai ver `[object Object]` ao invés do resultado correto.

O certo é fazer como eu fiz. Se por algum motivo o código que eu passei não estiver funcionando, então é preciso dar uma olhada no seu código todo, para entender o que pode estar acontecendo. 

Consegue subir seu código todo em um repositório aqui no GitHub pra eu dar uma olhada? :)

**Comment by jrosetim** [comment]
@fdaciuk , o código esta nesse repositório 

https://github.com/jrosetim/curso-reactjs

conforme vou fazendo o curso ja vou sincronizando aqui :D

**Comment by fdaciuk** [comment]
Legal! Provavelmente era algum erro de digitação.. 95% dos casos é isso :)
Que bom que deu certo! Qualquer coisa, só avisar :)
