### ISSUE TITLE
M2#A10

### ISSUE THREAD

**Issue by jrosetim** [da2k/curso-reactjs-ninja#476]
@fdaciuk

Boa noite Fernado, estou na aula M2#A10 , queria saber se tem como pular esse conteúdo de TDD sem perder nenhum conteúdo do REACTJS, porque para mim o interessante agora seria o react, mas tem muitas aulas de TDD la.

**Comment by fdaciuk** [comment]
Oi @jrosetim! Claro, pode pular sim :)

**Comment by jrosetim** [comment]
@fdaciuk para qual eu posso pular sem perder o conteúdo do react?

**Comment by fdaciuk** [comment]
Pode seguir à partir da aula `M2#A30` :)

**Comment by fdaciuk** [comment]
Oi @jrosetim! Vou fechar a issue, mas se você tiver qualquer problema, só avisar, ok? :)
