### ISSUE TITLE
M3#A24 - Erro: Definition for rule 'standard/no-callback-literal'

### ISSUE THREAD

**Issue by kadoshmt** [da2k/curso-reactjs-ninja#477]
![screenshot](https://user-images.githubusercontent.com/989544/83359666-b69e7700-a349-11ea-84b8-3a4ea2d0b004.png)
<!--
Ao baixar o exemplo m3/13-todo-list e rodar a aplicação, fica aparecendo alguns erros no console "standard/no-callback-literal" (conforme imagem). Não sei como desativar estes warnings, que acredito que aumentarão conforme novos arquivos .js forem criados.
@fdaciuk

**Comment by kadoshmt** [comment]
Como retirar esses warnings de standard/no-callback-literal?

**Comment by fdaciuk** [comment]
Oi @kadoshmt! Consegue me mostrar o conteúdo dos arquivos que o linter tá apontando os erros? Os arquivos são:
- `src/app.js`
- `src/index.js`

Ou tenta instalar a versão mais recente do standard, que parece que eles removeram essa regra :)

---

Obs.: Não esqueça de me marcar quando abrir uma issue (com `@fdaciuk`), senão eu não recebo notificação da sua dúvida :)

**Comment by kadoshmt** [comment]
Oi @fdaciuk 
Nas versões posteriores estes erros sumiram. Acredito que ao ter rodado pelo terminal do linux com o Node  v10, eles sumiram.

**Comment by fdaciuk** [comment]
Perfeito! A cada versão algumas atualizações são feitas, conforme o time da biblioteca vai percebendo que algumas coisas fazem sentido, outras não.. as que não fazem mais sentido, eles removem, como no caso dessa feature :)

Mas legal que deu certo! Qualquer coisa, só avisar :)
