### ISSUE TITLE
MRW#09 - hot loader não carrega as alterações automaticamente

### ISSUE THREAD

**Issue by rafa-so** [da2k/curso-reactjs-ninja#479]
Fala aí fernando, tudo tranquilo?

Estou - como o próprio título diz - enfrentando um problema nesta aula. Segui os passos para fazer fazer o hot loader. Quanto eu só inicio o servidor (npm start) o console do navegador já me dá a seguinte mensagem:
```
[WDS] Disconnected! client:41
[WDS] Hot Module Replacement enabled. client:37
[WDS] App hot update... client:37
```
se eu der CTRL + F5 vai de boas, mas o HL mesmo não está ok.

**Passos**
1. Exclui por garantia a pasta node_modules e o arquivo package-lock.json, e nada foi a mesma coisa.

2. Segui novamente a configuração do hot loader

De qualquer maneira segue o [repositório](https://github.com/rafa-so/react-webpack) no github, apesar de ter seguido esses passos, não estou conseguindo ver o que está errado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafa-so! Seu projeto não está exatamente igual o que foi mostrado na aula. O que você precisa fazer é deixar as configurações dos arquivos [dessa forma](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-09).

Se todos os arquivos estiverem assim, tudo vai funcoinar como esperado :)

**Comment by rafa-so** [comment]
Boa noite fernando tudo de boas?

Então, realmente o meu código a princípio não estava com o seu refactory que você faz no código em 10:33. De qualquer maneira também tinha uns erros de sintáxe (que também não são tão determinantes assim, pelo menos neste momento inicial). Bom... muito obrigado pelo auxílio aí.

A princípio seguindo a aula toda - inclusive com a refatoração - vai de boas :)

**Comment by fdaciuk** [comment]
Perfeito @rafa-so! Segue aí então, e qualquer dúvida, fique à vontade para perguntar :)
