### ISSUE TITLE
M1#A29 - Duvida sobre radio button

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#48]
Professor, na aula o senhor explica como trabalhar com checkbox, mas na parte de radio button a explicação ficou meio rasa, tentei fazer aqui um exemplo de radio button, a ideia é a mesma do checked e tal, mas se houver mais de 2 radio buttons, é preciso de uma abordagem diferente para controlar, o conceito foi intendido mas durante o curso faremos algum componente usando radio buttons ? só pra fixar melhor na pratica ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CheeseFlan! Com certeza! Vamos fazer várias pequenas aplicações durante o curso, para mostrar todos os recursos necessários =)

Agora no módulo 3 vamos utilizar mais formulários com Redux, então vai ficar mais claro o uso dos controles de formulário com React :D 

E qualquer dúvida que você tenha, pode perguntar =)

**Comment by CheeseFlan** [comment]
Vlw professor :D, uma duvida rápida, vamos aprender a colocar frameworks pra trabalhar em conjunto do react, exemplos bootstrap, materialize e etc ?

**Comment by fdaciuk** [comment]
Sim, nos dois primeiros módulos já tem alguns exemplos de como trabalhar com algumas libs externas, mas assim que começarmos a criar aplicações mais complexas, vamos ver na prática como usar essas libs de UI =)

**Comment by fdaciuk** [comment]
@CheeseFlan vou fechar a issue, mas se você tiver alguma dúvida relacionada a esse assunto, reabrimos, ok? =)
