### ISSUE TITLE
validateSchema is not a function

### ISSUE THREAD

**Issue by gustavoarmoa** [da2k/curso-reactjs-ninja#480]
# Segue snapshot do meu código atual
Sou aluno da Udemy e me deparei com um erro de schema do webpack. Por favor se puder ajudar indicando onde estou esrevendo errado.

OS: Linux Ubuntu 20.04

Segue a versão atual do código

###  **app.js**
```
'user strict'

var React = require('react')

var Title = React.createClass({
    render: function(){
        return React.createElement('h1', null, 'Titulo')
    }
})

exports default Title
```
### **index.js**
```
'use stric'

import Title from './app'

var React = require('react')
var ReactDOM = require('react-dom')

var Title = require('./app')

ReactDOM.render(
    React.createElement(Title),
    document.querySelector('[data-js="app"]')
)

exports default Title
```
Nota: Estou seguindo as instruções do [link das configurações](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) 

[Configuração webpack](https://gist.github.com/gustavoarmoa/a726dfb36a0105bef130ecaea3f0e4c8)
[Configuração babel](https://gist.github.com/gustavoarmoa/b329076595b5da7108010ab1d3c1aa48)

Poderias me dar uma luz onde estou errando porque estou tendo a seguinte situação

Rodando o comando **webpack-dev-server**
Saida: **validateSchema is not a function**

@gustavoarmoa

**Comment by gustavoarmoa** [comment]
So para adicionar @fdaciuk é a aula **MRW#06 - Usando o sistema de
módulos do ES6/2015**

**Comment by fdaciuk** [comment]
Oi @gustavoarmoa! Tenta comparar seu projeto com [esse código](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-06), que é o código que foi usado na aula.

Se ainda assim não estiver funcionando, sobe seu projeto todo em um repositório aqui no GitHub que eu baixo aqui e dou uma olhada no que pode estar errado, ok? :)

**Comment by fdaciuk** [comment]
Oi @gustavoarmoa! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
