### ISSUE TITLE
MRW#03 - Quebra na geração do bundle

### ISSUE THREAD

**Issue by fabiobranis** [da2k/curso-reactjs-ninja#481]
Apenas para constar que eu tentei usar a última build da versão 1 do webpack dev server (1.16.x) e a versão quebra (ele dá um erro de stream vindo do fs, ou seja, não achou o arquivo de bundle que ele deveria gerar). Sinceramente nem fui atrás de resolver isso pois a versão 1.16 já é bem outdated e realmente não faz sentido algum corrigir isso. Porém eu indico aqui usar a versão @1.6, pois ela não quebrou no modelo usado na aula. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fabiobranis! Testei aqui com a  `v1.15.0` do webpack e a `v1.16.5` do webpack-dev-server, e as duas funcionaram corretamente, tanto no node `v10` quando na `v12`. Qual sistema operacional você está usando, que teve esse problema?

**Comment by fabiobranis** [comment]
Estou usando o Linux Mint 19.3 Tricia com o npm na versão 6.13.7 e o node na versão 13.10.1.

**Comment by fdaciuk** [comment]
Legal! Tenta usar o node nas versões "par", que normalmente são as versões estáveis :)
A versão LTS atual é a `v12`, e a mais recente é a `v14`. As versões ímpar são consideradas "instáveis", pois o time do node.js faz muitos testes de novas features nessas versões. Elas também perdem suporte após 6 meses do seu lançamento, enquanto as pares se tornam LTS (versões com suporte a longo prazo) depois desse tempo.

Não sei se você já usa o [NVM](https://github.com/nvm-sh/nvm#installing-and-updating), mas se ainda não, recomendo desinstalar o node.js do seu sistema operacional, e usar o NVM para gerenciar as versões instaladas. Com o NVM você pode escolher qual versão você quer usar, e pode instalar várias versões do Node.js ao mesmo tempo :)

**Comment by fabiobranis** [comment]
@fdaciuk ah sim, eu uso o nvm sempre. É que na realidade eu sou um dev backend aprendendo React hehehe. Na máquina que eu estou fazendo o curso eu não tive uma preocupação em rodar o nvm install stable. Vou fazer uns testes aqui pra ver se roda tudo certo agora.

**Comment by fdaciuk** [comment]
Legal! Se precisar de alguma ajuda, só avisar :)

**Comment by fdaciuk** [comment]
Oi @fabiobranis! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
