### ISSUE TITLE
Dúvida sobre os dados do firebase.js

### ISSUE THREAD

**Issue by kadoshmt** [da2k/curso-reactjs-ninja#482]
Olá @fdaciuk 

Terminei aqui o app do reactflix e subi ele todo. Lembro-me de em um de seus vídeos você ter dito que não teria problema expor os dados de conexão do Firebase. Ocorre que enviei os dados pro Githyb e recebi uma mensagem dizendo que esta aplicação estava expondo dados sensíveis (api key do Google). 
Pergunto: esta informação é realmente sensível e pode ser utilizada para algum ataque? Deveria apagar o repositório e subir novamente sem as informações do firebase? 

P.S.: Deixei o modo de escrita como false nas regras do firebase. Apenas leitura.

Repositório: 
https://github.com/kadoshmt/reactjsninja-reactflix

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kadoshmt! O GitHub avisa mesmo, sempre que você comita qualquer informação que tenha credenciais. Mas a segurança do Firebase é tratada sempre do lado do Firebase, lá nas **rules** do banco, como mostrado na aula.

As chaves sempre ficam "abertas" para qualquer um ver, pois são usadas no frontend, e tudo o que está no frontend é público.

Mas, se você não quiser deixar as chaves no seu GitHub, o que você pode fazer é: se estiver usando o Create React App no seu projeto, já vai ter configurado [variáveis de ambiente](https://create-react-app.dev/docs/adding-custom-environment-variables/).

Elas servem exatamente para esse caso: ao invés de usar dados sensíveis direto no código, você usa as variáveis de ambiente e chama essas variáveis no seu código. Então você configura o valor dessas variáveis direto no ambiente onde você vai servir sua aplicação.

Variáveis de ambiente são um recurso do Node.js, não funcionam, de fato, no client side, pois a ideia delas é deixar esses dados escondidos do usuário final. O que acontece no caso do React, é que, por usar o webpack, nós conseguimos fazer uso das variáveis de ambiente apenas para isolar elas do nosso código. No final, ao gerar o build que vai para a produção, os valores dessas variáveis ficam expostos de qualquer forma.

Enfim, só expliquei isso pra você entender que isso existe, e que é um recurso que você pode usar para não deixar as chaves comitadas direto no seu código (ainda sabendo que elas vão ficar públicas no seu app de produção).

Se você nunca mexeu com variáveis de ambiente, pode dar uma olhada no módulo 4, onde eu explico como usá-las, ao fazer deploy da aplicação de pizzaria desenvolvida durante as aulas :)

Acho que é isso! Qualquer coisa, fique à vontade para perguntar :)

**Comment by kadoshmt** [comment]
Boa noite @fdaciuk .

Sim, conheço as variáveis de ambiente e já fiz uso delas em outros projetos. Até iria utilizar para este antes de comitar, mas pela pressa de começar outro tutorial e enviar este projeto logo pro GitHub, acabei esquecendo e comitando a mesma. Até tentei apagar seguindo um passo-a-passo do GitHub para remoção de arquivos tanto do repositório como do histórico, mas não deu muito certo.

Mas como você disse, ela se tornará pública de qualquer jeito, e como é só um arquivo de curso, e não um projeto real, acho que vou deixar ela comitada de qq forma, e ficar mais atendo quanto a isso.

Enfim, ansioso pra começar o modulo 4, onde a proposta dos dois apps parece bem mais próxima de um projeto real, e com certeza os conceitos ali aprendidos serão muito úteis.

**Comment by fdaciuk** [comment]
Legal @kadoshmt! Qualquer dúvida, fique à vontade para perguntar :)
