### ISSUE TITLE
Plugin vs Lib

### ISSUE THREAD

**Issue by luidyvcc** [da2k/curso-reactjs-ninja#483]
Eae Fernando, tudo bem por aí?
Estou acompanhando seu curso e surgiu uma dúvida sobre os termos que você usa durante as aulas.
O que é um Plugin?
O que é uma Lib?
Qual são as diferenças entre Plugin e Lib?

**Comment by fdaciuk** [comment]
Oi @luidyvcc! `Lib` é uma abreviação para `library` (ou biblioteca). Bibliotecas JavaScript são pequenos conjuntos de código que te oferecem uma interface abstraída de alguma coisa. Por exemplo: O React é uma biblioteca que abstrai a manipulação de DOM. Ao invés de manipular DOM manualmente, e organizar os estados da sua aplicação de forma manual, você usa uma biblioteca como o React para abstrair isso pra você, de uma forma mais simples.

Todo o "trabalho sujo", coisas que você precisaria escrever muito pra chegar em um resultado, o React faz isso por baixo dos panos, e te oferece uma interface mais clara (como o JSX) para que você consiga resolver os mesmos problemas, só que de forma mais simples :)

Um plugin também pode ser considerado uma biblioteca, mas "plugin" normalmente é uma pequena biblioteca que podemos usar para "extender" funcionalidades mais simples do nosso código. Por exemplo: o React abstrai toda a manipulação de DOM, mas se você tiver que escrever um carousel, por exemplo, você vai ter que escrever bastante código, e se preocupar bastante com a lógica de como o carousel vai funcionar.

Para isso, você pode instalar uma biblioteca de carousel, que já faz o trabalho mais pesado pra você! 

E essa biblioteca de carousel poderia ser um plugin, se a implementação dela já estiver feita em React, ou seja: você simplesmente pega essa biblioteca e "pluga" no seu projeto :)

Ficou claro? :)

**Comment by fdaciuk** [comment]
Obs.: sempre que você abrir uma nova issue, pode me marcar (com `@fdaciuk`) para que eu receba a notificação da sua dúvida, e te responda o mais rápido possível, ok? :)

Se você não me marca, eu acabo não recebendo a notificação, e posso demorar pra ver que você abriu uma issue :)

**Comment by fdaciuk** [comment]
Oi @luidyvcc! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
