### ISSUE TITLE
Erro ao iniciar o server após importar o css no index.js [M2#A31]

### ISSUE THREAD

**Issue by alsalvad** [da2k/curso-reactjs-ninja#484]
Olá, Fernando.
Sempre que insiro o css no index, ao iniciar o server, recebo os 2 seguintes erros:
./src/css/style.css 525 bytes {0} [not cacheable] [built]
./~/raw-loader/dist/cjs.js!./src/css/style.css 1.04 kB {0} [not cacheable] [built]

Quando entro na página pelo navegador, a tela fica toda branca.
Já refiz a aula 2 vezes pra ter certeza que não havia digitado algo errado, mas aparentemente está como no seu exemplo

O que pode ser isso?
Desde já agradeço!

**Comment by fdaciuk** [comment]
OI @alsalvad! Consegue mandar um print pra eu ver as mensagens completas? Outra coisa: suba seu projeto em um repositório aqui no GitHub, assim eu consigo colocar ele pra rodar aqui e ver o que pode estar acontecendo :)

**Comment by fdaciuk** [comment]
E detalhe importante: ao abrir uma issue aqui no GitHub, não esqueça de me marcar (com `@fdaciuk`), senão eu não recebo notificação da sua dúvida, ok? :)
Acabei vendo sua issue porque estava respondendo outra, e resolvi olhar na lista de issues abertas :)

**Comment by alsalvad** [comment]
@fdaciuk, através dos comandos no "versions-of-dependencies.md" eu consegui. Talvez tenha sido por conta da versão, visto que antes eu não informava qual versão deveria ser instalada.
Vou prosseguir assim mesmo, mas caso eu enfrente outro problema, aí já subo o projeto todo e te grito pra uma ajuda! :)
Obrigado pela atenção

**Comment by fdaciuk** [comment]
Perfeito meu caro! Conte comigo para o que precisar :)
