### ISSUE TITLE
SameSite=none (chrome deliver cookie)

### ISSUE THREAD

**Issue by tiagoeborsanyi** [da2k/curso-reactjs-ninja#485]
```
A future release of Chrome will only deliver cookies with cross-site requests
 if they are set with `SameSite=None` and `Secure`. 
You can review cookies in developer tools under Application>Storage>Cookies
```

Olá Professor, estou realizando o módulo 04 e começou a aparecer um warning no chrome sobre cookie associado a recursos entre siste.
No warning fala pra colocar SameSite=none pra ele desaparece, Tem como colocar em algum lugar da aplicação?
Pelo que pesquisei na internet e em alguns repositórios do github, ainda não tem um solução adequada para este tipo de problema. 
Se o senho conhecer alguma solução ficaria feliz em ouvir.

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tiagoeborsanyi! Não cheguei a ver essa mensagem. Chegou a ver se não é por causa de alguma extensão que você está usando? Tente abrir o mesmo site onde a mensagem estava aparecendo em uma aba anônima pra confirmar se não é alguma extensão :)

Se não for, qual versão do Chrome está usando?

**Comment by tiagoeborsanyi** [comment]
Boa tarde @fdaciuk  Desculpa pela demora mas estava fazendo alguns testes. Então pelo que fiz de teste e pesquisei esses warnings parece acontecer nas versões 6.x e 7.x do sdk do firebase somado a quando a pessoa tem algum plugin de segurança no chrome e/ou o react dev tools instalado. Eu desativei o react devTools e os warnings pararam.

Segue alguns links do que li pra testar e chegar nas conclusões:

Issue do repo do firebase apresentando esse problema
[https://github.com/firebase/firebase-js-sdk/issues/2284](url)

Forum do firebase com este tipo de problema:
[https://www.gitmemory.com/issue/firebase/firebase-js-sdk/2284/554906212](url)

Coloquei esses links para que alguém que passar por esses warnings possa consultar no futuro.
Obs.: Isso não causa problemas de funcionalidades quanto ao funcionamento da biblioteca.

Vou fechar a Issue, porque acredito que as dúvidas foram solucionadas.

Grato.

**Comment by fdaciuk** [comment]
Perfeito @tiagoeborsanyi! Provavelmente o warning é por conta de como as extensões lidam com a aplicação em si. Como extensões são usadas apenas em mode de desenvolvimento, não é algo que precisamos nos preocupar ao entregar nosso app em produção :)

De qualquer forma, obrigado pelos links! Eles poderão servir para consultas futuras, se mais alguém tiver o mesmo problema :)

Qualquer dúvida, fique à vontade para perguntar :)
