### ISSUE TITLE
Erro no html-webpack M2#A32

### ISSUE THREAD

**Issue by alsalvad** [da2k/curso-reactjs-ninja#486]
@fdaciuk consegui passar pelos problemas dos loaders raw e style, mas agora fiquei travado no html-webpack-plugin.
Nesse repositório está o projeto sem ter instalado o plugin, pra que você possa fazer a instalação do mesmo e ver os erros que irão surgir
https://github.com/alsalvad/curso-react

Eu realmente não faço ideia do que fiz errado, visto que segui passo a passo as aulas

**Comment by fdaciuk** [comment]
Oi @alsalvad! Acabei de ver aqui, e realmente dá problema com a versão mais recente do `html-webpack-plugin` :)
Já atualizei o [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md). Só instalar a `v2` desse plugin que vai funcionar corretamente :)

Qualquer problema com dependências que não estiver listada nesse arquivo, pode me avisar que eu adiciono lá, ok? :)

**Comment by alsalvad** [comment]
Obrigado, @fdaciuk, você é o cara!
Só mais uma pergunta sobre essa questão: eu tenho como reiniciar o projeto com versões atualizadas pra evitar que isso se repita utilizando versões atuais na hora da instalação de futuros plugins, ou é necessário seguir essas versões específicas?
Sempre que eu instalo um novo plugin, recebo um alerta de algumas falhas de segurança e que é necessário atualizar manualmente com o audit fix, mas quando o faço, o projeto todo quebra

**Comment by fdaciuk** [comment]
Para seguir as aulas, o ideal é usar as versões mostradas, apenas para aprender os conceitos. Como as bibliotecas estão em constante evolução, e recebem sempre atualizações, algumas coisas podem mudar de uma versão para outra.

Então, para seguir o curso, e entender os conceitos, use as versões que eu mostrei. Depois, na hora de criar um projeto seu mesmo, com o conhecimento da base das ferramentas, você pode usar as versões mais recentes, e olhar a documentação de cada uma para entender o que mudou de uma versão para a outra, e ajustar o que for necessário :)

A ideia de usar as mesmas versões que eu usei é só pra você não perder tempo durante o aprendizado :)

Depois, com os conceitos já aprendidos, você atualiza para novos projetos :)

**Comment by fdaciuk** [comment]
Oi @alsalvad! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
