### ISSUE TITLE
M2 #140: Sintaxe do Gulp v4

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#488]
Querido mestre, tudo bem?

Penso que talvez a sintaxe do Gulp nesta linha possa demandar atualização:
https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m02/applications/markdown-editor/gulpfile.js#L12

Digo isso porque eu enfrentei alguns erros, possivelmente porque meu Node ativo é o v12.

Lendo os erros e apelando ao Google, vi que uma solução seria usar o Gulp 4, ou um Node mais antigo.

Optei pelo Gulp 4.

Então os erros foram mudando de cara e ao fim vi que o Gulp 4 pede uma sintaxe ligeiramente diferente. A linha marcada acima no seu repo, portanto, eu alterei para:
```
gulp.task('default', function () {
  gulp.watch('src/**/*.js', gulp.series('lint'))
})
```
Então o Gulp passou a chamar o Lint corretamente.

Vou deixar aqui alguns links dos conteúdos que me levaram a essa solução:

### ReferenceError: primordials is not defined
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
https://github.com/gulpjs/gulp/issues/2324

### AssertionError: Task function must be specified
https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/

### Gulp error: watch task has to be a function
https://stackoverflow.com/questions/39665773/gulp-error-watch-task-has-to-be-a-function

Enfim. Agora acho que está de boa. Mas se você achar que fiz algo errado me diga. rsrsrs

abração!

@fdaciuk

**Comment by fdaciuk** [comment]
Perfeito meu caro! A sugestão seria usar o Node v10, mas se conseguiu resolver com o Gulp v4, ótimo! Se quiser mandar um PR lá no boilerplate também, fique à vontade :)

**Comment by pamplonapaulo** [comment]
Na verdade acho que me atrapalhei todo. Mas valeu o aprendizado. Você roda na aula o test:watch e eu tava tentando o lint:watch. kkkkk

**Comment by fdaciuk** [comment]
Sem problemas! De qualquer forma, em breve teremos atualizações nesses primeiros módulos, aí vai ficar mais simples seguir :D

**Comment by pamplonapaulo** [comment]
Bom dia, @fdaciuk

Me perdoe se eu já tiver te perguntado isso no passado, acho que não o fiz de forma tão direta:

dentre o CRA e começar um projeto com este work-flow (o qual eu gosto bastante, by the way), qual seria a DESVANTAGEM em não utilizar o CRA?

Presumo que este boilerplate está mais completão, tem o linter, o jest, storybook... Deve ter mais coisa que o CRA não me traz de largada.

E aproveitando, você abre mão de "direitos comerciais" em cima do boilerplate? Posso tocar um projeto para um cliente meu com esse chão aqui já lindamente pavimentado por você?

Como meu node v12 me forçou a alterar a versão e a sintaxe do Gulp.js, eu vou começar a guardar esse boilerplate em um repo à parte, para seguir vida própria na direção da minha carreira. Mas claro que poder colar aqui do mestre será sempre um help de extrema valia.

Grato pela atenção mais uma vez. Grande abraço!

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Sem crise meu caro, pergunte quantas vezes forem necessárias :)

Vamos lá:

**_Dentre o CRA e começar um projeto com este work-flow (o qual eu gosto bastante, by the way), qual seria a DESVANTAGEM em não utilizar o CRA?_**

Vou falar das vantagens que é mais fácil: apesar do boilerplate ser mais completo com relação a quantidade de coisas que temos nele, com o CRA você vai garantir que todo projeto vai começar sempre com a versão mais recente de todas as ferramentas, já testadas, e vai ter garantia que tudo estará funcionando sem problemas.

No boilerplate tem algumas versões das dependências que precisam ser revistas e testadas, para que tudo funcione com as versões mais recentes.

No caso das ferramentas, você pode instalar as mesmas no CRA. Inclusive, com o CRA, você consegue criar templates com o que você precisa, e criar uma nova instalação sempre partindo desse template, criado com o CRA :)

Na própria [documentação do CRA](https://create-react-app.dev/) eles ensinam [como criar seu próprio template](https://create-react-app.dev/docs/custom-templates/) :)

Vou falar sobre isso nas atualizações dos módulos desse curso, mas fica aí o link, caso você esteja curioso de como fazer :)

E se precisar fazer alguma configuração no CRA que ele não tenha (no webpack, babel, etc), mas ainda quiser mantê-lo "como é", sem ejetar, para não perder as atualizações dele, você pode usar uma ferramenta chamada [rescripts](https://github.com/harrysolovay/rescripts). Eu cito ela no módulo 4 e mostro como configurar o linter do standard para ser usado junto com a config atual de lint do CRA :)

---

**_E aproveitando, você abre mão de "direitos comerciais" em cima do boilerplate? Posso tocar um projeto para um cliente meu com esse chão aqui já lindamente pavimentado por você?_**

Importante você tocar nesse ponto: esse projeto do boilerplate - e várias outras ferramentas open source - devem oferecer uma licença de como o projeto pode ser usado.

No caso do boilerplate, ele está liberado com uma licença do tipo MIT (só olhar no rodapé do README do projeto).

Esse tipo de licença é bem liberal, e permite que você faça qualquer coisa com o projeto, incluindo projetos pessoas pagos, sem problema algum :)

Fique de olho apenas quando usar algum projeto open source que não tenha nenhuma licença. Se o projeto não apresenta licença, normalmente ele é restrito, e TALVEZ - com caixa alta mesmo, pois é um grande TALVEZ, mas tem chances de acontecer - talvez você possa ter problemas, então evite projetos que não definam uma licença, ok? :)

A maior parte dos projetos open source, principalmente com JS, você vai encontrar sob a licença MIT, então pode usar sem medo :)

Acho que era isso! Qualquer dúvida, fique à vontade para perguntar :)

**Comment by pamplonapaulo** [comment]
Po, valeu mestre @fdaciuk . Vou chegar no módulo 4 e vejo como ficam as coisas.

Eu não sei se consigo configurar o webpack com o lance das chunks e etc., que me parece um diferencial importante e mais complicadinho de settar. Vou rever com calma quando for o caso de fazer meu boilerplate a partir de um CRA, no próximo projetinho.

:)

Grande abraço!

**Comment by fdaciuk** [comment]
Sem crise! O CRA faz o mesmo esquema de separação dos chunks: você só precisa usar o `import()` função, que para cada componente importado dessa forma, o CRA gera um novo chunk :)
