### ISSUE TITLE
Aplicação para criação de Diagramas e telas

### ISSUE THREAD

**Issue by guilhermeci** [da2k/curso-reactjs-ninja#489]
Prof. bom dia.

estou desenvolvendo um trabalho e preciso criar as telas para prototipação e surgiu as seguintes dúvidas, no curso qual software/aplicação você utiliza para criá-las? 

Como ficaria um diagrama de classes e implantação da react pizzaria(não precisa ser completo, apenas uma dica de como ficariam os componentes)?

Desde já agradeço pela atenção.

Att;.
Guilherme Lopes

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @guilhermeci! Para o sistema de pedidos, eu fiz só um wireframe usando o [Gravit](https://designer.gravit.io), mas existem várias ferramentas para isso, como o Adobe XD, Figma, etc :)

**Comment by fdaciuk** [comment]
Oi @guilhermeci! Vou fechar essa issue, mas se ainda tiver dúvidas, pode comentar aqui que eu vou te ajudando, ok? :)
