### ISSUE TITLE
M1#A45 - Duvidas sobre os eventos do React

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#49]
Uma duvida rápida, no caso como foi explicado na aula, se eu usar "evento" que é emitido pelo onKeyUp, ele só vai deixar null as propriedades quando eu fizer uso desse "evento", em uma função assíncrona ?, ou sempre ao finalizar o callback, ele faz as propriedades ficarem null ?, porque na aula foi possível guardar e.target em uma constante, pra depois ser usada no método always, ai sim ele foi mudado pra null. em resumo só dá uma re explicação rápida pois não ficou muito claro pra min :)

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @CheeseFlan! O que acontece é mais ou menos o seguinte:

Como o evento não é o objeto de evento original do browser, é um evento que eles chamam de _sintético_, esse objeto está disponível de forma síncrona, ou seja: quando acaba a execução da função, ele se torna `null`, para não ficar consumindo memória.

Quando você faz qualquer ação assíncrona, o callback do evento já terminou de executar, então o evento é `null`, mas a função assíncrona ainda continua até finalizar a execução.

Como o parâmetro desse evento sintético é um objeto, e objetos são passados via referência de memória, quando você reatribui esse valor, o JS não vai remover esse objeto da memória, porque antes só existia o parâmetro da função apontando para esse objeto, agora, com a atribuição dentro da função de callback, tem outra variável apontando para ele, o que faz ele continuar sempre existindo, até que essa variável não esteja mais sendo utilizada, e então ele é removido da memória =)

Se você tem dúvidas com relação à referências de objetos, recomendo a leitura [desse post](https://blog.da2k.com.br/2017/01/25/objetos-referencias-de-valores-em-javascript/), vai ajudar a entender =)

Se ainda assim ficar alguma dúvida, comenta aqui :D

**Comment by CheeseFlan** [comment]
Vlw, professor agora deu pra entender melhor :+1:
