### ISSUE TITLE
MRW#03 - Erro ao rodar webpack-dev-server

### ISSUE THREAD

**Issue by ricardommps** [da2k/curso-reactjs-ninja#490]
Olá @fdaciuk, tudo bem?
Ao rodar o comando webpack-dev-server, estou recebendo o seguinte erro,
Error: ENOENT: no such file or directory, open 'C:\ ... node_modules\webpack-dev-server\client\live.bundle.js 
Antes de rodar fiz o processo de instalação dos pacotes,

npm install --save-dev webpack@1
npm install -g webpack@1
npm install --save-dev webpack-dev-server@1
npm install -g webpack-dev-server@1
 
Meu package.json esta assim,

```
{
  "devDependencies": {
    "webpack": "^1.15.0",
    "webpack-dev-server": "^1.16.5"
  }
}
```
node --version
v12.13.0

npm --version
6.12.0

Não roda nem chamando o webpack-dev-server direto do node_modules , node_modules/.bin/webpack-dev-server. Retorna o mesmo erro.
Obs: Estou usando windows

@fdaciuk

**Comment by ricardommps** [comment]
Pode desconsiderar , tinha algumas configurações no npm config de segurança da empresa que trabalho, comentei essas configurações e deu certo.

**Comment by fdaciuk** [comment]
Legal @ricardommps! Que bom que funcionou :)
Qualquer coisa, só avisar :)
