### ISSUE TITLE
M3 AULA 60

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#491]
Salve mestre. @fdaciuk

Não sei se captei o argumento que justifica a 'mágica' que você faz nessa aula, quando diz que podemos criar um objeto e mapear as propriedades se elas tiverem a mesma assinatura, "a propriedade passada como prop do action-creator".

Estamos falando exatamente da semelhança na assinatura destes dois blocos abaixo?

```
// action-creator:

export const updateAddress = (data) => ({
  type: UPDATE_ADDRESS,
  payload: data
})
```

```
// mapDispatchToProps:

const mapDispatchToProps = (dispatch) => ({
          updateAddress: (data) => dispatch(updateAddress(data))
        })
```

Nos permitindo chegar nessa abreviação:
```
const mapDispatchToProps = (dispatch) => { updateAddress }
```
Eu não acho os dois blocos tão idênticos assim, então estou na dúvida se entendi mesmo.

https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/m03/samples/40-todo-list-get-cep

Valeu! Obrigado! Abs

**Comment by fdaciuk** [comment]
OI @pamplonapaulo! Na verdade, o padrão que eu comentei foi:
- o nome do seu action creator (`updateAddress`) é exatamente o nome da prop que você vai passar para o componente;
- ao executar o action creator com om `dispatch`, você passa exatamente os mesmos argumentos que a prop espera, na mesma ordem;

Imagine se esse `mapDispatchToProps` não usasse o `dispatch`. O resultado ficaria assim:

```js
const mapDispatchToProps = (dispatch) => ({
  updateAddress: (data) => updateAddress(data)
})
```

Veja: é um objeto com uma propriedade `updateAddress`, que recebe uma função, que espera um argumento `data`. Isolando o objeto, pra facilitar a visualização:

```js
{
  updateAddress: (data) => {}
}
```

E o retorno desse método `updateAddress`, é uma função de mesmo nome, recebendo os mesmos argumentos. Nessa situação, poderíamos sempre escrever esse objeto dessa forma:

Ao invés de:

```js
{
  updateAddress: (data) => updateAddress(data)
}
```

Faríamos de forma abreviada:

```js
{
  updateAddress: updateAddress
}
```

Assim como fazemos em um `.map` com uma função externa, por exemplo:

```js
function funcaoQueTransformaOArray (item) {
  ...
}

const result = meuArray.map(funcaoQueTransformaOArray)
```

A diferença no padrão do que fazemos com o `mapDispatchToProps`, é que essa função de mesmo nome da propriedade do objeto vai ser disparada, passando seu resultado para a função `dispatch`:

```js
const mapDispatchToProps = (dispatch) => ({
  updateAddress: (data) => dispatch(updateAddress(data))
})
```

A abreviação que podemos fazer é passar um objeto para o `mapDispatchToProps`, não uma função, como no seu último exemplo:

```js
const mapDispatchToProps = { updateAddress }
```

O tratamento do dispatch é feito internamente pela função `connect`, que vai receber via argumento o `mapDispatchToProps` e, se ele for um objeto, ele faz uma iteração nesse objeto, chamando o dispatch e executando cada função que foi passada para esse objeto.

Não precisa você saber exatamente a implementação do `connect`, apenas saber que é isso que ele faz, que já vai ficar mais fácil entender o processo :)

Ficou mais claro? :)

**Comment by pamplonapaulo** [comment]
@fdaciuk 

Muito grato pela explicação.

Até aqui pra mim eu havia aceitado que 
```
{ paulo: paulo }
```
Seria o mesmo que
```
{ paulo }
```

Mas talvez por compreender pouco métodos e orientação a objeto, eu tenha dificuldade de enxergar a mesma redundância nesse código:
```
{
  updateAddress: (data) => updateAddress(data)
}
```
Pela qual seria possível escrever a mesma coisa com apenas

```
{
  updateAddress
}
```

Na minha cabeça ainda parece que uma coisa é o que vem antes dos ":" , o nome da chave, e outra coisa é o valor da chave, que vem à direita dos ":". Do lado esquerdo dos ":" temos apenas o nome da chave, o updateAddress. E do lado direito "(data) => updateAddress(data)". A simetria não é perfeita e me dificulta a "aceitação" kkk.

É um método chamando uma função homônima onde ambos passam o mesmo argumento, 'data'. Então é a mesma coisa e daí nos permite a abreviação. Seria isso? Acho que minha mente tende a criar uma linha vertical separando tudo em cima dos ":". Mas a sintaxe do método coloca os parâmetros logo à direita dos ":".A fixação nos ":" me induz ao erro, acho que é isso. Vou simplesmente aceitar!!! kkkk

**Comment by fdaciuk** [comment]
Não é legal simplesmente aceitar, é importante **entender** de fato, pois isso é muito usado em JS! E isso não tem a ver com orientação a objetos, mas sim com **referências de objetos**. Vou tentar explicar de outra maneira, vamos lá :)

Lembra lá do curso de JS, quando usamos o `.map` para iterar um array? O `.map` é uma função, que recebe uma função, e essa função recebida será executada uma vez para cada elemento do array, certo? Vimos isso também bastante no módulo 2 desse curso, quando falamos sobre testes, e recriamos os métodos de array :)

Mas vamos começar simples. Pense em um array `[1, 2, 3]`, onde você quer somar 1 para cada item do array. Dá pra usar o `.map` pra fazer isso, concorda? Vamos ver o código:

```js
const array = [1, 2, 3]
const newArray = array.map((item) => {
  return item + 1
})

console.log(newArray) // [2, 3, 4]
```

Essa função passada para o método `.map`, pode ser extraída dali, e então passamos somente a referência dessa função para o método `map`. Passamos a referência, sem executar, pois o método `map` é que vai executar ela:

```js
const array = [1, 2, 3]
function plusOne (item) {
  return item + 1
}

const newArray = array.map(plusOne)
console.log(newArray) // [2, 3, 4]
```

Percebeu o que aconteceu aqui? Passamos a referência da função `plusOne` para o método `.map`, sem executá-la. Perceba a semelhança dos dois códigos anteriores. No primeiro, eu passei a função direto no `.map`:

```js
array.map((item + 1) => {
  return item + 1
})
```

Se extraírmos só a função:

```js
const plusOne = (item) => {
  item + 1
}
```

Que é exatamente a mesma assinatura da função `plusOne`, só que dentro do `.map` usamos a arrow function:

```js
function plusOne (item) {
  return item + 1
}
```

Poderíamos passar para o `.map` uma função criada com `function` também:

```js
array.map(function (item) {
  return item + 1
})
```

E até uma função nomeada:

```js
array.map(function plusOne (item) {
  return item + 1
})
```

Todos esses códigos vão trazer sempre o mesmo resultado. Eles são semelhantes. Ficou claro até aqui?

Se sim, vamos continuar (se não ficou claro, comenta aí pra eu saber :D)!

Vamos voltar na parte que passamos a função `plusOne` como referência para `.map`:

```js
const array = [1, 2, 3]
function plusOne (item) {
  return item + 1
}

const newArray = array.map(plusOne)
console.log(newArray) // [2, 3, 4]
```

Agora pense no seguinte: ao invés de criar uma função `plusOne`, eu vou criar um objeto `methods` que vai ter um método `plusOne` (o que nós chamamos de **método** é uma função mesmo, não esquenta com nomenclatura):

```js
const methods = {
  plusOne: function plusOne (item) {
    return item + 1
  }
}
```

Nós fizemos bastante isso no JS Ninja, lembra? :)

Agora, podemos passar esse método `methods.plusOne` para o `map`, e ainda teremos o mesmo resultado:

```js
const array = [1, 2, 3]
const methods = {
  plusOne: function plusOne (item) {
    return item + 1
  }
}

const newArray = array.map(methods.plusOne)
console.log(newArray) // [2, 3, 4]
```

Perceba que o método `methods.plusOne` é uma função, que espera um argumento `item`. Podemos escrever essa função tanto nomeada, como anônima, usando `function` normal ou arrow function. Outras variações desse objeto seriam:

```js
const methods = {
  plusOne: function (item) {
    return item + 1
  }
}
```

Ou, com arrow function:

```js
const methods = {
  plusOne: (item) => {
    return item + 1
  }
}
```

Ou ainda, como só temos a expressão do `return` dentro da arrow function, podemos remover o "corpo" dela (chaves) e a palavra chave `return`:

```js
const methods = {
  plusOne: (item) => item + 1
}
```

Tudo bem até aqui?

Então vamos seguir!

Vamos olhar agora apenas para o objeto agora: podemos isolar essa função `plusOne`, e usá-la de duas formas. A primeira seria assim:

Definimos (criamos) a função:

```js
function plusOne (item) {
  return item + 1
}
```

E então, dentro da função do `plusOne` nós executamos ela:

```js
const methods = {
  plusOne: function (item) {
    // esse plusOne aqui dentro da função está chamando a função `plusOne` que criamos acima
    return plusOne(item)
  }
}
```

Veja: o método `plusOne` no objeto `methods` é uma função que espera um argumento (porque passamos ela para um método `.map`). Então, dentro dela, chamamos uma outra função de mesmo nome (`plusOne`) e repassamos o `item` recebido do `.map`.

Aí vem o grande ponto: a função criada fora, foi criada para esperar um argumento (`item`). E `plusOne` dentro de `methods`, também é uma função que espera um item. Então, ao invés de criar uma função e passar para `plusOne` dentro de `methods`, nós podemos aproveitar a referência da função `plusOne` que já estava criada fora:

```js
function plusOne (item) {
  return item + 1
}

const methods = {
  plusOne: plusOne
}
```

Percebeu o que aconteceu aqui? Não precisamos criar uma função para executar outra, se a assinatura da função é a mesma. Não fizemos isso lá no método `.map`, no início da explicação? Da mesma forma que passamos uma referência para o `.map`, podemos passar também uma referência para uma propriedade de um objeto :)

Deu pra entender melhor? :)

**Comment by pamplonapaulo** [comment]
Mestre @fdaciuk muitíssimo grato pela enorme gentileza dessa explicação tão detalhada. Me ajudou muito. Mesmo.

Baby steps de aprendizado! rsrsrs

Às vezes as abreviações ou abstrações do código começam a escalar e eu perco o fio da meada. Aqui você mastigou o assunto passo por passo.

Valeu demais!!! :)

**Comment by fdaciuk** [comment]
Massa @pamplonapaulo! Que bom que ficou claro! Qualquer coisa, só avisar :)
