### ISSUE TITLE
M3 AULA 64

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#492]
Mestre @fdaciuk.

Estou aqui na aula da revelação dos poderes assíncronos do middleware!!

Mas exatamente naquele momento em que você lança mão de um setTimeout para começar a demonstrar esse uso, meu console no Chrome jogou um erro meio cabuloso.

```
Warning: flattenChildren(...): Encountered two children with the same key, `bf7dc374-00da-4c00-871c-39f5c7cbf2f4`. Child keys must be unique; when two children share a key, only the first child will be used.
    in ul (created by TodosList)
    in TodosList (created by Connect(TodosList))
    in Connect(TodosList) (created by App)
    in div (created by App)
    in div (created by App)
    in App
    in Provider
    in AppContainer
```

Vou tentar reinstalar o redux na mesma versão do seu código, que seria o 3.7.2.
https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m03/samples/44-todo-list-get-cep/package.json

Acabei deixando meu package JSON com o redux versão ^4.0.5. É capaz dessa API ter recebido alguma alteração, né?

O meu folder tá aqui nesse link:
https://github.com/pamplonapaulo/cursoReactjsNinjaBackup/blob/master/m3/samples/31-get-CEP/src/index.js

O curioso é que visualmente, ao contrário do que esse erro dá a entender, ele renderiza na tela apenas um item novo na TODO list. Alguém já havia lhe reportado esse erro antes?

Ou é alguma bobagem e deu bug na mente e eu preciso tirar uma soneca! kkkk Estou numa maratona tentando fazer 20 vídeos por dia. Mas nunca consigo. 15, no máximo, em média.

Obrigado mais uma vez! Abs

**Comment by pamplonapaulo** [comment]
Mestre @fdaciuk muitíssimo grato pela enorme gentileza dessa explicação tão detalhada. Me ajudou muito. Mesmo.

Baby steps de aprendizado! rsrsrs

Às vezes as abreviações ou abstrações do código começam a escalar e eu perco o fio da meada. Aqui você mastigou o assunto passo por passo.

Valeu demais!!! :)

**Comment by fdaciuk** [comment]
Opa! Falae meu caro @pamplonapaulo :)

Então, esse erro aí não tem a ver com o Redux (não diretamente). É um erro do React mesmo: significa que você está renderizando algo dentro da sua `ul`, no componente `TodoList` (veja segunda primeira linha do erro, logo abaixo da mensagem), e a `key` que você está passando para os `li` etá duplicada. Quando isso acontece, o React renderiza apenas um elemento que tenha essa `key`. Exemplo:

Se o seu código tiver algo como:

```jsx
<ul>
  {items.map(item => (
    <li key='1'>Item 1 com key 1</li>
    <li key='1'>Item 2 com mesma key 1</li>
  ))}
</ul>
```

Se isso acontecer, apenas um dos `li` será exibido na tela, pois cada item deve ter uma `key` única :)

O erro deve estar acontecendo [nessa linha](https://github.com/pamplonapaulo/cursoReactjsNinjaBackup/blob/master/m3/samples/31-get-CEP/src/components/todos-list/index.js#L12), ou seja: em algum momento, foi feito o cadastro de dois itens com o mesmo ID :)

**Comment by pamplonapaulo** [comment]
@fdaciuk , sim eu havia notado. Mas foi falha humana minha no código? Comparei agora minuciosamente e o todos-list/index.js me parece idêntico ao seu. Seu console não joga esse erro na aula...

**Comment by fdaciuk** [comment]
Vou baixar seu projeto e dou uma olhada :)

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Já encontrei o problema. Ele está [aqui](https://github.com/pamplonapaulo/cursoReactjsNinjaBackup/blob/master/m3/samples/31-get-CEP/src/index.js#L36-L38).

Veja que, na linha 36, você cria a variável `nextAction`, executando a função `next` e passando a `action` pra frente. No momento em que essa função é executada, o próximo middleware é executado, recebendo a action.

Mas o problema acontece mesmo na linha 38, quando você faz o retorno **chamando novamente** a função `next`. Ali você deveria retornar a variável `nextAction`, pois você já chamou o `next` uma vez. Quando você chama duas vezes, ele vai executar a mesma ação duplicada.

Ao chamar a ação duplicada, como o ID já havia sido gerado, na hora de renderizar, ele tenta renderizar duas vezes a mesma coisa :)

Sacou a ideia? :)

**Comment by pamplonapaulo** [comment]
Putz, mestre @fdaciuk ! Que vacilo meu! Perdoe o lapso, falha minha ao reescrever o código dos vídeos. Era pra ser igual ao seu! kkk

Estou bem mais "calmo" com a maneira de lidar com meus bugs, mais paciente para analisar linha a linha. Mas ontem acho que não esperava por isso e comecei a "culpar" algum problema desconhecido, como as versões às vezes conflitantes. O horário avançado também me deu uma fadiga, acho.

Obrigado pelo help!!

**Comment by fdaciuk** [comment]
Ah, com certeza! Fadiga não ajuda muito no foco mesmo :)
Mas que bom que vc tá mais tranquilo com isso! Esse é o caminho cara! E conte comigo para o que precisar :)
