### ISSUE TITLE
M3 A81: Firebase packages import 

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#493]
Fala mestre
@fdaciuk

Só pra fechar aquele assunto, achei que deveria te comunicar que o Firebase também pediu para carregar os pacotes um por um, mesmo quando abandonei o CDN e fui para o package instalado via Yarn. Então significa que a mudança lá foi bem estrutural, agora qualquer acesso é chamando o package específico.

Deixo aqui um print do warning do Firebase à direita e, à esquerda, o JS que eu joguei para rodar sem warnings.

Só pra constar. Ta tudo ok. :)

![firebase](https://user-images.githubusercontent.com/25485709/86183520-901a5a00-bb08-11ea-9fea-3f12fe51622d.png)

**Comment by fdaciuk** [comment]
É isso mesmo @pamplonapaulo! Pode deixar que eu vou regravar essas aulas para refletir a atualização do Firebase!
Muito obrigado por reportar :)
