### ISSUE TITLE
M3 A89: Dispatch not working

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#494]
Mestre @fdaciuk , tudo bem?

Cara, você me daria um help? Ao clicar no botão do "Cadastrar Vídeo", nenhum erro e nenhuma ação acontece. Nada no console para dar uma pista...

https://github.com/pamplonapaulo/cursoReactjsNinjaBackup/tree/master/49-reactflix

Será que você faria ideia?

Eu fui tentar jogar uns console.log pra me ajudar, mas o dispatch é um objeto então não posso simplesmente jogar uma função lá dentro...

Gratidão!

**Comment by pamplonapaulo** [comment]
Ufa. Achei!

Estava faltando executar a openRegisterVideo, faltavam os parênteses!

```
  onOpenRegisterVideo: () => dispatch(openRegisterVideo())
```

Valeu mestre!!! Espero não ter dado trabalho à toa! Abs!!

**Comment by fdaciuk** [comment]
Opa! Que bom que resolveu @pamplonapaulo! Qualquer coisa, grita ae :)
