### ISSUE TITLE
Duvida sobre useState

### ISSUE THREAD

**Issue by jrosetim** [da2k/curso-reactjs-ninja#496]
@fdaciuk

Boa noite Fernando, estou com uma duvida em relação ao uso dos estados, vou colocar aqui para você um código que fiz somente para teste, e acontece que eu caio nesse problema recorrente.

```
import React, {useState} from 'react';
import {useHistory} from 'react-router-dom';


const ComponentTest : React.FC = () => {
  const history = useHistory();
  const [nextPage, setNextPage] = useState<boolean>(false);

  function handleClick() {
    setNextPage(true);

    if (nextPage){
       history.push('/');
    }
  }

  return (
    <button onClick={handleClick} >click</button>
  )
}
export default ComponentTest;

```

o que acontece é o seguinte, tenho o state nextpage que é iniciado como false, quando clico no meu botão, ele atualiza para true, porem a linha de baixo
que tem um if  é mais rápida do que a atualização do estado, dessa forma só consigo ir para a outra pagina clicando duas vezes no botão
como poderia resolver esse problema?

**Comment by fdaciuk** [comment]
Oi @jrosetim! O problema é a forma que você tentando pensar, vamos lá :)

Qualquer atualização de estado no React é assíncrona, seja usando `this.setState` em classes, ou funções de setState com hooks (como a sua `setNextPage`, por exemplo).

No momento em que você seta um novo valor usando essa função, você só terá acesso ao novo valor na próxima renderização do componente. E como você faz a verificação do `nextPage` apenas dentro do `handleClick`, que só é disparado após um clique, você vai ter esse problema mesmo. Seguindo o seu código como está, olha o que acontece:

- O componente renderiza pela primeira vez, e define o estado de `nextPage` para `false`;
- o componente retorna o `button`, que será renderizado na tela;
- você clica no `button`, e esse clique dispara a função `handleClick`;
- Você define um novo valor para `nextPage` como `true`, que só será `true` na próxima renderização, então `nextPage` ainda é `false` **nesse escopo**;
- Ainda não houve a re-renderização, pois tem mais código síncrono para ser executado: o seu `if`;
- Quando o `if` é executado, `nextPage` é `false`, logo ele não entra no `if`;
- Como não há mais código síncrono para ser executado, o componente é re-renderizado;
- Nessa nova re-renderização, `nextPage` recebe o novo valor `true`;
- Você clica novamente no botão, e todo o processo acontece novamente, dessa vez com o `nextPage` setado para `true`;
- Aí entra no `if` e o redirect acontece.

Entendeu como é o fluxo?

Sabendo disso, o que você vai precisar é simplesmente mover o seu `if` para dentro de um `useEffect`, que terá como dependência o `nextPage`:

```js
import React, { useState, useEffect } from 'react';
import {useHistory} from 'react-router-dom';


const ComponentTest : React.FC = () => {
  const history = useHistory();
  const [nextPage, setNextPage] = useState<boolean>(false);

  useEffect(() => {
    if (nextPage) {
      history.push('/');
    }
  }, [nextPage])

  function handleClick() {
    setNextPage(true);
  }

  return (
    <button onClick={handleClick} >click</button>
  )
}
export default ComponentTest;
```

O que vai acontecer nesse código acima? Vamos lá:

- O componente renderiza pela primeira vez, e define o estado de `nextPage` para `false`;
- o componente retorna o `button`, que será renderizado na tela;
- na primeira renderização, todo `useEffect` é executado. Então, nesse primeiro render, o `useEffect` vai executar, mas não vai cair no `if`, pois o valor de `nextPage` é false;
- você clica no `button`, e esse clique dispara a função `handleClick`;
- Você define um novo valor para `nextPage` como `true`, que só será `true` na próxima renderização, então `nextPage` ainda é `false` **nesse escopo**;
- Como não há mais código síncrono para ser executado, o componente é re-renderizado;
- Nessa nova re-renderização, `nextPage` recebe o novo valor `true`;
- Como o `useEffect` depende da mudança de `nextPage` para ser re-executado, e `nextPage` agora tem um novo valor, então o `useEffect` será executado nessa renderização.
- o componente retorna o `button`, que será renderizado na tela;
- a função do `useEffect` é executada;
- dessa vez, `nextPage` é `true`, então vai cair no corpo do `if`, e o redirect vai funcionar como esperado :)

Deu pra entender a ideia? :)

**Comment by jrosetim** [comment]
@fdaciuk agora ficou mais claro o funcionamento, acho que o que eu não tinha intendido direito era a questão da re-renderização, mas sua explicação foi muito tóp, ajudou bastante, muito obrigado!

**Comment by fdaciuk** [comment]
Perfeito meu caro! Qualquer dúvida, fique à vontade para perguntar :)
