### ISSUE TITLE
M4 A47: NODE_PATH=src/

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#497]
Fala mestre @fdaciuk, tudo bem?

Não encontrei nenhuma issue com esse tema, então achei que seria legal reportar a você.

Ao incluir NODE_PATH no .env, infelizmente recebi essa mensagem de deprecated:

"Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app."

Como não há esse arquivo jsconfig.json, fiquei um pouco perdido em onde eu poderia alocar esse baseUrl.

Você teria alguma dica?

Muito obrigado!

Abraço!

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! 
Esse arquivo `jsconfig.json` você pode criá-lo na raiz da sua aplicação, e colocar esse conteúdo aqui:
https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m04/04-reactzzaria/160/sistema-cadastro/jsconfig.json

Vai funcionar exatamente da forma que o `NODE_PATH` funcionava :)

E obrigado por informar, já anotei aqui a aula com o problema, e vou fazer a atualização da mesma :)

**Comment by pamplonapaulo** [comment]
Maravilha, mestre @fdaciuk !!! Grato pela força!! :)
