### ISSUE TITLE
MRW#05 Erro 

### ISSUE THREAD

**Issue by rafael-marques** [da2k/curso-reactjs-ninja#498]
Olá, estou tendo esse erro. Acredito que seja cois de versão. Seria possível informar como fazer isso no react atualizado. Tenho preferência por não seguir na versão anterior.

```
React.createClass is not a function
```
![image](https://user-images.githubusercontent.com/8671936/86972481-63d68d00-c149-11ea-8131-b7bcae7db99b.png)

@fdaciuk

**Comment by rafael-marques** [comment]
Eu pesquisei aqui e pello que vi eles removeram essa função na versão 16 e para conseguir rodar precisei adicionar uma dependência chamada `create-react-class`.

Acredito que possa encerrar esse chamado.

**Comment by fdaciuk** [comment]
Oi @rafael-marques! É isso mesmo: nesse caso, é só importar o `create-react-class` :)

Da v15 para a v16 foram feitas basicamente 2 alterações, que foi a remoção de dois pacotes para pacotes separados: o `create-react-class` e o `prop-types`. Eu abordo isso no módulo 2, quando mostro a atualização para a v15.5, pois essa remoção já estava prevista :)

Por isso eu sempre peço para usar as mesmas versões usadas em aula: assim você foca nos estudos, e não perde tempo para encontrar mudanças que ocorreram de uma versão para outra. Seguindo o curso, eu vou abordando essas mudanças, pode ficar tranquilo :)

Mudanças no React são bem raras, então tudo o que você vai ver na v15, vai ter na v16 também, pode estudar na v15 sem problemas, se quiser seguir exatamente como foi mostrado no curso :)

A diferença é que as versões posteriores vão ter features a mais, e isso eu vou sempre mostrando mais pra frente no curso :)

De qualquer forma, em breve eu devo atualizar os primeiros módulos para refletir a versão mais recente do React :)

**Comment by fdaciuk** [comment]
E fique à vontade para perguntar sempre que tiver dúvidas, ok? Estou aqui pra te ajudar no que for preciso :)
