### ISSUE TITLE
M4 A79: Linter cada vez mais exigente!

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#499]
Fala mestre @fdaciuk ! Beleza?

Cara, nada de mais mas duas observações sobre o meu linter aqui.

As funções login e logout, que entram em onClick na aplicação, o linter tem mandado incluir o "handle" antes, no nome de cada uma. Estão querendo controlar nosso trabalho, mano!! kkkk

E outra coisa, o useEffect de autenticação do Firebase, que no seu código está com um array vazio no segundo parâmetro, comigo o Linter está mandando eu colocar no array o setUserInfo:

```
  useEffect(() => {
    firebase.auth().onAuthStateChanged((user) => {
      console.log('user data:', user)
      setUserInfo({
        isUserLoggedIn: !!user,
        user
      })
    })
  }, [])
```

React Hook useEffect has a missing dependency: 'setUserInfo'. Either include it or remove the dependency array

Como o setUserInfo não sofre atualização, para obter o mesmo comportamento que um array vazio eu resolvi  passar ele dentro em vez de remover o array. Se eu remover o array, o código rodaria dentro desse useEffect no caso de qualquer atualização no componente. (certo?)

Mas apesar de passar o array em branco, apesar do warning, o código não quebra.

Tive um insight agora de num futuro distante os trabalhadores fazendo motim por causa de um novo pacote de regras do linter, "cerceando" a autonomia deles!! kkkk  Zoeira... Só pra descontrair!

grande abraço!

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Vamos lá :)

> As funções login e logout, que entram em onClick na aplicação, o linter tem mandado incluir o "handle" antes, no nome de cada uma. Estão querendo controlar nosso trabalho, mano!! kkkk

hahaha! É mais ou menos isso mesmo :)

Pois é.. Algumas alterações foram feitas recentes no standard, e eles adicionaram isso, para tentar padronizar =)

---

> E outra coisa, o useEffect de autenticação do Firebase, que no seu código está com um array vazio no segundo parâmetro, comigo o Linter está mandando eu colocar no array o setUserInfo

Sim, em alguma aula mais pra frente eu faço essa alteração. No momento em que essa aula foi gravada, acredito que o CRA ainda não tinha o linter de hooks ativado. Na versão mais recente o linter já vai te ajudar a evitar problemas com hooks. Pode seguir as recomendações sem problemas, que não vai ter diferença nos resultados :)

---

> Se eu remover o array, o código rodaria dentro desse useEffect no caso de qualquer atualização no componente. (certo?)

Isso mesmo: nunca remova o array do useEffect, a menos que você queira que ele rode a cada re-render do componente :)

---

> Mas apesar de passar o array em branco, apesar do warning, o código não quebra.

Exato, não vai quebrar pois a função setUserInfo é uma função se setState que vem do `useState` do React, então a referência dessa função nunca vai se perder.

Mas como nós importamos essa função, nesse componente não tem como saber se ela é uma função que pode ser recriada ou não, então é sempre bom seguir as recomendações do linter :)

---

> Tive um insight agora de num futuro distante os trabalhadores fazendo motim por causa de um novo pacote de regras do linter, "cerceando" a autonomia deles!! kkkk Zoeira... Só pra descontrair!

HAHAH! Muito bom! Vai ser algo assim mesmo haeuhae

**Comment by pamplonapaulo** [comment]
Valeu mestre. Obrigado mais uma vez!

Acabei de assistir a aula em que você fala dessa atualização das dependências, onde o useEffect passa a se queixar do array vazio quando contém o setUserInfo. É a aula 99, aquela de 25 min.

Valeu abração!

**Comment by fdaciuk** [comment]
Show! Qualquer coisa avisa aí :)

**Comment by lucianobarauna** [comment]
Santa pesquisa do github hahaha. Já achei a resposta da minha dúvida hahah @fdaciuk rsrs. Vlw @pamplonapaulo
