### ISSUE TITLE
Duvida sobre react + webservice

### ISSUE THREAD

**Issue by RodrigoWP** [da2k/curso-reactjs-ninja#5]
Duvida,

Eu já tenho um webservice rodando.. e quero fazer um CRUD de uma forma simples consumindo-o

O que usar em conjunto com o React? O Redux seria pra isso?

**Comment by fdaciuk** [comment]
Fala @RodrigoWP! =)

O Redux serve para gerenciar o estado da sua aplicação. Ele vai servir basicamente para substituir (na maior parte dos casos) o uso do `this.state` dentro de um componente do React. Vamos ver sobre ele em breve =)

Mas para consumir um webservice, você pode usar o React para fazer os componentes de formulário que irão submeter os dados, e componentes de apresentação dos dados.

Então, só vai precisar fazer os requests para buscar os dados do servidor: ou manualmente, ou com alguma lib para ajax ou fetch =)

Nas últimas aulas do primeiro módulo, eu mostro um exemplo consumindo a API do GitHub. Isso pode ajudar a dar uma visão melhor de como fazer isso com o React =)

Qualquer dúvida grita ae =)

**Comment by RodrigoWP** [comment]
@fdaciuk Obrigado!
