### ISSUE TITLE
Duvida rapida :D

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#50]
Professor, pelo que eu vi o modulo 4 ainda esta pra lançar, queira saber se vai haver um pouco de react fiber e se o modulo 4 vai ser grande como o modulo 2 ? ou vai ser surpresa ? :+1: 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CheeseFlan! O _Fiber_ é só o nome dado para o _core_ da nova versão 16 =)
Provavelmente eles irão lançar essa versão antes de finalizarmos o curso, então para manter tudo atualizado, vamos sim ver sobre ele =)

Os módulos `#03` (Redux) e `#04` (React Router v4+) vão ser um pouco menores que o `#02`, pois são específicos dessas ferramentas. Mas o `#05` (SSR) acredito que vai ser um pouco maior, pois vamos entrar na parte de backend, e começar a fazer algumas aplicações um pouco mais complexas, usando tudo o que vimos em todos os módulos anteriores :D

**Comment by CheeseFlan** [comment]
Vlw professor, estou gostando muito do curso ate agora foi o melhor
conteúdo de React brasileiro, acada aula que eu assisto fico mais empolgado
em continuar :D, ainda estou no modulo #02, mas estou na expectativa do
modulo 04 e e agora que você falou do modulo 05 estou ainda mais empolgado,
Obrigado.

Em 16 de setembro de 2017 08:46, Fernando Daciuk <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Legal :D 
Qualquer dúvida avisa ae :D
