### ISSUE TITLE
M4 A165: destructuring 

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#501]
Mestre @fdaciuk. Tudo bem?

Nessa aula onde removemos os dados fake de flavours você fez uma arrumação no código e colocou um segundo parâmetro/argumento (nunca sei qual nome dou! rsrs) em uma função:
```
function getFlavoursNameAndId ({ checkboxes, pizzasFlavours }) {
  return Object.entries(checkboxes)
    .filter(([_, value]) => !!value)
    .map(([id]) => ({
      id,
      name: pizzasFlavours.find((flavour) => flavour.id === id).name
    }))
}
```

A função estava com um argumento/parâmetro apenas, o checkboxes. E sem destructuring.

Minha dúvida é, você precisava usar a colcheia, isto é, o destructuring?

Seria essa uma sintaxe mais "respeitada" agora em tempos de ES6?

Também funcionaria sem o destructuring, sem as colcheias. Ou não? Então só queria entender porque optou por utilizar essa sintaxe em vez de apenas passar os dois argumentos.

É só isso. Mais uma vez obrigado pela força! Abraços

PS: 17ª issue aberta por mim. Vou ganhar o troféu de aluno mais mala! kkkk

**Comment by fdaciuk** [comment]
Opa, eae @pamplonapaulo! Vamos lá :D 

> Nessa aula onde removemos os dados fake de flavours você fez uma arrumação no código e colocou um segundo parâmetro/argumento (nunca sei qual nome dou! rsrs)

Primeiro respondendo à sua dúvida sobre parâmetro vs argumento: 
- argumento é o nome do **valor** passado para uma função. 
- parâmetro é como você nomeia um argumento recebido.

Quando você executa uma função: `soma(1, 2)`, os valores `1` e `2` são chamados de **argumentos**, pois você está passando isso para a função. 

Na declaração dessa função, os **argumentos passados** podem ser nomeados. Os nomes para esses argumentos são chamados de parâmetros:

```js
function soma (x, y) {
  return x + y
}
```

Na função `soma` acima, `x` e `y` são parâmetros, que irão receber os valores (argumentos) passados para a função :)

Não que seja algo que você precise se preocupar, mas só pra deixar aqui uma resposta pra isso :D 

---

> você precisava usar a colcheia, isto é, o destructuring?
> Seria essa uma sintaxe mais "respeitada" agora em tempos de ES6?
> Também funcionaria sem o destructuring, sem as colcheias. Ou não?

O objetivo de usar uma função dessa forma é simples: quando sua função espera que mais de um valor seja passado via argumento, ao executar a função, você precisa passar os argumentos na mesma ordem em que eles foram definidos na função. 

Imagine que não vamos usar o destructuring ali, vou passar os argumentos da forma "padrão". A definição da função ficaria assim:

```js
function getFlavoursNameAndId (checkboxes, pizzasFlavours) {
  // ...
}
```

E a execução da função seria:

```js
getFlavoursNameAndId(checkboxes, pizzasFlavours)
```

Funcionaria igual? Com certeza! Mas o grande problema é: e se eu inverter os argumentos passados? 

```js
getFlavoursNameAndId(pizzasFlavours, checkboxes)
```

Concorda que, se eu fizer isso, terei um problema? Eu estou passando `pizzasFlavours` primeiro, mas minha função espera `checkboxes` primeiro. Eu preciso passar os argumentos **exatamente** na ordem em que a função espera.

Pra resolver isso, nós podemos passar um objeto como argumento para a função, onde cada valor vai dentro de uma propriedade desse objeto.

E isso nós já fazíamos desde o ES5, não é novidade:

```js
getFlavoursNameAndId({
  checkboxes: [],
  pizzasFlavours: []
})
```

Fazendo dessa forma, lá na definição da função, não importa a ordem das propriedades do objeto. Nós estamos recebendo apenas um único argumento, que é um objeto com algumas propriedades. Como a ordem não importa, a definição da minha função poderia ser:

```js
function getFlavoursNameAndId ({ pizzasFlavours, checkboxes }) {
  // ...
}
```

Que tudo funcionaria da mesma forma! Imagine uma função que precisa de mais argumentos? E ainda tem um outro caso interessante: voltando no primeiro exemplo:

```js
function getFlavoursNameAndId (checkboxes, pizzasFlavours) {
  // ...
}
```

Você poderia executar a função assim:

```js
getFlavoursNameAndId([], [])
```

Concorda? Passando dois arrays, onde o primeiro vai representar o `checkboxes` e o segundo vai ser o `pizzasFlavours`. Mas você acha isso claro de entender? Não é obrigatório eu atribuir os arrays a uma variável antes de passar como argumento para essa função.

Já no caso do objeto, as propriedades do objeto são sempre nomeadas, então fica muito clara a intenção do que eu estou querendo passar para a função :)

Basicamente essa é a ideia :)

Como eu disse: isso não é específico do ES6+. No ES5 nós já fazíamos isso. A diferença é que, na hora de "pegar" esses valores, nós tinhamos que pegar um a um dentro da definição da função:

```js
function getFlavoursNameAndId (args) {
  var checkboxes = args.checkboxes
  var pizzasFlavours = args.pizzasFlavours
}
```

O destructuring só tornou nossa vida um pouco mais fácil :)

Então, minha recomendação é: sempre que você precisar passar mais de um argumento, use esse formato, pra não precisar se preocupar com a ordem em que os valores são passados. 

A menos que seja uma função que deixe muito claro a ordem dos argumentos, ou que realmente a ordem dos argumentos não importem, como uma função de soma, por exemplo.

Ficou claro? :)

---

> PS: 17ª issue aberta por mim. Vou ganhar o troféu de aluno mais mala! kkkk

Na verdade, isso só mostra o quão dedicado você está nos seus estudos! Se estão surgindo dúvidas, quer dizer que você está interessado em aprender. Abra issues sempre que precisar, estou aqui pra isso mesmo haha :D

**Comment by pamplonapaulo** [comment]
Muito grato prof @fdaciuk !!! Entendi perfeitamente os dois assuntos!! Vamo que vamo! faltam 50 vídeos!! Abs

**Comment by fdaciuk** [comment]
Show!! Foco aí :D
