### ISSUE TITLE
react route dom

### ISSUE THREAD

**Issue by mauriciogirardi** [da2k/curso-reactjs-ninja#502]
```
<Suspense fallback=''>
        <Switch>
          <Route path='/' exact component={Hero} />
          <Route path='/produtos' component={Products} />
          <Route path='/acompanhamento' component={ChooseTypeAcai} />
        </Switch>
</Suspense>
```

boa noite , estou com problema tento chamar o path acompanhamento  mais não aparece a pagina 
o Linke esta vindo de src/pages/food/acai/index.js  tem um link la q coloquei para teste mais nada 

repositorio 
https://github.com/mauriciogirardi/acaiDelivery

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mauriciogirardi! O problema é que você adicionou um `BrowserRouter` dentro [dessa página](https://github.com/mauriciogirardi/acaiDelivery/blob/master/src/pages/products/index.js#L20). Isso vai com que um novo contexto de rotas seja gerado, e sua página que estava antes desse `BrowserRouter` não carregue.

Você só deve ter **apenas um** `BrowserRouter` em todo o app, que é aquele que você colocou no arquivo `src/root.js` :)

Removendo esse `BrowserRouter` da página de produtos, tudo vai funcionar como esperado :)

**Comment by mauriciogirardi** [comment]
verdade msm falou isso no curso, obrigadão

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar :)
