### ISSUE TITLE
M4 A173: setting "sistema-cadastro" antes de começar 

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#504]
Querido mestre @fdaciuk ,

no aulão de 30 min onde vc prepara o diretório do sistema-cadastro, por que você não rodou ```yarn install``` em vez de copiar as dependências uma por uma para então instalar elas?

Eu fiz uma cópia do meu package.json e mantei um install geralzão, depois comparei e vi que o package.json não sofreu qualquer alteração.

Só isso mesmo pra entender.

Abração!
@fdaciuk

**Comment by fdaciuk** [comment]
Opa @pamplonapaulo! :D 

A ideia de fazer como eu fiz é para que as versões mais recentes de cada biblioteca sejam instaladas, ignorando as versões que estão no package.json :)

Mas como eu falei em aula: não recomendo fazer esse processo sem testar: crie sempre uma branch antes, faça esse update, e teste seu app, pra ver se nada quebrou, já que alguma lib pode ter virado uma versão _major_, e alterado a forma como ela funciona :)

**Comment by pamplonapaulo** [comment]
putz...rsrsrs entendi!  bom, ta tudo rodando direitinho! rsrs Mas legal, mais uma lição anotada! rs
Obrigado!!!
Abs!!

**Comment by fdaciuk** [comment]
Sim, como esse update foi feito recentemente, não deve quebrar nada mesmo. Mas daqui a um ano, por exemplo, alguma coisa pode quebrar, então é bom sempre ficar ligado :)

Qualquer dúvida, avisa ae :D
