### ISSUE TITLE
M4 A208

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#505]
Salve mestre @fdaciuk !

Hoje com esse bloco de código eu tive dois pensamentos.

```
                <List>
                  {Object.entries(pizza.value).map(([sizeId, value]) => {
                    const sizeName = pizzasSizes
                      ?.find(s => s.id === sizeId)
                      ?.name

                    return (
                      <ListItem
                        key={sizeId}
                        name={sizeName}
                        price={value}
                      />
                    )
                  })}
                </List>
```

O primeiro deles é sobre o destructuring  ``` ([sizeId, value]) ```

Acho que é a primeira vez que te vi fazendo um destructuring com variáveis cujos nomes você deu no ato do destructuring, isto é, nomes aleatórios. Durante todo o curso o normal é ver você chamando elas exatamente pelo nome que elas tem no seu objeto de origem. No nosso DB a gente não tem sizeId dessa forma, são apenas os números dos IDs. E value até há, mas a estrutura é tão outra que pra mim você realmente nomeou de fato no ato do destructuring, elas não vieram com estes nomes.

Então das duas formas é possível? Ou é porque trata-se de um destructuring em cima de um array, onde necessariamente temos apenas chave + valor? De um objeto mais completo, naturalmente, seria obrigatório chamar pelo nome das propriedades. Faz sentido?

E o outro assunto: o optional chaining. Achei fabuloso esse recurso! E tendo a olhar para ele como se fosse um short hand de um ternário, pois dependendo do booleano toma uma ou outra atitude. Faz sentido pra você?

Enfim. Que curso maravilhoso, cara!! Foda demais!!

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! Vamos lá :D 

> Então das duas formas é possível? Ou é porque trata-se de um destructuring em cima de um array, onde necessariamente temos apenas chave + valor? De um objeto mais completo, naturalmente, seria obrigatório chamar pelo nome das propriedades. Faz sentido?

Tem dois pontos importantes sobre essa pergunta: o primeiro:

### 1) ao fazer um destruturing, você sempre deve fazer em cima da estrutura do objeto base. 

Por exemplo:

Se eu tenho um objeto assim:

```js
const person = {
  name: 'Fernando',
  age: 35
}
```

E se eu quiser fazer destruturing das propriedades desse objeto, o destructuring vai ser no formato de objeto, "coletando" os nomes das propriedades para criar variáveis com esses mesmos nomes:

```js
const person = {
  name: 'Fernando',
  age: 35
}

const { name, age } = person
```
Perceba que estamos declarando **novas variáveis** aqui, usando o `const`. O código acima seria o mesmo que fazer:

```js
const name = person.name
const age = person.age
```

Agora eu tenho duas variáveis: `name` e `age`, que foram criadas à partir das propriedades do objeto. Se no meu escopo eu já tiver alguma variável já declara com esse nome, o JS vai dar um erro dizendo que a variável já foi declarada. Exemplo:

```js
const name = 'Maria'

const person = {
  name: 'Fernando',
  age: 35
}

const { name, age } = person // Uncaught SyntaxError: Identifier 'name' has already been declared
```

Com objetos, é sempre obrigatório fazer o destruturing com o mesmo nome da propriedade. Mas eu também consigo renomeá-la, para evitar esse tipo de problema:

```js
const name = 'Maria'

const person = {
  name: 'Fernando',
  age: 35
}

const { name: personName, age } = person 

console.log(name) // "Maria"
console.log(personName) // "Fernando"
```

Agora, ao invés de criar uma variável `name` no destrutucturing de `person`, eu criei uma variável chamada `personName`, que vai receber o valor da propriedade `name`.

Detalhe que não é obrigatório fazer destruturing de todas as propriedades do array: se eu quisesse criar apenas uma variável, com o nome de apenas uma propriedade do objeto, eu poderia sem problemas:

```js
const { age } = person
```

Pegou até aqui?

Com arrays é o mesmo esquema: a diferença é que, com arrays, nós não temos nomes de propriedades, mas sim **índices numéricos** representando cada posição do array.

Nesse caso, para fazer o destructuring com arrays, você vai dar um nome que irá representar o valor **naquela posição do array**. E isso não é novidade, nós já fizemos antes, com o uso do `useState`, lembra? :)

Exemplo:

```js
const coords = [0.12345, 2.1545]

const [lat, lng] = coords
```

Perceba que, ao fazer destruturing de um array, para criar as variáveis, nós precisamos usar a sintaxe de array para a desestruturação.

No exemplo acima, eu tenho um array de coordenadas para latitude e longitude. O primeiro índice do array representa a latitude, então, na **primeira posição da desestruturação**, representando o índice **0** (zero) do array, eu criei uma variável com o nome `lat`. 

E na segunda posição, representando o índice **1** do array, eu criei uma variável chamada `lng`.

Como arrays são ordenados, é preciso sempre respeitar as posições para criar as variáveis com os valores corretos. Olhe esse outro exemplo:

```js
const array3d = [10, 20, 15]

const [x, y, z] = array3d
```

Veja que agora eu tenho um array com coordenadas tridimensionais, que eu representei usando as variáveis `x`, `y` e `z`.

_Dá pra pegar só os valores de `x` e `y`, por exemplo?_ 

Claro! Só fazer assim:

```js
const [x, y] = array3d

console.log(x) // 10
console.log(y) // 20
```

_Legal, mas e se eu quisesse pegar só o valor de `z`?_ 

Dá sim, mas tem um ponto de atenção aqui: como precisamos respeitar a ordem dos elementos, mas só queremos o valor do índice `2` do array (posição 3), que seria o `z`, podemos só separar por vírgula a quantidade de valores que queremos "pular":

```js
const [, , z] = array3d

console.log(z) // 15
```

Veja que não nomeamos `x` e `y` aqui, pois só queremos o valor de `z`. Mas `z` está no índice 2 do array, então usamos a mesma sintaxe de array, separando valores por vírgula - nesse caso, separando as variáveis por vírgula - simplesmente **não nomeando** as primeiras variáveis, pois não vamos precisar delas. Faz sentido? 

E se ainda você quiser pegar só o `y`, também não precisa declarar os 3 valores. Pode fazer só assim:

```js
const [, y] = array3d

console.log(y) // 20
```

Já que o `y` está na posição do índice 1 do array.

Deu pra entender até aqui?

---

Se o ponto `1` ficou claro, podemos seguir para o segundo ponto importante:

### 2) É preciso ficar atento aos valores resultantes de uma expressão

Veja que, no exemplo, eu usei o `Object.entries`. O que esse método faz?

O `Object.entries` recebe um objeto via argumento, e retorna um array de arrays. Cada array, dentro do array principal, vai ter sempre duas entradas: no índice zero, a chave (ou propriedade) daquele objeto passado para `Object.entries`, e no índice 1, o valor daquela propriedade.

Voltando ao exemplo do primeiro objeto:

```js
const person = {
  name: 'Fernando',
  age: 35
}

console.log(Object.entries(person)) // [ ['name', 'Fernando'], ['age', 35] ]
```

Olha só o formato do array que a expressão `Object.entries(person)` retorna! Vou quebrar em linhas pra ficar mais fácil de ver:

```js
[
  ['name', 'Fernando'],
  ['age', 35]
]
```

Aqui podemos perceber que o `Object.entries`, quando executado, retorna um array. E cada item desse array também é um array com chave / valor daquele objeto.

_E por que precisamos do `Object.entries`?_

Aqui temos que voltar um pouquinho no nosso aprendizado de JS, e também sobre JSX:
- nós já vimos em JS que podemos iterar arrays com `for`, `while`, etc., para fazer alguma coisa com cada um dos seus valores isoladamente;
- vimos também que podemos iterar um objeto, e passar por todas as suas propriedades, usando o `for in`;
- mas, dentro do JSX, nós só podemos usar expressões. Não dá pra usar um `if`, `for`, `while`, por exemplo, pois essas estruturas não retornam valores, apenas criam blocos de código que serão executadas, dada uma certa condição.

Sabendo das informações acima, o que nós temos:

O objeto em `pizza.value` tem esse formato:

```js
{
  'asdfi-1asdf032-asdf23': 10,
  'lkjfef-320fsdj0-fsdlkjf': 20,
  'liesa-30saef0-adsfle': 30
}
```

Precisamos iterar por esse objeto para criar os nós HTML que serão representados em tela. Mas não podemos usar o `for in`, pois estamos dentro do JSX. Precisamos de uma expressão. Então vamos sempre pelo seguinte caminho: pegamos o objeto e o **transformamos em um array**, pois arrays contém métodos (como `map`, `filter`, `reduce`, etc), que **sempre retornam um valor**, logo podemos dizer que, ao executar esses métodos, nós temos **expressões**.

E como só podemos usar expressões dentro do JSX, para ter acesso à valores, ao invés de só criar blocos de código, o caminho é: sempre que você tiver um objeto e precisar iterá-lo, você vai transfomá-lo em um array antes :)

E pra finalizar, a explicação dos nomes dos parâmetros `sizeId` e `value`:

O objeto em `pizza.value` vai ser transformado da seguinte forma:

```js
Object.entries(pizza.value)
```

O resultado da expressão acima é:

```js
[
  ['asdfi-1asdf032-asdf23', 10],
  ['lkjfef-320fsdj0-fsdlkjf', 20],
  ['liesa-30saef0-adsfle', 30]
]
```

Veja só: um array de arrays! Para ter acesso a cada um dos itens desse array, podemos usar a sintaxe:

```js
const pizzasValues = [
  ['asdfi-1asdf032-asdf23', 10],
  ['lkjfef-320fsdj0-fsdlkjf', 20],
  ['liesa-30saef0-adsfle', 30]
]

console.log(pizzasValues[0]) // ['asdfi-1asdf032-asdf23', 10]
console.log(pizzasValues[1]) // ['lkjfef-320fsdj0-fsdlkjf', 20]
console.log(pizzasValues[2]) // ['liesa-30saef0-adsfle', 30]
```

Certo? Mas obviamente nós não vamos fazer isso manualmente. Vamos sempre iterar com o `map`, para ter acesso a todos os valores, e criar nossa lista de campos no JSX. Como o `map` sempre retorna um novo array, com os itens modificados, nós usamos o `map` para iterar por esse array, e retornar uma lista de itens já dentro do JSX. 

A iteração vai ficar assim:

```js
const pizzasValues = [
  ['asdfi-1asdf032-asdf23', 10],
  ['lkjfef-320fsdj0-fsdlkjf', 20],
  ['liesa-30saef0-adsfle', 30]
]

const result = pizzasValues.map((item) => {
  // aqui teremos acesso a cada array de pizzasValues, um por vez
})
```

Veja que, dentro do `map`, o argumento `item` representa cada array, dentro do array principal, concorda? Então eu poderia fazer um destruturing dentro do `map`:

```js
const pizzasValues = [
  ['asdfi-1asdf032-asdf23', 10],
  ['lkjfef-320fsdj0-fsdlkjf', 20],
  ['liesa-30saef0-adsfle', 30]
]

const result = pizzasValues.map((item) => {
  const [sizeId, value] = item

  // na primeira iteração, sizeId recebe `'asdfi-1asdf032-asdf23'`, e value recebe `10`.
  // na segunda iteração, sizeId recebe 'lkjfef-320fsdj0-fsdlkjf', e value recebe `20`.
  // e na terceira e última iteração, sizeId recebe 'liesa-30saef0-adsfle', e value recebe `30`.
})
```

A única diferença do código acima para o que eu fiz, foi que, no código da aula, eu fiz o destructuring direto no parâmetro da função passada para o `map`. O invés de passar o `item`, e fazer o destruturing dentro do `map`, criando variáveis com `const`, eu fiz direto no parâmetro:

```js
const result = pizzasValues.map(([sizeId, value]) => {
  // ...
})
```

Deu pra entender a ideia? :)

**Comment by pamplonapaulo** [comment]
Mestre @fdaciuk , muito boa a explicação! Super grato.

O destructuring da aula de transactions no Firebase também é muito louco!! kkk Eu quase trouxe pra cá mas assistindo de novo consegui entender. Sensacional esse recurso.

**Comment by fdaciuk** [comment]
Sim! Ainda tem o caso de você conseguir fazer destructuring de uma propriedade dinâmica, mas que não pode ser criada uma variável com o nome da propriedade, aí a gente precisar renomear ela :)

mas que bom que ficou claro! Qualquer dúvida, só avisar :D

**Comment by pamplonapaulo** [comment]
Que foi exatamente o que você fez nessa aula do transactions, né @fdaciuk ?

Eu também fiquei testando para ver se funcionava sem o [ ]  em volta da id, mas daí não consegue pegar. As [ ] são sintaxe de seletor de propriedade de objeto, né?

**Comment by fdaciuk** [comment]
Isso, foi o que eu mostrei na aula de transactions :)

Na verdade eu já tinha mostrado essa feature no módulo 2, no Editor de Markdown :)

> Eu também fiquei testando para ver se funcionava sem o [ ] em volta da id, mas daí não consegue pegar. As [ ] são sintaxe de seletor de propriedade de objeto, né?

Quando vamos nomear uma propriedade de um objeto, onde o nome dessa propriedade precisa ser dinâmico (vêm de uma variável, por exemplo), aí nós podemos usar os colchetes na definição do objeto, ou na desestruturação, dando um nome para essa propriedade. Seria algo similar a isso:

```js
const id = 'abc'

// Criando um objeto com a propriedade "abc" usando ES5:
var obj = {}
obj[id] = 123

// Criando com a nova feature "Dynamic Object Key":
const obj = {
  [id]: 123
}

// Fazendo destructuring da maneira padrão:
const {  abc } = obj

// Fazendo destructuring e renomeando a propriedade:
const { [id]: novaVarAbc } = obj
```

Veja o último exemplo: na desestruturação, é sempre obrigatório dar um nome para a propriedade dinâmica, ainda que o nome seja válido para nomes de variáveis. Isso aqui, por exemplo, daria um erro:

```js
const { [id] } = obj
```

Deu pra entender? :)

**Comment by pamplonapaulo** [comment]
Sensacional! Muito grato por essa super aula!! :)

**Comment by fdaciuk** [comment]
Qualquer coisa grita ae :)
