### ISSUE TITLE
Dúvida a respeito de setar um estado. 

### ISSUE THREAD

**Issue by arrudacaio** [da2k/curso-reactjs-ninja#507]
Prof, minha dúvida creio que seja bem besta, mas ficou na cabeça kkk. 
Então, qual das duas formas é a correta ? 
```
<button onClick={() => setCount(count + 1 )}>+</button>
// ou 
<button onClick={() => setCount(count => count + 1 )}>+</button>
```
existe alguma diferença em utilizar a arrow function para setar o estado do contador ? 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @arrudacaio! Sempre que você depender do estado anterior para definir o novo estado, use a função :) 

Nesse seu exemplo, você quer pegar o valor anterior de `count` e somar 1. Como você depende do valor anterior para conseguir somar 1, aí você usa a função.

Leve sempre essa regra que não tem erro :)

Como funções de `setState` são assíncronas, pode acontecer de, em algum momento, você estar setando o novo valor fora do escopo principal do seu componente de função.

Quando isso acontece, não dá pra ter certeza que você vai ter em `count`, que foi definido no corpo da função, o valor mais atualizado do estado.

Por isso usamos a função: como o React é quem manipula o estado, ele vai sempre ter o valor mais atualizado para nos passar, e nós comseguimos pegar esse valor mais atual da variável usando a sintaxe de função ao definir um novo estado :)

Ficou claro? :)

**Comment by arrudacaio** [comment]
perfeitamente claro!

**Comment by fdaciuk** [comment]
Perfeito! Qualquer coisa, só avisar :)
