### ISSUE TITLE
Fluxo de assinatura

### ISSUE THREAD

**Issue by geniton** [da2k/curso-reactjs-ninja#508]
Fala daciuk, 

blz mano?

cara, eu to refazendo um fluxo de assinatura aqui que contém 9 steps, 

![image](https://user-images.githubusercontent.com/38032416/89952932-86eed380-dc04-11ea-965a-a3963cdca1d3.png)
cada step desse ai é um component que é um form e o form é um component FormValidation, nele eu puxo todos os campos e faço as validações.

![image](https://user-images.githubusercontent.com/38032416/89953087-d33a1380-dc04-11ea-8e38-afe57cea30d8.png)
![image](https://user-images.githubusercontent.com/38032416/89953247-14cabe80-dc05-11ea-9589-fe46170baa59.png)
![image](https://user-images.githubusercontent.com/38032416/89954331-40e73f00-dc07-11ea-8c6e-576980eebd9d.png)

e retorno sempre 1 objeto com esses 2 caras aqui -> isValid e formError. caso os campos estejam invalidos o "isValid" vai ser false e o formError vai conter todos os campos invalidos, caso contrario isValid é true, e ai eu avanço de step de forma horizontal.

só que agora eu preciso deixar esse fluxo de forma vertical, de acordo com o avanço, eu vou exibindo mais steps abaixo.

minha dúvida é o seguinte, caso o usuario chegue na parte final e volte la em cima pra editar algum campo, como eu conseguiria validar todos os campos do step, se minha validação é apenas no submit do form? eu pensei em até colocar todos dentro de 1 form, pq ai ficaria até mais facil de validar.

mas como o form é um pouco grande e complexo, eu acho que ficaria até mais organizado deixar dessa forma msm, cada um com o seu form, mas ai eu nao sei como eu faria para validar todos os campos do form.

é possivel?

valeu mano! <3

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @geniton! Deixa eu ver se entendi: você está usando um `form` para cada step, correto? Se sim, você consegue validar os campos de cada step isoladamente, não?

Assim não vai acontecer do usuário estar no último passo, e ter que voltar lá no primeiro porque faltou alguma coisa.

Isso funciona pra você?

**Comment by geniton** [comment]
Mal mano, me expressei errado agora que eu vi haha.

Consigo sim, na verdade estou fazendo isso,  é que quando ele passa de step eu tiro o botão submit do form e exibo o proximo step e assim adiante, só que quando ele chega no ultimo step vai ter um botão de concluir assinatura, ai eu queria saber como eu faria pra validar, se caso ele volte no step anterior e edite algo, pq no momento eu só faço a validação no submit do form.

será que teria algum jeito de eu validar isso, chamando o submit do form, algo desse tipo? haha

ou eu teria que criar alguma func com o evento onChange e fazer essa validação?

**Comment by fdaciuk** [comment]
Acho que saquei haha :D
Vamos lá: o que eu faria nesse caso: você pode ter um componente só de form, sem problema algum, ou pode ter vários forms. Tudo vai depender de como o seu backend espera essas informações. 

Pelo que entendi, você precisa enviar tudo de uma vez só, mas validar por etapas, certo?
Se for isso, o que eu te recomendaria é: crie o formulário com uma Context, e vá salvando os dados de cada step ali. Assim você consegue validar por etapas os valores de cada campo.

Ao final, você já vai estar com todos os dados guardados no estado da Context, e validados conforme cada step passado. Então só vai precisar submeter o form.

Entendi certo? :)

**Comment by geniton** [comment]
Isso mesmo mano.

mas se no caso o usuario ele editar algum campo dos steps anteriores? eu to falando isso pq ele vai ter a visibilidade de todos os steps e vai poder editar.

como eu faria pra validar novamente?

**Comment by fdaciuk** [comment]
Aí depende de como vai ser o layout disso. Cada step já preenchido fica sempre aberto?

**Comment by geniton** [comment]
Isso

**Comment by fdaciuk** [comment]
Nesse caso, tem algumas formas de resolver: 
- vc pode criar componentes controlados e validar no change de cada campo;
- vc pode usar o evento onBlur, e validar o campo quando esse perder o foco;
- ou vc pode validar tudo no final mesmo, e usar um `ref` para pegar a posição do primeiro campo com problema e "rolar" até lá, quando tentar submeter o formulário e algum campo for inválido :)

**Comment by geniton** [comment]
Boa mano, é que quando o usuario digita no formulario, eu nao faço nenhuma validação com o onChange rs, só quando ele tenta avançar.

Mas boa mano, é isso mesmo.

Com o seu nitro agora, dá pra resolver isso facil. kkk

Valeu fdaciuk.

Um grande abraço mano!

**Comment by fdaciuk** [comment]
Massa! Qualquer dúvida, avisa aí :)
