### ISSUE TITLE
Como alterar estado em componente diferente

### ISSUE THREAD

**Issue by Andreporto1** [da2k/curso-reactjs-ninja#509]
Boa noite, 
Para eu alterar o estado de um componente através de um botão que está em um componente diferente é necessário usar o Redux? Por exemplo em uma loja em que o estado está no componente carrinho e o botão adicionar está no card do produto.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Andreporto1! Não precisa necessariamente do Redux não. Isso eu mostro ainda no módulo 1, nos fundamentos do React: todo dado no React é passado de forma unidirecional, sempre de cima pra baixo, do pai para o filho.

Então, quando você precisa executar uma ação em um componente, e o estado pertence a outro componente, esse estado precisa ser compartilhado de cima pra baixo (tanto o estado como a função que altera o estado).

Imagine que o exemplo que você comentou, sobre a loja, seja representado pelo seguinte JSX:

```jsx
const Store = () => {
  return (
    <div>
      <Product />
      <Cart />
    </div>
  )
}
```

Não tem como `Cart` saber o que acontece em `Product`, pois são componentes independentes. Nesse caso, para que seja possível eles conversarem, o estado precisa estar, no mínimo, um componente acima dos dois. Nesse exemplo, temos o componente `Store`, que contém os dois. 

Então você pode criar um estado nesse componente `Store`, e a função que altera esse estado também nesse componente.

Aí você só passa via props o estado para o componente `Cart`, e a função que altera o estado, vc passa via props para `Product`, que vai executar a função com o clique de um botão, por exemplo :)

Deu pra entender a ideia? :)

**Comment by fdaciuk** [comment]
OI @Andreporto1! Vou fechar a issue, mas se você ainda tiver dúvidas, fique à vontade para perguntar :)
