### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#51]
Professor, sobre o modulo#04 que vai ser sobre o react-router, vai demorar muito pra sair ? porque não é com essa lib que se faz as SPA ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CheeseFlan! Isso mesmo, você pode usar o react-router para navegação no frontend, para SPA. Não é obrigatório, mas ele facilita bastante as coisas =)

Sobre quando vai sair, ainda não tem data definida. O curso está em andamento, então primeiro vamos terminar o módulo `#03` para depois começar o `#04` =)

**Comment by CheeseFlan** [comment]
Blz obrigado pelos esclarecimentos, agora não sabia que dava pra fazer a navegação sem o uso do router, interessante :+1:

**Comment by fdaciuk** [comment]
Pois é! É aquele negócio: o React é só uma lib, então você se adapta a sua aplicação. O react-router usa a _history api_ do HTML5 por baixo dos panos, então você pode usar essa API no lugar do react-router.

Claro que vai ter mais trabalho pra ficar manipulando as rotas na mão, mas o react-router não faz mágica, ele usa uma tecnologia existente e independente do React :)

**Comment by CheeseFlan** [comment]
Muito bom, só uma ultima duvida, a frequência das aulas são postadas, é por semana ou só são postadas quando o modulo esta completo ?

**Comment by fdaciuk** [comment]
Escolheu mesmo :D 

As aulas são postadas semanalmente! Uma pena que a Udemy não avisa quando tem aulas novas, mas toda segunda-feira pela manhã eu libero algumas aulas :D

**Comment by CheeseFlan** [comment]
Vlw professor, obrigado ai pela atenção também sei que estou perguntando muito, mas queria esclarecer todas as minha duvidas, mas sem duvida valeu cada centavo o curso, é bastante abrangente e de ótima qualidade, tanto das aulas quanto da sua ajuda :D

**Comment by fdaciuk** [comment]
Relaxa cara! Essa área é pra tirar dúvidas mesmo! A ideia do curso é essa: te preparar para usar a ferramenta da melhor forma possível no seu dia a dia. E não tem como fazer isso se você tiver com dúvidas, então pode abrir issue sempre que achar necessário, ok? =)

Fico muito feliz em saber que está curtindo o curso :heart: 

E conte comigo para o que precisar :D
