### ISSUE TITLE
[M1A03] Versão do React

### ISSUE THREAD

**Issue by Matheusluz** [da2k/curso-reactjs-ninja#510]
Tudo bom @fdaciuk, adquiri agora o curso e percebi que no inicio do teu curso você está utilizando o react 15.1.0
Porém nós já estamos na versão 16.3.1, isso pode ser um problema?
No caso suas aulas não estarão desatualizadas?

Também gostaria de entender sobre o create-react-class, isso será abordado mais a frente em suas aulas?

@fdaciuk

**Comment by Matheusluz** [comment]
E também qual seria a diferença entre **CJS** e **UMD** dos links que tem disponível.

https://cdnjs.cloudflare.com/ajax/libs/react/16.13.1/cjs/react.development.js
https://cdnjs.cloudflare.com/ajax/libs/react/16.13.1/umd/react.development.js

**Comment by fdaciuk** [comment]
Oi @Matheusluz! Em breve eu devo atualizar os primeiros módulos, para mostrar desde o início as novidades que o React vêm lançando. Mas com a v15 vc não perde nada: tudo o que você vai usar na v16, eu mostro na v15, então pode ficar tranquilo :) 

No módulo 4 eu já mostrei algumas das novidades da v16, então não se preocupe que o curso não vai ficar parado, e você vai receber todos os updates quando eu liberar :) 

Sobre o `create-react-class`, ele só deve ser usado se você estiver usando a versão mais recente do React, mas não quiser usar ES6+.

Seguindo como eu mostrei no curso, você vai vendo a evolução aos poucos, saindo do ES5 e indo para o ES6, com ES Modules, e algumas outras novidades do JavaScript que eu mostro no decorrer do curso :)

Sobre as versões do React no cdnjs, pode usar a versão UMD. A versão CJS serve apenas se você estiver usando SSR no Node.js. A versão UMD é a versão universal para funcionar tanto em navegadores quanto no Node.js, quando necessário :)

Então pode pegar a versão UMD :)

Se quiser saber mais sobre a diferença desses sistemas de módulos (que foram criados antes do ES Modules ser lançado), eu escrevi alguns posts sobre o assunto:

https://blog.da2k.com.br/2015/01/03/como-criar-componentes-js-usando-modulos-amd-commonjs-e-umd-parte-1-3/
https://blog.da2k.com.br/2015/01/04/como-criar-componentes-js-usando-modulos-amd-commonjs-e-umd-parte-2-3/
https://blog.da2k.com.br/2015/01/05/como-criar-componentes-js-usando-modulos-amd-commonjs-e-umd-parte-3-3/
https://blog.da2k.com.br/2019/02/25/ecmascript-modules-modulos-nativos-no-javascript/

**Comment by Matheusluz** [comment]
Maravilha! Irei ler seus posts.
Muito obrigado.

**Comment by fdaciuk** [comment]
E qualquer dúvida, fique muito à vontade para perguntar. Estou aqui pra te ajudar no que precisar :D

**Comment by SallesCosta** [comment]
bom dia.. posso aproveitar a issue closed?
Atualmente no cdn não há react-dom sem ser min.
https://cdnjs.com/libraries/react-dom
seja umd ou cjs. 
Se nao tiver problema.. ok.. ou se tiver alguma recomendação específica.. eu agradeço!

**Comment by fdaciuk** [comment]
Oi @SallesCosta! Não tem problema, pode usar a versão minificada sim! =)
