### ISSUE TITLE
[M4#A59] Indicar se deseja enviar um cookie em uma solicitação entre sites especificando seu atributo SameSite

### ISSUE THREAD

**Issue by edsonborge** [da2k/curso-reactjs-ninja#511]
Fala Daciuk,
No momento em que eu clico no botão Entrar com Github ele aparece esse erro, no caso eu não sei onde faz essa configuração dos cookies para ele aparecer o dado do usuário e o botão de sair.
![image](https://user-images.githubusercontent.com/17258402/93608862-81be3a80-f9a1-11ea-93ef-6dd0740e712f.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @edsonborge! Pode ficar tranquilo que isso é configuração que deve ser feita do lado do Firebase. Não precisa você fazer nada :)

**Comment by edsonborge** [comment]
Então, mesmo ele não exibindo esse trecho de código?
```
{isUserLoggedIn && (
  <>
    <pre>{user.displayName}</pre>
      <Button variant='contained' onClick={this.handleLogout}>
        Sair
      </Button>
    </>
)}
```
No caso ele só fica na tela inicial e não mostra o nome do usuário.

**Comment by fdaciuk** [comment]
Aí eu preciso ver todo o seu código e colocar pra rodar aqui pra entender :)
Consegue subir em um repo aqui no GitHub?

**Comment by edsonborge** [comment]
Tem sim, eu subi ele no meu GitHub:
[https://github.com/edsonborge/reactzzaria](url)

**Comment by fdaciuk** [comment]
O problema é nessa linha aqui:
https://github.com/edsonborge/reactzzaria/blob/master/sistema-pedidos/src/pages/login/index.js#L53

Você usou `this.setState` ao invés de `this.state` :)

**Comment by edsonborge** [comment]
Agora deu certo! faltou atenção minha... haha
Obrigado pela força!!!

**Comment by fdaciuk** [comment]
Sem problemas meu caro :) 
Qualquer dúvida, só avisar :D
