### ISSUE TITLE
[M4#A45] Arquitetura da aplicação: rotas iniciais

### ISSUE THREAD

**Issue by felipecesr** [da2k/curso-reactjs-ninja#512]
Fala Daciuk,

Na aula você criou um arquivo com o componente:

```
// login.js
function Login () {
  ...
}

export default Login
```

E depois criou um outro arquivo só pra reexportar:

```
// index.js
export { default as Login } from './login'
```

Qual a vantagem de exportar os componentes dessa forma? Por quê não criar só o `index.js` e exportar assim, por exemplo:
`export function Login`

@fdaciuk

**Comment by fdaciuk** [comment]
Quando você tem muitos `index.js` abertos, dependendo do editor, você pode se perder na organização dos arquivos. Só por isso :)

**Comment by felipecesr** [comment]
Ah sim, valeu!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
