### ISSUE TITLE
Problema a partir da aula 49 não renderiza nada no localhost:3000

### ISSUE THREAD

**Issue by lucasoliveiraprofissional** [da2k/curso-reactjs-ninja#514]
Não tenho experiencia com React, está dando um erro que creio que não foi abordado. Aula 49 já deu esse erro.
Não aparece nada quando vou em localhost:3000 no browser, apenas no inspecionar elemento vejo esse erro:

E não consigo deixar identado a parte do render do AppContent no app.js, ele fala que o fechamento da tag precisa estar identado na coluna 12 o fechamento da tag, mas não dá pra identar na 12, ou é 11 ou é 13.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucasoliveiraprofissional! Qual erro você teve? Consegue subir seu projeto em um repositório aqui no GitHub e postar aqui o link pra eu dar uma olhada?

**Comment by lucasoliveiraprofissional** [comment]
Eu digitei no formato do Issue o erro que acontecia, mas creio que não apareceu pra vc, sem problemas. Não aparece nada na tela, fica tudo em branco o localhost. No Console no browser aparecem alguns erros. Eu criei o repositório aqui no Git, não consegui criar as subpastas dist e src e as subpastas delas, porém consegui colocar todos os arquivos do meu projeto. No repositório eu coloquei um arquivo de texto com o link dos prints de erro do localhost que eu compartilho via Google Drive. Segue o link: https://github.com/lucasoliveiraprofissional/Curso-React-Udemy/ . Muito obrigado!

**Comment by fdaciuk** [comment]
Ah, é que você colocou o código dentro do conteúdo comentado :)

Quando for assim, coloque o código seguindo o fluxo do seu texto mesmo, ok? :)

Vou dar uma olhada no seu projeto, e já te retorno :)

**Comment by fdaciuk** [comment]
@lucasoliveiraprofissional consegue deixar as imagens que estão lá no drive públicas?

**Comment by fdaciuk** [comment]
OI @lucasoliveiraprofissional! Vou fechar a issue, mas se você ainda tiver dúvidas, fique à vontade para perguntar :)
