### ISSUE TITLE
m3#a29 - Problema ao rodar 'yarn test:watch'

### ISSUE THREAD

**Issue by luidyvcc** [da2k/curso-reactjs-ninja#515]
Estou tendo problema ao rodar o comando 'yarn test:watch'. Você pode me ajudar nisso?

`$ yarn test:watch
 FAIL  src\redux-flow\reducers\todos\todos.test.js
  ● Test suite failed to run

    C:\Users\Ancos28\Documents\Cursos\Udemy\react-ninja\005-modulo-03\samples\14-todo-list\src\redux-flow\reducers\todos\todos.test.js:3
    import { expect } from 'chai'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at new Script (vm.js:84:7)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)`

**Comment by fdaciuk** [comment]
Oi @luidyvcc! Sempre que abrir uma issue, não remova a marcação do meu usuário `@fdaciuk`, senão eu não recebo notificação da sua dúvida :)

Posso te ajudar sim, vamos lá :D 

Bom, pelo erro, parece que faltou a configuração do webpack para o Jest. Você usou o Create React App para criar seu app?
Se não usou, recomendo usar ele, pois ele já vem com todas as configurações necessárias, inclusive para testes com Jest :)

**Comment by luidyvcc** [comment]
@fdaciuk Então, eu não criei do zero, eu peguei do seu repositório e tentei rodar.

**Comment by fdaciuk** [comment]
@luidyvcc pode usar o CRA, que ele já tem o Jest configurado e funcionando certinho.. como algumas dependências receberam atualizações, o boilerplate acabou parando de funcionar.. para atualizar ele, ficaria muito parecido com o que está sendo feito no Create React App, então estou recomendando usar direto o CRA, que vai ser mais simples :)
