### ISSUE TITLE
Convite + ajuda

### ISSUE THREAD

**Issue by Matheusluz** [da2k/curso-reactjs-ninja#516]
Boa tarde @fdaciuk.

O objetivo de eu ter comprado o curso, é que na empresa em que trabalho decidimos migrar o front do nosso sistema para React.
E nesse momento surgiu a oportunidade de acelerarmos o início dessa migração.

Como no nosso time não temos nenhum profissional especializado em React gostaria de saber se você não indicaria alguma empresa que realize essa terceirização.
Ou se até mesmo você possui o interesse.

**Comment by fdaciuk** [comment]
OI @Matheusluz! Que legal! :D
Infelizmente, no momento eu não consigo dar esse tipo de consultoria, mas posso te recomendar alguns grupos onde você deve conseguir achar alguém que possa te ajudar com isso:

[Telegram do React Brasil](https://t.me/reactjs_br)
[Slack do React Brasil](https://react.now.sh/)

Nos dois canais têm vários profissionais que trabalham com React no dia a dia, talvez ali você encontre alguém que possa te ajudar com essa demanda :)

**Comment by Matheusluz** [comment]
Muito obrigado @fdaciuk!

**Comment by fdaciuk** [comment]
Nada :)
Qualquer coisa, só avisar :)
