### ISSUE TITLE
Onde estão os desafios

### ISSUE THREAD

**Issue by carlosedlucas** [da2k/curso-reactjs-ninja#517]
Boa tarde, tudo bem? 
Onde encontro os desafios?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @carlosedlucas! Todos os códigos mostrados no curso estão dentro do diretório `examples`, separados por módulo :) 
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples

**Comment by carlosedlucas** [comment]
Obrigado!

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :)
