### ISSUE TITLE
[M1A01] - Retomando o curso

### ISSUE THREAD

**Issue by MarceloMileo** [da2k/curso-reactjs-ninja#518]
Fala Fernando, tudo tranquilo?
Cara, seguinte, eu to retomando o curso e vi que, pelo menos nas primeiras aulas, você usa a versão 15 do React e eu gostaria de saber se tem algum impacto se eu usar a 17, e pretendo usar essa versão em um novo projeto no meu trabalho.
Inclusive estou voltando com o curso pq preciso muito consolidar meus conhecimentos de React, Js, etc.
Grande abraço.
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @MarceloMileo! A v17 do React veio sem breaking changes. Ela foi criada apenas com mudanças internas na lib, que não afetam a interface externa que a gente usa :)

A ideia dessa v17 é facilitar a migração de projetos para as próximas versões, por isso lançaram sem mudanças na interface :)

na v15.5 algumas coisas mudaram da v15, mas eu abordo isso no curso, então pode seguir sem medo :) 

No módulo 4 eu já mostro as novidades da v16 (Hooks, nova Context API, Suspense, etc), então você estará bem coberto :) 

E em breve eu devo atualizar os primeiros módulos para iniciar já na versão mais recente do React.

De qualquer forma, se você tiver qualquer dúvida ou problema, só abrir issue aqui que eu vou te ajudando, ok? :)

**Comment by MarceloMileo** [comment]
@fdaciuk , opa, obrigado pela resposta rápida meu velho.
Como é comum na nossa profissão, to trocando o motor do avião com ele voando...hahahahahaha
Grande abraço.

**Comment by fdaciuk** [comment]
haha! Sem crise :) 
Conte comigo para o que precisar :)
