### ISSUE TITLE
Aula 19 da Seção 3:Módulo #01 - Parte 2

### ISSUE THREAD

**Issue by Gigleydson** [da2k/curso-reactjs-ninja#519]
Olá professor Daciuk, tudo bem?

Estou com um pequeno problema na Aula 19 da Seção 3:Módulo 01 - Parte 2.
Eu pulei as aulas de configuração de webpack e estou utilizando create-react-app e a estrutura que ele gera do React é bem diferente do que você está ensinando nessa aula.
Enquanto você utiliza:

```
const Title = React.createClass ({})...

```
Ele passa como função, dessa forma:

```
import React from 'react';

function Title() {
    return (
    <h1>Olá {this.props}!</h1>
  );
}

export default Title;
```

O problema é que quando vou utilizar o this.props, ele apresenta o seguinte erro:
TypeError: Cannot read property 'props' of undefined

Poderia me ajudar?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Gigleydson! Eu vou falar sobre componentes de função um pouco mais pra frente :) 
Mas pode continuar usando o Create React App sem problemas! Só pra você conseguir acompanhar com essa parte do `createClass`, você pode fazer uma das duas coisas:
- Ou você instala o React na versão v15.4, com o comando `npm i --save react@15.4 react-dom@15.4`;
- Ou então você deixa como está, e instala a biblioteca [`create-react-class`](https://www.npmjs.com/package/create-react-class), com o comando: 

```
npm i --save create-react-class
```

O `createClass` foi separado da biblioteca principal do React na versão 16, então você pode instalar essa biblioteca só para conseguir seguir com essa parte onde eu falo do `createClass`, beleza? :)

Só lembrando que essa parte do curso é só pra explicar os conceitos mais básicos. No decorrer do curso, nós vamos usar mais componentes de função simples mesmo :)

Me deixe saber se deu certo, e fique à vontade para perguntar sempre que tiver dúvidas :)

**Comment by Gigleydson** [comment]
Imaginei que mais para frente essas dúvidas seriam sanadas. Mas eu fiquei curioso para saber como poderia resolver o problema.
Tentei instalar o createClass como você recomendou mas não deu certo. 
Vou continuar as aulas prestando atenção e deixando para praticar quando der para acompanhar utilizando o create-react-app.

Muito obrigado pelo rápido retorno.

**Comment by fdaciuk** [comment]
Como você fez pra usar o `create-react-class`? Se você tentou usando `React.createClass` não vai funcionar. Tem que importar ele no seu arquivo onde você vai usar:

```js
import React from 'react
import createClass from 'create-react-class'

const Title = createClass({ ... })
```

Isso aqui é pra funcionar :)

**Comment by Gigleydson** [comment]
Perfeito professor! :)

Meu App.js
```
import Title from './Title.js';

function App() {
  return (
    <div>
      <Title name='Gigleydson' />
    </div>
  );
}

export default App;

```

E meu Title.js

```
import createClass from 'create-react-class';

const Title = createClass({
  render: function () {
    return (
    <h1>Olá {this.props.name}!</h1>
    )
  }
})

export default Title;

```

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :)
