### ISSUE TITLE
M2A#08

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#52]
Professor o comando `npm run test:watch` esta falhando e ocorrendo o seguinte erro.
![erro](https://user-images.githubusercontent.com/17899474/30550028-b0c541ce-9c6c-11e7-84f0-db0bfa8b7eb2.png)

@fdaciuk

**Comment by CheeseFlan** [comment]
Opa, dei uma pesquisada aqui e descobri que esse é um bug que ta ocorrendo na versão mais recente, então instalei uma versão do vídeo e funcionou só que esta dando o seguinte erro.
![error](https://user-images.githubusercontent.com/17899474/30551446-d6497f9c-9c70-11e7-88bd-056cf049e1b8.png)

**Comment by fdaciuk** [comment]
Me mostra o código do teste, por favor =)

**Comment by CheeseFlan** [comment]
```
import { expect } from 'chai'
import sum from './sum'

it('sum should be a function', () => {
    expect(sum).to.be.a('function')
})

it('sum(1, 2) should return 3', () => {
    expect(sum(1, 2)).to.be.equal(3)
})
```
aqui esta o código do test, eu finalizei a aula mesmo sem o watch.

**Comment by fdaciuk** [comment]
Acho que entendi! Tem como subir o projeto no GitHub pra eu dar uma olhada? Assim fica mais fácil pontuar o que precisa alterar =)

**Comment by CheeseFlan** [comment]
Pronto aqui esta o link [meu repositório](https://github.com/CheeseFlan/jest-tdd), não coloquei o readme.

**Comment by fdaciuk** [comment]
Bom, se o `npm test` roda, tenta colocar o comando completo no `test:watch`:

```
```

**Comment by CheeseFlan** [comment]
Funcionou !!! :+1:

**Comment by fdaciuk** [comment]
O comando que "passa" parâmetros pra frente (o `--`) é pra bases unix, então provavelmente é por isso que não funciona no windows =)

Talvez no bash do Ubuntu dentro do windows 10 funcione, mas não tenho como testar =)

**Comment by CheeseFlan** [comment]
Tranquilo, obrigado por tirar a duvida, se no curso aparecer outro comando do `--` , eu já faço desse jeito que foi explicado agora :+1:

**Comment by fdaciuk** [comment]
Isso ae :D 
Qualquer coisa avisa ae :D
