### ISSUE TITLE
MRW#09 - Funcionamento do hot loader

### ISSUE THREAD

**Issue by MarceloMileo** [da2k/curso-reactjs-ninja#520]
Grande Felipe, tudo tranquilo?

Cara, eu estou com um probleminha no hot loader, tem momentos que ele não funciona e tenho que atualizar o browser mas não da nenhum erro aparente, é normal isso?
@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae meu caro! Tudo ótimo, e vc? :) 

Cara, pior qie é normal sim.. à vezes ele se perde, e é preciso fazer um reload manual no navegador xD

**Comment by MarceloMileo** [comment]
Ah, então está tranquilo.
Valeu meu velho, abração.

**Comment by fdaciuk** [comment]
Qualquer dúvida, fique à vontade para perguntar :)

**Comment by MarceloMileo** [comment]
Felipe, só um adendo que pode ser interessante você comentar com outros alunos sobre esse problema, eu uso o auto-save do VSCode e reparei que ele esta com 1000 miliseconds de delay oque faz com que ele salve o código muito rápido e consequentemente com erros de syntax e o hot loader se embanana com isso. Eu aumentei para 5000 miliseconds e melhorou muito essa questão.

**Comment by fdaciuk** [comment]
Legal, bom saber :) 

Ah, meu nome é Fernando 😂

**Comment by MarceloMileo** [comment]
Putz....hahahahahahahah, foi mal Fernando, a cabeça ta a milhão.....hahahahahaha

**Comment by fdaciuk** [comment]
haha! Relaxa mano kkk
