### ISSUE TITLE
atualizacão do redux

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#521]
fala daciuk. vi que você atualizou os videos do modulo 4 com o hooks, queria saber se vocês atualizou o dos redux também?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! Eu ainda não fiz as atualizações no curso. O módulo 4 tá atualizado, mas seguindo no "fluxo natural" :)

Agora eu vou atualizar os dois primeiros módulos, e talvez o de Redux mais pra frente :)
