### ISSUE TITLE
Teste tdd mudando o valor do useState

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#523]
Usando a arquitetura do curso onde os states ficam dentro da pasta context seria possível testar a mudança de um state?

Por exemplo:
Tenho um useState que salva a marca da aplicação e a mudança desse state é através do sessionStorage quando a aplicação esta sendo inicializada; 

Ai queria mudar o valor default do useState de xpto para da2k e ver se refletiu no componente

Exemplo de código
```
**Context**
function BrandProvider () {
  const [brand, setBrand] = useState('xpto');
}

**Componente**
const Title = () => {
  const { brand } = useBrand();

  return (
    <Title>Você esta na marca ${brand}</Title>
  )
}


```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @hjdesigner! A ideia seria a mesma de testar os estados de um componente sem a Context: na hora de montar o componente para testar, envolva ele com a Context e pronto :)

**Comment by hjdesigner** [comment]
Mais eu conseguiria mudar o valor de brand na hora que eu envolvo o componente com o Context?

**Comment by fdaciuk** [comment]
Deveria.. você está usando o que pra testar? React Testing Library?

**Comment by hjdesigner** [comment]
Estou utilizando o Enzyme, mais posso mudar para o React Testing Library

**Comment by fdaciuk** [comment]
O Testing Library tem melhor suporte para Hooks, melhor usar ele :)

**Comment by hjdesigner** [comment]
Teria um exemplo, pois todo exemplo que estou achando no google tem algum evento de botão que altera o state.

**Comment by fdaciuk** [comment]
A [documentação](https://testing-library.com/docs/react-testing-library/example-intro) é o melhor caminho para começar. Mas normalmente vai ser isso mesmo: você vai testar contra alguma ação do usuário (um clique de botão, por exemplo), pra ver se o estado mudou, e sua interface respondeu como esperado, saca?

O que você estava tentando fazer?

**Comment by hjdesigner** [comment]
Entendi, no meu caso ele altera o valor conforme o valor dentro sessionStorage do browser.
Os states que mudar o valor através de clique eu conseguir testar de boa.
Achei que dava para fazer alguma coisa assim  <BrandProvider valueInitial="xpto"><Button>Generate Report</Button></BrandProvider>

**Comment by fdaciuk** [comment]
Nesse caso você teria que mockar o sessionStorage para conseguir testar o que precisa, já que o testing-library roda no terminal, ele precisa do Node.js, que não tem o objeto `window` pra você usar coisas do browser.

Mas como é JavaScript, em teoria é fácil resolver: dá uma olhada [nesse artigo](https://medium.com/javascript-in-plain-english/testing-local-storage-with-testing-library-580f74e8805b). 

Ele deve te dar uma luz pra ajudar a resolver seu problema :)

**Comment by fdaciuk** [comment]
@hjdesigner conseguiu resolver? Vou fechar a issue, mas se você ainda estiver com problemas, só avisar :)

**Comment by hjdesigner** [comment]
Conseguir resolver ontem a noite, eu utilizei o window.sessionStorage.setItem('session', '{"theme":"xpto"}'); nos teste para conseguir testar o cenários que o componente muda conforme o valor da sessionStorage.

Muito obrigado pela ajudar :)

**Comment by fdaciuk** [comment]
Boa! Que bom que deu certo :) 
Qualquer coisa, grita ae :)
