### ISSUE TITLE
Centralizaçao incorreta

### ISSUE THREAD

**Issue by thiagohora** [da2k/curso-reactjs-ninja#53]
Olá 

fui fazer um teste no componente de paginação, e quando eu coloco por exemplo 8 paginas visíveis , 16 no total e a pagina ativa 9,  a centralizaçao nao fica balanceada. 
 

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @thiagohora! Então, nesse caso não vai ficar centralizado mesmo, pois pra centralizar, a quantidade de páginas visíveis precisa ser ímpar, que assim a página ativa fica no meio, e fica dividido corretamente o restante nas laterias: se você colocar `7` páginas visíveis, vai ficar a página ativa no centro, e mais 3 pra cada lado :)

**Comment by fdaciuk** [comment]
@thiagohora ficou claro essa parte? Vou fechar a issue, mas se você tiver qualquer dúvida, só avisar que a gente reabre, ok? :D

**Comment by thiagohora** [comment]
Claro, já compreendi sim.
