### ISSUE TITLE
Sobre rescripts do projeto reactzzaria

### ISSUE THREAD

**Issue by renanlimabl** [da2k/curso-reactjs-ninja#530]
Fala professor, comecei a fazer o projeto da pizzaria agora e eu vi em uma aula que você utiliza o rescripts para não precisar ejetar o projeto e ter a vantagem de configurar Babel, eslint, etc...
Eu começando o projeto da pizzaria com create-react-app na versão atual, ainda precisaria utilizar o rescripts? 
Outra pergunta, o eslint pode ser opcional, né?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanlimabl! Nós usamos o rescripts nesse projeto apenas para adicionar o standard como linter sem precisar ejetar, mas com a versão mais recente do CRA, já é possível extender a configuração do linter sem ferramentas externas :) 

Você só vai precisar do rescripts se precisar mexer em alguma configuração do babel ou webpack, por exemplo.

Sobre o uso do eslint ser opcional: sim, ele é opcional, mas eu recomendo fortemente que você **não remova** o ESLint do projeto.

JavaScript é uma linguagem que você tem que programar "na defensiva", por ter tipagem fraca e dinâmica. O linter vai te ajudar a evitar muitos problemas que você teria que ficar se preocupando por conta própria :)

**Comment by renanlimabl** [comment]
@fdaciuk ahhh entendi, faz sentido!!
Obrigadão mestre!

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :)
