### ISSUE TITLE
M4#A169 problema com variáveis de ambiente 

### ISSUE THREAD

**Issue by angelilton** [da2k/curso-reactjs-ninja#531]
fala mestre, estou na aula que vc troca os dados do firebase para varáveis de ambiente. porém eu fiz aqui a minha aplicação fica em loop, então fiz um console.log no firebaseConfig e ele volta tudo undefined.
será que tem alguma coisa na minha configuração que possa estar errada vc se puder dar uma olha por favor (obs: vi que no seu package.json vc esta usando o rescript poderia ser isso)
https://github.com/angelilton/order-pizza-reactJS

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelilton! Você usou `:` para separar chave/valor das suas variáveis de ambiente.. o correto é usar o sinal de igual, desse jeito:

```
CHAVE=valor
```

:)

**Comment by angelilton** [comment]
nossa, foi isso mesmo valeu
