### ISSUE TITLE
Método createClass

### ISSUE THREAD

**Issue by filipeluiz** [da2k/curso-reactjs-ninja#532]
Olá fdaciuk!!!

Instalei com a versão React de acordo documentação e apareceu warnings no console:

> React.createClass is deprecated since React 15.5.0, use the npm module create-react-class instead

então o método createClass foi descontinuado desde React 15.5.0 e a documentação pediu para instalar React 15.4.x?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @filipeluiz! O `createClass` foi apenas separado da lib principal desde a versão 15.5, por isso você está vendo esse warning :) 
Com o passar das aulas, eu mostro todas essas atualizações que acontecem com as próximas versões, então pode seguir exatamente como foi mostrado em aula, instalando sempre as versões mostradas no 
[arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), que você vai conseguir acompanhar tudo sem problemas :)

**Comment by filipeluiz** [comment]
Massa fdaciuk!!! Então ta tudo resolvido, abraço!

**Comment by fdaciuk** [comment]
Show! Fique à vontade para perguntar sempre que tiver dúvidas :)
