### ISSUE TITLE
M4#A80  (Evitando redirects desnecessários)

### ISSUE THREAD

**Issue by renanlimabl** [da2k/curso-reactjs-ninja#534]
Fala Professor, só para eu entender direitin, nessa aula, praticamente criamos um loading entre os redirects, correto?

1º Criamos um estado "[didCheckUserIn, setDidCheckUserIn]" que começa como falso
2º Enquanto o "didCheckUserIn" for false, ele irá mostrar o `<LinearProgress>`
3º Dentro do useEffect , após o firebase.auth().onAuthStateChanged, o "didCheckUserIn" se torna true
4º Ai então, a aplicação segue seu fluxo normal, caindo nos if e elses para fazer redirects se o usuário está logado ou não

Seria isso?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @renanlimabl! É exatamente essa a ideia! Se não fizermos uso do `didCheckUserIn`, veríamos a tela "piscando", dependendo do estado de autenticação do usuário (logado ou não).

Como a ação de checar se o usuário está logado é assíncrona, mas o render dos componentes é síncrono, o render aconteceria sempre antes de saber se o usuário está, de fato, logado ou não!

Então nós mostramos um loading até que tenhamos certeza desse estado para garantir que vamos fazer os próximos redirects corretamente :)

**Comment by renanlimabl** [comment]
Ahh entendi!! Valeu mestrão

**Comment by fdaciuk** [comment]
Qualquer dúvida, grita ae :)
