### ISSUE TITLE
Dúvida instalação rescripts M4#A44

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#536]
Professor fiz a instalação do `rescripts` e toda vez que adiciono algum módulo ou instalo do 0 com o `yarn install` o módulo me faz essa pergunta. Tem alguma solução para isso ?

![image](https://user-images.githubusercontent.com/1054454/113024443-209bce80-915d-11eb-837b-c5c7a171973e.png)

**Inclusive até já coloquei essas dependências no package para ver se a pergunta saia mas não rolou:**
```
"devDependencies": {
    "@rescripts/cli": "0.0.16",
    "@rescripts/rescript-env": "0.0.14",
    "@rescripts/rescript-use-babel-config": "0.0.12",
    "@rescripts/rescript-use-eslint-config": "0.0.11",
    "@rescripts/rescript-use-tslint-config": "0.0.7",
    "babel-eslint": "10.1.0",
    "eslint-config-standard": "16.0.2",
    "eslint-config-standard-jsx": "10.0.0",
    "eslint-config-standard-react": "11.0.1",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "4.3.1",
    "eslint-plugin-react": "7.23.1",
    "snazzy": "9.0.0",
    "standard": "16.0.3"
  }
```

@fdaciuk

**Comment by lucianobarauna** [comment]
@fdaciuk deu certo não.
Segue o repo:
https://github.com/lucianoMeusCursos/ReactNinjaExample/tree/master/my-examples/m04/reactzzaria/sistema-pedidos

**Comment by fdaciuk** [comment]
@lucianobarauna parece que o problema é que alteraram a versão na lib do rescripts das dependências, mas ainda não publicaram elas no NPM:
https://github.com/harrysolovay/rescripts/issues/129

Por isso fica pedindo pra você escolher as versões ali. No caso, pode selecionar as mais recentes mesmo, por enquanto, até que eles subam a nova versão :)

Uma forma de não pedir a versão seria usando o argumento `--non-interactive`, mas aí como a versão correta não vai estar disponível, a instalação não finaliza por conta do erro qeu vai ser disparado. Então, para esse caso específico, o ideal seria escolher a versão mais recente nessa lista que é exibida :)

**Comment by fdaciuk** [comment]
Ou então vc pode somente instalar a versão anterior da `@rescripts/rescript-env`, onde ele não referencia a versão 0.0.12 da lib `@rescripts/rescript-use-eslint-config` :)

**Comment by fdaciuk** [comment]
Mais uma informação importante: no nosso projeto de pizzaria, nós apenas instalamos o rescripts para usar o standard como linter. Houve uma atualização recente no CRA, onde agora ele permite extender a configuração do linter [sem necessidade de ejetar ou de usar uma ferramenta externa](https://create-react-app.dev/docs/setting-up-your-editor/#extending-or-replacing-the-default-eslint-config)! :D

**Comment by fdaciuk** [comment]
Showw! Qualquer coisa, grita ae :D
