### ISSUE TITLE
console.assert não está funcionando 

### ISSUE THREAD

**Issue by joaooliveiradev** [da2k/curso-reactjs-ninja#537]
Boa noite, estou acompanhando as aulas agora em 2021 e senti que tinha uma coisa errada com meu console.assert(), ele não mostrava a linha aonde estava o erro, fui dar uma olhada na [documentação ](https://developer.mozilla.org/pt-BR/docs/Web/API/Console/assert) do mesmo e tinha uma nota falando que o método está sendo implementado de forma diferente em Node Js, parece que ele não interrompe a execução do código subsequente, será que é por causa disso? na nota também fala que é especificamente em navegadores mas no meu caso também está acontecendo quando utilizo o Node no Cmder.

```js
//Arquivo sum.js
'use strict';
function sum() { }
module.exports = sum

```
```js
//Arquivo sum-test.js
'use strict';
const sum = require('./sum');

console.assert(
    typeof sum === 'function',
    'Sum should as function'
);
console.assert(
    sum(1, 2 === 3),
    'Should sum(1,2) return 3'
)
console.log('All test passed!')
```
No momento em que eu rodo os testes, ele deveria parar a execução no segundo assert ali em sum-test.js, visto que meu arquivo sum não tem nenhum return e não vai dar 3. Mas mesmo quando executo ele, ele ainda roda o último console.log.

![erro](https://user-images.githubusercontent.com/44060767/116487198-c7ab7d00-a865-11eb-9624-0e52065f1474.png)

Desde já agradeço o esclarecimento da dúvida, você é o cara.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @joaooliveiradev! Sobre o `console.assert`, é isso mesmo: o comportamento dele foi alterado no Node.js. Eu falei um pouco mais sobre como resolver esse problema [nessa isssue](https://github.com/da2k/curso-reactjs-ninja/issues/443).

Sobre o seu teste que continua passando, na verdade o problema é com a sua sintaxe: você está comparando o `2` com o `3`, e passando o resultado (um valor booleano) como segundo argumento da função `sum`. Veja que sua comparação está dentro dos parênteses da função :)

A comparação precisa ser feita com a chamada da função `sum`, passando os valores `1` e `2`, e então comparando esse resultado com o valor `3`, dessa forma:

```js
sum(1, 2) === 3
```

Isso deve resolver seu problema! Me deixe saber se deu tudo certo :)

**Comment by joaooliveiradev** [comment]
Maravilha, obrigado pela ajuda!

**Comment by fdaciuk** [comment]
Qualquer dúvida, fique à vontade para perguntar :)
