### ISSUE TITLE
Não consigo fazer login. 

### ISSUE THREAD

**Issue by soniamarasa** [da2k/curso-reactjs-ninja#538]
![image](https://user-images.githubusercontent.com/61716037/116766460-0c1f5000-aa01-11eb-82a5-78955829d0f9.png)

Olá professor. Estou com problemas na autenticação. Clico para fazer o login, é feito a autorização no git mas ai da esse erro, dados do usuário continua null e volta para pagina de login. Não sei o que pode ser. Será que alguma coisa mudou em relação ao firebase?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @soniamarasa ! Consegue subir seu código em um repositório aqui no GItHub e mandar o link? Aí eu consigo baixar e testar, para entender o que está acontecendo e te ajudo a resolver, ok? :)

**Comment by soniamarasa** [comment]
Olá professor. Primeiramente desculpa a demora. Tentei achar erros revendo as aulas e comparando meu código com o seu, mas não consegui. Talvez tenha passado batido. Tentei deixar tudo igual mas não sei o que posso ter feito de errado. Segue: https://github.com/soniamarasa/curso-reactjs-ninja/tree/master/reactzzaria

**Comment by fdaciuk** [comment]
Oi @soniamarasa! Com o código parece estar tudo certo. Pode ser alguma configuração do Firebase, ou pode ter sido apenas um problema temporário. Pesquisando por esse erro, algumas pessoas relatam que aconteceu quando o acesso à internet estava intermitente.

Consegue testar novamente só pra ter certeza que não era a conexão? Se o problema continuar, me avise que eu vou tentando te ajudar com a configuração do Firebase.. pode ser alguma coisa do lado de lá, ou só alguma configuração que faltou fazer :D

**Comment by soniamarasa** [comment]
Olá. Eu testei mais de 3 vezes e em dias diferentes... E tenho certeza que não era a conexão :(. Vou fazer outro projeto no firebase, configurar tudo do 0 vendo as aulas novamente. Espero que seja isso, alguma coisinha que acabei deixando de lado, só espero achar a solução. Obrigada, qualquer coisa aviso :)

**Comment by fdaciuk** [comment]
Se quiser eu posso testar com suas chaves! Manda pra mim via mensagem privada na Udemy, só não pra elas não ficarem públicas, que eu testo aqui. Pelo menos a gente consegue confirmar se o problema é com a configuração do Firebase ou não =)

**Comment by fdaciuk** [comment]
Só respondendo aqui pra deixar registrado: conforme conversamos, o problema estava sendo gerado por alguma extensão do Google Chrome. Ao desabilitar as extensões, tudo funcionou como esperado =)
