### ISSUE TITLE
Problemas com o  npm start

### ISSUE THREAD

**Issue by Pedro-Marquardt** [da2k/curso-reactjs-ninja#539]
react-webpack@1.0.0 start c:\desenvolvimento\react-webpack
> node server.js

c:\desenvolvimento\react-webpack\webpack.config.js:24
        new webpack.HotModuleReplacementPlugin()
                    ^

TypeError: Cannot read property 'HotModuleReplacementPlugin' of undefined
    at Object.<anonymous> (c:\desenvolvimento\react-webpack\webpack.config.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\desenvolvimento\react-webpack\server.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-webpack@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pedro Marquardt\AppData\Roaming\npm-cache\_logs\2021-05-06T20_44_10_306Z-debug.log

**Comment by fdaciuk** [comment]
Oi @Pedro-Marquardt! Você chegou a instalar o webpack local, como dependência de desenvolvimento?

> Obs.: Sempre que criar uma nova issue, não apague a marcação no final da mensagem que aparece, senão eu não recebo notificaçãoi da sua dúvida, ok? =)

**Comment by Pedro-Marquardt** [comment]
Olá, eu não me liguei da marcação, peço perdão, mas sim cheguei a instalar
o webpack local

Em qua, 26 de mai de 2021 08:27, Fernando Daciuk ***@***.***>
escreveu:

**Comment by fdaciuk** [comment]
Legal! Nesse caso, você importou o `webpack` no arquivo de configuração? Pelo erro, parece que ele não está no escopo =)

**Comment by Pedro-Marquardt** [comment]
Importei ele no webpack.config.js

Em qua, 26 de mai de 2021 08:39, Fernando Daciuk ***@***.***>
escreveu:

**Comment by fdaciuk** [comment]
Consegue subir seu projeto em um repositório aqui no GitHub? Assim eu consigo baixar aqui para ver o que pode ter acontecido =)

**Comment by Pedro-Marquardt** [comment]
Claro vou subir e te mando o link ^-^

Em qua, 26 de mai de 2021 09:03, Fernando Daciuk ***@***.***>
escreveu:

**Comment by Pedro-Marquardt** [comment]
Opa, deu uns contra tempos aqui só vou conseguir subir bis arquivos de
tarde, peço desculpas hehe, espero que não tenha problemas 😅

Em qua, 26 de mai de 2021 09:12, Pedro Rufino Marquardt <
***@***.***> escreveu:

**Comment by fdaciuk** [comment]
Tranquilo meu caro, faça no seu tempo =)

**Comment by Pedro-Marquardt** [comment]
Olá desculpa a demora, tive que parar com o curso por um tempo, aqui está
meu repositório, se puder dar uma olhada no que não está rodando
agradeceria!

https://github.com/Pedro-Marquardt/ReactWebPack

Em qua., 26 de mai. de 2021 às 14:36, Fernando Daciuk <
***@***.***> escreveu:

**Comment by fdaciuk** [comment]
Oi @Pedro-Marquardt! Eu coloquei pra rodar aqui e funcionou corretamente =)
Tente fazer o seguinte: delete o diretório `node_modules` e o arquivo `package-lock.json`, e então execute `npm install` para instalar todas as dependências novamente.

Depois tente subir novamente o servidor, com `node server.js`. Me deixe saber se funcionou! =)

**Comment by Pedro-Marquardt** [comment]
Opa, tudo bem?
fiz aqui e não foi ele reclama do babel-core



Em sáb, 10 de jul de 2021 17:05, Fernando Daciuk ***@***.***>
escreveu:

**Comment by Pedro-Marquardt** [comment]
Opa, atualizando consegui aqui!!


Em sáb., 10 de jul. de 2021 às 17:24, Pedro Rufino Marquardt <
***@***.***> escreveu:

**Comment by fdaciuk** [comment]
Deu certo? Boa! Qualquer coisa, só avisar :D
