### ISSUE TITLE
M1#A27 - PropTypes

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#541]
Olá Fernando. 

Espero que esteja tudo bem por ai.

Nessa aula de PropTypes quando digitei o Button.propTypes... o VSCode não mostrou o metodo propTypes então fui me informar e vi que para continuar usando tem que adicionar uma dependencia chamada prop-types.

Nessa [documentação do ReactJS ](https://reactjs.org/docs/typechecking-with-proptypes.html#gatsby-focus-wrapper)consta que para typechecking pode ser utilizado o Flow ou TypeScript.

Procurei por ajuda na sua página de dependências e não encontrei algo sobre esse vídeo.

Para não me atrapalhar no curso o que você recomenda? Instalo essa dependencia prop-types? Se for para instalar então qual versão?

Quanto mais comentário, sugestão ou outra orientação para estar o mais preparado para atender as necessidades distints eu agradeço. Falo assim porque sei que cada caso é um caso.

@fdaciuk

**Comment by Alexandre1202** [comment]
oi @fdaciuk 

Agradeço muito se por favor, puder ajudar com essa duvida.

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Desculpe a demora na resposta =)

Vamos lá: o `prop-types` foi separado da lib principal do React na versão 15.5. Eu mostrei isso em algumas aulas mais pra frente, então minha recomendação seria usar a versão do React que e mostro nas aulas (15.4), para conseguir seguir exatamente como eu mostro, ok?

Em breve essas aulas estarão atualizadas, refletindo a versão mais recente do React, aí já vai resolver esses problemas que acontecem por conta da versão.

Não mudou praticamente nada, apenas novas coisas foram adicionadas, e algumas features menos utilizadas foram movidas para bibliotecas separadas, como o `prop-types`, então se você seguir com a versão 15.4 não vai ter perda de conteúdo :D

Desculpe mais uma vez a demora, e conte comigo para o que precisar! :D

**Comment by Alexandre1202** [comment]
Oi Fernando

Certo! Pelo que entendi é melhor eu avançar no curso sem o .propTypes por enquanto e mais adiante terá a instalação e utilização do prop-types para termos typechecking.

Por favor, você sabe uma forma (npm) de identificarmos a versão instalada do React melhor que essa?
![image](https://user-images.githubusercontent.com/8005205/118741216-29875300-b824-11eb-8acb-16df4d952b22.png)



@fdaciuk

**Comment by fdaciuk** [comment]
Na verdade, na versão 15.4 o `PropTypes` está incluído.. por isso o ideal é sempre seguir com a versão mostrada no 
[arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) =)

Para ver a versão instalada, você pode olhar no seu `package.json` mesmo, ou rodar o comando:

```
npm list react
```

=)

**Comment by Alexandre1202** [comment]
Perfeito! 
É exatamente isso que eu procurava. Uma forma direta e independente de obter essa informação no S.O.
![image](https://user-images.githubusercontent.com/8005205/118812965-0fca2800-b885-11eb-9447-a8f1acb4c41b.png)

Muito obrigado

**Comment by fdaciuk** [comment]
Show! Qualqueru dúvida, fique à vontade para perguntar =)
