### ISSUE TITLE
M1#A52 - 

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#543]
Olá Fernando.

É apresentado a mensagem de test quebrado quando eu executo console.assert() mas e a execução continua!
![image](https://user-images.githubusercontent.com/8005205/119910207-08fa7f80-bf2d-11eb-8a79-41024e5c8d55.png)

Veja meu teste:
![image](https://user-images.githubusercontent.com/8005205/119910385-6db5da00-bf2d-11eb-9493-5df8a112e0a7.png)

A função tem apenas duas linhas. A primeira só o 'use strict' e a segunda está vazia.

Por favor, faz ideia do que pode ter acontecido de errado aqui?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Pois é, isso foi de uma atualização do Node.js, onde ele não para mais a execução do programa por causa de alguma falha no console.assert.. A solução eu deixei pinada na lista de issues, [o link é esse](https://github.com/da2k/curso-reactjs-ninja/issues/443) =)

**Comment by Alexandre1202** [comment]
Legal! 
Tudo funcionando para o console.assert considerando o link acima! 
Muito obrigado

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
