### ISSUE TITLE
M3#A68 Como testar componentes conectados ao Redux

### ISSUE THREAD

**Issue by theandersonn** [da2k/curso-reactjs-ninja#547]
Oi Daciuk!!!

Após assistir as aulas de criação do todo e searchCep onde vc testou o reducer/actions. 
Fiquei com dúvida de como montar o fluxo para testar os componentes conectados ao reducer: 
- bater a cobertura dos dipatchs,
- verificar se o componente está listando os dados,
- verificar se ao clicar em um handle ele está retornando o esperado.

Assim o que eu desejo testar é o componente `main` que se conecta ao redux.
Andei pesquisando e vi sugestões para usar o `redux-mock-store`.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala meu caro! Vamos lá! :D 

Sobre cobertura de testes, não é algo que você precisa levar à risca. 100% de cobertura de testes não quer dizer muita coisa (apesar de te ajudar a ter uma visão, não deve ser seu único ponto de observação).

No caso de testes de componentes, o ideal é sempre tentar testar o que o usuário vai usar, não testar implementação do componente.

Para componentes conectados com o Redux, minha recomendação seria:
Se estiver usando o `connect`, por exemplo, você pode exportar para o seu app o uso do `connect`, e pode exportar, apenas para fins de teste, o componente mesmo que vai ser passado para o `connect`.

Ao fazer isso, o componente vai receber os dados de estado do Redux via props. Como props não são valores externos que o componente precisa acessar, você consegue, nos seus testes, injetar manualmente essas props para testar a entrada de cada uma delas, e como seria a saída, baseado na entrada desses dados =)

Essa seria a melhor forma de testar "unitariamente" os componentes.

Uma ferramenta que pode te ajudar com esse tipo de teste é a `react-testing-library`.

E se você quiser testar mesmo a integração com o Redux, aí a recomendação seria partir para testes E2E (end-to-end, ou ponta a ponta).

O Cypress é uma ótima ferramenta para isso. Esse tipo de teste testa todo o fluxo da aplicação, subindo um browser mesmo e testando exatamente as ações que o usuário faria.

Olhando para esses dois exemplos que eu dei, como são testes diferentes, cada um vai cobrir uma parte da aplicação, você não vai ter uma cobertura de testes centralizada, por isso cobertura de testes não deve ser o único ponto de observação para saber se sua aplicação está bem testada =)

E por fim, mocks ajudam a testar algumas coisas, mas normalmente não recomendo, pois você pode ter falsos positivos ao usar mocks.

Mocks servem para testar coisas unitariamente, mas ignorando completamente a integração. Se é isso que você precisa testar, aí os mocks fazem sentido. Mas é importante ter também, além dos testes com mock, alguns testes de integração (ou E2E), fazendo o caminho completo para garantir que tudo funciona como esperado mesmo =)

Não sei se a resposta ajudou muito. Tem muita coisa pra falar sobre esse assunto, e pode ter algo que não ficou tão claro. Se foi esse o caso, me deixe saber, que eu vou te ajudando, ok? =)

**Comment by theandersonn** [comment]
Claro que ajudou, obrigado!

Estou trabalhando aqui com Jest e RTL, para os componentes burrinhos estou usando mocks, esta sendo legal que serve tbm como uma pequena documentação do que espero.

No caso desses componentes conectados com o Redux esbarrei no `connect` e `withRouter` para montar o render básico. E o que eu gostaria de testar sao as interações de handle dentro desses componentes.

Esse trecho de sua explicação e uma novidade para mim: "...componente vai receber os dados de estado do Redux via props..."

Nesses testes eu planejo trazer mais uma camada com o Cypress.

Desejo manter os testes isolados, cada um com a sua responsabilidade. O que estou tentando eh prover o ambiente básico para o render desses componentes e começar a analise.

**Comment by fdaciuk** [comment]
> No caso desses componentes conectados com o Redux esbarrei no connect e withRouter para montar o render básico. E o que eu gostaria de testar sao as interações de handle dentro desses componentes.

> O que estou tentando eh prover o ambiente básico para o render desses componentes e começar a analise.

Legal @theandersonn! Nesse caso, o que você pode fazer é o seguinte: esses componentes que estão conectados ao Redux (com `connect`) e no React Router (com `withRouter`), precisam receber as informações de algum lugar.

No React, quem envia essas informações sem precisar passar props, normalmente é um Provider.

No caso do Redux, você tem o Provider que você envolve todo o seu app, e passa seu `state`, que será repassado para todo o app via Context API.

Para o React Router, mesma coisa: você normalmente usa o BrowserRouter, que também é um provider da Context API.

Então pra você escrever testes usando esses componentes que já estão envolvidos com `connect` e `withRouter`, você precisaria apenas envolver eles no seu teste com o devido Provider. Você pode mockar seu próprio Provider (no caso do Redux, mockar também o objeto de estado), ou pode só gerar o Provider externamente, em outro componente, e reutilizar o mesmo que você usa no app para os seus testes =)

Deu pra entender a ideia?

**Comment by theandersonn** [comment]
Eu evolui um pouco mockando `withRouter ` e o `Provider` do redux, passei o state inicial, só que na hora de passar a store, ele não conseguiu ler os dados e metodos. estive pensando... na real esse não é o caminho que quero seguir.

Resolvi separar o redux da ui e testar a partir das props que a ui está recebendo. Resolveu, vou melhorar a analise desses testes ainda. e deixei essa camada do redux para o teste de integração.

**Comment by fdaciuk** [comment]
Boa, vai deixar seus testes mais simples assim =)
