### ISSUE TITLE
M2#A30 - getstorybook

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#548]
oi, Fernando.

Tudo bom?

Por favor, veja se pode ajudar aqui no problema de detecção do tipo de projeto
![image](https://user-images.githubusercontent.com/8005205/121619668-599ace00-ca3f-11eb-913d-8f022b128692.png)

Caso ver o projeto facilite a análise eu já me antecipei e subi no meu [repositório](https://github.com/Alexandre1202/jest-in-practise.git) dessa parte do curso.

Agradeço se puder encontrar o motivo e uma solução para esse problema.

@fdaciuk

**Comment by Alexandre1202** [comment]
Já vi qual era o problema. 

Realmente o projeto não era o projeto template de desenvolvimento.

Executei o get storybook no projeto correto e está funcionando

@fdaciuk

**Comment by fdaciuk** [comment]
Boa! Qualquer coisa avisa ae =)
