### ISSUE TITLE
M2#A50

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#55]
Professor o yarn não esta funcionando comigo toda vez que eu faço `yarn add --dev <dependências>` ele reinstala todos os pacotes e não instala o que eu quero, e nem gera aquele arquivo `yarn.lock`.

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @CheeseFlan! Qual erro ele mostra?

**Comment by CheeseFlan** [comment]
```
error c:\dev\react_course\react-webpack-with-assets\node_modules\integer: Command failed.
Exit code: 1
Command: node tools/install
Arguments:
Directory: c:\dev\react_course\react-webpack-with-assets\node_modules\integer
Output:
c:\dev\react_course\react-webpack-with-assets\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\dev\react_course\react-webpack-with-assets\node_modules\integer
```

**Comment by CheeseFlan** [comment]
este é o erro que é mostrado :(

**Comment by fdaciuk** [comment]
Parece que ele está tentando fazer algum processo de build usando o `node-gyp`, mas pra isso ele precisa do `python`.

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

Provavelmente ele não vem instalado com windows, tente instalar ele pra ver se funciona :)

Senão use o NPM mesmo, sem problemas. O Yarn é só pra tentar facilitar o gerenciamento de pacotes, mas se o NPM funcionar pra você, não vai atrapalhar em nada :)

**Comment by CheeseFlan** [comment]
Então vou continuar com o npm pra não ter problemas :+1:  , sobre a atualização das aulas você falou que posta toda a segunda só que essa semana não foi postado ainda, esta tendo algum problema com o curso ou são eventos que estão tomando o tempo ? :)

**Comment by fdaciuk** [comment]
Legal!
Essas semanas realmente estão corridas por conta dos eventos, mas na próxima eu já libero mais alguns :D
