### ISSUE TITLE
Retornar dados de collection de um doc específico

### ISSUE THREAD

**Issue by carlossoglia** [da2k/curso-reactjs-ninja#552]
Olá Fernando, tudo bem?

Estou desenvolvendo um projeto muito semelhante ao React-zzaria, porém estou com dificuldades para conseguir retornar a partir de uma função, os dados de uma collection de um doc do Firestore. Por exemplo, se eu tiver dentro do doc "orders" uma collection "user" com o email, data do último pedido e nota de avaliação da última compra como eu poderia fazer uma consulta retornando esses dados numa nova página?

Desde já agradeço a gentiliza!
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @carlossoglia! Você pode fazer a chamada dessa forma:

```js
db.collection('orders').doc('id-da-order').collection('users').get()
```

isso deve trazer pra você somente os documentos que estão na coleção `users`, dentro do pedido que você está consultando =)

**Comment by carlossoglia** [comment]
Olá Fernando! Muito obrigado desde já, me ajudou bastante aqui, deu tudo certo da maneira como orientou...

**Comment by fdaciuk** [comment]
Massa @carlossoglia! Qualquer dúvida, só avisar :D
