### ISSUE TITLE
M2#A73 - Atualização Webpack

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#553]
Olá Fernando. 

Tudo bom?

Apenas para confirmar, o react-hot-loader tem algum problema com a  versão 2 do WebPack e por isso é que ele foi forçado em ser uma versão específica. Caso contrário todas as dependências de desenvolvimento poderiam ser atualizadas com o WebPack 2.  Correto?

Outro assunto. Pode ser necessário eu estudar mais sobre WebPack ou posso continuar rever os vídeos para eu acompanhar as atualizações necessárias que você fará continuamente? 

@fdaciuk

**Comment by Alexandre1202** [comment]
Claro.
Minha pergunta sobre a necessidade de eu ter que estudar sobre WebPack ou não é por conta de ver que você apresenta bastante configuração e agora veio a atualização dele. Ou seja, conhecimento de WebPack é sempre bom. Me passou que do mesmo jeito que preciso estudar JavaScript muito bem, tal como venho fazendo em paralelo com React, será que eu precisaria também passar o olho sobre o WebPack futuramente ou posso ficar atento apenas ao que está sendo apresentado no curso?

**Comment by fdaciuk** [comment]
Ah, entendi! Bom, diferente da linguagem JS, o webpack é apenas uma ferramenta, então ele não precisa da sua total atenção. Até porque, hoje em dia existem outras ferramentas que vieram para "competir" com o webpack, como o Parcel, Vite, Snowpack, etc.

Então assim: vale a pena estudar o webpack, para entender como esse tipo de ferramenta funciona, mas não precisa se aprofundar muito, a menos que você queira fazer isso.

Pensando no dia a dia de trabalho com React, se você entender como ele funciona já será o suficiente. Não precisa saber tudo dele não, até porque, quando você precisar fazer algo específico, você poderá, a qualquer momento, consultar a documentação =)

**Comment by Alexandre1202** [comment]
Perfeito. 
Obrigado.
Pode fechar

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só perguntar =)
