### ISSUE TITLE
Erro npm start apos instalar ajax

### ISSUE THREAD

**Issue by EdilsonTarcio** [da2k/curso-reactjs-ninja#554]
```
ERROR in Cannot find module 'standard'
Require stack:
- C:\Users\edils\Desktop\crud\node_modules\standard-loader\index.js
- C:\Users\edils\Desktop\crud\node_modules\webpack-core\lib\NormalModuleMixin.js
- C:\Users\edils\Desktop\crud\node_modules\webpack\lib\NormalModule.js
- C:\Users\edils\Desktop\crud\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\edils\Desktop\crud\node_modules\webpack\lib\Compiler.js
- C:\Users\edils\Desktop\crud\node_modules\webpack\lib\webpack.js
- C:\Users\edils\Desktop\crud\server.js
 @ multi main
webpack: Failed to compile.
```

esse erro ocorre ao executar o **npm start**  após executar o comando da aula 052 M1A40 

```
npm i --save @fdaciuk/ajax
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @EdilsonTarcio ! Pela mensagem de erro, parece que faltou fazer a instalação do `standard`. Você chegou a instalar ele no projeto?

**Comment by EdilsonTarcio** [comment]
Olá, @fdaciuk  eu já havia instalado, instalei novamente e o erro parou! Obrigado.

**Comment by fdaciuk** [comment]
Boa! Só confere se no seu package.json o standard ficou listado.. pode ser que você tenha instalado mas ele não tenha ficado salvo lá, aí se você deletar a node_modules, ou fazer um clone do projeto sem a node_modules, e fazer uma nova instalação, se a dependência não estiver listada no `package.json` ela não vai ser instalada =)
