### ISSUE TITLE
M2#A76 - Atualização Webpack

### ISSUE THREAD

**Issue by Alexandre1202** [da2k/curso-reactjs-ninja#555]
Oi Fernando.

Não te dou paz né? rs...rs...

Eu rodei o yarn update-packages e depois o yarn lint mas acredito que ele não funcionou corretamente.

Por favor, veja se o anexo com o tudo que foi apresentado no console ajuda na análise.
[yarn-update-scripts-error.rtf.zip](https://github.com/da2k/curso-reactjs-ninja/files/6787855/yarn-update-scripts-error.rtf.zip)

Ainda sobre esse tema eu vi agora que também não está rodando o `yarn build`
![image](https://user-images.githubusercontent.com/8005205/125007510-b8e80000-e036-11eb-8545-427e9f63c743.png)

Esqueci como faço para instalar o webpack cli e para não fazer errado preferi perguntar novamente antes de responder yes ali na console.

Achei fantástico esse Tree Shaking pois código/bundle conciso e limpo visa a qualidade esperada por uma aplicação bem feita.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Alexandre1202! Esse comando de atualizar as dependências automaticamente não vai funcionar como esperado. Eu acabei não prevendo os problemas de compatibilidade futuros das dependências, então o ideal seria seguir sem executar esse comando.

O webpack-cli é para a versão 4 ou posterior do webpack, e nessa etapa do curso nós estamos usando a v2, então o ideal seria seguir sem instalar ela =)

Bem interessante a ideia do tree shaking né? Hoje em dia não só o webpack, mas outras ferramentas que fazem o mesmo trabalho também já têm essa feature disponível :D

**Comment by Alexandre1202** [comment]
Então, acredito que faz sentido eu pegar uma cópia do boilerplate e seguir sem a atualização das dependências.
Que tal?

**Comment by fdaciuk** [comment]
Pra ser sincero, não sei aquele boilerplate vai funcionar corretamente da forma que está. Nesse caso, a recomendação seria pegar as dependências do `package.json`, do código da aula [desse diretório](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/m02), e usar elas, ao menos até eu conseguir atualizar esse módulo, essa vai ser a forma mais garantida de tudo funcionar =)

**Comment by Alexandre1202** [comment]
Fiz o teste e o boilerplate funcionou pra mim. Vida que segue rs...

Pode fechar essa issue.

**Comment by fdaciuk** [comment]
Então perfeito! Qualquer dúvida, vai avisando aqui :D
