### ISSUE TITLE
[Seção 2: Módulo React + Webpack] [Aula 02 - Configuração básica do Webpack]

### ISSUE THREAD

**Issue by raphaelprsilva** [da2k/curso-reactjs-ninja#558]
Olá Fernando, tudo bem?

Peço desculpas pelas perguntas bobas, mas é que estou apenas no início da jornada.

Tenho duas perguntas:

- 1ª - Após o ``npm install``, foi criado um diretório `node_modules`, no qual contém um diretório `webpack`. Há a necessidade de se criar o `webpack.config.js`? Se sim, em qual diretório eu crio?

![00-aula-02-react-ninja](https://user-images.githubusercontent.com/50886915/126192573-1e83475c-e6f7-40da-b46f-3f922e6005ce.png)

- 2ª - Vi que você utiliza o vim como editor. Posso fazer os procedimentos mostrados, pelo vscode?

Obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @raphaelprsilva! Tudo ótimo, e com você? =)

> Peço desculpas pelas perguntas bobas, mas é que estou apenas no início da jornada.

Bem capaz, não existe pergunta boba: se tem dúvida, tem que perguntar mesmo, é assim que se aprende! :D 

Vamos lá:

---

> 1ª - Após o npm install, foi criado um diretório node_modules, no qual contém um diretório webpack. Há a necessidade de se criar o webpack.config.js? Se sim, em qual diretório eu crio?

O diretório `node_modules` é criado automaticamente quando você instala uma dependência usando o `npm install`. Você nunca deve alterar o conteúdo desse diretório, pois ele é automaticamente gerado. Você pode, inclusive, apagar o diretório, desde que as suas dependências estejam listadas no arquivo `package.json`.

Se você pegar um projeto que só tem um package.json, você consegue rodar um `npm install`, e todas as dependências que estão listadas no package.json serão instaladas em um diretório automaticamente criado chamado `node_modules`. Por isso não devemos nunca alterar seu conteúdo =)

O arquivo `webpack.config.js` faz parte do seu projeto, então você cria ele sempre na raiz do projeto ("ao lado" do diretório node_modules e do arquivo package.json).

> 2ª - Vi que você utiliza o vim como editor. Posso fazer os procedimentos mostrados, pelo vscode?

Com certeza pode! Como eu falei logo no início do curso: você deve usar um editor de sua preferência. No meu caso, é o vim, mas você pode usar o que já está acostumado sem problema algum.

O editor de textos é só uma ferramenta para escrever código, e faz parte de gosto pessoal, nada mais =)

**Comment by raphaelprsilva** [comment]
Valeu mesmo @fdaciuk pelas respostas. Foram bastante esclarecedoras!

Sinta-se à vontade para fechar a issue.

Obrigado, mais uma vez.

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
