### ISSUE TITLE
[Seção 2: Módulo React + Webpack] [MRW#02 - Configuração básica do Webpack]

### ISSUE THREAD

**Issue by raphaelprsilva** [da2k/curso-reactjs-ninja#559]
Eu novamente @fdaciuk. Tive um pequeno problema!

Estava seguindo normalmente a aula 02. Como recomendado na aula do futuro, fiz:

- Imagem dos diretórios e arquivos criados na aula:
![00-aula-02-react-ninja](https://user-images.githubusercontent.com/50886915/126237107-3564c6f4-b62e-4e5a-b1b6-c05c0558191a.png)
1. Instalação do webpack, com o comando `npm install --save-dev webpack@1`;
2. Quando fui instalar globalmente o weback, `npm install -g webpack@1`, obtive um erro de permissão para esse diretório `/usr/lib/node_modules/webpack`. Pesquisei sobre o erro e:
2.1. Tentei alterar permissões para o diretório, e não deu certo;
2.2. Ao pesquisar sobre, também tentei utilizar alguns comandos, semelhante a esse, `sudo chown -R $(whoami) /usr/local/lib/node_modules`. E mesmo assim, não consegui instalar.
- Imagem do terminal após comando
![00-aula-02-react-ninja-error](https://user-images.githubusercontent.com/50886915/126237171-5eacafd2-d9ac-49fb-8e23-1be8079466a2.png)

- Versão do node: v15.14.0
- Versão npm: 7.7.6
- Versão OS: Ubuntu 20.04.2 LTS

Muito obridado, desde já!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @raphaelprsilva! Você está utilizando Ubuntu, certo? Nesse caso, desinstale o Node.js, e instale ele via NVM: https://github.com/nvm-sh/nvm

O motivo é o seguinte: O node.js, instalado a nível de sistema operacional, é instalado em um diretório que você só tem acesso se for root ou sudoer. E isso vai gerar um problema ao instalar dependências globais, pois seu usuário atual não vai ter permissão para instalar.

Uma forma de instalar é usando `sudo`, mas não recomendo fazer isso, pois as dependências instaladas com sudo terão permissões demais sobre o seu sistema.

Com o NVM, a instalação do Node.js acontece de forma "local", para o seu usuário atual. As instalações de dependências globais vão ficar no seu diretório de usuário (`/home`), e ali você  já tem todas as permissões necessárias, então não precisa do sudo para instalar as dependências globais =)

Fazendo isso já deve resolver seu problema! Se ainda assim tiver qualquer outro problema, me deixe saber :D

**Comment by raphaelprsilva** [comment]
Oi @fdaciuk, obrigado pelo retorno. Assim que possível, vou testar.

Obrigado mais uma vez e, se quiser fechar a issue, fique à vontade!

**Comment by fdaciuk** [comment]
Boa! Qualquer problema, volta a comentar aqui que eu vou te ajudando =)
