### ISSUE TITLE
M1#A08

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-reactjs-ninja#562]
Boa tarde Fernando, tudo bom?

O meu codigo está dando o seguinte erro: 
![image](https://user-images.githubusercontent.com/64866385/129611717-97fe3a77-b7aa-4c1e-b81a-05ee444c5385.png)

no App.js, usei o seguinte codigo: 
```
import React from 'react'
import Title from './title'

const App = React.createClass({
  render: function(){
    return(
      <div className='container'>
        <Title name='Maristela!'/>
      </div>
    )
  }
})


export default App;

```

e no title.js:

```
import React from 'react';

const Title = React.createClass({
    render: function(){
        return(
            <h1>Olá {this.props.name}</h1>
        )
    }
})

export default Title;

```

Sabe dizer o que estou fazendo de errado? Obrigada!!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marisbispo! Possivelmente você instalou uma versão do React e React DOM maior que a `15.4` =)

O ideal seria instalar essa versão para seguir tudo exatamente como foi mostrado no curso, ok? =)
Para saber como instalar as versões corretas mostradas em cada aula, você pode sempre consultar o [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) =)

**Comment by marisbispo** [comment]
Eu criei com o npx-create-react-app

Entao, o ideal é fazer passo a passo como você faz nas primeiras aulas, né?

**Comment by wandrebarbosa** [comment]
Boa noite @fdaciuk, tbm estou com um problema nesta aula, possivelmente o mesmo da amiga acima, porém até antes de configurar o para o server pelo npm start, estava correndo tudo bem conforme as aulas, porem quando carreguei o comando npm start ele da o seguinte erro abaixo:

![image](https://user-images.githubusercontent.com/23178857/129825834-fcfcdc06-f53b-46cb-94d1-c5d3f2817d43.png)

**Comment by fdaciuk** [comment]
@marisbispo pode continuar com o CRA sem problemas! Nesse caso, só precisa adaptar duas coisas: o `React.createClass` e o `React.PropTypes` foram movidos para bibliotecas externas à partir da versão 15.5, por isso eu peço para instalar a 15.4, mas em aulas mais pra frente eu mostro como fazer essa atualização =)

No seu caso, pode continuar com o CRA, mas você vai precisar instalar duas bibliotecas adicionais para usar o `createClass` e o `PropTypes`:

```
npm install --save-dev create-react-class prop-types
```

Isso vai instalar as duas bibliotecas. Aí para usar, é só importar e usar. Ao invés de:

```
import React from 'react'
React.createClass({ ... })
```

Use assim:

```
import createClass from 'create-react-class'
createClass({ ... })
```

Mesma coisa para o PropTypes, quando você chegar na aula que eu falo sobre ele, ok? =)

Fazendo isso, você não deve ter problemas daqui pra frente, e poderá continuar usando a versão mais recente do React =)

**Comment by fdaciuk** [comment]
Oi @wandrebarbosa! Pelo erro, parece que faltou instalar o `webpack` localmente. Você deve ter instalado só de forma global, com o `-g`, certo? =)

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :D
