### ISSUE TITLE
Dúvida a respeito de quando devo criar um componente

### ISSUE THREAD

**Issue by sou-gabriel** [da2k/curso-reactjs-ninja#564]
Fala professor, tudo bom?

Uma das minhas maiores dúvidas quando comecei a estudar React é a respeito de quando devo criar um componente na minha aplicação. Daí minha pergunta professor, como posso identificar que determinada parte da minha interface é ou não um componente?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @sou-gabriel! No React, tudo é um componente. Se você criar sua aplicação todinha em um componente só, ela ainda é um componente xD

Mas basicamente a ideia de quebrar que eu costumo usar é a seguinte: escreva tudo em um componente só. Quando você perceber "padrões" que podem ser reutilizados, você pode quebrar isso em um componente.

Outro momento bom pra quebrar é quando seu componente principal está ficando muito grande (com muita rolagem vertical), aí você quebra em componentes menores para deixar o código em geral mais legível.

Mas é basicamente isso: um componente é um pedaço de código que faz alguma coisa. Isso é bem genérico mesmo, pois para cada tipo de aplicação, o conceito de "componente" pode variar, e vai depender exclusivamente do seu código =)

**Comment by sou-gabriel** [comment]
Hmmm, entendi bem com essa explicação. Agora vou implementar essas dicas em alguns projetos pra praticar então, e qualquer coisa volto aqui professor.

Um abração e muito obrigado =)

**Comment by fdaciuk** [comment]
Perfeito meu caro! Qualquer dúvida, fique muito à vontade para perguntar =)
