### ISSUE TITLE
[M4A#186] - Error eslint

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#566]
Professor estou com o seguinte código:

```
<Fab color='primary' title={`Mudar status para "${orderStatus.nextButtonTitle}"`} />
```

E o meu estlint está pirando quando estou usando a template literals dessa forma. Vi uma solução que era para baixar o `@babel/eslint-parser` mais não funcionou.

Código do erro
```
Cannot read property 'value' of null
Occurred while linting /home/luciano/Documentos/devbara/gith/estudos/ReactNinjaExample/my-examples/m04/reactzzaria/sistema-cadastro/src/pages/orders/orders.js:152
```

E segue o link para o [arquivo](https://github.com/lucianoMeusCursos/ReactNinjaExample/blob/master/my-examples/m04/reactzzaria/sistema-cadastro/src/pages/orders/orders.js)

Detalhe que esse acontece quando estou colocando no template literals. Para o senhor vê eu tive que fazer dessa forma para seguir nas aulas:

```
{pizza.flavours
  .map(flavour => flavour.name)
  .reduce((acc, flavour, index, array) => {
    if (index === 0) {
      return flavour
    }

    if (index === array.length - 1) {
      return acc + ' ' + 'e' + ' ' + flavour
    }

    return acc + ',' + ' ' + flavour
}, '')}
```

Queria saber se já aconteceu isso alguma vez por aqui ?

@fdaciuk

**Comment by lucianobarauna** [comment]
Professor tentei atualizar o babel que é até mesmo recomendado por eles e deu alguns problemas.
Resolvi da forma mais bruta. Apaguei a node_modules e peguei o package da aula rs

**Comment by lucianobarauna** [comment]
Então professor ainda não entendi o que rolou mas eu no final dessa aula copiei o código que vc fez e joguei em cima do meu e parou de dar esse alerta.

Não sei se foi alguma string mal fechada ou outra coisa. Só sei que realmente fiquei curioso rsrs mas resolveu.

**Comment by fdaciuk** [comment]
Oi @lucianobarauna! Cara, pesquisando aqui pela mensagem do erro, parece que era algum problema do babel-eslint com dependências duplicadas.. em teoria, removendo a node_modules, package-lock.json e yarn.lock, e instalando as deps de novo, o problema é resolvido.

Mas que bom que deu tudo certo aí! Qualquer coisa, só avisar :D
