### ISSUE TITLE
M1#A36 - Cannot read properties of undefined

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-reactjs-ninja#567]
Boa tarde, @fdaciuk! Tudo bom?

Meu codigo está dando erro no 'Repos.propTypes'. O que eu fiz de errado? 

Segue o codigo que usei:

```
import React from 'react'

const Repos = ({className, title, repos}) =>(
    <div className={className}>
      <h2>{title}</h2>
      <ul>
          {repos.map((repo, index) => (
            <li key={index}>
                <a href={repo.link}>{repo.name}</a>
            </li>
          ))}
      </ul>
    </div>
)

Repos.defaultProps = {
    className: ''
}

Repos.propTypes = {
    className: React.PropTypes.string,
    title: React.PropTypes.string.isRequired,
    repos: React.PropTypes.array  
}

export default Repos

```

O erro:

![image](https://user-images.githubusercontent.com/64866385/136247849-66038f7f-63cc-4e66-b1cd-38e8bb1f4d9e.png)

Obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marisbispo! Qual versão do React você está usando? Se estiver usando uma versão maior que a `15.4`, você precisa instalar separado o pacote `prop-types` =)

**Comment by marisbispo** [comment]
@fdaciuk, funcionou! MUITO obrigada! Só mais uma dúvida: Seria melhor usar versões anteriores do react?
