### ISSUE TITLE
Sobre workflow-react

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#57]
Professor eu posso utilizar o boilerplate, que você disponibiliza pra aulas do modulo02 ?, porque estou fazendo seguinte eu criei um boilerplate qualquer aqui apenas pra acompanhar as aulas de atualização de dependências, porque ai caso quebre alguma coisa não afeta o fluxo das aulas, e ainda continuo entendendo cada mudança que vem ocorrendo nas dependências.

@fdaciuk

**Comment by fdaciuk** [comment]
Com certeza @CheeseFlan! As aulas onde eu mostro sobre o boilerplate é só pra que você realmente entenda as configurações necessárias para cada feature que nós vamos utilizar quando estivermos em um projeto com React, mas você pode usar qualquer boilerplate que achar mais fácil, ou até criar o seu, como você está fazendo :D

**Comment by CheeseFlan** [comment]
vlw, obrigado.

**Comment by fdaciuk** [comment]
Qualquer coisa só avisar :D
