### ISSUE TITLE
[M2A03] DUVIDA SOBRE DEPENDENCIAS

### ISSUE THREAD

**Issue by joaquimmulaza** [da2k/curso-reactjs-ninja#570]
@fdaciuk não consigo instalar as dependencias, começando pelo Webpack, já baixei a versão 10 do node e segui os passos da aula do futuro.

![Captura de Ecrã (190)](https://user-images.githubusercontent.com/71206707/141203810-1cfa09b4-004b-45fa-99be-a6b8b0363c10.png)

**Comment by fdaciuk** [comment]
Oi @joaquimmulaza! Pela mensagem de erro, o problema parece ser apenas um erro de sintaxe no seu arquivo `package.json`. Como ele está?

**Comment by joaquimmulaza** [comment]
@fdaciuk o arquivo package.json esta vazio, o que eu faço?

**Comment by fdaciuk** [comment]
Só adicionar as chaves nele e salvar!

```
{}
```

O comando `echo {} >> package.json` faz isso =)

No seu caso pode não ter rolado por falta das apas: dependendo do seu SO, do seu terminal, etc., ele pode ter um comportamento diferente.

Aí seria só rodar:

```
echo "{}" >> package.json
```

Mas esse comando é só uma facilidade.. dá no mesmo que colocar um objeto vazio no `package.json` =)

**Comment by joaquimmulaza** [comment]
@fdaciuk consegui resolver. Mas agora tem um outro bug, a atualização em tempo real do webpack não esta funcionando.

**Comment by fdaciuk** [comment]
Oi @joaquimmulaza! Sobe seu projeto em um repo aqui no GitHub e compartilha comigo o link que eu dou uma olhada pra te ajudar a entender o que pode estar faltando =)

**Comment by joaquimmulaza** [comment]
@fdaciuk aqui esta o link do meu projeto: https://github.com/joaquimmulaza/reactjsNinja.git

**Comment by joaquimmulaza** [comment]
@fdaciuk ?

**Comment by fdaciuk** [comment]
Oi @joaquimmulaza! Olhei aqui seu projeto, mas ele ainda não tem as configurações para funcionar o hot loader.

Seu projeto deveria ter essa configuração mínima pra funcionar corretamente:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-10

**Comment by FECUNHA** [comment]
Boa noite

Estou na aula MRW#03 - Usando o server do Webpack
Já baixei todas as dependências atualizadas.
Criei todos os arquivos e conferi todos e não possuem erros de sintaxe

quando efetuo o comando: 
webpack -dev -server
Não mostra erro algum e imprime o log abaixo

Hash: c45c3dfea1bd80f16e28
Version: webpack 1.15.0
Time: 83ms
 Asset     Size  Chunks             Chunk Names
bundle.js  1.63 kB       0  [emitted]  main
bundle.js.map   1.6 kB       0  [emitted]  main
   [0] ./src/index.js 21 bytes {0} [built]

Desde já agradeço

**Comment by fdaciuk** [comment]
Oi @FECUNHA! Sobe seu projeto em um repo aqui no GitHub e manda o link que eu dou uma olhada para entender o que pode ter acontecido =)

**Comment by FECUNHA** [comment]
Boa noite
Desde já agradeço!
https://github.com/FECUNHA/CursoReactNinja

**Comment by fdaciuk** [comment]
Oi @FECUNHA! Faltou o arquivo `package.json`, com as dependências :)

**Comment by fdaciuk** [comment]
@FECUNHA qualque coisa, confere se seu código está exatamente igual ao código nesse diretório aqui, que é o código da aula que você está vendo:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-03

**Comment by fdaciuk** [comment]
Oi @joaquimmulaza e @FECUNHA! Vou fechar a issue, mas se vocês ainda tiverem alguma relacionada à esse assunto, a gente reabre, ok? =)
