### ISSUE TITLE
M4#A99 - Aplicação não roda após atualizar as dependências

### ISSUE THREAD

**Issue by jhonnytrinca** [da2k/curso-reactjs-ninja#571]
Olá @fdaciuk!

Tive um problema após fazer as atualizações de dependências no projeto do React-zzaria, a principio enquanto estava logado funcionou bem, mas quando cliquei para deslogar e ver se funcionaria logar novamente as telas já não rodavam mais. ao dar o yarn dev ele abre a página, no console não mostra nenhum erro específico referente a isso mas fica carregando eternamente, seja tentando pela home ou já indo direto no /login
Pode dar uma olhada aonde está o problema no meu código?

Outra dúvida que fiquei também é referente a um warning que aparece no console de `Setting displayName on Context.Consumer has no effect. You should set it directly on the context with Context.displayName = 'Router.Consumer'`
Antes de eu deslogar isso não atrapalhou em nada na aplicação, mas sabe como resolvo isso?

Segue o projeto: [Reactzzaria](https://github.com/jhonnytrinca/reactzzaria.git)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jhonnytrinca! O problema está [nessa regra aqui](https://github.com/jhonnytrinca/reactzzaria/blob/main/sistema-pedidos/src/app.js#L21-L28).

Tá vendo ali no `useEffect` que você só seta o estado de `userInfo` e `didCheckUserIn` se o usuário estiver logado?

Ou seja: se o usuário não estiver logado (`user` será `null`), você não vai definir o novo estado. Não definindo o novo estado, `didCheckUserIn` vai ser sempre `false`, e [apenas esse código](https://github.com/jhonnytrinca/reactzzaria/blob/main/sistema-pedidos/src/app.js#L32-L34) será executado (loading infinito) =)

O certo é fazer [dessa forma](https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m04/04-reactzzaria/099/sistema-pedidos/src/app.js#L20-L30), como mostrado na aula: independente se o usuário está logado ou não, você precisa definir o novo valor para `didCheckUserIn` =)

Se quiser continuar fazendo com `if` como você fez, você só precisa mover o `setCheckUserIn(true)` para fora do `if`, pois assim, independentemente se o usuário logou ou não, você vai setar esse estado corretamente, e o app vai prosseguir com o funcionando esperado =)

**Comment by fdaciuk** [comment]
Sobre o warning: ele não afeta o comportamento da aplicação. Mas possivelmente esse warning é de algum componente do Material UI, pode ignorar =)

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar :D
