### ISSUE TITLE
Error createStore - "Redux não está definido"

### ISSUE THREAD

**Issue by nataliaaraujo0** [da2k/curso-reactjs-ninja#572]
```
const { createStore } = Redux;
const store = createStore(counter);

```

No console.log aparece que o Redux não está definido.
"main.js:13 Uncaught ReferenceError: Redux is not defined".

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @nataliaaraujo0! Consegue subir seu projeto no GitHub e postar aqui o link do repositório pra eu ver como você está fazendo?

**Comment by nataliaaraujo0** [comment]
@fdaciuk  segue reposittório 👍🏾
https://github.com/nataliaaraujo0/app-counter-redux

**Comment by fdaciuk** [comment]
Oi @nataliaaraujo0! O problema é que você colocou [o script do Redux depois dos scripts onde você tenta usar o Redux](https://github.com/nataliaaraujo0/app-counter-redux/blob/main/index.html#L16).

O script do Redux precisa vir antes, pra ser carregado primeiro e você ter acesso ao objeto =)

**Comment by nataliaaraujo0** [comment]
@fdaciuk nossa, erro bobo meu. Muito obrigada!

**Comment by fdaciuk** [comment]
Nada, acontece =)
Qualquer dúvida, só avisar :D
