### ISSUE TITLE
[M1A06] Componente Title em formato JSX não é renderizado no meu Google Chrome

### ISSUE THREAD

**Issue by danielrochadev** [da2k/curso-reactjs-ninja#573]
Fala Daciuk! Cara eu vinha acompanhando a aula normalmente, consegui renderizar o h1 até a aula 05. Porém, quando comecei a criar o componente de Título "Title"e chamar o JSX dele dentro do ReactDOM, o elemento simplesmente não aparece no Browser. Já inspecionei e só aparece a div com ID app mesmo.

Já fiz algumas coisas para tentar encontrar um erro no código e nada:

1- Reinstalei o Node - kkkk
2- Os scripts que estou utilizando foram do site do REACT e não do site CDN (será que tem alguma diferença?)

@fdaciuk

**Comment by danielrochadev** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <div id="app"></div>  

    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>


    <script type="text/babel">
        var Title = React.createClass({
            render: function () {
                return <h1>Hello World</h1>
            }
        })

        ReactDOM.render(
            <Title />,
            document.getElementById('app')
        )
    </script>
</body>
</html>`

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @danielrochadev! Na verdade, a diferença é pq vc está utilizando os scripts para a versão 17 do React, não para a 15.4, como mostrada no curso =)

O `createClass` foi removido da biblioteca principal, e adicionado à um pacote separado, então para usar com a versão mais recente do React, você precisaria adicionar o CDN dessa lib também =)

Mas para acompanhar o curso, é mais fácil você só usar a versão mostrada no curso, e quando terminar os primeiros módulos, aí você já vai poder usar a versão mais recente, pois no decorrer do curso eu vou mostrando os updates que vão acontecendo (os principais acontecem após a versão 15.5) =)

**Comment by danielrochadev** [comment]
Cara muito obrigado por responder.
Modifiquei os scripts para versão 15.5 e funcionou :D - Seguindo aqui.

Cara, não sei se aqui é um canal correto para esse tipo de assunto, mas existe algum tipo de possibilidade de trocar uma idéia contigo por Call? Sugerindo tá? Tipo uma "consultoria/mentoria" para responder algumas dúvidas ou compartilhar dicas sobre uma transição de carreira e qual maneira fazer isso de acordo com minha realidade, que hoje sou UX Designer e preciso muito migrar para Desenvolvimento (só consigo te explicar essa pressa na migração em uma Call mesmo).
 No seu dia a dia corrido existe espaço pra isso? Como podemos alinhar isso? WhatsApp? E-mail? Telefone?
 
 Valeuzão meu velho.

@fdaciuk
