### ISSUE TITLE
M2#A30

### ISSUE THREAD

**Issue by SallesCosta** [da2k/curso-reactjs-ninja#575]
Bom dia mestre Daciuk, na instalação do storyBook eu fiz:

```yarn add global getstorybook```
em seguida:
```getstroybook``` 
e então :
```yarn add global getstorybook```

Tive muitos 'warnings'  (foto)
![Screenshot 2022-02-05 at 12 03 34](https://user-images.githubusercontent.com/81476236/152639646-eb471c06-919e-4261-8015-e852ca26bae4.png)

porém ele 'rodou' na porta 6006.

Ao entrar em [localhost:6006](http://localhost:6006/), não vejo nada. O navegador nao renderizou nada embora o favicon so SB tenha vindo corretamente.

![Screenshot 2022-02-05 at 12 17 45](https://user-images.githubusercontent.com/81476236/152639860-a29a3211-c2b8-4fcd-bd61-d490855a751d.png)

Eu gostaria de manter tudo usando o yarn (só questão de costume). Mas eu tentei o mesmo procedimento com ```npm```.. ```npx```.. e cheguei no mesmo problema.

Será que 'comi-barriga' em alguma parte?

Segue o [repositório](https://github.com/SallesCosta/reactLearning/tree/main/modulo2/storybook) 
abraços
@fdaciuk

**Comment by SallesCosta** [comment]
@fdaciuk  => Tentei tbm as soluções que vc sugeriu nas outras issues da M2#30. O problema persiste.

**Comment by fdaciuk** [comment]
Oi @SallesCosta! Você chegou a desinstalar o `getstorybook`, e instalou a versão `1.6.1` dele de forma global? Pode ser com Yarn mesmo =)

**Comment by SallesCosta** [comment]
nao, na verdade eu criei um projeto com Vite só pra estudar o storybook. Como vi que estava dando erro, deletei o projeto e fiz outro.
está vindo a versao 1.7.0
![Screenshot 2022-02-06 at 10 03 45](https://user-images.githubusercontent.com/81476236/152674221-ca59d19f-9048-4cea-8b65-fb59bfb02b25.png)

![Screenshot 2022-02-06 at 10 04 40](https://user-images.githubusercontent.com/81476236/152674238-1e17b29d-d93b-4f67-810f-0aab3f8bb276.png)
 
e então eu chego no mesmo lugar.. ao dar ```yarn run storybook```

**Comment by fdaciuk** [comment]
Consegue compartilhar o seu projeto em um repositório aqui no GitHub?

**Comment by SallesCosta** [comment]
[aqui](https://github.com/SallesCosta/reactLearning/tree/main/modulo2/storybook)

**Comment by fdaciuk** [comment]
É, realmente essa versão do storybook não vai funcionar com as versões mais novas dos bundlers :(

Bom, tem duas opções aqui: para pegar "a base" do storybook mostrada no curso, você pode usar [esse setup](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-10) que nós fizemos no curso, e instalar o storybook com `npx getstorybook@latest` para instalar a versão mais recente gerada pelo `getstorybook`.

Isso vai funcionar pra você conseguir entender como o storybook funciona.

Se quiser usar a versão mais recente do storybook, aí você pode usar a config que você já está usando, mas algumas coisas importantes mudaram desde a versão mostrada na aula. Para aprender, nesse caso, teria que seguir pela documentação mesmo =)

**Comment by SallesCosta** [comment]
excelente mestre.. vou assistir as aulas.. mas na hora de aplicar vou pela documentação mesmo..
Valeu

**Comment by fdaciuk** [comment]
Legal! Você pode até aplicar usando o setup que eu passei acima, está bem simples.. depois vc vai na doc e só vê o que mudou =)

Mas é isso, qualquer coisa, só avisar :D
