### ISSUE TITLE
9. [MRW#02] Configuração do webpack

### ISSUE THREAD

**Issue by IsaquePinkuss** [da2k/curso-reactjs-ninja#577]
Professor estou com muita dificuldade em instalar e configurar o webpack.
Consegui instalar conforme a aula porém quando  executei o webpack aparece essa imagem
![image](https://user-images.githubusercontent.com/75698082/154182853-f3e71cd8-3e1c-4987-a2e2-c2aa2295f3f8.png)

Como ve na imagem a baixo o webpack config está igual ao apresentado em aula:
![image](https://user-images.githubusercontent.com/75698082/154182992-0513bfe1-09ef-4ec9-a97a-76d3538e16b9.png)

Fiz e refiz umas 15 vezes nos mínimos detalhes todos os passos da aula para configurar mas sem sucesso por favor o que eu faço. Vi vários tutoriais até mesmo só consegui pelo menos executar (com erro) tendo que entrar no powerSheell em modo Admin e desabilitar um padrão de segurança  com o comando Set-ExecutionPolicy Bypass

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @IsaquePinkuss! O problema, possivelmente, é a versão do webpack que você instalou. Dá uma conferida no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), onde eu mostro a versão exata que você precisa instalar =)

Lembre-se de, antes de tudo, desinstalar o webpack que você já instalou (inclusive o `webpack-cli`, se você instalou ele também).

Se ainda assim não funcionar, compartilha comigo o link do repositório do seu projeto pra eu ver como você está fazendo, ok? :)

Dica: na hora de compartilhar o repositório, crie um arquivo na raiz do projeto chamado `.gitignore` e adicione nele o conteúdo:

```
node_modules
```

Dessa forma, o diretório `node_modules` não será adicionado ao git :)

**Comment by renanperin7** [comment]
conseguiram resolver? Estou com o mesmo problema e não consegui nem desinstalando o webpack e instalando de novo.

**Comment by fdaciuk** [comment]
Qual o seu problema @renanperin7?
