### ISSUE TITLE
[M2#A07] - Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-reactjs-ninja#578]
Boa tarde, @fdaciuk 

Instalei as dependencias como você explicou e está dando o seguinte erro:

```
 FAIL  ./sum.test.js
  ● Test suite failed to run

    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/Maristela/Documents/react ninja/jest/node_modules/babel-preset-es2015/lib/index.js

      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:211:11)
          at createDescriptor.next (<anonymous>)
          at Array.map (<anonymous>)
          at createDescriptors.next (<anonymous>)
```

Sabe me dizer o por que?

Mto obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marisbispo! Compartilha comigo o seu repo que tem esse código pra eu ver quais versões você está usando?

Outra coisa: qual versão do Node.js você está usando? Assim eu consigo baixar o repo e testar aqui pra te dizer certinho como fazer funcionar da forma menos "trabalhosa" possível :)

**Comment by marisbispo** [comment]
https://github.com/marisbispo/jest aqui está!

e aqui está a versao do node 
![image](https://user-images.githubusercontent.com/64866385/157496576-e3291276-7e16-40b0-a31b-c37be6aeb827.png)

obrigada, @fdaciuk

**Comment by fdaciuk** [comment]
Oi @marisbispo! O problema são as versões das suas dependências.
Instale as versões [mostradas aqui](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#m2a07), que vai dar certo :)

Se você vir alguns warnings falando do Handlebars, pode ignorar, não vai afetar as aulas :)

**Comment by fdaciuk** [comment]
Tenta remover sua node_modules e package-lock.json, e instalar de novo. Pode ser algum cache do NPM :)

**Comment by marisbispo** [comment]
Olá, @fdaciuk deu certo! Agora ta funcionando bem.

Porém, tenho outra dúvida

Fui tentar dar o ```npm i -g getstorybook@1.6.1 ``` e está dando os seguintes erros:

![image](https://user-images.githubusercontent.com/64866385/158261079-3b66a532-d4a7-4f36-bf47-7c0d650b3fc3.png)


O que eu faço nesse caso? :( Mto obrigada!

**Comment by marisbispo** [comment]
esqueci de por isso aqui também: 
![image](https://user-images.githubusercontent.com/64866385/158269545-653d915d-f8dd-4ac0-a023-17925aad1d29.png)

**Comment by marisbispo** [comment]
Consegui resolver com ```npx sb init```

Obrigada!

**Comment by fdaciuk** [comment]
Oi @marisbispo! Desculpe a demora na resposta 🙈 

Que bom que deu certo! Só fica de olho que a forma de escrever stories na versão mais recente do storybook ficou um pouco diferente do que foi mostrado nas aulas.

Os conceitos são os mesmos, mas a forma de escrever mudou um pouco :)
