### ISSUE TITLE
[ MRW#02 ] Atualização do 

### ISSUE THREAD

**Issue by douglas-dreer** [da2k/curso-reactjs-ninja#579]
Não existe o plano ou a possibilidade de fazer uma atualização do curso para que possamos utilizar as versões mais atuais dos das dependências ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @douglas-dreer! Se você quiser pular as aulas de configurações, e usar uma ferramenta como Vite ou CRA, pode usar tranquilamente com a versão mais recente do React e React DOM! Eu só peço pra usar as mesmas versões mostradas no curso pra você seguir exatametne como eu mostrei, pois durante o curso eu mostro a evolução da lib, e o que muda de uma versão pra outra.

Mas da versão 15.5 pra cá, praticamente nada mudou: o que foi removido era esperado que fosse mesmo, e isso eu mostro no curso, e o que foi adicionado não muda o que já existia :)

O problema mesmo são as versões de ferramentas como webpack, por exemplo, já que a cada nova versão "major" a forma de configurar muda bastante.

Mas sim: em breve eu devo fazer uma atualização nos primeiros módulos para facilitar seguir sem precisar fazer configurações, e usando sempre a versão mais recente do React xD

**Comment by douglas-dreer** [comment]
Estou estudando essa ferramenta para iniciar um projeto na empresa, então, tenho que aprender o mais rápido possível junto com o Keyclock. Mesmo assim obrigado pela resposta.

**Comment by fdaciuk** [comment]
Entendi! Bom, o curso é bem longo, então não seria um processo tão rápido seguir pelo curso.
Mas posso te indicar um bootcamp gratuito que eu lecionei no ano passado: obviamente não tem tudo o que tem no curso, mas lá você consegue ter uma boa base pra começar com React.js :)

O conteúdo do bootcamp [está aqui](https://fdaciuk.notion.site/Bootcamp-React-js-B-Academy-04beed6c0dda4b79a28709b0f4cf6042) ;)
