### ISSUE TITLE
Standard style

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#58]
Professor, esta rolando uma discussão na minha faculdade sobre o style do standard sobre não usar ponto e virgula na maioria dos casos, a nível de informação qual sua posição já que o você usa isso ? :), sei que não tem nada haver com o curso mas é uma curiosidade.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CheeseFlan! Não há problema não utilizar ponto e vírgula no JS, pois ele tem uma feature chamada ASI - _Automatic Semicolon Insertion_ - ou inserção automática de ponto e vírgula.

Ele faz isso em vários casos, e existem alguns poucos casos em que não usar ponto e vírgula pode ser um problema, que seria iniciar uma nova linha com **(**, **[** ou **`**.

E esses pontos são cobertos pelo Standard.js, então ele não deixa você iniciar uma nova linha com esses caracteres que ele sabe que vai dar problema :)

Um outro problema que ele também cobre é usar o `return` e colocar o valor retornado em uma nova linha. O ASI vai adicionar o ponto e vírgula logo após o `return`, fazendo a função retornar `undefined`, e o código na linha de baixo do `return` ser ignorado. O standard também trata esse caso :)

Um outro ponto a favor do uso do standard.js: configuração zero. Você simplesmente aceita a configuração de ESLint que ele tem (muito boa, por sinal), e simplesmente usa, sem precisar ficar pensando em regras em cima de regras de linter. Ele já fez isso por você, e fez muito bem :D 

Em resumo: você escrever JS mais limpo (sem ponto e vírgula) e livre de erros, pois ele trata todos esses problemas pra você :)

Bom, esses são os pontos pelos quais eu decidi utilizar o standard.js, e o uso até hoje em todos os meus projetos :)

**Comment by CheeseFlan** [comment]
Vlw professor, muito bom esse esclarecimento, comecei a usar o standard graças ao curso ai quando o pessoal viu meu código já ficou falando, isso não é boa pratica, vai perder performance já que o javascript vai ter que adicionar pra você o ponto e virgula e etc.

**Comment by fdaciuk** [comment]
Dificilmente isso vai afetar performance, a menos que você realmente precise escovar bits, a diferença de velocidade de execução do código é provavelmente será praticamente zero, ainda que você entregue o código como você o escreveu.

Outro ponto importante é que, quando você escreve em ES6+, você transpila seu código para ES5, e depois o minifica para entregar em produção.

As ferramentas de _minify_ são otimizadas para entregar o melhor, menor e mais performático código possível, então essas ferramentas automaticamente adicionam o ponto e vírgula nos lugares realmente necessários, para dar o mínimo possível de trabalho para o motor JavaScript do browser onde o seu código estará rodando.

Então não há com o que se preocupar, pode usar o standard sem medo :)

**Comment by fdaciuk** [comment]
Só um ponto importante de comentar: escrever código JS sem ponto e vírgula e sem um linter pode sim ser perigoso, pois você pode acabar, hora ou outra, fazendo código "da forma errada" que daria problema se não fosse usado ponto e vírgula.

Mas se utilizar um linter bem configurado, como o standard, não precisa se preocupar com isso :)

**Comment by CheeseFlan** [comment]
show de bola obrigado :)

**Comment by fdaciuk** [comment]
Qualquer coisa grita ae :D
