### ISSUE TITLE
[ MRW#06 ] Firefox Error Import

### ISSUE THREAD

**Issue by douglas-dreer** [da2k/curso-reactjs-ninja#580]
Firefox Error

```
Uncaught SyntaxError: import declarations may only appear at top level of a module
```

O código está conforme a video aula.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @douglas-dreer! Consegue subir um repositório aqui no GitHub pra eu ver como ficou seu código? Pode ter faltado alguma configuração :)

Você pode também dar uma olhada se o seu projeto tem todos os arquivos da aula, conforme [esse link](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-06) :)

**Comment by dieg0almeida** [comment]
Veja se no webpack.config.json vc colocou a configuração corretamente. Eu tava com o mesmo problema e era porque eu tinha colocado loaders: 'babel' ao invés de loader: 'babel'.
