### ISSUE TITLE
M2#A31 webpack.config.js

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-reactjs-ninja#581]
Boa tarde

eu coloco o vim webpack.config.js para editar o arquivo, minha tela fica assim:

![image](https://user-images.githubusercontent.com/64866385/160904081-65a2fadb-ccb3-4439-a619-9475ac12a100.png)

por que será?

ai procurando dentro do diretorio um arquivo chamado webpack.config.js eu achei esse e é nele que eu tenho que editar?

![image](https://user-images.githubusercontent.com/64866385/160904827-0c6cbf90-004b-4c1a-91b1-744f8fdb849b.png)

obrigada!

@fdaciuk

**Comment by marisbispo** [comment]
Outra dúvida, @fdaciuk 

Fui para a aula M2#A32 e ao instalar o ```npm install --save-dev html-webpack-plugin@2``` tive esse problema:

![image](https://user-images.githubusercontent.com/64866385/160926766-3e0d6a0d-d794-44ef-a059-8fe618de36a7.png)
![image](https://user-images.githubusercontent.com/64866385/160926845-afe281a0-db12-4b4b-8fd4-f43d231cae13.png)

**Comment by fdaciuk** [comment]
Oi @marisbispo! O `webpack.config` é um arquivo que você precisa criar! Não edite arquivos dentro da `node_modules`, pois eles são arquivos das dependências. Como esse diretório é gerado automaticamente, qualquer coisa que você mudar ali vai se perder na próxima atualização :)

Sobre o problema com o `html-webpack-plugin`, o erro parecer ser por conta da versão do webpack. Nesse caso, a versão que você tem instalada uma versão diferente da que foi mostrada na aula.

Se puder, suba esse projeto no GitHub que eu dou uma olhada aqui pra te ajudar com isso :D

**Comment by marisbispo** [comment]
Oi, @fdaciuk 

Aqui está: https://github.com/marisbispo/github

**Comment by fdaciuk** [comment]
Ah, você está usando o Create React App né? Nesse caso, pode pular as aulas de configurações do webpack, pois o Create React App já vem com todas as configurações que você precisa!

Se quiser estudar sobre as configurações do webpack, aí eu recomendo você começar um projeto do zero, sem o CRA. Pode partir [dessa estrutura](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-10) que foi mostrada no módulo 1 :)

**Comment by marisbispo** [comment]
Ok, @fdaciuk .. ja q esse projeto ja esta em andamento, vou continuar com ele e fazer um do 0 sem o CRA.

Nesse projeto com o CRA, eu retorno no M2#A32? E pulo todos com o nome webpack?

**Comment by fdaciuk** [comment]
Você pode ir fazendo o projeto com CRA sem problemas! Se quiser fazer as aulas de webpack, pode ir fazendo em paralelo, mas com um projeto novo.

Ou então você só vai pulando as aulas de webpack, e depois volta pra fazer só elas :D

**Comment by marisbispo** [comment]
beleza, mto obrigada!
