### ISSUE TITLE
MR2#02 Webpack

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-reactjs-ninja#582]
Boa tarde, @fdaciuk.. eu mais uma vez com uma duvida kkkk

Fui instalar do 0 o webpack e usei todas as dependencias conforme recomendado na aula do futuro, e deu erro de permissao. Inclusive, vi que outra pessoa teve esse problema e você pediu para desinstalar o node e instalar via NVM

Mas o meu node ja foi instalado via NVM e mesmo assim estou com erro de permissao.. Segue a baixo:

![image](https://user-images.githubusercontent.com/64866385/161591164-a355f683-bb2c-4ea1-a820-e0dfc9b77746.png)

O que fazer nesse caso?

Obrigada!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marisbispo! Esse erro em específico parece ser porque o VSCode, quando conectado no WSL, "trava" os arquivos do WSL para não serem alterados por outro lugar.

A solução, segundo o que pesquisei, seria fechar a conexão do WSL com o VSCode, ou só fechar o VSCode inteiro pra você conseguir fazer a instalação, e depois você já pode abrir o VSCode novamente :)

Outro detalhe importante: possivelmente você vai precisar do node v10 para instalar essa versão do webpack. Executando o comando abaixo, você consegue usar ele:

```
nvm install v10
```

O comando acima faz a instalação da v10. Aí sempre que for usar a v10, você só precisa executar:

```
nvm use v10
```

Me diga se isso funciona pra você :)

**Comment by fdaciuk** [comment]
Deu esse erro mesmo com o VSCode fechado?

**Comment by marisbispo** [comment]
Sim, @fdaciuk 

![image](https://user-images.githubusercontent.com/64866385/161634509-ef8d6d8a-10a0-4c89-9f6c-b43c9b792a70.png)

**Comment by fdaciuk** [comment]
Aí você está rodando o comando pelo terminal do VSCode :)
Tenta fechar o VSCode, pra desconectar do WSL. Depois disso, você abre o terminal do Ubuntu (WSL) e tenta rodar novamente o comando :)

**Comment by marisbispo** [comment]
Bom dia, @fdaciuk.. eu com o programa VSCode fechado e segue dando erro. Aqui: 
![image](https://user-images.githubusercontent.com/64866385/161764253-be99bf23-6def-404a-bc42-c1a579a1460c.png)

**Comment by fdaciuk** [comment]
Que estranho.. vou pesquisar algumas coisas pra ver se encontro alguma solução, pois parece ser algo específico com o WSL. Volto aqui em breve xD

**Comment by fdaciuk** [comment]
Parece que dá pra resolver esse problema executando esse comando no WSL:

```
npm config set unsafe-perm=true
```

Depois tente rodar novamente o comando de instalação do webpack. Me diz se funcionou :D

**Comment by fdaciuk** [comment]
Rodar esse segundo comando é mais seguro que usar `sudo`, tenta ele primeiro :)

**Comment by marisbispo** [comment]
Ficou assim, @fdaciuk 

![image](https://user-images.githubusercontent.com/64866385/161795226-a35886ed-5253-42bd-99f4-e28a386ebee6.png)

pelo menos agora nao tá dando erro de permissao, porém continua assim

**Comment by fdaciuk** [comment]
Agora deu certo! Esses warnings são normais :)

**Comment by marisbispo** [comment]
@fdaciuk, mas ele nao deveria gerar  o bundle.js? e o dist?

**Comment by fdaciuk** [comment]
Esse comando que você rodou apenas fez a instalação global do `webpack`. Para gerar o `bundle.js` e o diretório `dist`, você precisa executar o comando `webpack` na raiz do seu projeto :)

**Comment by marisbispo** [comment]
Show, @fdaciuk, certinho

agora uma outra dúvida.. enquanto eu baixava as outras dependencias tive esse erro, sabe dizer o por que?

![image](https://user-images.githubusercontent.com/64866385/161879491-9ce36f6b-36b0-440b-a63d-e4640db6b68e.png)

**Comment by fdaciuk** [comment]
Oi @marisbispo! Se você pegou aquela estrutura que eu te passei, da aula 10 do módulo de React + Webpack, você precisa instalar as dependências que estão no `package.json` antes de instalar dependências novas.

Esse erro está dizendo que o `webpack-validator` não foi encontrado, porque ele está sendo usado, mas não foi instalado ainda.

Como a dependência já está no package.json, você só precisa rodar um `npm install` na raiz do seu projeto, que as dependências que ainda não foram serão instaladas :)

**Comment by marisbispo** [comment]
Oi, @fdaciuk! Eu fiz o passo a passo da aula e deu esse erro. Acabei de  tentar rodar o npm install como você tinha dito, e continua dando o mesmo erro, segue:

![image](https://user-images.githubusercontent.com/64866385/161984439-e3d16015-291d-4a60-b7ce-253141ef6187.png)

**Comment by fdaciuk** [comment]
Oi @marisbispo! Pode ser que você não tenha o arquivo package.json nesse seu projeto, que é o arquivo que têm a lista de dependências que você precisa usar.

Confere se o seu projeto está com [essa estrutura](https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-10) (todos os arquivos e diretórios iguais) antes de começar :)

**Comment by marisbispo** [comment]
@fdaciuk, percebi que nessa estrutura nao tem a pasta dist. Posso excluir?

**Comment by marisbispo** [comment]
@fdaciuk consegui! exclui a pasta node_modules e baixei de novo! deu certo! mto obrigadaaa e desculpa o incomodo!

**Comment by fdaciuk** [comment]
Show @marisbispo! Qualquer diretório auto-gerado pode ser deletado sem medo (e também nada lá dentro deve ser editado, exatamente porque é auto-gerado) xD

Mas que bom que deu certo! Qualquer dúvida, só avisar :D
