### ISSUE TITLE
[ MRW#02 ] Configuração inicial do Webpack

### ISSUE THREAD

**Issue by mandypry** [da2k/curso-reactjs-ninja#583]
Olá tudo bem?
Não estou conseguindo de jeito nenhum configurar o webpack, já apaguei o projeto, reiniciei do 0, e tenho instalado a versão de acordo com o arquivo de dependência. agora, o último erro que tive foi esse aqui:
<img width="644" alt="Captura de Tela 2022-04-07 às 00 55 24" src="https://user-images.githubusercontent.com/26863069/162117058-8b5d983b-2842-4d59-a036-72ee7928e2a5.png">

Eu já tentei também deixar o arquivo webpack.config dentro da pasta do webpack, e mesmo assim ele gera um outro erro: 
<img width="832" alt="Captura de Tela 2022-04-07 às 00 58 13" src="https://user-images.githubusercontent.com/26863069/162117335-4b828d7c-17c1-4c40-8b22-354f44f7b6ee.png">

Eu já subi para o meu repositório, segue o link:
https://github.com/mandypry/react_ninja

Poderia me dar uma ajuda por favor?

Desde já agradeço, 
u 
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @mandypry! Olhei aqui o seu projeto: o problema é que o arquivo `package.json` precisa estar na raiz do seu projeto, junto com o arquivo `webpack.config.js`.

Um outro possível problema é o nome do diretório: as dependências as vezes se perdem se você usar no nome do diretório o mesmo nome do pacote. Você pode renomear o diretório `webpack` para `webpack-test` ou algo assim (qualquer coisa diferente de `webpack`).

Aí você só precisa colocar todos os arquivos dentro desse diretório, e então já conseguirá executar os comandos queu precisa :)

**Comment by mandypry** [comment]
Oi @fdaciuk , eu tentei deixar todos os arquivos fora da pasta (que eu renomeei) e também não rolou(o que pra mim não faz muito sentido, se o node_modules está dentro da pasta né?): 
<img width="159" alt="Captura de Tela 2022-04-07 às 09 11 22" src="https://user-images.githubusercontent.com/26863069/162195761-77c94bdf-1e33-434b-a6ae-c6ab0934f843.png">
<img width="1115" alt="Captura de Tela 2022-04-07 às 09 17 46" src="https://user-images.githubusercontent.com/26863069/162196811-c7294cb1-b87f-4063-a4c2-9a8d77328b90.png">



Tentei colocar todos dentro da pasta também, e também não foi: 
 <img width="283" alt="Captura de Tela 2022-04-07 às 09 13 53" src="https://user-images.githubusercontent.com/26863069/162196180-b2b48fc2-deb9-42d0-8f4d-a5e8d57159d3.png">
2ae76-49e4-4c21-93dd-5f56eb52e1a4.png">
<img width="1111" alt="Captura de Tela 2022-04-07 às 09 14 38" src="https://user-images.githubusercontent.com/26863069/162196293-059ee917-78a4-4c0b-a044-05fae20cd213.png">

**Comment by fdaciuk** [comment]
Oi @mandypry! A `node_modules` precisa estar no mesmo diretório do `package.json` e do seu `webpack.config.js`, então pode mover ela também pra fora :)

Você tinha criado o diretório `webpack` apenas para testar? Se foi, pode remover ele.

A sua configuração deveria ficar assim:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack/mrw-02

**Comment by mandypry** [comment]
Oi Fernando tudo bem? Eu dei uma parada no curso e voltei, finalmente consegui passar dessa parte, deu certo com a sua explicação. Muito obrigada :-)

**Comment by fdaciuk** [comment]
Perfeito @mandypry! Qualquer dúvida, só avisar :D
