### ISSUE TITLE
hotloader nao funciona :(

### ISSUE THREAD

**Issue by marisbispo** [da2k/curso-reactjs-ninja#584]
Olá, @fdaciuk, tudo bem?

Mais uma vez eu aqui

o meu hotloader nao funciona.. nem oq eu fiz a instalação do 0, nem baixando o repositorio aqui do curso... inclusive, quando eu faço alguma atualização ele nao atualiza nem dando f5

Será q estou fazendo algo de errado?

No console parece estar tudo certo:

![image](https://user-images.githubusercontent.com/64866385/162830739-be1249ea-5640-4877-90cb-5558cfd2e4ed.png)

Subi aqui, inclusive caso queira dar uma olhada: https://github.com/marisbispo/react-webpack-hotloader

mto obrigada, estou no aguardo.

@fdaciuk

**Comment by marisbispo** [comment]
Oi, @fdaciuk 

Estranho isso.. porque mesmo baixando o seu repositório, sem mudar nada, ainda nao funciona! Será que é algo com o Windows? Há algo q eu possa fazer?

Outra coisa, na aula M2#A35 eu tive esse problema: 

![image](https://user-images.githubusercontent.com/64866385/162855781-55662fb6-9e67-494e-b921-d74ee968b253.png)

É normal? Na sua aula vi que nao deu e conferi o codigo mais de uma vez.

Muito obrigada!

**Comment by fdaciuk** [comment]
Oi @marisbispo! Não deveria ser um problema no windows não, até porque você está usando WSL2, certo? Mas vou ver se consigo fazer alguns testes no windows pra validar isso :)

Sobre o webpack dashboard: em alguns casos ele pode ser problemático, principalmente no windows. Como ele não é essencial, é apenas para dar uma interface mais bonitinha para o webpack no terminal, pode ignorar essa parte de instalação dele, ok? :)

**Comment by fdaciuk** [comment]
Oi @marisbispo! Pedi pra algumas pessoas que usam windows com WSL2 testarem, e o seu projeto funcionou certinho, inclusive com o hot reload.

Será que pode ser alguma configuração do seu PC?

**Comment by fdaciuk** [comment]
Oi @marisbispo! Conseguiu resolver esse problema? Se ainda não, me dá um toque lá no Discord do curso que a gente puxa uma vídeo chamada e eu te ajudo com isso, pode ser? :)
