### ISSUE TITLE
Canal Discord - Link ou Invite

### ISSUE THREAD

**Issue by danielrochadev** [da2k/curso-reactjs-ninja#585]
Fala Daciuk! Blza?

Desde que comprei o curso na Udemy, eu acabei não visualizando onde está o link pra o canal no Discord.
Tem como compartilhar comigo? (seria um invite?) Pois olhei em mensagens e não consta nada por lá.

Valeuzão!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @danielrochadev!

Você consegue me enviar uma mensagem lá pela Udemy? Te passo o link por lá, pois ele é exclusivo para alunos, e aqui no GitHub é tudo público, ok? :)
