### ISSUE TITLE
M1#A32  AULA sobre checkbox e formulários

### ISSUE THREAD

**Issue by PauloMarquess** [da2k/curso-reactjs-ninja#587]
Não sei se vai abordar mais pra frente no curso , sobre gerenciamento de estados no checkbox .
Eu consigo ultilizar conforme os videos das aulas ,porém se usar mais de um checkbox no formulário setando setstate(!state ),
ele muda o valor true em todos os checks , mais na frente você aborda como resolver a questão ?  
A nível de curiosidade apenas ...

**Comment by fdaciuk** [comment]
Oi @PauloMarquess! Pode sempre deixar a marcação do meu usuário na issue, senão eu não recebo notificação da sua dúvida, ok? :)

Mas sim, mais pra frente no curso nós vamos falar mais sobre formulários e listas de maneira geral, e como controlar estados de cada item de uma lista de forma independente :)
