### ISSUE TITLE
TDD Training

### ISSUE THREAD

**Issue by pgstudies22** [da2k/curso-reactjs-ninja#589]
Olá @fdaciuk!

No TDD training, fiz a implementação dos métodos `map`, `filter` e `reduce` usando `forEach` ao invés de `for`.

Há algum problema em não ter usado o `for`?

**Comment by fdaciuk** [comment]
Nenhum problema @pgstudies22! A ideia ali era mostrar como refazer esses métodos sem usar os próprios métodos disponíveis. Mas o `forEach` pode usar sim :)

**Comment by pgstudies22** [comment]
Massa, obrigado! =D
