### ISSUE TITLE
Aviso sobre atualização do React

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#59]
Galera. Só um aviso

Fiquem atentos o React agora está na versão 16 então se forem começar o curso instalem as seguintes versões:
"react": "^15.1.0",
"react-dom": "^15.1.0"

Por que está dando problema com o método React.createClass. 
Provavelmente o professor vai atualizar mais na frente.

@fdaciuk

**Comment by fdaciuk** [comment]
Isso mesmo @lucianobarauna, obrigado pelo aviso! Eu deixei mapeadas as dependências [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) para não dar problema conforme o andamento do curso :)

**Comment by lucianobarauna** [comment]
Po professor e eu to precisando disso agora tá dando pau no babel aqui :-(

**Comment by fdaciuk** [comment]
Segue as versões do arquivo que não tem erro :D

**Comment by alinebastos** [comment]
Ahhh, então é isso!

**Comment by lucianobarauna** [comment]
@alinebastos 
![image](https://user-images.githubusercontent.com/1054454/31867245-83935bd2-b76a-11e7-9ee5-c5ee420334bb.png)

**Comment by michaelsnogueira** [comment]
Opa.....Esse Issue ajudou bastante 💃

**Comment by rito** [comment]
Como toda pessoa ansiosa, ao começar o curso, vi que a versão mais nova é a 16.1.1. Logo de cara tentei usar esta e apresentou erro.
Depois vim na ISSUE e vi os comentários pra usar a 15.1.0 conforme curso. OK, funcionou.

Agora minha dúvida: Ao longo do curso, nosso aplicativo terá dependências das versões legadas do React ? Ou ao longo do curso isto é sanado com outras funções e outros métodos de construção.

Fico na dúvida, pois caso seja isso, estarei já criando uma primeira aplicação com funcionalidades legadas e isso me preocupa a longo prazo e pra colocar certos WebApps em produção.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rito! Não se preocupe pois, com o decorrer do curso, eu vou mostrando a atualização das dependências e o que mudou (se mudou) em cada uma delas =)

E com o React não é diferente =)

Eu não recomendaria você fazer um app com React antes de ver ao menos os dois primeiros módulos do curso. No primeiro módulo, o foco é nas features do React. No segundo, em partes mais avançadas da lib, atualização para a versão `15.5` (que é o "gancho" pra v16) e configurações para ambiente de produção.

Então esse arquivo com as versões mais antigas foi criado apenas para você conseguir acompanhar os exercícios e exemplos que foram feitos no curso sem erros.

Mas a v16 do React não tem breaking changes! Tudo o que você ver desde o início do curso continua funcionando na v16. O que mudou da v15 pra v16 foi que somente tiraram da lib principal o `prop-types` e o `create-class` (que eu mostro quando atualizamos pra v15.5) =)

Então pode seguir tranquilo que você não vai estar aprendendo algo legado não :D 

E qualquer dúvida, fique à vontade pra perguntar, estou à disposição para ajudar =)

**Comment by rito** [comment]
Pessoal,

Pra quem estiver com dificuldades com a versão 16 do React...

Ao chegar no módulo de webpack já foi difícil novamente acompanhar devido a versão, e por algum motivo, mesmo instalando a versão 15.1 do React, apresentaram alguns erros na função de createClass.

Resolvi fazendo o seguinte:
- instalei normalmente a versão 16.1 do react
- instalei o pacote create-react-class
```
npm install create-react-class --save
```
O arquivo app.js ficou da seguinte maneira:
````
'use strict'

var React = require('react')
var createReactClass = require('create-react-class');

var Title = createReactClass({
    render: function() {
        return React.createElement('h1', null, 'Titulo')
    }
})
export default Title
````

Além disso, no webpack.config.js o loader ao invés de ser *babel* , ficou como *babel-loader*:

```
'use strict'

const path = require('path')

module.exports = {
    entry: path.join(__dirname, 'src', 'index'),
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'

    },
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            include: /src/,
            loader: 'babel-loader',
        }]
    }
}
````

Desta maneira passei a acompanhar corretamente conforme o vídeo!!!

Abs.

**Comment by fdaciuk** [comment]
Oi @rito! Você está certíssimo! Não dá pra acompanhar o curso sem praticar :D 

Essa atualização que você fez, eu ainda vou mostrar mais pra frente =)

Para usar as versões corretas que estamos usando em aula, eu criei um arquivo mapeando cada uma que poderia dar problema. Não é nem o problema com o React em si, e sim com a versão do webpack =)

Veja esse comentário:
https://github.com/da2k/curso-reactjs-ninja/issues/59#issuecomment-336559818

=)
