### ISSUE TITLE
Cursoo está desatualizado webpack server

### ISSUE THREAD

**Issue by aluiziorenato** [da2k/curso-reactjs-ninja#590]
Meu amigo bom dia;

Não consigo fazer o webpack renderizar a pagina como você mostrou na aula mrw#02 e mrw#03,
após iniciar o webpack server e abrir o navegador com o local host o que mostra são os arquivos da pasta raiz e não o index.js ou html.
Muito triste, pois perdi o dia todo nessa brincadeira, não aprendi nada e não avancei no curso que percebi esta desatualizado utilizado o node versão 10 e já estamos na 16.16.0.
fiz tudo que sua aula mandou, mas mesmo assim não funciona, estou desde as 13:00 do dia 02/08/2022 e agora são 00:35 do dia 03/08/2022.
ou seja, mais de oito horas tentando sem sucesso algo que parece não ser solucionado pela sua aula.

@fdaciuk

**Comment by aluiziorenato** [comment]
Fernando;
Depois de uma peregrinação por vários blogs, centros espiritas e algumas sessões de descarregos e uma visita ao monte santo de israel.
Consegui achar no seu github uma pergunta parecida que me levou a solução.
Só não pergunte qual que eu até agora não entendi muito bem.
abraço.
Há, agora são 01:50 da madrugada...

**Comment by fdaciuk** [comment]
Oi @aluiziorenato! Tem que ver se você está usando as mesmas versões das dependências usadas no curso. A versão do Node não afeta a funcionalidade :)

Você pode ver os códigos das aulas aqui:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

Fiz um testes agora com a versão 18.2.0 do Node.js, e o código da aula mrw-03 funcionou certinho :)

Aqui no repositório tem um arquivo com todas as 
[versões das dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que você precisa instalar, e todo o código das aulas.

Procure consultar sempre aqui,e compare com o seu código pra ver se está igual, ok? :)

E qualquer dúvida, fique sempre à vontade para perguntar :)

**Comment by aluiziorenato** [comment]
Meu amigo @fdaciuk  boa noite; Muito obrigado pela sua resposta acima
desculpa ficar incomodando, mas o meu console está mostrando esse erro:
"bundle.js:356 Aviso: React.createElement: tipo é inválido -- esperava-se uma string (para componentes internos) ou uma classe/função (para componentes compostos), mas obteve: object. Você provavelmente esqueceu de exportar seu componente do arquivo em que está definido."

**Comment by fdaciuk** [comment]
Oi @aluiziorenato! Incômodo nenhum meu caro, sempre que tiver dúvidas, esse é o canal para tirar mesmo :)

O erro provavelmente é porque você esqueceu de dar `return` em algum componente que você criou. Dá uma olhada nisso :)

Se não for isso, suba seu código em um repositório do GitHub e poste aqui o link que eu dou uma olhada, ok? :)

**Comment by fdaciuk** [comment]
Oi @aluiziorenato! Vou fechar a issue, mas se vc ainda tiver problemas, me avise que eu te ajudo, ok? :D
