### ISSUE TITLE
m1#a03 - começando a trabalhar com react

### ISSUE THREAD

**Issue by fernandomk6** [da2k/curso-reactjs-ninja#596]
Ocorre um erro quando tento executar o comando http-server após ter feito a instalação tal como feito na aula.

![erro-http-server](https://i.ibb.co/FHTph7s/Screenshot-1.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fernandomk6! Tente usar com o comando `npx` na frente :)

**Comment by fernandomk6** [comment]
É. Funcionou. Mas queria entender por que fazer igual a aula deu erro. Será que houve alguma atualização? Mas obrigado, irei usar o npx de agora em diante para o http-server.

**Comment by fernandomk6** [comment]
Consegui resolver o problema adicionando um script

```json
{
  script: {
  }
}
```

**Comment by fdaciuk** [comment]
Oi @fernandomk6! Sim, com um script também funciona, aí você pode executar com `npm run http-server`.

Só executar o script não funcionou pra você porque o `http-server` só foi instalado localmente no seu projeto, e o diretório do seu projeto não faz parte do PATH do seu sistema, que é onde o sistema procurar por ferramentas de linha de comando (CLIs).

Então, para fazer essa execução de uma CLI instalada localmente, você pode usar sempre uma das duas formas: ou criar um script no `package.json`, como você fez, ou usar o `npx` na frente do nome da CLI, que ela será executada da mesma forma :D 

Mas que bom que deu tudo certo! Qualquer dúvida, só avisar :D
