### ISSUE TITLE
MMR#A06 - Usando sistema de módulos do ES6

### ISSUE THREAD

**Issue by fernandomk6** [da2k/curso-reactjs-ninja#597]
# Cannot use import statement

## Descrição

Fala Fernandão! 
Estou tento esse erro ao tentar visualizar minha página.
Fiz todas as etapas das aulas, mas me deparei com esse erro.
Tentei corrigir por conta própria mas não consegui.

Alguma luz? Acredito que o babel por algum motivo não esteja transpilando o código de entrada

![Cannot use import statement](https://i.ibb.co/h9zf9CH/Screenshot-1.png)

### webpack.config.js

```js
'use strict'

const path = require('path')

module.exports = {
  entry: path.join(__dirname, 'src', 'index'),
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/dist/'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      include: /src/,
      loader: 'babel'
    }]
  },
}
```

### .babelrc

```js
{
  "presets": ["es2015", "stage-0"]
}
```

### Package.json

```json
{
  "name": "react-webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "webpack": "webpack",
    "webpack-dev-server": "webpack-dev-server"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^1.15.0",
    "webpack-dev-server": "^1.16.5"
  },
  "dependencies": {
    "react": "15.4",
    "react-dom": "15.4"
  }
}
```

### Dependências

```log
├── babel-core@6.26.3
├── babel-loader@6.4.1
├── babel-preset-es2015@6.24.1
├── babel-preset-stage-0@6.24.1
├── react-dom@15.4.2
├── react@15.4.2
├── webpack-dev-server@1.16.5
└── webpack@1.15.0
```

@fdaciuk

**Comment by fernandomk6** [comment]
[link completo dos arquivos](https://github.com/fernandomk6/curso-react.js-ninja-react-completo/tree/main/modulo-webpack/projetos/react-webpack)

Esse é o link para visualizar todos os arquivos.

**Comment by fdaciuk** [comment]
Oi @fernandomk6! Baixei aqui seu projeto, coloquei pra executar o `webpack-dev-server` e está funcionando corretamente.

Em que momento você está vendo esse erro?

**Comment by fernandomk6** [comment]
Que estranho. Realmente tentei agora e funcionou normalmente. O erro ocorreu logo que configurei o babel seguindo os passos da aula. Após as configurações atualizei a página do servidor, e recebi essa mensagem. Mas aparentemente reiniciar o servidor resolveu pois não alterei o arquivo. Muito obrigado pelo retorno @fdaciuk e desculpa o incomodo.

**Comment by fdaciuk** [comment]
Ah, pode ser isso mesmo. Se você criou o arquivo com o servidor em pé, e não derrubou e subiu de novo, ele não pega as novas configurações =)

Que bom que deu tudo certo! E não é incomodo nenhum meu caro, fique sempre à vontade para perguntar sempre que tiver dúvidas. Estou aqui pra te ajudar :D
