### ISSUE TITLE
Aula - mrw#08

### ISSUE THREAD

**Issue by fernandomk6** [da2k/curso-reactjs-ninja#598]
Bom dia, boa tarde e boa noite professor.

É mais um daqueles errinhos chatos com as dependências. 
Acho que deixei passar alguma coisa nas aulas, mas o meu servidor (server.js)
não esta subindo corretamente. 

Na aula mrw#08 o senhor termina executando um `npm start` e o servidor roda, você consegue
acessar a pagina.

O meu está dando o seguinte erro no console quando subo o servidor e tento visualizar a página.

```
Refused to execute script from 'http://localhost:3000/dist/bundle.js' 
because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

Não consegui achar o problema, verifiquei se digitei alguma coisa errada mas não achei nada diferente
do mostrado nas aulas, talvez eu tenha deixado passar alguma coisa.

Alguma ideia do que esteja errado?

[Link do diretório dos arquivos. ](https://github.com/fernandomk6/curso-react.js-ninja-react-completo/tree/main/modulo-webpack/projetos/react-webpack)

Desde já obrigado pela atenção 😅

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fernandomk6! Tem um _typo_ no seu `server.js` [nessa linha](https://github.com/fernandomk6/curso-react.js-ninja-react-completo/blob/main/modulo-webpack/projetos/react-webpack/server.js#L8): era pra ser `publicPath`, você escreveu `publichPath` (com um `h` a mais no final de `public`) =)

**Comment by fdaciuk** [comment]
Sem problemas meu caro! Isso é bem comum de acontecer, na verdade, já que JavaScript é uma linguagem com tipagem fraca. Ele não te avisa quando você tem esse tipo de erro, por isso é importante ir escrevendo aos poucos e já testando pra ver se nada quebrou :D
