### ISSUE TITLE
React no frontend

### ISSUE THREAD

**Issue by fernandomk6** [da2k/curso-reactjs-ninja#599]
Olá professor, dessa vez não é um erro é uma duvida com relação ao ambiente no
qual o react é realmente executado.

Se o react é um lib que roda no frontend, por que é preciso usar o node? eu sei que o node não é
obrigatório, que da para rodar react apenas com um "CDN", e nesse caso ele seria totalmente frontend.
Mas com o react no ecossistema node, usando webpack, babel e muitas outras dependências instaladas via npm, 
o que exatamente é processado no lado do cliente e o que é processado no servidor (no caso o meu localhost)?

Desde já obrigado pela atenção professor. O curso está excelente.

@fdaciuk

**Comment by fernandomk6** [comment]
Exelente explicação professor muito obrigado. 

Entendi, o node então trabalha (no back) para fornecer o necessário para rodar tudo no frontend. Esse tudo
no final das contas acaba sendo o bundle. Correto? Acredito ter pego o fio da meada.

Muito obridado.

**Comment by fdaciuk** [comment]
Exatamente! Não só o bundle, mas tudo o que o webpack te oferece, é feito com Node.js =)

**Comment by fernandomk6** [comment]
Show. Valeu professor.
