### ISSUE TITLE
Teste componente node

### ISSUE THREAD

**Issue by RodrigoWP** [da2k/curso-reactjs-ninja#6]
Eae @fdaciuk ,

Estou com um duvida um tanto inciante, mas estou me quebrando um pouco.

Qual é a forma correta de utilizar lib's externas em componentes? Estou fazendo umas testes com uma lib de node qualquer e ocorre um erro na renderização do componente, consegue me ajudar?

Segue o fonte:

https://github.com/RodrigoWP/learning-react/blob/master/src/app.js

**Comment by fdaciuk** [comment]
Fala @RodrigoWP! Então cara, nesse caso, o problema não é a lib externa, mas sim que você está tentando usar uma lib de _server_ no _client_.

Nesse caso específico, você precisa usar essa lib no _server_, e passar as informações para _client_, para que possa utlizar com o React =)

Agora, usando libs de frontend que precisam manipular DOM, por exemplo, você pode inicializá-las no `componentDidMount`.

No curso tem uma aula falando exatamente sobre esse assunto de usar libs externas com React =)

Ficou claro?

Qualquer dúvida me avise =)

**Comment by RodrigoWP** [comment]
@fdaciuk Entendi cara. Valeu!
