### ISSUE TITLE
M2#A121 & A122 Duvida

### ISSUE THREAD

**Issue by fmussap** [da2k/curso-reactjs-ninja#60]
#### M2#A121

Seria errado tratar o state files com um array visto que Object.keys(localStorage) ja retorna um array?
Pergunto porque desta forma seria mais simples atualizar seu valor:

const files = Object.keys(localStorage)
this.setState({ files })

#### M2#A122
Apos remover um md poderiamos apenas atualizar o state de files lendo novamente o localstorage?

localStorage.removeItem(this.state.id)
this.setState({ files: Object.keys(localStorage) })

Pergunto isso pois tambem ficaria mais simples

Obrigado Fernando

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fmussap! Na verdade não, porque `Object.keys` retorna um array somente com as **chaves** do objeto. Então, ao salvar dessa forma, você vai perder todos os dados que estão internamente em cada objeto.

O seu objeto é algo assim:

```
{
  chave1: { title: 'File 1', content: '# File 1' }
  chave2: { title: 'File 2', content: '# File 2' }

}
```

O `Object.keys` vai pegar esse objeto e retornar somente `['chave1', 'chave2']`, entendeu? Ele não vai transformar o objeto em um array :)

Ficou claro? :)

**Comment by fmussap** [comment]
Obrigado @fdaciuk 

A parte do Object.keys ja tinha ficado claro.
A duvida surgiu durante a aula e eu tento fazer antes de ver como fiocu sua solucao.

O que fiz foi no state.files fica o array com as chaves apenas
no state.values armazeno { title: 'um titluto', content: 'seu conteudo' }.

Cada vez que abro, crio ou edito uma chave(files) atualizo seu conteudo no state.values.

* Para pegar o conteudo da chave uso JSON.stringify.
* Para gravar conteudo uso JSON.parse

Desta forma o codigo tinha ficado menor mas fiquei na duvida se haveria algim problema de performance lendo Object.keys(localStorage) para atualizar meu array de files.

**Comment by fdaciuk** [comment]
Ah, entendi :)
Cara, não vejo problema em fazer isso xD

O que é mais custoso nesse processo todo é o `JSON.stringify` e `JSON.parse`. Para uma aplicação pequena não vai dar muita diferença, mas aplicações maiores você provavelmente vai ter que tentar usar o mínimo possível esses métodos.

No mais, dessa forma que você fez resolve bem sim :)

**Comment by fmussap** [comment]
Obrigado Fernando.

Duvida resolvida.

**Comment by fdaciuk** [comment]
Show \o/
Qualquer coisa avisa ae :D
