### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by fernandomk6** [da2k/curso-reactjs-ninja#601]
Olá Professor!

Estou atualmente no modulo 1 parte 2. E gostaria de saber algumas coisas sobre o
conteúdo no decorrer do curso

- Será abordado o conceito de hooks?
- Os componentes no decorrer do curso, serão criados com class ou com function?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fernandomk6! Em todo o curso, você vai aprender sempre a usar componentes como funções. Nos primeiros módulos ainda não existiam hooks, então eu mostro como usar classes apenas para manipular estados.

No módulo 4 eu já mostro como usar o React sem classes, apenas com os hooks para manipulação dos estados.

Você pode seguir com o módulo 1, e ao final dele, pode ir direto para o módulo 4 se quiser ver a parte apenas do React.

No módulo 2 você vai aprender algumas coisas mais avançadas, principalmente voltadas à configuração do webpack, e no módulo 3 você irá aprender sobre Redux.

Então, se quiser focar só no React nesse início, você pode pular os módulos 2 e 3, e deixar para assistí-los no futuro, se quiser =)

**Comment by fernandomk6** [comment]
ICaramba professor. Muito obrigado por esse feedback. Eu certamente iria me desmotivar nos módulos 2 e 3, pois não tenho muito interesse em aprender "outras coisas". Meu foco é realmente o react. Apesar de hoje não ser muito usado (pelo pouco que sei) estou gostando de aprender como funcionam os componentes class, eu acho mais facil de entender. Hooks a primeira vista me pareceu algo "magico" enquanto as classes eu sei exatamente como funcionam, me sinto mais seguro e me mostraram como as coisas funcionam ali por baixo dos panos.

Mas depois de dominar o básico com classes eu vou focar em usar apenas o modo funcional e usando hooks.

Obrigado pelo toque sobre o conteúdo dos módulos isso vai fazer muita diferença. 
@fdaciuk

**Comment by fdaciuk** [comment]
Boa @fernandomk6! Acho que vai ficar tranquilo de pegar como os hooks funcionam no módulo 4, pois lá nós construímos duas aplicações de tamanho razoavelmente grande: um sistema de pizzaria. Criamos tanto o backoffice ou área de administração, onde são cadastradas as pizzas, como a parte do "frontend", onde os pedidos são feitos com base nos tamanhos de pizza e sabores inputados no backoffice =)

Ah, uma outra coisa que eu não citei: apesar do módulo 2 ter bastantes informações sobre configuração do webpack, ele também traz algumas informações importantes, sobre testes unitários, e a criação de mais algumas aplicações para praticar o que está sendo aprendido.

Você pode também fazer o módulo 2, só "pulando" as partes de configuração, e usando o Create React App para construir as aplicações ao invés de configurar o webpack na mão, como mostrado.

Em breve eu devo atualizar esses primeiros módulos pra organizar um pouco melhor e separar bem essa parte de configuração das aulas que falam só sobre React, mas fica aí também como opção, se você quiser fazer assim.

Esse conhecimento das aplicações criadas no módulo 2 podem facilitar o aprendizado do que será visto no módulo 4 :D
