### ISSUE TITLE
Recomendação de curso firebase

### ISSUE THREAD

**Issue by fernandomk6** [da2k/curso-reactjs-ninja#603]
Olá professor, eu andei bisbilhotando aqui, e vi que em algum(s) de seus projetos você vai usar o
firebase. 

Eu tenho bastante interesse em aprender firebase.

Como o curso é de React, acredito que não será abordados conceitos mais 
avançados, ou "irá a fundo" no firebase. 

Por esse motivo, você teria algum curso seu, que ensina a usar o firebase? 

Ou se não, teria alguma recomendação de curso
pagos ou gratuitos sobre firebase de um professor que você recomende?

Desde já muito obrigado. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @fernandomk6! Eu não mostro tudo o que o Firebase oferece, mas nós entramos em bastantes detalhes do uso dele sim. Não tenho nenhum curso para recomendar no moemento, mas após ver as aulas de Firebase, acredito que vai ser muito tranquilo você conseguir encontrar algo pela documentação, que é muito rica e detalhada =)

**Comment by fernandomk6** [comment]
Obrigado Professor. Irei acompanhar então suas aulas sobre o firebase depois faço um overview da doc oficial.
