### ISSUE TITLE
Atualização de código incorreto =)

### ISSUE THREAD

**Issue by lanaiconceicao-meli** [da2k/curso-reactjs-ninja#605]
Olá pessoal, tudo bem?

Estou fazendo o curso de React Ninja, e notei no vídeo **9. MRW#02 - Configuração básica do Webpack** no minuto `7:38` que na hora de criar o script do bundle do webpack no arquivo` index.html`, o acesso da página está como `/dist/bundle.js`, e na verdade o caminho seria `dist/bundle.js`. Sei que é algo simples e que muita gente consegue arrumar sozinha, mas estou comentando mais porque quando eu estava no início dos estudos eu seguia exatamente o que estava no curso, e esse era o tipo de coisa que me travava e não conseguia continuar e muitas vezes desistia kkk

Amando o curso! Ótimo dia, e obrigada!

@fdaciuk

**Comment by lanaiconceicao-meli** [comment]
**Atualização:** Gente vi aqui que no vídeo ele consegue subir o servidor mesmo assim e funciona... pra mim não funcionou, mas se funciona assim então desconsiderem a mensagem acima =) obrigada!

**Comment by fdaciuk** [comment]
Oi @lanaiconceicao-meli! Se quiser compartilhar o repositório onde está o seu código, eu posso dar uma olhada pra entender porque não funcionou.

Deveria funcionar com a barra no início porque o domínio principal é a raiz da aplicação, e o diretório `dist` está logo abaixo da raiz =)

O correto é sempre usar a barra, pois se você estiver usando algum sistema de roteamento na sua aplicação, `dist/bundle.js` pegaria o caminho de forma relativa à rota que você está no momento, enquanto que `/dist/bundle.js` vai pegar sempre à partir da raiz =)

**Comment by lanaiconceicao-meli** [comment]
Olá @fdaciuk , obrigada pela resposta!

Aqui meu repositório: https://github.com/lanaiconceicao/course-react/tree/main/modulo_1/react-webpack

Hummmm entendi, faz sentido mesmo! Que esquisito então o meu não ter funcionado com /dist/bundle.js 🫠

**Comment by fdaciuk** [comment]
Oi @lanaiconceicao-meli! Testei aqui o seu código, e funcionou corretamente com a barra e sem a barra =)

Como você está subindo o servidor para testar?

**Comment by lanaiconceicao-meli** [comment]
@fdaciuk hummmmmm daí tu realmente me pegou no pulo do gato kkkk estou subindo com o Live Server, uma extensão do VSCode, achou o problema então!

**Comment by fdaciuk** [comment]
Entendi! De qualquer forma, não deveria dar problema com o live server, desde que o servidor entenda que a raiz do projeto é onde está o arquivo `index.html`. Como o diretório `dist` está "do lado" desse arquivo, ele seria corretamente acessado via `/dist`, e o seu código vai funcionar como esperado.

Só confirma qual diretório ele está usando como raiz, e pode continuar usando ele sem problemas =)
