### ISSUE TITLE
M1#A13

### ISSUE THREAD

**Issue by kaiansamuel** [da2k/curso-reactjs-ninja#607]
Boa noite Professor!
Ao final da aula M1#A13 o App não renderizou o component Square

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kaiansamuel! Suba o seu projeto em um repositório aqui no GitHub e passa aqui o link que eu dou uma olhada, ok? =)

**Comment by kaiansamuel** [comment]
https://github.com/kaiansamuel/React_Ninja/blob/main/src/App.jsx

**Comment by fdaciuk** [comment]
O erro está [nessa linha aqui](https://github.com/kaiansamuel/React_Ninja/blob/main/src/Square.jsx#L8). `height` é com `ht` no final. Você escreveu com `th` =)

**Comment by kaiansamuel** [comment]
Obrigado Fernando! =)

**Comment by fdaciuk** [comment]
Qualquer dúvida, só avisar!
