### ISSUE TITLE
Sobre o curso

### ISSUE THREAD

**Issue by kaiansamuel** [da2k/curso-reactjs-ninja#608]
Professor estou terminando o módulo 2...estou meio perdido por conta das classes, sendo 0ouc9 usado hoje em dia...é legal pra conhecer e tal, mas o que eu quero saber ...é se todo resto do curso é dessa forma em classes...

**Comment by SallesCosta** [comment]
@kaiansamuel eu sou aluno.. e estou terminando. Pelo que eu ví, não. Logo logo passamos para funções, react 16 e outras formas de pensar o código em React.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kaiansamuel! 

No módulo 4 eu apresento o uso dos hooks, então pode seguir sem medo que os conceitos que você está aprendendo serão úteis inclusive nos componentes de função :D 


> Observação importante: Quando tiver uma dúvida, pode sempre manter a marcação do meu username na issue, senão eu não recebo notificação da sua dúvida, ok? :D
>
> Obrigado por me marcar @SallesCosta =)
