### ISSUE TITLE
Probelmas com a função .error() em M1#45

### ISSUE THREAD

**Issue by Leone98** [da2k/curso-reactjs-ninja#609]
Na aula M1#45, você mostra que existe a opção de utilizar as funções .then() em caso de sucesso da requisição, .error() em caso de falha, e .always() independentemente de sucesso ou falha. Na aula você usa o .then para impedir que o usuário modifique a entrada na barra de e depois o .always para liberar novamente. Eu vi que quando procuro um usuário inexistente, as informações do usuário anterior continuam na tela. Pensei então em testar a função .error e excluir as informações existentes. O código ficou depois do fechamento da função then() e antes do .always(), e foi implementado assim:

```

                .error((err) => {
                    this.setState({
                        userinfo: null,
                        repos: [],
                        starred: []
                    })
                    console.log(err)
                })

```

Entretanto, o código dá um erro na primeira linha do código mostrado acima, com a seguinte mensagem:
"Uncaught TypeError: (0 , _app.js:47 Uncaught TypeError: (0 , _ajax2.default)(...).get(...).then(...).error is not a function"

O código acima está implementado de forma incorreta? Como poderia resolver esse erro?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Leone98! O nome do método é `.catch`, não `.error` =)
