### ISSUE TITLE
Duvida ao passar as props para frente.

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#62]
Professor tem uma parte no código que é assim `<Header {...props} />` , ate ai tudo bem eu entendo que esta passando as props, mas como isso é feito já que ao usar o spread operator ele vai espalhar e um objeto, e pra passar uma prop normalmente não seria assim ? `<Header value={value}>` , como é que funciona essa parada do `{...props}`, ai no react ?

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @CheeseFlan! As props são passadas como um objeto mesmo. Seria o mesmo que fazer:

```jsx
<Header {...pros} />
<Header {...{ prop1: 'value1', prop2: 'value2' }} />

// Esse não é exatamente igual, pois ele não usa o `React.createElement`, 
// só invoca a função - se o `Header` for uma função - mas a ideia é a mesma:
Header({
  prop1: 'value1',
  prop2: 'value2'
})
```

Ficou claro? :)

**Comment by CheeseFlan** [comment]
A saquei, tipo pelo header ser um componente, mas em seu interior uma função, é como se eu tive-se passando parâmetros para um função.

**Comment by fdaciuk** [comment]
Isso mesmo! Lembra no início do curso que vimos como o JSX funciona? Que o babel compila a tag `<div>oi</div>` para a função `React.createElement('div', null, 'oi')`?

É isso :)

**Comment by CheeseFlan** [comment]
Show, bem lembrado, obrigado ae professor :D

**Comment by fdaciuk** [comment]
Qualquer coisa só avisar :)
