### ISSUE TITLE
[M1A_12] - Import

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#63]
Fala professor !

Seguinte pintou uma dúvida. Quando utilizamos dessa forma:
```
import React, { Component } from 'react'
```
E chamo a class da maneira abaixo ela funciona
```
class App extends Component {
...
}
```
Eu dei uma olhada aqui na docs do import antes de tirar minha dúvida
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/import

Pelo o que entendi o certo seria o React importar todo conteúdo de `form 'react' `, certo ?
Mais quando eu chamo dessa forma ela não funciona e estoura um erro.
```
class App extends React{
...
}

Por quê acontece isso ?


```

@fdaciuk

**Comment by gabrielferreiraa** [comment]
Desculpe a intromissão @fdaciuk, mas
@lucianobarauna parece que não te encontrei no slack do queroserninja :thinking:
Entra lá que a galera sempre ajuda e da umas dicas bem legais
https://queroserninja.slack.com

**Comment by lucianobarauna** [comment]
Opa @gabrielferreiraa, Agradeço muito o convite !
Quem criou o canal rs ?
Olha eu não estou conseguindo entrar nele pode me mandar o convite meu email é baraunaluciano@gmail.com

**Comment by gabrielferreiraa** [comment]
Provavelmente o @fdaciuk precisa te enviar o convite então :tired_face:

**Comment by lucianobarauna** [comment]
poxa @fdaciuk tá me panelando auehauiehauie!!!

**Comment by fdaciuk** [comment]
Valeu @gabrielferreiraa, já adicionei o @lucianobarauna :D 

@lucianobarauna, vamos à sua dúvida: o `Component` é uma `class` que é exportada pela lib `react`. É essa função que você precisa extender para criar um componente.

No caso, se você importar assim:

```js
import React from 'react'
```

O que vai acontecer é: no módulo `react` tem um objeto que foi exportado com `export default`. Esse objeto é que vai ser atribuído para a variável `React`.

Como o objeto exportado também tem como propriedade a class `Component`, você ainda pode extender o componente assim:

```js
class App extends React.Component {
}
```

Na prática, seria mais ou menos isso aqui:

*arquivo em node_modules/react:*

```js
const React = {}
class Component {}

React.Component = Component
export Component
export default React
```

É mais ou menos isso que acontece no componente do React. Aí você pode importar de várias formas:

```js
import React from 'react' // isso vai importar o objeto que foi exportado com `export default`
import { Component } from 'react' // isso vai importar a class Component, que foi exportada em `export Component`

class App extends React.Component {} // isso funciona porque foi criada uma propriedade `Component` no objeto `React`, que foi exportado com `export default`
```

Ficou claro? :)

**Comment by lucianobarauna** [comment]
Entendi sim eu só fiquei perdido nessa forma abreviada de declarar.
```
import React, { Component } from 'react'
```

**Comment by fdaciuk** [comment]
Show! Nesse caso, você importa o `React`, que foi exportado com `export default`, e o `{ Component }`, que precisa ter o `import` nomeado, pois foi exportado só com `export` :)

Sempre que você exportar algo de um arquivo somente com `export`, o nome que você usou para exportar deve ser o mesmo nome que você vai usar para importar.

Você ainda pode renomear ele na hora de importar, usando o `as`:

```js
import React, { Component as NewName } from 'react'
```

Agora você não tem mais a class com nome `Component` disponível para usar no seu arquivo, e sim com o novo nome atribuído, que será `NewName`.

Dessa forma, você pode criar sua class assim:

```js
class App extends NewName {
}
```

:)

**Comment by lucianobarauna** [comment]
Vlw professor @fdaciuk  !!!

**Comment by fdaciuk** [comment]
Qualquer dúvida avisa ae :D
