### ISSUE TITLE
Context-API

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#64]
Professor com relação a Context API, e recomendável utilizar ou usar a forma padrão do react, supondo que esta API fique estável (por alguma motivo :) ), ou esse conteúdo fica a nível de conhecimento pra entender como react funciona como um todo e caso agente encontre pela frente alguma aplicação que esteja utilizando ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @CheeseFlan! A ContextAPI, quando ficar estável, provavelmente terá uma implementação diferente :)

O importante é entender como ela funciona, e os gaps que ela gera, para saber quando é possível usar.

Você pode sim usar ela em uma aplicação, mas para usar com segurança, é importante isolar o uso dela, como mostramos no curso :)

O redux faz um uso parecido com o que foi mostrado no curso. Ele é um exemplo claro que dá pra usar com segurança a ContextAPI, isolando sem que você precise saber que está usando ela :)

O React Router também usa a ContextAPI.

O grande ponto é isolar o uso dela, para que, quando ela for alterada, você ter que mudar somente em um único lugar, sem precisar ficar refatorando toda a sua aplicação :)

**Comment by CheeseFlan** [comment]
Show de bola, :+1: , a questão é só o cuidado bom demais :dagger:

**Comment by fdaciuk** [comment]
Isso mesmo! Só lembrar que usar ContextAPI é como usar variáveis globais, então, se **realmente** precisar, use Redux.

Se o Redux não resolver para o que você precisa - o que é bem difícil - ou você for criar uma lib própria de temas, i18n, etc., então você pode fazer sua própria implementação, seguindo as diretrizes mostradas no curso para usar com segurança :)

**Comment by CheeseFlan** [comment]
Muito bom, esse conceitos de ContextAPI, vai ajudar muito nas aulas de Redux e caso seja necessário, me deparar com uma aplicação que terei que utilizá-lo de alguma forma :+1:

**Comment by fdaciuk** [comment]
Isso ae! Bom, qualquer dúvida, já sabe :D
