### ISSUE TITLE
Enzyme adapter

### ISSUE THREAD

**Issue by Joaoh3326** [da2k/curso-reactjs-ninja#65]
Pessoal para aqueles que estiverem no modulo 2 e estão vendo a aula(M2#A140) sobre enzyme, o enzyme sofreu uma mudança e precisa de uma configuração extra, como no curso ate esse ponto estamos usando React 15.5, é só fazer as seguintes configurações que vai funcionar:

1 - Instalação
`npm i --save-dev enzyme enzyme-adapter-react-15` ou `yarn add --dev enzyme enzyme-adapter-react-15`

2 - Configuração
```
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-15';

Enzyme.configure({ adapter: new Adapter() });
```
e pronto, seus testes irão funcionar :D

@fdaciuk

**Comment by fdaciuk** [comment]
Boa @CheeseFlan! Deixando marcado como dica :D
