### ISSUE TITLE
[M1A_43] higher order functions vs clojure

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#66]
Professor.
Achei melhor colocar aqui para ficar como um histórico para os outros alunos do que se perder no slack.

Uma dúvida nessa aula o senhor fala sobre higher order functions e eu fiquei pensando se não é a mesma coisa que uma clojure.

Estou certo ?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @lucianobarauna! Nem sempre =)
Uma _closure_ é uma função que foi retornada por outra. A função mais interna, que foi retornada, e conseguiu acessar o conteúdo de fora dela, mas dentro da primeira função, nós chamamos de _closure_.

Uma _higher order function_ pode ser uma closure, mas ela também pode apenas receber uma função por parâmetro e executar ela, sem retornar uma nova função ;)

Pra tentar exemplificar as diferenças:

```js
function plus (value) {
  return function (amount) {
    value + amount
  }
}

const plusOne = plus(1)
console.log(plusOne(2)) // 3

// No exemplo acima, `plus` é uma higher order function, e a função interna que ela retorna é uma closure.

// Agora uma HOF que não é closure:

function map (array, func) {
  let newArr = []
  for (let i = 0; i < array.length; i++) {
    newArr.push(func(array[i]))
  }
  return newArr
}

// a função `map` é uma HOC, pois recebe uma função via argumento, que será executada no futuro, mas não tem closure nela, pois ela não retorna nenhuma nova função. Para transformar o `map` em uma função com closure, poderíamos fazer ele receber somente um parâmetro por vez. Primeiro o array, e então ele retornaria uma função. Depois, na função que ele retorna, ele recebe essa segunda função que vai ser usada no for:

function map2 (array) {
  return function (func) {
    let newArr = []
    for (let i = 0; i < array.length; i++) {
      newArr.push(func(array[i]))
    }
    return newArr
  }
}

// veja que a função mais interna em `map2` tem acesso ao array passado para a função `map2`. Essa função interna é uma closure.
```

Ficou claro? :)

**Comment by lucianobarauna** [comment]
Então um Clojure é uma função que está dentro de outra função e que ele pode ser retornada ou não.

Uma HOF é uma função que é o primeiro nível e internamente ela pode ter ou não uma clojure.

Complicado isso hein rs

**Comment by fdaciuk** [comment]
Não se apegue aos nomes, mas procure entender os conceitos, é o mais importante =)

Você pode passar uma função via argumento, e fazer alguma coisa com ela no futuro: tanto executar ela logo após a primeira função ser executada, como retornar uma nova função que será usada depois, pois ela precisa de um outro argumento que pode chegar a ela apenas em algum momento no futuro, não no exato momento em que você está chamando a primeira função =)

Mas isso fica mais claro quando você pratica! No curso vamos ver vááááários exemplos de HOC e closure, pode ficar tranquilo :)
