### ISSUE TITLE
Erro ai criar html

### ISSUE THREAD

**Issue by nibarcellosdev** [da2k/curso-reactjs-ninja#67]
Aparece isso ai tentar criar o html
![sem titulo](https://user-images.githubusercontent.com/29047361/32475081-2b78716e-c357-11e7-8612-f2fef08b3c1a.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @nibarcellosdev! Não entendi sua dúvida. O que você está tentando fazer?
Se está tentando carregar um `index.html` na porta `8080`, você precisa ter esse arquivo na raiz onde você está rodando o servidor estático. Pelo seu print, parece que você tem um arquivo `index.html.swp`, não o `index.html` :)

Se puder detalhar melhor o que você está tentando fazer, ou subir o projeto como está em um repositório aqui no GitHub, fica mais fácil entender =)

**Comment by nibarcellosdev** [comment]
Então, eu crio um diretório e crio um vim index.html , mas cria um .index.html.swp
![image](https://user-images.githubusercontent.com/29047361/32513190-8bc0f12a-c3e0-11e7-9b91-d4a8d078e2e8.png)

**Comment by nibarcellosdev** [comment]
Então eu crio um in

**Comment by fdaciuk** [comment]
Conseguiu @nibarcellosdev ?
