### ISSUE TITLE
Babel não compila JSX , erro

### ISSUE THREAD

**Issue by nibarcellosdev** [da2k/curso-reactjs-ninja#69]
`'use strict'

import React from 'react'
import ReactDOM from 'react-dom'
import Title from './app'

ReactDOM.render(
	<Title />,
	document.querySelector('[data-js="app"]')
)`

Não tá reconhecendo, no terminal tá dando ERROR in ./src/index.js
Module parse failed: C:\Users\Nicolas\Desktop\react-webpack\src\index.js Unexpected token (8:1)
You may need an appropriate loader to handle this file type.

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @nibarcellosdev! Como está sua configuração do webpack? 
Dica: para colocar código aqui, coloque 3 crases uma linha antes, e 3 crases uma linha depois do código :)

**Comment by nibarcellosdev** [comment]
```` 'use strict'

const path = require('path')

module.exports = {
	entry: path.join(__dirname, 'src', 'index'),
	output: {
		path: path.join(__dirname, 'dist'),
		filename: 'bundle.js',
		publicPath: '/dist/'
	},
	module: {
		loaders: [
		{
			test: /\.js$/,
			exclude: "/node_modules/",
			include: "/src/",
			loader: "babel-loader"
		}
		]
	}
}

**Comment by nibarcellosdev** [comment]
Consegui arrumar aqui cara, instalei o npm que você colocou na dependência npm install --save-dev babel-preset-react@6

**Comment by fdaciuk** [comment]
Show de bola! Eu ia dizer que poderia ser ou algo na config do webpack ou alguma versão de dependência :)

Mas fica tranquilo que vamos atualizando durante o curso, essa versão é só pra você conseguir acompanhar a primeira parte :D 

Bom, qualquer dúvida, avisa ae :)
