### ISSUE TITLE
M1#A11- Interpolação

### ISSUE THREAD

**Issue by danieldocki** [da2k/curso-reactjs-ninja#7]
Tem dois tipos de interpolação:

```
<h1>Olá {this.props.name + ' ' + this.props.lastname}!</h1>
```

```
<h1>{`${this.props.name} ${this.props.lastname}`}!</h1>
```

mas por prática de ruby eu fiz assim:
```
<h1>{this.props.name} {this.props.lastname}!</h1>
```

e funcionou, a diferença delas está somente na escrita? porque essa última me pareceu mais agradável.

**Comment by fdaciuk** [comment]
Sim @danieldocki! Você pode fazer das 3 formas =)
A terceira forma é a forma de interpolação do JSX, então é válida também. Você pode usar sem problemas =)

**Comment by danieldocki** [comment]
@fdaciuk Obrigado :)

**Comment by fdaciuk** [comment]
Precisando, grita ae =)
