### ISSUE TITLE
MRW#01 createreactapp x workflow-reactjs

### ISSUE THREAD

**Issue by leomendesm** [da2k/curso-reactjs-ninja#72]
Queria saber a diferença entre usar a ferramenta que o Facebook criou pra iniciar os projetos para um boilerplate customizado como o workflow que você disponibiliza. O que levar em conta na hora de escolher uma das opções?
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @leomendesm! Basicamente a opção de customização. O CRA não permite que você adicione qualquer tipo de configuração ao webpack, por exemplo, a menos que você ejete, o que vai trazer muitos arquivos e configurações para a raiz do seu projeto, e pode acabar sendo complicado de manter.

A ideia de criar o boilerplate é principalmente a facilidade de customizar como você quiser, mas ainda assim mantendo-o simples o suficiente para criar aplicações menores e mais rápidas =)

**Comment by fdaciuk** [comment]
Outro ponto importante também de eu estar criando o boilerplate junto com o curso, é que o aluno terá também o conhecimento necessário se precisar adicionar novas configurações de qualquer tipo, e escolher formas melhores de otimizar, sempre baseado em como sua aplicação está sendo desenvolvida =)

**Comment by leomendesm** [comment]
Entendi, sempre usei o cra pra fazer os testes pela facilidade de simplesmente rodar um comando e estar tudo pronto, mas agora parando pra olhar o webpack estou começando a me interessar pela customização.

**Comment by fdaciuk** [comment]
Legal! Só entenda que não é um problema usar o CRA, pelo contrário! Ele facilita muito pra começar qualquer projeto =)

Mas, se houver necessidade de customização, aí com ele começa a complicar =)

**Comment by llmdev** [comment]
Está era minha duvida, CRA ajuda muito mas acho que todo bom ninja tem que conhecer os fundamentos, o basico de tudo ;D

**Comment by fdaciuk** [comment]
Isso aí @llmdev!
