### ISSUE TITLE
Props Validation Func

### ISSUE THREAD

**Issue by llmdev** [da2k/curso-reactjs-ninja#73]
22k, mano Seguinte..

Acompanhando o video M1A41, nao consigo me librar de uma validação de props..

> ./src/components/search.js
  Line 4:  'handleSearch' is missing in props validation  react/prop-types

Os arquivos estao aqui no meu repo.. 
https://github.com/llmdev/curso-react/blob/master/src/components/search.js

Estou usando RCA..

Dentro do Search ele não recebe a função, parece que se perde...

Pode me ajudar :D ?

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, eae @llmdev!
O problema é aqui:
https://github.com/llmdev/curso-react/blob/master/src/components/search.js#L14

É `.protTypes`, não `prototype` xD

**Comment by llmdev** [comment]
Putz mano autocomplete me lascou vlw.. pode fechar..

**Comment by fdaciuk** [comment]
haha! Qualquer coisa grita ae =)
