### ISSUE TITLE
Posso importar as handles ?

### ISSUE THREAD

**Issue by llmdev** [da2k/curso-reactjs-ninja#74]
Mano tire uma duvida, estava aqui no almoço pensando...

nao posso importar minhas funcoes, no lugar de passar via props ?

tipo:

> import Funcao from './funcao'

> onClick={funcao}

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @llmdev! Poder, até pode. Tudo vai depender da ação que você vai fazer internamente. Se essa função precisar fazer algo que necessite um re-render, você vai ter que garantir, de alguma forma, que novas props ou um novo state seja passado =)

**Comment by llmdev** [comment]
Não consigo guardar states nesses arquivos separados né ? É possível modularizar essas funções ?

**Comment by fdaciuk** [comment]
Se for pra guardar _state_ nessas funções isoladas não faz muito sentido isolar, usa `class` mesmo xD
Tem várias formas de modularizar essas funções.. no curso vamos ver várias delas xD

**Comment by llmdev** [comment]
Demoro mano vou aguardar para ver as aulas.. pode fechar vlw

**Comment by fdaciuk** [comment]
Legal @llmdev! =)
Só detalhe: se a issue estiver resolvida, você mesmo pode fechar, ok? =)
