### ISSUE TITLE
[M2#A24] - Dúvida sobre concorrência

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#76]
Professor o senhor comenta sobre concorrência nessa aula, poderia explicar melhor o que seria ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucianobarauna! Concorrência é exatamente o que diz a palavra: quando dois ou mais <qualquer coisa> concorrem entre si por um objetivo em comum.

Imagine, por exemplo, o seguinte código:

```js
let counter = 0

function incrementCounter () {
  counter++
  return counter
}
```

Veja que a função `incrementCounter` modifica um valor externo a ela. 
Agora imagine essa função na sua aplicação. Se qualquer código depender de valores seguidos para a variável `counter` (0, 1, 2), você pode chamar essa função, que vai incrementar a variável `counter` e retornar o valor dela.

Agora, o que aconteceria se, em dois lugares diferentes do meu código, eu executar essa mesma função?

Imagine o botão 1 e o botão 2, os dois executam essa função. Ao clicar no botão 1, eu vou incrementar o valor de `counter` de 0 para 1. E se continuar clicando, ele vai continuar incrementando. E enquanto eu preciso de valores que são seguidos um do outro, fica tudo certo.

O problema acontece quando eu clico no botão 2: - ou você pode ter uma outra ação assíncrona, um request, por exemplo, que executa também essa função - o que vai acontecer?

O mesmo `counter` será incrementado! Isso é um exemplo de concorrência! Eu tenho mais de um lugar no meu código alterando **a mesma** variável!

Existem momentos que é exatamente isso que você quer: fazer com que um valor seja único, então você usa algo nesse sentido. Mas quando você quer que cada botão incremente seu próprio contador, mas eles não o fazem, isso gera concorrência entre eles, causando efeitos colaterais inesperados no seu código =)

**Comment by lucianobarauna** [comment]
Então não entendi errado. Ajudou muito a explicação vlw professor !
