### ISSUE TITLE
[M1#A40] - Erro: No 'Access-Control-Allow-Origin' header is present on the requested resource...

### ISSUE THREAD

**Issue by angelomedeiros** [da2k/curso-reactjs-ninja#77]
Problema com o CORS. Como proceder com a solução do problema?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @angelomedeiros! CORS sempre precisa ser liberado no servidor onde você está tentando fazer o request. Onde você está tentando fazer requests que está dando esse problema?

**Comment by angelomedeiros** [comment]
Tô seguindo exatamente o fluxo da aula. Solicito acesso a API do github, e quando pesquiso o nome do usuário, o console apresenta o erro:

> Failed to load https://github.com/angelomedeiros: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by angelomedeiros** [comment]
Descobri o erro @fdaciuk ! Eu tinha digitado o caminho errado 😅😅
Mas passei um tempão pesquisando a respeito do CROS, pelo menos valeu o aprendizado kkk

**Comment by fdaciuk** [comment]
Ah, agora ficou claro haha =)
