### ISSUE TITLE
Duvida sobre o surso

### ISSUE THREAD

**Issue by gmferreir1** [da2k/curso-reactjs-ninja#78]
Boa noite Fernando Daciuk !
Não sei bem se o lugar certo para postar isso mas me desculpe caso for um erro.
Faço seu curso de Javascript Ninja e estou querendo muito fazer o React visto que estou gostando muito da sua didática e domínio do que passa. 
Já programo com Vue e estou fazendo esses cursos para me aperfeiçoar mais, pois sempre ponho em duvida minha programação, sempre acho que estou fazendo errado e que posso melhorar mais. Você acha que consigo me virar no curso de React sendo que ja programo com Vue e tenho uma pequena base em JS. Ou você acha melhor eu terminar o de JS Ninja e depois partir para React ?
Ou fazer os dois em paralelo :) ?
Obrigado !!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gmferreir1! Não acho que seja especificamente necessário terminar o de JS para começar o de React. Se você já tem uma base legal da linguagem, pode começar o de React sem problemas. Se perceber que está sentindo dificuldade em algo específico da linguagem, pode voltar ao curso de JS ir fazendo os dois em paralelo, se tiver tempo disponível pra isso =)

**Comment by gmferreir1** [comment]
@fdaciuk o React é muito diferente do VUE ?
A minha base de Vue irá ajudar no aprendizado ?
Vai ser passado conceitos sólidos, tdd e resource  ?

**Comment by fdaciuk** [comment]
Sim, o React é diferente do Vue =)
O React traz muitos conceitos de programação funcional, mas não se preocupe, pois esses conceitos são todos passados no curso.

Inclusive as novidades da linguagem (ES6+) também são explicadas bem a fundo, conforme vamos usando.

E você vai aprender não só React, mas algumas ferramentas que compõe o seu ecossistema como Redux e React Router, vai aprender sobre testes, renderização do lado do servidor, configuração do webpack, tanto para dev como otimizações para ambiente de produção, etc =)

O curso é completo mesmo =)

**Comment by gmferreir1** [comment]
Fiz a inscrição, rsrs. Vou te incomodar muito agora. Abraço !!

**Comment by fdaciuk** [comment]
Legal! Espero que curta =)
