### ISSUE TITLE
M2#16 Erro ao Instalar o Lint

### ISSUE THREAD

**Issue by gmferreir1** [da2k/curso-reactjs-ninja#79]
Bom dia,
Ocorre um erro quando instalo o Lint, quando executo o servidor e atualizo a pagina aparece o seguinte erro:
Cannot find module "/var/www/html/Curso React Ninja/src/index"

client?843a:75 Cannot read property 'concat' of undefined
 @ multi main

Mas quando removo as configurações do Lint no webpack.config ele funciona normalmente.
Meu Dev Dependencies esta assim

"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "react-hot-loader": "^3.1.3",
    "standard": "^10.0.3",
    "standard-loader": "^5.0.0",
    "webpack": "^1.15.0",
    "webpack-dev-server": "^1.16.5",
    "webpack-validator": "^3.0.0"
  },

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gmferreir1! Consegue subir seu projeto aqui no GitHub pra eu dar uma olhada?

**Comment by gmferreir1** [comment]
Professor Daciuk, removi a pasta node modules e instalei tudo de novo e funcionou. Vai entender :)
Obrigado.
@fdaciuk

**Comment by fdaciuk** [comment]
Pode acontecer, principalmente se mudou a versão do NPM/Yarn que vc está utilizando =)

**Comment by gmferreir1** [comment]
Estou usando o npm 4.2.0 e yarn 1.3.2
Acho que vou começar a usar o yarn ele me parece bem mais rapido, de qualquer form obrigado professor, estou adorando o curso, muito bommm
@fdaciuk

**Comment by fdaciuk** [comment]
Massa \o/
