### ISSUE TITLE
React + Webpack #09

### ISSUE THREAD

**Issue by danlaurent** [da2k/curso-reactjs-ninja#8]
Fiz toda a configuração do Hot Loader porém ele não atualiza a página.

No console exibe as mensagens:

[HMR] Waiting for update signal from WDS...
ReactDOM.js:75 Download the React DevTools for a better development experience: https://fb.me/react-devtools
client?843a:37 [WDS] Hot Module Replacement enabled.
2client?843a:37 [WDS] App updated. Recompiling...
client?843a:37 [WDS] App hot update...
2client?843a:37 [WDS] App updated. Recompiling...
client?843a:37 [WDS] App hot update...
2client?843a:37 [WDS] App updated. Recompiling...
client?843a:37 [WDS] App hot update...

Reparei que no vídeo, no seu console são exibidas algumas mensagens a mais, do only-dev-server e do log-apply-result.

**Comment by fdaciuk** [comment]
Fala @danlaurent! Consegue subir o projeto em um repositório no GitHub pra eu ver como está o código todo? =)

**Comment by danlaurent** [comment]
Fala @fdaciuk! Ta aqui o repositório https://github.com/danlaurent/treino-react.git

**Comment by fdaciuk** [comment]
Cara, o erro provavelmente está acontecendo por causa da versão do webpack que você está usando. A versão 2 ainda está em beta, e a configuração é diferente da versão 1.
Tente trocar pela versão mais recente, dentro da v1 que deve funcionar certinho =)

Se não rolar, posta o erro aqui =)

**Comment by danlaurent** [comment]
É, era a versão mesmo! Agora funcionou.

Estranho, no vídeo você usou a v2 não?

Bom, valeu @fdaciuk !

**Comment by fdaciuk** [comment]
Show \o/
Nós usamos a v1: https://github.com/fdaciuk/workflow-reactjs/blob/master/package.json#L14

Aqui o código do boilerplate que estamos usando: https://github.com/fdaciuk/workflow-reactjs
