### ISSUE TITLE
M1#42

### ISSUE THREAD

**Issue by gmferreir1** [da2k/curso-reactjs-ninja#80]
Boa noite Professor,
Fiquei em duvida na parte do handleSearch :(
Posso pensar que isso seria uma comunicação de Filho para Pai ou seja quando o componente Search
dispara o evento keyup chamando o handleSearch ele vai se comunicando para cima ? 
Ou ao contrario quando é montado o componente ja fica implicito essa props handleSearch que foi definida no componente Pai app.js ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gmferreir1! Pense nos componentes como simples funções. Em React, a maior parte dos componentes não guardam estado. Todo o estado desses componentes é passado via props (que seriam como argumentos de funções mesmo).

Então, sempre que você precisa executar uma função em um componente filho, onde o estado que será alterado está no componente pai, você cria a função no componente pai, onde essa função vai alterar o estado, e então passa a função como referência para o filho, para que o filho, no momento necessário, execute a função =)

Era isso que você queria saber?

**Comment by gmferreir1** [comment]
Sim. Acho que eu entendi certo então.  :)
Obrigado professor.
Desculpe tantas dúvidas.

Em 18 de dez de 2017 9:05 PM, "Fernando Daciuk" <notifications@github.com>
escreveu:

**Comment by fdaciuk** [comment]
Legal @gmferreir1! Fique tranquilo, dúvidas servem para serem resolvidas ;)
