### ISSUE TITLE
M2#A51 - Problema Watch

### ISSUE THREAD

**Issue by sergiohpreis** [da2k/curso-reactjs-ninja#81]
Olá, tudo bem ?

Configurei tudo igual a aula, mas ao executar o `yarn lint:watch`, ele executa o lint, porém não funciona o watch :/.
Segue o meu repositório com o código:

https://github.com/sergiohpreis/curso-react-ninja

@fdaciuk

**Comment by sergiohpreis** [comment]
Era um problema no `cb()` do spawn, resolvido rs

**Comment by fdaciuk** [comment]
Opa, legal! Que bom que deu certo =)
