### ISSUE TITLE
Versão da dependência do extract-text-webpack-plugin

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#82]
Boa tarde Fernando no módulo 2 aula 33 com a versão mais recente do extract-text-webpack-plugin quebra a aplicação, usei a versão 1.0.1 e funcionou, só para deixar registrado ;)

valeu parabéns pelo curso

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Obrigado pela dica! Vou adicionar isso no arquivo de dependências =)
Muito obrigado por reportar :D

**Comment by fdaciuk** [comment]
Feito! Obrigado novamente! :heart:
