### ISSUE TITLE
Módulo 2 Aula 51 "Error: spawn yarn ENOENT" 

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#84]
Módulo 2 Aula 51

Para quem estiver utilizando Windows e ocorrer esse erro "Error: spawn yarn ENOENT" ao tentar executar o lint:watch : 

deve ir no arquivo `gulpfile.js` e adicionar ao objeto passado como parâmetro para a função spawn a propriedade  `shell: true`  ficando :

`const cmd = spawn('yarn', ['lint'], { stdio: 'inherit', shell: true })`

Pelo que eu pesquisei rapidamente este erro ocorre devido as diferenças em que os sistemas operacionais  lidam com comandos shell

@fdaciuk

**Comment by fdaciuk** [comment]
Boa @willianrssi!
Eu havia sugerido, no nosso boilerplate, o [uso do `cross-spawn`](https://github.com/fdaciuk/workflow-reactjs/blob/master/gulpfile.js#L6-L7), mas com essa propriedade resolve de forma mais elegante =)

Muito obrigado =)
