### ISSUE TITLE
Instalação Webpack server - Aula 10

### ISSUE THREAD

**Issue by Zarppa** [da2k/curso-reactjs-ninja#85]
Boa tarde,

Fui fazer a instalação conforme recomendado na primeira "Aula do futuro", seguindo suas dependências e apresentou o seguinte erro:

G:\desenvolvimento\projetos\reactjs\react-webpack>npm i --save dev webpack-dev-server@1
npm WARN react-webpack No description
npm WARN react-webpack No repository field.
npm WARN react-webpack No license field.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.2: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-01-27T19_14_02_660Z-debug.log

Como posso proceder? 

Obrigado. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Zarppa! Conseguiu resolver? =)

Parece que faltou apenas o traço entre `save` e `dev`, foi isso mesmo? :D

**Comment by Zarppa** [comment]
tirei as instalações que tinha feito e fiz de novo e deu certo.

**Comment by fdaciuk** [comment]
Show de bola =)
Que bom que funcionou \o/

Qualquer dúvida, só avisar! :D
