### ISSUE TITLE
Módulo 2 Aula 85: Regex do minChunks no Windows

### ISSUE THREAD

**Issue by willianrssi** [da2k/curso-reactjs-ninja#86]
Boa noite Fernando, na regex do minChunks​ tive que modifica-la para:

/node_modules\\react(-dom)?/.test(resource)

dai sim funcionou no Windows, mas deixei :

/node_modules(\\|\/)react(-dom)?/.test(resource)

isso deve funcionar em ambos os SOs certo ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @willianrssi! Olhando agora, pode fazer sentido sim.

Eu só trocaria o `(\|/)` por `[\\\/]`, pelo seguinte: Os parênteses fazem uma captura, não necessária nesse caso. E, para usar uma barra, ou uma contra-barra em regex, elas precisam ser escapadas. O escape é feito com uma contra-barra. 

Então para poder usar tanto uma barra, quanto uma contra-barra, você pode usar qualquer uma das regex abaixo:

```js
/node_modules(\\|\/)react(-dom)?/.test(resource)/
/node_modules(?:\\|\/)react(-dom)?/.test(resource)/ // -> O `?:` é só para não fazer a captura, somente "agrupar"
/node_modules[\\\/]react(-dom)?/.test(resource)/
```

Qualquer um dos 3 deve funcionar para qualquer SO =)

**Comment by fdaciuk** [comment]
Vou deixar a issue aberta, pois outras pessoas podem ter o mesmo problema, assim fica fácil achar =)

**Comment by willianrssi** [comment]
Valeu Fernando ,
me esqueci de inserir os trechos como código e o github desconsiderou o escape na hora que publiquei,
só vi agora, não sabia que ele fazia isso kkkkkkkk, eu utilizei a primeira opção que você sugeriu

mais uma vez obrigado por sempre estar disposto em nos ajudar

**Comment by fdaciuk** [comment]
haha! Sem problemas meu caro =)

Qualquer dúvida, só avisar :D
