### ISSUE TITLE
CSS do Componente no Storybook

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#87]
Escreva aqui sua dúvida

@fdaciuk

Não estou conseguindo fazer o componente vim estilizado que nem mostra na aula M2#A44.

https://github.com/hjdesigner/curso-react-ninja/tree/storybook

branch storybook

**Comment by fdaciuk** [comment]
Fala @hjdesigner! =)

Nesse caso específico, o problema é que você está usando _CSS Modules_ no componente, e o storybook não funciona, por default, com _CSS Modules_, então você precisa configurar o `webpack.config` do storybook pra funcionar =)

A ideia seria basicamente iterar pelos loaders do storybook, encontrar o loader de CSS e, ao encontrá-lo, iterar pelos `loaders` dessa entrada do loader de CSS, pra adicionar o parâmetro `modules` ao CSS loader =)

Pra começar, você pode usar ir debugando com `console.log`. Podemos usar o `find` para encontrar primeiro o loader de CSS. No arquivo `storybook/webpack.config.js`, adicione o seguinte código, antes do `return newConfig`:

```js
  const cssLoader = newConfig.module.loaders.find((loader) => {
    return loader.test.test('actions.css')
  })
  console.log(cssLoader)
```

O método `find` funciona parecido com o `filter`, com a diferença que, ao invés de retornar um `array`, ele vai retornar o elemento do array que casar com o que foi retornado na função.

No caso, nós iteramos por cada `loader` em `newConfig.module.loaders`, e usamos a propriedade `test` - que é uma regex, e regex tem um método `test` - para verificar se essa entrada `test` casa com o arquivo `actions.css` (poderia ser qualquer nome que termine com `.css`, só pra testar o _match_ da regex.

Quando você executar `npm run storybook`, vai ver no console o objeto do loader de CSS. Pra mim apareceu assim:

```js
```

**Comment by fdaciuk** [comment]
Fala @hjdesigner! =)

Nesse caso específico, o problema é que você está usando _CSS Modules_ no componente, e o storybook não funciona, por default, com _CSS Modules_, então você precisa configurar o `webpack.config` do storybook pra funcionar =)

A ideia seria basicamente iterar pelos loaders do storybook, encontrar o loader de CSS e, ao encontrá-lo, iterar pelos `loaders` dessa entrada do loader de CSS, pra adicionar o parâmetro `modules` ao CSS loader =)

Pra começar, você pode usar ir debugando com `console.log`. Podemos usar o `find` para encontrar primeiro o loader de CSS. No arquivo `storybook/webpack.config.js`, adicione o seguinte código, antes do `return newConfig`:

```js
  const cssLoader = newConfig.module.loaders.find((loader) => {
    return loader.test.test('actions.css')
  })
  console.log(cssLoader)
```

O método `find` funciona parecido com o `filter`, com a diferença que, ao invés de retornar um `array`, ele vai retornar o elemento do array que casar com o que foi retornado na função.

No caso, nós iteramos por cada `loader` em `newConfig.module.loaders`, e usamos a propriedade `test` - que é uma regex, e regex tem um método `test` - para verificar se essa entrada `test` casa com o arquivo `actions.css` (poderia ser qualquer nome que termine com `.css`, só pra testar o _match_ da regex.

Quando você executar `npm run storybook`, vai ver no console o objeto do loader de CSS. Pra mim apareceu assim:

```js
{ test: /\.css?$/,
  include: 
   [ '/media/storage/code/hjdesigner-curso-react-ninja/workflow-reactjs' ],
  loaders: 
   [ '/media/storage/code/hjdesigner-curso-react-ninja/workflow-reactjs/node_modules/@kadira/storybook/node_modules/style-loader/index.js',
     '/media/storage/code/hjdesigner-curso-react-ninja/workflow-reactjs/node_modules/@kadira/storybook/node_modules/css-loader/index.js?importLoaders=1',
     '/media/storage/code/hjdesigner-curso-react-ninja/workflow-reactjs/node_modules/postcss-loader/index.js' ] }
```

Veja que é exibido o caminho completo de cada loader. Olhando os diretórios, podemos ver que temos os seguintes loaders:
**style-loader**, **css-loader** e **postcss-loader**.

O **css-loader** está com um parâmetro `importLoaders=1`. O que nós precisamos fazer é apenas adicionar, nessa linha onde aparece o loader de CSS, o `?modules`. Como a linha já contém uma _query string_ iniciada com `?`, os próximos parâmetros devem ser adicionados com `&`. A linha do CSS loader deve ficar assim:

```js
'/media/storage/code/hjdesigner-curso-react-ninja/workflow-reactjs/node_modules/@kadira/storybook/node_modules/css-loader/index.js?importLoaders=1&modules'
```

Vamos ver como resolver isso. Já sabemos como encontrar o loader de CSS. Só usar o método `test()` na propriedade `test` do objeto do loader. Se bater/casar com qualquer string que termine com `.css`, esse é o nosso cara! Como temos que manter o array de loaders, podemos usar o `map`, que itera por um array, mas retorna um novo array, do mesmo tamanho, mas transformado, alterando qualquer entrada do array. 

Então, para continuar com o mesmo resultado, o código vai ficar assim (coloque esse código no lugar do `console.log`):

```js
  newConfig.module.loaders = (newConfig.module.loaders || []).map((loader) => {
    return loader
  })
```

Isso só vai iterar pelos loaders e retornar os mesmos loaders em um novo array. Agora podemos começar a brincar. Vamos fazer alguma coisa somente se o loader for o de CSS:

```js
  newConfig.module.loaders = (newConfig.module.loaders || []).map((loader) => {
    if (loader.test.test('actions.css')) {
      // aqui nós temos loader de CSS
    }
    return loader
  })
```

Pronto! Com esse `if`, nós conseguimos fazer alguma coisa só com o loader de CSS. Os outros loaders ele vai apenas retornar como estão. Vamos ver como vai ficar pra adicionar o `modules`:

```js
  newConfig.module.loaders = (newConfig.module.loaders || []).map((loader) => {
    if (loader.test.test('actions.css')) {
      return {
        ...loader, // copiamos todo o loader
        loaders: loader.loaders.map() // aqui vamos iterar pelos loaders (style, css e postcss) do loader de CSS padrão do storybook
      }
    }
    return loader
  })
```

Veja que agora precisamos iterar a propriedade `loaders` do loader de CSS. Vamos fazer isso:

```js
  newConfig.module.loaders = (newConfig.module.loaders || []).map((loader) => {
    if (loader.test.test('actions.css')) {
      return {
        ...loader,
        loaders: loader.loaders.map((internalLoader) => {
          return internalLoader.includes('/css-loader') 
            ? `${internalLoader}&modules` 
            : internalLoader
        })
      }
    }
    return loader
  })
```

Pronto! O código acima apenas testa, dentro dos loaders, qual deles inclui a palavra `/css-loaders`. O que tiver essa string incluída, nós simplesmente adicionamos `&modules` ao final dele. Se for qualquer outro loader, só retorna como está =)

---

É meio chatinho de fazer essas configurações na mão, mas, por outro lado, o storybook nos dá a liberdade de configurarmos exatamente da forma que nossa aplicação está funcionando =)

Espero que tenha ficado claro! Qualquer dúvida, só avisar =)

**Comment by hjdesigner** [comment]
Ele da erro no spread operator, SyntaxError: Unexpected token ...Loader,
Não conseguir achar a solução na internet.

**Comment by fdaciuk** [comment]
Opa! Atualiza seu repositório pra eu dar uma olhada.. era pra ter funcionado, eu testei o código à partir desse seu =)

**Comment by hjdesigner** [comment]
Atualizei o repositório 8)

**Comment by fdaciuk** [comment]
Oi @hjdesigner! Agora vi aqui =)
Provavelmente você está usando o Node.js na versão 6 ou inferior, correto?
Bom, tem duas formas de resolver:
- Ou você atualiza a versão do Node para a mais recente;
- Ou você pode escrever o código assim:

```js
  newConfig.module.loaders = (newConfig.module.loaders || []).map((loader) => {
    if (loader.test.test('actions.css')) {
      return Object.assign({}, loader, {
        loaders: loader.loaders.map((internalLoader) => {
          return internalLoader.includes('/css-loader')
            ? `${internalLoader}&modules`
            : internalLoader
        })
      })
    }
    return loader
  })
```

**Comment by hjdesigner** [comment]
Achei melhor atualizar a versão do Node.js, ele estava na 6.11 rsrs
Funcionou perfeito, obrigado pela ajuda. 8)

**Comment by fdaciuk** [comment]
Show! Qualquer coisa, só avisar =)
