### ISSUE TITLE
Pasta node_modules?

### ISSUE THREAD

**Issue by reglachek** [da2k/curso-reactjs-ninja#88]
Eu gostaria que alguém pudesse me dizer de onde veio essa pasta node_modules, eu já entendi mais ou menos pra que ela serve, mas ainda não entendi como ela apareceu aqui no meu diretório.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @reglachek! Eu acabei não entrando muito no assunto, mas basicamente é o seguinte: quando você usa o NPM para instalar algum pacote, ele centraliza os pacotes instalados localmente nesse diretório `node_modules`.

Esses pacotes (ou módulos) surgiram pela necessidade de uso do Node.js (por isso o nome `node_modules` =)

No caso, o NPM é o gerenciador de pacotes do Node.js - ou ao menos começou assim - e hoje ele centraliza qualquer tipo de pacote escrito em JavaScript, tanto para o Node.js, quando para aplicações frontend, como estamos vendo com React no curso =)

Esses pacotes ficam referenciados no arquivo `package.json` que nós criamos. Nesse `package.json` ficam listados o nome do pacote, e a versão utilizada no momento em que ele foi instalado.

Isso facilita para que, quando você for tentar rodar o mesmo projeto em outro computador, ou outra pessoa quiser rodar seu projeto, você não precisa compartilhar o projeto + a pasta `node_modules`, que vai estar cheia de coisas por conta dos módulos: você só precisa compartilhar o projeto + o `package.json`.

Quando você - ou outro dev - executarem `npm install` no diretório que contém o arquivo `package.json`, automaticamente todos os pacotes listados nesse arquivo serão baixados e colocados nesse diretório `node_modules` =)

Ficou claro? =)

**Comment by reglachek** [comment]
@fdaciuk, entendi perfeitamente, eu fiz o teste criando um diretório qualquer e colocando somente o `package.json`  e rodando `npm install`, funcionou perfeitamente. Muito obrigado.

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar =)
