### ISSUE TITLE
Erro ao rodar clone da aplicação

### ISSUE THREAD

**Issue by reglachek** [da2k/curso-reactjs-ninja#89]
Quando dei `npm start` na aplicação desse repositório: https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

Ele me mostrou o seguinte erro:

```
$ npm start

> @ start C:\Users\Wallace\Documents\Curso React\teste
> yarn dev

'yarn' n▒o ▒ reconhecido como um comando interno
ou externo, um programa oper▒vel ou um arquivo em lotes.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ start: `yarn dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'yarn dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yarn dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Wallace\Documents\Curso React\teste\npm-debug.log
```

Dai eu rodei o comando `npm install` e depois de 2 minutos mais ou menos ele mostrou o seguinte erro:

```
$ npm i
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! cb() never called!
```

Dai fui no link que ele me mostrou e rodei o comando que ele pediu no caso o `npm ls gulp-util` e novamente me mostrou esse erro:

```
$ npm ls gulp-util
C:\Users\Wallace\Documents\Curso React\teste
`-- (empty)

npm ERR! code 1
```
Não sei mais o que fazer, alguém pode me dar uma luz ?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @reglachek! Esse repositório está atualizado com as versões mais recentes das libs mostradas no curso.
Acabei não prevendo esses problemas com versões no início do curso, então estou mapeando as versões certinhas e criando diretórios específicos para cada ponto do curso, para ficar fácil acompanhar com as dependências certas e não dar esse tipo de erro.

Por enquanto, sugiro você ir criando seu próprio boilerplate, instalando as bibliotecas que eu vou mostrando durante o curso, mas seguindo esse arquivo que tem as versões exatas necessárias para não dar erro: https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md

Em breve eu vou conseguir disponibilizar todas as versões certinhas para esse primeiro módulo, que é onde estão acontecendo esses probelmas, ok? =)

Desculpe por isso, mas qualquer dúvida, pode contar comigo =)

**Comment by fdaciuk** [comment]
Oi @reglachek! Já deixei as versões corretas de cada aula em um diretório separado! Você encontra tudo aqui:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

Se ainda tiver problemas, só avisar =)
