### ISSUE TITLE
[m01] Githubapp

### ISSUE THREAD

**Issue by RodrigoWP** [da2k/curso-reactjs-ninja#9]
Boa tarde @fdaciuk 

Dúvida, no projeto githubapp eu vi que você criou um styles.css no diretorio dist, mas no webpack.config não tem nenhuma saída pra css.. é isso mesmo? Ele não será sobre escrito ao gerar o bundle?

Valeu!

**Comment by fdaciuk** [comment]
Opa! Fala @RodrigoWP =)
Então, esse CSS eu decidi deixar direto no diretório final pra não mexer em configuração nesse primeiro momento.

No módulo 2 nós vamos entrar mais a fundo em configurações, e vamos ver algumas formas pra usar CSS em aplicações React =)

Mas com certeza o ideal seria deixar o CSS no `src`, para não depender do `dist` e deixar que esse diretório seja sempre gerado junto com o bundle. =)

**Comment by RodrigoWP** [comment]
@fdaciuk  Foi o que pensei, perguntei só por curiosidade hehe Valeu

**Comment by fdaciuk** [comment]
Sem problemas =)

É que o foco do módulo 1 é somente o React mesmo. Fazemos algumas configurações básicas somente pra poder usar ES6 e JSX, mas no módulo 2 vamos entrar um pouco mais nessa parte de configurações :smiley: 

Qualquer dúvida só avisar =)
