### ISSUE TITLE
Módulo 2 aula 81

### ISSUE THREAD

**Issue by lucianobarauna** [da2k/curso-reactjs-ninja#90]
Professor não estou conseguindo rodar o storybook no windows.

![image](https://user-images.githubusercontent.com/1054454/36331586-a711f5a4-1355-11e8-8c3e-fb1cce32ac37.png)

Fui tentar achar uma solução sozinho e encontrei essa aqui:
https://github.com/webpack/webpack/issues/1465

mais não deu certo por que ele estorou erro pelo webpack agora, creio que esse erro seja pq estou utilizando a versão nova a 2 até agora.

Até debuguei ele pensando que estava vindo vazio e não tá mais continua com o mesmo erro, se liga;

```
 newConfig.module.preLoaders = (newConfig.module.preLoaders || []).concat(preloaders)
 console.log('OLHA AQUI --- ', newConfig.module.preLoaders)
```

![image](https://user-images.githubusercontent.com/1054454/36331755-43f866f0-1356-11e8-9f1f-65ecdef7b403.png)

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @lucianobarauna! Consegue subir o projeto aqui no GH e passar o link pra eu ver?

**Comment by lucianobarauna** [comment]
https://github.com/lucianoMeusCursos/ReactNinjaExample/tree/master/my-examples/m02/batch-updates

**Comment by fdaciuk** [comment]
Ah, agora entendi o problema =)
O que acontece é o seguinte: essa versão do storybook ainda usa a v1 do webpack, por isso vc tem que passar `undefined` para o `use` e usar `loader` no lugar =)

No caso, o `newConfig.module.rules` ainda não existe na v1 do webpack, apenas da v2 pra frente =)

Então o objeto correto seria: `newConfig.module.loaders` :)

**Comment by fdaciuk** [comment]
Oi @lucianobarauna! Vou fechar a issue, mas se você ainda estiver com esse problema, reabrimos ok? =)
