### ISSUE TITLE
Erro no Eslint

### ISSUE THREAD

**Issue by augustoar** [da2k/curso-reactjs-ninja#91]
Oi @fdaciuk estou usando o eslint Standard no VSCode, e na aula _**M1#A16 - A prop "children"**_, ele acusa a seguinte mensagem de erro:

```'children' is missing in props validation (react/prop-types)```

Só que essa mensagem só acontece no VSCode, não aparece no terminal nenhum erro, então procurei na internet sobre isso, e achei a seguinte solução:

```Button.propTypes = { children: React.PropTypes.element.isRequired }```

Neste caso, o Button é o nome do componente á ser exportado, depois disso, o erro sumiu, pelo que eu entendi, a propriedade **children** faz parte dos proto types do React, seria isso mesmo?

**Comment by augustoar** [comment]
Então o erro no VSCode sumiu, mas agora dá erro no console do navegador:

```Warning: Failed prop type: Invalid prop `children` of type `string` supplied to `Button`, expected a single ReactElement.```

Mesmo assim, ele continua renderizando o componente na página, não entendi o que pode ser o erro.

**Comment by augustoar** [comment]
Já consegui resolver e entender o que significa, na aula **_M1#A27 - propTypes_**

**Comment by fdaciuk** [comment]
Opa, legal que deu certo =)
Qualquer dúvida só avisar :D
