### ISSUE TITLE
M1#A40

### ISSUE THREAD

**Issue by dizwes** [da2k/curso-reactjs-ninja#92]
Boa tarde!

Gostaria de tirar uma dúvida, por que utilizado o import do ajax com '@fdaciuk/ajax' ?

Desde já agradeço!

@fdaciuk

**Comment by fdaciuk** [comment]
Opa @dizwes! Não entendi muito bem a dúvida xD
Todo import, quando você faz referência à dependência, ou seja, quando você passa o caminho da dependência, ele precisa ser feito dentro de uma string =)
