### ISSUE TITLE
Problema para rodar Webpack

### ISSUE THREAD

**Issue by LeoRedin** [da2k/curso-reactjs-ninja#93]
Boa tarde! Tudo blz?

Procurei nas issues mas não encontrei uma resposta.

Seguinte, fiz a config do webpack e do package.json igual está no Módulo 2, Vídeo 2. Porém, ao rodar o comando webpack recebo o seguinte aviso : 
The CLI moved into a separate package: webpack-cli.

Rodei o webpack como no vídeo e também como estava no github para tentar solucionar problema de dependência, mas ainda assim sem sucesso.

Poderia me auxiliar?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @LeoRedin! Você diz do módulo 02 mesmo, ou do módulo de React + Webpack?

Se for do módulo de React + Webpack, você pode dar uma olhada [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), aqui mesmo no repositório do curso, que eu vou centralizar todas as versões exatas das dependências usadas no momento que o curso estava sendo desenvolvido, para que você consiga acompanhar sem maiores problemas =)

Qualquer coisa me avise =)

**Comment by raphaelanjos1** [comment]
@fdaciuk  Tive o mesmo problema que o @LeoRedin ! Eu instalei o webpack@1 somente para dev, e na hora do npm i -g webpack, esqueci de passar a versão 1! Tive de refazer, mas deu certo! 

Esse arquivo das versões salva muito!

**Comment by fdaciuk** [comment]
Show @raphaelanjos1! Com o decorrer do curso, vamos fazendo as atualizações necessárias, mas para acompanhar é necessário instalar essas versões específicas =)

Que bom que funcionou \o/

**Comment by LeoRedin** [comment]
Buenas! Esse mesmo! O React + Webpack.

Testei com a versão que estava disponível nesse link que enviou e não consegui.

Vou tentar usar a mesma solução do Raphael, acredito ter esquecido de passar a versão 1 tbm quando fiz a instalação.

Se resolver volto aqui para dar um retorno ou se o erro persistir volto igual haha

**Comment by LeoRedin** [comment]
Funcionando perfeitinho o comando webpack.

Realmente fiz todas as instalações usando webpack@1, acredito que eu tenha esquecido de alguma vez o @1 .

Vlw pela ajuda!

**Comment by fdaciuk** [comment]
Legal @LeoRedin! Qualquer coisa só avisar =)
