### ISSUE TITLE
Faltou a linha da instalação do react-hot-loader

### ISSUE THREAD

**Issue by duduindo** [da2k/curso-reactjs-ninja#94]
No título do **Vídeo 10** faltou:
`npm install --save-dev react-hot-loader@3.0.0-beta.2`

https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#v%C3%ADdeo-10

@fdaciuk

**Comment by fdaciuk** [comment]
Opa, valeu @duduindo! Mas essa dependência nós adicionamos na aula `#08`, já com a versão exata, por isso não adicionei no arquivo de dependências =)

Mas obrigado por reportar! Sempre que tiver algo a acrescentar, pode abrir issue! Valeu mesmo :D
