### ISSUE TITLE
Webpack Server não é reconhecido

### ISSUE THREAD

**Issue by LeoRedin** [da2k/curso-reactjs-ninja#95]
Opa! Beleza?

Eu recentemente fechei uma issue sobre gerar o bundle, que o problema estava na versão do webpack e consegui resolver. Segui o vídeo usando a instalação npm install --save-dev webpack-dev-server@1 pra continuar com a mesma versão. Mas me deparei com o seguinte erro ao tentar executar o comando : webpack-dev-server OU webpack-dev-server@1 : 

' webpack-dev-server' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @LeoRedin! É preciso instalar ele como global também, para usar como comando direto no terminal =)
Faça o mesmo que o `webpack`: Instale com `npm i -g webpack-dev-server@1` que vai funcionar =)

**Comment by fdaciuk** [comment]
Oi @LeoRedin! Vou fechar a issue, mas se você ainda estiver com esse problema, reabrimos ok? =)

**Comment by andrelucasmartins** [comment]
Oi @fdaciuk! Estou com um problema simular, tento rodar o webpack a partir prompt com o comand npm run build. Mas, ele só me retorna sem o mesmo erro.

PS C:\Users\usuario\Desktop\game-simulado> npm run build

> game-simulado@1.0.0 build C:\Users\usuario\Desktop\game-simulado
> webpack --config webpack.config.js

C:\Users\usuario\Desktop\game-simulado\webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { ��c
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Users\usuario\Desktop\game-simulado\node_modules\webpack\bin\convert-argv.js:97:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! game-simulado@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the game-simulado@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usuario\AppData\Roaming\npm-cache\_logs\2018-06-11T16_38_17_638Z-debug.log


E este é meu package.json

{
  "name": "game-simulado",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "dev": "webpack-dev-server",
    "prod": "npx webpack --config ./config/webpack.prod",
    "build": "webpack --config webpack.config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "André L. M. Ezequiel",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0"
  },
  "devDependencies": {
    "lodash": "^4.17.10",
    "webpack": "^3.12.0",
    "webpack-cli": "^3.0.3"
  }
}
 
E este é meu webpack.config.js

const path = require('path');

const config = {
  entry: './src/app.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  }
};

module.exports = config;

Alguém poderia me dar alguma ajuda com esse problema. Desde já agradeço toda ajuda que puderem me dar.

**Comment by fdaciuk** [comment]
Oi @andrelucasmartins! O seu problema parece ser de encoding do arquivo. Dá uma olhada se ele está salvo como `utf-8` (provavelmente é alguma configuração do editor de textos que você está usando) =)

**Comment by andrelucasmartins** [comment]
Oi, Fernando! Obrigado, verifiquei que todo projeto está em code uft-16 no editor. Agora vou modificar para ver se tudo está funcionando normalmente.

Obter o Outlook para Android<https://aka.ms/ghei36>



De: Fernando Daciuk
Enviado: segunda-feira, 11 de junho 14:56
Assunto: Re: [da2k/curso-reactjs-ninja] Webpack Server não é reconhecido (#95)
Para: da2k/curso-reactjs-ninja
Cc: André Ezequiel, Mention


Oi @andrelucasmartins<https://github.com/andrelucasmartins>! O seu problema parece ser de encoding do arquivo. Dá uma olhada se ele está salvo como utf-8 (provavelmente é alguma configuração do editor de textos que você está usando) =)

**Comment by andrelucasmartins** [comment]
Muito obrigado Fernando, funcionou e gerou o bundle.js e tudo está funcionando.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fdaciuk** [comment]
Legal @andrelucasmartins =)

**Comment by feelipefreitas** [comment]
Caso esteja no Windows tente executar dessa maneira: .\node_modules\.bin\webpack
