### ISSUE TITLE
[M1#A11] - Renderizando componentes com funções puras

### ISSUE THREAD

**Issue by raphaelanjos1** [da2k/curso-reactjs-ninja#96]
Oi @fdaciuk , estou com um problema:

ao renderizar meu código, recebo o seguinte retorno no navegador: Olá [object Object] [object Object] [object Object]

Só alterei app.js e title.js, não mexi em webpack (tanto que não acusa nenhum erro), acho que é algo similar ao próprio video, em um momento perto do fim você tenta fazer uma alteração e o hot loader não altera. Segue o código do meu app.js e title.js, respectivamente:

App.js:

`'use strict'

import React from 'react'
import Title from './Title'

const App = React.createClass({
  render: function () {
    return (
      <div className='container'>
        <Title name='Raphael' lastname='Anjos' />
      </div>
    )
  }
})

export default App`

Title.js:

`'use strict'

import React from 'react'

const Title = (name, lastname) => (
    <h1>Olá {``${name} ${lastname}``}</h1>
)

Title.defaultProps = {
    name: ' Sem',
    lastname: ' Sobrenome'
}

export default Title`

Fico no aguardo da sua ajuda para prosseguir com o curso, que por sinal está ótimo!

@fdaciuk

**Comment by raphaelanjos1** [comment]
Quando trabalho passando props como parâmetro e chamando props.name, funciona normalmente...

**Comment by raphaelanjos1** [comment]
@fdaciuk , descobri o meu erro:

estava passando const = Title = (name, lastname) ao invés de ({name, lastname}).

faltaram as chaves.

**Comment by fdaciuk** [comment]
Oi @raphaelanjos1! Legal que conseguiu resolver =)
Qualquer dúvida, só avisar =)
