### ISSUE TITLE
MRW#02 - Erro Comando Webpack

### ISSUE THREAD

**Issue by samuelbrehm** [da2k/curso-reactjs-ninja#97]
Estou usando o MacOS e instalei o webpack global, porém o comando "webpack" não faz nada no terminal. Não gerou os arquivos que vc mostra. Como fazer?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! Eu deixei mapeadas as dependências [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) para que você consiga acompanhar o andamento do curso sem maiores problemas :)

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! Vou fechar a issue, mas se você ainda estiver com esse problema, reabrimos ok? =)

**Comment by samuelbrehm** [comment]
Ok

**Comment by fdaciuk** [comment]
Só pra vc saber: deixei os exemplos mostrados nas aulas separados por aula, um em cada diretório. 
Assim fica fácil acompanhar cada dependência usada nos momentos certos. Está tudo aqui:
https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/react-webpack

**Comment by samuelbrehm** [comment]
O problema é que o comando webpack apresenta uma lista de opções e não gera o bundle.
<img width="1638" alt="captura de tela 2018-03-24 as 10 55 16" src="https://user-images.githubusercontent.com/6319555/37864795-2027082c-2f52-11e8-9b4e-c8a7bd7c5639.png">

**Comment by fdaciuk** [comment]
Oi @samuelbrehm! O problema é que você está usando uma versão do webpack diferente da que foi usada na aula =)

Como comentei acima, dá uma olhada [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), que ele contém as versões exatas das dependências que você precisa instalar, inclusive o webpack =)

**Comment by fdaciuk** [comment]
Oi @luizcrpereira! Sim =)
Você deve ter instalado a versão 4 do webpack. Remova essa versão e o webpack-cli, e instale as versões conforme [esse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) =)
