### ISSUE TITLE
M02 | Configuração webpack do hot-loader e node server

### ISSUE THREAD

**Issue by tiagosatur** [da2k/curso-reactjs-ninja#98]
Olá Fernando, beleza? 

Estou tendo erro para terminar a configuração do webpack com hot-loader e node server.
Está dando Cannot GET / em localhost 3000

O repositório está aqui: https://bitbucket.org/tiagosatur/reactninja

npm i em m02-webpack/a02-config-webpack

Como resolvo isso?

Outra dúvida, é se eu utilizar as dependências mais recentes, uso as mesmas configs?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @tiagosatur! Vou baixar o projeto e dar uma olhada pra entender o problema =)

Sobre as dependências: provavelmente não. Algumas coisas normalmente se mantém, mas as versões "maiores" sempre têm _breaking changes_.

Durante o curso vamos ver várias atualizações para as ferramentas usadas.

Provavelmente teremos um módulo específico, apenas pra falar sobre algumas atualizações mais específicas =)

**Comment by fdaciuk** [comment]
Oi @tiagosatur! Tem dois problemas aí:
Primeiro é o `contentBase` no seu `server.js`. Esse cara diz para o `webpack-dev-server` à partir de onde ele deve servir os arquivos. Como no seu diretório `dist` você não tem nenhum `index.html`, então nada é servidor à partir dali, e o servidor retorna `Cannot GET /`.

Para resolver, isso, você pode apenas mover o arquivo `src/index.html` para `dist/index.html`.

---

Mas, como o diretório `dist` normalmente é gerado automaticamente, você pode ter um problema se ele for removido - é muito comum remover diretórios gerados. Exemplo da `node_modules` =)

Então a segunda solução seria:
- Mova o arquivo `src/index.html` para a raiz do seu diretório, onde vc executa o `npm start`;
- Remova o `contentBase` do `server.js`.

Fazendo isso, o código vai ficar igual o exibido na aula, e vai funcionarn corretamente =)

**Comment by tiagosatur** [comment]
@fdaciuk Consegui resolver com a ajuda de um amigo. Faltava criar um arquivo index.html na pasta dist/ . contentBase: "dist/", em server.js e if (module.hot) {module.hot.accept()} em src/index.js pro hotloader funcionar nessa versao do webpack.

**Comment by fdaciuk** [comment]
Era isso mesmo @tiagosatur! Só atente para a questão da `dist` que eu comentei acima =)

Qualquer coisa, só avisar =)
