### ISSUE TITLE
Sass Storybook

### ISSUE THREAD

**Issue by hjdesigner** [da2k/curso-reactjs-ninja#99]
Escreva aqui sua dúvida

@fdaciuk
Se usar o sass-loader tem como fazer o storybook compilar o sass?

**Comment by fdaciuk** [comment]
Tem sim @hjdesigner! É só adicionar o loader do sass no arquivo de configuração do webpack do storybook =)

**Comment by hjdesigner** [comment]
Consegui. \o/

Adicionei essa linha no storybook.config.js

newConfig.module.rules.push(common.cssLoader)

**Comment by fdaciuk** [comment]
Isso ae! =)

Qualquer dúvida, só avisar! =)
